### ISSUE TITLE
Unsubscribe behaviour improvement

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#2358] opened 2016-08-21 00:31 UTC
What type of report is this: Enhancement?

## Description:
When the unsubscribe link is clicked by a lead, they are stamped with Do Not Contact and never receive any more emails.

Unsubscribe currently can't just remove them from a specific list, or even all lists, but only globally and permanently.

This makes it hard to have more than a global mailing list relationship with your leads/contacts. They might only want to be removed from a specific list, but that's not possible, so if the relationship is developing along, it can harm the future potential of the relationship by giving them no options other than to never receive emails again. Also if a lead isn't ready to subscribe one month,  maybe six months later they are, but it's not possible to let them opt back in without having to manually change things. 

## Request

* It would be great if there was a simple per list and global unsubscribe option that did not tag them with Do Not Contact.
* Ideally this would be deliverable to the lead via a form/landing page when they click the unsubscribe button, they can then be offered choice for a specific list to be removed from, or all lists.
* I'm not proposing to remove the Do Not Contact/Supression List feature. We have strict anti spam legislation here in Aus(via our privacy laws), maybe similar to US for practical spam control purposes. I feel there has to be a finer balance between offering the lead control about emails they receive without having to make it the option so global and final.

Without this, it makes lead self service difficult and hampers scalability of Mautic within an organisation, especially as the organisation itself grows. It would be a shame if missing something like like led to an organisation outgrowing Mautic.

**Comment by escopecz** [comment] 2016-08-22 07:25
Seems like duplicate of https://github.com/mautic/mautic/issues/822

**Closed by escopecz** 2016-08-22 07:25 UTC
