### ISSUE TITLE
By deleting leads the count continues, it is not removed

### ISSUE THREAD

**Issue by juizmill** [mautic/mautic#1378] opened 2016-01-24 22:26 UTC
I removed all leads, and made a new import, however the system kept the old leads count, cleared all caches and yet remained the count.

![screen shot 2016-01-24 at 19 19 52](https://cloud.githubusercontent.com/assets/1959742/12539403/288b773c-c2d0-11e5-88cc-880027b17276.png)

**Comment by npracht** [comment] 2016-01-26 21:02
Hi @juizmill ,

How often are running your CRON? One of them is concerning lists and until the CRON runs it can keeps the previous result.

N.

**Comment by juizmill** [comment] 2016-03-02 13:11
Hi @npracht ,

It is running within one minute.

**Comment by escopecz** [comment] 2016-05-02 13:12
I tested this issue:
1. In the List table I have 1 list with 4 leads.
2. I clicked on the lead count (4) and it opened the lead table with 4 leads who belong to the list.
3. I removed one of them.
4. I run `app/console mautic:lists:update` command
5. I check the list table. Now there are only 3 leads at the same list.

So it works for me. Try to run the command manually. Maybe the issue is in your cron setup? Also check that the list doesn't have any filters. Because the leads could be added again according to the list filters.

I'll close this issue now since it's working for me. But feel free to comment with a new information and I'll reopen it again.

**Closed by escopecz** 2016-05-02 13:12 UTC
Labels: Pending Feedback
