### ISSUE TITLE
Widgets Broken in Mautic 3.1

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9126] opened 2020-08-26 12:01 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Since updating to version 3.1.0 I can no longer add new widgets to the dashboard. See logs below. This has been tried on a few different widgets and they all produce the same error.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 
| Browser | 
 
### Log errors
[2020-08-26 12:57:04] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO ma_widgets (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, type, width, height, cache_timeout, ordering, params) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2020-08-26 11:57:04", 1, "admin", "2020-08-26 11:57:04", null, null, null, null, null, "Downloads in time", "asset.downloads.in.time", 100, 330, null, null, "a:0:{}"]:  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO ma_widgets (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, type, width, height, cache_timeout, ordering, params) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2020-08-26 11:57:04\", 1, \"admin\", \"2020-08-26 11:57:04\", null, null, null, null, null, \"Downloads in time\", \"asset.downloads.in.time\", 100, 330, null, null, \"a:0:{}\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment] 2020-09-02 12:04
I think this has to do with an issue with my SQL migration.

**Comment by mabumusa1** [comment] 2020-09-18 10:39
@colourfulowl please include steps to reproduce? I created a widget and it worked as expected, is there anything else I should do to get the same issue

**Comment by RCheesley** [comment] 2020-09-18 12:30
@colourfulowl can you reproduce this on a non-Bitnami instance? We are seeing several issues with Bitnami-based installations and like @mabumusa1 I am unable to reproduce this in Mautic 3.1.  I think therefore this is an environment-specific issue and will close the issue accordingly - may be worth posting this on the Bitnami support forum.

**Closed as completed by RCheesley** 2020-09-18 12:30 UTC
Labels: regression, needs-triage, widget
