### ISSUE TITLE
Editing company causes 500 error due to companyfax field being unknown

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8485] opened 2020-02-29 15:58 UTC
## Bug Description

Bug identified when editing a company in Mautic 3 (see UAT card [here](https://trello.com/c/VP0QdDNx/275-companies-edit-company-ensure-all-core-fields-are-editable)) - throws the following error:

500 Internal Server Error - An exception occurred while executing 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?' with params ["11", 5]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list'

| Q   | A 
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Edit a company
2. Save
3. Error occurs as above
 
### Log errors
500 Internal Server Error - An exception occurred while executing 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?' with params ["11", 5]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list'

**Comment by RCheesley** [comment] 2020-02-29 15:58
![](https://github.trello.services/images/mini-trello-icon.png) [Companies > Edit company - ensure all core fields are editable](https://trello.com/c/VP0QdDNx/275-companies-edit-company-ensure-all-core-fields-are-editable)

**Comment by RCheesley** [comment] 2020-02-29 15:59
![](https://github.trello.services/images/mini-trello-icon.png) [Companies > Change company owner](https://trello.com/c/1HFDznGg/276-companies-change-company-owner)

**Comment by escopecz** [comment] 2020-03-05 12:17
I cannot replicate this on my local. But I can see the error at https://m3.mautibox.com/3.x/s/companies/edit/3. My guess is that this is related to https://github.com/mautic/mautic/issues/8522. The `companyfax` field exists twice.

**Comment by alanhartless** [comment] 2020-03-06 00:10
I think this has something to do with Mautibox. I've hit it several times there. https://acquia.slack.com/archives/CPVGZE516/p1583451178138400 But it's not 100% sure if this is something in M3 triggering this or something with Mautibox.

**Comment by alanhartless** [comment] 2020-03-06 16:01
Confirmed that this is caused by the duplicate custom fields from https://github.com/mautic/mautic/issues/8522. Will close this as Mautibox will be fixed when that issue is fixed.

**Closed by alanhartless** 2020-03-06 16:01 UTC
Labels: Bug, Mautic 3
