### ISSUE TITLE
Ability to configure multilingual unsubscribe message

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4711] opened 2017-08-23 06:53 UTC
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
For international companies, it would be great to have the ability to configure multilingual unsubscribe message on the unsubscribe page.

**Comment by escopecz** [comment] 2017-08-23 07:31
Probably duplicate of https://github.com/mautic/mautic/issues/873

**Closed by escopecz** 2017-08-23 07:31 UTC

**Comment by npracht** [comment] 2017-08-23 07:56
Indeed, i didn't find it. Thanks !
