### ISSUE TITLE
500 Internal Server Error (2.15.0)

### ISSUE THREAD

**Issue by kjonix123** [mautic/mautic#7061] opened 2018-12-27 11:24 UTC
I suddenly got 500 error on my Mautic installation running on 2.15.0

Last error:
[2018-12-27 00:31:02] mautic.ERROR: Segment QB: Query Exception: An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, HVLWYmbE.lead_id AS HVLWYmbE_lead_id FROM mauxw_leads l LEFT JOIN mauxw_lead_lists_leads HVLWYmbE ON HVLWYmbE.lead_id = l.id and (HVLWYmbE.leadlist_id = 7) WHERE ((l.email IS NOT NULL) AND (l.email <> '')) AND (HVLWYmbE.lead_id IS NULL)) sss':  Prepared statement needs to be re-prepared {"query":"SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, HVLWYmbE.lead_id AS HVLWYmbE_lead_id FROM mauxw_leads l LEFT JOIN mauxw_lead_lists_leads HVLWYmbE ON HVLWYmbE.lead_id = l.id and (HVLWYmbE.leadlist_id = 7) WHERE ((l.email IS NOT NULL) AND (l.email <> '')) AND (HVLWYmbE.lead_id IS NULL)) sss","parameters":{"ShMPcxbK":null}} []
[2018-12-27 00:31:02] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, HVLWYmbE.lead_id AS HVLWYmbE_lead_id FROM mauxw_leads l LEFT JOIN mauxw_lead_lists_leads HVLWYmbE ON HVLWYmbE.lead_id = l.id and (HVLWYmbE.leadlist_id = 7) WHERE ((l.email IS NOT NULL) AND (l.email <> '')) AND (HVLWYmbE.lead_id IS NULL)) sss':  Prepared statement needs to be re-prepared (uncaught exception) at /home/yogynkva/marketing.yogy.no/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `mautic:segments:update` [] []

**Comment by heathdutton** [comment] 2018-12-27 14:00
I believe what you are experiencing is a MySQL issue, not a bug with Mautic. It may have only just shown itself due to memory consumption during/after upgrade or optimizations to segment queries. 

A few solutions: https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared/4381155#4381155

**Comment by npracht** [comment] 2019-01-03 08:52
Please see Heath comment. As far as it is a configuration issue, i'll close the issue from github where we store only bug reports. Feel free to join the chat on Slack or Discord.

**Closed by npracht** 2019-01-03 08:52 UTC
