### ISSUE TITLE
Email Spooling Error with Amazon SES

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2567] opened 2016-09-20 10:47 UTC
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Choose to send Emails in Queue mode
2. Emails 
 
### Log errors: 

I had been getting the below error while choosing to Queue Emails to be sent through Amazon SES. 

What happens is that it seems that the same email is sent several times, causing some leads to be marked as "Bounced" due to "tried sending email more than 3 times and it's not delivered" while actually Emails was not sent to Amazon to be delivered.

[13-Sep-2016 18:56:12 UTC] PHP Warning:  rename(/home/egyprene/cache/mautic/default/43CLeH9f2k.message.sending,/home/egyprene/cache/mautic/default/43CLeH9f2k.message.finalretry): No such file or directory in /home/egyprene/public_html/mautic/app/bundles/EmailBundle/Command/ProcessEmailQueueCommand.php on line 99
[13-Sep-2016 18:56:12 UTC] PHP Warning:  file_get_contents(/home/egyprene/cache/mautic/default/43CLeH9f2k.message.finalretry): failed to open stream: No such file or directory in /home/egyprene/public_html/mautic/app/bundles/EmailBundle/Command/ProcessEmailQueueCommand.php on line 101
[13-Sep-2016 18:56:12 UTC] PHP Warning:  unlink(/home/egyprene/cache/mautic/default/43CLeH9f2k.message.finalretry): No such file or directory in /home/egyprene/public_html/mautic/app/bundles/EmailBundle/Command/ProcessEmailQueueCommand.php on line 127
[13-Sep-2016 19:02:39 UTC] PHP Warning:  unlink(/home/egyprene/cache/mautic/default/3EKovScrSd.message.sending): No such file or directory in /home/egyprene/public_html/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 171

Any idea what's going wrong and how to fix it?

**Comment by wittwerch** [comment] 2016-09-20 14:33
I had the same problem. In my environment it was caused by the email job running multiple times in parallel due to the bad locking. Should be fixed with #2453

**Comment by iadj** [comment] 2016-09-25 20:26
@amagdy3 @wittwerch Interesting. Do the same issues occur when using Amazon SES's SMTP details as `Other SMTP Service` rather than the `Amazon SES` option in the configuration?

**Comment by amagdy3** [comment] 2016-09-25 21:21
@iadj Actually using the Amazon SES option never worked for me. I'm using "Other SMTP Service" and inserting Amazon SES details.

**Comment by amagdy3** [comment] 2016-09-30 07:55
Just as an update. @wittwerch's #2453 have fixed that. 

I also managed to modify server configuration to be able to use "Amazon SES" other than "Other SMTP Service" by disabling "SMTP Security Restrictions". 

Now, the challenge is enhancing speed through sending with Amazon API other than SMTP server which is extremely slow with mautic.

**Comment by escopecz** [comment] 2016-09-30 08:25
Thanks for the info! I'll close this issue then.

**Closed by escopecz** 2016-09-30 08:25 UTC
