### ISSUE TITLE
Emails > Theme > Content and Body Froala Editor is gone on v2.3

### ISSUE THREAD

**Issue by Getron** [mautic/mautic#3036] opened 2016-12-01 08:58 UTC
| Bug report | 

## Description:
If i try to edit my Emails like in v2.2.1, and i go to Emails - Theme, select the theme, and the "Content" tab is not there, is not showing. It has just the text body, but not the editor.

I have tryed many times to update, manualy, and automaticaly, but no luck, updating works ok, no problems there, but the "Content" tab is not showing, and not able to editing with froala editor like in v2.2.1, just with the Builder, but, Builder give me not all the options like editing in "Content" tab in v2.2.1, for example, a code view switching, and back to WYSIWYG editor.

I know there is a new Code mode, but, this is not so great, because of missing editor there. It would be great, if Code mode would have the editor implemented on it, and able to use both, code mode manualy, and, if needed, editor to.

## If a bug:

| Mautic version 2.3 | 
| PHP version 7.0.x | 

### Steps to reproduce:
1. Create a email in v2.2.1
2. Update to v2.3
3. "Content" tab is missing, and no WYSIWYG editor.
 
### Log errors: 

There are no errors given.

**Comment by escopecz** [comment] 2016-12-01 09:50
This is duplicate of https://github.com/mautic/mautic/issues/3032, let's discuss it at one place.

**Closed by escopecz** 2016-12-01 09:50 UTC
