### ISSUE TITLE
Update 2.16.1  broke Segments by tag

### ISSUE THREAD

**Issue by gitlares** [mautic/mautic#8609] opened 2020-03-30 20:47 UTC
Mautic version 2.16.1 
7.2
ALL

The ability to create tag-based segments does not work after this update.

Specifically when we include the "exclude" filter the segment stops working.

For example, making a segment where all contacts that have the VIP tag are included but exclude those that have the VEGETARIAN tag is impossible.

In the previous version this kind of filter works without any problem

**Comment by npracht** [comment] 2020-03-31 06:50
Do you have an error message in logs please ?

**Comment by npracht** [comment] 2020-03-31 09:28
Introduced by https://github.com/mautic/mautic/pull/7424, we'll check it.

**Comment by martinstr** [comment] 2020-04-01 09:11
Same problem here

**Comment by danielberndt** [comment] 2020-04-06 10:36
We also just upgraded to 2.16.1 and found this broke our campaigns as the underlying segments are now empty due to this bug.
As we're still quite new to mautic: what's the usual timeline for releasing fixes to such issues? Or is feasible/possible to somehow downgrade to 2.16.0?

**Comment by silsha** [comment] 2020-04-06 11:26
@danielberndt I have just downgraded one of our customer installations to 2.16.0 because of this bug.

You can save your config, and the folders "media", "plugins" and "themes", then upload the 2.16.0 files and restore your backup files.

Here are the paths to the important files/folders:

- /path/to/mautic/app/config/local.php
- /path/to/mautic/media
- /path/to/mautic/themes
- /path/to/mautic/plugins

It would be best to make a full backup of the files and database in case something goes wrong.

**Comment by npracht** [comment] 2020-04-06 11:34
It'll be fixed in 2.16.2

**Comment by danielberndt** [comment] 2020-04-06 11:46
thanks @silsha, good to know that downgrading is an option!

@npracht thanks! Since we need to find a solution rather soon, what's the timeline for 2.16.2? Will it be days or more likely weeks?

**Comment by npracht** [comment] 2020-04-06 12:04
Today or tomorrow latest ;)

**Closed** 2020-04-07 16:07 UTC
Labels: Bug, Regression

**Comment by dennisameling** [comment] 2020-04-07 20:04
2.16.2-beta is now released, please help us by testing if this issue is indeed resolved: https://github.com/mautic/mautic/releases/tag/2.16.2-beta

Two ways to test:
1. Clone your production environment, change the update stability to "beta" and you should be able to see the new version:
![image](https://user-images.githubusercontent.com/17739158/78714115-98a13100-791b-11ea-85fb-4b64eb8dc7a6.png)
2. Do a clean install with the ZIP file provided in https://github.com/mautic/mautic/releases/tag/2.16.2-beta and test if the issue has gone now

This helps us to be 100% sure that the issue is indeed fixed now. Thanks in advance! :)

**Comment by danielberndt** [comment] 2020-04-08 09:06
I just performed the update. 

Running `php app/console mautic:segments:update` leads to this error:

![Screenshot 2020-04-08 at 11 03 57](https://user-images.githubusercontent.com/856386/78765945-f5870080-7988-11ea-955a-761ca401c78e.png)

Not sure whether it's related or not.

**Comment by dennisameling** [comment] 2020-04-09 15:17
@danielberndt Thanks for testing! Did you clear your cache after updating? The error you're seeing might be related to https://github.com/mautic/mautic/issues/8098 and didn't come up in our testing AFAIK. 

I'm putting the final 2.16.2 release on hold now until either:
- @danielberndt has confirmed whether the issue above is a recurring issue for him or can be solved by clearing cache/changing permissions
- or @gitlares @silsha @martinstr could help us by testing if the original issue (segments by tag) is resolved for them now.

Thanks in advance for your help!

**Comment by silsha** [comment] 2020-04-09 15:19
I'll try it out later. I'll get back to you with results.

**Comment by danielberndt** [comment] 2020-04-09 15:24
okay nice, I can confirm that clearing the cache (I did both, `php app/console cache:clear` and `rm -rf app/cache/*`) seems to have worked! 👍

![image](https://user-images.githubusercontent.com/856386/78911589-ca82d680-7a86-11ea-89e9-bf7a7bd98810.png)

**Comment by dennisameling** [comment] 2020-04-10 14:09
Just tested by doing the following to be 100% sure this is fixed now:
- Do a clean installation of 2.16.1
- Create a new contact with the tag "demo"
- Create another contact, now with tag "demo2"
- Create a segment, filter on:
  - tags, "including", "demo"
  - tags, "excluding", "demo2"
![Screenshot from 2020-04-10 16-04-20](https://user-images.githubusercontent.com/17739158/78996547-1ac06e00-7b45-11ea-8e05-f3db90c573ce.png)
- Run `app/console mautic:segments:update`, the segment will still have 0 contacts.

Now, check again with 2.16.2-beta and repeat the steps above. Running `app/console mautic:segments:update` will show 1 contact :tada: 

I'm going ahead with the 2.16.2 release now. Thanks everyone for reporting and testing
