### ISSUE TITLE
Number fields aren't visible in form editor

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11310] opened 2022-07-03 20:37 UTC
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

I tested this with M4.12 and M4.4 (other servers). With polish language you can't make number type field. And already made fields are invisible in form editor. Maybe the problem also arises with another languages.

The problem may be in the language, where in Mautic "phone number" are translated as "numer", and also "number" field may be translated as "numer".

I mention polish contributors: @patrykgruszka @tomekkowalczyk, would you like check it?

### How can we reproduce this issue?

Step 1: Set up language as polish
Step 2: Go to field editor and check existing number fields and try make new number field.

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-07-06 10:03
I think that this is a duplicate of an existing issue which is impacting all custom fields: #11299 so closing this to centralise the discussion there.

**Closed as completed by RCheesley** 2022-07-06 10:03 UTC
Labels: bug, duplicate

**Comment by automatyzuj** [comment] 2022-07-06 12:35
Hello @RCheesley I think that they are completely different topics.

I wrote about fields in form builder, not custom fields. And IMHO the problem is due to the identical translation of the field type name.

**Comment by automatyzuj** [comment] 2022-07-08 22:57
Hi @RCheesley this fixes it in my issue:.
in /translations/pl_PL/CoreBundle/messages.ini you should change to line 385 from "mautic.core.type.tel="Numer" to mautic.core.type.tel="Numer telefonu" (in line 383 is also; mautic.core.type.number="Numer")

After this all works fine.

If you want you can add this PR to Mautic repository.

cc: @escopecz 

Regards.

**Comment by RCheesley** [comment] 2022-07-11 08:28
Thanks, translations are all done on transifex.com so any changes will need to be made there.

**Comment by automatyzuj** [comment] 2022-07-11 14:12
Done.
