### ISSUE TITLE
Problem in docker-image mautic/mautic:v4 (Sep 5, 2022 at 2:03 pm)

### ISSUE THREAD

**Issue by rogerio-pereira** [mautic/mautic#11446] opened 2022-09-07 21:09 UTC
### Mautic Version

4.4.x series

### PHP version

I don`t know

### What browsers are you seeing the problem on?

Not relevant

### What happened?
Error in migration

Same issue on mautic/docker-mautic repository
https://github.com/mautic/docker-mautic/issues/234

### How can we reproduce this issue?

Using Docker-compose
Image mautic/mautic:v4 (updated on Sep 5, 2022 at 2:03 pm)

The problem happens when running migrations:
1. with flag `MAUTIC_RUN_MIGRATIONS=true` 
2. or without the flag when setting up database in mautic (first screen on web installer)

### Relevant log output

```shell
In AbstractMySQLDriver.php line 79:

  An exception occurred while executing 'ALTER TABLE leads ADD generated_emai
  l_domain VARCHAR(255) AS (SUBSTRING(email, LOCATE("@", email) + 1)) COMMENT
   '(DC2Type:generated)';
              ALTER TABLE leads ADD INDEX `generated_email_domain`(generated_
  email_domain)':

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '@' in 'generated co
  lumn function'


In Exception.php line 18:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '@' in 'generated co
  lumn function'


In PDOConnection.php line 141:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '@' in 'generated co
  lumn function'
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-09-23 11:41
Closing as a duplicate of the existing image in the Docker repository.

**Closed as not planned by RCheesley** 2022-09-23 11:41 UTC
Labels: bug, needs-triage
