### ISSUE TITLE
Google defines Mautic as a malicious program and blocking

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#9539] opened 2020-12-26 08:35 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Google defines Mautic as a malicious program and blocks  the container with the tag mautic.

In addition to prohibiting Google from scanning the tag, can something be done so that Google does not consider the tracking code of the Mautic malware?

| Q   | A
| --- | ---
| Mautic version | 3.2.1

### Steps to reproduce
1. place the standard tracking code in the Google Manager tag container
2. after some time, Google will send an alert report by email
 
![Google_tag_block_mautic](https://user-images.githubusercontent.com/42971248/103148125-9151da00-476d-11eb-9503-07ed9968b5e5.png)

in Mautic I see a lot of hits from Google. He scanned
![Google_tag_hit_in_mautic](https://user-images.githubusercontent.com/42971248/103148213-73d14000-476e-11eb-86cc-483c6b2f22bf.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by saitanay** [comment] 2020-12-29 03:11
Can be merged/closed as duplicate of https://github.com/mautic/mautic/issues/7524

The best path forward is creating a GTM community template for Mautic 
From google on https://support.google.com/tagmanager/answer/6328489?hl=en 
`The best way to avoid malware issues is to use the tag templates built into Google Tag Manager. Tag manager supports a wide number of 3rd party tag templates, and many more templates are shared in the Community Template Gallery.`

There is an initiative underway to do this @ https://forum.mautic.org/t/create-a-google-tag-manager-template-for-mautic/11568 . If you can contribute to building the community template, please add to the thread [here](https://forum.mautic.org/t/create-a-google-tag-manager-template-for-mautic/11568).

**Comment by npracht** [comment] 2020-12-29 05:16
Closing in favour of https://github.com/mautic/mautic/issues/7524

**Closed as completed by npracht** 2020-12-29 05:16 UTC
Labels: duplicate
