### ISSUE TITLE
Editing a segment associated to campaigns (emails) causes 500 error 

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8501] opened 2020-03-02 13:19 UTC
## Bug Description
I came across this while working with segments. In my case I edited a segment, then went back to the overview and this 500 error was thrown almost immediately.

I think it's related to the fact that this segment is in use with two campaigns - I did not see it on other segments that were not 'in use'.

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Edit a segment (I edited https://m3.mautibox.com/3.x/s/segments/edit/1)
2. Save or cancel 
3. Go back to the overview page and the error will be shown - if not click on the 'campaign share' tab.
 
### Log errors
```
[2020-03-02 13:15:52] mautic.CRITICAL: Uncaught PHP Exception BadMethodCallException: "Undefined method 'getCampaignsSegmentShare'. The method name must start with either findBy, findOneBy or countBy!" at /var/app/current/code/pulls/3.x/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php line 235 {"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'getCampaignsSegmentShare'. The method name must start with either findBy, findOneBy or countBy! at /var/app/current/code/pulls/3.x/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:235)
[stacktrace]
#0 /var/app/current/code/pulls/3.x/app/bundles/LeadBundle/Segment/Stat/SegmentCampaignShare.php(53): Doctrine\\ORM\\EntityRepository->__call('getCampaignsSeg...', Array)
#1 /var/app/current/code/pulls/3.x/app/bundles/LeadBundle/Controller/AjaxController.php(858): Mautic\\LeadBundle\\Segment\\Stat\\SegmentCampaignShare->getCampaignsSegmentShare('1', Array)
#2 /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Controller/AjaxController.php(131): Mautic\\LeadBundle\\Controller\\AjaxController->getCampaignShareStatsAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#3 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('getCampaignShar...', Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#4 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#5 /var/app/current/code/pulls/3.x/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(108): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#6 /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Controller/AjaxController.php(109): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticLeadBundl...', Array)
#7 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#8 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#9 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/app/current/code/pulls/3.x/app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/app/current/code/pulls/3.x/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/app/current/code/pulls/3.x/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/app/current/code/pulls/3.x/app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/app/current/code/pulls/3.x/app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/app/current/code/pulls/3.x/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/app/current/code/pulls/3.x/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/app/current/code/pulls/3.x/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#18 /var/app/current/code/pulls/3.x/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#19 /var/app/current/code/pulls/3.x/index.php(6): require_once('/var/app/curren...')
#20 {main}
"} 
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-03-02 13:19
![](https://github.trello.services/images/mini-trello-icon.png) [Segments > Filters using a single field from core fields (please test each type of field and each qualifier available)](https://trello.com/c/LFF54ONE/136-segments-filters-using-a-single-field-from-core-fields-please-test-each-type-of-field-and-each-qualifier-available)

**Comment by escopecz** [comment] 2020-03-05 12:26
@kuzmany would you mind to take this one? It was introduced with the new feature merged to 2.16.0 that you worked on.

**Comment by kuzmany** [comment] 2020-03-05 17:36
At the moment. Can't reproduce it

**Comment by escopecz** [comment] 2020-03-06 10:37
@RCheesley I can't reproduce on the segment you linked either. Can you make a screen share?

**Comment by RCheesley** [comment] 2020-03-19 10:49
Sorry missed this notification :blush: 

https://youtu.be/hob7lBJLY88

**Comment by alanhartless** [comment] 2020-04-14 19:26
@kuzmany based on the trace in the description, it does look like this method is not defined on the CampaignRepository
https://github.com/mautic/mautic/blob/3.x/app/bundles/LeadBundle/Segment/Stat/SegmentCampaignShare.php#L53

**Comment by dongilbert** [comment] 2020-04-14 19:28
Confirmed the issue here, and the method `getCampaignsSegmentShare` is not defined.

Possibly due to a bad merge, not sure.

**Comment by alanhartless** [comment] 2020-04-14 21:20
Ah yes, seems that method was removed somewhere around when 2.16 was merged into 3.x because it's in the original PR. https://github.com/mautic/mautic/pull/7285/files#diff-4a74fb01118346a8216c86b9fcf1534eR741 I'll PR back that method.

**Comment by dongilbert** [comment] 2020-04-14 21:59
linked PR is merged

**Closed by dongilbert** 2020-04-14 21:59 UTC
Labels: Bug, Mautic 3
