### ISSUE TITLE
Google Tag Manager flagged mautic tracking code by Malware scanning system

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#13523] opened 2024-03-06 09:47 UTC
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The Tag Manager has blocked the Mautic tracking code. I am attaching a screenshot of the notification letter
![OtAvWOpToi](https://github.com/mautic/mautic/assets/42971248/420d4fdb-7e53-4aab-a3b7-7ef7b798438b)

### How can we reproduce this issue?

Step 1: Place the Mautic tracking code in GTM and wait for it to be blocked

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment] 2024-04-22 13:57
Are you sure this email is real (not spam)?

**Comment by directpromo** [comment] 2024-04-22 17:50
> Are you sure this email is real (not spam)?
real 100%  
![изображение](https://github.com/mautic/mautic/assets/42971248/26073c7d-af4f-4416-a2b6-800390d90372)

**Comment by andersonjeccel** [comment] 2024-04-22 20:59
This issue seems old
https://github.com/mautic/mautic/issues/9539
https://github.com/mautic/mautic/issues/7524

**Comment by RCheesley** [comment] 2024-04-29 16:18
Hi @directpromo how are you embedding Mautic within your GTM? Are you using a template or just dropping it in with custom HTML?

**Comment by directpromo** [comment] 2024-04-29 16:56
Hi @RCheesley . Custom HTML. The standard tracking code from Mautic. Without changes.

**Comment by RCheesley** [comment] 2024-04-30 14:20
I think that is where the issue is. We never got to writing an actual template to add to the community library.

There are some already provided though: https://forum.mautic.org/t/create-a-google-tag-manager-template-for-mautic/11568 but you should review the code behind the templates and ensure you're happy with them, before you use them.

It'd be nice if we could create a template - an 'official' Mautic one - but we don't quite have the resources for that at this time.

I'm going to close this issue as it's addressed by using one of the available templates, feel free to raise a forum issue if there are any problems going forward.

**Closed as not planned by RCheesley** 2024-04-30 14:20 UTC
Labels: bug, tracking
