### ISSUE TITLE
Using Sparkpost API for sending mail

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#1488] opened 2016-03-01 08:42 UTC
It would be awesome if there would be support for the Sparkpost API in Mautic like there is for Mandrill.

With [Mandrill's anouncement from last week](http://blog.mandrill.com/important-changes-to-mandrill.html) in mind people could start moving away from Mandrill to another transactional emailprovider. 
Sparkpost has an API and can make use of webhooks. Since last week they even offer 100.000 emails per month for their free accounts.

**Comment by paulocastellano** [comment] 2016-03-07 19:44
+1

**Comment by germanotm** [comment] 2016-04-01 19:39
+1

**Comment by Xavivico** [comment] 2016-04-03 19:40
+1

**Comment by wittwerch** [comment] 2016-04-12 11:47
I've implemented the webhook to handle bounce messages. Unfortunately, we discovered that we can't use Sparkpost for our use case, so the implementation still uses the smtp interface. So maybe somebody can use the code and complete it. For example protecting the callback with authentication is missing.

https://gist.github.com/wittwerch/6c223a102b9c4427f50e65f7521aab14

**Comment by germanotm** [comment] 2016-04-12 15:43
Tanks wittwerch.

After see this issue i realised that sendgrid has a free plan up to 12,000 email per month.
I am using it now, so if anyone here do not intend continue using mandrill i recomend take a look at sendgrid. Its already integrated with mautic and working fine.

**Comment by wderuijter** [comment] 2016-04-13 06:32
@germanotm I'm not sure but I think Mautic's Sendgrid setting just uses the regular SMTP connection, not the API. 
I thought so far only the Mandrill setting used an API with webhooks for hard bounces, soft bounces, and some other events.

**Comment by zstephen** [comment] 2016-04-14 11:44
@wderuijter you're correct about the Sendgrid connection using SMTP, for shared hosts like GoDaddy and others this prevents them from being able to use Sendgrid because SMTP(across all the common ports) is blocked.

Sendgrid is keen to pick up those users that have left Mandrill, they're specifically [marketing](https://sendgrid.com/blog/how-to-migrate-from-mandrill-to-sendgrid/) to that exact pain point. There is a whole lot of info there about the differences between their APIs, if I knew how to modify APIs I'd help. Maybe there are others who also have this issue, and also some API skills?

I'm going to get what info I can about their API in how it's similar to Mandrill and try to find out about Mautic talking HTTPS via Sendgrid's API instead of SMTP.

**Comment by jjroelofs** [comment] 2016-04-19 09:17
+1

**Comment by versadial** [comment] 2016-04-21 21:00
+1

Hoping someone can finish this. Sparkpost appears to be a pretty good alternative to Mandrill and the other ones out there. 100k monthly and a 10k daily limit is pretty impressive and I think fits right into Mautics clientele.

**Comment by yepher** [comment] 2016-04-26 16:43
Hi I am from SparkPost. One of the users of this project directed me to this ticket. 

I would like to let you know that SparkPost has a Slack channel dedicated to answering questions from developers to help them solve problems.

You can join that Slack group here: http://slack.sparkpost.com

Reading through this ticket it was not clear to me what the current issue is. I do see that in https://gist.github.com/wittwerch/6c223a102b9c4427f50e65f7521aab14 it is processing the response inline. Generally SparkPost expects the receiving system to queue the events and return and then process the events in another thread.

Not sure if it is helpful (or you probably already know) but there is sample code in http://github.com/SparkPost

I hope to see you on the SparkPost Slack group so we can help you get your questions answered quickly and your integration completed.

I highlighted this issue to our dev-relations team so maybe someone else will pop in with some additional advice.

**Comment by zstephen** [comment] 2016-04-26 19:55
thanks @yepher !

**Comment by yepher** [comment] 2016-04-26 20:32
Yes SparkPost support HTTPS. You can send email with the Transmission API.

You can view the documentation here:
     https://developers.sparkpost.com/api/#/reference/transmissions

Let me know if you have more questions.

**Comment by jfgrissom** [comment] 2016-04-27 16:09
I need the integration for sending through the Sparkpost API, so I'll join the cause on this one.

I'll start working on a plugin similar to the other integrations we currently have here https://github.com/mautic/mautic/tree/staging/plugins/MauticEmailMarketingBundle/Integration

I see that we have a Mautic slack community so I'll join that. 
@Yepher I've joined the Sparkpost slack community too, I'll ping you guys when I have questions.

**Comment by zstephen** [comment] 2016-04-27 20:17
Let me know if you need testing and error reporting help

Is there anyone else who needs this plugin that doesn't quite have API writing skills but that would be willing to help test for those who are working on the actual API?

I know we're not at testing stage, but let's get a bunch of people who are willing to jump in at that point to help.

**Comment by wderuijter** [comment] 2016-04-27 20:21
The same applies to me. I'll definitely help testing when needed.

**Comment by versadial** [comment] 2016-04-27 20:24
Count me in.

**Comment by Xavivico** [comment] 2016-04-27 20:32
Hi. I do not have programing skills but I am willing to test


De: zstephen <notifications@github.com> <notifications@github.com>
Respondre: mautic/mautic
<reply@reply.github.com>
<reply@reply.github.com>
Data: 27 d’abril de 2016 at 22:17:59
Per a: mautic/mautic <mautic@noreply.github.com> <mautic@noreply.github.com>
CC: Xavivico <xavier.viladiu@gmail.com> <xavier.viladiu@gmail.com>, Comment
<comment@noreply.github.com> <comment@noreply.github.com>
Tema:  Re: [mautic/mautic] Using Sparkpost API for sending mail (#1488)

Let me know if you need testing and error reporting help

**Comment by jfgrissom** [comment] 2016-04-29 13:52
Wow, nice turnout to support this!

I will let you know when I have a fork ready to test (I'm shooting for getting the first cut of this done over the weekend).

**Comment by jfgrissom** [comment] 2016-05-02 05:05
Hi,

I've completed getting the configuration into the UI for this. I have it storing the API key (using the build in encryption features that Mautic has for storing stuff like that).

The UI configuration can also (optionally) pull back a recipient list to bind to for syncing contacts between Mautic and Sparkpost.

I'll try to get a working version pushed to Git tomorrow morning (maybe evening). I'll share the fork/branch once it is published. When it is solid I'll submit a PR.

Most of the work left to do looks pretty straight forward. I'll set it up so we can send to Sparkpost via the API not SMTP (so low cost VPS providers don't give us head-aches about sending email from their IP addresses).

So that is the update. I hope it is good. More to come...

**Comment by jfgrissom** [comment] 2016-05-04 14:44
Hi,

Sorry for the delay on this. My day job has me tied up. I'm carving out some time this weekend to finish this up. I just wanted to keep you guys in the loop.

Would hate for anyone to think I slipped and fell on a banana peal or something.
=)

Thanks for you patience.

I'll keep you updated.

**Comment by wderuijter** [comment] 2016-05-04 15:14
@jfgrissom  Good to hear you're okay Jason :)

**Comment by jfgrissom** [comment] 2016-05-06 14:26
Hi,

Here is another update. (These screen shots will likely change over this weekend - but at least it is something you can see in progress.)

**E-mail delivery configuration is about 50% complete:**
The views/form pieces are completed. I mostly reviewed the Amazon and Mailchimp Transports and build one for SparkPost based on those.
On this screen shot you can select Sparkpost as a transport (I also alphabetized the select options - It was making me crazy every time I looked at it).
![screen shot 2016-05-06 at 6 22 14 am](https://cloud.githubusercontent.com/assets/660762/15074425/bdff7448-1353-11e6-8d10-159029779b29.png)
 
On this screen shot you can enter your Api Key and then save it.
![screen shot 2016-05-06 at 6 21 37 am](https://cloud.githubusercontent.com/assets/660762/15074461/010aa578-1354-11e6-81ad-ad51e2c7ab6a.png)

I still need to get the Ajax "test connection/test email" buttons to work. And, I need to finish up the SparkpostTransport class to tie it all together.

**Regarding the Sparkpost Email Marketing Integration (Plugin):**
This is about 50% complete too. I mostly just took the base of this from the MailChimp Plugin and I'm just refactoring it to fit SparkPost.
We have SparkPost as an option to select as an email marketing plugin.
![screen shot 2016-05-06 at 6 38 39 am](https://cloud.githubusercontent.com/assets/660762/15074745/73bf306a-1355-11e6-87ba-826ee715b060.png)

We have the ability to set the API key for the integration.
![screen shot 2016-05-06 at 7 13 38 am](https://cloud.githubusercontent.com/assets/660762/15075664/78aca968-135a-11e6-8b08-1b1ae6d3e983.png)

We have the features we want to enable. All the goodies we care about will be here just like the other plugins. (The email item in the drop down list "Personal Email List" is just a test list I'm pulling from SparkPost into Mautic.) 
![screen shot 2016-05-06 at 7 20 47 am](https://cloud.githubusercontent.com/assets/660762/15075887/abbfc712-135b-11e6-88ad-aac820fd367d.png)

I hope seeing progress on this is encouraging.

I'll keep updating as I make progress.

**Comment by zstephen** [comment] 2016-05-07 05:46
What a fantastic update @jfgrissom 

Thanks!

**Comment by jfgrissom** [comment] 2016-05-09 01:57
@zstephen thanks for the feedback!

Ok, I've sent a test email through Mautic to Sparkpost (via the api NOT via smtp - though I may set that up too. It looks like it may be really easy to do).

Both the connectivity test and the send email test work from here (I took my api key out of the field for this screen shot. The success you see there is from clicking the "send test email" button. Also, please not if you don't have an official sending domain setup you need to use the sandbox@sparkpostbox.com address. This means you can't send test emails from gmail or other domains you don't own).
 
![screen shot 2016-05-08 at 6 10 41 pm](https://cloud.githubusercontent.com/assets/660762/15101579/e7ad6a88-1548-11e6-8c92-106bf6acaa9a.png)


**Here is a screen shot of the delivered emails I tested:**

![screen shot 2016-05-08 at 6 20 30 pm](https://cloud.githubusercontent.com/assets/660762/15101634/a8021248-1549-11e6-85dd-ba94e0773c69.png)

If there is anyone who wants to help me test this please feel free to pull the integration/sparkpost branch on my fork of the Mautic repo.

To make it easy for you to help test:
Here are some notes for getting setup. https://github.com/jfgrissom/mautic/wiki/Using-the-Sparkpost-Transport-for-Email-delivery-in-Mautic 
Here is the repo to clone in your "testing lab".
`
git clone -b integration/sparkpost https://github.com/jfgrissom/mautic.git

`

**Comment by tristanbailey** [comment] 2016-05-09 09:26
+1 for linking this from me so will look to add my testing

**Comment by wderuijter** [comment] 2016-05-09 11:15
Thanks @jfgrissom!
I just did a small test with your repo.
I get a "success" message when testing the connection.
When I try to send a test email I get this error message:
![screenshot-localhost 2016-05-09 13-12-17](https://cloud.githubusercontent.com/assets/618804/15111551/08eaf202-15e8-11e6-81d4-935eff6f406c.png)

**Comment by jfgrissom** [comment] 2016-05-09 13:04
@wderuijter,

Thanks so much for helping to test this! 
Very Interesting... I'm very sorry for that error.

I'll check on this before I head out to my day job this morning.
I will blow away my entire installation, pull it, and bundle install it from scratch.

**Comment by jfgrissom** [comment] 2016-05-09 13:31
composer install*** (Sorry I do rails stuff at my day job... LOL)

**Comment by jfgrissom** [comment] 2016-05-09 13:40
I'm glad you shared this @wderuijter!

I already see where I've missed this on the installer too.

![screen shot 2016-05-09 at 6 38 12 am](https://cloud.githubusercontent.com/assets/660762/15114853/c9cc96c0-15b0-11e6-80f0-efa404bd57fe.png)

More updates to come.

**Comment by jfgrissom** [comment] 2016-05-09 14:11
@wderuijter 

I'm 💯% sure that your experience is legitimate. The first time I looked at this code base was just over a week ago, so I'm confident what you're seeing is very real.

To identify where the point of failure is we may need to chat (I'm on the Mautic slack channel if you want to meet there sometime? Or we can Skype/Google Hangout if you want to share screens.)

**Here was my experience when I tried to reproduce what you saw:**
Interestingly, I had a different experience with the unsaved API key. I was able to send an email with or without saving (which makes sense you want to test before saving the settings). This worked in all 4 browsers I tested in.

**Here are the steps I followed:**
1. Dropped the Database.
2. Moved my mautic code to a backup folder.
3. Cloned the branch.
4. Moved into the new mautic folder created by the clone.
5. Ran the composer install.
6. Ran the mautic installer in Safari.
7. Tested a Sparkpost delivery using my API Key.

**Here is my environment configuration:**
MacOSX - El Capitan (Running really well on my ancient 2009 iMac BTW.)
PHP 5.6.21 (homebrew)
nginx 1.8.1 (homebrew)
mysql 5.7.12 (homebrew)
Safari Version 9.1 
Chrome Version 50.0.2661.94 (64-bit)
Firefox Version 34.0.5 
Firefox Version 46.0.1 (I updated my version for this test)

**Comment by wderuijter** [comment] 2016-05-09 14:41
thanks @jfgrissom 

I installed the mautic master branch before I switched to your branch. I did delete the cache/prod after switching.

I'm on mautic's slack too: @wim. Message me when it suits you. I'd be glad to help with this.

**Comment by jfgrissom** [comment] 2016-05-10 14:53
I've submitted a PR for this to be included. It may still need some refinements, but at least it is moving forward.

@wderuijter I'm still very willing to help you out on this. I'll keep pinging you on Slack.

**Comment by zstephen** [comment] 2016-05-12 05:16
Thanks @jfgrissom for your awesome work!

I have a question which is probably obvious to most people, so apologies in advance.
To clone this update into a test deployment, do I first clone the main repo then clone this update or will cloning this repo also bring down all the other needed Mautic content?

I was the one who originally contacted SparkPost support and asked them to help us on this topic. I feel I need to do my bit and help test all the fantastic work that's gone into this since. (I just need a bit of help getting my head around the git clone processes)

**Comment by wderuijter** [comment] 2016-05-12 05:58
Hey @zstephen, all you have to do is clone the repo like @jfgrissom posted:
`git clone -b integration/sparkpost https://github.com/jfgrissom/mautic.git`
That should checkout the correct branch, but you can check this by typing `git branch`. It should say `integration/sparkpost`.

**Comment by escopecz** [comment] 2016-05-12 06:50
@zstephen @wderuijter or follow this tutorial: https://github.com/mautic/mautic#how-to-test-a-pull-request

**Comment by versadial** [comment] 2016-05-18 16:57
For us non-technical guys...is there an easier release to test...ie. Grab these four files and replace them on the mautic install...and commence testing?

**Comment by jfgrissom** [comment] 2016-05-27 00:57
I just saw these (I've been in Vacation).

If the stuff @escopecz isn't enough I can help to add some specifics for testing it.

If you need more post it here and I'll create something.
=)

**Comment by zstephen** [comment] 2016-05-28 06:21
Hey thanks @jfgrissom I wasn't quite sure how to test out your work, I got a bit lost with the commands.

I'd reiterate the question @versadial asked, can we just grab the files in question and replace them?

**Comment by versadial** [comment] 2016-06-10 17:25
This project still going? Or it die out? Any updates to it? Thanks.

**Comment by jfgrissom** [comment] 2016-06-19 15:26
Hi,

This is being merged into the staging branch of the main project.

There were some merge errors that I flubbed. I've fixe them and am watching the build right now.

I believe this will be in a release pretty soon.

Thanks for your patience with my response. (At my day job we have an enterprise Github instance of our own so I'm not in the habit of checking this public version of github.com.)

=)

**Closed** 2016-08-10 18:01 UTC
Labels: Feature Request

**Comment by chandon** [comment] 2016-08-11 13:26
FYI 
Package sparkpost/php-sparkpost is abandoned, you should avoid using it. Use sparkpost/sparkpost instead.

**Comment by shoeshine** [comment] 2016-09-16 04:34
@chandon Where is the sparkpost/sparkpost package?

**Comment by lukas-outlook** [comment] 2017-02-28 10:44
Hello,
Does SparkPost support hard bounces and soft bounces? I couldn't get Amazon SES and SendGrid to work with bounces :(

**Comment by wderuijter** [comment] 2017-02-28 10:58
Hey @lukas-outlook . Sparkpost itself does support Soft and Hard bounces in it's own reporting.
However, sparkpost does not send Soft Bounce or Hard Bounce to Mautic. Just all the Bounces in general.

**Comment by lukas-outlook** [comment] 2017-02-28 11:13
Thanks @wderuijter! Does Mautic recognizes mandrill's soft and hard bounces?

**Comment by wderuijter** [comment] 2017-03-01 08:37
I have no idea about that @lukas-outlook.

**Comment by 3L1AS** [comment] 2017-09-27 21:55
Does someone else has the problem that Mautic is not processing the bounce webhook from Sparkpost? https://www.mautic.org/community/index.php//8464-mautic-is-not-processing-bounce-webhook-from-sparkpost

**Comment by ak47thakore** [comment] 2018-01-03 01:48
Hello everyone. Please let me know if this is not the right place for this message and direct me to the right place.

I am using Mautic 2.11. I was able to successfully set up send emails from Mautic using Soarkpost. However, when I try to create the Webhook inside Sparkpost (for Bounce processing), I get the following error in Sparkpost Webhook panel:

Our servers could not post a sample payload to this URL (POST to webhook target URL failed with error code UNABLE_TO_VERIFY_LEAF_SIGNATURE)

My target URL is:

https://My-Mautic-URL/mailer/sparkpost/callback.

I changed the actual URL to "My-Mautic-URL" above. 

Please help or point me to the right site where I can get help.

AK
