### ISSUE TITLE
Email clicks statistics doesnt match

### ISSUE THREAD

**Issue by andersonid** [mautic/mautic#1997] opened 2016-07-08 21:37 UTC
## Description
Email clicks statistics doesnt match on  Contact Segments comparison with, click counts.

## Steps to reproduce

Just looking at channels >> email >> email "XYZ" view details

http://look.andersonid.com/dkpp

**Comment by escopecz** [comment] 2016-08-17 19:04
Seems like duplicate of https://github.com/mautic/mautic/issues/1703

**Closed by escopecz** 2016-08-17 19:04 UTC
