### ISSUE TITLE
Undefined variable: submissions after 2.15 update

### ISSUE THREAD

**Issue by ldrolez** [mautic/mautic#7135] opened 2019-01-16 09:12 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Since I upgraded to Mautic 2.15 I noticed the 'undefined variable' errors in the Mautic log (see below).
They appear when a focus item is edited or display. But The focus popups seem to work, and
I hope that I won't discover other side effects.

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.0.33
| Browser | Any

### Steps to reproduce
1. Upgrade Mautic from 2.14 to 2.15
2. Display a Mautic focus item with attached form from an external site
3. Or edit a focus item, the errors are also displayed when you click 'save and close'

### Log errors
[2019-01-16 09:58:41] mautic.NOTICE: PHP Notice - Undefined variable: submissions - in file /www/mautic/app/bundles/FormBundle/Views/Builder/form.html.php - at line 59 [] []
[2019-01-16 09:58:41] mautic.NOTICE: PHP Notice - Undefined variable: lead - in file /www/mautic/app/bundles/FormBundle/Views/Builder/form.html.php - at line 59 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2019-01-21 10:42
It looks like this is caused by https://github.com/mautic/mautic/pull/6826/files#diff-19c65f7d8ae6eb196b2ac74601bfe62eR59

@alanhartless it should check if the var exists probably like
```
if (isset($submissions) && $f->showForContact($submissions, $lead, $form)):
```
What do you think?

**Comment by alanhartless** [comment] 2019-01-22 13:58
@escopecz no, that was one of the bugs fixed because it wouldn't show for a contact to start with unless they had previous submissions. We'll need to just make sure `$submissions` is defined if not set.

**Comment by escopecz** [comment] 2019-01-22 14:01
That's what I was suggesting. To check if `$submissions` is set and if so use it in the `showForContact` method.

**Comment by rhingonekar** [comment] 2019-03-12 20:19
So what is the solution to fix this issue?

**Comment by Uebix** [comment] 2019-04-02 18:50
Hello, solutions?

Mautic version: 2.15.1
PHP version: 7.0.33
Browser: Any

**Comment by diegodorgam** [comment] 2019-05-29 19:46
Same problem here

**Comment by cremigerhonig** [comment] 2019-06-06 21:14
same problem here!

**Comment by tenil** [comment] 2019-06-07 20:05
Same problem here

**Comment by BrainRift** [comment] 2019-06-18 18:28
Same problem

**Comment by nfwade** [comment] 2019-08-15 23:44
Same problem. If anyone's fixed this, please lmk.

**Comment by sudo-shubham** [comment] 2019-08-16 12:22
Same problem

**Comment by escopecz** [comment] 2019-08-31 19:14
Fixed in pull request https://github.com/mautic/mautic/pull/7839. Please test and comment with your test results as a comment on that pull request. It will help to get this bug fix merged and released asap.

**Comment by Woeler** [comment] 2019-09-01 20:45
Fix merged

**Closed by Woeler** 2019-09-01 20:45 UTC
Labels: Ready To Test, Regression
