### ISSUE TITLE
Campaigns and email messages sent, to find reporting on which emails clicked and open rates?

### ISSUE THREAD

**Issue by manish200793** [mautic/mautic#7051] opened 2018-12-25 11:27 UTC
Hello,
I want to know which user has opened and clicked on a mail using REST API’s , and also the list of users whom email is not delivered ?

**Comment by escopecz** [comment] 2019-01-03 08:39
Duplicate of https://github.com/mautic/mautic/issues/7053

**Closed by escopecz** 2019-01-03 08:39 UTC
