### ISSUE TITLE
Segment filter "Visited URL" not working

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4484] opened 2017-07-21 08:32 UTC
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I cant create a segment with the filter *Visited URL*. The segment stays empty and my logs show a broken SQL SELECT.

The table ```mautic.leads``` does not have the column ```hiturl```:

![image](https://user-images.githubusercontent.com/7669818/28455523-a190642c-6dff-11e7-89a7-cfca39372893.png)

Shouldn't the filter use the table ```mautic.page_hits```?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | PHP Version 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create a segment
2. Use the filter *Visited URL*
3. Save
4. Wait for your cronjob or use ```php console mautic:segments:update```
 
### Log errors: 

```
[2017-07-20 11:54:05] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list'" at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
```

**Comment by escopecz** [comment] 2017-07-21 10:19
I cannot replicate. Please make a screenshot of the segment configuration.

There is no mention of "hiturl" in the whole Mautic codebase. Do you have a custom field called hiturl?

**Comment by FabianTe** [comment] 2017-07-21 13:20
![image](https://user-images.githubusercontent.com/7669818/28465080-d9832de2-6e27-11e7-9746-0526d9f11b32.png)

I can't finde "hiturl" or "SELECT DISTINCT" in my bundles folder either :/

**Comment by escopecz** [comment] 2017-07-21 13:24
Are you sure it's this segment which is failing? Try to execute `app/console mautic:segments:update` manually and it will show you the ID of the segment which is failing.

**Comment by FabianTe** [comment] 2017-07-28 07:57
Bug does not happen anymore. Will open this if it happens again.

**Comment by FabianTe** [comment] 2017-07-28 08:04
_Sorry for closing this to hastly, got this issue confused with another._

> Are you sure it's this segment which is failing? Try to execute app/console mautic:segments:update manually and it will show you the ID of the segment which is failing.

Last week I removed the faulty segment and the error went away. Today I added a new segment like the other one and got the error againg:

```
[2017-07-28 09:59:06] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list'" at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
```

Strangely it doesn't show any error when running ```app/console mautic:segments:update```.

**Comment by escopecz** [comment] 2017-07-28 08:21
This issue seems like duplicate of https://github.com/mautic/mautic/issues/4160. Lets discuss it there.

**Closed by escopecz** 2017-07-28 08:21 UTC
Labels: Pending Feedback
