### ISSUE TITLE
Campaign Builder : Getting [object Object] in Form field condition value

### ISSUE THREAD

**Issue by l2aelba** [mautic/mautic#3172] opened 2017-01-04 08:49 UTC
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When I created a campaign form and make a new campaign. I got [object Object] in value when I trying to add condition by Form field.

**Campain form, I added a select options like this :**

![screen shot 2017-01-04 at 09 39 02](https://cloud.githubusercontent.com/assets/983458/21636334/a2e5794a-d262-11e6-8bab-a47b22616df5.png)

**When I trying to add condition in campaign, This showing `[object Object]` and not able to add**

![3atjrvwmrc](https://cloud.githubusercontent.com/assets/983458/21636386/e00ff368-d262-11e6-8682-0f5ea5f5e75b.gif)

## System info:

| Q   | A
| --- | ---
| Mautic version | v2.5.0
| PHP version | 7.0.14

**Comment by victorkoopman** [comment] 2017-02-19 20:13
Exact same problem here. I have several Mautic installations (Selfhosted, version 2.6.1). In one of them i have it working from a previous version. I do the exact same in the second installation and do not get the values specified in the form.

I think the problem is in the form. When i create a test form in the first installation the problem appears aswell. But all works fine when I use the earlier made form. Problem only with new form.

**Comment by escopecz** [comment] 2017-03-06 10:48
Duplicate of https://github.com/mautic/mautic/issues/2725

**Closed by escopecz** 2017-03-06 10:48 UTC
Labels: Bug

**Comment by Ri100** [comment] 2017-03-20 16:12
The bug still persist in v.2.7.1 with PHP Version 7.0.17-1~dotdeb+8.1 and Apache/2.4.10 (Debian) in Form field values.
![image](https://cloud.githubusercontent.com/assets/13216315/24109261/6594884c-0d90-11e7-919d-f95677f413da.png)
