### ISSUE TITLE
Page Hits Report with calculated field - Sort Error

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#7858] opened 2019-09-09 07:16 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.2
| PHP version | 7.1.27
| Browser |  Chrome

### Steps to reproduce
1.  Create a report with Data source = `Page Hits`
2. In `Columns` set `Hit Url`
3. `Group By` set `Hit Url`
4. `Calculated Column` set `Count Hit Url`
5. Save the report.
6. Try to sort using the `Count Column`
7. Exception will raise
 
### Log errors

```[2019-09-09 17:06:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT ph.url AS url1, COUNT(ph.url) AS 'COUNT ph.url' FROM ma_page_hits ph LEFT JOIN ma_pages p ON ph.page_id = p.id LEFT JOIN ma_page_redirects r ON r.id = ph.redirect_id LEFT JOIN ma_lead_devices ds ON ds.id = ph.device_id LEFT JOIN ma_ip_addresses i ON i.id = ph.ip_id LEFT JOIN ma_leads l ON l.id = ph.lead_id LEFT JOIN ma_pages tp ON p.id = tp.id LEFT JOIN ma_pages vp ON p.id = vp.id LEFT JOIN ma_categories c ON c.id = p.category_id WHERE (ph.date_hit IS NULL OR (ph.date_hit BETWEEN ? AND ?)) AND ((l.mirus_admissions_companio = ?) AND (ph.url IS NOT NULL) AND (ph.url <> '')) GROUP BY ph.url ORDER BY COUNT DESC) c' with params ["2019-05-31 14:00:00", "2019-09-09 07:06:29", "0"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT ph.url AS url1, COUNT(ph.url) AS 'COUNT ph.url' FROM ma_page_hits ph LEFT JOIN ma_pages p ON ph.page_id = p.id LEFT JOIN ma_page_redirects r ON r.id = ph.redirect_id LEFT JOIN ma_lead_devices ds ON ds.id = ph.device_id LEFT JOIN ma_ip_addresses i ON i.id = ph.ip_id LEFT JOIN ma_leads l ON l.id = ph.lead_id LEFT JOIN ma_pages tp ON p.id = tp.id LEFT JOIN ma_pages vp ON p.id = vp.id LEFT JOIN ma_categories c ON c.id = p.category_id WHERE (ph.date_hit IS NULL OR (ph.date_hit BETWEEN ? AND ?)) AND ((l.mirus_admissions_companio = ?) AND (ph.url IS NOT NULL) AND (ph.url <> '')) GROUP BY ph.url ORDER BY COUNT DESC) c' with params [\"2019-05-31 14:00:00\", \"2019-09-09 07:06:29\", \"0\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by sensalot** [comment] 2019-10-22 10:32
Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

**Comment by RCheesley** [comment] 2019-11-05 21:25
I was able to reproduce this on 2.15.3, error:

`[2019-11-05 21:24:13] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT ph.url AS url1, COUNT(ph.url) AS 'COUNT ph.url' FROM mau_page_hits ph LEFT JOIN mau_pages p ON ph.page_id = p.id LEFT JOIN mau_page_redirects r ON r.id = ph.redirect_id LEFT JOIN mau_lead_devices ds ON ds.id = ph.device_id LEFT JOIN mau_ip_addresses i ON i.id = ph.ip_id LEFT JOIN mau_leads l ON l.id = ph.lead_id LEFT JOIN mau_pages tp ON p.id = tp.id LEFT JOIN mau_pages vp ON p.id = vp.id LEFT JOIN mau_categories c ON c.id = p.category_id WHERE ph.date_hit IS NULL OR (ph.date_hit BETWEEN ? AND ?) GROUP BY ph.url ORDER BY COUNT ASC) c' with params ["2019-10-05 00:00:00", "2019-11-05 21:24:13"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause'" at /Users/ruth.cheesley/Sites/local.mautictest/@vcs/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT ph.url AS url1, COUNT(ph.url) AS 'COUNT ph.url' FROM mau_page_hits ph LEFT JOIN mau_pages p ON ph.page_id = p.id LEFT JOIN mau_page_redirects r ON r.id = ph.redirect_id LEFT JOIN mau_lead_devices ds ON ds.id = ph.device_id LEFT JOIN mau_ip_addresses i ON i.id = ph.ip_id LEFT JOIN mau_leads l ON l.id = ph.lead_id LEFT JOIN mau_pages tp ON p.id = tp.id LEFT JOIN mau_pages vp ON p.id = vp.id LEFT JOIN mau_categories c ON c.id = p.category_id WHERE ph.date_hit IS NULL OR (ph.date_hit BETWEEN ? AND ?) GROUP BY ph.url ORDER BY COUNT ASC) c' with params [\"2019-10-05 00:00:00\", \"2019-11-05 21:24:13\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /Users/ruth.cheesley/Sites/local.mautictest/@vcs/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /Users/ruth.cheesley/Sites/local.mautictest/@vcs/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'COUNT' in 'order clause' at /Users/ruth.cheesley/Sites/local.mautictest/@vcs/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
`

**Comment by RCheesley** [comment] 2020-07-29 11:37
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by RCheesley** [comment] 2020-07-29 11:39
Tested quickly on Mautic 3.x and was not able to reproduce so closing this issue down :)

**Closed by RCheesley** 2020-07-29 11:39 UTC
Labels: bug, pending-feedback, triage-mautic-3
