### ISSUE TITLE
PHP Fatal error:  Cannot use Mautic\LeadBundle\Entity\DoNotContact as DoNotContact because the name is already in use

### ISSUE THREAD

**Issue by mareksotak** [mautic/mautic#6386] opened 2018-07-29 08:08 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
Running any cron command e.g. `/usr/bin/php app/console mautic:campaigns:update`

`PHP Fatal error:  Cannot use Mautic\LeadBundle\Entity\DoNotContact as DoNotContact because the name is already in use in app/bundles/LeadBundle/Model/LeadModel.php on line 36`

which does not execute the related command at the end

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version |  5.6.33-3

### Steps to reproduce:
1. Run any Mautic command from console
 
### Log errors: 

`PHP Fatal error:  Cannot use Mautic\LeadBundle\Entity\DoNotContact as DoNotContact because the name is already in use in app/bundles/LeadBundle/Model/LeadModel.php on line 36`

**Comment by sibben** [comment] 2018-07-30 14:32
Same here

**Comment by alanhartless** [comment] 2018-07-30 14:38
Can you guys deleting app/cache/prod to see if it resolves the issue?

**Comment by sibben** [comment] 2018-07-30 14:42
Yes, solved it!

**Comment by sibben** [comment] 2018-07-30 14:43
Hmmm,,  solved it once.

**Comment by sibben** [comment] 2018-08-01 14:14
For the time being I run my commands like this
` rm -rf app/cache/prod/ && php  app/console mautic:segments:update`

**Comment by Inarus** [comment] 2018-08-01 23:14
Remove files from app/cache/prod solve problem for first command run. To run command again console (mautic:segments:update --env=prod) app/cache/prod folder need to be removed again. Remove cache folder before each console command run is not the best solution.

**Comment by Inarus** [comment] 2018-08-01 23:50
Same problem here but I think I found solution.

Problem was caused by running cronjob command while update to 2.14.0. 
My solution is:

1. Stop all mautic cronjob,
2. Restore files and database from backup.
3. Run update script once again.

**Comment by Inarus** [comment] 2018-08-02 09:29
Unfortunately same problem here php 5.6.36 

 `PHP Fatal error: Cannot use Mautic\LeadBundle\Entity\DoNotContact as DoNotContact because the name is already in use in app/bundles/LeadBundle/Model/LeadModel.php on line 36` after each app/console command. 

Temporary solution is: 

`rm -rf app/cache/prod/appProdProjectContainer.php` before each `app/console` command run.

**Comment by Inarus** [comment] 2018-08-02 17:51
I switch php5 to php7.1 and all commands works.

`php7.1 app/console mautic:segments:update --env=prod`

**Comment by fianbiasa** [comment] 2018-08-06 21:30
not solve / not work

**Comment by jerime** [comment] 2018-08-09 16:58
Any update on this?  I'm having the same issue.

**Comment by SurajMDurgad** [comment] 2018-08-30 07:46
I'm still facing this issue! Any updates?

**Comment by directpromo** [comment] 2018-09-04 20:09
I'm having the same issue. Цhen will the update with the bugfix?

**Comment by SurajMDurgad** [comment] 2018-09-05 05:30
Yup, 
https://github.com/chordify/mautic/commit/7224f3674db039f5785b1081be54aa0b5d4bdcb9
fixes the issue in php 5.6.
@jbransen Thanks for the fix.

**Comment by jbransen** [comment] 2018-09-05 07:04
@directpromo @SurajMDurgad Note that I forgot a case, you would also need
https://github.com/chordify/mautic/commit/36f22b2347d6e756c1b8f93fa34ecc7c54c22463

The [pull request](https://github.com/mautic/mautic/pull/6512) looks much cleaner, I would suggest using that.

**Comment by directpromo** [comment] 2018-09-05 07:33
@jbransen Thank You

**Comment by directpromo** [comment] 2018-09-21 10:28
This bug was not fixed in the last update (v2.14.1) :(

it will be fixed in the next update?

**Comment by ISKCONonlineadmin** [comment] 2018-09-30 11:47
> For the time being I run my commands like this
> `rm -rf app/cache/prod/ && php app/console mautic:segments:update`

Yes, this seems to work.

**Comment by gabriel-sf** [comment] 2018-10-02 12:06
I dont know if it helps, but if  update the configuration and select the PHP Mailer it does work, when I move it to AWS SES then I get that error.
Removing the cache works but thats not the proper solution

**Comment by jbransen** [comment] 2018-10-02 12:08
The proper fix is https://github.com/mautic/mautic/pull/6512 which was now finally merged to `staging`, so should be in the next release.

**Closed** 2018-10-02 21:10 UTC
Labels: Bug
