### ISSUE TITLE
Can't see company in Contact edit form

### ISSUE THREAD

**Issue by Tioneb90** [mautic/mautic#3687] opened 2017-03-15 19:52 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I can see Company name in contact view but then I edit the contact the Company field is empty. If I save the form, the company is changed. If I set the field obligatory ( for don't forgetting to fill the fiel ), the Contact Edit form can't submit but don't show error.

The Contact View
![capture d ecran 2017-03-15 a 19 53 08](https://cloud.githubusercontent.com/assets/468562/23967913/0cf58344-09c1-11e7-9c56-48dad5d13179.png)

The Contact Edit Form
![capture d ecran 2017-03-15 a 19 53 20](https://cloud.githubusercontent.com/assets/468562/23967917/12fb0b24-09c1-11e7-9946-ca13134471c5.png)

The bug appears after a migration from Mautic 2.5.1 to 2.7.1 with update.php script from CLI.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Go to contact edit form // It's for all contacts
 
### Log errors: 

No errors in APACHE2 / MYSQL and MAUTIC.

**Comment by escopecz** [comment] 2017-03-16 07:03
I cannot replicate. I can see the companies in the edit for as well as in the contact detail on Mautic 2.7.1. So my guess is that some migration didn't finish successfully. Try some steps from https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful and let us know if it helped, please.

**Comment by Tioneb90** [comment] 2017-03-16 07:39
Thanks for your response, I already try all of this "debug tips & tricks" and no changes ... Mautic cache is empty, Database migration is OK, I try to reinstall Mautic from files directly and I started to read PHP sources and database directly but It will be long ! Do you want more informations ?

**Comment by sneakersgames** [comment] 2017-03-16 14:43
![image](https://cloud.githubusercontent.com/assets/473894/24001735/40dbec4a-0a5f-11e7-80ba-b8d874c60799.png)
I can't see the **name input**

**Comment by escopecz** [comment] 2017-03-16 14:53
@sneakersgames could you try to switch to English language and try to open the form again?

**Comment by sneakersgames** [comment] 2017-03-18 10:56
Yes, same thing
![image](https://cloud.githubusercontent.com/assets/473894/24071417/7e7b1e04-0bd1-11e7-9207-298d84dac63d.png)

I see this in the error logs:
[2017-03-18 11:53:52] mautic.NOTICE: PHP Notice - Undefined index: companyemail - in file /var/www/mautic-master/app/bundles/LeadBundle/Views/Company/list.html.php - at line 125 [] []
[2017-03-18 11:53:52] mautic.NOTICE: PHP Notice - Undefined index: companyname - in file /var/www/mautic-master/app/bundles/LeadBundle/Views/Company/list.html.php - at line 143 [] []

**Comment by escopecz** [comment] 2017-03-20 08:39
Ok, I can replicate if I unpublish a company field. Please check your company custom fields and make sure all are published until this bug will be fixed.

**Comment by Tioneb90** [comment] 2017-03-20 12:43
@escopecz I've more informations about my problem, it's still not solved, but it's not about "published" or "unpublished" company field.

When a contact edit form is loading, just the 100 first companies are loaded in the select of the form. So if the company isn't in the 100 top, there is no company "selected" and nothing appears into the field. I think it's not a problem with the database, but a problem with sources, why 100 companies limitation in this field ?

**Comment by Tioneb90** [comment] 2017-03-20 14:13
I find a hack for my problem in file /app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php line 266 :

```php
        if (empty($data) && isset($args['limit'])) {
            $args['limit'] = 2000; //HERE : Before it was 100
        }

        if (isset($this->options['model_lookup_method'])) {
            $choices = call_user_func_array([$model, $this->options['model_lookup_method']], $args);
        } elseif (isset($this->options['repo_lookup_method'])) {
            $choices = call_user_func_array([$model->getRepository(), $this->options['repo_lookup_method']], $args);
        } else {
            $alias     = $model->getRepository()->getTableAlias();
            $expr      = new ExpressionBuilder($this->connection);
            $composite = $expr->andX();

            $limit = 2000; //HERE : Before it was 100 too
            if ($data) {
                $composite->add(
                    $expr->in($alias.'.id', $data)
                );
                if (count($data) > $limit) {
                    $limit = $data;
                }
            }

            $choices = $model->getRepository()->getSimpleList($composite, [], $labelColumn, $idColumn, null, $limit);
        }

        return $choices;
```

**Comment by cpot** [comment] 2017-03-20 16:28
Thank you @Tioneb90 for this patch of this very annoying bug !

**Comment by Tioneb90** [comment] 2017-03-21 14:11
You're welcome @cpot. Please pay attention that it's literally a hack but not a patch. For example if there is more than 2000 companies in mautic it will not work.

**Comment by alanhartless** [comment] 2017-04-03 20:59
I fear the hack here doesn't address the issue - whatever that may be. I'm starting to see if I can reproduce this. But $data should have the IDs of the chosen companies. $limit should not affect that. I did notice a bug looking that code though where `$limit = $data;` should be `$limit = count($data);` but that shouldn't be the cause of this unless you have more than 100 companies selected for the contact (which you don't; you just have one). So the bug here has to be somewhere in either $data not having the selected ID or getSimpleList not returning the expected results.

**Closed** 2017-04-18 10:16 UTC
Labels: Bug, P0
