### ISSUE TITLE
Sending an email to a contact with embeded image doesn't work

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2170] opened 2016-08-03 13:37 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When you try to send an single email to a contact (from his "contact" page), you can use a template.
If the template got an image, and if you embed the image, the src="cid:..." is not well formated, and swiftmailer is not able to send the mail

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1 + PR #2032 
| PHP version | 5.6

### Steps to reproduce:
1. Go to a contact 
2. Click on the top right menu, and "send an email"
3. Select a template with an image
4. Send the email
 
### Log errors: 

app/log file :  

mautic.NOTICE: Swift_IoException: Unable to open file for reading [cid%3A222d2d85e6759ae39ce3910b41126699@your.domain.com] (uncaught exception) at vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []

**Comment by chandon** [comment] 2016-08-03 14:26
More globaly, lots of HTML problem when sending an email to a "specific contact" with froala

**Comment by dbhurley** [comment] 2016-08-03 20:16
My fault on issue closing, I think it was a rogue Mautibot at work. I'll find them and reprimand them ;)

**Comment by Complectia** [comment] 2016-08-09 00:47
I am seeing the same issue on mautic.net.  This happens in both the Email editor when I send a test email and when I follow the steps above to reproduce.

This happened in both a Yahoo and Gmail client.

It has not been consistent - sometimes the email shows the image - and other times it does not.  I have tried both uploaded and URL images.  I have not been able to replicate the steps or pattern to get it to work - but it seems that images are not consistently displaying now.  

I do not see an image error in the email and if there is a link for the image, the link still works.

**Comment by Complectia** [comment] 2016-08-09 22:49
I did some extensive testing on this today and believe that the issue might be the browser.  What I found is that if I am logged into mautic.net with Firefox, the WYSIWYG editor does not work very well, and the emails I send from either Contacts or as a test in the editor do not have images embedded.  When I use Chrome, everything works as expected.

I submitted my test documentation and results in Slack and it was passed on to development.

**Comment by chandon** [comment] 2016-08-09 22:56
My initial issue concern only "Send email" from a contact page
![image](https://cloud.githubusercontent.com/assets/4522557/17536403/0b06464a-5e95-11e6-9c8c-eb72c973a0c0.png)

If you got problems with image size or firefox, please see PR #2032 , it might solve them

**Comment by Complectia** [comment] 2016-08-11 13:10
Please see my comment above.  There is an issue with embedded images not showing up when either sending emails from the Contact page, or as a test from the Email editor if you are using Firefox.  Chrome works fine.

**Comment by chandon** [comment] 2016-08-11 13:28
@Complectia did you merge PR #2032 ? Or you'll have to wait some more days, mautic 2.1.0 is on the way (and PR #2032 will be in)...

**Comment by mqueme** [comment] 2016-08-16 16:33
In new version of Mautic (2.1.0) this works correctly. Will close this issue.

**Closed by mqueme** 2016-08-16 16:33 UTC
Labels: Bug

**Comment by chandon** [comment] 2016-09-28 13:36
@mquene i'm using mautic 2.1.1, and it's still doen't work well. E.G: <img> are missing attributes width="" and height="", they only got style="width; height"... this causes troubles with many mail clients

in campaign emails, width/height attributes are present, but not in single contact email.

I think it's still linked to Froala editor.

This issue should be re-opened

**Comment by escopecz** [comment] 2016-09-28 13:38
@chandon check https://github.com/mautic/mautic/pull/2459. The option which added width and height attributes will be removed in 2.2.0 completely because many users didn't like it.

**Comment by chandon** [comment] 2016-09-28 13:39
@escopecz i'll give a try right now...

**Comment by chandon** [comment] 2016-09-28 13:56
@escopecz i've tried #2459, it's not doing the job, still no width and height attribute.

#2459 removes "imageOutputSize: true", so it's **removing** height and width attributes ? i want the opposite, i want height= and width= in the <img> (style is not enough)

**Comment by escopecz** [comment] 2016-09-28 14:00
Well, it's getting hard to please everyone. See the linked issues. People doesn't like it because it destroy responsiveness and it is buggy when percentage is used.

**Comment by chandon** [comment] 2016-09-28 14:03
ok, so in fact, Froala should'nt change the attributes. If people want to set height and width attributes, they should remain. If people want to remove it, it should be removed... Froala should'nt change the attributes when posting...

**Comment by chandon** [comment] 2016-09-28 14:14
in froala, there is a parameter : imageDefaultWidth. I think we should set it to 0 to avoid 300px default width (so it'll be the image default width ?)

**Comment by escopecz** [comment] 2016-09-28 14:27
Good idea. I tested it, liked it, sent a PR with it: https://github.com/mautic/mautic/pull/2601

**Comment by chandon** [comment] 2016-09-28 14:27
imageDefaultWidth:0 is quite good : it doesn't change the default image size of an embeded image, so there is no conflict with widht and style="width" (because images are by default included with 300px, so you have to resize it to go back to the default size, and it adds style="width")

**Comment by chandon** [comment] 2016-09-28 14:27
@escopecz tested it too :)
