### ISSUE TITLE
Internal Server Error when saving contact via API

### ISSUE THREAD

**Issue by sensalot** [mautic/mautic#7334] opened 2019-03-18 15:39 UTC
Checked in Chrome IE and Firefox
Mautic 2.15.0 and upgraded to 2.15.1
PHP Version 5.6.40 and upgraded to 7.2.16 

When I click a contact to view it, I get a 500 error
When I change the word view in the URL to edit, I can edit the contact
https://mautic.mydomain.biz/s/contacts/view/869 fails
https://mautic.mydomain.biz/s/contacts/view/869 works

I checked with incognito in Chrome as well

Error log in Mautic shows only none related errors
[2019-03-18 09:00:32] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "554", with message "554 Transaction failed: Header too long: 'List-Unsubscribe'. " Log data: >> MAIL FROM:  << 250 Ok  >> RCPT TO:  << 250 Ok  >> DATA  << 354 End data with .  >>  .  << 554 Transaction failed: Header too long: 'List-Unsubscribe'.  !! Expected response code 250 but got code "554", with message "554 Transaction failed: Header too long: 'List-Unsubscribe'. " (code: 554) (send); an-email-address [] []

**Comment by andrekutianski** [comment] 2019-03-18 20:51
You have upgraded your Mautic recently?

**Comment by sensalot** [comment] 2019-03-19 08:52
No fresh install of 2.15.0

**Comment by andrekutianski** [comment] 2019-03-19 17:00
Try to force a sql schema update, I recommend this guide https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by sensalot** [comment] 2019-03-26 18:37
might me memory related

**Comment by sensalot** [comment] 2019-03-27 14:12
We updated to 2.15.1 and did the suggested checks of https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful. This did not solve it. Mautic reports an error about a Null-byte.
So we created a new user in Mautic (to rule out import issues). And the problem persists. We checked with newly created anonymous contacts (website visitors) and the problem persists. 
There must be a bug in the save command behind the user interface, that results in the null-byte error

mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)"} []

**Comment by sensalot** [comment] 2019-03-27 15:01
Chrome console error
libraries.js?va9c03cbc:673 POST https://mydomain.biz/s/contacts/edit/1097?mauticUserLastActive=1&mauticLastNotificationId=9886 500 (Internal Server Error)
send @ libraries.js?va9c03cbc:673
ajax @ libraries.js?va9c03cbc:649
fileUploadXhr @ libraries.js?va9c03cbc:2321
$.fn.ajaxSubmit @ libraries.js?va9c03cbc:2309
Mautic.postForm @ app.js?va9c03cbc:244
Mautic.postMauticForm @ app.js?va9c03cbc:242
(anonymous) @ app.js?va9c03cbc:241
dispatch @ libraries.js?va9c03cbc:404
elemData.handle @ libraries.js?va9c03cbc:379
trigger @ libraries.js?va9c03cbc:402
(anonymous) @ libraries.js?va9c03cbc:437
each @ libraries.js?va9c03cbc:149
each @ libraries.js?va9c03cbc:139
trigger @ libraries.js?va9c03cbc:437
jQuery.fn.(anonymous function) @ libraries.js?va9c03cbc:602
buttonClick @ app.js?va9c03cbc:67
dispatch @ libraries.js?va9c03cbc:404
elemData.handle @ libraries.js?va9c03cbc:379

**Comment by sensalot** [comment] 2019-03-27 21:17
upgrade to 2.15.1 did not fix it
upgrade php version to 7.2.16 did not help
I do have one record containing only an emailaddress and no ID. It shows up under report email. But not as a contact. But I expect that this is not the solution

**Comment by igisho** [comment] 2019-04-11 09:33
same issue for me

**Comment by escopecz** [comment] 2019-04-18 11:30
Based on the reported error message this is duplicate of https://github.com/mautic/mautic/issues/6339

**Comment by sensalot** [comment] 2019-04-18 12:23
They don't seem a duplicate. 6339 has title: Multiple value on List-Unsubscribe header

**Comment by escopecz** [comment] 2019-04-18 12:28
The reported error message is the same. If the 500 error on contact detail is caused by another error then please provide it.

**Comment by sensalot** [comment] 2019-04-18 12:37
No. Here is written before the error: Error log in Mautic shows only none related errors. So the error mentioned here has nothing to do with the problem

**Comment by sensalot** [comment] 2019-04-18 12:38
I just repeated the error and the internal server error does not add tot the mautic log.

**Comment by escopecz** [comment] 2019-04-18 12:40
Maybe it's in the server logs then? Check https://www.mautic.org/docs/en/tips/troubleshooting.html for more details about troubleshooting. We cannot fix it without steps to reproduce or an error message so it doesn't make much sense to have such issue open.

**Comment by sensalot** [comment] 2019-05-02 07:01
Mautic Error: [2019-05-01 22:23:13] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)"} []

Appache Log contains no Errors. And does contain this: our-ipaddress - - [01/May/2019:22:22:22 +0200] "GET / HTTP/1.1" 302 292
our-ipaddress - - [01/May/2019:22:22:24 +0200] "GET /s/dashboard HTTP/1.1" 302 424
our-ipaddress - - [01/May/2019:22:22:26 +0200] "GET /s/login HTTP/1.1" 200 9099
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /media/css/app.css?va9c03cbc HTTP/1.1" 200 21457
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /media/css/libraries.css?va9c03cbc HTTP/1.1" 200 155617
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /media/js/app.js?va9c03cbc HTTP/1.1" 200 73815
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?va9c03cbc HTTP/1.1" 200 81975
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /media/js/libraries.js?va9c03cbc HTTP/1.1" 200 495899
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/align.js?va9c03cbc HTTP/1.1" 200 1430
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/code_beautifier.js?va9c03cbc HTTP/1.1" 200 28138
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/code_view.js?va9c03cbc HTTP/1.1" 200 3032
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/font_size.js?va9c03cbc HTTP/1.1" 200 1340
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/colors.js?va9c03cbc HTTP/1.1" 200 3975
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/font_family.js?va9c03cbc HTTP/1.1" 200 1887
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/fullscreen.js?va9c03cbc HTTP/1.1" 200 1695
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/image.js?va9c03cbc HTTP/1.1" 200 16814
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/filemanager.js?va9c03cbc HTTP/1.1" 200 1221
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/inline_style.js?va9c03cbc HTTP/1.1" 200 1111
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/line_breaker.js?va9c03cbc HTTP/1.1" 200 4060
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/lists.js?va9c03cbc HTTP/1.1" 200 2902
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/link.js?va9c03cbc HTTP/1.1" 200 7014
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/paragraph_format.js?va9c03cbc HTTP/1.1" 200 2575
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/paragraph_style.js?va9c03cbc HTTP/1.1" 200 1518
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/quick_insert.js?va9c03cbc HTTP/1.1" 200 3418
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/quote.js?va9c03cbc HTTP/1.1" 200 1166
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/url.js?va9c03cbc HTTP/1.1" 200 1463
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/gatedvideo.js?va9c03cbc HTTP/1.1" 200 7471
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/table.js?va9c03cbc HTTP/1.1" 200 23787
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/dynamic_content.js?va9c03cbc HTTP/1.1" 200 884
our-ipaddress - - [01/May/2019:22:22:27 +0200] "GET /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/token.js?va9c03cbc HTTP/1.1" 200 1630
our-ipaddress - - [01/May/2019:22:22:28 +0200] "GET /app/bundles/CoreBundle/Assets/css/libraries/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 -
our-ipaddress - - [01/May/2019:22:22:28 +0200] "GET /media/images/favicon.ico HTTP/1.1" 304 -
our-ipaddress - - [01/May/2019:22:22:30 +0200] "POST /s/login_check HTTP/1.1" 302 440
our-ipaddress - - [01/May/2019:22:22:31 +0200] "GET /s/dashboard HTTP/1.1" 200 344701
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /s/contacts?_=1556742158164&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 151944
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /media/images/flags/Germany.png HTTP/1.1" 304 -
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /media/images/flags/United-States.png HTTP/1.1" 304 -
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /media/images/flags/Netherlands.png HTTP/1.1" 304 -
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /media/images/flags/Romania.png HTTP/1.1" 200 180
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /media/images/flags/Serbia.png HTTP/1.1" 200 1483
our-ipaddress - - [01/May/2019:22:22:52 +0200] "GET /s/ajax?action=commandList&model=lead.lead&_=1556742158165&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 1270
our-ipaddress - - [01/May/2019:22:22:56 +0200] "GET /s/contacts/view/845?_=1556742158166&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 254710
our-ipaddress - - [01/May/2019:22:22:57 +0200] "GET /s/ajax?action=commandList&model=lead.note&_=1556742158167&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 113
our-ipaddress - - [01/May/2019:22:23:01 +0200] "GET /s/contacts/edit/845?_=1556742158168&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 553729
our-ipaddress - - [01/May/2019:22:23:03 +0200] "GET /app/bundles/CoreBundle/Assets/css/libraries/chosen/chosen-sprite.png HTTP/1.1" 304 -
our-ipaddress - - [01/May/2019:22:23:03 +0200] "GET /s/ajax?action=lead:fieldList&field=title&_=1556742158169&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 449
our-ipaddress - - [01/May/2019:22:23:07 +0200] "GET /s/ajax?action=lead:fieldList&field=title&filter=Ing&_=1556742158170&mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 200 13
our-ipaddress - - [01/May/2019:22:23:13 +0200] "POST /s/contacts/edit/845?mauticUserLastActive=1&mauticLastNotificationId=196519 HTTP/1.1" 500 55214
our-ipaddress - - [01/May/2019:22:24:23 +0200] "POST /s/ajax?action=updateUserStatus&mauticUserLastActive=61&mauticLastNotificationId=196519 HTTP/1.1" 200 13

Might be related to https://github.com/mautic/mautic/issues/7117

**Comment by escopecz** [comment] 2019-05-02 07:09
Thanks for the error message! You are right. Looks like related to #7117. I leave this closed and let's track this issue there.

**Comment by sensalot** [comment] 2019-05-03 11:55
We tested with #7192 but this did not fix the error.
We changed only the file as mentioned in there.

**Comment by sensalot** [comment] 2019-05-03 11:59
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)"} []

**Comment by grinono** [comment] 2019-08-08 10:28
i'm having the same 'Internal Server Error' on the /api/contacts/new POST request. it worked before, but some it stopped working. running the bitnami Mautic instance on AWS > v2.15.2 any updates on this?

**Comment by grinono** [comment] 2019-08-13 15:42
any updates on this? of pointings on how to fix, as we can not use our Mautic instance in this conditions.

**Comment by escopecz** [comment] 2019-08-14 07:08
@grinono please provide what error you have. The one in this issue is not related to API but to email send. Then the other in the comments about null bytes may be related in case you want to save some obscure characters like emojis. You have to provide full details. What is your payload, what is the response and what is the error in the logs.

**Comment by grinono** [comment] 2019-08-14 09:11
@escopecz the payload of the POST request is { phone: "test123", firstname: "myname" }

`export async function MauticCreateUpdateContact(data) {
  console.log("data:", data);
  var body = JSON.stringify(data);
  const value = await fetch(`${url}/contacts/new`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${authorization}`,
      "Content-Type": "application/json"
    },
    body: body
  });
  console.log(value);
}`

Mautic does not provide any relevent error message at: /opt/bitnami/apps/mautic/htdocs/app/logs
the Apache logs show: 

> [Wed Aug 14 09:08:56.312753 2019] [proxy_fcgi:error] [pid 2237:tid 140469984028416] [client 90.100.76.202:49479] AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /opt/bitnami/apps/mautic/htdocs/app/bundles/LeadBundle/Entity/CustomFieldEntityTrait.php on line 257\nPHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /opt/bitnami/apps/mautic/htdocs/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php on line 1\n'

any suggestions on how to fix this

**Comment by escopecz** [comment] 2019-08-14 10:05
Ok, that's completely different error. Try to increase the memory limit in php.ini and restart the server. If that won't help, create a new issue.

This issue now contains several different issues in it. The original error reported has nothing to do with the API request. For this reason I will close this one. Please create a new issue if you still have problem.

**Closed by escopecz** 2019-08-14 10:05 UTC
Labels: Bug

**Comment by sensalot** [comment] 2019-10-16 14:45
I found the cause. 
The approach was to go to custom fields and disable all custom fields added. Just keep the core fields (with a slot) active. I could then save the contact without a problem. I activated the disabled fields on by one testing each time if save was possible. 
It was the notes field under the professional tab.
