### ISSUE TITLE
(Bug) Export form results as CSV, Excel or HTML doesn't work properly for "file" type field

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7832] opened 2019-08-29 08:47 UTC
1) Created a form.
2) Set one of the fields as type "file", so that visitors can upload something.
3) Export the results in any available format (CSV, Excel, HTML), 
4) Check the column for the said field 

Actual result : column shows a text which is the filename (incliding the file extension) without any indication of the path to download it. It makes the export of such field/columns practically useless, because I can't retrieve the files.

Expected result : same as when navigating to `/<form_id>/results`, the column displays a path to uploaded the file, as expected.
I would expect that the CSV, Excel or HTML exported files, also show a path or a link directly.

**Comment by AlbanL74fr** [comment] 2019-09-08 10:22
It sounds rather like a bug @npracht. Any reason why you selected the enhancement label?

**Comment by npracht** [comment] 2019-09-09 07:04
Because this is not a bug, you have the path to the file but not a link. A bug would be a broken link.

**Comment by AlbanL74fr** [comment] 2019-09-10 15:10
@npracht My description wasn't clear then. I improved it. No path, no link, it's just the filename. Can't do anything with that. It's a bug.

**Comment by RCheesley** [comment] 2020-07-31 17:12
I don't think that this is a bug, it is an enhancement to the current behaviour to make it more useful.

As we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment] 2020-09-04 09:28
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 09:28 UTC
Labels: enhancement, forms, pending-feedback, triage-mautic-3
