### ISSUE TITLE
Feature request - Company IP Lookup

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#2527] opened 2016-09-13 09:14 UTC
| Feature request? | 
Key feature of other systems is identification of the anonymous traffic. its very valuable for marketing and sales. 
Would be great to have the ability to identify traffic similar to Jumplead OR to do integration with the likes of lead forensices, whoisvisiting and ruler analytics.

**Comment by escopecz** [comment] 2016-09-13 09:38
Seems like duplicate of https://github.com/mautic/mautic/issues/1785

**Comment by mellsaid** [comment] 2016-09-13 09:46
@escopecz 
This is different than #1785 

IP lookup identify the anonymous traffic on the website or a landing page through the lookup services similar to Ruler Analytics, lead forensics etc... 
So instead of seeing just Visitors in the backend, the marketing will see the company name of that specific visit.

**Comment by escopecz** [comment] 2016-09-13 09:51
How about https://github.com/mautic/mautic/issues/1164?

**Comment by mellsaid** [comment] 2016-09-13 09:52
Actually yeah!. thats is same request. I can add few suggestions over there.

**Comment by escopecz** [comment] 2016-09-13 09:54
Ok, thanks for confirmation! I'll close this one and let's continue the discussion about it there.

**Closed by escopecz** 2016-09-13 09:54 UTC
