### ISSUE TITLE
Forumula fields in salesforce

### ISSUE THREAD

**Issue by waqdev786** [mautic/mautic#7506] opened 2019-05-09 10:06 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We integrated the Mautic with salesforce all fields are getting updated but for formula fields in salesforce we are getting below error. How can we update formula field information from salesforce to Mautic without error.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors
[2019-05-09 09:41:54] mautic.ERROR: INTEGRATION ERROR: Salesforce - Unable to create/update fields: Top_100_customer__c, STC_Prospect__c, IsDeleted, Lead_Segment__c, CRM_Create_Date__c. Please check the security settings of this field and verify that it is read/write for your profile or permission set. [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by waqdev786** [comment] 2019-05-09 10:07
Mautic v2.15.0
php 7.x

**Comment by escopecz** [comment] 2019-05-17 12:48
It's written in the SF error:
```
Please check the security settings of this field and verify that it is read/write for your profile or permission set
```
This is not a Mautic issue, so I'll close it.

**Comment by stevedrobinson** [comment] 2019-06-11 14:02
@escopecz Could we re-open this? These are non-writable fields. The connector should not try to sync Formula fields two-ways, but instead should only try to sync them one-way, since they are computed within Salesforce. I don't think there is any way to make them writable.

**Comment by stevedrobinson** [comment] 2019-06-11 14:11
I think this may be caused by this change: https://github.com/mautic-inc/mautic/commit/33982fbefbb2a3e90a7954966112df5be1b26891#diff-9b15b6be04482d6f57b012a98d72e58a 

It was working before we upgraded to 2.15.X

**Comment by stevedrobinson** [comment] 2019-06-11 14:15
I this was working for us in the past, but is not now. I believe it broke with the upgrade to 2.15.X

**Comment by boverhuisr** [comment] 2019-07-08 11:55
We have the same issue on 2.15.0. Within the Salesforce plugin we configured the formula fields (which are dynamic and read-only in Salesforce) to be imported into custom fields in Mautic; as such the integration direction is Salesforce -> Mautic. 

However when updating the lead/contact as part of a campaign, Mautic apparently tries to update all fields including the (read-only) formula fields.

**Comment by boverhuisr** [comment] 2019-08-22 11:56
@escopecz is there any news on this issue?

**Comment by boverhuisr** [comment] 2019-08-23 08:29
Would there be a quick fix we could apply to avoid the many errors we are having due to the fact that Mautic tries to update formula field (= not updateable)? Could we filter our these fields in the buildCompositeBody() in SalesforceIntegration.php?

This is causing a backlog of retries which eats up our Salesforce API limits and thus drastically impacting the integration with Salesforce.

**Comment by boverhuisr** [comment] 2019-08-23 09:23
We need the values from those (readonly) formula in Mautic to use for segmentation. As such they are mapped into custom fields.

**Comment by boverhuisr** [comment] 2019-08-23 09:25
> Definitely patch the code if needed. That's the perk of open source. 

Clear, however I'm not a PHP developer and would also need to first understand a bit better how Mautic handles this.

**Comment by RCheesley** [comment] 2020-07-29 12:21
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment] 2020-09-04 08:58
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 08:58 UTC
Labels: bug, pending-feedback, plugin, triage-mautic-3

**Comment by boverhuisr** [comment] 2020-10-12 15:33
Apologies; we did not do the upgrade to Mautic 3.x yet, so unable to confirm if problem still exists.
