### ISSUE TITLE
Bug: Social monitor experiencing encoding issue

### ISSUE THREAD

**Issue by cspenn** [mautic/mautic#5352] opened 2017-11-20 10:31 UTC
When running the social monitor on the command line, mySQL throws an error that looks like an encoding problem:

```
An exception occurred while executing 'INSERT INTO ma_leads (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, points, last_active, internal, social_cache, date_identified, preferred_profile_image, title, firstname, lastname, company, position, email, phone, mobile, address1, address2, city, state, zipcode, timezone, country, owner_id, stage_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-11-20 10:29:36", null, " ", null, null, null, null, null, null, 0, "2017-11-15 19:33:18", "a:0:{}", "a:1:{s:7:\"Twitter\";a:3:{s:7:\"profile\";a:9:{s:13:\"profileHandle\";s:5:\"JoDtw\";s:4:\"name\";s:8:\"Jo Darby\";s:8:\"location\";s:2:\"UK\";s:11:\"description\";s:116:\"Cocktail purveyor\ud83c\udf78, Social Media dabbler, intermittent blogger \ud83d\udda5\ufe0f, #freelancer, participating in #NaNoWriMo.\";s:3:\"url\";s:23:\"https:\/\/t.co\/mvywETYKCp\";s:9:\"time_zone\";s:13:\"Europe\/London\";s:4:\"lang\";s:2:\"en\";s:5:\"email\";s:0:\"\";s:12:\"profileImage\";s:68:\"https:\/\/pbs.twimg.com\/profile_images\/908334427373273093\/TzzRDn6K.jpg\";}s:8:\"activity\";a:3:{s:6:\"tweets\";a:6:{i:0;a:4:{s:5:\"tweet\";s:48:\".@LeeMack with a beard? Mmm, OK, I'm interested.\";s:3:\"url\";s:54:\"https:\/\/twitter.com\/18291451\/status\/932338307601780736\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Nov 19 20:02:29 +0000 2017\";}i:1;a:4:{s:5:\"tweet\";s:85:\"Matching hair extensions? OK. But can we limit the wigs on #strictly2017 from now on?\";s:3:\"url\";s:54:\"https:\/\/twitter.com\/18291451\/status\/932337885050822656\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Nov 19 20:00:48 +0000 2017\";}i:2;a:4:{s:5:\"tweet\";s:142:\"Am I the only one desperate for @Aj11Ace to give @MollieKing a big ole kiss on the lips when it's announced they're\u2026 https:\/\/t.co\/g9PxIWbWDa\";s:3:\"url\";s:54:\"https:\/\/twitter.com\/18291451\/status\/932334232583720962\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Nov 19 19:46:17 +0000 2017\";}i:3;a:4:{s:5:\"tweet\";s:56:\"Hey @brumhippodrome you Fizz Bar is out of fizz glasses.\";s:3:\"url\";s:54:\"https:\/\/twitter.com\/18291451\/status\/931966434909081601\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sat Nov 18 19:24:47 +0000 2017\";}i:4;a:4:{s:5:\"tweet\";s:104:\"Feeling a little stressed today so took a relaxing stroll around the new @marksandspencer Food. #therapy\";s:3:\"url\";s:54:\"https:\/\/twitter.com\/18291451\/status\/931939489227984896\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sat Nov 18 17:37:43 +0000 2017\";}i:5;a:4:{s:5:\"tweet\";s:133:\"Mmm, @RoyalMail Drop &amp; Go doesn't appear to be any quicker as Post Office still insist on weighing parcel &amp; printing receipt.\";s:3:\"url\";s:54:\"https:\/\/twitter.com\/18291451\/status\/931933334292385794\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sat Nov 18 17:13:16 +0000 2017\";}}s:6:\"photos\";a:0:{}s:4:\"tags\";a:2:{s:12:\"strictly2017\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:44:\"https:\/\/twitter.com\/search?q=%23strictly2017\";}s:7:\"therapy\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:39:\"https:\/\/twitter.com\/search?q=%23therapy\";}}}s:11:\"lastRefresh\";s:19:\"2017-11-20 10:29:36\";}}", "2017-11-20 10:29:36", "Twitter", null, "Jo", "Darby", null, null, null, null, null, null, null, null, null, null, null, "UK", null, null]:

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8D\xB8, ...' for column 'social_cache' at row 1
```

I ran into this recently myself and solved it by running utf8_encode() on the insert statement.

**Comment by adiwegs** [comment] 2020-03-12 10:58
Just tested the Twitter plugin with Mauitc v2.16.0. Problem still persists. However, not with all users. I tested with @sarahseyr

**Comment by RCheesley** [comment] 2020-07-17 18:33
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by cspenn** [comment] 2020-07-17 19:19
Unfortunately i have no way of testing until Mautic 3 supports PHP 7.4

**Comment by RCheesley** [comment] 2020-07-17 19:42
Mautibox.com ? Or on a local instance? Either should work :)

**Comment by cspenn** [comment] 2020-07-17 19:45
On a local instance. Mautic 3.0 only works with up to PHP 7.3; there's an open ticket that says PHP 7.4 support is in the works but not available yet. 

https://github.com/mautic/mautic/pull/8447

**Comment by RCheesley** [comment] 2020-07-17 19:55
Sorry I was not clear, I was suggesting that you could check locally on a localhost environment where it is easier to change the version of PHP in order to test things like this (or on mautibox.com). 

I am hopeful that we will get 7.4 support merged in 3.1, but there is a fair amount of work we have to do to get that to happen as we need to bump several dependencies before we can implement that. Feel free to jump in if you are able to help us with any of that! 

I shared the spreadsheet which included all of the dependencies on the PR that you mentioned.

**Comment by adiux** [comment] 2020-07-29 08:26
I tried to test, however, on localhost I run into problems with the Twitter oauth2 authentification, the redirect url and the callback. And to test it with Mautibox I think I will need a PR?

**Comment by RCheesley** [comment] 2020-07-29 08:55
@adiwegs indeed I was unable to add a Twitter account when trying to test recently, as I think we need to update the plugin to use full Oauth2 authentication (it gave me a pin number to enter, from what I recall, and there was nowhere to add it!).

I was asking to try and reproduce this and see if it still exists in M3, you can do that on the staging branch of mautibox.com which just pulls in the current staging branch.  FWIW I think this is due to incorrect database encoding/collation.

**Comment by RCheesley** [comment] 2020-07-29 09:06
Added an issue about the Twitter authentication problem: https://github.com/mautic/mautic/issues/9042

**Comment by adiux** [comment] 2020-07-29 12:41
thanks @RCheesley. 

I tested with the staging branch now. I was able to set up the Twitter plugin, Authenticate and map the fields. I also set up a social monitoring for #ai. But nothing happens. Are crons running on Mautibox?

**Comment by RCheesley** [comment] 2020-12-15 15:05
Closing this issue due to lack of recent engagement.

**Closed by RCheesley** 2020-12-15 15:05 UTC
Labels: T1, bug, social-monitoring, triage-mautic-3
