### ISSUE TITLE
Vtiger 7.1 not syncing with mautic 2.15

### ISSUE THREAD

**Issue by sensalot** [mautic/mautic#7301] opened 2019-03-06 00:47 UTC
I have a vtiger integration that pushes contacts from mautic 2.15  to leads in Vtiger 7.1
The documentation is outdated both at
https://www.mautic.org/docs/en/plugins/vtiger_crm.html
https://mautic.com/help/vtiger-plugin-setup/
The screens are not the sames as in Mautic 2.15

The documentation and the fields in Mautic indicate that a by-directional sync with Vtiger is possible. However: The integration does not pull contact and organisations from Vtiger into Mautic.
I receive no errors in Mautic log
A cronjob is active, however it is fetchleads not contacts or organisations

The documentation does not explain what is needed to get the sync working. Based on the available information the integration does not pull contact or organisations fromVtiger 7.1

**Comment by BrainRift** [comment] 2019-04-09 00:58
I was looking for an answer for this myself.  Were you able to solve it?  I know with other integrations like Hubspot, you need a cron job.  Here is what I use for Hubspot integration, but not sure if vTiger needs something similar...

mautic:integration:fetchleads --integration=Hubspot  #mautic-hubspot-cron`

**Comment by sensalot** [comment] 2019-04-09 07:30
What I have working is a push of a new contact in Mautic using a Mautic form, to Vtiger as a lead. The .php of the Vtiger plugin is mutch smaller compared to Hubspot or Suger, so I think the integration of  Vtiger has more limitations. The setupfield suggest otherwise.

**Comment by r1lita** [comment] 2019-04-09 11:56
I'm facing the same problem, the sync doesn't go both ways. I'm able to push contacts to VTiger but not the other way around. No errors in Mautic's logs.

**Comment by ReZarrected** [comment] 2019-04-19 05:24
> I'm facing the same problem, the sync doesn't go both ways. I'm able to push contacts to VTiger but not the other way around. No errors in Mautic's logs.

How did you guys get to push contacts to vTiger? I tried everything... it seems broken, no error in logs either. Also, the screens on [this page](https://mautic.com/help/vtiger-plugin-setup/) aren't even available. I started liking Mautic but now I'm beginning to think the devs are not concerned about the open-source version and have sold-out

**Comment by ReZarrected** [comment] 2019-04-19 05:32
You can only push a contact through a standalone form. Why is that?

**Comment by ridjy** [comment] 2019-08-21 07:33
Hello, I'm using this Cron 
_[timing [path tp php] [path to mautic] mautic:integration:fetchleads --integration=Vtiger_
but not work, 
is it not working for Vtiger?

**Comment by edtaaffe** [comment] 2019-08-30 13:27
Im in the same boat more or less. Cant get off first base. Documentation all out of date.
Created the configuration of the plugin by following the instructions, no errors.
Try a trigger in mautic to shove contact into CRM. No integrations show up on the dropdown.
Since this is I assume instant integration, maybe the cron not needed, 
Any one know how do i get the integration (plugin I am assuming) to show up in the dropdown for selecting an integration

**Comment by cloudpotions** [comment] 2019-11-14 01:59
Aug 30, 2021 - The below comment from myself is not right. On the open source version of Vtiger, If you go use /webservice.php (For example, https://YourVtigerUrl.com/webservice.php )  at the end of your starting URL, it will work. Sometimes to make it work you have to press Save and Close and then try reopening it, but if you try a couple of times, you will eventually see the Contact Mapping tab, it is pretty glitchy to get it working but once it is set up, the push to integration feature seems to work pretty good. I have requested an update to the documentation on GitHub for this. 

-------
The Vtiger Plugin in Mautic ONLY works with Vtiger Cloud Version - it does not work with Vtiger open source. Furthermore, it will only do one initial push ... so points are only updated once. With the points update - same problem with Suite CRM as well. Is there a smart work around to sync to a plugin that works perfectly (like Hubspot?) and then sync from Hubspot to Vtiger using a service like Integromat or Pie Sync?

**Comment by jonascasarin** [comment] 2019-12-09 21:04
@MyBpoConsultant, where did you see this information that mautic plugin just works on cloud version?! I'm trying to integrate with booth, cloud and open source and got same problem.

**Comment by Plato39** [comment] 2019-12-17 12:10
I am also struggling with this integration. The lack of up-to-date documentation is quite frustrating.  I tested it with cloud vTiger (version 8) and found contacts manually added to cloud vTiger are pushed to Mautic.  Incidentally cloud vTiger 8 by default has the Leads module deactivated - everyone is classed as a contact, but with a status option (cold, warm, hot).  With open source vTiger 7.1 I am only able to get contacts via Mautic forms to be added to vTiger as a Lead at the moment of capture.  Adding contacts manually to Mautic - or Leads / Contacts to open source vTiger 7 - has no sync / push whatsoever.

**Comment by mabumusa1** [comment] 2020-03-10 14:52
I am building a connector for Mautic using Integromat, if you are interested to try it out, please use the link below.

It is still beta, so any feedback is really appreciated.

https://www.integromat.com/en/apps/invite/8b0395a5c92243ebe90adf89113bc6a4

**Comment by MyBpoConsultant** [comment] 2020-03-10 18:13
thank you for this,  I will be keeping an eye on it ... Interested to see
how well the point sync works with a CRM as it tends to only update once
with other sync apps...

**Comment by RCheesley** [comment] 2020-03-11 08:55
> I am building a connector for Mautic using Integromat, if you are interested to try it out, please use the link below.
> 
> It is still beta, so any feedback is really appreciated.
> 
> https://www.integromat.com/en/apps/invite/8b0395a5c92243ebe90adf89113bc6a4

Hi there, this is not the appropriate place to be sharing commercial offerings. We have the commercial category on the forum for sharing commercial offerings - https://forum.mautic.org/c/commercial - or the third-party addons category for discussing plugins you're working on/offering: https://forum.mautic.org/c/3rd-party-addons.

I'll remove the post above, please add your invite to the relevant category on the forums.

**Comment by RCheesley** [comment] 2020-07-29 12:29
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by MyBpoConsultant** [comment] 2020-07-30 19:28
> @MyBpoConsultant, where did you see this information that mautic plugin just works on cloud version?! I'm trying to integrate with booth, cloud and open source and got same problem.

---------

I actually figures this out on my own. The documentation is wrong but after testing multiple instances I can definitely confirm that the cloud version works and open source or vtiger does not. However, out of all my testing, leads bridge works very well with the mautic API. Integromat works okay but leads bridge has been the best so far and you have to work with segments and tags ...

**Comment by RCheesley** [comment] 2020-07-30 19:50
@MyBpoConsultant would you be able to update the docs? There is a super simple edit link at the bottom of every page which allows you to edit in the GH UI.

I will leave this open as it seems that there is still a problem with the synchronisation.

**Comment by Plato39** [comment] 2020-07-31 10:04
As others have already said open source Mautic Vtiger integration is one way.  I've been using it successfully in this limited (but still useful) capacity for many months.  I suspect this is by design - but without documentation, who knows?

**Comment by Plato39** [comment] 2020-07-31 10:09
Incidentally Zapier do not support self hosted Vtiger. When I asked them about this they told me that Vtiger only allow them to offer the cloud version integration. A similar thing is probably happening here.

**Comment by cloudpotions** [comment] 2020-08-07 02:29
> Incidentally Zapier do not support self hosted Vtiger. When I asked them about this they told me that Vtiger only allow them to offer the cloud version integration. A similar thing is probably happening here.

I can confirm that Zapier only works with Cloud version of Vtiger. HOwever, I was able to get this to work with LeadsBridge and Integromat. LeadsBridge is easier if you dont a GUI based approach but Integromat is very powerful. By memory I think LeadsBridge might have been the only one to do 2 way sync though...

**Comment by cloudpotions** [comment] 2020-08-07 02:30
> @MyBpoConsultant would you be able to update the docs? There is a super simple edit link at the bottom of every page which allows you to edit in the GH UI.
> 
> I will leave this open as it seems that there is still a problem with the synchronisation.

Hello - Yes I can update the docs

**Comment by cloudpotions** [comment] 2020-08-14 03:00
Just an update to this thread. Autoize claims that you can actually update contacts in Vtiger by running a campaign that will merge the data from updated Mautic Data to Vtiger. I am not sure if this works but will be testing.... Please see below 
https://autoize.com/mautic-crm-integration/

https://autoize.com/mautic-crm-integration/

Autoize: If the updated contact details from Mautic should ever be reflected in vTiger, the contact canbe pushed again with the “Push Contact to Integration” action, and the records will be automatically merged based on the primary email field (unique identifier). A Mautic campaign can be scheduled to do this for selected segments (i.e. Contact Source) at a regular time interval (e.g. hourly or daily).

**Comment by cloudpotions** [comment] 2020-09-05 18:18
@RCheesley Hi everyone. I can confirm that the vtiger plugin works with the Mautic (3.0.2). It will  sync to Open Source Vtiger CRM (hosted with a SSL certificate) --  with a push one way (Push to integration). It does not update though. I also got points too work. I am using Mautic 3.0.2 and Vtiger 7.1.0 (I used Installatron on a Plesk server (Ionos VPS Ubuntu) to install both instances and they work perfect). Here is what I would like to know though - Autoize website claims that you can create a campaign in Mautic to "push to integration" with an update. I have been trying to create a campaign to do this but I cannot find a way because it only seems to immediately push a contact once it first joins a segment within a campaign (no way to re-push) ?? .

 Do you think there is a way in Mautic to trigger an update campaign and then push to integration? Furthermore, I am not sure how the duplicate check works in Vtiger if it will even merge (In Vtiger you can go to Settings, Module, Leads Fields and Layout and then select Duplicate Check. For incoming via Vtiger Api it has 3 options a) Prefer Latest Record b) Prefer Internal c) Prefer External --- if you do a CSV import it has a merge option but I am not sure if the 3 options via API import have this feature... If we can figure this out guys then we have this Vtiger plugin perfected!! :) @edtaaffe @r1lita @sensalot

**Comment by RCheesley** [comment] 2020-09-10 18:17
I think that those questions would be best placed at https://forum.mautic.org @MyBpoConsultant so I will close down this old issue which seems to no longer be relevant. Please do make an update to the documentation if it is needed!

**Closed by RCheesley** 2020-09-10 18:17 UTC
Labels: bug, pending-feedback, plugin, triage-mautic-3

**Comment by cloudpotions** [comment] 2021-08-30 22:38
> @MyBpoConsultant, where did you see this information that mautic plugin just works on cloud version?! I'm trying to integrate with booth, cloud and open source and got same problem.

updated:  If you go use /webservice.php (For example, https://YourVtigerUrl.com/webservice.php ) at the end of your starting URL, it will work.
