### ISSUE TITLE
Segment Filters using "date"-Field and operator "empty/not empty" break Segemts:update

### ISSUE THREAD

**Issue by LeonOltmanns** [mautic/mautic#10686] opened 2021-12-15 12:19 UTC
### Mautic Version

4.1.1

### PHP version

7.4

### What happened?

When creating a segment with a filter on a date field like "Date Last Active" or "Date Identified" and then using the "empty" or the "not empty" operator, the segment wont work. 

But what makes thing worse is that the mautic:segments:update command or cron will stop as soon as it tries to put contacts in this Segment, thus not updating any Segments after that.

Here you can see the SQL-error provided when using mautic:segments:update:
![image](https://user-images.githubusercontent.com/55587275/146185097-5feb034a-10f8-46e5-be0e-cb473d8d5a48.png)

I tested this against Mautic 4.x and Mautic 3.3.4, both times resulting in the same error. 

### How can we reproduce this issue?

1. Create Segment
2. Use Filter on a date-field like "Date last active" or "Date identified" etc.
3. Save the Segment
4. Use Terminal to navigate to your Mautic-Instance htdocs-folder
5. Use the command "mautic:segments:update"
6. See the errors for yourself

### Relevant log output

```shell
[2021-12-15 12:16:09] mautic.ERROR: Segment QB: Query Exception: An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par7.lead_id AS par7_lead_id FROM leads l LEFT JOIN lead_lists_leads par7 ON par7.lead_id = l.id and (par7.leadlist_id = 52) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (par7.lead_id IS NULL)) sss':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' {"query":"SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par7.lead_id AS par7_lead_id FROM leads l LEFT JOIN lead_lists_leads par7 ON par7.lead_id = l.id and (par7.leadlist_id = 52) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (par7.lead_id IS NULL)) sss","parameters":{"par6":null}} []
[2021-12-15 12:16:09] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par7.lead_id AS par7_lead_id FROM leads l LEFT JOIN lead_lists_leads par7 ON par7.lead_id = l.id and (par7.leadlist_id = 52) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (par7.lead_id IS NULL)) sss':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' (uncaught exception) at /var/www/m4test.mautic2.leuchtfeuer.com/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 while running console command `mautic:segments:update` [] []
[2021-12-15 12:16:09] mautic.WARNING: Command `mautic:segments:update` exited with status code 1 [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LeonOltmanns** [comment] 2022-01-07 09:24
Edit:

```
In AbstractMySQLDriver.php line 128:

  An exception occurred while executing 'SELECT count(leadIdPrimary) count, m
  ax(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.i
  d as leadIdPrimary, parm.lead_id AS parm_lead_id FROM leads l LEFT JOIN lea
  d_lists_leads parm ON parm.lead_id = l.id and (parm.leadlist_id = 66) WHERE
   ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (l.dat
  e_identified = ?) AND (parm.lead_id IS NULL)) sss' with params ["2022-01-08
  "]:

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''


In Exception.php line 18:

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''


In PDOStatement.php line 112:

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''

```

**Comment by kuzmany** [comment] 2022-01-27 09:43
Already fixed by https://github.com/mautic/mautic/pull/10194 
Please test

**Comment by escopecz** [comment] 2022-02-18 14:47
Reopening because https://github.com/mautic/mautic/pull/10194 is fixing the same problem for reports, not segments.

**Comment by kayacekovic** [comment] 2022-07-20 15:58
i updated `applyQuery` function `notEmpty` case in `app/bundles/LeadBundle/Segment/Query/Filter/BaseFilterQueryBuilder.php` something below. Its worked for me!

```php
            case 'notEmpty':
                $query = [
                    $queryBuilder->expr()->isNotNull('l.'.$filter->getField())
                ];

                if (!$filter->contactSegmentFilterCrate->isDateType()) {
                    $query[] = $queryBuilder->expr()->neq('l.'.$filter->getField(), $queryBuilder->expr()->literal(''));
                }

                $expression = new CompositeExpression(CompositeExpression::TYPE_AND, $query);

                break;
```

**Comment by escopecz** [comment] 2022-07-21 07:31
@kayacekovic what Mautic version do you have? This was fixed by https://github.com/mautic/mautic/pull/11126 in Mautic 4.3

**Closed as completed by escopecz** 2022-07-21 07:31 UTC
Labels: bug, segments

**Comment by kayacekovic** [comment] 2022-07-21 07:36
@escopecz my mautic version is 3.3.4

**Comment by escopecz** [comment] 2022-07-21 07:53
Ok. Makes sense then. Thanks!

**Comment by zaharovrd** [comment] 2022-09-27 06:47
Please reopen...
Version   v4.4.2 
when  

php bin/console mautic:segment:update

Rebuilding contacts for segment 4

In AbstractMySQLDriver.php line 98:
                                                                                                                                 
  An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId   
  FROM (SELECT DISTINCT l.id as leadIdPrimary FROM leads l WHERE (l.id IN (SELECT par1.lead_id FROM lead_tags_xref par1 WHERE p  
  ar1.tag_id IN ())) AND (l.id NOT IN (SELECT par2.lead_id FROM lead_lists_leads par2 WHERE par2.leadlist_id = ?))) sss' with p  
  arams [4]:                                                                                                                     
                                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspon  
  ds to your MariaDB server version for the right syntax to use near '))) AND (l.id NOT IN (SELECT par2.lead_id FROM lead_lists  
  _leads par2 WHERE pa...' at line 1                                                                                             
                                                                                                                                 

In Exception.php line 18:
                                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspon  
  ds to your MariaDB server version for the right syntax to use near '))) AND (l.id NOT IN (SELECT par2.lead_id FROM lead_lists  
  _leads par2 WHERE pa...' at line 1                                                                                             
                                                                                                                                 

In PDOStatement.php line 117:
                                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspon  
  ds to your MariaDB server version for the right syntax to use near '))) AND (l.id NOT IN (SELECT par2.lead_id FROM lead_lists  
  _leads par2 WHERE pa...' at line 1

**Comment by kuzmany** [comment] 2022-09-27 12:17
@zaharovrd from your logs it's not clear If is related to this date time issue.

**Comment by zaharovrd** [comment] 2022-09-27 12:20
I understood what the problem is.
I created a segment. It created an empty condition "if the contact contains a tag" and did not specify anything in the value of the tag.

Now I filled in the value of the tag and the segments were updated.

But I think it's not very good when, due to non-filling of the conditional tag in 1 segment, all segments stop updating.

**Comment by kuzmany** [comment] 2022-09-27 12:30
@zaharovrd should fixed https://github.com/mautic/mautic/pull/11253 in 4.4.1

Please create new issue If need it
