### ISSUE TITLE
Editing email with builder doesn't not succeed

### ISSUE THREAD

**Issue by meggiebbq** [mautic/mautic#2481] opened 2016-09-06 12:37 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y |
| Feature request? | N | 
| Enhancement? | N |

## Description:
When editing an exisiting Template Email (Oxygen) with the builder, whatever the changes I make, I am unable to close the builder, it keeps working, and I lose my changes. No matter if the email is published or not, it is still not updating.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | revision 5c8b5d63855e0479c47e1389a0b61ac3e7617e8a |
| PHP version | 5.6.23 |

### Steps to reproduce:
1. Create an email with the builder and the Oxygen theme
2. Make some changes
3. Close the builder
4. Apply
5. Click the edit button
6. Go back to the builder
7. Make some changes
8. Close the builder
 
### Log errors: 

No related log errors.

**Comment by altomarketing** [comment] 2016-09-07 02:18
I have the same issue, the problem is only with Oxygen, i try a test with the template oxygen, save and after that if i try to edit.
1. the page/ superior bar keeps loading
2. editor is broken
3. text body dissapear ..
![mautic](https://cloud.githubusercontent.com/assets/474889/18297592/2ad6c4e6-7488-11e6-9aca-9f1dc08dadd9.PNG)

**Comment by escopecz** [comment] 2016-09-07 07:34
@altomarketing Oxygen theme is fixed here: https://github.com/mautic/mautic/pull/2474

**Comment by escopecz** [comment] 2016-09-07 07:36
I'll close this issue as duplicate of https://github.com/mautic/mautic/issues/2436

**Closed by escopecz** 2016-09-07 07:36 UTC

**Comment by chasebros** [comment] 2016-09-16 16:02
Same issue here:
<img width="1498" alt="screen shot 2016-09-16 at 10 01 50 am" src="https://cloud.githubusercontent.com/assets/15108978/18592537/a61a7918-7bf4-11e6-8464-72cb4e54a130.png">
