### ISSUE TITLE
mautic:campaigns:update runs in an infinite loop after manually removing the contact from the campaign

### ISSUE THREAD

**Issue by MadlenF** [mautic/mautic#11484] opened 2022-09-19 11:35 UTC
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you have a campaign, that starts from a segment and you then remove the contact manually from that campaign, but not from the starting segment, the mautic:campaigns:update will run infinitely (and might also cause that other jobs don't start). 

### How can we reproduce this issue?

Step 1:  Create a Segment
Step 2: Build a simple campaign, where re-entering is allowed. The campaign starts from the segment you just created
Step 3: Create a contact and put it into the segment
Step 4: Run mautic:campaigns:update & mautic:campaigns:trigger for the campaign. 
Step 5: Remove the contact manually from the campaign (via the dropdown in the contact)
Step 6: Run mautic:campaigns:update again and see it's running infinitely. 

![image](https://user-images.githubusercontent.com/87804194/191007786-42623aae-7600-49bb-aeb8-481b3314e727.png)

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-09-19 11:57
This is a duplicate of #11061 and is already resolved in #11318 so closing this issue.

**Closed as completed by RCheesley** 2022-09-19 11:57 UTC
Labels: bug, needs-triage
