### ISSUE TITLE
libraries.js has file paths on install

### ISSUE THREAD

**Issue by ullfindsmit** [mautic/mautic#13076] opened 2023-12-14 00:53 UTC
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After installing, I see javascript errors on my console.
Upon investigation I noticed that there were actual file paths in my libraries.js file instead of javascript.

### How can we reproduce this issue?

Step 1: Clone code from Github to your local stie
Step 2: run composer2 install
Step 3: install app
Step 4: access the mautic login screen

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment] 2024-01-09 08:40
Hi, can you expand on

> there were actual file paths in my libraries.js file instead of javascript.

What does it mean? Did the `composer install` command failed on some step?

**Comment by TonyBogdanov** [comment] 2024-05-02 10:34
I am currently investigating this issue and have managed to track it down to asset generation in: `app/bundles/CoreBundle/Helper/AssetGenerationHelper.php`.

Basically, when `libraries.js` is being generated, a bunch of JS files are loaded one after another and then minified using the `matthiasmullie/minify` package. However, that package simply outputs the path of a JS file instead of its contents in case it does not exist. I can't say if this is a bug, or by design, but it was not an issue before, so it should be irrelevant.

The actual issue is that the `node_modules` folder in Mautic 5 contains only 2 packages: `jquery` and `vimeo-froogaloop2`, so the majority of the JS files being loaded for `libraries.js` do not exist and are replaces with their paths in the final file. This is what the issue is referring to.

I do have to point out that this issue happens when using the official docker image for mautic, so perhaps this repo is not the correct place for the issue. Still, I believe the issue is caused by this line: https://github.com/mautic/docker-mautic/blob/084bcee5cc963379a8c519fe2fad4df8eeb37615/apache/Dockerfile#L62 For some reason the script is deleting all NPM packages except for jquery and vimeo-froogaloop2, but that breaks the on-the-fly media/asset generation.

**Comment by escopecz** [comment] 2024-05-02 14:36
@mollux FYI

**Comment by RCheesley** [comment] 2024-11-11 12:42
I'm going to close this issue in favour of https://github.com/mautic/docker-mautic/issues/281 which seems the appropriate place for this discussion to happen.

**Closed as not planned by RCheesley** 2024-11-11 12:42 UTC
Labels: bug, pending-feedback
