### ISSUE TITLE
Submitting a simple campaign form from default landing page throws error

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8488] opened 2020-02-29 16:29 UTC
#7305  Bug Description
Submitting a campaign form with first name / last name / email with remain at form set on the form and no form actions associated from a Mautic landing page results in an error in the logs, although the lead appears in Mautic (didn't think it did initially, took time to arrive in the lead list!)

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Create a basic campaign form with two text fields for first name and last name connected to the Mautic fields, and a third field for email
2. Set 'remain at form' as the form action and don't assign anything else to the form.
3. Add form to a Mautic landing page using {form=<id>}
4. Try to submit form - it does not complete, and an error is thrown in the logs as below.
 
### Log errors
```
[2020-02-29 16:22:31] mautic.DEBUG: CONTACT: In a Mautic user session  
[2020-02-29 16:22:31] mautic.DEBUG: CONTACT: In a Mautic user session  
[2020-02-29 16:22:31] mautic.DEBUG: FORM: Not in kiosk mode so using current contact ID #  
[2020-02-29 16:22:31] mautic.DEBUG: FORM: Unique fields submitted include newlead2@example.com  
[2020-02-29 16:22:31] mautic.DEBUG: FORM: Potential conflicts 0 = email  
[2020-02-29 16:22:31] mautic.DEBUG: FORM: Current unique contact fields email = newlead2@example.com  
[2020-02-29 16:22:31] mautic.DEBUG: FORM: Submitted unique contact fields email = newlead2@example.com  
[2020-02-29 16:22:31] mautic.DEBUG: FORM: Associating (IP) to contact  
[2020-02-29 16:22:31] mautic.DEBUG: CONTACT: 61 set as current lead.  
[2020-02-29 16:22:31] mautic.DEBUG: LEAD: 61 set as system lead.  
[2020-02-29 16:22:31] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getType() on null" at /var/app/current/code/pulls/3.x/app/bundles/FormBundle/Event/SubmissionEvent.php line 275 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getType() on null at /var/app/current/code/pulls/3.x/app/bundles/FormBundle/Event/SubmissionEvent.php:275)
[stacktrace]
#0 /var/app/current/code/pulls/3.x/app/bundles/FormBundle/Model/SubmissionModel.php(443): Mautic\\FormBundle\\Event\\SubmissionEvent->setAction(NULL)
#1 /var/app/current/code/pulls/3.x/app/bundles/FormBundle/Controller/PublicController.php(104): Mautic\\FormBundle\\Model\\SubmissionModel->saveSubmission(Array, Array, Object(Mautic\\FormBundle\\Entity\\Form), Object(Symfony\\Component\\HttpFoundation\\Request), true)
#2 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\FormBundle\\Controller\\PublicController->submitAction()
#3 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#4 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#5 /var/app/current/code/pulls/3.x/app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#6 /var/app/current/code/pulls/3.x/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/app/current/code/pulls/3.x/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/app/current/code/pulls/3.x/app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/app/current/code/pulls/3.x/app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/app/current/code/pulls/3.x/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/app/current/code/pulls/3.x/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/app/current/code/pulls/3.x/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#13 /var/app/current/code/pulls/3.x/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#14 /var/app/current/code/pulls/3.x/index.php(6): require_once('/var/app/curren...')
#15 {main}
"} 
```

**Comment by RCheesley** [comment] 2020-02-29 16:30
![](https://github.trello.services/images/mini-trello-icon.png) [Forms > Campaign Form > Submit action remain at form](https://trello.com/c/MT4dQfiB/174-forms-campaign-form-submit-action-remain-at-form)

**Comment by RCheesley** [comment] 2020-02-29 16:33
![](https://github.trello.services/images/mini-trello-icon.png) [Forms > Standalone form > Submit Action: remain at form](https://trello.com/c/KHQdI3s6/188-forms-standalone-form-submit-action-remain-at-form)

**Comment by escopecz** [comment] 2020-03-05 12:22
Duplicate of https://github.com/mautic/mautic/issues/8469, fixed by https://github.com/mautic/mautic/pull/8474

**Closed by escopecz** 2020-03-05 12:22 UTC
Labels: Bug, Forms, Mautic 3
