### ISSUE TITLE
Issue with Redirect URL for forms

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#605] opened 2015-07-03 06:48 UTC
I set up an standalone form for collecting eMail addresses. My issue is that the Redirect URL is not shown. I only the the following URL in the Browser: https://different-thinking.de/mautic/form/submit?formId=8

Form is at: http://different-thinking.de/newsletter/ 
I'm using Thrive Content Builder for that landing page.

Redirect should be: https://different-thinking.de/newsletter/

Robert

**Comment by escopecz** [comment] 2015-07-03 12:26
Can you make a screanshot of what you see when you visit https://different-thinking.de/mautic/s/forms/edit/8 ?
(upload screenshot here to drag&drop it to the comment textarea)

**Comment by johnmckenzie** [comment] 2015-07-08 15:15
Hi there, I am facing a similar issue which I posted on the community forum [here](https://www.mautic.org/community/index.php/510-looking-for-wordpress-plugin-popup-with-exit-intent-that-works-). There have also been previous similar issues highlighted in the community forum [here](https://www.mautic.org/community/index.php/491-integration-of-form-into-wordpress-via-html-didn-t-work-right) and [here](https://www.mautic.org/community/index.php/419-how-to-assign-download-and-asset-action-v-1-1).

I have a popup that is displayed with exit intent behaviour on my home page. The form has been set-up as a standalone form in the Mautic backend. I have used the 'manual copy' method to insert the Mautic code into the popup. The popup asks for a name and an email address. Currently the popup is displayed successfully and when I submit the form the lead data is passed successfully to Mautic. However, upon submission I'm taken to the following URL http://example.com/mautic-master/form/submit?formId=1 where I get a blank white screen and **no redirect back** to the specified thank you page.

**Current setup**

* Self hosted version of Mautic (latest version)
* Wordpress version 4.2.2
* Running 2015 theme (default on wordpress install)

**Image of source code of page with blank white screen is attached**

![example_screenshot](https://cloud.githubusercontent.com/assets/10623269/8573978/48e6967e-258c-11e5-95cc-76cf34915a63.jpg)

I have also reproduced the same issue on the hosted version of Mautic.

Kind Regards

John

**Comment by escopecz** [comment] 2015-07-08 15:37
Hi, could you make a little test to determine where the problem is? Could you go to the public preview of the form which can be found at http://path-to-your-mautic/form/1 and submit the form there? Does the redirect work there?

**Comment by johnmckenzie** [comment] 2015-07-08 15:40
Hi there, yes the redirect works when I submit via the public preview.

**Comment by escopecz** [comment] 2015-07-08 17:06
That's great progress. Now, could you compare source code of the form from the Mautic public page and from your website? There must be something missing.

**Comment by johnmckenzie** [comment] 2015-07-09 10:52
Hi, I can see that the Mautic method is to use an iframe to post form data to the backend? I have managed to hack a workaround using my plugin (Ninja popups) and have a working version. Am I correct in assuming that if your browser physically redirects you to a url like  http://domainname.com/mautic-master/form/submit?formId=1  upon submitting the form then it should be a red flag that you are missing the iframe code in your form code?

The plugin I'm using inserts a hidden field into the form for redirects e.g to a thank you page. I still have to track down the location of the function dealing with this feature. So at the moment the plugin is dealing with the redirect **and not** the mautic backend script.

My question would be am I losing any tracking capability etc. if I **don't** have Mautic handling the redirect upon form submission? Everything else works fine e.g leads are recorded in the Mautic backend.

Kind Regards

John

**Comment by escopecz** [comment] 2015-07-09 11:42
Hi, when you mentioned missing iframe I remembered testing this PR: https://github.com/mautic/mautic/pull/589

So this issue should be fixed in upcoming version 1.1.3.

I don't understand the second and third paragraph. I guess that's logic of your plugin? Mautic cannot track the data if there is a redirect before it gets the data. Not sure what can be done from the Mautic side.

**Comment by johnmckenzie** [comment] 2015-07-09 15:29
That is awesome thanks for highlighting the PR! I've updated now and it works perfectly.

**Comment by alanhartless** [comment] 2015-07-13 02:02
Just adding to this that Mautic does expect an iframe to be present that the PR John referred to dynamically adds it via JS if missing.  However, if you want to bypass the iframe method all together, be sure to remove the hidden messenger input from the copied HTML which tells Mautic to respond with JS rather than HTML.

**Comment by alanhartless** [comment] 2015-07-13 02:04
Closing this as it's a known issue with 3rd party applications that strip out iframe and/or JS.  The PR should fix the iframe as long as the JS is included.  If the 3rd party editor strips out the JS as well, then the JS needs to be manually added via the template or some other method.  Or remove the hidden messenger input so that it behaves as a standard form submission (of course client side validation will not occur if the 3rd party editor removes the JS as well and it is not added via some other method).

**Closed by alanhartless** 2015-07-13 02:04 UTC
