### ISSUE TITLE
Problems with email tracking pixel

### ISSUE THREAD

**Issue by aantoniotech** [mautic/mautic#11991] opened 2023-02-17 19:50 UTC
### Mautic Version

4.4.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The tracking pixel in emails does not load and does not record the opening of the email.
But if I load the url of the pixel in a separate tab, it registers the opening.
After opening the email, an email is scheduled to be sent, but it is never sent, unless the tracking pixel gif is opened in a new tab.

<img width="787" alt="mautic1" src="https://user-images.githubusercontent.com/53708159/219776768-68f3b5dc-f926-4b93-8215-66aaaf73f467.png">
<img width="843" alt="mautic2" src="https://user-images.githubusercontent.com/53708159/219776795-e2209332-e072-4def-b110-f26c88d46e21.png">

### How can we reproduce this issue?

Step 1: 

### Relevant log output

```shell
Web Bug from https://mydomain.com/email/63efd77371c25269430939.gif
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2023-02-20 09:21
Out of interest, are you writing long emails that are clipped in the email provider? This can prevent the pixel being fired.

Either way, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by jos0405** [comment] 2023-03-26 17:30
Hi,
Are you testing in the same browser as you are logged in into Mautic as admin?
That is a common error. I will close it for now, as I can't reproduce it.
Plz feel free to reopen.

**Closed as completed by jos0405** 2023-03-26 17:30 UTC
Labels: bug, needs-triage
