### ISSUE TITLE
GrapesJS Facebook icon is served from mailjet.com

### ISSUE THREAD

**Issue by tkima** [mautic/mautic#10491] opened 2021-09-29 19:56 UTC
### Mautic Version

4.0.1

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Facebook icon is served from mailjet.com not from your own media map. 
If you include the socials in the e-mail from the e-mail builder.

### How can we reproduce this issue?

Step 1: Go to email builder
Step 2: Add socials block
Step 3: Send the test mail to your inbox

The Facebook icon is served from mailjet.com in the email. It would be better this would be from the media map.

### Relevant log output

```shell
File: 
mautic/plugins/GrapesJsBuilderBundle/Assets/library/js/dist/builder.js

Code, two lines with:
src:"".concat(r="https://www.mailjet.com/images/theme/v1/icons/ico-social/","facebook.png")
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2021-09-30 10:17
Thanks for raising this @tkima - it's already being tracked here: https://github.com/mautic/mautic/issues/9992 so I will close this issue as a duplicate of that one.

**Closed as completed by RCheesley** 2021-09-30 10:17 UTC
Labels: bug, duplicate, needs-triage
