### ISSUE TITLE
Broken Avatar on Clean Install 2.8.2

### ISSUE THREAD

**Issue by MarvinSk** [mautic/mautic#4210] opened 2017-06-08 13:06 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Seems like the avatar URL is still broken. 

Why is the URL generation process adding "i2.wp.com" to the URLS?????

IMPORTANT NOTES ABOUT MY SETUP:

"domain" replaces my real domainname
"mautic" replaces my real subdir name

URL: https://apps.domain.com/mkt/mautic  <---I am using two subfolders from the root

The inspector show this URL being generated:
<img src="https://www.gravatar.com/avatar/6136b6224705ba6c65ae5adb0944a105?s=250&amp;d=https%3A%2F%2Fapps.domain.com%3A443%2Fmkt%2Fmautic%2Fmedia%2Fimages%2Favatar.png">

The above URL resolves to the following:
https://i2.wp.com/apps.domain.com/mkt/mautic/media/images/avatar.png?ssl=1

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 5.6.29-0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
<img src="https://www.gravatar.com/avatar/6136b6224705ba6c65ae5adb0944a105?s=250&amp;d=https%3A%2F%2Fapps.domain.com%3A443%2Fmkt%2Fmautic%2Fmedia%2Fimages%2Favatar.png">

https://i2.wp.com/apps.domain.com/mkt/mautic/media/images/avatar.png?ssl=1

**Comment by escopecz** [comment] 2017-07-03 09:48
Seems like a duplicate of https://github.com/mautic/mautic/issues/3709

**Closed by escopecz** 2017-07-03 09:48 UTC

**Comment by aspiers** [comment] 2019-06-02 16:13
Looks more like a duplicate of #3382 to me.
