### ISSUE TITLE
Feature rquest: View which leads opened/clicked emails

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#1597] opened 2016-04-14 00:54 UTC
In email view (e.g. /s/emails/view/18), we can see which links were clicked / unique clicked.
It will be good to be able to click through and view which leads performed those clicks.

Also it would be good to be able to see which leads (recipients) opened the email. I know this is possible in a custom report, but to have this info available on the email/view page would be very useful.

**Comment by escopecz** [comment] 2016-04-14 06:48
Duplicate of https://github.com/mautic/mautic/issues/851 and https://github.com/mautic/mautic/issues/1579

**Closed by escopecz** 2016-04-14 06:48 UTC

**Comment by ganeshsoftee** [comment] 2018-05-18 05:39
How do I set it up that points are added  E mail  website url clickl?
