### ISSUE TITLE
Problem managing images

### ISSUE THREAD

**Issue by vihuarar** [mautic/mautic#1503] opened 2016-03-04 16:01 UTC
## Description
I have problems uploading or inserting media after the upgrade to 1.3 version...
its an infinite loading
## Steps to reproduce
just try to insert an image to the email.. or to upload to the server

See this short video:
https://www.dropbox.com/s/wcjzgusgta61jyd/problem%20-%20mautic%20-%20gallery.avi?dl=0

**Comment by escopecz** [comment] 2016-03-08 09:04
Seems like duplicate of https://github.com/mautic/mautic/issues/1499

**Closed by escopecz** 2016-03-08 09:04 UTC

**Comment by klausvogel** [comment] 2016-06-11 15:56
For me, it seems like having wrong default path. If you delete "lang", you have access to your local files, you can select files but the udload button is not active and the whole html form is not working correct.
Are there any new fixes or solutions?
