### ISSUE TITLE
1.4 - error 500 on email preview

### ISSUE THREAD

**Issue by Dcoutelle** [mautic/mautic#1707] opened 2016-05-09 15:28 UTC
## Description
error 500 on email preview

## Steps to reproduce
- on 1.4 fresh install, create a New Segment Email with at least one link in the body.
- save this email
- come back and preview ==> error 500

**Comment by escopecz** [comment] 2016-05-09 15:49
Seems like duplicate of https://github.com/mautic/mautic/issues/1692

**Closed by escopecz** 2016-05-09 15:49 UTC
