### ISSUE TITLE
dropdown menu at bottom of page

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9327] opened 2020-10-22 00:47 UTC
## Bug Description
On a contact detail page, the dropdown menus are not showing all items in the list if they are at the bottom. Although you have scrolled all the way down on the page, you have to click on the dropdown list, then move away with the cursor and scroll again on the page, so all items in the dropdown become visible on the page.

| Q   | A
mautic 3.1.2 rc
php 7.3.22 

### Steps to reproduce
1. go to a contact detail page. if there is no dropdown field at the bottom of the page, create a custom field with 5-6 items.
2. scroll down all the way on the detail page.
3. click on the dropdown field so the list becomes visible.
3. some of the entries are not visible, since the dropdown list is extending beyond the page.
 
Suggestion:
Create a bigger footer area, or check the available space, so the dropdown list is shown maybe above the field, so all items become available or the dropdown list should be scrollable.

Screenshot:
![mautic-dropdown](https://user-images.githubusercontent.com/35775329/96805005-d9245000-1410-11eb-9948-99a54e0db2cf.gif)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-12-11 15:21
Closing this as a duplicate of https://github.com/mautic/mautic/issues/8674

**Closed as completed by RCheesley** 2020-12-11 15:21 UTC
Labels: duplicate
