### ISSUE TITLE
Emails impossible to edit after upgrading to 2.8.1

### ISSUE THREAD

**Issue by appscaptain** [mautic/mautic#4145] opened 2017-05-24 13:59 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have about 30 e-mails created with the “Blank” template in Mautic 2.1.1. After upgrading to Mautic 2.8.1 their content have disappeared. I can’t see it or edit it anywhere.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0

### Steps to reproduce:
1. Create e-mail with Mautic 2.1.1 using the Blank template
2. Upgrade to Mautic 2.8.1 and try to edit that mail
3. There's no way to see or edit the content.

**Comment by escopecz** [comment] 2017-05-24 20:10
Duplicate of https://github.com/mautic/mautic/issues/3032

**Closed by escopecz** 2017-05-24 20:10 UTC
