### ISSUE TITLE
Mautic From Outcome Behavior is Not Executed on Client Side When Mautic Base URL is Not Root

### ISSUE THREAD

**Issue by leonidr** [mautic/mautic#4588] opened 2017-08-04 09:41 UTC
What type of report is this:

Bug report

## Description:
Mautic From Outcome Behavior is Not Executed on Client Side When Mautic Base URL is Not Root
The defect is in this line:
https://github.com/mautic/mautic/blob/f6e32428b5e7d8184139539bd658c811e6c0b4cd/media/js/mautic-form-src.js#L623

## If a bug:

| Q   | A
| Mautic version | 2.9.,2
| PHP version | 7.x

### Steps to reproduce:
1. Deploy mautic to sub-directory
2. Properly defined mautic base url in configuration - e.g. http://domain/subdir
3. Define mautic form
4. Embed the form or try to fill it using preview/direct ur.

In the code 
https://github.com/mautic/mautic/blob/f6e32428b5e7d8184139539bd658c811e6c0b4cd/media/js/mautic-form-src.js#L623
`if (event.origin !== MauticDomain) return; `
event.origin will be equal to "http://domain" while MauticDomain will be equal to "http://domain/subdir"

**Comment by escopecz** [comment] 2017-08-04 09:43
Duplicate of https://github.com/mautic/mautic/issues/4287

**Closed by escopecz** 2017-08-04 09:43 UTC
