### ISSUE TITLE
Last functionning version for HTML emails is still 3.x

### ISSUE THREAD

**Issue by benfavre** [mautic/mautic#11499] opened 2022-09-23 10:13 UTC
### Mautic Version

4.4.x series

### PHP version

8.0.x

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

Can't create new email with custom HTML.
After clicking save, a popup asking to select what kind of email I would like to create opens again.

F.Y.I Haven't been able to use any version since 3.X to send custom HTML.
Do you actually test releases ?

### How can we reproduce this issue?

Create an email, paste the html in the worst textarea in the world, click save.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment] 2022-09-23 12:30
Hello,
Could you plz be more specific: which Mautic version are you using? Also: is this a segment / template email you try to create? Of so, which template are you using?

**Comment by luizeof** [comment] 2022-09-25 17:10
Hello @jos0405 

I couldn't reproduce this issue, it may be something local.

But I have noticed layout problems in emails in code mode. It might have some relationship.

**Comment by benfavre** [comment] 2022-09-27 11:57
I installed 4.4.2 on a dedicated ubuntu server with php 8.0
Tried creating a "manual" email.
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/664679/192517290-2e383895-fe96-49a0-b3a4-5a40eb2361aa.png">

My clients need to paste in HTML from tools that generate the newsletter for them based on MJML templates.
So basically I tried to paste HTML in a new "manual" email.

As I have gathered, right now in 4.x if I don't want my "source HTML" to be messed with, I "only" have a silly textarea in advanced
<img width="937" alt="image" src="https://user-images.githubusercontent.com/664679/192517682-12383dd5-0c29-46bc-a0cb-0668f610ac17.png">
I no longer have 4.x installed so you have to imagine the textearea that says HTML instead of plain text.

When I paste my HTML and attempt to save the new "manual email", the first popup opens again and no email is created.

I reverted once again to 3.x because it still has a workable editor for HTML emails.
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/664679/192518287-7ffc7a24-fdf4-4836-8247-d5b7867efc9a.png">

I regularly try new releases and have 18 mautic installs with various configurations. Nginx/PHP with dedicated servers.

All of them are still using mautic 3.x because the GrapesJS based editor is unworkable for generated HTML.
Source is altered, conditionnal comments get screwed and emails no longer get delivered to older clients.
(A bit off topic ... I previously opened an issue some time ago about that).

**Comment by jos0405** [comment] 2022-10-10 08:38
Hi, there is a new feature in 4.4.0+ (I think) where you can just drop the HTML here:
Choose codemode
![image](https://user-images.githubusercontent.com/4246909/194827491-79faf989-08d5-4bce-bd07-697f4c6cba18.png)
Now you can drop the HTML.
![image](https://user-images.githubusercontent.com/4246909/194827521-f746207f-05f1-4133-bdb3-8fa8b3cc33e6.png)
Yes, there is no editor, just dropping html. It might seem like a step beck, but it's actually a step forward from 2 steps back. Think positive and cheer for the progress.

**Comment by jos0405** [comment] 2022-10-10 08:39
I will close this now, since it's more like a feature request :) If you dom't agree with me, feel free to reopen.

**Closed as completed by jos0405** 2022-10-10 08:39 UTC
Labels: bug, builder-grapesjs
