### ISSUE TITLE
Error: when click on new forms -  I get no response no showing the modal forms window

### ISSUE THREAD

**Issue by AlexanderGoerlich** [mautic/mautic#9059] opened 2020-08-07 09:54 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.16
| Browser |  Chrome  Version 84.0.4147.105 (Official Build) (64-bit)

### Steps to reproduce
1.  Click on Forms 
2.  Click on new Forms

You will see nothing will happen.
 
### Log errors
libraries.js?v0e626066:766 GET https://mydomain.us/forms/new?_=1596793707890&mauticUserLastActive=2&mauticLastNotificationId= 500 (Internal Server Error)
send @ libraries.js?v0e626066:766
ajax @ libraries.js?v0e626066:744
Mautic.loadContent @ app.js?v0e626066:40
Mautic.ajaxifyLink @ app.js?v0e626066:103
(anonymous) @ app.js?v0e626066:88
dispatch @ libraries.js?v0e626066:465
elemData.handle @ libraries.js?v0e626066:451

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2020-08-11 14:26
Hello @AlexanderGoerlich ! Thanks for your report.

I just did it and it works properly. So i'm scared to do not be able to reproduce. Any change you have more information in browser logs or applications logs ?

**Comment by SavannahSoftware** [comment] 2020-08-16 17:23
I’m having exactly the same issue.

My Mautic version is: 3.0.3
My PHP version is: 7.3.20

I’ve tried with both Safari and Firefox. Same thing. If you right-click on the “New Form” button, and select “Open in new window”, then the form opens in new windows, but there is no chrome, or ability to go any further from there.

**Comment by SavannahSoftware** [comment] 2020-08-16 17:38
It looks like this is the same issue as:
[https://github.com/mautic/mautic/issues/9016](url)

**Comment by RCheesley** [comment] 2020-08-16 17:44
Closing as a duplicate, please refer to #9016 thanks for the link @SavannahSoftware :)

**Closed as completed by RCheesley** 2020-08-16 17:44 UTC
Labels: pending-feedback, forms
