### ISSUE TITLE
After update mautic Save company showing Internal server Error 500

### ISSUE THREAD

**Issue by rkaartikeyan** [mautic/mautic#7469] opened 2019-04-25 03:51 UTC
## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 7.0.33-0ubuntu0.16.04.3
| Browser | Chrome

### Steps to reproduce
1. Goto Companies
2. Add or Edit a company with Custom Multi-select field.
3. Save
 
### Log errors
[2019-04-25 03:42:36] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at /var/www/mautic/vendor/symfony/validator/Constraints/LengthValidator.php line 38 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"string\", \"array\" given at /var/www/mautic/vendor/symfony/validator/Constraints/LengthValidator.php:38)"} []

**Comment by escopecz** [comment] 2019-04-25 13:09
This is duplicate of https://github.com/mautic/mautic/issues/7344. I will leave it open until 2.15.2 will be released so it's still considered a bug.

**Comment by RoyeA** [comment] 2019-05-06 04:20
Have the same issue with multi-select in forms and custom list field.
Using release 2.15.1.

**Comment by Bizcrony** [comment] 2019-05-06 08:58
@RoyeA How did you upgrade ?

**Comment by RoyeA** [comment] 2019-05-06 14:45
@Bizcrony I didn't upgrade, I installed a clean 2.15.1 and tried multi-selection.
But, after applying on top of 2.15.1 changes of  #7375 the issue resolved, and data is stored correctly.

**Comment by npracht** [comment] 2019-05-20 07:23
Fixed in 2.15.2

**Closed by npracht** 2019-05-20 07:23 UTC
Labels: Bug, Ready To Test
