### ISSUE TITLE
Code Mode is changing my HTML. It's not a true code mode.

### ISSUE THREAD

**Issue by isaiahdahl** [mautic/mautic#10572] opened 2021-11-03 16:51 UTC
### Mautic Version

4.0.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I paste code into the GrapeJS editor with code mode as the theme, it makes a bunch of changes to the code to power the GrapeJS editor. ie. adding id's, auto-formatting. stripping out stuff. 

Code Mode is for people that want nothing to do with the editor Mautic provides because they generate their HTML from another source. ie: Litmus Email Builder, Custom implementation, etc ..

In my scenario, I have a custom build email builder that is completely unique to our business. It connects directly with our API so we can pull data and generate emails fast. (We are a music publishing company and often send emails containing lists of songs. Our builder allows us to just type in an ID and it generates an email with all the songs. Wayyyy out of scope for a Mautic template, but it works awesome for us.) Our builder spits out nice, formatted, minified HTML.

We just upgraded to Mautic 4 and now the code mode is all different and it's messing up the code. Adding ID's everywhere, all the minified formatting is lost.

I paste in this:
<img width="856" alt="CleanShot 2021-11-03 at 09 42 48@2x" src="https://user-images.githubusercontent.com/23046374/140104472-76bf719b-a6d4-4fe1-8672-9a5f3fec2d21.png">

After save it looks like this:
<img width="913" alt="CleanShot 2021-11-03 at 09 44 12@2x" src="https://user-images.githubusercontent.com/23046374/140104717-9cee12ac-bdab-4957-b0e3-b8c6629cc7b6.png">

A Code Mode option, and having the ability to edit HTML code for an email are not the same thing.

Am I missing something? 
![CleanShot 2021-11-03 at 09 51 05@2x](https://user-images.githubusercontent.com/23046374/140107615-5c1bf9ff-00c3-466b-bbbc-fcb512eeea53.png)

### How can we reproduce this issue?

Step 1: Use Code Mode to past in email HTML.
Step 2: Save the email
Step 3: Open back up to review the code.
Step 4: Copy the code and string compared to what you pasted in. If you didn't implicitly press any button to format the code, it should be exactly what you pasted in.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by isaiahdahl** [comment] 2021-11-03 17:11
I havn't been able to pinpoint what exactly is going wrong but the formatting and extra stuff that GrapeJS adds is causing my emails to lose their formatting in GMAIL. 

This is the exact same pasted HTML.

Mautic 2.16.5, sending a preview email.
![CleanShot 2021-11-03 at 10 08 24@2x](https://user-images.githubusercontent.com/23046374/140132761-c17b0049-a353-4cfc-9f5e-1385b76a3a8c.png)

Mautic 4.0 sending a preview email. 
![CleanShot 2021-11-03 at 10 08 08@2x](https://user-images.githubusercontent.com/23046374/140132866-150d5504-a346-4dfc-a463-763b2720e681.png)

Seems to look fine in other clients.

**Comment by isaiahdahl** [comment] 2021-11-03 17:15
I have just learned how to turn off the GrapeJS builder. https://docs.mautic.org/en/builders?_ga=2.268173966.1005044082.1635782165-1467733879.1635289998#switching-back-to-the-legacy-builder

This fixes my problem.

But leaving this open for a comment on how this could be addressed for the future. I don't want to lose the support for a true code mode.

**Comment by npracht** [comment] 2021-11-09 12:51
@isaiahdahl can you confirm your issue persists in 4.0.1 ?

**Comment by npracht** [comment] 2021-11-09 12:54
Just did a quick test with this snippet and i face same issue. Code is changed.
```html
<!DOCTYPE html><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" style="" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths responsejs "><head>
  <title></title>
  <!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                                      </head><body style="background: rgb(245, 245, 245); overflow: visible;" class="ui-sortable"><!--<!--[endif]---->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <style type="text/css">
    #outlook a {
      padding: 0
    }
    .ReadMsgBody {
      width: 100%
    }
    .ExternalClass {
      width: 100%
    }
    .ExternalClass * {
      line-height: 100%
    }
    body {
      margin: 0;
      padding: 0;
      -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%
    }
    table,
    td {
      border-collapse: collapse;
      mso-table-lspace: 0;
      mso-table-rspace: 0
    }
    img {
      border: 0;
      height: auto;
      line-height: 100%;
      outline: 0;
      text-decoration: none;
      -ms-interpolation-mode: bicubic
    }
    p {
      display: block;
      margin: 13px 0
    }
  </style>
  <!--[if !mso]><mcomment />>
  <style type="text/css">
    @media only screen and (max-width:480px) {
      @-ms-viewport {
        width: 320px
      }
      @viewport {
        width: 320px
      }
    }
  </style>
  <mcomment /><![endif]-->
  <!--[if mso]>
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
<![endif]-->
  <!--[if lte mso 11]>
<style type="text/css">
  .outlook-group-fix {
    width:100% !important;
  }
</style>
<![endif]-->
  <!--[if !mso]><mcomment />>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css" />
  <style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);
  </style>
  <mcomment /><![endif]-->
  <style type="text/css">
    @media only screen and (min-width:480px) {
      .mj-column-per-100 {
        width: 100%!important
      }
      .mj-column-per-33 {
        width: 33.333333333333336%!important
      }
      .mj-column-px-550 {
        width: 550px!important
      }
    }
  </style>
  <div class="mj-container" style="background-color:#f5f5f5">
    <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;">
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
      <![endif]-->
    <div style="margin:0 auto;max-width:600px" data-section-wrapper="1">
      <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0;width:100%" align="center" border="0" data-section="1">
        <tbody>
          <tr>
            <td style="text-align:center;vertical-align:top;direction:ltr;font-size:0;padding:20px 0;padding-bottom:10px;padding-top:0">
              <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td style="vertical-align:top;width:600px;">
      <![endif]-->
              <div class="mj-column-per-100 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%">
                <table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
                  <tbody>
                    <tr>
                      <td style="word-wrap:break-word;font-size:0;padding:10px 25px;padding-bottom:0" align="center" data-slot-container="1" class="ui-sortable">
                        <div data-slot="text" style="cursor:auto;color:#000;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:10px;line-height:12px;text-align:center">Retour du WebSummit 2021 - <a class="mj-content" href="{webview_url}" style="text-decoration:none;color:inherit" target="_blank">Pour voir cet email en ligne, cliquez ici.</a></div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
    <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;">
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
      <![endif]-->
    <div style="margin:0 auto;max-width:600px;background:#fff" data-section-wrapper="1">
      <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0;width:100%;background:#fff" align="center" border="0" data-section="1">
        <tbody>
          <tr>
            <td style="text-align:center;vertical-align:top;border:1px #d3d3d3 solid;direction:ltr;font-size:0;padding:20px 0">
              <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td style="width:600px;">
      <![endif]-->
              <div style="margin:0 auto;max-width:600px">
                <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0;width:100%" align="center" border="0">
                  <tbody>
                    <tr>
                      <td style="text-align:center;vertical-align:top;direction:ltr;font-size:0;padding:20px 0;padding-bottom:10px;padding-top:0">
                        <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td style="vertical-align:top;width:600px;">
      <![endif]-->
                        <div class="mj-column-per-100 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%">
                          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
                            <tbody>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px;padding-top:0;padding-bottom:5px" align="center">
                                  <table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0" align="center" border="0">
                                    <tbody>
                                      <tr>
                                        <td style="width:150px"><img alt="Webmecanik logo" height="auto" src="https://www.webmecanik.com/wp-content/uploads/logo_header_email.png" style="border:none;border-radius:0;display:block;font-size:13px;outline:0;text-decoration:none;width:100%;height:auto" width="150" /></td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!--[if mso | IE]>
        </td>
      </tr>
      <tr>
        <td style="width:600px;">
      <![endif]-->
              <table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0" align="center" border="0">
                <tbody>
                  <tr>
                    <td style="width:600px" data-slot-container="1" class="ui-sortable"><div data-slot="image"><img alt="" height="auto" src="https://www.webmecanik.com/wp-content/uploads/web-summit2.jpeg" style="border: none; border-radius: 0px; display: block; font-size: 13px; outline: 0px; text-decoration: none; width: 100%; height: auto;" width="100%" class="fr-view" /></div></td>
                  </tr>
                </tbody>
              </table>
              <!--[if mso | IE]>
        </td>
      </tr>
      <tr>
        <td style="width:600px;">
      <![endif]-->
              <div style="margin:0 auto;max-width:600px">
                <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0;width:100%" align="center" border="0">
                  <tbody>
                    <tr>
                      <td style="text-align:center;vertical-align:top;direction:ltr;font-size:0;padding:20px 0;padding-bottom:0">
                        <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td style="vertical-align:top;width:550px;">
      <![endif]-->
                        <div class="mj-column-px-550 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%">
                          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
                            <tbody>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px" align="center" data-slot-container="1" class="ui-sortable">
                                  <div style="cursor:auto;color:#5e0a4f;font-family:Helvetica Neue;font-size:22px;font-weight:300;line-height:22px;text-align:center" data-slot="text">Retour du Websummit 2021</div>
                                </td>
                              </tr>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px" align="center" data-slot-container="1" class="ui-sortable">
                                  <div style="cursor:auto;color:#525252;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:14px;line-height:22px;text-align:center" data-slot="text">Merci pour votre inscription !<br />Nous vous enverrons toutes les informations nécessaires prochainement ! <br /><br /><br />Une question ? Envie d'échanger ? Notre équipe d'experts se tient à votre disposition !</div>
                                </td>
                              </tr>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px" align="center" data-slot-container="1" class="ui-sortable"><div data-slot="text"><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate"><tbody><tr><td align="center" bgcolor="#5e0a4f" style="border:none;border-radius:3px;color:#fff;cursor:auto;padding:10px 25px" valign="middle"><a href="https://www.webmecanik.com/contact/" rel="noopener noreferrer" style="text-decoration:none;background:#5e0a4f;color:#fff;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:13px;font-weight:400;line-height:120%;text-transform:none;margin:0" target="_blank">Nous contacter</a></td></tr></tbody></table></div>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!--[if mso | IE]>
        </td>
      </tr>
      <tr>
        <td style="width:600px;">
      <![endif]-->
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
    <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;">
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
      <![endif]-->
    <div style="margin:0 auto;max-width:600px" data-section-wrapper="1">
      <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0;width:100%" align="center" border="0" data-section="1">
        <tbody>
          <tr>
            <td style="text-align:center;vertical-align:top;direction:ltr;font-size:0;padding:20px 0">
              <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td style="width:600px;">
      <![endif]-->
              <div style="margin:0 auto;max-width:600px">
                <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0;width:100%" align="center" border="0">
                  <tbody>
                    <tr>
                      <td style="text-align:center;vertical-align:top;direction:ltr;font-size:0;padding:20px 0;padding-top:0">
                        <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td style="vertical-align:top;width:600px;">
      <![endif]-->
                        <div class="mj-column-per-100 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%">
                          <table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
                            <tbody>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px;padding-bottom:0" align="center">
                                  <table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0" align="center" border="0">
                                    <tbody>
                                      <tr>
                                        <td style="width:40px" data-slot-container="1" class="ui-sortable"><div data-slot="image"><img alt="" height="auto" src="https://www.webmecanik.com/wp-content/uploads/picto_savoie.png" style="border: none; border-radius: 0px; display: block; font-size: 13px; outline: 0px; text-decoration: none; width: 100%; height: auto;" width="40" class="fr-view" /></div></td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px" align="center" data-slot-container="1" class="ui-sortable">
                                  <div data-slot="text" style="cursor:auto;color:#000;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:10px;line-height:12px;text-align:center">Cet email automatique a été envoyé à {contactfield=email} suite à votre demande en ligne.<br />Made with love in the French Alps<br />Webmecanik - 6, avenue de Thônes - 74000 Annecy - France</div>
                                </td>
                              </tr>
                              <tr>
                                <td style="word-wrap:break-word;font-size:0;padding:10px 25px" align="center">
                                  <div>
                                    <!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" align="undefined"><tr><td>
      <![endif]-->
                                    <table role="presentation" cellpadding="0" cellspacing="0" style="float:none;display:inline-table" align="center" border="0">
                                      <tbody>
                                        <tr>
                                          <td style="padding:4px;vertical-align:middle">
                                            <table role="presentation" cellpadding="0" cellspacing="0" style="background:#424242;border-radius:3px;width:20px" border="0">
                                              <tbody>
                                                <tr>
                                                  <td style="font-size:0;vertical-align:middle;width:20px;height:20px"><a href="https://facebook.com/Webmecanikfr"><img alt="facebook" height="20" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/facebook.png" style="display:block;border-radius:3px" width="20" /></a></td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                          <td style="padding:4px 4px 4px 0;vertical-align:middle"><a href="https://facebook.com/Webmecanikfr" style="text-decoration:none;text-align:left;display:block;color:#333;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:13px;line-height:22px;border-radius:3px"></a></td>
                                        </tr>
                                      </tbody>
                                    </table>
                                    <!--[if mso | IE]>
      </td><td>
      <![endif]-->
                                    <table role="presentation" cellpadding="0" cellspacing="0" style="float:none;display:inline-table" align="center" border="0">
                                      <tbody>
                                        <tr>
                                          <td style="padding:4px;vertical-align:middle">
                                            <table role="presentation" cellpadding="0" cellspacing="0" style="background:#424242;border-radius:3px;width:20px" border="0">
                                              <tbody>
                                                <tr>
                                                  <td style="font-size:0;vertical-align:middle;width:20px;height:20px"><a href="https://plus.google.com/+Webmecanik"><img alt="google" height="20" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/google-plus.png" style="display:block;border-radius:3px" width="20" /></a></td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                          <td style="padding:4px 4px 4px 0;vertical-align:middle"><a href="https://plus.google.com/+Webmecanik" style="text-decoration:none;text-align:left;display:block;color:#333;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:13px;line-height:22px;border-radius:3px"></a></td>
                                        </tr>
                                      </tbody>
                                    </table>
                                    <!--[if mso | IE]>
      </td><td>
      <![endif]-->
                                    <table role="presentation" cellpadding="0" cellspacing="0" style="float:none;display:inline-table" align="center" border="0">
                                      <tbody>
                                        <tr>
                                          <td style="padding:4px;vertical-align:middle">
                                            <table role="presentation" cellpadding="0" cellspacing="0" style="background:#424242;border-radius:3px;width:20px" border="0">
                                              <tbody>
                                                <tr>
                                                  <td style="font-size:0;vertical-align:middle;width:20px;height:20px"><a href="https://twitter.com/webmecanik_fr"><img alt="twitter" height="20" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter.png" style="display:block;border-radius:3px" width="20" /></a></td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                          <td style="padding:4px 4px 4px 0;vertical-align:middle"><a href="https://twitter.com/webmecanik_fr" style="text-decoration:none;text-align:left;display:block;color:#333;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:13px;line-height:22px;border-radius:3px"></a></td>
                                        </tr>
                                      </tbody>
                                    </table>
                                    <!--[if mso | IE]>
      </td><td>
      <![endif]-->
                                    <table role="presentation" cellpadding="0" cellspacing="0" style="float:none;display:inline-table" align="center" border="0">
                                      <tbody>
                                        <tr>
                                          <td style="padding:4px;vertical-align:middle">
                                            <table role="presentation" cellpadding="0" cellspacing="0" style="background:#424242;border-radius:3px;width:20px" border="0">
                                              <tbody>
                                                <tr>
                                                  <td style="font-size:0;vertical-align:middle;width:20px;height:20px"><a href="https://www.linkedin.com/company/269273/"><img alt="linkedin" height="20" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/linkedin.png" style="display:block;border-radius:3px" width="20" /></a></td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                          <td style="padding:4px 4px 4px 0;vertical-align:middle"><a href="https://www.linkedin.com/company/269273/" style="text-decoration:none;text-align:left;display:block;color:#333;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:13px;line-height:22px;border-radius:3px"></a></td>
                                        </tr>
                                      </tbody>
                                    </table>
                                    <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
                                  </div>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!--[if mso | IE]>
          </td>
        </tr>
      </table>
      <![endif]-->
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
  </div>
--></body></html>
```

**Comment by isaiahdahl** [comment] 2021-11-09 16:37
Yea can confirm it's happening in 4.0.1.

**Comment by shekhar677** [comment] 2021-11-18 03:39
> Yea can confirm it's happening in 4.0.1.

It's the same thing with Mautic 4.0.2 also

**Comment by shekhar677** [comment] 2021-11-18 03:55
> I have just learned how to turn off the GrapeJS builder. https://docs.mautic.org/en/builders?_ga=2.268173966.1005044082.1635782165-1467733879.1635289998#switching-back-to-the-legacy-builder
> 
> This fixes my problem.
> 
> But leaving this open for a comment on how this could be addressed for the future. I don't want to lose the support for a true code mode.

Thanks for this solution 👌

**Comment by officialsuyogdixit** [comment] 2021-12-22 11:10
I can confirm that same happening even on 4.1.1. But I just loved GrapeJS builder. Disabling it is not a permanent solution.

**Comment by ghost** [comment] 2021-12-22 14:11
I really hate GrapeJS for Mautic. Now I have got this same problem. GrapeJS modify my code. It delete my CSS for mobile when I update code, for example I tried add something like this:
```
@media all and (max-width: 800px) {
		.mautic_images {
			display: none;
			border: 1px solid #fff;
		}
	
		.mautic_images_mobile {
			display: block;
		}
	
		.mautic_upload  {
			max-width: unset !important;
			width: 100% !important;
			min-height: auto;
		}
	
		.mautic50 {
			width: 100%;
			padding: 0px !important;
		}
  
  		.mautic_images_mobile {
          max-width: 100%;
          border-radius: 10px;
}}
```
This editor doesn't give me adding mobile CSS. 

I alredy prefer the old HTML editor in Mautic.

**Comment by ghost** [comment] 2021-12-28 13:21
I have got next problem with GrapeJS. Now it changing my code with Dynamic Content.

**How can we reproduce this issue?**
Step 1: Make e-mail in GrapeJS editor and add some Dynamic Content,
Step 2: Edit something (like CSS) in HTML editor inner GrapeJS editor.
Step 3: Save and check your code. Your dynamic code is now invisible in GrapeJS and you see only something like: "{dynamiccontent="Dynamic Content 2"}" in email preview.

**Comment by ghost** [comment] 2021-12-29 10:58
I see that problem happened since already on start of M4 and still is without fix. If I had known all my templates on grapesjs would be useless, I wouldn't have upgraded to that version. This is a huge problem.

My client without HTML and CSS knowledge used GrapeJS on M3. I made them Update to M4, and now he could't make working e-mails. Why somebody let new version without inform people about such big bug like this.

**Comment by shmaltz** [comment] 2021-12-29 16:41
Facing the same issue on v4.1.1.

Is this a Mautic issue or a Grapesjs issue?

**Comment by AntoniyaM** [comment] 2022-01-11 09:18
I've been using the new builder for a while now and would say that it works best with MJML code. I think it's in a very good state and appreciate all the great work many people have done to get it this far. 👏

Keep in mind that a lot of issues related to HTML being stripped or altered might have to do with MJML's own validation processes in mjml2html. I've only just started to debug some things and most of the time I can't really tell whether the bug is coming from MJML or the builder integration in Mautic. If you need highly customized auto-generated HTML for your emails just switch to the legacy builder.

**Comment by nazeno** [comment] 2022-01-13 13:52
Glad i have found this thread.

I am new to Mautic and racked my brain trying to figure out why my emails was not working. I was editing with pure code and for some reason the editor always got in my way. I just removed the plugin and now everything is fine! All happy again!

Mautic v4.1.1

**Comment by RCheesley** [comment] 2022-03-29 16:02
Hey folks! Please take a look at #10976 where we are proposing a workaround which allows you to just use a text field to dump in pure HTML without touching GrapesJS (eg like the old code mode). It's a workaround/bug fix while we work on something to address the root of the issues.

**Comment by adiux** [comment] 2022-05-31 15:13
This is fixed with https://github.com/mautic/mautic/pull/11102

**Closed as completed by adiux** 2022-05-31 15:13 UTC
Labels: bug, builder-grapesjs
