### ISSUE TITLE
javascript or cookie visitor tracking

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#1295] opened 2015-12-30 03:44 UTC
Is there any reason why cookies or javascript is not used in addition to using a image pixel to track visitors to our website?  Google Analytics and SiteCounter.com use javascript code that the user embeds into each page to help track them.  

Was wondering why mautic did not use these methods?  What limitations or benefits can be gained

I would think with javascript, we could especially track what part of the webpage the visitor looks at, mouse movements, etc.

**Comment by escopecz** [comment] 2016-01-06 12:24
Cookies are used for the tracking. This issue is duplicate of https://github.com/mautic/mautic/issues/209

**Closed by escopecz** 2016-01-06 12:25 UTC
