### ISSUE TITLE
Contact not added to campaign that uses a segment as source

### ISSUE THREAD

**Issue by cedoe** [mautic/mautic#8129] opened 2019-11-14 14:01 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
To implement double opt-in in one of our campaigns we have the following setup:
1. Create a standalone form with two actions: send an email with the confirmation link for the double opt-in and add the contact to a segment called 'pending'.
2. A campaign uses this pending segment as a source.
3. If the contact visits the confirmation page for the double opt-in the contact is moved to a 'subscribed' segment and another email is sent.

I use the following code to submit the form data to Mautic:
`function pushMauticForm($data, $pathToMautic, $formId, $ip = null)
{
    // Get IP from $_SERVER
    if (!$ip) {
        $ipHolders = array(
            'HTTP_CLIENT_IP',
            'HTTP_X_FORWARDED_FOR',
            'HTTP_X_FORWARDED',
            'HTTP_X_CLUSTER_CLIENT_IP',
            'HTTP_FORWARDED_FOR',
            'HTTP_FORWARDED',
            'REMOTE_ADDR'
        );
        foreach ($ipHolders as $key) {
            if (!empty($_SERVER[$key])) {
                $ip = $_SERVER[$key];
                if (strpos($ip, ',') !== false) {
                    // Multiple IPs are present so use the last IP which should be the most reliable IP that last connected to the proxy
                    $ips = explode(',', $ip);
                    array_walk($ips, create_function('&$val', '$val = trim($val);'));
                    $ip = end($ips);
                }
                $ip = trim($ip);
                break;
            }
        }
    }

    $data['formId'] = $formId;
    // return has to be part of the form data array
    if (!isset($data['return'])) {
        $data['return'] = '';
    }
    $data = array('mauticform' => $data);
    $formUrl =  $pathToMautic . '/form/submit?formId=' . $formId;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $formUrl);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("X-Forwarded-For: $ip"));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($ch);
    curl_close($ch);
    return $response;
}`

The code was taken from this post by John Linhart:
https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005

In 2.15.0 this worked fine: a contact who filled out the form would immediately be added to the campaign and after the confirmation page had been visited the followup email would be sent immediately.

However, after updating Mautic to 2.15.3 the contact is no longer added to the campaign immediately after form submission, but only after the mautic:campaigns:update cronjob had run. If the contact visits the double opt-in confirmation page before that then the page hit would still show up in the contact's history, but the campaign would not continue. The contact's segment is not changed and the next email is not sent.

This problem does not occur if I use the Mautic form directly instead of the above code, but our client wishes to use his own form so that is not possible.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.24
| Browser | 

### Steps to reproduce
1. Create a standalone form with two actions: send an email with the confirmation link for the double opt-in and add the contact to a segment called 'pending'.
2. A campaign uses this pending segment as a source.
3. If the contact visits the confirmation page for the double opt-in the contact is moved to a 'subscribed' segment and another email is sent.
4. Submit form data to Mautic with the code from above.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by ttencate** [comment] 2019-12-31 15:31
We had a similar problem and worked around it by sending the confirmation email not from the sign-up form, but from the 'pending' campaign. This way, by the time the email is sent, you're certain that the contact has been added to the campaign, and the campaign is ready and waiting for the confirmation link to be clicked.

A drawback is that the confirmation email will also be delayed a bit, but this is obviously better than just losing contacts entirely.

**Comment by cedoe** [comment] 2020-01-09 12:59
Thanks for the tip with the pending campaign. As a workaround we have decided to use a 'pending' contact tag instead of a segment or campaign. That way the confirmation email is still sent after form submission.

**Comment by RCheesley** [comment] 2020-02-02 21:15
@cedoe are we OK to close this down as it sounds like quite a specific use case, or is this still a bug which needs addressing in your opinion?

**Comment by ttencate** [comment] 2020-02-03 11:26
@RCheesley This looks like a regression to me, and implementing double opt-in doesn't sound like such an uncommon scenario either.

It could probably be fixed by running the equivalent of the regular cron jobs for this one contact after the form's submit actions have been executed. But I'm no Mautic expert, so take this with a grain of salt.

**Comment by cedoe** [comment] 2020-02-04 15:53
Yes, it is ok to close this. We found a workaround. This only happened with one Mautic version and because we use a script to submit form to Mautic.

**Closed** 2020-02-04 15:53 UTC

**Comment by RCheesley** [comment] 2020-02-18 11:10
@escopecz is there any chance that your code no longer works since 2.15.3 in the article cited above?

**Comment by escopecz** [comment] 2020-02-18 14:16
Yes, that simple script no longer works. The article suggests to use the library instead.
