### ISSUE TITLE
Can't send sms

### ISSUE THREAD

**Issue by web30s** [mautic/mautic#8536] opened 2020-03-07 10:57 UTC
## Bug Description
Can't send sms in campaign

| Q   | A
| --- | ---
| Mautic version | 2.16
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors
[Sat Mar 07 17:51:19.685210 2020] [proxy_fcgi:error] [pid 29463:tid 2582619168] [client 141.101.99.15:36436] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: status in /app/bundles/SmsBundle/Views/SubscribedEvents/Timeline/index.html.php on line 28\nPHP message: PHP Notice:  Undefined index: type in /app/bundles/SmsBundle/Views/SubscribedEvents/Timeline/index.html.php on line 30\nPHP message: PHP Notice:  Undefined index: content in /app/bundles/SmsBundle/Views/SubscribedEvents/Timeline/index.html.php on line 36\n', referer:

Anybody has the same this issue and how can i fix it.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2020-03-08 19:39
Hi @web30s ! Thanks a lot for your message but your message is incomplete. How could we reproduce ? It is working on my side. Can you give a bit more of information ? How is your setup ?

Thanks

**Comment by web30s** [comment] 2020-03-09 02:25
Dear Mautic/Mautic team,

I setup via tivilo plugin and send sms via one compaign. When customer
submit form so sms will send immediately.

**Comment by npracht** [comment] 2020-03-10 09:05
I still need more configuration information. This is not enough to reproduce.
Thanks

**Comment by RCheesley** [comment] 2020-07-29 10:26
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-29 10:26 UTC
Labels: pending-feedback
