### ISSUE TITLE
Multiple Lead Point Scoring Categories

### ISSUE THREAD

**Issue by TornMarketing** [mautic/mautic#7598] opened 2019-06-12 01:03 UTC
Currently Mautic has the ability to score a prospect globally with a point system.

Looking for the ability to score a prospect based on behavioral different events within scoring segments.

For instance, a ecommerce store which has multiple store categories, I would like to track users based on what they are doing within each category, profile them and then assign a score to them.

Outcome being to collect and store category scores, sort the categories based on the most active, then the ability to send product relevant content back to the prospect based on the scores of each category or the most active category (highest score).

This would also be effective for companies that run multiple businesses within the one platform.
Centralised data but personalised experiences.

**Comment by TornMarketing** [comment] 2019-06-12 01:15
Trying to replicate something I had in Pardot
https://www.pardot.com/training/lead-qualification-scoring-categories/ (edited)

Also the ability to send parameter information about each product back through to Mautic to be considered in the category segment scoring

For instance Price points or product specific features and dimensions, ie price, product size, colour, delivery costs, etc
Thinking this would be a webhook to mautic with product information

**Comment by npracht** [comment] 2019-06-25 11:49
Duplicate of https://github.com/mautic/mautic/issues/581
Please share your feedbacks there ! Thanks a lot for contributing.

**Closed by npracht** 2019-06-25 11:49 UTC
