### ISSUE TITLE
Error after update do Mautic 2.2.1 when edit Email

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#2783] opened 2016-10-18 18:54 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | y |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7.0 |
| Cloudflare | no |
| Hosting | VPS |
### Steps to reproduce:
1. Go to Email List
2. Open an Email
3. Fire the button Edit Email
4. The blue progress bar on top runs and stop
5. Nothing Happen. 
### Log errors:

[2016-10-18 16:50:57] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /var/www/html/marketing/app/bundles/EmailBundle/Views/Email/form.html.php on line 213" at /var/www/html/marketingr/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php line 162 {"exception":"[object](Symfony\Component\Debug\Exception\FatalThrowableError%28code: 0%29: Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget%28%29 must be an instance of Symfony\Component\Form\FormView, null given, called in /var/www/html/marketing/app/bundles/EmailBundle/Views/Email/form.html.php on line 213 at /var/www/html/marketingr/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php:162)"} []
[2016-10-18 16:50:57] mautic.ERROR: Notice: Trying to get property of non-object - in file /var/www/html/marketing/app/bundles/EmailBundle/Views/Email/form.html.php - at line 15 [] []

[2016-10-18 17:06:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /var/www/html/marketing/app/bundles/EmailBundle/Views/Email/form.html.php on line 213" at /var/www/html/marketing.ibad.com.br/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php line 162 {"exception":"[object](Symfony\Component\Debug\Exception\FatalThrowableError%28code: 0%29: Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget%28%29 must be an instance of Symfony\Component\Form\FormView, null given, called in /var/www/html/marketing/app/bundles/EmailBundle/Views/Email/form.html.php on line 213 at /var/www/html/marketing/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php:162)"} []
[2016-10-18 17:06:11] mautic.ERROR: Notice: Trying to get property of non-object - in file /var/www/html/marketing/app/bundles/EmailBundle/Views/Email/form.html.php - at line 15 [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-10-18 18:56
Fill in steps to reproduce, please.

**Comment by luizeof** [comment] 2016-10-18 19:01
@escopecz sorry. I just update.

**Comment by escopecz** [comment] 2016-10-18 19:07
I can't replicate. Does it happen to every form or some special form? What fields and action does it have? There is a known bug with the social login field.

**Comment by luizeof** [comment] 2016-10-18 19:09
@escopecz hi jhon. I make a mistake and change the title. It's not on forms ... it's on Email Editor.
I dont have any custom template.

**Comment by escopecz** [comment] 2016-10-18 19:33
Ok. It seems to be related to Dynamic Content because the line 15 is:
```
$filterBlockPrototype    = $form['dynamicContent']->children[0]['filters']->vars['prototype'];
```
I'll mark this as a bug. But could you please confirm that this happens only to emails created before upgrade to Mautic 2.2.0? If you create a new email and edit it, it works OK, right?

**Comment by luizeof** [comment] 2016-10-18 22:07
@escopecz no, any e-mail

**Comment by cristibucur90** [comment] 2016-10-19 12:13
Hello,

I have the same issues like @luizeof 
It applies to all emails after update

Do you think when will be solved? Because we need to edit all these emails and if this will take a while we'll need to recreate all these emails.

Thank you,
Cristi

**Comment by cristibucur90** [comment] 2016-10-28 19:13
Any update for this issue?

**Comment by cristibucur90** [comment] 2016-11-09 09:39
Hello guy,

What happends with this issue. It's a very important bug and we didn't receive any response.

Can you please just give us an answer about this?

Thank you,
Cristi

**Comment by alucmb** [comment] 2016-11-09 11:56
Same here :/

**Comment by robsontecle** [comment] 2016-11-09 13:26
I have decided as follows:
When updating Mautic, I was adding a dynamic_content field to the prefix_emails table. As this field did not exist in previous versions it was null.
To solitate, I created any record in this table with the minimum of possible information, which generated the record:

a:1:{i:0;a:3:{s:9:"tokenName";N;s:7:"content";N;s:7:"filters";a:1:{i:0;a:2:{s:7:"content";N;s:7:"filters";a:0:{}}}}}

I replicated this value to the records that were null and resolved.

I hope they help.
Robson Vieira

**Comment by escopecz** [comment] 2017-03-06 17:30
Will be fixed in 2.7.0

**Closed by escopecz** 2017-03-06 17:30 UTC
Labels: Bug

**Comment by ojorgesilva** [comment] 2017-06-06 13:06
@escopecz I have the same problem in version 2.8 onwards and nothing to solve. And for that reason I can not create a custom field in a custom form.

**Comment by escopecz** [comment] 2017-06-06 13:30
It cannot be the exactly same error. Can you please post the error message from your logs?

**Comment by ojorgesilva** [comment] 2017-06-06 13:36
Yes, I can @escopecz!

[2017-06-06 10:02:15] mautic.WARNING: PHP Warning - Invalid argument supplied for foreach() - in file /home/digital/public_html/marketing/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php - at line 27 [] []
[2017-06-06 10:02:15] mautic.ERROR: PHP Error - Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::errors() must be an instance of Symfony\Component\Form\FormView, null given, called in /home/digital/public_html/marketing/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 31 and defined - in file /home/digital/public_html/marketing/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php - at line 205 [] []

And when I try to add a "Select" field it does not add the field and does not display an error message.

**Comment by ojorgesilva** [comment] 2017-06-06 13:47
I made a short video demonstrating the creation process at this link [ y](https://drive.google.com/file/d/0B9iDP6mCysHva0xmckhUVVEyZDA/view)
