### ISSUE TITLE
SimpleXML / RSS feed issue suddenly occurring on multiple instances of Mautic

### ISSUE THREAD

**Issue by BillyHilly** [mautic/mautic#8283] opened 2020-01-02 16:49 UTC
#7305 Bug Description
This is very odd, but confirmed in Slack that others are experiencing it as well. I'm seeing it on two different instances of Mautic (v.2.14 & v.2.15.3) on two different servers. Error log is different between the two but appears to be the same issue.
Basically, the Mautic Log is flooded with SimpleXML errors.
I'd wager there was an update to the Mautic RSS feed that caused this, likely an incorrect or un-escaped character entity.

| Q   | A
| --- | ---
| Mautic version | both v.2.14.0 AND v.2.15.3
| PHP version | 7.1.33 (v.2.14) AND 7.2.24 (v.2.25.3)
| Browser | Safari

### Steps to reproduce
1. Not sure, just suddenly started showing in the log.
 
#### v.2.14.0 log errors
```
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 741: parser error : Opening and ending tag mismatch: article line 368 and div - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): </div> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():       ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 743: parser error : Opening and ending tag mismatch: div line 362 and article - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): </article> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():           ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 746: parser error : Opening and ending tag mismatch: section line 358 and div - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): </div> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():       ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 748: parser error : Opening and ending tag mismatch: div line 355 and section - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): </section> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():           ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 849: parser error : StartTag: invalid element name - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1 - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():  ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 870: parser error : StartTag: invalid element name - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1 - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():  ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 902: parser error : Entity 'copy' not defined - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Copyright &copy; 2019 Acquia, Inc. All Rights Reserved. Drupal is a - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():                 ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 921: parser error : Opening and ending tag mismatch: body line 57 and div - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): </div> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():       ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 924: parser error : Specification mandate value for attribute defer - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <script src="//fast.wistia.net/assets/external/E-v1.js" defer async></script> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():                                                               ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 924: parser error : attributes construct error - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <script src="//fast.wistia.net/assets/external/E-v1.js" defer async></script> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():                                                               ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 924: parser error : Couldn't find end of Start Tag script line 924 - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <script src="//fast.wistia.net/assets/external/E-v1.js" defer async></script> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():                                                               ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 924: parser error : Opening and ending tag mismatch: html line 2 and script - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <script src="//fast.wistia.net/assets/external/E-v1.js" defer async></script> - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct():                                                                              ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 925: parser error : Extra content at the end of the document - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): <script src="/sites/acquia.com/files/js/js_Ko5Nk9HdCNkfdQ4ZiVUOR7gXNKCQMYiP0XgkE - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): ^ - in file /var/www/html/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []
[2020-01-02 11:28:01] mautic.WARNING: String could not be parsed as XML [] []
```

#### v.2.15.3 log errors 
[mautic_v2-15-3_XML-error-log.txt](https://github.com/mautic/mautic/files/4016618/mautic_v2-15-3_XML-error-log.txt)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by BillyHilly** [comment] 2020-01-02 16:57
Here's the log from v.2.15.3.
Also, this seems to be the same issue cited at #8258 
https://github.com/mautic/mautic/issues/8258#issue-541419031

## v.2.15.3 log

[2020-01-02 16:42:06] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 741: parser error : Opening and ending tag mismatch: article line 368 and div - in file /var/www/html/site/public/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 {"xmlString":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
\n\nSkip to main navigation\n\n
\n 
\n
\n
\n\nX\n\n
\n
\nWe use cookies to offer you a better browsing experience, analyze site traffic, personalize content, and serve targeted advertisements. Read about how we use cookies and how you can control them by clicking "Cookie Settings." If you continue to use this site, you consent to our use of cookies.\n
\n
\n
\n\nCookie Settings \n
\n
\n\nAccept Cookies \n
\n
\n
\n
\n
\n
\n
\n
Privacy Preference Center
\n
\n
\n
\n
Acquia’s websites may request cookies to be set on your device. We use cookies to enrich and personalize your user experience. ....

entire log attached
[mautic_v2-15-3_XML-error-log.txt](https://github.com/mautic/mautic/files/4016612/mautic_v2-15-3_XML-error-log.txt)

**Comment by RCheesley** [comment] 2020-01-06 14:14
Closing this as a duplicate of #8258

**Closed by RCheesley** 2020-01-06 14:14 UTC
Labels: Duplicate
