### ISSUE TITLE
Feature Request: Lead expoort

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#1494] opened 2016-03-02 05:48 UTC
would it be possible, to add the "Export Leads to CSV"-Function to each List?

**Comment by escopecz** [comment] 2016-03-02 10:42
Duplicate of https://github.com/mautic/mautic/issues/597

**Closed by escopecz** 2016-03-02 10:42 UTC

**Comment by OlafDammann** [comment] 2016-03-03 14:10
cool, thanks :)
