### ISSUE TITLE
syntax error, unexpected '[' in pathtomautic/app/bundles/ReportBundle/Model/ReportModel.php on line 708

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#3412] opened 2017-02-12 19:27 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  yes
| Feature request? |  no
| Enhancement? |  no

## Description:
since upgrading to 2.6.0 cron jobs create an error msg:

syntax error, unexpected '[' in pathtomautic/app/bundles/ReportBundle/Model/ReportModel.php on line 708

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 7.0.15

### Steps to reproduce:
1.  run required cronjobs
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-02-12 19:40
Duplicate of https://github.com/mautic/mautic/issues/2198 (suggested fix there as well)

**Closed by escopecz** 2017-02-12 19:40 UTC
