### ISSUE TITLE
New Campaign Action to Make CURL call

### ISSUE THREAD

**Issue by Loanatik** [mautic/mautic#4332] opened 2017-07-02 02:36 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Use Case
From within a campaign I would like to send a physical postcard to a contact.  Products such as [sendwithscout.com](url) have a rich API that would allow us to do this.

When an email bounces I want to create a wunderlist item or trello card to have my admin follow up with the contact and update their information.  

If a contact fails to open an email after creating and account and then ignores the followup email, I want place a call to their sales person and then get the contact on the phone without any physical action being taken by the sales person.

All of these features are available through easy to use APIs, however, none of their functionality is available to mautic users.  Creating a plugin or modifying the mautic core to enable these features is prohibitively complex and risks being out of sync with mautic development.  However, adding the simple ability to call an outside URL and pass parameters would solve this problem very nicely.

## Description:
To allow for easy integration of almost any functionality from within a campaign, we can create an action that when triggered passes control to a user specified URL and also sends as parameters all of the core and custom fields within mautic.  

By creating a simple PHP program outside of mautic, the campaign action would call the program and the program would carry out the user's desired task.  This would enable anyone with basic programming skills and no knowledge of the inner workings of mautic to integrate anything they wanted -- without having to change any code in mautic.   The functionality would be similar to "push to integration" without having to create a plugin or integration.

![image](https://user-images.githubusercontent.com/14249107/27767331-a5b7bfd8-5ea9-11e7-8dd7-ecbb91f19eb1.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-07-03 07:25
This seem like a duplicate of https://github.com/mautic/mautic/issues/854

**Closed by escopecz** 2017-07-03 07:25 UTC
