### ISSUE TITLE
Incorrect Field URL Mapping

### ISSUE THREAD

**Issue by Dylancb** [mautic/mautic#2969] opened 2016-11-17 15:52 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Upon sending emails with custom contact forms, I am having a problem, the custom fields are being mixed up and it is sending other contact's fields. After some testing I can see that the tracking url is being generated wrong (because said field is an URL field). This is being generated before any of the other tokens are. We are not entirely sure whether the url is being generated incorrectly or, if its receiving the wrong URL, either way we have been sending the wrong info out.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6 & 7.0

**Comment by escopecz** [comment] 2017-02-13 14:02
Duplicate of https://github.com/mautic/mautic/issues/2571

**Closed by escopecz** 2017-02-13 14:02 UTC
