### ISSUE TITLE
Bounce handling

### ISSUE THREAD

**Issue by robov** [mautic/mautic#7896] opened 2019-09-27 18:17 UTC
I have setup SES successfully and I can send out emails to my list
However bounce handling I cannot get working. When I send an email to "bounce@simulator.amazonses.com" from my SES account, I see a bounce email coming in my inbox.
However
When I send through mautic, then it seems that this email never goes out... as hooking up to my mailbox.. I get no result
Hooking bouce into callbacks... I get no result

Contact is not updated
No log items
The emails (that should bounce are in the email_copies table as well as in the email_stats

Any ideas ?

**Comment by npracht** [comment] 2019-10-02 15:53
Hi @robov i'll close it as duplicate of other issues, they are a lot already --> https://github.com/mautic/mautic/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+SES+bounce

**Closed by npracht** 2019-10-02 15:53 UTC
