### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by donbowman** [mautic/mautic#10373] opened 2021-08-26 20:28 UTC
### Mautic Version

4.0.x series

### PHP version

7.4

### What happened?

I'm not sure what triggers this. its something from the mtc.js event processing. its not all the time. but, i think its obvious in the code how its not right,

$result = $sq->execute()->fetch();

is assumed to be an array, but can be a false, it assumes there is a row.
https://www.php.net/manual/en/pdostatement.fetch.php

shows 
The return value of this function on success depends on the fetch type. In all cases, false is returned on failure.

we should catch teh false and not do the set.

### How can we reproduce this issue?

i'm not sure

### Relevant log output

```shell
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type bool in /app/app/bundles/PageBundle/Entity/HitRepository.php on line 276"



        if (isset($options['second_to_last'])) {
            $sq->andWhere($sq->expr()->neq('h.id', $options['second_to_last']));
        } else {
            $sq->orderBy('h.date_hit', 'DESC limit 1');
        }
        $result = $sq->execute()->fetch();

        return new \DateTime($result['latest_hit'], new \DateTimeZone('UTC'));
```

full stack:

```
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type bool in /app/app/bundles/PageBundle/Entity/HitRepository.php on line 276"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /app/index.php:0"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   2. Stack\run() /app/index.php:24"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   3. Stack\StackedHttpKernel->handle() /app/vendor/stack/run/src/Stack/run.php:13"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   4. Mautic\Middleware\TrustMiddleware->handle() /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   5. Mautic\Middleware\VersionCheckMiddleware->handle() /app/app/middlewares/TrustMiddleware.php:51"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   6. Mautic\Middleware\CatchExceptionMiddleware->handle() /app/app/middlewares/VersionCheckMiddleware.php:67"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   7. Mautic\Middleware\CORSMiddleware->handle() /app/app/middlewares/CatchExceptionMiddleware.php:43"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   8. AppKernel->handle() /app/app/middlewares/CORSMiddleware.php:91"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP   9. AppKernel->handle() /app/app/AppKernel.php:115"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  10. Symfony\Component\HttpKernel\HttpKernel->handle() /app/vendor/symfony/http-kernel/Kernel.php:201"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  11. Symfony\Component\HttpKernel\HttpKernel->handleRaw() /app/vendor/symfony/http-kernel/HttpKernel.php:80"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  12. Mautic\PageBundle\Controller\PublicController->trackingAction() /app/vendor/symfony/http-kernel/HttpKernel.php:158"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  13. Mautic\PageBundle\Model\PageModel->hitPage() /app/app/bundles/PageBundle/Controller/PublicController.php:392"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  14. Mautic\PageBundle\Model\PageModel->processPageHit() /app/app/bundles/PageBundle/Model/PageModel.php:538"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  15. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /app/app/bundles/PageBundle/Model/PageModel.php:731"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  16. Symfony\Component\EventDispatcher\EventDispatcher->callListeners() /app/vendor/symfony/event-dispatcher/EventDispatcher.php:73"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  17. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /app/vendor/symfony/event-dispatcher/EventDispatcher.php:239"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  18. Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure:/app/vendor/symfony/event-dispatcher/EventDispatcher.php:299-305}() /app/vendor/symfony/event-dispatcher/EventDispatcher.php:264"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  19. Mautic\PageBundle\EventListener\PointSubscriber->onPageHit() /app/vendor/symfony/event-dispatcher/EventDispatcher.php:304"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  20. Mautic\PointBundle\Model\PointModel->triggerAction() /app/app/bundles/PageBundle/EventListener/PointSubscriber.php:81"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  21. ReflectionMethod->invokeArgs() /app/app/bundles/PointBundle/Model/PointModel.php:290"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  22. Mautic\PageBundle\Helper\PointActionHelper::validateUrlHit() /app/app/bundles/PointBundle/Model/PointModel.php:290"
[mautic-b8cdf46b5-hbp82] [26-Aug-2021 20:21:33] WARNING: [pool www] child 757 said into stderr: "NOTICE: PHP message: PHP  23. Mautic\PageBundle\Entity\HitRepository->getLatestHit() /app/app/bundles/PageBundle/Helper/PointActionHelper.php:87"
```
```


### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2021-08-26 20:34
Hey @donbowman are you testing against the Release Candidate version, or the Features branch? We did merge a bunch of fixes relating to this kind of error just recently which would be reflected in the features branch.

**Comment by RCheesley** [comment] 2021-08-26 20:36
Actually, I think that this may be a duplicate of #10316 perhaps?

**Comment by donbowman** [comment] 2021-08-26 20:42
its 4.0.0-rc, should i test -features? i can give that a go.

I suspect you are correct its related.

This is a lack of defensive programming here too, perhaps we want:

```
        $result = $sq->execute()->fetch();
        if ($result == false) {
                return new \DateTime('now', new \DateTimeZone('UTC'));
        }

        return new \DateTime($result['latest_hit'], new \DateTimeZone('UTC'));

```

**Comment by RCheesley** [comment] 2021-08-26 20:53
Yeah give features a test as that's the most up to date code base, however I suspect it's still an issue.

If you are up for making a PR that would be awesome. 

I'll close this one as a duplicate and let's carry the conversation forward in #10316 so that we don't duplicate efforts! :)

**Closed as completed by RCheesley** 2021-08-26 20:53 UTC
Labels: bug, duplicate, needs-triage
