### ISSUE TITLE
Segments is Broken in 4.3.x

### ISSUE THREAD

**Issue by nomadicjosh** [mautic/mautic#11188] opened 2022-05-25 18:09 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

After upgrading from 4.2 to 4.3, I started having issues with Segments.

1. The first issue is that when I created a segment, saved it, and then updated it, the system recreated the same one, 2 more times. I deleted all three of them. Then I created it again.
2. After doing so, I clicked on the Segment's name to open it. Nothing happened. I then clicked to open in a new tab. The following error occurred:
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```
3. I went to try and open the old Segments that had been created before the upgrade, and I ran into the same issue.
4. A Mautic log wasn't generated because it was trying to create it in a place where it did not have permission to do so. UPDATE: found the log, and added the error log messages below.

### How can we reproduce this issue?

Step 1: Make sure to upgrade from the last 4.2.x version to the latest 4.3.x version.
Step 2: Create a new ssh tunnel to Mautic's root directory as a web user and not as root.
Step 3: Via the command line run the command ```php bin/console mautic:update:apply```
Step 4: Make note of any errors via the console if any.
Step 5: Try to create a new segment, click save (not save and close), then try to update, save, then try to save and close.
Step 6: Try to open the newly created segment and then try to open an old segment.

### Relevant log output

```
[2022-05-25 17:54:14] mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] {"hostname":"ad70","pid":2955}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by patrykgruszka** [comment] 2022-05-26 14:42
I've got similar problem during the segments update. Test #11193 if you use prefixed tables.

**Comment by nomadicjosh** [comment] 2022-05-27 04:51
> #11193


Tried it, cleared cache and segments still don't work for me.

**Comment by jos0405** [comment] 2022-05-27 07:03
I couldn't reproduce on 4.3.1. It means nothing, just a feedback from me. :)

**Comment by RCheesley** [comment] 2022-05-27 08:21
Have you also:

1. Cleared the Mautic cache
2. Run `bin/console m:a:g`
3. Cleared your Browser cache

**Comment by nomadicjosh** [comment] 2022-05-28 03:29
> Have you also:
> 
> 1. Cleared the Mautic cache
> 2. Run `bin/console m:a:g`
> 3. Cleared your Browser cache

Yes, I've tried several things and nothing. I see a different error in the logs than I saw before:

In prod*.php, I get errors like the following:
```
[2022-05-28 03:25:02] console.CRITICAL: Error thrown while running command "mautic:segments:update". Message: "An exception occurred while executing 'SELECT count(l.lead_id) as thecount, l.leadlist_id FROM gwt_lead_lists_leads l USE INDEX (manually_removed) WHERE (l.leadlist_id = 9) AND (l.manually_removed = ?) GROUP BY l.leadlist_id' with params [0]:  SQLSTATE[42000]: Syntax error or access violation: 1176 Key 'manually_removed' doesn't exist in table 'l'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT count(l.lead_id) as thecount, l.leadlist_id FROM mau_lead_lists_leads l USE INDEX (manually_removed) WHERE (l.leadlist_id = 9) AND (l.manually_removed = ?) GROUP BY l.leadlist_id' with params [0]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1176 Key 'manually_removed' doesn't exist in table 'l' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1176 Key 'manually_removed' doesn't exist in table 'l' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1176 Key 'manually_removed' doesn't exist in table 'l' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)","command":"mautic:segments:update","message":"An exception occurred while executing 'SELECT count(l.lead_id) as thecount, l.leadlist_id FROM mau_lead_lists_leads l USE INDEX (manually_removed) WHERE (l.leadlist_id = 9) AND (l.manually_removed = ?) GROUP BY l.leadlist_id' with params [0]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1176 Key 'manually_removed' doesn't exist in table 'l'"} {"hostname":"ad70","pid":810264}
```

In mautic_prod*.php, I get errors like the following
```
[2022-05-28 03:28:01] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT count(l.lead_id) as thecount, l.leadlist_id FROM mau_lead_lists_leads l USE INDEX (manually_removed) WHERE (l.leadlist_id = 9) AND (l.manually_removed = ?) GROUP BY l.leadlist_id' with params [0]:  SQLSTATE[42000]: Syntax error or access violation: 1176 Key 'manually_removed' doesn't exist in table 'l' (uncaught exception) at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 while running console command `mautic:segments:update` [] {"hostname":"ad70","pid":810535}
```

**Comment by jos0405** [comment] 2022-06-14 09:13
Hi, do you have contacts manually added to your segment either by campaign action/form action/manual action?
thx,
Joey

**Comment by nomadicjosh** [comment] 2022-06-15 16:22
> Hi, do you have contacts manually added to your segment either by campaign action/form action/manual action? thx, Joey

Yes to all. The majority are manually added because they were imported from another system.

**Comment by ilannjoaquim** [comment] 2022-06-22 11:01
Any news about this problem ? I have the same error with same config.

**Comment by RCheesley** [comment] 2022-06-22 11:19
I think that we may be muddling several different issues in this thread.

First issue about segments being broken: I am also unable to reproduce, are you _sure_ that you have cleared both your Mautic cache, and your browser cache, and you have cleared any CDN like Cloudflare or server-side caching which might also be caching JS?

Have you also regenerated the assets before doing that so you definitely have the latest assets?

I noticed @parkerj that you are using a database prefix, which is throwing errors - we did find a bug with database prefixes which has been merged already for the next release: https://github.com/mautic/mautic/pull/11128 but that related to tables being missing rather than indexes. Have you by any chance tried to update the schema at some point? Is your schema up to date when you check it using the troubleshooting steps: https://docs.mautic.org/en/troubleshooting#2-try-to-fix-the-database-schema

**Comment by nomadicjosh** [comment] 2022-06-22 14:21
@RCheesley trying to update schema throws a 500 Internal Server Error.

**Comment by nomadicjosh** [comment] 2022-07-11 01:22
Ok, I tried updating to the newest version, but made sure to make note this time of the error after running the command: `php bin/console mautic:update:apply --finish`.

Below is the error message from the error log:

```
[2022-07-11 01:13:09] mautic.NOTICE: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'ALTER TABLE `gwt_lead_event_log` RENAME INDEX `IDX_SEARCH` TO `gwt_IDX_SEARCH`':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX `IDX_SEARCH` TO `gwt_IDX_SEARCH`' at line 1 (uncaught exception) at /var/www/clients/client1/web4/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 while running console command `doctrine:migrations:migrate` [] {"hostname":"ad70","pid":1237295}
[2022-07-11 01:13:09] mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] {"hostname":"ad70","pid":1237295}
```
I am hoping this will help pinpoint the exact issue.

**Comment by RCheesley** [comment] 2022-07-11 08:37
This is relating to a problem with a migration. I had it myself in my Mautic instance. For me, dropping the index `IDX_SEARCH` solved the issue, then I was able to update the schema.

This issue is reported already in the forums, please go there first to search/post and see if the problem is already resolved, then if it is found to be a bug we can raise an issue here.

Here is the forum thread: https://forum.mautic.org/t/mysql-error-upgrading-to-4-2/22867 - the root cause has been fixed in a later release.

Closing this issue as it is not related to a new bug in Mautic, thanks for reporting!

**Closed as completed by RCheesley** 2022-07-11 08:37 UTC
Labels: bug, segments
