### ISSUE TITLE
Cronjob running issue: The EntityManager is closed

### ISSUE THREAD

**Issue by Shaileshpx** [mautic/mautic#5488] opened 2017-12-23 09:32 UTC
| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 7.0

### Steps to reproduce:
1. while running console command `mautic:campaigns:trigger`.
 
### Log errors: 
[Mautic logfile](http://192.241.165.153/mautic_prod-2017-12-23.php)

**Comment by mannytriana** [comment] 2018-01-11 10:06
I am having the same issue when running: 

`php app/console mautic:campaigns:trigger`

`[2018-01-11 09:32:55] mautic.ERROR: The EntityManager is closed. [] []'

Running latest version: v2.12.1

I do have a database of a few million contacts processing 1 campaign, not sure if its related to the number of campaigns and contacts being processed by the system / cron console.

Thanks

**Comment by Rikk03** [comment] 2018-02-11 14:42
Im having this issue when running social monitoring via Cron.  Tried the cron activation via URL also via command.php.  Got exactly the same message.  (The EntityManager is closed). If i try to save a social monitoring i get 500 error message also.

**Comment by Rikk03** [comment] 2018-02-11 15:05
just tested it again.  Here is what is being put into the db.

An exception occurred while executing 'INSERT INTO promotecee_leads (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, points, last_active, internal, social_cache, date_identified, preferred_profile_image, title, firstname, lastname, company, position, email, phone, mobile, address1, address2, city, state, zipcode, timezone, country, owner_id, stage_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2018-02-11 15:01:07", null, " ", null, null, null, null, null, null, 0, "2018-02-11 14:40:34", "a:0:{}", "a:1:{s:7:\"Twitter\";a:3:{s:7:\"profile\";a:9:{s:13:\"profileHandle\";s:12:\"WeTee_Design\";s:4:\"name\";s:5:\"WeTee\";s:8:\"location\";s:10:\"Etats-Unis\";s:11:\"description\";s:148:\"Get your #Tshirt delivered by #Amazon\/#Redbubble\/ #Etsy https:\/\/t.co\/1W6GipkEgI #fashion #design #Tech #green  #1DDrive  DM for specfic inquires\ud83d\udc4d\";s:3:\"url\";s:23:\"https:\/\/t.co\/QCulE7b3Hb\";s:9:\"time_zone\";s:26:\"Pacific Time (US & Canada)\";s:4:\"lang\";s:2:\"fr\";s:5:\"email\";s:0:\"\";s:12:\"profileImage\";s:68:\"https:\/\/pbs.twimg.com\/profile_images\/949998508312006660\/w5VPx_3C.jpg\";}s:8:\"activity\";a:3:{s:6:\"tweets\";a:10:{i:0;a:4:{s:5:\"tweet\";s:142:\"RT @onestartc: From the home office, on tough days listening to my wife and kids play and laugh upstairs is a welcome distraction. #workper\u2026\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962702209766100993\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:57:47 +0000 2018\";}i:1;a:4:{s:5:\"tweet\";s:141:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #March #for #Science #Earth #Day #Tshirt\u2026 https:\/\/t.co\/0RcBaRGN18\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962701996028563457\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:56:56 +0000 2018\";}i:2;a:4:{s:5:\"tweet\";s:140:\"https:\/\/t.co\/0w31uqbXFs #EarthDay #Earth #GoGreen #Happy #EarthDay #Tshirt #Environment #Vegans #Activist #Planet\u2026 https:\/\/t.co\/XvsJYiOWPW\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962701938293866496\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:56:42 +0000 2018\";}i:3;a:4:{s:5:\"tweet\";s:139:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #Happy #Earth #Day #TShirt #Gift #Save\u2026 https:\/\/t.co\/TPNE1xR1Nu\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962701867540246528\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:56:26 +0000 2018\";}i:4;a:4:{s:5:\"tweet\";s:135:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #StPatricks #Dab #Shirt #StPatrick\u2026 https:\/\/t.co\/Z6rLY0mQsD\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962697942825160704\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:40:50 +0000 2018\";}i:5;a:4:{s:5:\"tweet\";s:137:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #Happy #Earth #Day #Shirt #Save #The\u2026 https:\/\/t.co\/II0nG7KzKo\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962697876777439233\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:40:34 +0000 2018\";}i:6;a:4:{s:5:\"tweet\";s:137:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #Happy #Earth #Day #Shirt #Save #The\u2026 https:\/\/t.co\/dn9S7LzFFT\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962697805985996800\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:40:17 +0000 2018\";}i:7;a:4:{s:5:\"tweet\";s:140:\"https:\/\/t.co\/0w31uqbXFs #EarthDay #Earth #GoGreen #Happy #EarthDay #Tshirt #Environment #Vegans #Activist #Planet\u2026 https:\/\/t.co\/rdFLaitEab\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962697751002861568\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:40:04 +0000 2018\";}i:8;a:4:{s:5:\"tweet\";s:137:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #Saint #Patricks #TShirt #StPatricks\u2026 https:\/\/t.co\/cQCmGx0m1n\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962697685793955840\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:39:49 +0000 2018\";}i:9;a:4:{s:5:\"tweet\";s:139:\"#Amazon #Redbubble #Etsy #WeeTee #SweatShirt #DDrive #Printed #Customized #StPatricks #Dab #Dabbing #Irish #Beer\u2026 https:\/\/t.co\/JIu1lZTpAV\";s:3:\"url\";s:64:\"https:\/\/twitter.com\/703754312485367809\/status\/962697619255578626\";s:11:\"coordinates\";N;s:9:\"published\";s:30:\"Sun Feb 11 14:39:33 +0000 2018\";}}s:6:\"photos\";a:0:{}s:4:\"tags\";a:34:{s:6:\"Amazon\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23Amazon\";}s:9:\"Redbubble\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:41:\"https:\/\/twitter.com\/search?q=%23Redbubble\";}s:4:\"Etsy\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:36:\"https:\/\/twitter.com\/search?q=%23Etsy\";}s:6:\"WeeTee\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23WeeTee\";}s:10:\"SweatShirt\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:42:\"https:\/\/twitter.com\/search?q=%23SweatShirt\";}s:6:\"DDrive\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23DDrive\";}s:7:\"Printed\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:39:\"https:\/\/twitter.com\/search?q=%23Printed\";}s:10:\"Customized\";a:2:{s:5:\"count\";i:7;s:3:\"url\";s:42:\"https:\/\/twitter.com\/search?q=%23Customized\";}s:5:\"March\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:37:\"https:\/\/twitter.com\/search?q=%23March\";}s:3:\"for\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:35:\"https:\/\/twitter.com\/search?q=%23for\";}s:7:\"Science\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:39:\"https:\/\/twitter.com\/search?q=%23Science\";}s:5:\"Earth\";a:2:{s:5:\"count\";i:6;s:3:\"url\";s:37:\"https:\/\/twitter.com\/search?q=%23Earth\";}s:3:\"Day\";a:2:{s:5:\"count\";i:4;s:3:\"url\";s:35:\"https:\/\/twitter.com\/search?q=%23Day\";}s:6:\"Tshirt\";a:2:{s:5:\"count\";i:3;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23Tshirt\";}s:8:\"EarthDay\";a:2:{s:5:\"count\";i:4;s:3:\"url\";s:40:\"https:\/\/twitter.com\/search?q=%23EarthDay\";}s:7:\"GoGreen\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:39:\"https:\/\/twitter.com\/search?q=%23GoGreen\";}s:5:\"Happy\";a:2:{s:5:\"count\";i:5;s:3:\"url\";s:37:\"https:\/\/twitter.com\/search?q=%23Happy\";}s:11:\"Environment\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:43:\"https:\/\/twitter.com\/search?q=%23Environment\";}s:6:\"Vegans\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23Vegans\";}s:8:\"Activist\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:40:\"https:\/\/twitter.com\/search?q=%23Activist\";}s:6:\"Planet\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23Planet\";}s:6:\"TShirt\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:38:\"https:\/\/twitter.com\/search?q=%23TShirt\";}s:4:\"Gift\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:36:\"https:\/\/twitter.com\/search?q=%23Gift\";}s:4:\"Save\";a:2:{s:5:\"count\";i:3;s:3:\"url\";s:36:\"https:\/\/twitter.com\/search?q=%23Save\";}s:10:\"StPatricks\";a:2:{s:5:\"count\";i:3;s:3:\"url\";s:42:\"https:\/\/twitter.com\/search?q=%23StPatricks\";}s:3:\"Dab\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:35:\"https:\/\/twitter.com\/search?q=%23Dab\";}s:5:\"Shirt\";a:2:{s:5:\"count\";i:3;s:3:\"url\";s:37:\"https:\/\/twitter.com\/search?q=%23Shirt\";}s:9:\"StPatrick\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:41:\"https:\/\/twitter.com\/search?q=%23StPatrick\";}s:3:\"The\";a:2:{s:5:\"count\";i:2;s:3:\"url\";s:35:\"https:\/\/twitter.com\/search?q=%23The\";}s:5:\"Saint\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:37:\"https:\/\/twitter.com\/search?q=%23Saint\";}s:8:\"Patricks\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:40:\"https:\/\/twitter.com\/search?q=%23Patricks\";}s:7:\"Dabbing\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:39:\"https:\/\/twitter.com\/search?q=%23Dabbing\";}s:5:\"Irish\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:37:\"https:\/\/twitter.com\/search?q=%23Irish\";}s:4:\"Beer\";a:2:{s:5:\"count\";i:1;s:3:\"url\";s:36:\"https:\/\/twitter.com\/search?q=%23Beer\";}}}s:11:\"lastRefresh\";s:19:\"2018-02-11 15:01:07\";}}", "2018-02-11 15:01:07", "Twitter", null, "WeTee", "WeTee", null, null, null, null, null, null, null, null, null, null, null, "Etats-Unis", null, null]:

**Comment by TheSpanner** [comment] 2018-09-01 10:54
I am also getting this error in v2.14.0, on every campaign. even one that simply tries to tag the contacts.
![image](https://user-images.githubusercontent.com/18556096/44945275-f5567480-ade5-11e8-869d-7a0a5541f73a.png)

```
Triggering events for campaign 37
Triggering events for newly added contacts
436 total events(s) to be processed in batches of 100 contacts
   0/436 [>---------------------------]   0%PHP Notice:  unserialize(): Error at offset 53 of 272 bytes in /home/websites/content/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58
 436/436 [============================] 100%

```

**Comment by RCheesley** [comment] 2019-12-02 10:33
From my reading, it’s something to do with the collation and charset of the database. 

Suggestions include using utf8mb64 and utf864mb_unicode_ci however I have not tried this to see if it resolves the problem (although it resolved the issue for a community member [in slack](https://mautic.slack.com/archives/C02HU8K0D/p1575282658027900). 

Reference: https://stackoverflow.com/questions/48270374/invalid-datetime-format-1366-incorrect-string-value (not mautic-specific)

**Comment by RCheesley** [comment] 2020-02-10 17:18
For those with this problem, updating the collation type on both the database and the tables fixes the issue.

The issue is almost certainly https://stackoverflow.com/questions/48270374/invalid-datetime-format-1366-incorrect-string-value and by switching to UTF8mb4 encoding.

So it seems to relate to setting up with the wrong collation types. Maybe we need to make this more explicit in the installation instructions @escopecz @alanhartless ?

**Comment by alanhartless** [comment] 2020-02-10 17:36
@escopecz is this something we need to consider for M3 since it defaults to UTF8MB now?

**Comment by escopecz** [comment] 2020-02-11 08:46
@alanhartless what do you mean by consider? New installations of M3 will use UTF8MB4 encoding and so will not have this issue. Instances that will be upgraded from M2 to M3 will still use just UTF8 and will have this issue.

Since the migration is close to impossible on MySql < v8, we can suggest users with this issue to install M3 next to M2, export data from the M2 database, import them to M3 and then switch the web traffic from M2 to M3.

**Comment by RCheesley** [comment] 2020-07-31 17:32
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-31 17:32 UTC
Labels: bug
