### ISSUE TITLE
Using css from wordpress theme in Mautic Landing Page

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#3998] opened 2017-05-05 04:11 UTC
## Background:
I know it's possible to embed Mautic forms into wordpress and have that form inherit the CSS of the wordpress page. I've seen this discussed in other posts, but I have a similar, but different issue

## Overall Goal
I want to utilise the A/B testing capability of Mautic landing page builder to create landing pages in mautic that look exactly like they are part of our main wordpress site. Our A/B tests would usually involve copywriting variations.

## Problem

When I embed a Mautic form into a Mautic landing page, I don't know how to get it looking like our wordpress theme's css.

## Question
I think my issue boils down to two possible questions
 * How do I configure a standalone Mautic landing page(i.e. one that is not being used in an iframe, but that the user is accessing directly) to utilise css from another site? (That other site is our Wordpress website)
  * I believe that might be an issue because how CSS accumulates inheritance of settings, but my knowledge of CSS doesn't go beyond that.

* How do I get the inherited CSS outcome to apply onto a Mautic landing page that's been presented in an iframe?

* Is there a better way I should be thinking about this problem?

Using:

* Mautic v2.8.0
* PHP 7

**Comment by escopecz** [comment] 2017-05-05 07:53
I'd suggest to create a [custom Mautic Theme](https://developer.mautic.org/#themes) where you'll use the CSS from your WP site. Since this is more related to CSS than Mautic itself, please start the discussion in [Mautic forum](https://www.mautic.org/community/.

Closing this issue since it's not a bug report nor feature request.

**Closed by escopecz** 2017-05-05 07:53 UTC
