### ISSUE TITLE
Focus item - Disabling "Allow to Hide" option make the focus blank

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8037] opened 2019-10-29 09:49 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In the Focus item editor when you select bar as a style for your focus you have an option to allow the contact to hide the focus. 
If you disable this option,  the focus item will be blank on the site it displays. 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a focus item
2. Set Display a notice
![image](https://user-images.githubusercontent.com/49391402/67755902-535a0880-fa39-11e9-96de-de839d2dd690.png)

3. Set "bar" as style
![image](https://user-images.githubusercontent.com/49391402/67755966-6ff64080-fa39-11e9-83f2-a3a96383359f.png)

4. Here, disable the "Allow to hide" option
![image](https://user-images.githubusercontent.com/49391402/67755869-3faea200-fa39-11e9-8213-f7c9430ff1bc.png)

5. Set color and enter text if you want.
6. Save your focus.
7. Create a landing page with the focus token in it. Or insert the focus script on a site.
8. See that the focus is a blank bar. 
 
### Log errors
Error logs in the browser console : 
![image](https://user-images.githubusercontent.com/49391402/67756057-9ddb8500-fa39-11e9-845c-2d15fb77dbdf.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-07-16 14:26
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment] 2020-10-08 18:54
Closing as I am unable to reproduce.

**Closed by RCheesley** 2020-10-08 18:54 UTC
Labels: bug, pending-feedback
