### ISSUE TITLE
Cannot reset date/time field to null over API

### ISSUE THREAD

**Issue by jiripudil** [mautic/mautic#6502] opened 2018-08-29 07:25 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:

I don't know if this is an issue with the api-library or the core package, but I suspect this one. I've found out that when you update a contact over API, setting a field to `null` makes Mautic ignore the field entirely and keep its value unchanged. While this was a bit unexpected to me, it's not that much of a problem, I resorted to sending an empty string which works.

What _is_ a problem is resetting a date/time field to an empty value. There seems to be some format check which ignores either `null`, empty string, and `'0000-00-00'`. Is there any way I can achieve that over API?

Thanks for your help

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.1
| PHP version | 5.6.36

### Steps to reproduce:

1. Create a new date/time custom field.
2. Create a contact over API, setting the date/time field to a valid value.
3. Edit the contact over API and try to empty the date/time field.

### Log errors: 

None.

**Comment by npracht** [comment] 2018-08-29 07:27
Hi @jiripudil thanks for that reporting. Could you please confirm you still meet the same issue in 2.14.0 ? Then we can avoid looking for something already fixed (in case it is).

Thanks again.

**Comment by jiripudil** [comment] 2018-08-29 08:00
Hello, after a quick scan through the code, I think the problem lies [here](https://github.com/mautic/mautic/blob/729fa25e276d233c495c6de743279cf9078642e8/app/bundles/CoreBundle/Form/RequestTrait.php#L66), so I believe it is still relevant for current master. I can check it on a live instance when I find a bit of spare time, if you want me to

**Comment by Aniz** [comment] 2018-09-04 19:26
I checked, and the problem still occurs on 2.14.0.
Sending an empty string or a null value does not work in date/time fields.

**Comment by Snejp** [comment] 2018-10-25 22:08
I can confirm this problem on 2.14.1.
I quickly checked also `multiselect` field and it does not clear all options over contact API. Same steps to reproduce as with `date/time` custom field.

**Comment by npracht** [comment] 2020-07-17 15:07
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment] 2020-08-04 20:10
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-08-04 20:10 UTC
Labels: API, bug, triage-mautic-3

**Comment by JB-iundf-mt** [comment] 2022-01-25 09:35
@npracht This issue remains for mautic v4.1.1. I have the same problem setting null values for `multiselect` fields. Any solutions since 2020?

**Comment by jos0405** [comment] 2022-01-25 09:56
Hi,

I think this is not a bug. The API call has to be made a little bit different if you want the blank to replace existing values.
Call has to be modified as:

![image](https://user-images.githubusercontent.com/4246909/150954170-46f726ab-8ab2-47f9-9b18-bd15f6dab59d.png)

Here is the docs:
https://developer.mautic.org/#edit-contact

![image](https://user-images.githubusercontent.com/4246909/150954443-c2bbcee2-a580-4192-aa8f-0dcb3754e614.png)
