### ISSUE TITLE
Images inserted and re-sized...Outlook ignores styling 

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5028] opened 2017-09-26 20:48 UTC
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
so... if you insert an image and resize it using the handles, the editor adds a style="width:xxxpx; height:xxxpx; - Outlook ignores those styles

if you edit the html and put it in the <img tag as height="xxx" and width="xxx" then it works.

Thoughts?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by chriscalabro** [comment] 2017-10-26 23:33
Same issue already being discussed here I think: https://github.com/mautic/mautic/issues/2791

**Comment by escopecz** [comment] 2018-10-31 09:38
Closing as duplicate of #2791

**Closed by escopecz** 2018-10-31 09:38 UTC
Labels: Bug
