### ISSUE TITLE
Wrong date in lead history timeline

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2231] opened 2016-08-10 14:55 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

Sometime, the timeline show "Today" instead of "Yesterday". It's also right in the "mail Toggle detail", with email read date
![image](https://cloud.githubusercontent.com/assets/4522557/17558453/efd49508-5f1a-11e6-9ddb-9aecea7289db.png)

Seen on 10 August 2016, 16:54
![image](https://cloud.githubusercontent.com/assets/4522557/17558488/1683e56e-5f1b-11e6-910e-ee9c2e7ba790.png)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.0.2-dev |
| PHP version |  |

**Comment by escopecz** [comment] 2016-08-15 12:48
@chandon could you please check if this issue is still in Mautic 2.1.0?

**Comment by dongilbert** [comment] 2016-08-23 02:33
Fixed in #2327

**Comment by chandon** [comment] 2016-09-07 16:13
Not fixed, i still have the problem

**Comment by chandon** [comment] 2016-09-07 16:37
Last Event : Yesterday, 16h56 UTC

Users timezone : +2H

In Contact list, last active : "Yesterday, 4h56am" (should be "Yesterday, 6h56am", good day, wrong timezone)
In Detail : "Today, 6h56am" (should be "Yesterday, 6h56am", good timezone, wrong day)

**Comment by amagdy3** [comment] 2016-09-17 13:14
I second that, the time in "Last Active" in the segment list view is in UTC. While both the configuration and user profile is at UTC + 2. Inside each contact it's showing at UTC + 2. But in the segment list view UTC, which is not expected.

**Comment by escopecz** [comment] 2016-09-19 07:30
Please check if https://github.com/mautic/mautic/pull/2397 fix it for you.

**Comment by chandon** [comment] 2016-09-19 22:43
it seems #2397 solves this issue

**Comment by chandon** [comment] 2016-09-21 16:36
@escopecz #2397 this only solves partialy the problem. I still have an issue with the timeline "contact created" is shown on yesterday, but it was 2 days ago...

![image](https://cloud.githubusercontent.com/assets/4522557/18720035/3f0e2bae-802a-11e6-91b0-4dba933ac818.png)

**Comment by chandon** [comment] 2016-11-02 12:10
This should be re-open, still buggy !

**Comment by npracht** [comment] 2017-05-31 07:42
@escopecz this is a duplicate of https://github.com/mautic/mautic/issues/2883

**Comment by escopecz** [comment] 2017-05-31 08:16
In my mind the duplicate is something what was created after the original. So I'll close #2883 as a duplicate instead

**Comment by johbuch** [comment] 2017-10-10 12:49
Hello, I still notice this bug in version 2.10
<img width="94" alt="capture d ecran 2017-10-10 a 14 38 37" src="https://user-images.githubusercontent.com/31535432/31387261-123ba506-adca-11e7-9c02-b9f4de5bae3e.png">
<img width="493" alt="capture d ecran 2017-10-10 a 14 38 23" src="https://user-images.githubusercontent.com/31535432/31387260-122447f8-adca-11e7-8935-1b5f8ba5284e.png">

**Closed** 2017-12-17 18:16 UTC
Labels: Backlog, Bug, L2
