### ISSUE TITLE
mod_rewrite index.php remove from base url

### ISSUE THREAD

**Issue by ramielbarsoum** [mautic/mautic#1204] opened 2015-11-26 07:03 UTC
Is there a way to remove the index.php in the URL?
I am using the mautic wordpress plugin, the embedded URL used in that plugin references my mautic install without the index.php in the src, where as the automatic script calls for it.

Example:
Automatic script:
<script type="text/javascript" src="http://mautic.example.com/index.php/form/generate.js?id=1"></script>

Wordpress plugin script:
<script src="http://mautic.example.com/index.php/form/generate.js?id=1" type="text/javascript"></script>
Leading to a 404 file not found error.

Any advice on the best way to fix this while also allowing the main dashboard to be accessible?
http://mautic.example.com/index.php/s/dashboard

**Comment by escopecz** [comment] 2015-11-26 07:49
Duplicate of https://github.com/mautic/mautic-wordpress/issues/16

**Closed by escopecz** 2015-11-26 07:49 UTC
