### ISSUE TITLE
Mautic form validation is not working when installed in a subdirectory instead of a subdomain

### ISSUE THREAD

**Issue by scmoral** [mautic/mautic#4020] opened 2017-05-09 16:18 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
It seems that when installing Mautic in a directory instead of a subdomain the code provided for the forms is duplicating the directory in which Mautic is installed.

I attach a scrennshot where you can view that the directory "marketing" in script.src is duplicated.

![mautic_error_in_forms](https://cloud.githubusercontent.com/assets/126643/25860930/57ea00e4-34e3-11e7-9b2c-971a55c705ff.png)

This error happens in a site already configured and running and in a fresh installation with the new version of Mautic (2.8.0)

The effect I could see is that no javascript validation is done in the form when you include it in a page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.18

### Steps to reproduce:
1. Install Mautic in a directory of a domain
2. Create a form
3. Get the HTML Code of the form from Mautic
4. You can create a form with some mandatory fields and try to integrate it in a page. No validation is done.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-05-09 17:45
This seems like a duplicate of https://github.com/mautic/mautic/issues/3697

**Closed by escopecz** 2017-05-09 17:45 UTC
