### ISSUE TITLE
Filter contacts in report by tags

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#4665] opened 2017-08-15 14:34 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
A feature I really miss is to create a report for contacts and directly in the report filter contacts on tags
else we have to create a lot of segments.

**Comment by kuzmany** [comment] 2017-08-15 15:03
not finished https://github.com/mautic/mautic/pull/3134

**Comment by escopecz** [comment] 2017-08-18 07:43
Duplicate of https://github.com/mautic/mautic/issues/995

**Closed by escopecz** 2017-08-18 07:43 UTC
Labels: Feature Request
