### ISSUE TITLE
Filter disappears after creating report 

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#3521] opened 2017-02-24 20:47 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When I create a report, add 2 filters and then save, one of the filter will be removed. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a new report
2. Set Data Source: Emails Sent
3. Move to Data tab and select Columns: Contact email, clicks, unique clicks and viewed in browser
4. Add filter "ID equals 44" (44 is the ID of email)
5. Add another filter "Clicks greater than 0"
6. Click Save and close. 
7. First filter is gone. 

 
### Log errors: 
No error logs.

**Comment by escopecz** [comment] 2017-02-27 08:31
Duplicate of https://github.com/mautic/mautic/issues/2959

**Closed by escopecz** 2017-02-27 08:31 UTC
