### ISSUE TITLE
Element of "Go To"

### ISSUE THREAD

**Issue by moskoweb** [mautic/mautic#3503] opened 2017-02-23 01:11 UTC
Go To element in campaigns to move a place contact within the same campaign, an example of what ActiveCampagn has.

This way it is possible to take the lead from one place to another within the same campaign, without having to create several daughters campaigns.

![captura de tela 2017-02-22 as 22 10 15](https://cloud.githubusercontent.com/assets/6052272/23240353/c9e682f4-f94b-11e6-8c97-b91a5b445867.png)

**Comment by escopecz** [comment] 2017-02-23 08:34
Duplicate of https://github.com/mautic/mautic/issues/1414

**Closed by escopecz** 2017-02-23 08:34 UTC
