### ISSUE TITLE
Environment variable not found: "MAUTIC_MAILER_ENCRYPTION".

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8801] opened 2020-05-16 11:02 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Maybe this is related for windows enviroment but I see a many times this error with other enviroments variable

Symfony\Component\DependencyInjection\Exception\EnvNotFoundException: Environment variable not found: "MAUTIC_MAILER_ENCRYPTION".

![image](https://user-images.githubusercontent.com/462477/82118145-7c43b000-9775-11ea-9b8a-2252ffccb3e9.png)

Trace

```
\vendor\symfony\dependency-injection\EnvVarProcessor.php:76 at
\vendor\symfony\dependency-injection\Container.php:491 at Symfony\Component\DependencyInjection\EnvVarProcessor -> getEnv ( 'string', 'MAUTIC_MAILER_ENCRYPTION', object(Closure) )
\vendor\symfony\dependency-injection\EnvVarProcessor.php:67 at Symfony\Component\DependencyInjection\Container -> getEnv ( 'MAUTIC_MAILER_ENCRYPTION' )
\vendor\symfony\dependency-injection\Container.php:491 at Symfony\Component\DependencyInjection\EnvVarProcessor -> getEnv ( 'resolve', 'MAUTIC_MAILER_ENCRYPTION', object(Closure) )
\app\bundles\CoreBundle\DependencyInjection\EnvProcessor\NullableProcessor.php:20 at Symfony\Component\DependencyInjection\Container -> getEnv ( 'resolve:MAUTIC_MAILER_ENCRYPTION' )
\vendor\symfony\dependency-injection\Container.php:491 at Mautic\CoreBundle\DependencyInjection\EnvProcessor\NullableProcessor -> getEnv ( 'nullable', 'resolve:MAUTIC_MAILER_ENCRYPTION', object(Closure) )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:10731 at Symfony\Component\DependencyInjection\Container -> getEnv ( 'nullable:resolve:MAUTIC_MAILER_ENCRYPTION' )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:10035 at ContainerZhhgbuu\appDevDebugProjectContainer -> getSwiftmailer_Mailer_Default_Transport_DynamicService ( )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:10075 at ContainerZhhgbuu\appDevDebugProjectContainer -> getMautic_Spool_DelegatorService ( )
\var\cache\dev\ContainerZhhgbuu\getSwiftmailer_Mailer_DefaultService.php:8 at ContainerZhhgbuu\appDevDebugProjectContainer -> getMautic_Transport_SpoolService ( )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:5880 at require ( 'C:\wamp3-1-4\www\mautic3\var\cache\dev\ContainerZhhgbuu\getSwiftmailer_Mailer_DefaultService.php' )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:9317 at ContainerZhhgbuu\appDevDebugProjectContainer -> load ( 'getSwiftmailer_Mailer_DefaultService.php' )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:10095 at ContainerZhhgbuu\appDevDebugProjectContainer -> getMautic_Helper_MailerService ( )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:9050 at ContainerZhhgbuu\appDevDebugProjectContainer -> getMautic_User_Model_UserService ( )
\var\cache\dev\ContainerZhhgbuu\appDevDebugProjectContainer.php:6674 at ContainerZhhgbuu\appDevDebugProjectContainer -> getMautic_Core_SubscriberService ( )
\vendor\symfony\event-dispatcher\EventDispatcher.php:147 at ContainerZhhgbuu\appDevDebugProjectContainer -> ContainerZhhgbuu\{closure} ( )
\vendor\symfony\event-dispatcher\ContainerAwareEventDispatcher.php:97 at Symfony\Component\EventDispatcher\EventDispatcher -> removeListener ( 'kernel.controller', array(object(RouterDataCollector), 'onKernelController') )
\vendor\symfony\event-dispatcher\Debug\TraceableEventDispatcher.php:263 at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher -> removeListener ( 'kernel.controller', array(object(RouterDataCollector), 'onKernelController') )
\vendor\symfony\event-dispatcher\Debug\TraceableEventDispatcher.php:137 at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher -> preProcess ( 'kernel.controller' )
\vendor\symfony\http-kernel\HttpKernel.php:139 at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher -> dispatch ( 'kernel.controller', object(FilterControllerEvent) )
\vendor\symfony\http-kernel\HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '2' )
\app\bundles\CoreBundle\EventListener\ExceptionListener.php:76 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '2', false )
\vendor\symfony\event-dispatcher\Debug\WrappedListener.php:115 at Mautic\CoreBundle\EventListener\ExceptionListener -> onKernelException ( object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher) )
\vendor\symfony\event-dispatcher\EventDispatcher.php:214 at Symfony\Component\EventDispatcher\Debug\WrappedListener -> __invoke ( object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher) )
\vendor\symfony\event-dispatcher\EventDispatcher.php:44 at Symfony\Component\EventDispatcher\EventDispatcher -> doDispatch ( array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent) )
\vendor\symfony\event-dispatcher\Debug\TraceableEventDispatcher.php:143 at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( 'kernel.exception', object(GetResponseForExceptionEvent) )
\vendor\symfony\http-kernel\HttpKernel.php:227 at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher -> dispatch ( 'kernel.exception', object(GetResponseForExceptionEvent) )
\vendor\symfony\http-kernel\HttpKernel.php:79 at Symfony\Component\HttpKernel\HttpKernel -> handleException ( object(EnvNotFoundException), object(Request), '1' )
\vendor\symfony\http-kernel\Kernel.php:200 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
\app\AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
\app\middlewares\CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
\app\middlewares\CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
\app\middlewares\Dev\IpRestrictMiddleware.php:64 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
\app\middlewares\VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
\app\middlewares\TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
\vendor\stack\builder\src\Stack\StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
\vendor\stack\run\src\Stack\run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
\index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
```

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment] 2020-05-17 01:12
@kuzmany are there reproducible steps for this? Does it happen every time you try to load the Mautic site? Only specific parts of Mautic?

**Comment by kuzmany** [comment] 2020-05-17 13:05
Not happen every time, just some time and not every click.

For example on edit email 

![image](https://user-images.githubusercontent.com/462477/82147364-7e7a3d00-984f-11ea-892d-6aa56b2c9766.png)

On open builder

![image](https://user-images.githubusercontent.com/462477/82147368-90f47680-984f-11ea-8202-30eb5da87b72.png)

On open segments

![image](https://user-images.githubusercontent.com/462477/82147375-a10c5600-984f-11ea-90a4-033265bc7cb6.png)

**Comment by kuzmany** [comment] 2020-05-17 13:06
Looks like every these parameters are null.

**Comment by dennisameling** [comment] 2020-06-15 21:09
@kuzmany I couldn't seem to reproduce this issue on Windows. Can you try with a clean install of 3.0.0 to see if the issue is still there? I'm moving this out of the 3.0.0 release for now, happy to look into it later 👍

**Comment by kuzmany** [comment] 2020-07-01 13:44
Should close it.

**Closed as completed** 2020-07-01 15:02 UTC
Labels: bug, pending-feedback
