### ISSUE TITLE
Attempting to Edit Imported Contacts Causes 500 Error & Possibly Related Reports Error

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2872] opened 2016-10-31 17:19 UTC
What type of report is this:

| Bug report | 

## Description:

Starting with 2.2.1, I am unable to edit any contacts that were imported into Mautic via a CSV file around 8 months ago.

Error logs point to a data discrepancy in MySql affecting Symphony's DateTimeToStringTransformer.php

Investigating the ma_leads table in phpmyadmin shows the affected rows have "0000-00-00 00:00:00" for both datecreated and datemodified custom fields. Each of these entries were imported from a CSV file around 8 months ago. (I can't remember the Mautic version we were running at that time.)

Interestingly enough, there was a previous bug I never got around to reporting where the Reports function of Mautic would not show any of these imported contacts. Otherwise, until 2.2.1 the application had displayed and interacted well with them in all other functions. (With no log files indicating errors)

**## To solve, I executed:**

`UPDATE `ma_leads` SET `datemodified` = NULL WHERE `datemodified` = '0000-00-00 00:00:00'`

and

`UPDATE `ma_leads` SET `datecreated` = NULL WHERE `datecreated` = '0000-00-00 00:00:00'`

This fixed the issue with editing contacts, but did not fix the issue causing these imported contacts to not show up in reports.

## If a bug:

| Mautic version | 2.2.1
| PHP version | 5.6.21

### Steps to reproduce:
1. Navigate to Contacts
2. Click "Edit Contact" on an affected entry
 
### Log errors: 

[2016-10-31 11:29:29] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "datecreated": Unexpected data found." at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Form.php line 1086 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"datecreated\": Unexpected data found. at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Form.php:1086, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unexpected data found. at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php:141)"} []

[2016-10-31 11:32:15] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "datecreated": Unexpected data found." at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Form.php line 1086 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"datecreated\": Unexpected data found. at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Form.php:1086, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unexpected data found. at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php:141)"} []

[2016-10-31 15:35:00] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:02] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:03] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:06] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:06] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:07] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:07] mautic.ERROR: Gmail: query variables are not found [] []
[2016-10-31 15:35:08] mautic.ERROR: Gmail: query variables are not found [] []

## Relevant Code from Logs

Line 1086 /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Form.php reads:

```
    /**
     * Normalizes the value if a normalization transformer is set.
     *
     * @param mixed $value The value to transform
     *
     * @return mixed
     *
     * @throws TransformationFailedException If the value cannot be transformed to "normalized" format
     */
    private function modelToNorm($value)
    {
        try {
            foreach ($this->config->getModelTransformers() as $transformer) {
                $value = $transformer->transform($value);
            }
        } catch (TransformationFailedException $exception) {
            throw new TransformationFailedException(
                'Unable to transform value for property path "'.$this->getPropertyPath().'": '.$exception->getMessage(),
                $exception->getCode(),
                $exception
            );
        }

        return $value;
    }
```

Line 141 of /opt/bitnami/apps/mautic/htdocs/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php reads:

```
    /**
     * Transforms a date string in the configured timezone into a DateTime object.
     *
     * @param string $value A value as produced by PHP's date() function
     *
     * @return \DateTime An instance of \DateTime
     *
     * @throws TransformationFailedException If the given value is not a string,
     *                                       or could not be transformed
     */
    public function reverseTransform($value)
    {
        if (empty($value)) {
            return;
        }

        if (!is_string($value)) {
            throw new TransformationFailedException('Expected a string.');
        }

        $outputTz = new \DateTimeZone($this->outputTimezone);
        $dateTime = \DateTime::createFromFormat($this->parseFormat, $value, $outputTz);

        $lastErrors = \DateTime::getLastErrors();

        if (0 < $lastErrors['warning_count'] || 0 < $lastErrors['error_count']) {
            throw new TransformationFailedException(
                implode(', ', array_merge(
                    array_values($lastErrors['warnings']),
                    array_values($lastErrors['errors'])
                ))
            );
        }
```

**Comment by escopecz** [comment] 2017-01-02 10:11
Could you share a part of the CSV with problematic contacts? I'm not able to replicate it.

**Comment by escopecz** [comment] 2017-07-03 09:18
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.

**Comment by josecastano01** [comment] 2020-03-23 04:58
I have the same problem. When integrating hubspot with mautic, the dates appear in the contacts as follows 0000: 00: 00 00:00:00 In mautic no error is generated in the registry.

The first problem is that the dates are not synchronized properly.

The second problem is that the contacts whose date is 0000: 00: 00 in some field cannot be edited


I have the latest version of mautic installed. PHP version 7.2.28

**Comment by escopecz** [comment] 2020-03-23 08:53
Can you write steps how to replicate that manually? Is it enough to add value `0000: 00: 00` to a date time custom field?

**Comment by josecastano01** [comment] 2020-03-24 04:53
To replicate it, you must integrate with a hubspot account.

Create custom date fields in Mautic to map them.

Some of these fields are:

- Became a Customer Date
- Became a Lead Date
- Became a Marketing Qualified Lead Date
- Became an Evangelist Date
- Became an Opportunity Date
- Became an Other Lifecycle Date
- Became a Sales Qualified Lead Date

Running cron integration synchronizes contacts.

In the contacts in which there is no date in Hubspot registers in Mautic 0000-00-00 00:00:00 later they cannot be edited.

In the contacts in which there is a date registered in Hubspot it does not convert it correctly and registers for example 1544-03-12 02:54:00

The error is not generated by creating a field and entering the date manually in Mautic. Neither when a CSV is imported.

Thank you.

**Comment by escopecz** [comment] 2020-03-24 08:50
Can you export such broken contact and provide SQL insert query for it?

**Comment by RCheesley** [comment] 2020-06-30 23:03
I think that the Hubspot issue is a duplicate of https://github.com/mautic/mautic/issues/8814 so closing as a duplicate

**Closed by RCheesley** 2020-06-30 23:03 UTC
Labels: pending-feedback
