### ISSUE TITLE
Tooltips dont go away

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#9505] opened 2020-12-16 15:48 UTC
## Bug Description
Tooltips in campaign builder seem to appear and never go away in some instances. A refresh will clear them but they usually come back fairly quickly while editing. Happens because I like to use my keyboard more than my mouse I guess. Tooltips will persist throughout mautic unless you refresh the page. Dashboard, configuration page, etc you name it they stay.

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3.24
| Browser | Chrome 87.0.4280.88

### Steps to reproduce
1. Create/Open a campaign
2. Launch Builder
3. Click "Select" to create an action
4. Hover mouse over last one on the list
5. Without moving mouse, type "tag" and hit enter
6. Hit cancel on modal or create
7. See tooltips on the screen.

![Screen Shot 2020-12-16 at 10 47 03 AM](https://user-images.githubusercontent.com/985837/102371502-40333080-3f8c-11eb-8c76-28d976a69e7e.png)

![Screen Shot 2020-12-16 at 10 51 40 AM](https://user-images.githubusercontent.com/985837/102371947-bb94e200-3f8c-11eb-8bc4-8fb35032face.png)

### Log errors

JS console error

Uncaught TypeError: Cannot read property 'off' of null
    at libraries.js?v3b271e09:1606
    at HTMLDivElement.complete (libraries.js?v3b271e09:1551)
    at HTMLDivElement.fn (libraries.js?v3b271e09:444)
    at HTMLDivElement.handle (libraries.js?v3b271e09:1031)
    at HTMLDivElement.dispatch (libraries.js?v3b271e09:465)
    at HTMLDivElement.elemData.handle (libraries.js?v3b271e09:451)
    at Object.trigger (libraries.js?v3b271e09:682)
    at HTMLDivElement.<anonymous> (libraries.js?v3b271e09:688)
    at Function.each (libraries.js?v3b271e09:153)
    at jQuery.fn.init.each (libraries.js?v3b271e09:144)
(anonymous) @ libraries.js?v3b271e09:1606
complete @ libraries.js?v3b271e09:1551
fn @ libraries.js?v3b271e09:444
handle @ libraries.js?v3b271e09:1031
dispatch @ libraries.js?v3b271e09:465
elemData.handle @ libraries.js?v3b271e09:451
trigger @ libraries.js?v3b271e09:682
(anonymous) @ libraries.js?v3b271e09:688
each @ libraries.js?v3b271e09:153
each @ libraries.js?v3b271e09:144
trigger @ libraries.js?v3b271e09:688
callback @ libraries.js?v3b271e09:1026
setTimeout (async)
$.fn.emulateTransitionEnd @ libraries.js?v3b271e09:1027
Tooltip.hide @ libraries.js?v3b271e09:1555
Tooltip.destroy @ libraries.js?v3b271e09:1606
(anonymous) @ libraries.js?v3b271e09:1617
each @ libraries.js?v3b271e09:153
each @ libraries.js?v3b271e09:144
Plugin @ libraries.js?v3b271e09:1612
(anonymous) @ app.js?v3b271e09:409
each @ libraries.js?v3b271e09:153
each @ libraries.js?v3b271e09:144
Mautic.campaignBuilderUpdateEventListTooltips @ app.js?v3b271e09:409
(anonymous) @ app.js?v3b271e09:407
dispatch @ libraries.js?v3b271e09:465
elemData.handle @ libraries.js?v3b271e09:451

**Comment by RCheesley** [comment] 2021-01-25 19:40
I was able to reproduce this in 3.2.5 and yes, super annoying!

**Comment by ldrrp** [comment] 2021-04-26 02:40
Ill retest on the latest 3 tomorrow señor stale bot. Maybe if its an easy fix ill do a pr

**Comment by RCheesley** [comment] 2021-04-26 08:52
@ldrrp a PR would be awesome - thank you!

**Comment by biozshock** [comment] 2022-08-05 07:05
~~Tested on latest 4.4. Can't reproduce. All tooltips are gone.~~
Edit: when testing another PR actually found the cause. https://github.com/twbs/bootstrap/issues/20511 . PR is coming your way now.

**Comment by jos0405** [comment] 2022-10-10 08:44
Closing in favour of https://github.com/mautic/mautic/pull/11383

**Closed as completed by jos0405** 2022-10-10 08:44 UTC
Labels: T1, bug, user-interface, campaigns
