### ISSUE TITLE
Contact import fails on same record 'Lead was not configured to cascade persist operations for entity'.

### ISSUE THREAD

**Issue by clanstyles** [mautic/mautic#2863] opened 2016-10-28 21:25 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

Trying to import the below lead list. It always fails on the second record, "Baptist Express Care In", after it's created. 

The lead list is comma delimited with quotes around each cell in UTF-8.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.26 |
### Steps to reproduce:
1. Upload list [18k-med-test - Copy.txt](https://github.com/mautic/mautic/files/559451/18k-med-test.-.Copy.txt)
2. Click import 
### Log errors:

```
(#2) A new entity was found through the relationship 'Mautic\LeadBundle\Entity\ListLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #6364. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
```

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

There was nothing written to any logs in the web server logs or the app logs.

**Comment by brandner** [comment] 2017-03-15 19:24
Seeing this error in 2.7.1, unrelated to import.

During testing (reproducible), I send a email within a campaign to a new contact with a link to a landing page. The first time they click to the landing page they receive the 'Uh-oh' Mautic page. Subsequent clicks and visits work fine.

I haven't been able to reproduce it with a new campaign/email/landing page combination, so I haven't been able to pinpoint a cause.

**Comment by brandner** [comment] 2017-03-16 19:06
OK, after testing every combination I could come up with, these are the reproduction steps that enabled me to cause the error.

- Create test landing page
- Create test email with link to landing page
- Create test segment
- Create test campaign for the test segment
- Campaign workflow: segment -> action: send test email -> decision: visits test page -> action: modify segment -> decision: check field value (check tag not equal to some value) -> action: modify field value (set tag to some value)

The error seems to occur at the 'check contact field value' step.

**Comment by dellabella22** [comment] 2017-04-20 08:20
Im also getting the same error is there a fix for this yet? 

[2017-04-20 09:16:24] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #520. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /usr/www/users/clghyjcxpz/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #520. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /usr/www/users/pathto mautic/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by FabianTe** [comment] 2017-07-04 09:45
I am getting the same error:
```
[2017-07-04 11:21:05] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #18791. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #18791. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
```

Might this in some way be related to #2664? There it says:

```A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead```
vs here:
```A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead```

In my case this error happens only when submitting forms for the first time, but I guess the cause of this bug might be the same.

**Comment by escopecz** [comment] 2017-07-26 15:51
Should be fixed by https://github.com/mautic/mautic/pull/4498

**Closed** 2017-07-28 09:07 UTC
Labels: Bug, Ready To Test

**Comment by namratasaun** [comment] 2021-01-07 18:56
I am not getting this issue in 2.16 but again getting it in 3.2
When I am using tracking pixel for mobile apps
