### ISSUE TITLE
Campaign email trigger cron crashes after first event

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#938] opened 2015-09-24 11:09 UTC
I have something similar to this!
the job also stops after the first lead event 
>sudo php /var/crm/app/console --force mautic:campaigns:trigger --env=prod
...
Triggering events for campaign 4
Triggering first level events
108 total events(s) to be processed in batches of 100
   1/108 [>---------------------------]   0%
[Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #1964. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

similar to #544

**Comment by vikijel** [comment] 2015-09-24 11:39
We have the same issue:

php /data/www/mautic.easyredmine.com/public_html/app/console mautic:campaigns:trigger --env=prod

PHP Warning:  Module 'newrelic' already loaded in Unknown on line 0
Triggering events for campaign 2
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering 'non-action' events
201 total lead(s) to be analyzed in batches of 100
 201/201 [============================] 100%
0 event(s) executed

Triggering events for campaign 3
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering 'non-action' events
18 total lead(s) to be analyzed in batches of 100
 18/18 [============================] 100%
0 event(s) executed

Triggering events for campaign 4
Triggering first level events
43 total events(s) to be processed in batches of 100
  1/43 [>---------------------------]   2%


  [Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist ope
  rations for entity: Mautic\LeadBundle\Entity\Lead with ID #36743. To solve this issue: Either explicitly call EntityManager#persist() on
   this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by wderuijter** [comment] 2015-09-24 11:49
I might have got the same issue for 
php httpdocs/example.com/app/console mautic:campaigns:trigger --env=prod
I receive a CRON email saying:
"Script in progress. Use -f or --force to force execution."

**Comment by escopecz** [comment] 2015-09-24 11:54
@wderuijter that is different problem and could be caused by
1. Another background script running at a time.
2. Error while a background script run so it didn't check itself out.
The error message is saying what to do. Use `-f` parameter to force the script to run. Like
```
php httpdocs/example.com/app/console mautic:campaigns:trigger --env=prod -f
```
(if you use 1.2.0 or newer, you can skip the php at the beginning and --env=prod at the end)

**Comment by ptcc** [comment] 2015-09-24 14:39
This seems to happen to me only if the email has attachments

**Comment by ptcc** [comment] 2015-09-29 14:20
@vikijel do your emails also contain attachments?

**Comment by vikijel** [comment] 2015-09-29 15:03
@ptcc Yes, our campaign id 4 sends email containing a zip archive, but since we processed leads in campaign one by one (by repeating the cron), it seems to be working now - even for more than one lead per batch, so I am not sure if it has something to do with emails.... My tip is it has something to do with specific leads or their data or relations (maybe some merged leads)

Lead #36743 has existing email address and also some social data loaded from google+... and there is huge text in Google+: about me field of he lead and this text contains some external links.

**Comment by edudesouza** [comment] 2015-10-01 18:50
Hi there, I think this should be related to some merger lead.

I had a test area whether the user can try my platform in 3 different roles, each role has its own lead list. If I see that this person did all three he is more qualified to buy our subscription.

I don´t have  any attachment, only plain html is sent.

Triggering events for campaign 1
Triggering first level events
9 total events(s) to be processed in batches of 100

[Doctrine\ORM\ORMException]

Entity of type Mautic\CampaignBundle\Entity\LeadEventLog has identity through a foreign entity Mautic\LeadBundle\Entity\Lead, however this entity has no identity itself. You have to call EntityManager#persist() on the related entity and make sure that an identifier was generated before trying to persist 'Mautic\CampaignBundle\Entity\LeadEventLog'. In case of Post Insert ID Generation (such as MySQL Auto-Increment or PostgreSQL SERIAL) this means you have to call EntityManager#flush() between both persist operations.

mautic:campaigns:trigger [-i|--campaign-id[="..."]] [--scheduled-only] [--negative-only] [-l|--batch-limit[="..."]] [-m|--max-events[="..."]] [-f|--force]

**Comment by edudesouza** [comment] 2015-10-02 14:31
Hi fellows,

To help me understand where was the problem I cutted it on pieces to see where the problem was residing.

I ran each action apart:  
- update list
- update campaigns
- campaign triggers

And I found the problem running all campaign triggers together, I have 5 campaigns.  
I can have one cron task running update list, update campaigns and campaign triggers although it I put the campaign trigger together the error occurs.

The solution, in may case, was run each trigger apart and consecutively,  trigger campaign 1, if finished, fire campaign trigger 2, if finished, fire campaign trigger 3 .... and so on.

I someone else could test this hypothesis, I will glad to hear the result.

**Comment by vikijel** [comment] 2015-10-02 14:41
Leads merging may also be our case - we use multiple forms and mautic aggregates their data into one lead, so the relations error may have something to do this automatic merging of multiple form data into single lead.

*PS: We also submit custom post requests to form submit urls (we have standalone custom non-mautic forms on our web and forward the submitted form data into mautic forms via curl post requests)*

**Comment by alanhartless** [comment] 2015-10-09 04:31
Can you guys test https://github.com/mautic/mautic/pull/996 to see if it could also be the fix for these abnormal behaviors reported here?

Thanks guys!

**Comment by alanhartless** [comment] 2015-10-09 15:00
@ptcc and @vikijel, what does the campaign that's causing the Download entity error look like?

**Comment by ptcc** [comment] 2015-10-09 15:13
a simple open test with modi
![captura de ecra 2015-10-9 as 16 13 03](https://cloud.githubusercontent.com/assets/482937/10397658/b936b85c-6ea0-11e5-8749-d24c96ca9a3c.png)
fy lead lists

**Comment by ptcc** [comment] 2015-10-09 16:56
#996 does not seem to fix this.... Also I tested an even simpler campaign: leadlist -> send email.

**Closed** 2015-10-22 12:15 UTC
Labels: Bug, Ready To Test

**Comment by TiagoGouvea** [comment] 2016-01-13 11:03
I'm having a different issue on that job:

Triggering events for campaign 1
Triggering first level events
2 total events(s) to be processed in batches of 100
 0/2 [>---------------------------]   0%/usr/sbin/sendmail: unexpected response 550 to RCPT TO command
/usr/sbin/sendmail: unexpected EOF

 1/2 [==============>-------------]  50%/usr/sbin/sendmail: unexpected response 550 to RCPT TO command
/usr/sbin/sendmail: unexpected EOF

 2/2 [============================] 100%
0 event(s) executed

Triggering scheduled events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

**Comment by escopecz** [comment] 2016-01-13 11:12
@TiagoGouvea could you create a new issue for it? It is not related to the original issue. Also, since this one is closed, not many people notice your comment.
