### ISSUE TITLE
Sporadically can't drag and drop tokens onto builder

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#529] opened 2015-06-09 20:39 UTC
Before 1.1.2 I drag an drop these buttons 
![image](https://cloud.githubusercontent.com/assets/10166840/8069060/303efc10-0ef8-11e5-8c94-6065fe3aee34.png)
over the email. 

Now nothing happens when I do this.

**Comment by alanhartless** [comment] 2015-06-09 23:52
Hi Miguel,

I can't reproduce this.  I see that the click action isn't working as expected but the drag and drop for me is with each of the three stock templates. 

 Is the drop area activating when you drag the token over it? Does it not work all the time or intermittently? 

Thanks!
Alan

**Comment by miguelpascual** [comment] 2015-06-10 07:08
https://youtu.be/LdrvIOcAB-A

But now it works :S

**Comment by alanhartless** [comment] 2015-06-10 15:09
I'll continue looking at this one.  Thinking that maybe something with jQuery UI droppable, the iframe, CSS, and maybe a combination of focused elements could be causing some sporadic issues.  If you notice a pattern to what could be causing it to stop working, definitely post back!

**Comment by RCheesley** [comment] 2015-06-12 20:47
I had this issue immediately after I had updated, I went into an email builder and the fields wouldn't drag and drop.  It seemed that when I maximised my window and refreshed, the buttons started to work again.

**Comment by escopecz** [comment] 2015-07-09 09:10
Closing this issue since it was probably caused by old, cached JS.

**Closed by escopecz** 2015-07-09 09:10 UTC
Labels: Bug
