### ISSUE TITLE
Old version of SwiftMailer doesn't play nicely with PHP7+

### ISSUE THREAD

**Issue by smcpeck** [mautic/mautic#8189] opened 2019-12-05 05:12 UTC
## Bug Description
E-Mail configuration test fails against SMTP server with TLS1.2 certificate.  Please upgrade to a recent version of Swiftmailer.

| Q   | A
| --- | ---
| Mautic version | 2.15.3 |
| PHP version | 7.1.33 |
| SwiftMailer | 5.4.9 |

### Steps to reproduce
1. Setup SMTP server with TLS1.2 cert.
2. Test SMTP
 
### Log errors
[2019-12-05 04:38:29] mautic.WARNING: PHP Warning - stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version - in file /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php - at line 94 []

### More information:
It looks like the old version of Swiftmailer uses a constant that has changed meaning in recent versions of PHP.

Reference: https://www.php.net/manual/en/function.stream-socket-enable-crypto.php#119122

Changing things where the error is coming from so it matches the current Swiftmailer code fixes this in my current install of Mautic.

Reference: https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/StreamBuffer.php#L94

**Comment by RCheesley** [comment] 2019-12-09 11:33
I believe this is already being addressed with the work going on in the Mautic 3 project, @escopecz can you confirm?

**Comment by escopecz** [comment] 2019-12-09 11:39
That's right! I'll close this as duplicate of https://github.com/mautic/mautic/issues/8018

**Closed by escopecz** 2019-12-09 11:39 UTC
