### ISSUE TITLE
InvalidArgumentException 

### ISSUE THREAD

**Issue by bodiaSBK** [mautic/mautic#8730] opened 2020-04-25 16:13 UTC
Hi, i think this is error in Russian language, on English that good.

[2020-04-25 19:09:09] mautic.ERROR: InvalidArgumentException: Unable to choose a translation for "один: %count%  элемент| несколько: %count% элементов" with locale "ru" for value "8". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples"). - in file /vendor/symfony/translation/MessageSelector.php - at line 81 [] []

**Comment by RCheesley** [comment] 2020-04-27 14:48
Closing as a duplicate of #8716 - let's continue the discussion there.

**Closed as completed by RCheesley** 2020-04-27 14:48 UTC
