### ISSUE TITLE
New leads do not get their emails right away when sending segment emails.

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#3189] opened 2017-01-05 10:49 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
I don't know if I should set this as a bug or feature request but.
When new leads signs up to our newsletter they do not get their email directly when we send out a segment email in the same time because the system is set to queue emails. And when sending over 100.000 emails to a list the new leads do not get their email until the next day when the spool is empty. We then get angry emails from new leads telling us why they don't receive any emails etc.  

So is it possible to split the spool folder into two folders, one for campaigns one for segment emails?
that way new leads would still get their emails directly.
Or just fix an API to Amazon SES ;)   

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version |  

### Steps to reproduce:
1. Send a segment email to a BIG list in Mautic 
2. Sign up as a new lead make some coffee and wait wait until you get the email.

**Comment by escopecz** [comment] 2017-08-25 14:22
This seems like duplicate of https://github.com/mautic/mautic/issues/2425

**Closed by escopecz** 2017-08-25 14:22 UTC
Labels: Feature Request
