### ISSUE TITLE
Salesforce integration - sync tracking code

### ISSUE THREAD

**Issue by beloa-fr** [mautic/mautic#7777] opened 2019-08-08 23:07 UTC
Add the the tracking code field to the mautic list of fields available for export to salesforce.

This will enable the creation of tracked urls in salesforce mails, following this format :

Https://mautic-host/r/asset-id?ct=tracking-code

**Comment by escopecz** [comment] 2019-08-15 08:52
What's the issue again? I'll close this issue. Please create a new one with clear description of what the issue is and provide the whole info that was requested in the issue template.

**Closed by escopecz** 2019-08-15 08:52 UTC

**Comment by beloa-fr** [comment] 2019-08-15 09:55
OK done: https://github.com/mautic/mautic/issues/7798
