### ISSUE TITLE
Only enable the pre-fill form feature if the contact clicked through a link

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#2380] opened 2016-08-24 11:10 UTC
| Bug report? | Yes
| Mautic version | 2.1.0
| PHP version | 5.6.22
### Steps to reproduce:
1. Create a form with a few fields that (under the behavior tab) have "auto fill data" set to "yes".
2. Create a new landing page in Mautic and insert the form code shortcode e.g. `{form=1}` there. 
3. Save & close.
4. Open a new private window in your browser and visit the newly created landing page. 
5. Fill out and submit the form. 
6. Close the private browser window to make sure all identifying data and cookies are erased. 
7. Open a new private browser window and visit the URL of the landing page again. 
8. You will now see all of the auto fill fields filled out with your private data! 

You can also do this: 
9. Visit the landing page in question on a second device (2nd laptop, tablet etc.) that's connected to the same internet connection and thus has the same IP address. 
10. You will now see all of the auto fill fields filled out with your private data!

I don't know for how many days or weeks the private data will be revealed this way to anyone who happens to have the same IP address, but my point here is: 
### Description:

First of all: I think you guys are doing great work and have the best intentions when developing Mautic, but identifying the user **solely based on IP address** (and for how long?) is a serious bug. Not a feature. 

At first, I couldn't believe this and double and triple checked everything to make sure I'm not doing anything wrong. But that's really what's happening. It reveals private data to ANYONE, on any device who happens to have the same IP address (for an unknown period of time, is happening for almost a day now). 

So, here's how to fix this: 
First of all: As a marketer, I would NEVER want to identify a user based solely on their IP address (even if there were no privacy laws violated by such behavior). It's just so imprecise that it has no value to me. 
The industry standard is to identify a user based on my tracking link that they clicked in the email I sent them before and based on the cookie that was set after clicking that tracking link. 
### This is the ONLY time I want auto fill data to work!

Only if I can identify the user with 100% certainty because they just clicked a link I sent them via email! 

When submitting their details for the first time the user has agreed to my privacy terms (on my website), privacy terms that explicitly permit me to use cookies for tracking them. 
And frankly, when a user clicks a tracking link, you don't even need cookies because all required values can be passed in the URL. 

So, that's the ONLY instance when the auto fill should out form fields with user's details! 
ONLY IF the user has clicked my tracking link! 
And cookies can temporarily store that data. That's fine. 

But under no circumstances should the form fields be auto-filled if the user can't be identified with 100% certainty (because they, for example, open a new private browser window or visit a page on a different device). 

Please: NO "fingerprinting" tricks for this! 
No tricks of any kind! 
**Only if they click my tracking link (or have the data from that tracking link stored in their cookies), only then can the form fields be auto-filled with their data. No exceptions!** 

Anything else is gonna land me (as a European Mautic user) in jail. 

Thanks again for your great efforts!
You're doing great work!  :+1: 

P.S. 
The precursor to this auto-fill feature was the ability to pass form field value in the URL of the link sent by email. This passing form field values in the URL never quite worked in my experience with Mautic and was way to cumbersome (and undocumented) to begin with. 

**So, all this auto-fill feature ever needs to be is to be a more convenient version of passing form field values in the URL.**
No more, no less. 
My understanding is that Mautic only needs to pass the user ID in the URL to get all the known user data for the form auto-fill. But those details are irrelevant. 
Important is that the auto-fill only auto-fills if the user clicked the tracking link they got in their email.

**Comment by escopecz** [comment] 2016-08-24 11:34
Hi again! To summarize your post, you want the field prefill feature to be removed, right?

It's turned off by default, so why do you turn it on if you don't want it? There also is a warning about the accuracy in the form tooltip.

You can still prefill the fields from URL query just like before and it's [documented here](https://mautic.org/docs/en/forms/manage_forms.html#pre-populate-a-form-field-value).

As far as I know, EU law says that you must inform your website visitors that you track them. I personally think that that's up to the website owner to make this announcement to their visitors.

I agree that the tracking algorithm must be improved. So is this issue a feature request to improve the tracking algorithm?

**Comment by abooster** [comment] 2016-08-24 11:43
**NO! I absolutely do NOT want that feature to be removed!** 
That's a gross misinterpretation. 
I reported a bug! 
The feature itself is very much needed! 
But without the bug.
Please read my bug report again. Thank you! 
I explained, in a very detailed manner, what the actual issue is and suggested how to fix it.

**Comment by escopecz** [comment] 2016-08-24 11:52
Ok, we clearly do not understand each other, because I think I answered exactly to your concerns. I'll repeat it again.

You say that if you turn on the "auto fill data" feature, it can reveal data of someone else. I say do not turn it on if you don't want to use it. You say you want just to prefill data from the URL, I say you can still do that. You say it's not documented, I published a link to where it is documented. You say that Mautic violates EU laws, I said that every website owner must inform their visitors about the tracking to comply with the EU laws. And to be more accurate, it doesn't matter if you track IP, cookie or fingerprint. If I missed something, then I'm sorry, but your text is quite long and I can't tell which of these issues is the bug you reported. I rather won't react to your comments since it doesn't seem to have any effect.

**Comment by abooster** [comment] 2016-08-24 12:20
There's definitely a misunderstanding going on here. Big time! 
Except, it appears that you don't understand what I'm trying to say and not the other way around. 
I never said "Mautic violates EU laws". That's nonsense! 

OK, let me start again. Hopefully, I'll manage to get my point across this time: 

Please correct me if I'm wrong, but I believe that the whole point of Mautic is to provide marketers a set of tools they need for their work. 
Is this right or wrong? 
It would be pointless just to code something for the sake of coding and ignoring the requirements of people who are actually supposed to use the software. Wouldn't it?

Now, assuming I'm right on that one, let me tell you this: 
The "auto fill data" feature is the further development/refinement of passing form field values in the URL. 
That's just a fact. I'm just stating it here. 
Why do marketers want to pass form field values in the URL? 
Usually, because they want to auto-fill form fields (or customize, in some other way, the web page presented to the user). 
So, this "auto fill data" feature (the original version of it) was created by a marketing-savvy user who wanted to make it easier to pass form field values when the user clicked on a link send via email. 

That's what it is and that's what it was. 

Now, please correct me if I'm wrong, but you seem to be hell-bent on turning this feature into something that marketers don't need or want. (just because it's technically possible to create that sort of functionality) 
I have reported here that not only that sort of thing is not needed and not wanted from a marketer's point of view (although it's great to know that it's technically possible to track an IP address)... 
I have reported that changing the feature the way it was done, not only makes it useless from a marketer's standpoint but also requires the marketer to violate Europeran laws because in it current form the feature tracks the user by IP address alone. 

I really hope that I was descriptive enough this time but do let me know if something is still unclear. 
Thank you! 
I really appreciate your effort and I know it's a lot of work dealing with these issues. 
So, I really appreciate you're doing this. Thanks again! :+1:

**Comment by mqueme** [comment] 2016-08-24 12:50
I think this feature needs to be reviewed in order to make tracking more reliable and verified so that the use of the tool doesn't break any laws.

**Comment by abooster** [comment] 2016-08-24 13:02
@alanhartless 
Alan, I wonder how you see this? 
Am I really so daft at explaining this issue? 
I really apologize for my poor English! 
English is the 4th language I speak and I'm desperately trying to improve it every day but sometimes it's just not enough. It takes a long time to get my point across. I'm so sorry! 

But even though I'm super daft I'm very grateful for the amazing work you guys are doing.
Thumbs up! :+1:

**Comment by alanhartless** [comment] 2016-08-24 14:02
First of all, Alex, I really appreciate these posts. Thank you!

This feature was developed and contributed by a community member. We realized the risk of the IP tracking/details and thus the reason for having it disabled by default. 

What I'm understanding is that because we are defaulting to tracking by IP alone (something we're definitely planning to fix) - this feature should be disabled in any circumstance that we are not 100% sure the contact is who we think they are - i.e. only when the contact did something to identify themself like clicking on a link from an email. Is that right?

Thanks!
Alan

**Comment by alanhartless** [comment] 2016-08-24 14:03
Or maybe not even because we're tracking by IP - but regardless of how we fingerprint, the feature should only work for contacts who have identified themself with 100% certainty.

**Comment by luizeof** [comment] 2016-08-24 16:15
The fix for this "bug" could be an alert on documentation saying that "EU user cannot enable Mautic Auto-fill feature by violating the EU Privacy Laws". I'm a Brazilian user and here this feature can be enabled and is very very useful.

**Comment by abooster** [comment] 2016-08-24 16:15
### > This feature was developed and contributed by a community member.
That's exactly right, Alan! 
Now I feel a tiny little bit less daft than I normally do. 
(normally, I'm completely daft but right now a little less so :) 

This feature was originally developed by a very bright community member @vln104 
But the big question is: 
What did our good friend @vln104 actually intended this feature for? 
Well, I already said it earlier in this thread a couple of times, but don't take my word for it. 
Read the first paragraph here: https://github.com/mautic/mautic/pull/1363

I just didn't have the name of the community member nor the link to that thread when I posted earlier. 

So, repeating myself for probably the 3rd time here: 
Our good friend @vln104 **intended this feature to replace the cumbersome way of passing form field values via URL query string.**
(phew, so glad the light is finally shining through here! :) 

Soooo... it's worth repeating myself for the 4th time: 
This feature currently DOES NOT work the way it was originally meant to. 
(and also primes European users for jail) 

It was NEVER meant to sneakily track the user via IP address only (and regardless of the device). 
That's why I said: 
Please do NOT add any "fingerprinting" sneakiness! 
Just because it's technically possible to track a user via things like cookie-independent device fingerprint does not make it desirable for an ethical marketer to do. 
(we don't want to track the user the way shady agencies like NSA or some shady corporations do)

### Tracking the user this way is illegal in Europe because it violates common privacy laws. 

What we CAN do (in Europe) **and what simultaneously eliminates any uncertainty about the user identity** (because it tracks the user with :100: precision) is tracking via URL query string and/or cookies which is exactly what our good friend @vln104 who originally developed this feature originally intended it to do! 

I totally understand that in all the excitement about coding new features you guys have given this feature a different "flavor". 
But I hope, we all now finally agree that this flavor is: 
a) illegal in Europe 
but also: 
b) is NOT what marketers need or want to do. 

Marketers want to track the user via URL query string (which they've been doing forever and which is completely legal in Europe). 
And we, marketers, also would LOVE to see this feature enhanced and made less "techie" (as our good friend @vln104 said) and allow us to pass form field value with a click of a button instead of the cumbersome and extremely techie way of juggling query string parameters around! 

**Can we, marketers, PLEASE get our voice heard?** 
Thank you so much! 
You are real heroes! :+1: 

P.S. 
Oh, and yes, we, marketers, would also LOVE for the end user to get cookied after he/she clicks a link passing query string parameters! That would also be totally legal and Europe and would also keep the user identified with 100% certainty. 
Thanks again, you are ROCK STARS! :100: 

P.P.S.
**> the feature should only work for contacts who have identified themself with 100% certainty**
Yes, Alan! That's correct! 
**Which is why it should only work if the end user has either clicked our tracking link or has our cookie in their browser.** 

I'm guessing this shouldn't require more than a dozen lines of code to fix, right?

**Comment by luizeof** [comment] 2016-08-24 16:20
@abooster you can disable the email tracking on Settings and use a landing page outside mautic (rg. an wordpress website) without tracking script. I hope this is the only way mautic identify user only when the user fill an form.

**Comment by abooster** [comment] 2016-08-24 16:25
@luizeof my dear friend: Let me talk this issue with @alanhartless
OK?
Alan is a superbly bright guy and has proven to quickly grasp complex issues on the fly! 
He is a legend! 
I'm deeply humbled that he is even replying here 
and we should let his genius untangle this issue! 
Brilliant geniuses like him work best unimpeded!  :+1:  :+1:  :+1:

**Comment by luizeof** [comment] 2016-08-24 16:29
@abooster i'm so sorry.

**Comment by luizeof** [comment] 2016-08-24 16:30
@alanhartless i'm so sorry too.

**Comment by abooster** [comment] 2016-08-24 17:49
@luizeof There's no need to be sorry, Luiz. 
I'm sure you're just trying to help like we all do. 
So, it's all fine and I bet this little bug will be fixed before the next Mautic version making us all as happy as little kids that get a big present from the Santa Clause! :-)

**Comment by alanhartless** [comment] 2016-08-24 17:51
@abooster I'll be re-reading through this again and will reply soon. On a quick note - we implemented the feature code as it was submitted with just moving the new form field to the Behavior tab. So whatever Linh intended I assume was in his code. Now we can take what was submitted and nurture it as the community provides feedback. We obviously don't want any one going to jail. But since it's an opt in feature and the old option of query params remains - I'm assuming wise decisions are being made to avoid jail time. 

On that note, we do welcome discussion from all community members as anything we change will affect everyone who uses it (yourself included obviously). And you did state `Can we, marketers, PLEASE get our voice heard?` I think @luizeof is therefore entitled to share his voice with us too. :-)

On the new comment about the next Mautic version - I'm afraid we've already closed the roadmap for 2.1.1 which is coming out tomorrow. But we'll be looking at this in more detail for the release after that. 

More soon!

**Comment by vln104** [comment] 2016-08-24 17:57
Hi guys,

I'll chime in since it was originally my feature. 

My intention was that I felt passing the values to form fill by URL query parameter was cumbersome and almost impossible for non techies. My intended behaviour was as follow:

The feature relies on Mautic to identify the current lead and does not modify this behaviour in anyway. If a lead is identified and the feature switched on then it will autofill the lead's data. I don't see how it is different from using the URL method because the URL method would also ask Mautic to replace the field values with certain lead fields. So if the lead was identified incorrectly, the URL method would also show the lead data on the form?

**Comment by abooster** [comment] 2016-08-24 18:15
Thank you, @vln104 for validating what I said in this thread about this feature before! 
And I'm so glad you came up with the idea to make this so much easier for us to use! 

Once this bug gets fixed, I'd rate this feature among the top 5 most useful features.

**Comment by dongilbert** [comment] 2016-08-24 18:31
@abooster Your way of trying to get your point across is very abrasive and not easy to receive. Writing long posts with clickbait titles that repeat and belabor a point (you stated yourself that you've repeated yourself 4 times, and once more for good measure) aren't how to push an agenda in an open source community.

The best way to accomplish that is to file the bug using _work-appropriate_ language that does not attack Mautic or those commenting. Then gain support or +1's for the idea or bug through communication. _Listen_ to the responses to see if the answers meet your needs, then reply. 

Oh, I also forgot, don't try to silence those who are commenting. It's one thing to be abrasive towards us at Mautic, but completely unacceptable to be abrasive and antagonistic towards the other community members. Mautic strives to foster _positive_ community growth and interaction.

**Comment by abooster** [comment] 2016-08-24 19:00
@dongilbert When the points I'm trying to get across aren't arriving at the other end, then I believe that repeating those things is warranted and indeed required and necessary. 

Oh, and I'm "not trying to silence those who are commenting". 
I was replying to a person who had previously called me out with a suggestion. So, I replied to him telling him in a very friendly manner that his idea has no relevance to the issue raised here. This perfectly valid and you can hardly call it "trying to silence". 

Also, your impression of me being "abrasive" has absolutely no relation to this particular thread here. 
I think you are referring to one of my previous threads where I was a little abrasive and please accept my apologies for that. 
In this thread though, I haven't been abrasive at all. It's a false, lingering impression of yours. (which is probably due to my failure to apologize for that last incident) 
In this thread here I'm about 100 times more friendly and cordial than I'd normally be in a face-to-face situation. You gotta give me credit for that! :-)

**Comment by dongilbert** [comment] 2016-08-24 19:52
@abooster I don't know you in person; all I have to go off is your interaction with me, the other Mautic team members, and the community.

Let's not turn this into a "he said, she said" situation. It's very clear and public what was said and by whom. Please, just be respectful when interacting with the community.

**Comment by abooster** [comment] 2016-08-24 20:30
@dongilbert Yes, let's not turn this into a "he said, she said" situation. 
And **thank you** for recognizing that I've been VERY cordial and respectful when interacting with the community **in this thread here**. You certainly got that part right. 

I think the main difference between you and me is: 
While you happen to believe that something that's known as "positive thinking" has a value I'm convinced that the so-called "positive thinking" is an **illness**. I was badly affected by this illness for over a decade but luckily I managed to cure myself of that. 

I am aware that from your current point of view you can't possibly recognize "positive thinking" as an illness but I'm afraid that in regards to this point our opinions will remain different. 
I just happen to be a guy with very strong opinions and it will always remain that way. 

Oh, and it's not a good thing for a moderator to remind others that he can click a button if other people's opinions don't perfectly fit his own. This doesn't communicate a very "positive" message about the moderator. A moderator who is an adult should be able to lead discussions with other adults even if the opinions of those other people diametrically oppose his own opinions. This, of course, is not an easy thing to do because it requires strength of character and the ability to endure other opinions (even if they don't perfectly correspond with one's own opinions) and sometimes it might even require presenting logical arguments in a convincing manner. 
Clicking a button is so much easier than that! :-)

**Comment by dongilbert** [comment] 2016-08-24 21:05
@abooster The post will only be locked if you continue to belittle and berate our fellow community members. What's next is up to you.

**Comment by abooster** [comment] 2016-08-24 21:17
@dongilbert "continue to belittle and berate" implies that I have previously done that in this thread. 
This is NOT true. I have NOT done any of that in this thread. There's absolutely no evidence of that. 
I was merely replying to people who were expecting a reply from me. 

**Your attempt to frame my humorous replies as "belittle and berate" is wrong and doesn't correspond with facts.** 

And YES, I'd absolutely LOVE to return to the discussion at hand! 
I would have done so a looong time ago -- if only there wasn't a need to defend myself from false claims and accusation. 
You can't possibly ask me to stop defending myself from false claims and accusations, can you?

**Comment by alanhartless** [comment] 2016-08-25 13:14
For now - I am going to consider this a feature request and not a bug for the following reasons reasons:

1. The code implemented is doing what it was designed to do under the restraints Mautic currently provides which is made clear by [Linh who coded the feature](https://github.com/mautic/mautic/issues/2380#issuecomment-242154026).
2. It's not breaking laws unless enabled in a country that it is illegal in - therefore if it breaks a law for where the marketer resides, don't enable it and use the prior existing behavior.
3. Because the feature is doing what it was coded to do - any enhancements or improvements of said feature is not a bug - but rather a feature request or an enhancement request.

Rest assured - we will be addressing this. However, we are not currently seeing a reason to make it top priority. With that said, all pull requests are welcome if a community or hired dev would like to enhance the feature with the suggested improvements from the original post.

**Comment by merlin0** [comment] 2016-08-25 19:00
I think the topic starter has has shed some light on a much bigger issue, diffrent laws in European Countries and around the world. For example in my country it's officialy not legal to detect wether or not a user uses an adblocker, which the fingerpint.js can do. Since not every Mautic user will understand how the combinination of Ip and Fingerpint.js tracking works it might be a good Idea to inform them it might be illigal or they should notify their vistors that they are being tracked when using Mautic. Aslo I can imagne that with future features we might to update our privacy policy in some way so it would be nice to have an heads up if a features or a new tracking implementation could be a legal issue.

Regardless the progression has been amazing so far, the rate the new features are coming are great!

**Comment by abooster** [comment] 2016-08-25 19:16
@merlin0 All of the problems with this feature (legal problems as well as technical problems i.e. the ability to identify the user with 100% accuracy), all those problems instantly disappear if this feature is modified in such way that only a link click and/or user ID stored in a cookie on end user's machine is used for tracking. 
There would be no need to update any privacy policies or worry about any laws if the tracking is limited to using only the link/cookie combination. Because in this form it becomes just a better and infinitely more convenient) version of passing URL query parameters.

**Comment by luizeof** [comment] 2016-08-25 20:14
summarizing, if I disable autofill I continue breaking the law?

**Comment by abooster** [comment] 2016-08-25 20:25
Luiz, we don't want to "disable" the auto-fill. 
We want to USE the auto-fill because... it's very USEFUL! 
I know, this idea is very difficult to grasp, but I hope you got it now. And if not, don't worry about it.

**Comment by luizeof** [comment] 2016-08-25 21:42
@abooster I really get upset with her way of expressing to me or other members of this growing community that help thousands of companies to reap the benefits of digital marketing, in Brazil we have less stringent laws with digital privacy but I understand your concerns about privacy and I also have the same concerns. But as we have seen in the comments of the developers this is not a bug but a feature that needs improvement, and neither is on the priority list of time as it does not affect a lot of users. For now I will disable this feature to not break these rules. I find it easier to disable a feature in Mautic than asking for developers who are already busy with more important things to change things to my taste. Thanks for your time and be happy my friend, life is too short for grudges and coarseness.

**Comment by luizeof** [comment] 2016-08-25 21:46
@abooster I also find interesting to adjust the Mautic documentation with an alert to this "possible problem" and for now the user can disable the feature to not have problems with the law.

**Comment by abooster** [comment] 2016-08-25 22:01
@luizeof And I really get upset when people can't read or are lacking the ability to understand the most simplistic things. But maybe it's just because I forgot to take my dafty pills today? 
That's must be it! I'm so sorry that I forgot to take my dafty pills! I'll do this right now! 

It has been said numerous times in this thread that this feature is *disabled* by default. 
But again, the ability to read and understand basic English would be required for that. 
Maybe that's the issue here? If yes, I'm truly sorry because I didn't take that into account. (but will do next time, promise!) 

So, my dear: There's absolutely NO need for you to disable anything. This feature is disabled by default. 
And trust me, my friend: I also badly need to improve my English!

**Comment by dbhurley** [comment] 2016-08-26 10:19
A bug implies the feature does not work as intended. The feature does work, the feature is also disabled by default requiring user interaction to enable and thus assume responsibility for implementation. The correct label for this issue is "feature request" and has now been tagged as such. We will review this for possible inclusion in a future Mautic release. If, in the meantime, there is anyone in the community interested in submitting a pull request to improve this feature then you are welcome to do so! https://github.com/mautic/mautic/pulls 

Thanks all for your input and feedback.

**Comment by zyzioziom** [comment] 2016-08-26 11:19
I'd like to focus on something else than EU laws here.
Imagine somebody on public computer (library) filling the form with sensitive data. Another person from the same library can visit the website and read all of this info because it's prefilled thanks to the same IP address.

**Comment by abooster** [comment] 2016-08-26 12:06
@zyzioziom Well, in this post, you are definitely a voice of reason! 
I might have had more success in getting this classified as a bug if I had focused on this point. 
Alas, it's only a feature request now! With no milestone set. :-)

**Comment by alanhartless** [comment] 2016-08-26 12:26
Yup. Exactly why it's disabled by default and that very warning is in the
feature tooltip/explanation.

Mautic plans to improve both fingerprinting/contact identification along
with enhancing this feature for that very reason. Until then, if that's a
huge concern for the present for the audience you're reaching, leave the
option disabled and use the old method of URL embedded values.

Pull requests with code suggestions are always welcome! 😉

**Comment by abooster** [comment] 2016-08-26 12:30
If I were any good at coding, I'd make a pull request with 2 tons of pulling power! :)

**Closed** 2017-11-27 15:58 UTC
Labels: Backlog, Feature Request
