### ISSUE TITLE
Cannot edit contact - bug?

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1830] opened 2016-06-06 15:01 UTC
## Description
Seems that there is a bug in mautic contact editor

## Steps to reproduce
1. Added new field but forgot setting order
2. Login > Contact > Edit Contact ... nothing happens

Updated to latest stable version 1.4.1 did not solve the problem. Cache is cleared, migrations are run.

## Logs
mod_fcgid: stderr: PHP Fatal error:  Call to a member function isRendered() on a non-object in /path-to-mautic/app/bundles/LeadBundle/Views/Lead/form.html.php on line 153, referer: http://www.finkmedia.de/ma/s/contacts

## Solution
force to set field order on adding/updating new fields!

**Comment by escopecz** [comment] 2016-06-06 17:16
Possible duplicate of https://github.com/mautic/mautic/issues/1780. Please inspect the comments there and also please test if https://github.com/mautic/mautic/pull/1827 fix it for you.

**Comment by manuelfink** [comment] 2016-06-17 09:44
Gonna check with next release. Not having the time to set up a dev environment right now :(

**Comment by manuelfink** [comment] 2016-06-17 09:50
Just reviewed #1827. I don't think this resolves the problems I experienced. Form Rendering appears to also run into problems if field order is not set.

**Closed** 2016-08-01 05:03 UTC
