### ISSUE TITLE
A lag during API requests

### ISSUE THREAD

**Issue by treehousetim** [mautic/mautic#4101] opened 2017-05-19 22:50 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Using the API with HTTP Basic Auth causes Symfony\Component\Security\Http\Firewall to consume 500+ms.  We are trying to optimize our API calls because we're doing a search then an update or an insert and this causing 2-3 API calls per contact in our system of record which is translating into 2-4 seconds total to get a contact in and/or updated.

A screenshot is available from the symfony profiler.
![API using HTTP Basic Auth Profiler Screenshot](https://cloud.githubusercontent.com/assets/541887/26268972/93f23440-3cb7-11e7-9de1-f4ea7652a4f1.png)

Normal visits through a web browser come in at 62 ms _total_ with Symfony\Component\Security\Http\Firewall consuming 11 ms (just as one example).

Screenshot for that one is attached as well.
![Non API Profiler Screenshot](https://cloud.githubusercontent.com/assets/541887/26269057/3b39df32-3cb8-11e7-91fd-f2c8d0572938.png)

| Q   | A
| --- | ---
| Symfony version | 2.8.15
| Mautic version | v2.7.2-dev
| PHP version | 7.0.15-0ubuntu0.16.04.4

### Steps to reproduce:
1. Use basic auth to connect to the API

```
<?php
$mm = new myMautic();
$mm->insertOrUpdate();

class myMautic
{
	public function insertOrUpdate( )
	{
		// ApiAuth->newAuth() will accept an array of Auth settings
		$settings = [
			'userName'   => 'user',
			'password'   => 'pass',
		];

		// Initiate the auth object specifying to use BasicAuth
		$initAuth = new \Mautic\Auth\ApiAuth();
		$auth = $initAuth->newAuth($settings, 'BasicAuth');

		$api = new \Mautic\MauticApi();
		$contactApi = $api->newApi( 'contacts', $auth, 'http://example.com/' );

		$contactData['login_id'] = 1000;
		$contactData['email'] = 'example@example.com';

		// existing Login id
		if ( $contact = $this->getFirst( [ 'o_login_id' => $ds->o_login_id ] ) )
		{
			$result = $api->edit( $contact['id'], $contactData );
		}
		elseif ( $contact = $this->getFirst( ['email' => $ds->email ] ) )
		{
			$result = $api->edit( $contact['id'], $contactData );
		}
		else
		{
			$result = $api->create( $contactData );
		}

		// to get the profiler url (with profiling turned on)
		var_dump( $api->getResponseHeaders() );
	}
	//------------------------------------------------------------------------
	public function getFirst( $terms )
	{
		// ApiAuth->newAuth() will accept an array of Auth settings
		$settings = [
			'userName'   => 'user',
			'password'   => 'pass',
		];

		// Initiate the auth object specifying to use BasicAuth
		$initAuth = new \Mautic\Auth\ApiAuth();
		$auth = $initAuth->newAuth($settings, 'BasicAuth');

		$api = new \Mautic\MauticApi();
		$contactApi = $api->newApi( 'contacts', $this->auth(), $this->apiUrl() );

		$search = $this->buildSearch( $terms );

		$result = $api->getList($search);
		if( array_key_exists( 'contacts', $result ) === false )
		{
			throw new Exception( 'Request Failed: ' . print_r( $result, true ) . PHP_EOL . print_r( $api, true ) );
		}

		$items = $result['contacts'];


		if ( $result['total'] >= 1 )
		{
			return array_pop( $items );
		}
		else
		{
			return false;
		}
	}
	//------------------------------------------------------------------------
	public function buildSearch( $terms )
	{
		$search = [];
		foreach ( $terms as $key => $value )
		{
			$search[] = $key . ':' . $value; 
		}
		return implode( ' ',  $search );
	}
}

**Comment by escopecz** [comment] 2017-05-22 07:46
Wouldn't it be better to let Mautic do the merging? https://github.com/mautic/mautic/pull/3317

**Comment by treehousetim** [comment] 2017-05-22 17:14
@escopecz I will look into that.  Thanks.  I still find the underlying latency of using basic auth odd - any ideas about that?

**Comment by escopecz** [comment] 2017-05-22 17:34
Maybe use some profiler like New Relic or Blackfire to see what's causing the latency issue. If you find something, let us know here. I'll close this issue for now.

**Comment by sbrendtro** [comment] 2017-05-22 19:40
Sorry, but I don't understand why this is being closed.  I can reproduce this issue as well - on multiple servers to boot.  There is a significant lag on the API that needs to be further investigated and fixed.  This issue should remain open.

**Comment by escopecz** [comment] 2017-05-23 06:10
I suggested how to make it work with one less request. But if the issue is the lag, I'll rename the issue and leave it open.

**Comment by npracht** [comment] 2020-08-04 20:40
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by treehousetim** [comment] 2020-08-04 20:42
Thanks for checking in.  The company I work for has moved on from Mautic.  I have no need to fix this problem.  Thanks.

**Closed** 2020-08-04 20:53 UTC
Labels: API, bug, triage-mautic-3
