### ISSUE TITLE
Unable to trigger focus in a campaign after an update

### ISSUE THREAD

**Issue by pawneetdev** [mautic/mautic#5757] opened 2018-02-28 12:04 UTC
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
**I want to show focus in a campaign only.**

Case 1:
If I publish the focus and include the JS of the focus, it gets triggered when the page is loaded i.e. without the campaign being triggered.

Case 2:
If I unpublish the focus and include the JS of the focus, it *used to get triggered* only in campaigns, which served my purpose. But since I updated mautic today in the morning, it stopped triggering, when unpublished.

### Steps to reproduce:
1. Create a focus. Set it unpublished.
2. Create a campaign and trigger the focus.

**Comment by directpromo** [comment] 2018-10-17 10:09
Confirm the bug. It doesn't work for me either.

**Comment by tykarol** [comment] 2019-07-03 19:50
Check if the issue is not the same as in https://github.com/mautic/mautic/pull/7663

**Comment by RCheesley** [comment] 2020-03-05 20:49
Closing as I believe this should be the correct behaviour - if the focus is unpublished it should not be triggered under any circumstances. If it is published, it can be triggered via the campaign to show.

**Closed by RCheesley** 2020-03-05 20:49 UTC
Labels: Bug
