### ISSUE TITLE
Ability to add category to segments

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2413] opened 2016-08-29 12:36 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
There is more or less the ability to **add a category** everywhere. But in the segment menu, it is not possible to categorize them.
It would be very useful to store them depending on a category.

**Comment by alanhartless** [comment] 2016-08-29 14:55
Duplicate of #899 and #1721

**Closed by alanhartless** 2016-08-29 14:55 UTC
Labels: Feature Request
