### ISSUE TITLE
Allowed memory size of exhausted when trying to update to 2.15.3

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#8308] opened 2020-01-08 06:53 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0 and 7.2
| Browser | 

### Steps to reproduce
PHP limit: 896M

Cleared cache folder
Updated using these commands:
php public_html/app/console mautic:update:find
php public_html/app/console mautic:update:apply

Got this error:

[Symfony\Component\Debug\Exception\OutOfMemoryException]
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
44044288 bytes)
 
### Log errors
[2020-01-08 06:33:21] request.INFO: Matched route "mautic_core_ajax". {"route_parameters":{"_controller":"Mautic\\CoreBundle\\Controller\\AjaxController::delegateAjaxAction","_route":"mautic_core_ajax"},"request_uri":"http://mauticurl.com/s/ajax?action=updateUserStatus&mauticLastNotificationId=&mauticUserLastActive=901"} []
[2020-01-08 06:33:21] security.DEBUG: Read existing security token from the session. {"key":"_security_mautic"} []
[2020-01-08 06:33:21] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Mautic\\UserBundle\\Security\\Provider\\UserProvider"} []
[2020-01-08 06:33:21] security.DEBUG: Stored the security token in the session. {"key":"_security_mautic"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-02-02 20:54
Hi there, thanks for reporting this! I believe it is a duplicate of #7408 so closing this in favour of that issue, which has a fix that was merged. Please take a look at the discussion over there which might help you to address this issue and get your instance updated!

**Closed by RCheesley** 2020-02-02 20:54 UTC
