### ISSUE TITLE
segmentation campaign issues

### ISSUE THREAD

**Issue by dhmusman** [mautic/mautic#8102] opened 2019-11-05 11:59 UTC
SETUP: Our current setup is we're self hosted and we're using Amazon SES to send email. We did install the recent update v2.15.3 on October 29th, but since we had the below problem, we rolled it back to v2.15.2. We still have the below issue.

PROBLEM: When sending a segmentation campaign, it will only send the amount of emails that you set in the "enter the number of emails to send per batch" screen. 

Our sending limit is 14 per second with Amazon SES, so 840 per minute. I've tested it all the way up to sending 600 at a time (today) per batch and waiting 10 minutes and it's done. The other issue is once it's sending, the progress bar doesn't update unless I only set the batch amount to 100, then it will show 100 once those 100 have been sent, but then of course just stops. Anything above that the progress bar doesn't move, so I just set a timer for it and then cancel the send after 10 minutes. Then I'll go back to the batch setting page and set it again and resend. Repeat.

LAST TIME WORKING: The last time it was working and sending with no issues was on 03 October. We hadn't sent any segmentation emails since then up until October 30th.

**Comment by RCheesley** [comment] 2020-07-16 14:26
Unable to reproduce this in Mautic 3.x so closing this issue.

**Closed by RCheesley** 2020-07-16 14:26 UTC
Labels: Bug
