### ISSUE TITLE
An admin UI link that causes a 500 error fails silently for the user

### ISSUE THREAD

**Issue by joachim-n** [mautic/mautic#12523] opened 2023-06-26 12:39 UTC
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Firefox

### What happened?

Some of the links in the admin UI, e.g. 'Configuration' have no effect when I click them.

Copy-pasting the URL for the link, e.g. https://MYDOMAIN/s/config/edit and opening it shows a 500 error.

The admin UI should shows some sort of feedback to the user, e.g. an error message, instead of the JS failing silently.

### How can we reproduce this issue?

1: Do something so that an admin link causes a 500
2: Click on it in the admin UI.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment] 2023-07-05 09:06
Hi @joachim-n ... seems like some setup issue. I tried to reproduce, but my system doesn't give me error 500 for opening the configuration as admin. It sometimes takes some loading time. But it works. I even tested it in firefox.

So the issue is the error 500 that needs to be solved?
Or do you suggest, that - even if there is an issue with the system, the UI should behave better and catch and display the error to the user?

**Comment by joachim-n** [comment] 2023-07-05 09:13
>  Or do you suggest, that - even if there is an issue with the system, the UI should behave better and catch and display the error to the user?

Yes, that's my point for this issue.

(I don't know what caused the 500 but it's happened several times - if I can find that out, I'll file a separate issue for it.)

**Comment by dsp76** [comment] 2023-07-05 09:39
Mhm, given the current nature of issues and prioritization I would suggest we close it - as its more like a feature request: "Improve UX in the error handling" -> https://forum.mautic.org/c/ideas/14 ... would you please open this request?

**Closed as not planned by dsp76** 2023-07-05 09:39 UTC
Labels: bug, wont-fix
