### ISSUE TITLE
Cannot Send Emails

### ISSUE THREAD

**Issue by jamesjosh912** [mautic/mautic#10141] opened 2021-06-08 06:06 UTC
My Mautic version is: 4.15.0
My PHP version is: 7.4.16
My Database type and version is: ?

Your problem
My problem is: Cannot Send Emails

These errors are showing in the log:

[2021-04-27 00:20:07] mautic.NOTICE: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The “swiftmailer.transport.real” service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. (uncaught exception) at /var/www/html/mautic/vendor/symfony/dependency-injection/Container.php line 275 while running console command mautic:emails:send

[2021-04-27 00:20:07] mautic.WARNING: Command mautic:emails:send exited with status code 1

Steps I have tried to fix the problem:

"found a workaround:

replace it with:

/var/www/html/mautic/bin/console swiftmailer:spool:send --message-limit=1 --env=prod

the above limit=1 can be changed to anything u want"

Someone gave me this solution, but I am not sure what they mean. Do I make this change somewhere in WINSCP, Putty, mautic, etc? Can someone please help me with this work-around? I am looking for any and other solutions as well.

**Comment by imihandstand** [comment] 2021-06-10 22:13
> "found a workaround:
> 
> replace it with:
> 
> /var/www/html/mautic/bin/console swiftmailer:spool:send --message-limit=1 --env=prod
> 
> the above limit=1 can be changed to anything u want"
> 
> Someone gave me this solution, but I am not sure what they mean. Do I make this change somewhere in WINSCP, Putty, mautic, etc? Can someone please help me with this work-around? I am looking for any and other solutions as well.

They mean do that change in the **CronJob** - where you set the cronjobs to run every X minutes to execute everything (campaigns, sending, segments, etc.). This is not done within Mautic, it's done somewhere else - often in cPanel.

**Comment by jamesjosh912** [comment] 2021-06-10 22:52
So like this? It says I have an error in my cronjobs though.
![cron](https://user-images.githubusercontent.com/68710900/121606851-e84a2380-ca1c-11eb-9a54-09e122346689.png)

**Comment by RCheesley** [comment] 2021-06-13 17:07
Closing as a probable duplicate of #9948

**Closed as completed by RCheesley** 2021-06-13 17:07 UTC
Labels: needs-triage
