### ISSUE TITLE
Form field value condition in campaign shows [object Object]

### ISSUE THREAD

**Issue by mikerowe81** [mautic/mautic#4272] opened 2017-06-21 17:41 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When adding a "Form field value" condition to a campaign, and selecting a form field that is a Select field, all of the "Value" options show up as "[object Object]"

![error](https://user-images.githubusercontent.com/3849143/27398184-f447f8e6-5686-11e7-8f96-7da9374d5345.png)

I had some old forms that were created in an earlier version of Mautic that were showing up correctly in a campaign, but if I went to that form and re-saved that form field, in then broke it in the campaign. It looks like the way select fields in forms are saved has changed at some point to allow for a _value_ and a _label_.

Here's an example of the same form field saved in the DB:
**Older Version**
`a:3:{s:4:"list";a:1:{s:4:"list";a:3:{i:0;s:3:"Mr.";i:1;s:4:"Miss";i:2;s:4:"Mrs.";}}s:11:"empty_value";N;s:8:"multiple";b:0;}`

**Current Version**
`a:4:{s:4:"list";a:1:{s:4:"list";a:3:{i:0;a:2:{s:5:"label";s:3:"Mr.";s:5:"value";s:3:"Mr.";}i:1;a:2:{s:5:"label";s:4:"Miss";s:5:"value";s:4:"Miss";}i:2;a:2:{s:5:"label";s:4:"Mrs.";s:5:"value";s:4:"Mrs.";}}}s:11:"empty_value";N;s:8:"multiple";i:0;s:8:"syncList";i:0;}`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18

### Steps to reproduce:
1. Create Form with Select field
2. Create Campaign and add "Form field value" condition and choose the form and select field
 
### Log errors: 

mautic.WARNING: PHP Warning - Illegal offset type - in file /path/to/mautic/app/bundles/FormBundle/Form/Type/CampaignEventFormFieldValueType.php - at line 104

**Comment by escopecz** [comment] 2017-07-18 09:57
Closing as a duplicate of https://github.com/mautic/mautic/issues/4323 which also already have a fix linked.

**Closed by escopecz** 2017-07-18 09:57 UTC
Labels: Bug
