### ISSUE TITLE
Add "switch" to campaign builder

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#2003] opened 2016-07-11 07:01 UTC
## Description

It would be great to have an analog of PHP `switch` statement in campaign builder.
I mean, choose a field which is going to be "switched" - and then add several "cases" with ability to provide default one.
This feature would replace a cascade of conditions, making campaign building a lot more pleasant.

**Comment by merlin0** [comment] 2016-07-21 09:50
This would be great ! I think this feature with #2023 will set-up an campaign a lot easier indeed. +1

**Comment by escopecz** [comment] 2017-03-06 08:48
I'll close this as a duplicate of https://github.com/mautic/mautic/issues/2023

**Closed by escopecz** 2017-03-06 08:48 UTC
Labels: Feature Request
