### ISSUE TITLE
Boadcast email sending error

### ISSUE THREAD

**Issue by tuiuiudev** [mautic/mautic#10162] opened 2021-06-17 14:12 UTC
<p style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What type of report is this:</p>
<table role="table">
<thead>
<tr>
<th>Q</th>
<th>A</th>
</tr>
</thead>
<tbody>
<tr>
<td>Bug report?</td>
<td>BUG</td>
</tr>
<tr>
<td>Feature request?</td>
<td></td>
</tr>
<tr>
<td>Enhancement?</td>
<td></td>
</tr>
</tbody>
</table>

<h2 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-weight: 600; font-size: 1.5em; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-secondary); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: `initial;">Description:</h2>
<p>When broadcasting an email message, we get a really low open rate as it appears that the email message was not sent properly to all contacts.
</p>
<p>When submitting manually through the web browser, we get a completely different open rate, up to 30% more.
</p>
<p>This test I described is for the same email message and the same contact segment.
</p>
<h2 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-weight: 600; font-size: 1.5em; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-secondary); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If a bug:</h2>
<table role="table">
<thead>
<tr>
<th>Q</th>
<th>A</th>
</tr>
</thead>
<tbody>
<tr>
<td>Mautic version</td>
<td>v3.3.3
</td>
</tr>
<tr>
<td>PHP version</td>
<td>7.4.16</td>
</tr>
</tbody>
</table>

<h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Steps to reproduce:</h3>
<ol style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
<li style="box-sizing: border-box;">Create an email message to be Published at any (date/time) in the future</li>
<li style="box-sizing: border-box; margin-top: 0.25em;">Select a segment and save it.</li>
<li style="box-sizing: border-box; margin-top: 0.25em;">Wait until it is sent.</li>
<li style="box-sizing: border-box; margin-top: 0.25em;">Duplicate this message.</li>
<li style="box-sizing: border-box; margin-top: 0.25em;">And send the cloned one after the first one has been sent. You can wait a day or two if so.</li>
</ol>
<h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Log errors:</h3>
<p>Not sure if related.. but appears to be so:
</p>
<p>[2021-06-17 13:05:09] mautic.ERROR: Invalid clickthrough value: Yjo4OntmOjk6ImZiaGVkZiI7Yjo1Ont2OjM7Zjo4OiJmemJ2eSI7djo0O3Y6NjU2O31mOjg6ImZ6YnZ5Ijt2OjY1NjtmOjc6ImZnYmciO2Y6NTU6IjkzZGI4YWFmZDg3M2U3NTY4NTUwMjQiO2Y6NzoieWZiZSI7Zjo3OiI3ODM1IjtmOjA6ImR1YmFhZnkiO2I6NDp7Zjo4OiJmemJ2eSI7djo2NTY7fX0= {"exception":"[object] (Mautic\\CoreBundle\\Exception\\InvalidDecodedStringException(code: 0): The string b:8:{f:9:\"fbhedf\";b:5:{v:3;f:8:\"fzbvy\";v:4;v:656;}f:8:\"fzbvy\";v:656;f:7:\"fgbg\";f:55:\"93db8aafd873e756855024\";f:7:\"yfbe\";f:7:\"7835\";f:0:\"dubaafy\";b:4:{f:8:\"fzbvy\";v:656;}} is not a serialized array at /home/pontodereferenci/info/app/bundles/CoreBundle/Helper/ClickthroughHelper.php:46)"} []</p>
<p>[2021-06-17 10:05:42] mautic.NOTICE: Swift_TransportException: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: >>  .  << 250 2.0.0 Ok: queued as 9CF8482  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 520C912A  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 0D6626E  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as B0DC58F  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 8425368  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 2FC9785  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 550 5.1.2 : Recipient address rejected: Domain not found  !! Expected response code 250/251/252 but got code "550", with message "550 5.1.2 : Recipient address rejected: Domain not found " (code: 550) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) Log data: << 250 2.0.0 Ok: queued as 9CF8482  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 520C912A  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 0D6626E  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as B0DC58F  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 8425368  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 2FC9785  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 550 5.1.2 : Recipient address rejected: Domain not found  !! Expected response code 250/251/252 but got code "550", with message "550 5.1.2 : Recipient address rejected: Domain not found " (code: 550) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: >>  .  << 250 2.0.0 Ok: queued as 9CF8482  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 520C912A  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 0D6626E  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as B0DC58F  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 8425368  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 2FC9785  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 550 5.1.2 : Recipient address rejected: Domain not found  !! Expected response code 250/251/252 but got code "550", with message "550 5.1.2 : Recipient address rejected: Domain not found " (code: 550) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) (code: 554) (uncaught exception) at /home/pontodereferenci/info/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/LoggerPlugin.php line 124 while running console command `mautic:emails:send` [] []</p>
<p>[2021-06-17 10:05:42] mautic.WARNING: Command `mautic:emails:send` exited with status code 255 [] []</p>
<p>[2021-06-17 10:05:42] mautic.NOTICE: Swift_TransportException: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: >>  .  << 250 2.0.0 Ok: queued as 9CF8482  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 520C912A  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 0D6626E  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as B0DC58F  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 8425368  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 2FC9785  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 550 5.1.2 : Recipient address rejected: Domain not found  !! Expected response code 250/251/252 but got code "550", with message "550 5.1.2 : Recipient address rejected: Domain not found " (code: 550) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) Log data: << 250 2.0.0 Ok: queued as 9CF8482  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 520C912A  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 0D6626E  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as B0DC58F  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 8425368  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 2FC9785  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 550 5.1.2 : Recipient address rejected: Domain not found  !! Expected response code 250/251/252 but got code "550", with message "550 5.1.2 : Recipient address rejected: Domain not found " (code: 550) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: >>  .  << 250 2.0.0 Ok: queued as 9CF8482  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 520C912A  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 0D6626E  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as B0DC58F  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 8425368  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 250 2.1.5 Ok  << 354 End data with .  >>  .  << 250 2.0.0 Ok: queued as 2FC9785  >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 550 5.1.2 : Recipient address rejected: Domain not found  !! Expected response code 250/251/252 but got code "550", with message "550 5.1.2 : Recipient address rejected: Domain not found " (code: 550) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) (code: 554) (uncaught exception) at /home/pontodereferenci/info/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/LoggerPlugin.php line 124 while running console command `mautic:emails:send` [] []
</p>
<p>[2021-06-17 10:05:42] mautic.WARNING: Command `mautic:emails:send` exited with status code 255 [] []
</p>
<p>[2021-06-17 11:00:43] mautic.NOTICE: Swift_TransportException: Expected response code 250 but got code "503", with message "503 5.5.1 Error: nested MAIL command " Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtpz.f1.k8.com.br ESMTP Postfix  >> EHLO info.pontodereferencia.com.br  << 250-smtpz.f1.k8.com.br 250-PIPELINING 250-SIZE 33554432 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH PLAIN YXRlbmRlPXBvbnRvZGVyZWZlcmVuY2lhLmNvbS5icgBhdGVuZGU9cG9udG9kZXJlZmVyZW5jaWEuY29tLmJyAGF0ZW5kZSQkMTA=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/  !! Expected response code 250/251/252 but got code "554", with message "554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/ " (code: 554) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtpz.f1.k8.com.br ESMTP Postfix  >> EHLO info.pontodereferencia.com.br  << 250-smtpz.f1.k8.com.br 250-PIPELINING 250-SIZE 33554432 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH PLAIN YXRlbmRlPXBvbnRvZGVyZWZlcmVuY2lhLmNvbS5icgBhdGVuZGU9cG9udG9kZXJlZmVyZW5jaWEuY29tLmJyAGF0ZW5kZSQkMTA=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/  !! Expected response code 250/251/252 but got code "554", with message "554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/ " (code: 554) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) (code: 554) >> MAIL FROM:  >> RCPT TO:  >> DATA  << 503 5.5.1 Error: nested MAIL command  !! Expected response code 250 but got code "503", with message "503 5.5.1 Error: nested MAIL command " (code: 503) Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtpz.f1.k8.com.br ESMTP Postfix  >> EHLO info.pontodereferencia.com.br  << 250-smtpz.f1.k8.com.br 250-PIPELINING 250-SIZE 33554432 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH PLAIN YXRlbmRlPXBvbnRvZGVyZWZlcmVuY2lhLmNvbS5icgBhdGVuZGU9cG9udG9kZXJlZmVyZW5jaWEuY29tLmJyAGF0ZW5kZSQkMTA=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/  !! Expected response code 250/251/252 but got code "554", with message "554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/ " (code: 554) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtpz.f1.k8.com.br ESMTP Postfix  >> EHLO info.pontodereferencia.com.br  << 250-smtpz.f1.k8.com.br 250-PIPELINING 250-SIZE 33554432 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH PLAIN YXRlbmRlPXBvbnRvZGVyZWZlcmVuY2lhLmNvbS5icgBhdGVuZGU9cG9udG9kZXJlZmVyZW5jaWEuY29tLmJyAGF0ZW5kZSQkMTA=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/  !! Expected response code 250/251/252 but got code "554", with message "554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/ " (code: 554) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) (code: 554) >> MAIL FROM:  >> RCPT TO:  >> DATA  << 503 5.5.1 Error: nested MAIL command  !! Expected response code 250 but got code "503", with message "503 5.5.1 Error: nested MAIL command " (code: 503) !! Expected response code 250 but got code "503", with message "503 5.5.1 Error: nested MAIL command " Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtpz.f1.k8.com.br ESMTP Postfix  >> EHLO info.pontodereferencia.com.br  << 250-smtpz.f1.k8.com.br 250-PIPELINING 250-SIZE 33554432 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH PLAIN YXRlbmRlPXBvbnRvZGVyZWZlcmVuY2lhLmNvbS5icgBhdGVuZGU9cG9udG9kZXJlZmVyZW5jaWEuY29tLmJyAGF0ZW5kZSQkMTA=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/  !! Expected response code 250/251/252 but got code "554", with message "554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/ " (code: 554) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtpz.f1.k8.com.br ESMTP Postfix  >> EHLO info.pontodereferencia.com.br  << 250-smtpz.f1.k8.com.br 250-PIPELINING 250-SIZE 33554432 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH PLAIN YXRlbmRlPXBvbnRvZGVyZWZlcmVuY2lhLmNvbS5icgBhdGVuZGU9cG9udG9kZXJlZmVyZW5jaWEuY29tLmJyAGF0ZW5kZSQkMTA=  << 235 2.7.0 Authentication successful  ++ Swift_Transport_EsmtpTransport started >> MAIL FROM:  >> RCPT TO:  >> DATA  << 250 2.1.0 Ok  << 554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/  !! Expected response code 250/251/252 but got code "554", with message "554 5.7.1 : Recipient address rejected: policy rejection: mark@srvapor.eco.br: recipient is known to bounce; see https://www.hostnet.com.br/info/recipient-is-known-to-bounce/ " (code: 554) << 554 5.5.1 Error: no valid recipients  !! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients " (code: 554) (code: 554) >> MAIL FROM:  >> RCPT TO:  >> DATA  << 503 5.5.1 Error: nested MAIL command  !! Expected response code 250 but got code "503", with message "503 5.5.1 Error: nested MAIL command " (code: 503) (code: 503) (uncaught exception) at /home/pontodereferenci/info/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/LoggerPlugin.php line 124 while running console command `mautic:emails:send` [] []
</p>
<p>[2021-06-17 11:00:43] mautic.WARNING: Command `mautic:emails:send` exited with status code 255 [] []
</p>
<p>[2021-06-17 14:02:17] mautic.ERROR: Invalid clickthrough value: Yjo4OntmOjk6ImZiaGVkZiI7Yjo1Ont2OjM7Zjo4OiJmemJ2eSI7djo0O3Y6NjU2O31mOjg6ImZ6YnZ5Ijt2OjY1NjtmOjc6ImZnYmciO2Y6NTU6IjkzZGI4YWYxZjM5NDA2MDUyNzIyMTYiO2Y6NzoieWZiZSI7Zjo4OiI0NzYwNiI7ZjowOiJkdWJhYWZ5IjtiOjQ6e2Y6ODoiZnpidnkiO3Y6NjU2O319 {"exception":"[object] (Mautic\\CoreBundle\\Exception\\InvalidDecodedStringException(code: 0): The string b:8:{f:9:\"fbhedf\";b:5:{v:3;f:8:\"fzbvy\";v:4;v:656;}f:8:\"fzbvy\";v:656;f:7:\"fgbg\";f:55:\"93db8af1f3940605272216\";f:7:\"yfbe\";f:8:\"47606\";f:0:\"dubaafy\";b:4:{f:8:\"fzbvy\";v:656;}} is not a serialized array at /home/pontodereferenci/info/app/bundles/CoreBundle/Helper/ClickthroughHelper.php:46)"} []
</p>

**Comment by RCheesley** [comment] 2021-07-06 16:29
Closing as a duplicate of existing issue #9400

**Closed as completed by RCheesley** 2021-07-06 16:29 UTC
