### ISSUE TITLE
Hook before sending Email in segment

### ISSUE THREAD

**Issue by dseegers** [mautic/mautic#7950] opened 2019-10-14 09:32 UTC
What type of report is this:

| Q  | A
| ---| ---
| Question? | x

## Description:
I am writing a plug-in for Mautic that automatically adds an dynamic attachment to an email that is in a Segment. 

## The Issue
The issue that I am facing now that the event is called 2 times. So it will add 2 images to the first e-mail, and 2x2 to the second one. Before it is sent to the user. 
When I do an `error_log` I can confirm that the event is called 2 times for each email. 

## Some code

```    
public static function getSubscribedEvents()
    {
        return [
            EmailEvents::EMAIL_ON_SEND => ['onEmailSend', 100],
        ];
    }

    /**
     * Search and replace tokens with content
     *
     * @param EmailSendEvent $event
     */

    public function onEmailSend(EmailSendEvent $event)
    {
        $helper = $event->getHelper();

        $lead = $event->getLead();



        $helper->attachFile('https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Voorbeeld_nl.png/600px-Voorbeeld_nl.png');

        $event->setSubject('mail included attachment');
    }
```

As you can see, I am using the `EMAIL_ON_SEND` event. This is working fine when I am using an example mail. But with sending mails to multiple contacts (in a segment) it seems to add the same attachment multiple times. Is there some other event (/hook) I could use because I cannot find it in the documentation.

![image](https://user-images.githubusercontent.com/6848396/66741632-3ee11200-ee76-11e9-82c6-e8970b454a1e.png)

**Comment by RCheesley** [comment] 2019-11-05 20:42
Closing this as it's a duplicate of a forum thread here: https://forum.mautic.org/t/attachment-is-added-multiple-times-to-email-using-email-on-send-event-hook/11376 which is the correct place to ask for advice.

**Closed by RCheesley** 2019-11-05 20:42 UTC
