### ISSUE TITLE
Editing a contact throws an error due to column 'fax' being unknown

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8493] opened 2020-03-01 09:58 UTC
## Bug Description
While editing and saving a contact to check the fields all worked, at some point I had an error thrown with the stack trace below. It seems due to a missing column? Although it did enable me to save initially with content in the Fax field, which seems a bit strange. Also note #8485 which had a similar problem with the companyfax field.

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Edit existing contact (I think this would happen with a new one as well)
2. Save several times, ensuring there's something in the fax field
 
### Log errors
 ```
[2020-03-01 09:52:19] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'UPDATE 3_x_leads SET fax = ?, preferred_locale = ?, attribution_date = ?, website = ?, facebook = ?, foursquare = ?, instagram = ?, linkedin = ?, skype = ?, twitter = ? WHERE id = ?' with params ["9", null, "2020-03-01", "http:\/\/21", "22", "23", "24", "25", "26", "27", "512"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fax' in 'field list'" at /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'UPDATE 3_x_leads SET fax = ?, preferred_locale = ?, attribution_date = ?, website = ?, facebook = ?, foursquare = ?, instagram = ?, linkedin = ?, skype = ?, twitter = ? WHERE id = ?' with params [\"9\", null, \"2020-03-01\", \"http:\\/\\/21\", \"22\", \"23\", \"24\", \"25\", \"26\", \"27\", \"512\"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fax' in 'field list' at /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fax' in 'field list' at /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fax' in 'field list' at /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)
[stacktrace]
#0 /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(146): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')
#2 /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1069): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE 3_x_lead...', Array)
#3 /var/app/current/code/pulls/3.x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(743): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE 3_x_lead...', Array, Array)
#4 /var/app/current/code/pulls/3.x/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php(267): Doctrine\\DBAL\\Connection->update('3_x_leads', Array, Array)
#5 /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Model/FormModel.php(111): Mautic\\LeadBundle\\Entity\\LeadRepository->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Lead))
#6 /var/app/current/code/pulls/3.x/app/bundles/LeadBundle/Model/LeadModel.php(533): Mautic\\CoreBundle\\Model\\FormModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Lead), true)
#7 /var/app/current/code/pulls/3.x/app/bundles/LeadBundle/Controller/LeadController.php(645): Mautic\\LeadBundle\\Model\\LeadModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Lead), true)
#8 /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Controller/CommonController.php(449): Mautic\\LeadBundle\\Controller\\LeadController->editAction('512', '')
#9 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', '512', 0, '')
#10 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#11 /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/app/current/code/pulls/3.x/app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/app/current/code/pulls/3.x/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/app/current/code/pulls/3.x/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/app/current/code/pulls/3.x/app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/app/current/code/pulls/3.x/app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/app/current/code/pulls/3.x/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/app/current/code/pulls/3.x/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/app/current/code/pulls/3.x/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#20 /var/app/current/code/pulls/3.x/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#21 /var/app/current/code/pulls/3.x/index.php(6): require_once('/var/app/curren...')
#22 {main}
"} 
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-03-01 09:59
![](https://github.trello.services/images/mini-trello-icon.png) [Contact > Edit individual contact - ensure all default fields can be updated & saved](https://trello.com/c/aYpF5vhc/36-contact-edit-individual-contact-ensure-all-default-fields-can-be-updated-saved)

**Comment by alanhartless** [comment] 2020-03-06 16:02
Confirmed that this is caused by the duplicate custom fields from https://github.com/mautic/mautic/issues/8522. Will close this as Mautibox will be fixed when that issue is fixed. Same issue as https://github.com/mautic/mautic/issues/8485

**Closed by alanhartless** 2020-03-06 16:02 UTC
Labels: Bug, Mautic 3
