### ISSUE TITLE
Schedule shipment to a specific time

### ISSUE THREAD

**Issue by natansouza** [mautic/mautic#1401] opened 2016-02-03 12:29 UTC
It would be great if we could schedule the submission for a specific time determines without a date. Thus sending not have a specific date to happen and would be held every day.

**Comment by escopecz** [comment] 2016-02-05 13:17
I'm not entirely sure from your description what are you talking about. Campaigns? The "Send email" action?

**Comment by npracht** [comment] 2016-02-11 08:06
I think it's a duplicate of https://github.com/mautic/mautic/issues/539

**Comment by ps92** [comment] 2016-02-16 06:41
If I am assuming correctly, you might be talking about scheduling emails everyday.or update and trigger email actions. 
if yes, then you can easily do that by setting up CRON jobs on your servers.

**Comment by escopecz** [comment] 2016-05-02 13:03
Closing for unclear description. Can be opened any time the questions will be answered.

**Closed by escopecz** 2016-05-02 13:03 UTC
Labels: Pending Feedback
