### ISSUE TITLE
Mautic opening a very large amount of connections to database

### ISSUE THREAD

**Issue by chizuoka** [mautic/mautic#8287] opened 2020-01-03 03:33 UTC
Mautic seems to open so many connections to the database yet leaves most of them sleeping. Its causing the database to run out of connections. I have noticed for one with a low number of traffic is using up over 300 connections which then kills the server. I have tried 500 connections now and monitoring.. but 300 seems quite a bit. Is there a way to limit it or is there an issue with my installation.

**Comment by npracht** [comment] 2020-01-06 17:06
Hi @chizuoka.
I am not able to reproduce with the given information. I'm running several instances and it is not using such amount of threads. You may have a configuration issue ?
Could you please explain the version and infrastructure/configuration you use and how to reproduce it ?

**Comment by RCheesley** [comment] 2020-07-29 10:25
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-29 10:25 UTC
Labels: pending-feedback
