### ISSUE TITLE
Removing all variations from a dynamic content slot makes the email uneditable

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3135] opened 2016-12-23 11:25 UTC
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

Removing all variations from a dynamic content slot makes the email uneditable

![image](https://cloud.githubusercontent.com/assets/18265735/21452672/cf4e4d62-c908-11e6-8182-3ca0bf7cd22a.png)

| Q   | A
| --- | ---
| Mautic version | `2.4.0`
| PHP version | `7.0.14`

### Steps to reproduce:

1. Create a new email
2. Remove all variations from the automatically created _Dynamic Content 1_
3. Save & Close
4. Try to open the email again
 
### Log errors: 

```
[2016-12-23 10:27:49] mautic.NOTICE: PHP Notice: Undefined offset: 0 - in file path-to-mautic/app/bundles/EmailBundle/Views/Email/form.html.php - at line 16 [] []
[2016-12-23 10:27:49] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in path-to-mautic/app/bundles/EmailBundle/Views/Email/form.html.php on line 215" at path-to-mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php line 162 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Symfony\\Bundle\\FrameworkBundle\\Templating\\Helper\\FormHelper::widget() must be an instance of Symfony\\Component\\Form\\FormView, null given, called in path-to-mautic/app/bundles/EmailBundle/Views/Email/form.html.php on line 215 at path-to-mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php:162)"} []
[2016-12-23 10:27:49] mautic.ERROR: Notice: Trying to get property of non-object - in file path-to-mautic/app/bundles/EmailBundle/Views/Email/form.html.php - at line 16 [] []
```

**Comment by escopecz** [comment] 2016-12-29 09:42
This issue was fixed in 2.3.0: https://github.com/mautic/mautic/pull/2813

I cannot replicate it in 2.4.0. Are you sure this happens in 2.4.0? Is there some step missing in the steps to reproduce?

**Comment by MaxWebmecanik** [comment] 2016-12-29 13:18
@escopecz Here's a screencast

![dec](https://cloud.githubusercontent.com/assets/18265735/21544697/9f1d5458-cdd1-11e6-9973-f686c8524ccc.gif)

**Comment by escopecz** [comment] 2016-12-29 13:26
Aha, ok. I was deleting the whole DC, not the variation. I can reproduce this issue.

**Comment by MaxWebmecanik** [comment] 2016-12-30 08:20
Great! I need to make these gifs more often :smile:

**Comment by fernandolcardoso** [comment] 2017-02-16 10:17
Hello friends! I wonder if there is any solution or some suggestion so I can solve this problem. I'm having a stopped campaign because I can not edit the email. Any help is welcome!

**Comment by escopecz** [comment] 2017-06-23 07:45
Fixed in https://github.com/mautic/mautic/pull/4271

**Closed by escopecz** 2017-06-23 07:45 UTC
Labels: Bug
