### ISSUE TITLE
Can't change interface language

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#1492] opened 2016-03-01 22:09 UTC
## Description

Still in v. 1.3.0: When trying to load a different interface language, error message is: "mautic.core.could.not.set.language"

In this forum message the cause and solution is posted:
https://www.mautic.org/community/index.php/587-problem-setting-language/p1#p7927

## Steps to reproduce
Try to change interface language to e.g. German.

**Comment by escopecz** [comment] 2016-03-02 10:45
Seems like duplicate of https://github.com/mautic/mautic/issues/1260

**Closed by escopecz** 2016-03-02 10:45 UTC
