### ISSUE TITLE
The UTM tags are not URL encoded

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#8878] opened 2020-06-05 10:28 UTC
## Bug Description
When you use special characters in UTM tags, like "hírlevél", than these chars are not URL encoded, this causing 404 errors when arriving to mautic
Search for similar report among other reported issues.

### Steps to reproduce
create utm tag: hírlevél
send email, try the link, not working

**Comment by RCheesley** [comment] 2020-07-01 11:30
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment] 2020-07-29 11:34
Hi there, closing this as a duplicate of an existing issue: #8039

**Closed as completed by RCheesley** 2020-07-29 11:34 UTC
Labels: bug, pending-feedback, email
