### ISSUE TITLE
Add "import file type" form input 

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2587] opened 2016-09-23 13:37 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | X

## Description: Add a new input type "file".
It would be very great to have the ability to add a input type "file" in the forms.
Then, the visitor would be able to upload a file and this file would be integrated to the email notification action `send form results`.

You could configure the **weight limit** of the file.

### Why ?
For a HR form (resume, etc.) for instance or any other marketing needs.

**Comment by escopecz** [comment] 2016-09-30 08:32
Duplicate of https://github.com/mautic/mautic/issues/221

**Closed by escopecz** 2016-09-30 08:32 UTC
Labels: Duplicate
