### ISSUE TITLE
DataFixtures broken due to erroneous class metadata

### ISSUE THREAD

**Issue by k127** [mautic/mautic#3951] opened 2017-05-01 20:44 UTC
| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
When executing console command `doctrine:fixtures:load`, first, tables should be purged, see `Doctrine\Common\DataFixtures\Purger\ORMPurger::purge()`, line 143ff., but this seems broken.
Some debugging hints to the `return;` statement in file [ChannelBundle/Entity/MessageQueue.php](https://github.com/mautic/mautic/blob/2.8.0/app/bundles/ChannelBundle/Entity/MessageQueue.php#L130):

```php
    // @deprecated 2.4 to be removed in 3.0; BC support to ensure Doctrine doesn't populate metadata for Core and Channel bundle's entities
    if (get_called_class() == \Mautic\CoreBundle\Entity\MessageQueue::class) {
        return;
    }
```

This statement is probably the reason for the bug.
In the above mentioned `purge()` function, `getAllMetadata()` is collected, but the depicted _early exit_ erroneously causes the `$orderedTables` list to contain the table of concern twice:
* both `message_queue`, which is correct as defined in `$builder->setTable('message_queue')`,
* and the wrong `MessageQueue` which is reflected in the error messages below.

@alanhartless maybe there's a way to get this solved already in `2.8.1` :)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0 - app/prod
| PHP version | 7.0.18
| `doctrine/data-fixtures` version | v1.2.1

### Steps to reproduce:
1. `./app/console doctrine:fixtures:load`
 
### Log errors: 

From `[mautic root]/app/log/mautic_prod-….log`:

    mautic.NOTICE: Doctrine\DBAL\Exception\TableNotFoundException: 
    An exception occurred while executing 'DELETE FROM MessageQueue':  
    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'messagequeue' doesn't exist (uncaught exception) 
    at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 
    while running console command `doctrine:fixtures:load` [] []

Output of `./app/console doctrine:fixtures:load -vvv`:

```
Careful, database will be purged. Do you want to continue y/N ?y
  > purging database


  [Doctrine\DBAL\Exception\TableNotFoundException]
  An exception occurred while executing 'DELETE FROM MessageQueue':
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'messagequeue' doesn't exist


Exception trace:
 () at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
 Doctrine\DBAL\Connection->executeUpdate() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:137
 Doctrine\Common\DataFixtures\Purger\ORMPurger->purge() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:136
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->purge() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:85
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at n/a:n/a
 call_user_func() at vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:233
 Doctrine\ORM\EntityManager->transactional() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:90
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:118
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at app/console:41


  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'messagequeue' doesn't exist


Exception trace:
 () at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59
 Doctrine\DBAL\Driver\PDOConnection->exec() at vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:993
 Doctrine\DBAL\Connection->executeUpdate() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:137
 Doctrine\Common\DataFixtures\Purger\ORMPurger->purge() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:136
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->purge() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:85
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at n/a:n/a
 call_user_func() at vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:233
 Doctrine\ORM\EntityManager->transactional() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:90
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:118
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at app/console:41


  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'messagequeue' doesn't exist


Exception trace:
 () at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
 PDO->exec() at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
 Doctrine\DBAL\Driver\PDOConnection->exec() at vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:993
 Doctrine\DBAL\Connection->executeUpdate() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:137
 Doctrine\Common\DataFixtures\Purger\ORMPurger->purge() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:136
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->purge() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:85
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at n/a:n/a
 call_user_func() at vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:233
 Doctrine\ORM\EntityManager->transactional() at vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:90
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:118
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at app/console:41

doctrine:fixtures:load [--fixtures [FIXTURES]] [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [--multiple-transactions] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by k127** [comment] 2017-05-23 12:04
I had a solution, which is to add two lines…

```php
        // @deprecated 2.4 to be removed in 3.0; BC support to ensure Doctrine doesn't populate metadata for Core and Channel bundle's entities
        if (get_called_class() == \Mautic\CoreBundle\Entity\MessageQueue::class) {
            $builder = new ClassMetadataBuilder($metadata);
            $builder->setTable('message_queue');
            return;
        }
```

…to the place mentioned in the issue description. Then, the command `doctrine:fixtures:load` would work.

**But: it would also break `mautic:install:data`.** After having tried to understand the earyl exit return statement in question, it's actually seems to be in place in order to make sample data installation work.

To be honest, I did not notice that with `mautic:install:data` there's a Mautic specific way for `doctrine:fixtures:load`.

Not sure what would be the best solution or workaround, the command `doctrine:fixtures:load` maybe should be hidden (somehow like [Symfony docs of newer version](http://symfony.com/doc/current/console/hide_commands.html) suggest?).

**Comment by RCheesley** [comment] 2020-07-17 18:47
Unable to reproduce in Mautic 3.x so closing this issue!

**Closed by RCheesley** 2020-07-17 18:47 UTC
Labels: Bug
