### ISSUE TITLE
long lead name cause smtp failures

### ISSUE THREAD

**Issue by regevbr** [mautic/mautic#7732] opened 2019-07-29 10:30 UTC
## Bug Description

When a lead has a long name (e.g. `jon doeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`), trying to send him an email fails with the following smtp error (using SES mail transport)

The reason it happens is that mautic sets the `to` field with the contact name. e.g. `<my name> aaa@gmail.com`

Quick fix will be to discard the contact name part from the `to` header when it is too long

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7
| Browser | NA

### Steps to reproduce
1. Create a lead with a very long name
2. Send out an email to that lead
 
### Log errors

note: in the case below, the contact has hebrew characters.

[2019-07-27 18:55:48] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "554", with message "554 Transaction failed: Address length is more than 320 bytes long: '=?utf-8?Q?=D7=97=D7=99=D7=99=D7=9D_=D7=9E=D7=95=D7=A2?= =?utf-8?Q?=D7=9C=D7=9D_=D7=94=D7=A4=D7=95=D7=A1=D7=98=D7=99=D7=9D_=D7=95?= =?utf-8?Q?=D7=94=D7=A1=D7=A8=D7=98=D7=95=D7=A0=D7=99=D7=9D?= =?utf-8?Q?_=D7=94=D7=9B=D7=99_=D7=A7=D7=95=D7=A8=D7=A2=D7=99=D7=9D_?= =?utf-8?Q?=D7=91=D7=A8=D7=A9=D7=AA?= <aaaaaaa@gmail.com>'. " Log data: >> MAIL FROM:<unsubscribe+bounce_aaaaaaaaaaaaaaaaaaaaaaaaa@pruvo.net>  << 250 Ok  >> RCPT TO:<aaaaaaa@gmail.com>  << 250 Ok  >> DATA  << 354 End data with <CR><LF>.<CR><LF>  >>  .  << 554 Transaction failed: Address length is more than 320 bytes long: '=?utf-8?Q?=D7=97=D7=99=D7=99=D7=9D_=D7=9E=D7=95=D7=A2?= =?utf-8?Q?=D7=9C=D7=9D_=D7=94=D7=A4=D7=95=D7=A1=D7=98=D7=99=D7=9D_=D7=95?= =?utf-8?Q?=D7=94=D7=A1=D7=A8=D7=98=D7=95=D7=A0=D7=99=D7=9D?= =?utf-8?Q?_=D7=94=D7=9B=D7=99_=D7=A7=D7=95=D7=A8=D7=A2=D7=99=D7=9D_?= =?utf-8?Q?=D7=91=D7=A8=D7=A9=D7=AA?= <aaaaaaa@gmail.com>'.  !! Expected response code 250 but got code "554", with message "554 Transaction failed: Address length is more than 320 bytes long: '=?utf-8?Q?=D7=97=D7=99=D7=99=D7=9D_=D7=9E=D7=95=D7=A2?= =?utf-8?Q?=D7=9C=D7=9D_=D7=94=D7=A4=D7=95=D7=A1=D7=98=D7=99=D7=9D_=D7=95?= =?utf-8?Q?=D7=94=D7=A1=D7=A8=D7=98=D7=95=D7=A0=D7=99=D7=9D?= =?utf-8?Q?_=D7=94=D7=9B=D7=99_=D7=A7=D7=95=D7=A8=D7=A2=D7=99=D7=9D_?= =?utf-8?Q?=D7=91=D7=A8=D7=A9=D7=AA?= <aaaaaaa@gmail.com>'. " (code: 554) (send); aaaaaaa@gmail.com [] []

**Comment by AndrassGray** [comment] 2019-07-29 18:47
What does http://isemail.info/ say ? For reference : http://www.dominicsayers.com/isemail/

**Comment by regevbr** [comment] 2019-07-29 18:51
@AndrassGray the issue was not the actual mailing address but the long name e.g.
`<שלום מלכה מלכה אדאא דאדא דאדא> a@gmail.com` and this format can't be tested in the website you submitted

**Comment by mundadashri** [comment] 2019-08-07 17:21
I am also facing this issue with AWS SES set for email.

**Comment by ZenDevMaster** [comment] 2019-08-31 07:59
I'm also experiencing this; we are sending to a Thailand segment which has many Thai character lead names.

>  Expected response code 250 but got code \"554\", with message \"554 Transaction failed: Address length is more than 320 bytes long:

Looks like a UTF-8 encoding issue of some kind. We're on AWS SES.

**Comment by ZenDevMaster** [comment] 2019-09-04 06:58
Is there a way to (easily?) temporarily get around this; perhaps by modifying the to header? Trying to get a campaign going and 3,000 of my 6,000 contacts are failing because of this error.

**Comment by AndrassGray** [comment] 2019-09-04 07:06
You could try and hack the different setter functions for From:, To:, Cc: and Bcc: in app/bundles/EmailBundle/Helper/MailHelper.php to shorten the email address.

Or modify the addresses permanently with help of a clever SQL command directly in the database.

**Comment by ZenDevMaster** [comment] 2019-09-04 07:23
Ok, I think I got it -
Line 2048 in the cleanName() function of app/bundles/EmailBundle/Helper/MailHelper.php

`$name = mb_strcut($namee, 0, 319, "UTF-8");`

Still testing so unsure if this impacts anything else. But so far the emails are flowing...

Thanks for the tip @AndrassGray

**Comment by AndrassGray** [comment] 2019-09-04 07:34
YW!

Might be worth keeping an eye on it, though : Not sure what SES counts for the address-length : "name <@address>" or just the name part. Would certainly be good to monitor this. And maybe you could let us know as well.

**Comment by ZenDevMaster** [comment] 2019-09-04 07:51
The error logs shows this continually for the failed addresses
` << 554 Transaction[66/1763]Address length is more than 320 bytes long:`

So hoping that by limiting the string to 319 bytes we'll never hit the error whether the address is ASCII or UTF-8

**Comment by AndrassGray** [comment] 2019-09-04 07:58
Sure. but my questioning is what SES considers for the address length. You are shortening the name part only. What happens if you have a name of 310 characters that has an email address that is 11 characters long ? And does the To: within the smtp header count? And what about the angle-brackets '<>'?

`To: verylongname <some@where.to>`

**Comment by ZenDevMaster** [comment] 2019-09-04 08:04
Makes sense; we'll monitor this in the coming days. Thankfully Mautic seems to catch the error and leave the message pending for that address, so we should be able to iterate if needed.

**Comment by ZenDevMaster** [comment] 2019-09-10 08:05
Update on this, we've used the list twice now since implementing the change. I ended up having to change the code to the following, because at 319 bytes the To field was still failing at a very high rate: 

$name = mb_strcut($name, 0, 319, "UTF-8");

Unfortunately, I think this change had a serious impact on deliverability. The read rates on this list went from about 35% down to 9.5%, So I'm thinking that by not placing the recipient's name in the To field the emails are getting flagged as spam much more often.

Back to the drawing board on whether this is the right function to modify, but we do seem to generally be on the right track.

**Comment by RCheesley** [comment] 2020-07-16 18:00
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment] 2020-09-04 08:54
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 08:54 UTC
Labels: bug, integrations, pending-feedback, triage-mautic-3

**Comment by adirbnology** [comment] 2020-10-04 10:29
hi. having same issue on 3.1.0. @ZenDevMaster  any insights that u can offer maybe ?

**Comment by namratasaun** [comment] 2021-05-14 08:39
Facing similar issue in MAUTIC 3.2

**Comment by npracht** [comment] 2021-05-14 08:41
Can you try on latest mautic version (3.3.3)?

**Comment by namratasaun** [comment] 2021-05-14 08:43
> $name = mb_strcut($name, 0, 319, "UTF-8");

I did this @ZenDevMaster , but still getting errors

**Comment by namratasaun** [comment] 2021-05-14 08:52
> Can you try on latest mautic version (3.3.3)?

I don't have version 3.3.3 but leads with names like à¸à¸´à¹à¸à¸­à¸±à¹à¸¡ à¸à¸§à¸±à¸à¸­à¹à¸¥à¸¡à¹à¸² are getting the error. Is their anything I can change and try in this version only?

I tried $name = mb_strcut($name, 0, 319, "UTF-8"); but still getting the error

**Comment by ZenDevMaster** [comment] 2021-05-14 10:36
I never solved the issue the proper way :( The php code adjustment seemed to help in some cases but didn't get us to a perfectly working solution as it would still periodically fail a lead. 

Our list isn't huge, so in the end we hand-edited every failing lead name to remove the UTF characters. During testing I tried SendGrid which didn't have the problem.

**Comment by namratasaun** [comment] 2021-05-14 10:53
> I never solved the issue the proper way :( The php code adjustment seemed to help in some cases but didn't get us to a perfectly working solution as it would still periodically fail a lead.
> 
> Our list isn't huge, so in the end we hand-edited every failing lead name to remove the UTF characters. During testing I tried SendGrid which didn't have the problem.

Thanks for your reply.
The code that you wrote should do it, but idk why it keeps on giving errors and those errors are getting rescheduled and then fail again.
I think I can't handpick the names tho.
Thank you for your reply, will try to find some workaround.
One last thing, what UTF characters are you talking about, what i feel is it will fail on big names, the characters doesn't matter,  am I wrong here? @ZenDevMaster

**Comment by Semelovich** [comment] 2021-06-01 17:37
The issue is still present in the latest version of Mautic when using it with Amazon SES SMTP

**Comment by ShareBtech** [comment] 2021-11-11 13:32
I can confirm that this is present in 4.0.1.:

`Last execution error: Expected response code 250 but got code "554", with message "554 Transaction failed: Address length is more than 320 bytes long: '=?utf-8?Q?=D7=A8=D7=95=D7=99=D7=AA?= / =?utf-8?Q?=D7=9E=D7=9C=D7=95=D7=A0=D7=95=D7=AA_=D7=93?= =?utf-8?Q?=D7=9F_=D7=90=D7=92=D7=A3_=D7=9E=D7=A2=D7=A8=D7=9B=D7=95=D7=AA?= =?utf-8?Q?_=D7=9E=D7=99=D7=93=D7=A2_=D7=A7=D7=95=D7=9E=D7=AA_=D7=9B?= =?utf-8?Q?=D7=A0=D7=99=D7=A1=D7=94_=D7=A8=D7=95=D7=99=D7=AA_=D7=A7=D7=9C?= =?utf-8?Q?=D7=91=D7=A8=D7=A1?= '. "`

**Comment by patrykgruszka** [comment] 2025-02-10 10:39
The fix for this issue is ready to test https://github.com/mautic/mautic/pull/14577
