### ISSUE TITLE
 Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 2336462217216 bytes) 

### ISSUE THREAD

**Issue by ankit-verma** [mautic/mautic#2605] opened 2016-09-29 06:48 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-09-30 07:27
Please fill in all the information you can in the issue description. It's hard to help when we don't know what you did when this exception was triggered, what Mautic/PHP version do you have and so on.

**Comment by escopecz** [comment] 2017-02-03 20:03
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.

**Comment by corradofiore** [comment] 2017-08-01 16:11
Hi,

I'm not the original poster, but since this issue came up in Google, I'm going to fill in the blanks...

### Mautic version
`2.9.1`

### PHP Version
````
PHP 7.0.16 (cli) (built: Feb 14 2017 17:22:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16, Copyright (c) 1999-2017, by Zend Technologies
````
### How to reproduce the bug
It's relatively easy; I'm trying to import a CSV file with 3 columns (email, first name, last name) and 42700 rows.

````
/usr/bin/php  /home/******/htdocs/mautic/app/console  mautic:import
Import 19 with 42700 is rows starting.
 15005/42700 [=========>------------------]  35%PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/webmaster/htdocs/mautic-2.6.1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /home/webmaster/htdocs/mautic-2.6.1/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1
````

**Comment by escopecz** [comment] 2017-08-01 16:17
Could you check if you have some webhook configured?

**Comment by corradofiore** [comment] 2017-08-01 16:22
I don't think I have got any (if there's a command or page to verify this, please let me know).  In general, this is a kind of minimal, stand alone installation which doesn't tie into external services.

**Comment by corradofiore** [comment] 2017-08-01 16:29
Ah, it was right under my nose!  I confirm that there are no webhooks configured at all.

**Comment by maltonite** [comment] 2017-08-02 14:19
I can confirm I am also getting the same error when running `mautic:campaigns:trigger --batch-limit=500`. The error appears after a while (i.e. it can process a batch of 500, so I don't think it is the batch size which is throwing the error). I have also got the same error when downloading contacts from Salesforce.


```
Fatal` error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /mautic/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php on line 91
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 73728 bytes) in /mautic/vendor/composer/ClassLoader.php on line 444

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 73728 bytes) in /mautic/vendor/composer/ClassLoader.php on line 444
```

The php version is:
```
PHP 7.1.5-1+deb.sury.org~xenial+2 (cli) (built: May 22 2017 12:48:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5-1+deb.sury.org~xenial+2, Copyright (c) 1999-2017, by Zend Technologies
```
I don't have any webhooks configured (it is a fresh install of Mautic). 
I have the Salesforce and Mautic focus plugins installed. Thanks.

**Comment by escopecz** [comment] 2017-08-02 14:27
@maltonite does it happen with the default batch limit?

@corradofiore what is the batch for import? Did you modify it somehow?

**Comment by maltonite** [comment] 2017-08-02 14:29
@escopecz For the Salesforce issue, yes, it did happen with the default limits. It seems to be intermittent. I should have said that I am using a Ningx AWS server with 1GB of Ram.

**Comment by tecnomaster** [comment] 2017-08-15 21:06
Fellows, same problem here. I'm using PHP 7.0 and MySQL 5.6.35. Uploaded a csv file with 50K registers, configured the cron task and tested the console mautic:import through the cron and ssh direct execution. The import process behaviour is erratic, it means, some times it imports 400 registers and stop, other times it imports 500 registers and later 1650 registers, it has no sense.

I have increased memory_limit from 128M to 1024M with the same bad behaviour. 

Besides, the only way to run again the import process is to unpublish and publish again the file in the import history interface.

The cron for the import process is running each minute but doesn't process the csv file until the moment when I unpublish/publish it again. Once stopped it send the email saying:

Import 29 with 50315 is rows starting.
     0/50315 [>---------------------------]   0%
 20200/50315 [===========>----------------]  40%PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8208 bytes) in /home/tmatic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58


or

Import 29 with 50315 is rows starting.
     0/50315 [>---------------------------]   0%
 19300/50315 [==========>-----------------]  38%
 20124/50315 [===========>----------------]  39%PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8208 bytes) in /home/tmatic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58


or 


Import 29 with 50315 is rows starting.
     0/50315 [>---------------------------]   0%
 18800/50315 [==========>-----------------]  37%PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8208 bytes) in /home/tmatic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58


PLEASE HELP!!

**Comment by maltonite** [comment] 2017-08-15 21:52
Do you know what the total memory usage of your server is? Where I am using Mautic only has 1GB ram - running the top command, noticed that I was physically hitting a memory limit, so there was literally no memory available to allocate. I have also noticed that the memory usage increases as the script runs. To me this implies some form of memory caching issue; I should have a look, but I am thinking that the import file rows aren't being released from memory.

**Comment by tecnomaster** [comment] 2017-08-15 22:04
The server has 16GB RAM and I was reviewing the use with top and never goes beyond 2%.

**Comment by maltonite** [comment] 2017-08-15 22:09
This post might be of use to try and understand what is going on: https://stackoverflow.com/questions/21513825/php-fatal-error-allowed-memory-size-of-268435456-bytes-exhausted-on-normalizerf

**Comment by escopecz** [comment] 2017-08-16 06:50
It's directly in the error message: `134217728 bytes exhausted`

memory_limit in the php.ini configuration is only 134 MB. Mautic needs at least 250 MB. But if you can make it even more, do it. See https://github.com/mautic/mautic#mautic-requirements

**Comment by tecnomaster** [comment] 2017-08-16 12:14
What is rare is that, as we manage our own servers, I have increased memory_limit to 1024M for the local and the master php ini configuration. In fact, using the System Information option of mautic (which runs phpinfo function) it shows both values in 1024M, however, it reports 128M (134...) in the fatal error email.

We are using CPanel with multiphp functionalities. 

Just to let you know, it was not possible to use mautic with PHP 5.6 since each clic had too much delay to show the screens rendering, so, to solve this issue we use PHP 7.0.2 which let it works as expected.

I don't know if the cron tastks are using the main php in the server (5.6) instead of 7.0, however, I changed the memory limit in both and ran the console mautic:import with the same bad behaviur and the same report of memory exhausted value (134...) for both cases.
 
I'm investigating this more deeply to understand why it happens. If you have some clue please let me know.

**Comment by escopecz** [comment] 2017-08-16 12:22
PHP running on CLI can have different php.ini configuration. And also version. Try to run `php -i |grep php\.ini` to find out where is the ini for CLI. And run `php -v` to get CLI PHP version.

**Comment by tecnomaster** [comment] 2017-08-16 14:59
I have bad and good news:

Bad News:
We have verified that and in a cpanel environment, the cli uses the main system php version/handler setting, it means that even if you have a local php version used by apache for the web pages, cli doesn't use it but the global one. The bad news @escopecz is that even if you change the memory_limit for any of the cpanel configuration and if you force it in the php.ini location used by cli, the console mautic:import doesn't use it, keeping the failure with the memory limit.

Good News:
We have analyzed the code and solved it just inserting an iniset for memory_limit. The change we did was:
File: app/bundles/LeadBundle/Model/ImportModel.php
Method (function): Process
Line: 272
Just under:
        $batchSize = $config['batchlimit'];
Add:
        ini_set('memory_limit', '1024M');
Save it and you are done!.

Seen all this situation our recommendation is to change the code to assure the flusing process of the data once it has been inserted/updated in the database as suggested by @maltonite above, avoiding the memory exausting.

We were looking for a flush action in the code but we never found it.

Besides, what we didn't find is where is it recorded the batchlimit value. We were looking for it everywhere and saw that it comes from the session but, we uploaded the csv file some days ago and we can't find were that (100) batch limit value was written and how the current import running process is taking it. Please, could you tell us where is the batchlimit value saved?

**Comment by escopecz** [comment] 2017-08-16 15:06
If you follow the save methods, you'll end up where the [flush is called](https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Entity/CommonRepository.php#L766)

Look into `imports` table and `properties` column for the batch limit configuration for each import.

**Comment by nakab** [comment] 2017-08-20 22:04
Hi, 

I have the same problem, when I import a 40k lines file in background an error occurs. The installation is the minimum and I have no web hook configured and I did not make any changes to the code.

**Mautic version**

`2.9.2`

**PHP version**

```
PHP 5.6.31 (cli) (built: Aug 14 2017 17:37:23) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Memory Limit**

```
php -i | grep memory_limit
memory_limit => 512M => 512M
```

**Error**

```
php /var/www/app/console mautic:import
Import 9 with 40060 is rows starting.
 18217/40060 [============>---------------]  45%PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/app/bundles/LeadBundle/EventListener/LeadSubscriber.php on line 90
```

**Comment by escopecz** [comment] 2017-08-21 06:56
@nakab did you change the batch limit for import from 100 to something else? What if you make the batch for example 10? Will it avoid the memory limit issue?

**Comment by nakab** [comment] 2017-08-21 13:34
@escopecz I set the batch limit to 1000, I realize that every 1000 processed, the process will increase the memory until reaching the limit.

**Comment by escopecz** [comment] 2017-08-21 13:40
Can you please try to import with the default batch of 100? Does it work for you then?

@corradofiore, @ankit-verma can you please check how big batches you used for import when the error appeared?

**Comment by nakab** [comment] 2017-08-21 14:51
@escopecz I imported with the default value of 100 and the same error occurred

```
php /var/www/app/console mautic:import
Import 13 with 40060 is rows starting.
 18194/40060 [============>---------------]  45%PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/app/bundles/LeadBundle/EventListener/LeadSubscriber.php on line 90
```

**Comment by escopecz** [comment] 2017-08-21 15:26
@nakab can you tell me what do you have on that line 90?

It seems like you are importing either a lot of fields or some field with long values. I tested what the line `$check = base64_encode($lead->getId().serialize($details));` generates if I save a contact when changing most of the fields I have. It generates a string with 2196 characters/bytes. I'm sure this could be improved, but still. I'm curious what you are importing. What is on row 18194 of your CSV?

**Comment by nakab** [comment] 2017-08-21 15:32
@escopecz I'm importing an email list with two more columns of numbers

Line 90 of /var/www/app/bundles/LeadBundle/EventListener/LeadSubscriber.php
`if (!in_array($check, $preventLoop)) {`

Line 18194 of CSV
`j.renato.palladino@bol.com.br,9,9`

**Comment by escopecz** [comment] 2017-08-21 15:39
Could you try to replace the line with this content:
`$check = base64_encode($lead->getId().serialize($details));`
(it should be line 89 for you)
and replace it with this:
`$check = base64_encode($lead->getId().md5(json_encode($details)));`
It should reduce the `$preventLoop` array significantly and still keep its purpose. Let me know if it solved your issue. I'll send a pull request with this change then.

**Comment by nakab** [comment] 2017-08-21 16:10
@escopecz the problem still occurs, even after a suggested change.

```
php /var/www/app/console mautic:import
Import 14 with 40060 is rows starting.
 18408/40060 [============>---------------]  45%PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/app/bundles/LeadBundle/EventListener/LeadSubscriber.php on line 90
```

**Comment by tecnomaster** [comment] 2017-08-21 17:06
If you want to solve it, first assign through .htaccess or php.ini the memory_limit to 512 or 1024, then:

We have analyzed the code and solved it just inserting an iniset for memory_limit. The change we did was:
File: app/bundles/LeadBundle/Model/ImportModel.php
Method (function): Process
Line: 272
Just under:
$batchSize = $config['batchlimit'];
Add:
ini_set('memory_limit', '1024M');
Save it and you are done!.

**Comment by corradofiore** [comment] 2017-08-22 02:50
Hi @escopecz 

we always used the default batch value (100).

Cheers
Corrado

**Closed** 2017-11-28 11:03 UTC
Labels: Ready To Test
