### ISSUE TITLE
Using "contacts" as report data source gives incomplete data

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2257] opened 2016-08-12 14:08 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When creating a custom report and choosing "contacts" as the data source, the report does not contain all the eligible contacts. 

A small number of contacts are correctly included in the report. For the vast majority, empy lines are generated in the report. It looks like there is one empty line for each missing contact. 
Below is a screenshot. 

<img width="846" alt="capture d ecran 2016-08-12 a 15 59 07" src="https://cloud.githubusercontent.com/assets/7101583/17624768/55d64bb2-60a6-11e6-8ac4-4469b5d87980.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a custom report and choose "contacts as a data source"
2. Add some columns in the "data" tab
3. Save the report
4. View it. It should contain empty lines shortly past the begining.  
 
### Log errors: 

No related error logs.

**Comment by mqueme** [comment] 2016-08-16 09:38
This is due to anonymous contacts.

**Comment by pierreavizou** [comment] 2016-08-16 09:39
I'm not quite sure :/ 
I defintely have a whole lot of **non anonymous** contacts that are missing here in this report...

**Comment by mqueme** [comment] 2016-08-16 09:40
Can you please confirm that your empty rows are indeed anonymous contacts? this can be a feature request, to exclude anonymous contacts from reports

**Comment by mqueme** [comment] 2016-08-16 09:41
what I have done to confirm is to grab random ids of empty rows, and searched them in my contacts. for me they are all anonymous.

**Comment by pierreavizou** [comment] 2016-08-16 09:47
Ok yes maybe these are anonymous contacts, I have also randomly selected IDs to compare. However I cannot test them all. 

However, as stated in my initial post, reports using the "contacts" data source give incomplete data, I have a lot of missing identified contacts that should be in this report but are not.

**Comment by mqueme** [comment] 2016-08-16 09:52
Ok, I can't reproduce that, have you used any filters? To test I haven't used any filters, and I've added all the fields resulting on a report with all my contacts. Using Mautic 2.1.0 php 7.0.0

**Comment by pierreavizou** [comment] 2016-08-16 11:30
Sure, here are the screenshots. 
The field called "nombre de commandes" is a custom field, but the problem is the same when I create a report with only Mautic's default fields. 

![capture d ecran 2016-08-16 a 13 21 51](https://cloud.githubusercontent.com/assets/7101583/17697374/ca2a91d8-63b4-11e6-88f5-02668dff3fe8.png)

![capture d ecran 2016-08-16 a 13 22 03](https://cloud.githubusercontent.com/assets/7101583/17697380/d386161c-63b4-11e6-9930-0144e9fc81e3.png)

Maybe the problem is coming from the PHP version, you are using PHP 7, and I'm using PHP 5.6.23.

Please don't hesitate to ask me if I can provide you with more details.

**Comment by pierreavizou** [comment] 2016-08-16 11:31
Interestingly enough, the data is correct and complete when the data source is "contact point log". Hope this helps.

**Comment by mqueme** [comment] 2016-08-16 11:36
I am closing this issue, since I have not been able to replicate. Test do come up with all contact data.

**Closed by mqueme** 2016-08-16 11:36 UTC

**Comment by pierreavizou** [comment] 2016-08-16 11:37
You do not use the same PHP version as me, this could be the source of the issue...

**Comment by mqueme** [comment] 2016-08-16 11:41
pls check your dates as well. tnx.

**Comment by pierreavizou** [comment] 2016-08-16 11:42
Could you please be more specific regarding "checking dates" ?

**Comment by pierreavizou** [comment] 2016-08-16 11:44
Hummm yes that was the source of the problem. :)

**Comment by pierreavizou** [comment] 2016-08-16 11:44
Thank you :)
