### ISSUE TITLE
Bad email stops processing of list

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#1402] opened 2016-02-03 12:29 UTC
I started to send to my list, now 10 hours later in the error log every 12 minutes apart I have 3 of these
mautic.ERROR: [MAIL ERROR] Address in mailbox given [user@aol.com.] does not comply with RFC 2822, 3.6.2. [] [] 

If it is a non-compliant email, it should log it once, skip it and move on.

**Comment by escopecz** [comment] 2016-02-12 11:16
Are you sure it stops sending? What do you have to do to start it again? It should just log it and continue as you wrote. Do you use immediate send or the queue? What email transfer? What Mautic version?

**Comment by healthstatus** [comment] 2016-02-12 12:57
version 1.2.4, I have tried both SMTP and PHP mail, immediate send.  I have 10 hours of exactly the same message, and the ajax bar doesn't move and none of my test accounts ever receive the email, so I think it stopped, but their really is no way to tell in the system.

**Comment by escopecz** [comment] 2016-05-02 13:16
Duplicate of https://github.com/mautic/mautic/issues/1329

**Closed by escopecz** 2016-05-02 13:16 UTC
Labels: Pending Feedback
