### ISSUE TITLE
Dynamic Content in Email, not being handled in Contact Send Email

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#10926] opened 2022-03-02 15:55 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

Dynamic content email, that fills based on a contact field, custom field. When the email is used in a campaign it works fine, if I use the contact screen send email option, the dynamic content is not shown, only the: {dynamiccontent=“Dynamic Content 3”} where it should be is in the email.

### How can we reproduce this issue?

Step 1:  Create an email with dynamic content based on a custom contact field
Step 2: go to Contacts, select a contact (where you have access to the email)
Step 3:  Click send email, Import from an existing template dropdown select the dynamic email created in step 1

View: {dynamiccontent=“Dynamic Content 3”} is shown in the body

Step 4: Click Send

View received email: {dynamiccontent=“Dynamic Content 3”} is shown in the body instead of populating based on custom contact field as it should.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-03-04 18:22
I don't know if dynamic content is supported in the sending of individual emails from the contact - at least, I have never come across a use case for this as you are sending an email to a single person on a one-time basis. Could you maybe share why you would expect to use dynamic content in this setting?

@kuzmany do you know if this is supported?

**Comment by healthstatus** [comment] 2022-03-04 18:26
When a person signs up for our service they get an automated email with their access url, username and password information.   If they misplace it, delete it etc, and we need to resend it to them we use this method.  Our products are white labeled or cobranded in many instances and we are using dynamic content to add header images, or "signatures" from the companies we are sending out for.

**Comment by kuzmany** [comment] 2022-03-04 18:55
@RCheesley no it's not supported. The custom email is not related to email ID, then dynamic content cannot be provided.  That feature just import content. There are other solutions like push contact to campaign with send email...

**Comment by RCheesley** [comment] 2022-03-04 18:57
OK thanks for confirming @kuzmany - @healthstatus sorry this isn't something that is supported so it's not a bug with Mautic so I will close this issue as not something we would fix.

**Closed as completed by RCheesley** 2022-03-04 18:57 UTC
Labels: bug, dynamic-content, wont-fix
