### ISSUE TITLE
Deleting a contact in Suite / SugarCRM does not sync (delete) the contact in Mautic and vice versa.

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6142] opened 2018-05-30 12:22 UTC
What type of report is this: Bug report

Description:
Using the Sugar plugin with SuiteCRM (theoretically 100% compliant) Deleting a contact in Suite does not sync (delete) the contact in Mautic and vice versa.

Result:

      Action        | Action performed on |  Syncing | Expected | Sync direction
Delete contact |             Mautic            |      NO    |      Yes     | Mautic to Suite
Delete contact |              Suite              |      NO    |      Yes     | Suite to Mautic

If a bug:
Mautic version: 2.13.1
PHP version: 7.0.x
SuiteCRM version: 7.10.1 - Sugar Version 6.5.25 (Build 344)

Steps to reproduce:
TEST 1 - Direction Suite to Mautic (default)
1. Install Sugar plugin (and SuiteCRM) and establish a working link.
2. Delete a contact in Suite.
3. Run the sync command: php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

TEST 2 - Direction Mautic to Suite
1. Delete a contact in Mautic.
2. Run the sync command: php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

Log errors:
Mautic log is empty
No errors in Apache log.

**Comment by YosuCadilla** [comment] 2018-05-31 16:57
Just found out this will get fixed by #5610

**Comment by RCheesley** [comment] 2020-07-01 06:48
Closing as a duplicate of #6141

**Closed by RCheesley** 2020-07-01 06:48 UTC
Labels: Bug, Plugin
