### ISSUE TITLE
Change Owner on Contact Update Campaign Action

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4595] opened 2017-08-06 21:15 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y 
| Enhancement? |  Y

## Description:

When multiple users work with own leads on Inbound Stages (like one person to MQL and someone else to SQL) Mautic show all leads to everyone.

@kuzmany  @escopecz @alanhartless It's a great new feature to change Contact Owner on Campaigns actions like Contact Update or a new one to only Change Owner.

Thanks for Mautic!

**Comment by escopecz** [comment] 2017-08-07 07:15
Duplicate of https://github.com/mautic/mautic/issues/897

**Closed by escopecz** 2017-08-07 07:15 UTC
