### ISSUE TITLE
Exporting reports doesn't work

### ISSUE THREAD

**Issue by magdalenaleonow** [mautic/mautic#13518] opened 2024-03-04 14:24 UTC
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Exporting reports doesn't work - error when running the ddev exec bin/console mautic:reports:scheduler command.
Tested on Gitpod (v5.0.3)

### How can we reproduce this issue?

1: Create a report, add some data
2: In "Schedule" tab: choose email report: yes, add email and choose "now"
3: Save report
4: In the terminal run `ddev exec bin/console mautic:reports:scheduler`
5: Errors in the terminal, report not sent

### Relevant log output

```shell
13:49:56 ERROR     [mautic] Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: There is currently no session available. (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/RequestStack.php line 126 while running console command `mautic:reports:scheduler`
[stack trace]
#0 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(96): Symfony\Component\HttpFoundation\RequestStack->getSession()
#1 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(496): Mautic\ReportBundle\Model\ReportModel->getSession()
#2 /var/www/html/app/bundles/ReportBundle/Adapter/ReportDataAdapter.php(27): Mautic\ReportBundle\Model\ReportModel->getReportData(Object(Mautic\ReportBundle\Entity\Report), NULL, Array)
#3 /var/www/html/app/bundles/ReportBundle/Model/ReportExporter.php(70): Mautic\ReportBundle\Adapter\ReportDataAdapter->getReportData(Object(Mautic\ReportBundle\Entity\Report), Object(Mautic\ReportBundle\Model\ReportExportOptions))
#4 /var/www/html/app/bundles/ReportBundle/Model/ReportExporter.php(32): Mautic\ReportBundle\Model\ReportExporter->processReport(Object(Mautic\ReportBundle\Entity\Scheduler))
#5 /var/www/html/app/bundles/ReportBundle/Scheduler/Command/ExportSchedulerCommand.php(43): Mautic\ReportBundle\Model\ReportExporter->processExport(Object(Mautic\ReportBundle\Scheduler\Option\ExportOption))
#6 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} ["hostname" => "mautic-web","pid" => 4494]
13:49:56 CRITICAL  [console] Error thrown while running command "mautic:reports:scheduler". Message: "There is currently no session available." ["exception" => Symfony\Component\HttpFoundation\Exception\SessionNotFoundException^ { …},"command" => "mautic:reports:scheduler","message" => "There is currently no session available."] ["hostname" => "mautic-web","pid" => 4494]
13:49:56 WARNING   [mautic] Command `mautic:reports:scheduler` exited with status code 1 ["hostname" => "mautic-web","pid" => 4494]

In RequestStack.php line 126:
                                            
  There is currently no session available.  
                                            

mautic:reports:scheduler [-report|--report [REPORT]]

Failed to execute command bin/console mautic:reports:scheduler: exit status 1
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by obamwonyi** [comment] 2024-03-24 18:57
Hi , I tried to replicate the issue but it seems to work fine, has it been fixed ?
currently I get this feed back ```Scheduler has finished```, when I run the command ```ddev exec bin/console mautic:reports:scheduler```

**Comment by patrykgruszka** [comment] 2024-04-11 08:22
I can confirm that the issue exists on the 5.0 branch, but works fine on 5.x.

**Comment by RCheesley** [comment] 2024-04-29 16:21
OK I'm going to close this down then as it seems the issue is resolved already.

**Closed as completed by RCheesley** 2024-04-29 16:21 UTC
Labels: bug, needs-triage
