### ISSUE TITLE
Jump to Event Action Fails Silently When Asked to Repeat Action Steps

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#7730] opened 2019-07-27 03:03 UTC
## Bug Description
When the "Jump to Event" action step is used to send the user back to a previously executed condition or action it fails silently when directed to an action step, and errors out when directed to a condition step

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | N/A

### Steps to reproduce
1. Create a segment campaign
2. Add an action step, such add 1 point
3. Add an action step to jump to event and set it to wait 10 minutes. Direct it to jump back to the previous action step (add 1 point)
4. Publish the campaign against a segment with contacts in it
5. Monitor error log, and note that the "Jump to Step" is never executed

<img width="435" alt="Screen Shot 2019-07-26 at 9 27 58 PM" src="https://user-images.githubusercontent.com/866855/61989191-2db00400-aff1-11e9-89de-25618f2accb8.png">

Screenshot taken well after 9:42pm
<img width="298" alt="Screen Shot 2019-07-26 at 10 00 34 PM" src="https://user-images.githubusercontent.com/866855/61989193-356fa880-aff1-11e9-9370-d6e1e7078332.png">

 
### Log errors
This is the error produced when sent to a condition step:
`[2019-07-26 22:51:13] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'INSERT INTO campaign_lead_event_log (rotation, date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, campaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2019-07-26 22:51:13", 0, null, 1, "a:0:{}", null, null, 0, 674, 343361, 80, 41]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '674-343361-1' for key 'campaign_rotation' [] []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by pety-dc** [comment] 2019-10-25 15:42
I believe it is the same issue as 
https://github.com/mautic/mautic/issues/6613

**Comment by RCheesley** [comment] 2019-11-05 21:04
Closing as a duplicate of #6613

**Closed by RCheesley** 2019-11-05 21:04 UTC
