### ISSUE TITLE
Url shorten not working for sms

### ISSUE THREAD

**Issue by hiniesta** [mautic/mautic#2643] opened 2016-10-05 11:34 UTC
URL shorten not working for SMS. Think is a bug.
In file app/bundle/SmsBundle/EventListener/SmsSuscriber.php you have to change line 144 to:
$tokens[$token] = $this->trackableModel->generateTrackableUrl($trackable, $clickthrough,true);

**Comment by escopecz** [comment] 2016-10-05 12:09
Duplicate of https://github.com/mautic/mautic/issues/2575

**Closed by escopecz** 2016-10-05 12:09 UTC
