### ISSUE TITLE
Dynamic Content Inserted into Wordpress Loses Classes and Styles

### ISSUE THREAD

**Issue by incentfit** [mautic/mautic#8042] opened 2019-10-29 20:27 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm trying to make a wordpress page adjust it's content based on a field in Mautic.  So I setup 2 non-compaign dynamic content fields in Mautic.  I can get them to show up in Wordpress but the styling gets totally messed up.
The html that I put into dynamic content goes through 2 very weird transformations.
First, when I click save in Mautic, it adds `style="box-sizing: border-box;"` to every div, header, and paragraph element.  Even though I'm exclusively using the code view, I can't find any way to make it not alter my code.
Second, when I review the dynamic content on my Wordpress page, all my `class` attributes are totally stripped and instead they are placed in `fr-original-class` attributes.  Also, a bunch of additional styles are added in, from seamingly nowhere.
Am I just massively misunderstanding dynamic content or is there a pretty big bug here?

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.24
| Browser | Chrome 77

### Steps to reproduce
1.  In Mautic, create some dynamic content that is not template-based that has bootstrap HTML in it.  For example:
```
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				Testing
			</div>
		</div>
	</div>
</section>
```
2. In Wordpress, create a page with a dynamic content block.  For example:
```<div data-slot="dwc" data-param-slot-name="my-slot">Defafult</div>```
3. Load your Wordpress page and you'll see that all the class attributes are changed to fr-original-class and there's a bunch of random styling...
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by incentfit** [comment] 2019-10-29 22:08
I also looked into just having the dynamic content be a script tag with a `jquery.show()` command in there but Mautic strips out all javascript from dynamic content for some reason...

**Comment by RCheesley** [comment] 2020-02-04 18:10
I think this is a duplicate of #7272 so closing in favour of that issue, let's continue the discussion over there.

**Closed by RCheesley** 2020-02-04 18:10 UTC
Labels: Bug
