### ISSUE TITLE
Configurations panel not opening - Mautic 5.1

### ISSUE THREAD

**Issue by syreali** [mautic/mautic#13843] opened 2024-06-16 05:24 UTC
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

After installing Mautic 5.1 and logging in, when I click on the Configurations option, nothing happens. Configurations panel does not open. All other options like Categories, Custom fields, Themes, User management etc are working. Only when I click on Configurations, the configurations panel does not open and I cannot configure anything.

### How can we reproduce this issue?

Step 1: Clicking on the gear icon in the top right corner and then click the option Configurations. In my case, it does not open the configurations panel.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by J-Wick4** [comment] 2024-06-16 22:06
Upgrade to PHP 8.2, I don't have this problem.

**Comment by RCheesley** [comment] 2024-06-17 06:58
Hi there,

Please ensure you've cleared your cache, and where necessary regenerated assets using the command `bin/console m:a:g`

**Comment by syreali** [comment] 2024-06-18 04:37
I did change the PHP version to 8.2 but it didn't work.
Then I deleted the cache folder with the \var directory, and it worked.
@RCheesley Could you please guide about the second part of your response? "where necessary regenerated assets using the command bin/console m:a:g". How to do this? I am not a programmer, so if you could elaborate a little bit on this please.
@J-Wick4 & @RCheesley Thanks for your time and response. It helped.

**Comment by syreali** [comment] 2024-06-18 04:43
I don't know whether this is related to this or not, but now a new problem has surfaced.
I have successfully setup the Email configurations in the configurations section. Tested the configurations by clicking on the "Send test email" in the Email DSN section. The test was successful and the test email was received in the inbox.
PROBLEM:
I created an Email in the Channels>Email section and then after successfully saving the email, I clicked on the "Send Example", but it was never successful and returns error 500, as shown in the attached image.
![Screenshot 2024-06-18 094228](https://github.com/mautic/mautic/assets/91010316/6a7d5608-1c6d-4e19-9697-f9d2d82931f7)

**Comment by fernandoc83** [comment] 2024-06-18 14:16
> Hi there,
> 
> Please ensure you've cleared your cache, and where necessary regenerated assets using the command `bin/console m:a:g`

I solved the issue with this command and then clearing the cache, thanks

**Comment by syreali** [comment] 2024-06-19 05:56
When I execute the following command:
php bin/console m:a:g
The following error returns:
/home/xxxxxxx/mauto.edds.com.pk/node_modules does not exist. Execute `npm install` to generate it.

**Comment by fernandoc83** [comment] 2024-06-19 09:40
> When I execute the following command: php bin/console m:a:g The following error returns: /home/xxxxxxx/mauto.edds.com.pk/node_modules does not exist. Execute `npm install` to generate it.

You need to install nodejs to do that first

**Comment by RCheesley** [comment] 2024-06-20 19:26
Closing this issue as the original reported issue is not a bug. Please ask on https://forum.mautic.org for support, GitHub is only for reporting actual bugs with Mautic rather than issues with configuration etc. Thanks all!

**Closed as not planned by RCheesley** 2024-06-20 19:26 UTC
Labels: bug, needs-triage
