### ISSUE TITLE
Clone form gives error

### ISSUE THREAD

**Issue by gbela** [mautic/mautic#1320] opened 2016-01-05 23:57 UTC
I Clone an existing form,rename click Apply and I get the following error.

Uh oh! I think I broke it. If I do it again, please report me to the system administrator!

**Comment by 432jhfbs** [comment] 2016-01-06 11:23
I think this is a duplicate of:

https://github.com/mautic/mautic/pull/1278

**Comment by escopecz** [comment] 2016-01-06 12:08
It's not exactly a duplicate. This is a bug request and #1278 is fix, but yes, we can close this issue I think. Any tests of that PR are very welcome.

**Closed by escopecz** 2016-01-06 12:08 UTC
