### ISSUE TITLE
Broken Javascript in email Code Mode

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#9138] opened 2020-08-26 19:46 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1
| PHP version | 7.3.20
| Browser | Google Chrome latest

### Steps to reproduce
1. Create new segment email
2. Select code mode
3. Save the email with proper fields
4. Go to the Builder
5. Start editing the code
6. The app.js will broke
 
### Log errors
No PHP errors in the log.
Javascript errors in the console in the infinite loop:

20:40:36.846 ​ Uncaught TypeError: Cannot read property 'attr' of undefined
    at Object.Mautic.setCodeModeSlotContent (​)
    at ​
Mautic.setCodeModeSlotContent @ ​
(anonymous) @ ​
20:40:37.236 ​ Uncaught TypeError: Cannot read property 'attr' of undefined
    at Object.Mautic.setCodeModeSlotContent (​)
    at ​
Mautic.setCodeModeSlotContent @ ​
(anonymous) @ ​
20:40:38.843 ​ Uncaught TypeError: Cannot read property 'attr' of undefined
    at Object.Mautic.setCodeModeSlotContent (​)
    at ​
Mautic.setCodeModeSlotContent @ ​
(anonymous) @ ​
20:40:39.218 ​ Uncaught TypeError: Cannot read property 'attr' of undefined
    at Object.Mautic.setCodeModeSlotContent (​)
    at ​
Mautic.setCodeModeSlotContent @ ​
(anonymous) @ ​
20:40:40.840 ​ Uncaught TypeError: Cannot read property 'attr' of undefined
    at Object.Mautic.setCodeModeSlotContent (​)
    at ​
Mautic.setCodeModeSlotContent @ ​
(anonymous) @ ​
20:40:41.216 ​ Uncaught TypeError: Cannot read property 'attr' of undefined
    at Object.Mautic.setCodeModeSlotContent (​)
    at ​
Mautic.setCodeModeSlotContent @ ​
(anonymous) @ ​

## No errors before starting editing

![ScreenShot_20200826213234](https://user-images.githubusercontent.com/6353141/91348737-80578300-e7e4-11ea-8b48-8fa9ff558356.png)

## Errors started with mouse event (clicking and modifying code content) 

![ScreenShot_20200826213504](https://user-images.githubusercontent.com/6353141/91348763-8d747200-e7e4-11ea-8162-94d0ae9b7108.png)

## The app.js will remain in broken state after closing the email builder. 

![ScreenShot_20200826212819](https://user-images.githubusercontent.com/6353141/91348784-95ccad00-e7e4-11ea-9c4f-a2b42ba2dfe0.png)

The issue is possible related to the issue: https://github.com/mautic/mautic/issues/9128
But, I did not experience this issue on v.3.0.1 or v.3.0.2

This broken code mode editor issue is appeared in all of my supervised Mautic instances.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment] 2020-08-27 10:37
This is related to https://github.com/mautic/mautic/pull/8949
I'll take a  look

**Comment by trianity** [comment] 2020-08-27 11:13
@kuzmany Thank you.
I am using my production Mautic instances with the Code Mode email Builder in about 95% of cases, so this change made my life enough hard.
The test was made with the Mautic built in code mode sample email. And enough to click and change a character in the code area to start the issue.

**Comment by kuzmany** [comment] 2020-08-27 11:22
Try this https://github.com/mautic/mautic/pull/9143

**Comment by trianity** [comment] 2020-08-27 13:11
@kuzmany Thank you for the suggestion.
I changed the /app/bundles/CoreBundle/Assets/js/4.builder.js 
and changed the /media/js/app.js (compressed form of the file - line 167) and clear the application cache with the command 

[...]# php bin/console cache:clear --version
Mautic 3.1.0 - app/prod (kernel: app, env: prod, debug: false)
[...]# php bin/console cache:clear -v
 // Clearing the cache for the prod environment with debug false
 // Warming up cache...
 // Removing old cache directory...
 // Finished
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

And clear the browser cache and can confirm, that with all these actions **the suggested patch works**, and handled the issue.

**Comment by ghost** [comment] 2020-08-31 06:15
@trianity You mentioned the issue #9128 to be related. Actually we're running on v3.0.2 and checked the patch. It's not working for us

**Comment by StoppingBuck** [comment] 2020-09-07 09:28
@karo-me That seems to be a completely different issue from this

**Comment by mabumusa1** [comment] 2020-09-18 10:33
This bug is fixed by https://github.com/mautic/mautic/pull/9143, I reproduced the issue, applied the patch and the issue did not appear anymore

**Comment by StoppingBuck** [comment] 2020-09-19 06:58
@mabumusa1 Not to be pedantic, but shouldn't the PR be merged **before** closing the bug report? In theory, if the PR doesn't make it into 3.1.1 then this bug is still open.

**Comment by mabumusa1** [comment] 2020-09-19 07:16
@StoppingBuck that is correct, I marked the PR as ready to commit but did not merge it yet

**Comment by StoppingBuck** [comment] 2020-09-21 16:12
@mabumusa1 Now it can be closed :)

**Comment by mabumusa1** [comment] 2020-09-21 17:28
@StoppingBuck Sure it is

**Closed as completed by mabumusa1** 2020-09-21 17:28 UTC
Labels: T1, bug, regression
