### ISSUE TITLE
Trouble with Dollar sign in Email Password (settings)

### ISSUE THREAD

**Issue by seapal** [mautic/mautic#1301] opened 2015-12-30 18:38 UTC
I hade a email password with a Dollar Sign . When I tried to save the configuration I got no response. In the error log I got the message unknown variable ... 
But real issue was that this error caused mautic to write the local.php file without leading < (at the beginning). That was the reason mautic was not able anymore to read the configuration and even worse printed out the complete content of the file with all credentials. I was able to solve this by adding the "<", but had to change all passwords just to be safe.

**Comment by dongilbert** [comment] 2016-02-17 18:12
Testing on the latest staging branch, I am unable to duplicate.  I tested the following passwords containing dollar signs: `dollar$ign`, `$ign`, `dollar$` (middle, beginning, and end of string), and it successfully saved, updated the `local.php` config file, and continued functioning.

Could you provide an example similar to the password you were using when this occurred?

**Comment by seapal** [comment] 2016-03-07 16:53
Hi Don,

thanks for taking care. My password was like aBcd$qW - so maybe the error
was produced by somting else. Sorry, if my description was misleading.

2016-02-17 19:12 GMT+01:00 Don Gilbert <notifications@github.com>:

**Comment by arubacao** [comment] 2016-05-07 01:33
I can confirm this error.

As @dongilbert mentioned, i was able to save a password including a $ sign. Everything worked fine, even email sending.
But shortly after, Mautic stopped working. (maybe stuff was cached)
Replacing `"` with `'` in the `local.php` config file solved the problem.

I guess that the best fix for this would be to utilize a library like https://github.com/oscarotero/env

Cheers

**Comment by escopecz** [comment] 2016-08-02 09:33
Duplicate of https://github.com/mautic/mautic/issues/1047

**Closed by escopecz** 2016-08-02 09:33 UTC
Labels: Bug
