### ISSUE TITLE
Add the option to reset statistics from campaign, email and assets.

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#3225] opened 2017-01-11 15:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  X
| Enhancement? | 

## Description:
Add the Ability to reset the campaign, assets and e-mail stats. I always test my campaign and e-mails on multiple devices. It would be a welcome edition to Mautic to have the ability to reset the statistic after testing. This way it's easier to start with a baseline measurement when a campaign is official live.

Another option could be a test mode for the campaign, with this mode the campaign can be tested without effecting the statistics in the reports like suggested in #2307 .

**Comment by Paul979** [comment] 2017-02-04 14:39
I would also appreciate this option

**Comment by escopecz** [comment] 2017-02-16 11:28
This seems like a duplicate of https://github.com/mautic/mautic/issues/195

**Closed by escopecz** 2017-02-16 11:28 UTC

**Comment by PeterTL** [comment] 2018-01-23 20:40
@escopecz,

this is definitely not a duplicate of #195. Where #195 ist about resetting the Mautic instance after installation and initial testing, #3225 (this one) is about resetting campaign (and connected, e.g. email) statistics after a campaign was tested and before it is going live.

I would appreciate it if this issue could be re-opened that I could +1 it. This functionality is really useful, especially if you have smaller target groups where tests affect statistics.

**Comment by marqpdx** [comment] 2018-05-22 18:50
Definitely agree with this. I like to test campaigns a ton of different ways, and want to reset, re-launch (w/ my test segment), reset, re-launch... until it's perfect, than swap in my actual segments, then launch the campaign live. 

This is a super important feature from a quality control perspective.

Thanks, and let me know if there are ways around this already.
:-)

**Comment by putzwasser** [comment] 2022-01-15 17:53
+1
