### ISSUE TITLE
Import broken with Internal Server Error

### ISSUE THREAD

**Issue by stoneddesigner** [mautic/mautic#4937] opened 2017-09-17 20:29 UTC
What type of report is this:

 Bug report

## Description:

Import no longer works after importing with a blank required field, gave me a Internal Server Error. Checking the logs shows a Symfony component error.

## Steps to Reproduce:

1. I go to the Contacts screen
2. click the down arrow, click Import
3. Server loads import page fine. 
4. I pick a CSV file, and delete one of the required fields and leave it blank. 
5. Click import, and see the Internal Server Error. 
6. I close the web browser, navigate back to the contacts page, try to go to the import screen again, and nothing loads. I see the load bar move, but nothing happens. 

Checking the Console shows: 

> libraries.js?v9f0802db:673 GET http://mysite.com/s/contacts/import/new?_=1505678972629&mauticUserLastActive=1&mauticLastNotificationId= 500 (Internal Server Error)

If I check the Mautic logs:

> [2017-09-17 20:11:16] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "A form with an empty name cannot have a parent form." at /home/mautic/vendor/symfony/form/Form.php line 273 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): A form with an empty name cannot have a parent form. at /home/mautic/vendor/symfony/form/Form.php:273)"} []

I'm currently using PHP version 5.6.2. Not sure which version of Mautic I have, it's the staging release from a week ago. I might give the release branch a shot and see if it's just me using the wrong version.

**Comment by isleshocky77** [comment] 2017-10-14 16:11
The exception is being thrown from the following block of code

```php
// /bundles/LeadBundle/Controller/ImportController.php:206
                $form = $this->get('form.factory')->create(
                    'lead_field_import',
                    [],
                    [
                        'object'           => $object,
                        'action'           => $action,
                        'lead_fields'      => $leadFields,
                        'company_fields'   => $companyFields,
                        'import_fields'    => $importFields,
                        'line_count_limit' => $this->getLineCountLimit(),
                    ]
                );
```
It appears that all of the parameters being passed into the factory have correct values.

**Comment by isleshocky77** [comment] 2017-10-14 16:29
Wondering if it's related to #4930

**Comment by isleshocky77** [comment] 2017-10-14 17:13
I don't know if this is the issue for other people, but it turns out my file contained a header name which was made up of all non alphaNum characters and thus was stripped without a name.  Could other people confirm this is their issue as well?  Make sure the column headers have at least one number or name and is not blank.

I have a patch to fix my issue I'll submit later.

**Comment by rskonieczka** [comment] 2017-10-16 18:25
+1

**Comment by isleshocky77** [comment] 2017-10-16 20:25
I was working on a failing test case to go along with my fix, but I ended up running out of time. For now i just changed one of my column headers from "#" to "id" and I can import the file fine. 

I also believe the following patch probably would have solved it but I'm not going to put a PR on without there being some testing around it.

```patch
diff --git a/app/bundles/LeadBundle/Controller/ImportController.php b/app/bundles/LeadBundle/Controller/ImportController.php
index bcd32ef..d1975bd 100644
--- a/app/bundles/LeadBundle/Controller/ImportController.php
+++ b/app/bundles/LeadBundle/Controller/ImportController.php
@@ -315,8 +315,11 @@ class ImportController extends FormController
 
                                             $importFields = [];
 
-                                            foreach ($headers as $header) {
+                                            foreach ($headers as $columnNumber => $header) {
                                                 $fieldName                = strtolower(InputHelper::alphanum($header, false, '_'));
+                                                if (!strlen($fieldName)) {
+                                                    $fieldName = sprintf('column_%d', $columnNumber);
+                                                }
                                                 $importFields[$fieldName] = $header;
                                             }

```

I'd also say someone needs to go and fix the error handling. For there to be a 500 error and you need to logout and back in after giving it a bad format is a bad behavior.

**Comment by nicodeforge** [comment] 2017-11-09 15:09
Hi Guys,

Just had a similar issue : the problem was that some data in my csv were in a column with no header. I read `mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "A form with an empty name cannot have a parent form." at /var/www/html/vendor/symfony/form/Form.php line 273 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): A form with an empty name cannot have a parent form. at /var/www/html/vendor/symfony/form/Form.php:273)"}`

First it simply outputed a warning message saying the Import cound not run, then caused a 500 error and I was not able to use Mautic at all (create a single contact or anything). Had to log out and in again, correct my csv, run the import again and it's fine. 

Maybe a simple message stating that there is a missing header in the imported file would be sufficient; provided it doesn't cause 500 Errors afterwards.

**Comment by rteijeiro** [comment] 2017-11-17 17:57
Confirmed the issue when a column header is missing. Added the missing header and everything is fine. Had to logout and login again in order to make the Import page work again.

**Comment by goldpromotion** [comment] 2017-12-21 20:10
fwiw, the same thing happens when a user attempts to import file with the wrong encoding for .csv

**Comment by duchu** [comment] 2018-02-08 15:54
@goldpromotion so what is proper encoding ?

**Comment by RCheesley** [comment] 2018-02-19 18:14
Confirming the error.  Initially I thought it might be due to not all column headers being complete which results in being unable to access the import screen until logging out and logging back in again.  

I fixed what I thought was the problem (missing column headers) but am still getting the error, even with all columns having a header (e.g. A, B, C, D where they did not previously have a column header etc)

**Comment by robwent** [comment] 2018-02-22 12:02
I was getting 500 errors when people tried to upload some csv files (before getting to the column selection screen).

In my case I think it was because there were empty columns in the file.

After adding @isleshocky77 s patch https://github.com/mautic/mautic/issues/4937#issuecomment-337028318
I can now upload the same files without any errors.

In the field selection screen, the empty columns now show as 'column 0', 'column 1' etc.

So it fixes the file upload issues, but the numbering of the columns seems a bit odd.
I tested with a file that had 22 empty columns that a user had uploaded. All the empty columns were after the ones with the info, but the numbering still starts at 0 so they don't really relate to the actual column number in the file.

**Comment by isleshocky77** [comment] 2018-02-24 06:12
@robwent That's why I didn't submit it as a PR. I'm not happy enough with it to be in the codebase. I would say someone should look more into this. Probably best idea would be someone to put a PR in with a file which fails.

**Comment by escopecz** [comment] 2018-06-11 13:49
Importing a CSV with empty columns fixed in https://github.com/mautic/mautic/pull/6190. Ready to test.

**Closed** 2018-07-06 15:08 UTC
Labels: Bug, Pending Test Confirmation, Ready To Test
