### ISSUE TITLE
Boolean contact fields get overwritten through action update contact in campaign

### ISSUE THREAD

**Issue by MaraKasubke** [mautic/mautic#10669] opened 2021-12-07 12:19 UTC
### Mautic Version

4.1.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Firefox

### What happened?

When updating contact fields through a campaign the boolean fields get overwritten with the default setting. There ist just YES and NO, a third option (the little x) from before is missing. So if I change a contact field through a campaign through the action update contact all boolean fields show "NO".

![2021-12-07_13h11_40](https://user-images.githubusercontent.com/34441995/145026894-0ade5909-8ce5-49c0-81bc-b85703787318.png)

You can see here that multiple fields have been updated. But I only changed the field "Interessen". All the other fields that have been updated falsely are boolean fields.
![2021-12-07_13h15_11](https://user-images.githubusercontent.com/34441995/145027309-0eb70ef4-9ed7-4ffe-9429-276feead323e.png)

### How can we reproduce this issue?

Step 1: Have some boolean fields in your contact with option YES
Step 2: Create a campaign that updates a contact field which is NOT boolean - do not touch the boolean field in the action
Step 3: Run the campaign
Step 4: You can see that in your contact the boolean field is now set to NO

### Relevant log output

```shell
Produces no error log
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by patrykgruszka** [comment] 2021-12-20 17:18
Confirmed, the same problem is in the edit contact form. The boolean fields have no neutral values. 

@alanhartless could you take a look on this case? I've found that it's caused by PR #9931. The type casting in the `app/bundles/CoreBundle/Form/Type/YesNoButtonGroupType.php:57` makes the neutral option disappear and i can't figure out why. I don't think it's intended change.

**Comment by RCheesley** [comment] 2022-01-25 12:41
Resolved with #10716

**Closed as completed by RCheesley** 2022-01-25 12:41 UTC
Labels: T1, bug, regression, campaigns, companies, contacts, custom-fields
