### ISSUE TITLE
Form submition during update causes error

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4542] opened 2017-07-28 23:11 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
If someone fills out a mautic form during the update process (using the UI updater, didn't test the script) an error is shown to the user fulling out the form.

![screenshot from 2017-07-29 00-07-27](https://user-images.githubusercontent.com/2853040/28739352-3c761b10-73f2-11e7-86e5-879565bba3ae.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0 > 2.9.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-07-29 07:33
Please provide the error message from the logs: https://mautic.org/docs/en/tips/troubleshooting.html

And please, please, please, please, use the script to upgrade. We really have to get rid of the UI updater.

**Comment by gingerling** [comment] 2017-08-04 20:07
Hi, sorry, I don't have the error and I can't really test it again. It basically said "this isn't working" though. I really wouldn't get rid of the UI updater, I expect apps to have an update button in them, like wordpress does. It's really useful. I am assuming you mean a CLI script? I don't use CLI at all, I have help when I need it, but I use Webmin for most things.

**Comment by escopecz** [comment] 2017-08-07 07:29
So the problem is gone now?

**Comment by gingerling** [comment] 2017-08-07 11:51
Hi, yes, it's specifically during the update - so basically the forms are "down" for 5 mins while the updater works. Can you test this with the CLI script too? It's funny, I can see how maybe this is expected behaviour, but I don't think I have this issue with other, comparable software

**Comment by escopecz** [comment] 2017-08-07 12:06
It really depends on different variables like
- How big is your database
- How many database migrations are in the particular update
- What is your RAM or memory limit
- How powerful is processor on your server

My suggestion is:
- start the upgrade when you don't expect much traffic - after working hours
- monitor your server during the upgrade so you'd know if it's caused by server overload

I'll close this issue since I can't think of any solution to this problem. But if anyone has some idea, I'll gladly reopen.

Please let us know if the problem was weak server.

**Closed by escopecz** 2017-08-07 12:06 UTC
Labels: Pending Feedback

**Comment by gingerling** [comment] 2017-08-09 12:16
Hi, I doubt it, it's a very small databased, only about 3000 people in total. The upgrade was quick and painless.

**Comment by escopecz** [comment] 2017-08-09 12:38
It would help a lot if we'd know what the error message was: https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by gingerling** [comment] 2017-08-09 21:34
Ok, next time I update I will check this.
