### ISSUE TITLE
The grapesjs builder is not loading 5.x branch [$100 bounty]

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13510] opened 2024-03-01 12:30 UTC
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.2.4

### What happened?

The legacy builder loads by default on the 5.x branch instead of GrapesJS.

### How can we reproduce this issue?

Step 1: Open latest 5.x on gitpod: https://gitpod.io/new/#https://github.com/mautic/mautic/
Step 2: Go to email, select any type and open the builder. Result on screenshot:
![image](https://github.com/mautic/mautic/assets/8580942/58638801-16d4-415d-ac0d-1488a4e142a3)

### How to turn on the GrapesJS
Step 1: Open latest 5.x on gitpod: https://gitpod.io/new/#https://github.com/mautic/mautic/
Step 2: Enable GrapesJS in plugins
Step 3: Remove and rebuild the cache
```
rm -rf var/cache/*
ddev exec php bin/console c:c
```
Step 4: Go to email, select any type and open the builder the GrapesJS should be loaded

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by annamunk** [comment] 2024-03-01 14:37
@patrykgruszka I came across the same error. Additionally, manually enabling the GrapesJS plugin did not solve this and the plugin, even though it is enabled, is not highlighted in the plugin list.
![grey](https://github.com/mautic/mautic/assets/102536220/352d24f9-3d2c-4dfb-9772-68ceeb0ec698)

**Comment by escopecz** [comment] 2024-03-08 16:24
And doing what the error message says is not helping? 
![Screenshot 2024-03-08 at 17 24 18](https://github.com/mautic/mautic/assets/1235442/ac36308e-a407-4072-968d-e56486bfa382)

**Comment by patrykgruszka** [comment] 2024-03-11 10:42
Enabling the Froala assets helps to run the legacy builder. I did some more tests and it is possible to enable the GrapesJS, but I had to remove the cache with `rm -rf var/cache*` and then run the `ddev exec php bin/console c:c`. I've updated this in the issue description.

The issue is that the legacy builder is set as the default on the 5.x branch, rather than GrapesJS.

**Comment by RCheesley** [comment] 2024-03-12 09:34
This is a bug/regression, as GrapesJS should be the default editor.

**Comment by escopecz** [comment] 2024-03-25 08:35
I was adding the `isMauticAdministrationPage` method recently as it was loading the assets everywhere like landing ages, 404 pages and so on. So perhaps I broke it?

https://github.com/mautic/mautic/pull/11442/files#diff-b3d7a031523b9c22ffd8727b2fbb1c44d0c6e240bbc09b279b487a3f69a2a45eR45

**Comment by obamwonyi** [comment] 2024-03-25 11:46
### My approach to fixing this problem so far
Take a look at the themes page below
![suspected_cause](https://github.com/mautic/mautic/assets/96271272/ae44df34-58eb-4ad4-890b-3ff5a4cacdcd)
Notice that each theme has their default features, This should mean that some themes (prolly the default theme too) , does not have the grapejsbuilder added by default.
#### Attempt to fix 
I tried to install a theme with the grapejsbuilder feature to see if it will add the grapejsbuilder by default without explicitly enabling it in plugins, but when I download the file and try to install as shown below.
![image](https://github.com/mautic/mautic/assets/96271272/c7be9bc6-0685-4a31-90e1-d60b71f14503)
I get the error below 
```blank (or confirmme or aurora) is the default theme and therefore cannot be overwritten.``` , this happened for all the themes I have tried so far.

Any help on how to install the themes, as the approach above is what is given in the [docs](https://docs.mautic.org/en/5.x/themes/manage_themes.html#manage-themes)

**Comment by obamwonyi** [comment] 2024-03-25 11:57
And also I need to know the theme activated by default.

**Comment by andersonjeccel** [comment] 2024-03-25 14:17
Hm, it's working fine here (both dev on 5.x and prod on 5.0.3)

The only time I had this issue was when something gone wrong while running composer or npm...
Perhaps I'm missing external context about all this

**Comment by obamwonyi** [comment] 2024-03-25 14:22
> Hm, it's working fine here (both dev on 5.x and prod on 5.0.3)
> 
> The only time I had this issue was when something gone wrong while running composer or npm... Perhaps I'm missing external context about all this

like I am running it locally, and not on gitpod. and the themes are not installing.

**Comment by obamwonyi** [comment] 2024-03-25 14:23
And also what theme do you get be default . And do you also have any idea where the default plugins like that of focus are set ?

**Comment by fama** [comment] 2024-03-26 15:57
Same problem here.  I am running 5.0.3 using [docker basic](https://github.com/mautic/docker-mautic/tree/mautic5/examples/basic).

Everything seemed to work, until my marketing reported to me that they cannot upload images in the Builder of the email:

![image](https://github.com/mautic/mautic/assets/720793/5defe072-8d1b-479d-9b7d-c217250b4b85)

I checked the folder to make sure that everything is pointing to correct folders and also double checked the permissions.

This was a show stopper and had to roll back to v4.

**Comment by obamwonyi** [comment] 2024-03-27 08:38
> Same problem here. I am running 5.0.3 using [docker basic](https://github.com/mautic/docker-mautic/tree/mautic5/examples/basic).
> 
> Everything seemed to work, until my marketing reported to me that they cannot upload images in the Builder of the email:
> 
> ![image](https://private-user-images.githubusercontent.com/720793/316941224-5defe072-8d1b-479d-9b7d-c217250b4b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1Mjg3NjUsIm5iZiI6MTcxMTUyODQ2NSwicGF0aCI6Ii83MjA3OTMvMzE2OTQxMjI0LTVkZWZlMDcyLThkMWItNDc5ZC05YjdkLWMyMTcyNTBiNGI4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwODM0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODE1MTI1YmIwNzAxYTNjZTI0NTMxMzVkMWVjZjFjN2VmMmQ2YmYzMmZkOTg1ZTlkNTMyNWU4MjJiYmM2MTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._t9oOiyF5OOd8gnUx4hPAk4rle271WHMpHaWEw8kOcE)
> 
> I checked the folder to make sure that everything is pointing to correct folders and also double checked the permissions.
> 
> This was a show stopper and had to roll back to v4.

Hi @fama, is your grapejs builder enabled by default ?, the main problem for this issue is that the grapejsbuilder is not enabled by default, I have looked at the default theme (blank) and it is set as the builder. However, it is preceded by the legacybuilder, which I removed just to try out a fix , but it still did not work.

**Comment by escopecz** [comment] 2024-04-05 07:34
There is this Slack thread also about this topic:

https://mautic.slack.com/archives/C01EGF5U422/p1711533925889869

Quoting a comment that should solve this issue in case someone is free to test it out and push a PR:

> Perhaps the fix will be as simple as adding the tag to the fixture service as other service above it
https://github.com/mautic/mautic/blob/5.x/app/bundles/InstallBundle/Config/config.php#L50

**Comment by vibhuti019** [comment] 2024-04-05 18:50
Hi, Can I take up this issue if no one is working on it ?

**Comment by escopecz** [comment] 2024-04-08 08:57
@vibhuti019  Please do

**Comment by RCheesley** [comment] 2024-04-09 14:24
Hi folks! Looks like we have a proposed fix in #13619 - please review that PR and leave the outcomes so we can get it merged!

Here's the docs on how to test (which can all be done in the browser with Gitpod, if you like): https://mau.tc/tester.

Thanks in advance!

**Comment by patrykgruszka** [comment] 2024-04-09 14:38
@RCheesley I think this is just a mention of this issue in the test instructions and info about the workaround.

**Comment by RCheesley** [comment] 2024-04-11 14:06
Doh, sorry I mis-read!

**Comment by escopecz** [comment] 2024-04-19 08:05
OK, folks. I was waiting 2 weeks after I did the investigation and [suggested the solution](https://github.com/mautic/mautic/issues/13510#issuecomment-2039148508). I have pushed the fix now as we want to release 5.1.0 next week. Apologies to everyone who was about to push the same fix.

https://github.com/mautic/mautic/pull/13672

Please give it a review and test so it can be merged soon.

**Closed as completed** 2024-04-19 12:09 UTC
Labels: T1, bug, ready-to-test, plugin, regression, landing-pages, email, bounty, builder-grapesjs
