### ISSUE TITLE
Skyline theme: Blank space between one and two/three column sections in emails

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3910] opened 2017-04-25 16:54 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | N

## Description:
When using the builder, adding a two column section creates a blank space which can't be modified. It seems to be caused by the builder creating a separate frame (highlighted in orange). The space persists in the preview window and into the sent message.

![screenshot from 2017-04-25 17-45-15](https://cloud.githubusercontent.com/assets/2853040/25397329/d112fac0-29df-11e7-8792-40fc2bce1126.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create email from skyline template
2. Drag "two column" section into mail in builder
3. see that there is space (send test etc)

I tested on Sunday and goldstar and they did not have the same issues.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment] 2020-04-01 23:18
Closing as this is not a bug, but a feature of the email template design to ensure spacing between elements. 

If you wish to remove the extra table row, you can edit the theme by downloading it, making your changes, and uploading it as a new theme. See https://developer.mautic.org/#themes for more guidance on working with themes.

**Closed by RCheesley** 2020-04-01 23:18 UTC
Labels: Bug
