### ISSUE TITLE
eMail bloked because of IP reputation are marked as do not contact as "Unknow user"

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#9222] opened 2020-09-20 21:20 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

I have changed my SMPT provider from AWS SES to Elastic Email.

Microsoft is rejecting emails because of sender IP is blocked as spammer. The email received in bounce email account has thsi content: 

550 Mailbox unavailable. The server response was: 550 5.7.1 Unfortunately, messages from [51.38.210.174] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3150).

and Mautic is marking email as do not contact because of "Unknow user or server"

I attach an image of a contact who has read a recent email and is marked as do not contact. 

   
| Q   | A
| --- | ---
| Mautic version | 2.16.3 
| PHP version |  7.2.29
| Browser | Any

### Steps to reproduce
1. Configure SMTP sender
2. Configure a bouncing email address
3. Send email from blocked email by microsoft (I don't know how to do this for test propouses)
4. Receive bounce notification in boucing email from no-reply@bounces.elasticemail.net
5. Mautic proccess the email and mark the contact as do not contact because of "Unknown user or server"

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

![image](https://user-images.githubusercontent.com/39302320/93722550-ea6f0800-fb97-11ea-9386-1df8159bfa72.png)

**Comment by RCheesley** [comment] 2020-09-21 20:19
Hi there,

It sounds like this is an issue you need to take up with your email service provider based on:

> Microsoft is rejecting emails because of sender IP is blocked as spammer.

This is not an issue with Mautic as it is correctly being flagged as a bounce, so I am going to close this down. 

Please raise a support request with your email provider, and if you still require assistance please post at https://forum.mautic.org/c/support.

**Closed as completed by RCheesley** 2020-09-21 20:19 UTC
Labels: needs-triage

**Comment by Carlos-mb** [comment] 2020-09-21 20:37
WTF?

Have you read It?

Mautic is processing bounced as unkown user (logically permanent block) when it's a IP rating problem (contact shoudn't be marked as do not contact)

**Comment by RCheesley** [comment] 2020-09-21 20:50
Hi there,

Firstly, please re-acquaint yourself with our [code of conduct](https://www.mautic.org/code-of-conduct), particularly with regards to expected and unacceptable behaviour. Expletives are not an appropriate or acceptable way to express your disagreement with something that someone has suggested.

In your screenshot, the image shows 'email bounced', rather than 'do not contact'. Therefore I was suggesting that this was correct behaviour because it sounds like the email did not make it to the intended recipient - it bounced - without fully understanding that you were suggesting it was wrongly marking the contact as DNC in addition to reporting that the email had bounced (I believe this is what your later message implied, post expletives).

For information, we are currently processing several bug fixes in the 3.1.1 Release Candidate which will be available this evening which address issues with DNC, and there is an open issue already which relates to [soft bounces being incorrectly flagged as DNC](https://github.com/mautic/mautic/issues/9190).  

Unfortunately we did not have enough tests on [this PR](https://github.com/mautic/mautic/pull/9186), which I believe will resolve the soft-bounce issue, to include it in the 3.1.1 release. We are hopeful that it will ship with 3.1.2.

So either way, the issue is already reported (as far as I can tell from your description) and we should, hopefully, be shipping a fix for it within the next few weeks.

Thanks for taking the time to report the issue, and hopefully next time we can have a slightly more pleasant encounter with less expletives involved. Have a great night. 🙂

**Comment by Carlos-mb** [comment] 2020-09-21 21:08
I apologize if I was too much explicit sharing my mind when I read the response. 

If you had explained in the first response as you have done in the second, I could have had the chance to respond to your explanation.

Anyway. It doesn't matter. I prefer to don't argue. It's a lost battle. 

Regards

**Comment by Carlos-mb** [comment] 2020-09-23 11:33
If someone read this issue sometime.... 

**Yes, it's happening.** 

Emails bounced because of IP reputation are being marked as "do not contact" and removed from all campaigns. 

Microsoft banned my SMTP provider's shared IP and now, all my contacts at outlook, hotmail, live... have been removed from campaigns. 

It was marked as "Unkown user or server"
It was marked as "do not contact"
Removed from all campaigns
I can't send email to they

![image](https://user-images.githubusercontent.com/39302320/94006732-91be8b80-fda0-11ea-976c-de3acbe3a8e0.png)


![image](https://user-images.githubusercontent.com/39302320/94007103-350fa080-fda1-11ea-9972-9f1aa46b6f75.png)
