### ISSUE TITLE
Error 500 in contact view after campaign trigger command 5.x

### ISSUE THREAD

**Issue by annamunk** [mautic/mautic#12585] opened 2023-07-26 13:57 UTC
### Mautic Version

5.0.x series

### PHP version

8.0.20, 8.1.6

### What browsers are you seeing the problem on?

Chrome

### What happened?

After triggering campaign, there is a problem with displaying the contact view and the list of upcoming events.

### How can we reproduce this issue?

Step 1: Create a campaign with an event planned for the future, such as email sending event in the next few days.
Step 2: Rebuild campaign and trigger events.
Step 3: Attempting to open the view of one of the campaign contacts (s/contacts/view/{id}) returns error 500, the metadata appears to be empty.

### Relevant log output

```shell
[2023-07-26 13:07:18] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Key "errors" does not exist as the array is empty." at /var/www/html/app/bundles/LeadBundle/Resources/views/Lead/lead.html.twig line 465 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"errors\" does not exist as the array is empty. at /var/www/html/app/bundles/LeadBundle/Resources/views/Lead/lead.html.twig:465)"} {"hostname":"mautic-web","pid":2385}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2023-08-11 16:20
Thanks @annamunk - this seems to be a duplicate of #12082 so let's centralise efforts there!

**Closed as not planned by RCheesley** 2023-08-11 16:20 UTC
Labels: bug, duplicate, needs-triage

**Comment by Ruffin12** [comment] 2023-09-18 10:04
I upgraded to version 5 of mautic and there, my campaigns when they are executed no longer allow me to access the history of my contacts.

[2023-09-18 09:59:36] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Key "errors" does not exist as the array is empty." at /var/www/html/mautic-5.x/app/bundles/LeadBundle/Resources/views/Lead/lead.html.twig line 443 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"errors\" does not exist as the array is empty. at /var/www/html/mautic-5.x/app/bundles/LeadBundle/Resources/views/Lead/lead.html.twig:443)"

**Comment by Ruffin12** [comment] 2023-09-18 10:07
@RCheesley, How to solve this problem?

**Comment by RCheesley** [comment] 2023-09-28 10:05
@Ruffin12 As it says in the message above, please don't reply on closed issues.  Mautic 5 is not for production use, you should not be upgrading to it.  

If you are saying the same bug as this issue then you need a post on the link duplicated issue: https://github.com/mautic/mautic/issues/12082 rather than here.
