### ISSUE TITLE
[bug] A/B Test Stats doesn't show any graph

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#493] opened 2015-06-03 10:05 UTC
I'm not sure if this is due to the long titles of the pages or due to the data not showing, but there seems to be a problem with the A/B Test Stats: http://nimb.ws/goHbOn

No graph seems to be showing.

**Comment by escopecz** [comment] 2015-07-08 15:48
Yes, this is caused by long titles. I'll take care of it.

**Comment by alanhartless** [comment] 2015-07-19 11:07
Fixed with 1.1.3.

**Closed by alanhartless** 2015-07-19 11:07 UTC
Labels: Bug, Ready To Test
