### ISSUE TITLE
Campaign Condition Contact-Feld.Value Timezome Region This value is not valid.

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#10935] opened 2022-03-07 08:18 UTC
### Mautic Version

4.1.x series

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

Under Campaign Builder -> Condition -> Contact Field Value, if I select a field of type TimeZone or Region and then Equal and I select an item in the list, after clicking on the Add button comes a error message "This value is not valid."
someone knows why the problem arises, yet I have not changed in the Lookup list of TimeZone and Region.

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-03-07 11:22
Closing as a duplicate of https://github.com/mautic/mautic/issues/10911 - please do not create multiple issues for the same problem.

**Closed as completed by RCheesley** 2022-03-07 11:22 UTC
Labels: bug, duplicate, needs-triage
