### ISSUE TITLE
Allow contacts to restart the campaign seems to be always active in release 2.15.2 and later commits

### ISSUE THREAD

**Issue by romainlaisne** [mautic/mautic#7881] opened 2019-09-18 20:19 UTC
## Bug Description
We based our campaigns workflow on the assumption that Mautic would not send an email twice to the same lead if the lead is removed and then re-added to the segment, source of the campaign.

In fact it seems that after version 2.14.0, a lead returning to a segment will receive the campaign email again.

| Q   | A
| --- | ---
| Mautic version | 2.15.2 and following 58 commits (we have tested also on the staging branch)

### Steps to reproduce
1. Make a segment with a lead
2. Create a campaign with this segment as source and an email to send
3. Trigger the campaign to send the email. The email is received
4. Remove the lead from the segment
5. Trigger the campaign again (just in case), nothing happens
6. Add the same lead again to the segment
7. Trigger the campaign again.

Here, with the button "Allow contacts to restart the campaign" to **NO** (default state), we expect that **this lead should not receive the email again**. In our tests, it does.
![image](https://user-images.githubusercontent.com/7721517/65182297-4e309380-da61-11e9-92fe-d11bb9fd8f37.png)

**Till Version 2.14.0** at least (we use it in one of our installation), the behaviour was correct.

We are here 2 developers having tested that. But please test it on your side and confirm this behaviour.

**In a commit after 2.15.2**, we saw something that we thought was related : https://github.com/mautic/mautic/commit/bef2070c93acabcba3d8bf48affc2d18637dae09
We have thus tested the Staging branch. But the behaviour is the same.

Thanks in advance for your help.

We find this one is a huge change in Mautic default behavior to treat campaigns, so we do not really understand why it has changed.

**Comment by romainlaisne** [comment] 2019-09-26 15:39
Any ideas?

**Comment by romainlaisne** [comment] 2019-10-15 09:56
Have anyone had the chance to test this to confirm or not the flow ?
Thanks in advance.

**Comment by dichvuhuuich** [comment] 2019-10-16 04:44
You can try this fix from @DanielCiochiu https://github.com/mautic/mautic/pull/7704.

**Comment by romainlaisne** [comment] 2019-10-30 11:19
Hi all,

I have done the test via mautibox for the issue fix 7704 (https://github.com/mautic/mautic/pull/7704).

Here is the link to the instance : 
https://mautibox.com/7704/s/dashboard

The result below, shows that the user receive a second email when added back to the segment, even though the option "Allow contacts to restart the campaign" is on FALSE : 

![image](https://user-images.githubusercontent.com/7721517/67853496-f3ce2c80-fb0e-11e9-8fe4-8dec8bacd31e.png)

![image](https://user-images.githubusercontent.com/7721517/67853812-91c1f700-fb0f-11e9-91dd-57538aa827bc.png)

**Comment by DanielCiochiu** [comment] 2019-10-30 12:40
This is indeed a bug. The steps to reproduce this bug should be updated because it only happens when you manually add the contacts to the source segments of the campaign.

The problem seems to be that when manually adding contacts to a certain segment (this issue doesn't affect segments:updated or campaign:rebuild commands), Mautic automatically adds these contacts to the campaign for which that segment is source and afterwards adds the contact to the segments (that's why you can notice in contact's history that first it gets added to the test campaign an later to the test segment) without waiting for campaign:rebuild command which checks whether or not campaign can be restarted.

**Comment by RCheesley** [comment] 2020-07-07 19:24
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment] 2020-07-29 10:18
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-29 10:18 UTC
Labels: bug, campaigns, pending-feedback, triage-mautic-3
