### ISSUE TITLE
AWS SES API - MAIL ERROR - mautic 3

### ISSUE THREAD

**Issue by dilshadh** [mautic/mautic#9151] opened 2020-08-28 23:53 UTC
**Tried sending a test email using aws ses api . got the below error:**

mautic.ERROR: [MAIL ERROR] Token amount (2) is larger than the capacity (1). (send); sample@gmail.com {"exception":"[object] (Swift_TransportException(code: 0): Token amount (2) is larger than the capacity (1). at /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []

aws ses smtp is working fine.

**Comment by mabumusa1** [comment] 2020-08-29 11:03
@dilshadh please share the steps to reproduce

**Comment by wise-gorilla** [comment] 2020-08-29 14:28
This issue will be solved after the merge of PR [#9150](https://github.com/mautic/mautic/pull/9150), tille then you can solve it by using the code on that PR or just edit this method on AmazonApiTransport.php

```
    public function getMaxBatchLimit()
    {
        return (50 > $this->concurrency) ? $this->concurrency : 50;
    }
```

**Comment by dilshadh** [comment] 2020-08-29 15:17
I have tried the same . But issue still persist
Error - [2020-08-29 15:12:52] mautic.ERROR: [MAIL ERROR] Token amount (2) is larger than the capacity (1). (send); dilshadh.clt@gmail.com {"exception":"[object] (Swift_TransportException(code: 0): Token amount (2) is larger than the capacity (1). at /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []

**Comment by jclimac** [comment] 2020-08-29 20:00
This error is related to Max Send Rate of each SES account. In my case, my send rate is 14 emails per second, so doing the modification indicated by @Wise-Gorilla did not work, I had to specify a fix number, 13 in my case, and I could send emails without error.

Just for the records, this was the error message I was getting:

[2020-08-29 16:46:20] mautic.ERROR: [MAIL ERROR] Token amount (15) is larger than the capacity (14).

**Comment by wise-gorilla** [comment] 2020-08-29 22:33
@jclimac Strange that the code edit i mentioned didn't work for you,, that code edit i suggested supposed to read the maxSendRate of your SES account and set the getMaxBatchLimit accoridingly... anyway i suggest to use the code in this PR instead [#9150](https://github.com/mautic/mautic/pull/9150) Since the current code has some other issues

**Comment by jclimac** [comment] 2020-08-29 23:22
@Wise-Gorilla yeah, that is strange. Anyway, I also tested with your PR and it is working great. Thank you!

**Comment by wise-gorilla** [comment] 2020-08-29 23:28
@jclimac Great, it would be nice if you submitted a review on the PR so it can be ready to get merged

**Comment by jclimac** [comment] 2020-08-30 00:28
@Wise-Gorilla Done!

**Comment by mabumusa1** [comment] 2020-08-31 07:11
Closing in favor of #9137

**Closed as completed by mabumusa1** 2020-08-31 07:11 UTC
Labels: bug, regression
