### ISSUE TITLE
Timeline Mrerge Error

### ISSUE THREAD

**Issue by tkostenko** [mautic/mautic#327] opened 2015-04-17 18:43 UTC
not sure whats going wrong here but its something I never saw before in log 

[2015-04-17 16:37:35] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The template "MauticLeadBundle:SubscribedEvents/Timeline:merge.html.php" does not exist." at /home4/medsupin/public_html/mail/app/cache/prod/classes.php line 1093 {"exception":"[object] (InvalidArgumentException(code: 0): The template \"MauticLeadBundle:SubscribedEvents/Timeline:merge.html.php\" does not exist. at /home4/medsupin/public_html/mail/app/cache/prod/classes.php:1093)"} []

**Comment by alanhartless** [comment] 2015-05-19 19:46
This is likely caused by the same issue as #382.  Let's close this one in favor of it.

**Closed by alanhartless** 2015-05-19 19:46 UTC
Labels: Duplicate
