### ISSUE TITLE
GrapeJS and CSS style on Mautic v4.2.x bug in Outlook

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#11004] opened 2022-03-25 16:11 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

On Mautic 3.x and Mautic 4.1.2 when I create a theme and use it the HTML/CSS code is not modified.
**From Mautic 4.2.0 onwards, following the same procedure (with the same theme) the code is modified which causes layout problems with Outlook.**

The problem found in the GrapeJS builder is :
- All "inline" styles are removed in favour of CSS styles added at the end of the page and id="..." on the elements. These CSS styles are not interpreted by Outlook or mail. These styles were already present on the previous versions but the "inlines" styles were not removed.
- By looking for documentation on Outlook, I end up realizing that there is no real reason why Outlook does not interpret the CSS. The source code of an e-mail that causes problems when tested in Mailchimp... no miracle, it still doesn't work. The same code by moving the CSS styles created by Mautic into the <head> and no longer before closing the body. And there, it works.
- I do the same by putting the styles in the <body> but at the beginning and not at the end, and that works too. So it seems that Mautic does not put its styles in the right place for Outlook.

With Mautic 4.2.0 the emails sent when they are read on Outlook :
- an e-mail with the CSS styles at the end of the <body>: NOK
- an e-mail with CSS styles at the beginning of <body>: OK
- an e-mail with CSS styles in the head tag: OK

I see that the GrapeJS builder has evolved between Mautic 4.1.2 and Mautic 4.2.0.
In any case on Mautic v3.3.1 it works correctly, while on Mautic v4.2.0 there is a bug.

### How can we reproduce this issue?

Step 1: create a Mautic theme compatible with Outlook
Step 2: integrate this theme in Mautic 4.1.2 => send a test email => see the compliant layout in Outlook
Step 3: integrate this theme in Mautic 4.2.0 => send a test email => see the layout NOT conforming in Outlook

### Relevant log output

```shell
RAS
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-03-29 15:58
Thanks for the report @PierreAmmeloot but I think this is a duplicate of several existing issues and we are already working on a fix:

https://github.com/mautic/mautic/issues/10769
https://github.com/mautic/mautic/issues/10572

Proposed fix: https://github.com/mautic/mautic/pull/10976

**Closed as completed by RCheesley** 2022-03-29 15:58 UTC
Labels: bug, needs-triage

**Comment by PierreAmmeloot** [comment] 2022-04-01 21:07
Hello @RCheesley,

Why wasn't this patch offered with Mautic 4.2.1?
What can I do in the meantime for my instances that have error emails?

Pierre

**Comment by RCheesley** [comment] 2022-04-02 13:00
Please review the comments on the PR: https://github.com/mautic/mautic/pull/10976 - it is adding functionality so it will be released in 4.3 most likely. Apply that PR if you want a fix in the meantime.

**Comment by benfavre** [comment] 2022-04-07 16:19
#10976 will not fix the issue
I recommend having a developer send emails with your product to a mail box and then look at the content.

**Comment by PierreAmmeloot** [comment] 2022-04-08 16:46
Hello @RCheesley,

I confirm #10976 not fix this bug on my side.

Pierre
