### ISSUE TITLE
Delete all contacts in a segment

### ISSUE THREAD

**Issue by dpeatross** [mautic/mautic#2562] opened 2016-09-20 00:36 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | When I am in segment view I am unable to batch delete contacts, however it can be deleted one by one. |
| Feature request? | Add delete all contacts in this segment button. |
| Enhancement? |  |
## Description:

When I am in segment view I am unable to batch delete contacts, however it can be deleted one by one. The system acts like it going to delete the contacts then they just reappear. 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1 |
| PHP version | 5.6.24. |
### Steps to reproduce:
1. In Segment view, click the highlight all checkbox. 
2.  Click the delete button selected items. Confirm by click delete button.
### Log errors:

2016-09-20 00:15:50] mautic.WARNING: PHP Warning: php_uname() has been disabled for security reasons - in file /home/nbsclead/public_html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php - at line 116 [] []
[2016-09-20 00:16:00] mautic.ERROR: Warning: php_uname() has been disabled for security reasons - in file /home/nbsclead/public_html/mautic/app/bundles/CoreBundle/Helper/UpdateHelper.php - at line 116 [] []
[2016-09-20 00:27:46] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:27:57] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:28:42] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:31:04] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:31:17] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:33:15] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:35:57] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []
[2016-09-20 00:36:32] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []

**Comment by escopecz** [comment] 2016-09-30 09:22
I can batch-delete contacts, so I wasn't able to reproduce the bug.

The `php_uname` error is fixed in Mautic 2.2.0.

To avoid the second error, follow the suggestion in it: `To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini`

I'll mark this as feature request to add option to delete all contacts from a segment.

**Comment by olimits7** [comment] 2017-02-08 23:18
@escopecz was this **feature request** ever added?  

I can select up to 100 contacts in a segment to delete, but I would like the option to select ALL contacts in the segment to delete;  I need to delete 3,000+ contacts in this segment and doing this 100 at a time is very time consuming.

**Comment by escopecz** [comment] 2017-02-09 09:38
@olimits7 if this feature was added, it would be written in its history, linked to the pull request which added the feature and closed.

**Comment by olimits7** [comment] 2017-02-09 16:55
@escopecz ok, i got confused because i thought you closed this "**feature request**" when I saw the "**Closed**" tag next to "**Delete all contacts from a segment with one click #3363**" but I see this is for another issue.

**Closed** 2017-02-17 09:11 UTC
Labels: Feature Request, Ready To Test

**Comment by ramphy** [comment] 2020-04-14 23:00
You can access directly from mysql database (phpmyadmin) and empty the table "leads" IF YOU WANT DELETE ALL CONTACTS.

**Comment by asksock** [comment] 2021-10-22 07:09
> You can access directly from mysql database (phpmyadmin) and empty the table "leads" IF YOU WANT DELETE ALL CONTACTS.

Anyone use this method and confirm it?

**Comment by escopecz** [comment] 2021-10-23 17:56
@asksock as mentioned in the pull request linked to this issue: https://github.com/mautic/mautic/pull/3413

There is a campaign action that can delete all contacts. Steps:
1. Have a segment with contacts you want to delete
2. Create a new campaign with the segment as a source
3. Add the delete contacts action

Warning:
1. It will delete the contacts and all their actions like they have never existed. For example the campaign stats will show zero executed events because the campaign event logs will be deleted together with the contacts you are deleting.
2. If you'll be deleting a lot of contacts (hundreds of thousands) it can make a great load on your database as it is deleting not only the contact records but also all their history from various other tables.
