### ISSUE TITLE
Feature Request - Pick Specific Days For Actions In Campaign Builder

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [mautic/mautic#2417] opened 2016-08-29 16:54 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y 
| Enhancement? | N

## Description:
In the campaign builder, would it be possible to create an option where we could schedule an email or action to occur on specific days of the week?

It would be a gem if i could:
* click once on the day name (outlined in red) and it would automatically select all of those days under it and highlight the numbered days under it as being activated for that month (image 1)
* click on the date highlighted and assign a specific email or action
* click on a specific date again to disable and show it be having an un-highlighted status (image 2)
* click twice on the day name (selects all days in the calendar year (images 3 & 4)

Image 1
![Image 1](https://s18.postimg.io/b7x346z3d/image.png)

Image 2
![Image 2](https://s18.postimg.io/ltgyg75ex/image.png)

Image 3
![Image 3](https://s18.postimg.io/5sod387jd/image.png)

Image 4
![Image 4](https://s18.postimg.io/vpi1fub6x/image.png)

**Comment by ninjoan** [comment] 2016-08-29 17:16
+1

**Comment by ninjoan** [comment] 2016-08-30 13:29
Another good feature if is possible to in the at specific date/time we have the option to send only weekdays.

For sample: 
Scenario we have a campaign that sends 2 emails (Email #1 a confirmation email, Email #2 The Whitepaper or any other content)

So if a lead field the form on Sunday and Sunday is not a working day the Email #1 will be send because is a confirmation email but the Email #2 will be delivery on Monday this will give the sensation that this email is sent by a human and not a Software.

Do you get the idea?

**Comment by escopecz** [comment] 2016-09-30 12:05
This seems to be duplicate of https://github.com/mautic/mautic/issues/539

**Closed by escopecz** 2016-09-30 12:05 UTC
