### ISSUE TITLE
Some contact field's values get deleted when updating other fields via API.

### ISSUE THREAD

**Issue by krnowakowski** [mautic/mautic#7544] opened 2019-05-16 14:34 UTC
**Bug Description**

When updating contacts via API, some fields get cleared for no apparent reason. From initial tests three fields are affected - timezone, stage and points.

Q | A
-- | --
Mautic version | 2.15.1
Mautic API version | 2.15.1
PHP version | 7.2
Browser | Firefox Developer Edition 67.0b9

**Steps to reproduce**

1. Create an array of fields to be updated, e.g.:
$mautic_contact = array( 'email' => $mtc_email, 'mobile' => $mtc_mobile, 'preferred_locale' => $_SESSION['lang']);
2. Send edit request via API:
$createIfNotFound = true;
$response = $contactApi->edit($mautic_contact_id, $mautic_contact, $createIfNotFound);

**Log errors**

Not applicable

**Comment by escopecz** [comment] 2019-05-20 08:17
I transfered this issue from the api-library repo directly to mautic repo as that's the place where the problem is.

**Comment by RCheesley** [comment] 2020-07-29 12:20
Closing as this should have been addressed by #7717 which was merged in 2.16.1. Please open another issue if you continue to encounter this problem and link to this one.

**Closed by RCheesley** 2020-07-29 12:20 UTC
Labels: API, bug
