### ISSUE TITLE
Feature Request - Add delivery day limit

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1131] opened 2015-11-05 12:08 UTC
Hi,

In a campaign you can delay the sending of an email (eg: 4 days after trigger).
By consequence *-because campaigns can be perpetual-* the email can be send the weekend and when you're working B2B or if you wanna try to simulate a "human" email, that's not nice at all.

My opinion, **we should on the campaign settings enable email time delivery windows**.
__________
Here is an example of competitor:
![capture d ecran 2015-11-05 a 13 07 23](https://cloud.githubusercontent.com/assets/14075239/10967904/2f815a9e-83be-11e5-80b2-a543a968a770.png)

N.

**Comment by dmarkotter** [comment] 2015-11-05 12:56
Apart from preventing delivery over a  weekend, this also lets you restrict delivery time to, say, between 07h00  and 09h00 (using the subscriber's local time), rather than whatever time they subscribed.

**Comment by alanhartless** [comment] 2015-12-17 19:24
Marking this as a duplicate of #539.

**Closed** 2015-12-17 19:24 UTC
Labels: Duplicate
