### ISSUE TITLE
[BUG] Dates of read emails in lead profile log are not updated 

### ISSUE THREAD

**Issue by inseti** [mautic/mautic#1014] opened 2015-10-15 10:25 UTC
I'm sending custom emails to leads from their profile page.

The read dates are not updated in the log, I can see properly the date/hour of the lead Last Activity in the Lead List, but in their profile the dates are not updated correctly.

In the Lead List I see that the lead Last Activity was **Yesterday** at 7:00pm but in the Profile Log the last read of the email (and last activity) it shows that was **Today** at 7:00pm (and today actual time is 11:00am)

Using version 1.2

**Comment by alanhartless** [comment] 2015-10-21 05:50
Could this be a duplicate of #935 which is fixed in #973 and will be part of the next release?

**Comment by inseti** [comment] 2015-10-21 09:18
It seems that it's not the same issue, I detected the problem in the Lead Log, not in the Lead List Table.

And it was for periods of time about days, not 1month.

In any case, I'm going to implement the PR and I'll check the error again.

Thanks!

**Comment by alanhartless** [comment] 2015-10-21 13:13
Let us know! I wasn't for sure if the issue was the lead list showing the incorrect date/time or the profile timeline showing the incorrect date/time. 

And is the issue that the email is not marked as read or is the issue an incorrect last active date/time?

Thanks!

**Comment by inseti** [comment] 2015-10-21 18:54
Yes Alan, the issue is that in the **lead profile timeline** there is an incorrect last active date/time comparing with the lead list table.

As an example:

In the Lead List Table I see that the lead Last Activity was **Yesterday at 7:00pm** 
but in the Profile Log the last read of the email (and last activity) it shows that was **Today at 7:00pm** (and today actual time is 11:00am)

**Closed** 2015-10-22 18:04 UTC
Labels: Bug
