### ISSUE TITLE
Mautic 3.0.0 - Wrong memory_limit warning php.ini (< 128 MB warning but 256 is set)

### ISSUE THREAD

**Issue by CyberMarsl** [mautic/mautic#8932] opened 2020-06-20 14:02 UTC
Fresh install of Mautic 3.0.0 Environemnt Check on installer suggests this Recommendation:

---
"We have detected some minor things that we recommend changing in order to have a better Mautic experience:
    The memory_limit setting in your PHP configuration is lower than the suggested minimum limit of 128MB. Mautic can have performance issues with large datasets without sufficient memory."
---

BUT, php.ini is set 256MB:                   memory_limit = 256M
testing php config in commandline with -v it recognizes 256mb
testing in browser with phpinfo(): its 256 MB.

Mautic Version 3.0.0. fresh installation (Mautic 2.x did not reported this problem)
PHP Version: 7.3.19
Browser: Firefox

### Steps to reproduce
1.  Get a fresh install of Mautic 3.0
2.  Start installation (it starts the Environment Check)

**Comment by autoize** [comment] 2020-06-20 17:16
We can also reproduce this. Memory limit is set to 512M but setup wizard reports it is < 128M.

**Comment by dennisameling** [comment] 2020-06-21 15:31
Can reproduce this on PHP 7.3 / Mautic 3.0.0 fresh installation:

`memory_limit` set to 256MB but error still shows:

![image](https://user-images.githubusercontent.com/17739158/85228647-cbb87400-b3e4-11ea-8fe0-f6c9d2f3b4d6.png)

**Comment by dennisameling** [comment] 2020-06-21 15:38
Just checked in the source code. Turns out [the recommended `memory_limit` has increased to 512MB in Mautic 3](https://github.com/mautic/mautic/blob/staging/app/bundles/InstallBundle/Configurator/Step/CheckStep.php#L231), but the error message [is still showing 128MB](https://github.com/mautic/mautic/blob/staging/app/bundles/InstallBundle/Translations/en_US/messages.ini#L58). So it's just a display error.

@CyberMarsl @autoize can you confirm whether setting the `memory_limit` to 512M fixes the issue?

**Comment by CyberMarsl** [comment] 2020-06-23 14:45
@dennisameling great to know, well update to 512 works well.

**Closed as completed** 2020-06-27 14:20 UTC
Labels: bug, essential
