### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by azanatek** [mautic/mautic#2222] opened 2016-08-09 21:12 UTC
What type of report is this:

| Q  | A
| ---| yes
| Bug report? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | latest
| PHP version | 7

### Steps to reproduce:
1.  under normal operating conditions

mautic.core.error.500 
500 Internal Server Error
Mautibot
mautic.core.report_issue
 
### Log errors: cant access

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-08-10 06:54
Closing because the actual error message is missing and most of the questions are not filled at all. If you want us to help fix your error, go to app/logs and find it there. Also, fill in the description and steps to reproduce. The Mautic version "latest" doesn't really work through the time.

**Closed by escopecz** 2016-08-10 06:54 UTC
