### ISSUE TITLE
issue importing csv background in obviously correct format

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4552] opened 2017-08-01 12:14 UTC
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
This file only with email address cannot be imported for i don't know which reason. Obviously it is correctly formatted.
File is coming from a website that propose example formatted files.

#### Remove .txt extension before your try (csv not supported on github)
[us-500.csv.txt](https://github.com/mautic/mautic/files/1190539/us-500.csv.txt)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1
| PHP version |

**Comment by corradofiore** [comment] 2017-08-01 15:40
Me too.  I'm getting this error every time I try to upload a CSV (which has been correctly produced using LibreOffice and double-checked in BBEdit):

> Invalid file type "application/octet-stream". Use a file that matches one of the following mime types: "text/csv", "text/plain". 

Nothing gets printed in Mautic logs.

**Comment by corradofiore** [comment] 2017-08-01 17:26
I forgot to add:  the problem happened with all of the browsers I tried (Chrome, FF, Safari).

OS:  Mac OS X 10.11.6.

**Comment by corradofiore** [comment] 2017-08-02 04:57
The attached file above (us-500.csv.txt) has a "Classic Mac"-type line ending (CR).  Maybe the parser in Mautic doesn't like it?

**Comment by escopecz** [comment] 2017-08-02 07:08
Good catch. This is note from the [PHP docs](http://php.net/manual/en/function.fgetcsv.php):

> Note: If PHP is not properly recognizing the line endings when reading files either on or created by a Macintosh computer, enabling the auto_detect_line_endings run-time configuration option may help resolve the problem.

Could you try to set auto_detect_line_endings to 1 in your php.ini, restart the server and try to import again?

**Comment by awurman** [comment] 2017-08-09 23:06
@escopecz  i tryied that... not working at all

**Comment by servantlabs** [comment] 2017-11-01 02:40
I'm having this same problem. It was working for me (Mac, OS X Sierra) by exporting a unicode-8 csv. Then, without updating or any other change on my part, it gave me this error.

**Comment by marcocevoli** [comment] 2018-03-04 20:39
Same issue here. Tried to convert EOL to Win, Unix and Mac, tried to convert encoding, in all possible combinations. Still no luck.

**Comment by servantlabs** [comment] 2018-03-04 20:41
I think the problem is empty columns or rows. Once I delete empty columns and rows in Goggle sheets, then the exported csv works.

**Comment by kauelinden** [comment] 2018-05-16 22:11
Today I got this error during import to one of my customers.

I started to split the file to try to find the problem.

After one hour I realized some email address had an especial character
 that is showed in open office like this""
![image](https://user-images.githubusercontent.com/25824537/40146582-70704636-593c-11e8-854d-952f690a8bcc.png)

On notepad++ it shows like this:
![image](https://user-images.githubusercontent.com/25824537/40146554-4b748482-593c-11e8-831f-2b32cb6ba94c.png)

So if you find and replace for this character then remove it, Mautic will be able to process the file.

This was the firt time I got this problem. My customer said he used the service "neverbounce" to clean his list, so I believe this typo was generated from neverbounce

I hope it help others with this problem.

**Comment by hickham** [comment] 2019-01-07 02:35
> Today I got this error during import to one of my customers.
> 
> I started to split the file to try to find the problem.
> 
> After one hour I realized some email address had an especial character
> that is showed in google sheets like this:
> 
> ![image](https://user-images.githubusercontent.com/25824537/40146582-70704636-593c-11e8-854d-952f690a8bcc.png)
> 
> On notepad++ it shows like this:
> 
> ![image](https://user-images.githubusercontent.com/25824537/40146554-4b748482-593c-11e8-831f-2b32cb6ba94c.png)
> 
> So if you find and replace for this special character then remove it, Mautic will be able to process the file.
> 
> I hope it help others with this problem.

Me Salvou Kaue. Voce perdeu 1 hora e eu perdi 5 por causa de um caracter lazarento

**Closed** 2019-02-06 15:17 UTC
Labels: Bug

**Comment by rwrz** [comment] 2020-11-05 18:17
On Sublime, you can search for "" (will show on your search bar <0x1a>).
