### ISSUE TITLE
Pipedrive mapping issue when pipedrive contact field is deleted cause sync error

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5325] opened 2017-11-13 08:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I push a contact to pipedrive in a campaign, contact does not synchronize and I've got an error in mautic logs: 

`[2017-11-13 00:28:24] mautic.ERROR: INTEGRATION ERROR: Pipedrive - Client error: `POST https://mydomain.pipedrive.com/v1/persons?api_token=d01b78081cc6740eddc9dea044f4d09c31cdaa36` resulted in a `400 Bad Request` response: {"success":false,"error":"Unknown field 'ca56a5a6bf930725ab0dd333a628908f988d4472' in your request."}  [] []`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Set the pipedrive pluggin
2. Create a campaign and add the action "push to integration"
3. Lauch the campaign for a contact
4. Wait and check in pipedrive
5. Contact does not get to pipedrive
6 Check in mautic "system info" and "journal" to see the logs.

**Comment by kuzmany** [comment] 2017-11-15 14:06
Please copy what fields you tried sync. I did try and sync works properly for firstname and email. 
As I see in your log, Did you tried sync custom field?

**Comment by npracht** [comment] 2017-11-20 10:31
Very weird. We had a field with the alias `ca56a5a6bf930725ab0dd333a628908f988d4472` from Pipedrive in the integration mapping in the SQL.

I reseted the configuration of the plugin and it works. I don't know how this field arrived here...

**Comment by npracht** [comment] 2017-11-20 10:34
I have the issue with another customer (another pipedrive account).
That time, there are several of those weird fields. Something is going strange here...

![capture d ecran 2017-11-20 a 11 32 28](https://user-images.githubusercontent.com/14075239/33014138-932e4448-cde6-11e7-8b68-65ca19c1925c.png)

**Comment by npracht** [comment] 2017-11-20 11:02
Here we go @kuzmany !

So those IDs are "normal". The issue you can reproduce it like that !

1. Create a custom field in Pipedrive
2. Map it in integration mapping tab
3. Delete the custom field in Pipedrive
4. Notice that in the integration_settings table the mapping with the deleted field is still existing. You can try to open the mapping and save & close but in DB the value stays
5. Push a contact and notice error "the field XXX is not existing"

**Comment by kuzmany** [comment] 2017-11-20 11:12
Yeah. In progress :)

**Comment by npracht** [comment] 2017-12-11 16:24
@kuzmany is that fixed in your full sync. mode ?

**Comment by kuzmany** [comment] 2017-12-11 22:31
@npracht  nope

**Comment by npracht** [comment] 2017-12-21 10:26
@alanhartless & @escopecz 
I just noticed that this issue is not only concerning pipedrive, we have an own integration and the issue is also existing.

## The issue
When you delete a field that has been previously mapped, then it stays saved in the plugin_integration_settings table and generates different issues, even if you change the mapping and save, the deleted fields says in DB.
Only way to get rid of it is to manually clean the mentioned table in SQL.

I'm scared this issue is happening for all the integrations (i cannot test all, i don't have access for Salesforce & cie).

## Questions
How to correct that? I see 2 options:

### Improve mapping saving
We would need to be sure that when you open the plugin mapping panel and save, it erase totally the saved data in the plugin_integration_settings table. I don't know how today those old/deleted fields stay here.

🔴  I don't feel confortable with it because if you remove a field and forgot about the fact that it was mapped, you have a silent issue.
---> You could have an error message when you try to delete a field used in an integration like: `this field is used in an integration mapping, please first make it free before removing it.`

### Add a trigger when you delete a field 
This is close to the error message. The trigger is the field deletion.
In that case it could clean automatically every integration mapping in the plugin_integration_settings table and remove the mapping of the deleted field.

I like this one more because that way it is applied on all integration and the issue cannot exist and it is not depending on human action (redo integration mapping).

Your opinion? How would you proceed?
Thanks !

**Comment by escopecz** [comment] 2017-12-21 10:39
I'm not skilled in the integration mapping, but from testing I know that the mapping form is not paginated because the API requests for integration fields were taking ages and caused time limit errors. From this reason only the fields from one page are updated instead of all wiped out and saved.

The idea with event handler on custom field delete is good and should be implemented.

**Comment by kuzmany** [comment] 2017-12-22 08:21
@npracht but this solution resolve issue just if you delete custom field in Mautic, not in externernal software like Pipedrive?

**Comment by npracht** [comment] 2017-12-22 08:24
@kuzmany i think you are right...
@alanhartless @escopecz any suggestion ?

**Comment by kuzmany** [comment] 2017-12-22 08:29
That means every integration should resolve this issue in their own way.
If u delete custom field in Mautic, there is possible create  solution for all integrations.
But in reverse, not.

**Comment by npracht** [comment] 2017-12-22 08:31
Yes but you cannot ask Salesforce to do something for mautic...
That means that we should consider both options. When you open the mapping of an integration it should clean deleted fields from the integration. This is he only way to manage it from the mautic side i think.

**Comment by kuzmany** [comment] 2017-12-23 09:44
Yes, thats sounds like possible solution

**Comment by kuzmany** [comment] 2018-02-04 14:42
WIP

**Comment by kuzmany** [comment] 2018-02-04 14:42
Label: WIP

**Comment by npracht** [comment] 2018-02-20 16:07
update @kuzmany ?

**Comment by kuzmany** [comment] 2018-02-28 08:27
Label: Ready to test

**Closed** 2019-04-12 12:06 UTC
Labels: Bug, Ready To Test
