### ISSUE TITLE
Text disappears from GrapesJS Builder

### ISSUE THREAD

**Issue by burnoutberni** [mautic/mautic#10130] opened 2021-06-04 10:57 UTC
## Bug Description
When creating a mailing with the new GrapesJS Builder, I can edit everything normally. But once I close the builder and then reenter, most of the texts just disappear. When looking into the MJML/HTML code, it's still there, yet I'm no longer able to edit the content with the builder. 

![Screenshot_2021-06-04 New Email Mautic(1)](https://user-images.githubusercontent.com/1640933/120791292-50d46480-c534-11eb-9c3c-fe0a04164f59.png)
![Screenshot_2021-06-04 New Email Mautic(2)](https://user-images.githubusercontent.com/1640933/120791287-4f0aa100-c534-11eb-8496-bafe39c199c3.png)

| Q   | A
| --- | ---
| Mautic version | 3.3.0 (I think, our Mautic is managed and I didn't find a quick way to find out the current version from the frontend)
| PHP version | 7.3.28-1+0~20210503.84+debian10~1.gbp6819da
| Browser | Firefox 88

### Steps to reproduce
1. Create mailing
2. Enter builder
3. Optionally: Edit content
4. Close builder
5. Enter builder again
 
### Log errors

No errors.

**Comment by burnoutberni** [comment] 2021-06-04 11:05
On closer inspection, this looks related to #9987. When I look at the Web Inspector and look at the image above the text block, you can see that there's actually all of the content _inside_ the `<img>`

```
<img alt="Lake of Brienz - Switzerland" src="https://mautic.links-wien.at/themes/brienz/assets/brienz.jpeg" style="border: medium none; display: block; outline: currentcolor none medium; text-decoration: none; height: auto; width: 100%; font-size: 13px; pointer-events: none;" width="550" height="auto">
<tr data-gjs-type="mj-text" draggable="true" color="#000000" font-family="Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif" padding-bottom="0px" padding-top="0px" line-height="1.5" id="i9xsi" style="pointer-events: all; display: table; width: 100%;" align="justify">
              <td style="font-size: 0px; padding: 0px 25px; word-break: break-word; pointer-events: none;" align="justify">
                
      <div style="font-family: Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 1.5; text-align: justify; color: rgb(0, 0, 0); pointer-events: none;">
          <p><span style="color: rgb(57, 63, 76);" line-height="1.5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rutrum enim eget magna efficitur, eu semper augue semper. Aliquam erat volutpat. Cras id dui lectus. Vestibulum sed finibus lectus, sit amet suscipit nibh. Proin nec commodo purus. Sed eget nulla elit. Nulla aliquet mollis faucibus.</span></p>
        </div>
    
              </td>
            </tr><tr data-gjs-type="mj-button" draggable="true" background-color="#486AE2" color="#FFFFFF" border="none" padding="15px 30px" href="#" font-family="Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif" padding-top="0px" id="ivg8h" style="pointer-events: all; display: table; width: 100%;">
              <td vertical-align="middle" style="font-size: 0px; padding: 0px 30px 15px; word-break: break-word; pointer-events: none;" align="center">
                
      <table role="presentation" style="border-collapse: separate; line-height: 100%; pointer-events: none;" cellspacing="0" cellpadding="0" border="0">
        <tbody style="pointer-events: none;"><tr style="pointer-events: none;">
          <td role="presentation" style="border: medium none; border-radius: 3px; cursor: auto; background: rgb(72, 106, 226) none repeat scroll 0% 0%; pointer-events: none;" valign="middle" bgcolor="#486AE2" align="center">
            <a href="#" style="display: inline-block; background: rgb(72, 106, 226) none repeat scroll 0% 0%; color: rgb(255, 255, 255); font-family: Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif; font-size: 13px; font-weight: normal; line-height: 120%; margin: 0px; text-decoration: none; text-transform: none; padding: 10px 25px; border-radius: 3px; pointer-events: none;" target="_blank">READ MORE</a>
          </td>
        </tr>
      </tbody></table>
    
              </td>
            </tr></img>
```

**Comment by burnoutberni** [comment] 2021-06-04 11:23
I'm using the Brienz theme here, which is shipped by default. I noticed that the original theme MJML does not include self-closing image tags (see https://github.com/mautic/mautic/blob/34e8b58c9ec029d52cbdf80097230200c438b788/themes/brienz/html/email.mjml.twig).

Nevertheless, when I click on "View code" in the GrapesJS builder, all of the `<mj-image>` elements are now self-closing. Next time I enter the MJML, the other bug hits and the texts below the self-closing images are gone.

```
        <mj-image src="https://mautic.links-wien.at/themes/brienz/assets/brienz.jpeg" alt="Lake of Brienz - Switzerland" border="none" width="550px" padding-left="0px" padding-right="0px" padding-bottom="0px" padding-top="0"/>
```

**Comment by RCheesley** [comment] 2021-06-04 11:35
@burnoutberni I think that this is probably a duplicate of #9987 so let's have the discussion over there to keep it all in one place. Thanks for taking the time to report it!

**Closed as completed by RCheesley** 2021-06-04 11:35 UTC
Labels: T1, bug, duplicate, builder-legacy, needs-triage
