### ISSUE TITLE
Form submission fails

### ISSUE THREAD

**Issue by janxin** [mautic/mautic#4506] opened 2017-07-25 04:22 UTC
Yesterday I upgrade to 2.9.0 and now, when I submit a form which simple collects emails, I got this error:

[2017-07-25 04:16:16] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /home/gravcmspro/mautic.gravcmspro.com/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /home/gravcmspro/mautic.gravcmspro.com/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

My PHP version is 5.6

**Comment by escopecz** [comment] 2017-07-25 06:31
Duplicate of https://github.com/mautic/mautic/issues/4349

**Closed by escopecz** 2017-07-25 06:31 UTC
