### ISSUE TITLE
tracking on GMAIL is pointless as of now (proxy)

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10409] opened 2021-09-06 06:03 UTC
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

The situation has been reported already at least 
 [here](https://github.com/mautic/mautic/issues/7884) and
[here](https://forum.mautic.org/t/mautic-tracks-as-email-read-when-email-is-not-read-by-user/11676/12)

I have in mind as this might be tricky to resolve but still the reality is that like it or not 90% of target audience just might be behind a GMAIL account.

Ideas:

- get to know IPs used by google's proxies and black-list these from affecting statistics (for that a sort of a public database would be needed)
- check e-mail client/other meta data reported by the proxy (probably not good enough as google could get past these fast by faking data)
- simply omit the first open when targeting GMAIL, I think the first open event always fires almost the exact time the-email is dispatched or introduce sort of a grace time-period.

### How can we reproduce this issue?

Step 1: like described

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2021-09-06 15:35
Closing as a duplicate of https://github.com/mautic/mautic/issues/9798 which has several discussions on workarounds.

**Closed as completed by RCheesley** 2021-09-06 15:35 UTC
Labels: bug, needs-triage
