### ISSUE TITLE
Allow users to flow through campaign more than once

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4470] opened 2017-07-20 03:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
When using campaigns for data management and flowing leads through a funnel, you may add conditions as a fail-safe to double check contacts meet the criteria before continuing on. The problem is, if the contact fails the check, then qualifies later, the lead has already run through the campaign and cannot flow through again. 

There should be a setting on the campaign to allow contacts to flow through "once" or "every time" if meet the original contact source condition again(i.e. fills out the same form again, or qualifies for the selected segment).

**Comment by escopecz** [comment] 2017-07-20 08:03
Seems like duplicate of https://github.com/mautic/mautic/issues/1606

**Closed by escopecz** 2017-07-20 08:03 UTC
