### ISSUE TITLE
Scrolling in email builder launched from campaign builder, changes the selected email on the action

### ISSUE THREAD

**Issue by kgroveshok** [mautic/mautic#4264] opened 2017-06-20 11:45 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:

Editing an email in campaign builder can cause the selected email action to change

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.8.0
| PHP version | 5.6

### Steps to reproduce:
1. When in the campaign builder and then clicking on an email action step allows for the editing of the email displayed in the combo box.

2. This email allowing access to the email builder. When in the email builder click on any of the panels which then produces a large scroll area of controls in the right hand side.  In the scroll bar use the mouse wheel to move up and down a few times, finally ending on a scroll down. 

3. Save the email and return to the campaign builder.

4. The selected email that was in the combo box is likely do have changed. For example If the last scroll action was to the bottom, the email selected in the combo would be the last one in the combo list.

**Comment by RCheesley** [comment] 2020-01-15 12:58
Unable to reproduce in 2.15.3 so closing this issue.

**Closed by RCheesley** 2020-01-15 12:58 UTC
Labels: Bug
