### ISSUE TITLE
Users seeing log entries relating to PHP version since 3.2.5

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9619] opened 2021-01-25 20:57 UTC
## Bug Description

From Slack:

> Just tried the last update to 3.2.5 ... Now I have this notice in the error log, every time I log into Mautic:
> mautic.NOTICE: PHP Notice - Undefined index: show_php_version_warning_if_under - in file /var/www/htdocs/app/bundles/CoreBundle/Release/Metadata.php - at line 82 {"metadata":{"version":"3.0.0-beta2","stability":"beta","minimum_php_version":"7.2.21","maximum_php_version":"7.3.99","minimum_mautic_version":"3.0.0-alpha","announcement_url":""}} []

Users are on 7.3.x and 7.4.14 versions of PHP.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.3.x and 7.4.14
| Browser | N/A

**Comment by izdrail** [comment] 2021-01-25 21:00
running 
```
PHP Version 7.3.23-1+focal
System	Linux ns306294 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
Build Date	Oct 1 2020 16:41:09
Configure Command	'./configure' '--prefix=/usr/local/lsws/lsphp73' '--disable-cgi' '--enable-cli' '--enable-phpdbg=no' '--with-litespeed' '--with-config-file-path=/usr/local/lsws/lsphp73/etc/php/7.3/litespeed/' '--with-config-file-scan-dir=/usr/local/lsws/lsphp73/etc/php/7.3/mods-available/' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--libdir=${prefix}/lib/php' '--libexecdir=${prefix}/lib/php' '--datadir=${prefix}/share/php/7.3' '--program-suffix=7.3' '--disable-all' '--disable-debug' '--disable-rpath' '--disable-static' '--with-pic' '--with-layout=GNU' '--without-pear' '--enable-bcmath' '--enable-calendar' '--enable-ctype' '--enable-dom' '--with-enchant' '--enable-exif' '--with-gettext' '--with-gmp' '--enable-fileinfo' '--enable-filter' '--enable-ftp' '--enable-hash' '--with-iconv' '--enable-mbregex' '--enable-mbregex-backtrack' '--enable-mbstring' '--enable-phar' '--enable-posix' '--with-mcrypt' '--enable-mysqlnd-compression-support' '--with-bz2' '--with-zlib-dir' '--with-openssl=yes' '--with-libedit' '--enable-libxml' '--enable-session' '--enable-simplexml' '--enable-soap' '--enable-sockets' '--enable-tokenizer' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xmlrpc' '--with-xsl' '--with-mhash=yes' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-zip' '--with-sodium' '--with-password-argon2' '--with-system-tzdata' '--with-gd' '--enable-gd-native-ttf' '--with-jpeg-dir' '--with-xpm-dir' '--with-png-dir' '--with-webp-dir' '--with-freetype-dir' '--with-vpx-dir' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--disable-dtrace' '--enable-pdo' '--enable-mysqlnd' '--enable-pcntl' '--with-recode=shared,/usr' '--with-sqlite3=shared,/usr' '--with-pdo-sqlite=shared,/usr' '--with-pdo-dblib=shared,/usr' '--with-ldap=shared,/usr' '--with-ldap-sasl=/usr' '--enable-intl=shared' '--with-snmp=shared,/usr' '--enable-json=shared' '--with-pgsql=shared,/usr' '--with-pdo-pgsql=shared,/usr' '--enable-opcache' '--enable-opcache-file' '--enable-huge-code-pages' '--with-imap=shared,/usr' '--with-kerberos' '--with-imap-ssl=yes' '--with-mysqli=shared, mysqlnd' '--with-pdo-mysql=shared, mysqlnd' '--with-tidy=shared,/usr' '--with-pspell=shared,/usr' '--with-curl=shared,/usr' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/php7.3-7.3.23=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -Wall -fsigned-char -fno-strict-aliasing -g'
```
My app/release_metadata.json 

```
{
  "version": "3.2.5",
  "stability": "stable",
  "minimum_php_version": "7.2.21",
  "maximum_php_version": "7.4.99",
  "show_php_version_warning_if_under": "7.3.0",
  "minimum_mautic_version": "3.1.0",
  "announcement_url": ""
}

```

**Comment by dennisameling** [comment] 2021-01-25 21:04
Cannot seem to reproduce locally on PHP 7.4.13 (DDEV). error_reporting is set to E_ALL and tried in Mautic's dev mode as well.

- Does clearing your cache (`bin/console cache:clear`) make any difference?
- Are you getting a more complete stack trace in the logs? From the log above I can't see what function is calling `/var/www/htdocs/app/bundles/CoreBundle/Release/Metadata.php` 

Thanks in advance!

**Comment by jonathandhn** [comment] 2021-01-26 00:33
> CronJob messed-up with Mautic 3.2.5 on php 7.4.14

Cron <www-data@vps1> /usr/local/lsws/lsphp74/bin/php /var/www/mautic.jonathanphoto.fr/bin/console mautic:update:find 1>/dev/null 
`PHP Notice:  Undefined index: show_php_version_warning_if_under in /var/www/mautic.jonathanphoto.fr/app/bundles/CoreBundle/Release/Metadata.php on line 82`

Mautic shows php warnings on 3.2.5 with php 7.3.23 on an other server and the same on a third server with php 7.4.14 again. 

> [Screen capture](https://mautic.sos-homophobie.org/asset/3:github-mautic-display-bug-report)

> I received tons of cron errors all day long, and all instances shows already 6 logs files for today only ! 

Extract from logs files : 
`[2021-01-26 01:12:10] mautic.NOTICE: PHP Notice - Undefined index: show_php_version_warning_if_under - in file /home/mautic.theatre-oeuvre.com/public_html/app/bundles/CoreBundle/Release/Metadata.php - at line 82 {"metadata":{"version":"3.0.0-beta2","stability":"beta","minimum_php_version":"7.2.21","maximum_php_version":"7.3.99","minimum_mautic_version":"3.0.0-alpha","announcement_url":""}} []`

> bin/console cache:clear does not get it back to work.

**Comment by dennisameling** [comment] 2021-01-26 13:04
Found the issue 👍🏼 When Mautic checks for updates, it fires some API requests to GitHub to get all previous releases that we did. Since we only introduced `show_php_version_warning_if_under` in 3.2.5, this triggers several PHP notices when the code loops through the previous versions from GitHub, which obviously don't have a `show_php_version_warning_if_under` key:

![image](https://user-images.githubusercontent.com/17739158/105848231-fd2e9900-5fde-11eb-9fcf-d1817029f6d0.png)

PR coming in a sec! Apologies for the inconvenience everyone 🐛

**Comment by dennisameling** [comment] 2021-01-26 13:14
Fixed in https://github.com/mautic/mautic/pull/9622, please test it if you have a minute!

**Closed as completed** 2021-02-01 19:01 UTC
Labels: T1, bug, installation
