### ISSUE TITLE
Focus feature: website snapshot not working

### ISSUE THREAD

**Issue by shrinet** [mautic/mautic#7547] opened 2019-05-21 12:26 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am still getting snapshot issue, some time its working, some times not. I was trying to get snapshot for URL https://www.maxvisionsolutions.com and it responds with very old contents and if I change URL with https://www.maxvisionsolutions.com/magento-development it completely fails

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 7.0
| Browser | chrome

### Steps to reproduce
1. Go to Channels > Focus Items > New
2. In builder enter the URL to grab snapshot.
 
### Log errors
No error

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by r-martins** [comment] 2019-11-26 22:49
Duplicates #7925

**Comment by RCheesley** [comment] 2020-01-10 16:13
Closing as a duplicate of #7179 - please move the conversation to that issue.

**Closed by RCheesley** 2020-01-10 16:13 UTC
Labels: Bug
