### ISSUE TITLE
Contact import is not merging based on more than one unique identifier fields

### ISSUE THREAD

**Issue by WaldemarOrobanche** [mautic/mautic#8948] opened 2020-06-25 14:15 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Trying to upload contacts via CSV, but it is not merging data based on more than one unique identifier fields. It just merge them into one.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.1 
| Browser | any

### Steps to reproduce
1. Make more then one custom fields for contacts and choose "unique identifier" for them;
2. Upload CSV file to Contacts;
3. No merged contacts according to the defined unique identifiers, it merged them into one contact.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-07-01 06:26
Closing as a duplicate of #7316

**Comment by WaldemarOrobanche** [comment] 2020-07-08 16:09
But it's not company import, it's contact import!

**Comment by RCheesley** [comment] 2020-07-08 16:19
@WaldemarOrobanche sorry it seems like this is the same root cause with the import so I'd suggest centralising the discussions on the first post which I will adapt to show it also relates to companies.

As we are only providing fixes for Mautic 3.x going forward, can you confirm (on #7316) if this issue continues in Mautic 3.0.1? Thanks!

**Comment by WaldemarOrobanche** [comment] 2020-07-08 16:31
The bug belongs to the `LeadModel` and to the `LeadRepository` classes. It is similar but not the same.

**Comment by WaldemarOrobanche** [comment] 2020-07-08 17:28
The part of a code that belongs to the bug is the same. So, I can say that it still exist at 3.0.1 version.

https://github.com/mautic/mautic/blob/483d21b7060ed1ce19fdb7ddc1b4d43d1751a8d2/app/bundles/LeadBundle/Entity/LeadRepository.php#L196-L199

https://github.com/mautic/mautic/blob/483d21b7060ed1ce19fdb7ddc1b4d43d1751a8d2/app/bundles/LeadBundle/Model/LeadModel.php#L971

**Comment by RCheesley** [comment] 2020-07-08 17:35
OK thanks for checking, would you like to look into making a PR to address the issue and then we can get it fixed maybe in the 3.0.2 release at the end of July? If it is indeed a completely separate issue to the bug with companies let's re-open the issue.

**Comment by RCheesley** [comment] 2020-08-16 16:05
Closing due to no feedback on the linked PR where it was not possible to reproduce the issue.

**Comment by dennisameling** [comment] 2021-05-03 19:13
Re-opening for now as https://github.com/mautic/mautic/pull/9452 will fix this issue. When the PR is merged this issue will automatically be closed 👍🏼

**Closed as completed** 2021-05-14 06:54 UTC
Labels: T1, bug, pending-feedback
