### ISSUE TITLE
Database columns referenced using camel case instead of snake case

### ISSUE THREAD

**Issue by mikemathewson** [mautic/mautic#8120] opened 2019-11-12 18:44 UTC
| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.1

### Steps to reproduce
1. Go to `/s/companies` and search for `is:mine`
2. This results in a 500 error because it is using the field name `createdAt` instead of `created_at`. The same is true for the other filters as well, i.e. `is:published`
 
### Log errors
`mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(comp.id) as count FROM companies comp WHERE comp.createdBy = ?' with params [2]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.createdBy' in 'where clause'"`

**Comment by jonathands** [comment] 2019-11-13 12:48
this seems to be related to https://github.com/mautic/mautic/issues/7597 as  Mautic\CampaignBundle\Entity\Campaign seems to have the opposite problem

**Comment by RCheesley** [comment] 2020-07-07 19:47
Good catch! Was able to reproduce on Mautic 3.0.1 - took a long time and yielded no results, error in the log:

`
[2020-07-07 20:45:15] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(comp.id) as count FROM mau_companies comp WHERE comp.createdBy = ?' with params [2]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.createdBy' in 'where clause'" at /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT COUNT(comp.id) as count FROM mau_companies comp WHERE comp.createdBy = ?' with params [2]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.createdBy' in 'where clause' at /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.createdBy' in 'where clause' at /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.createdBy' in 'where clause' at /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
`

@jonathands would you consider making a PR to address this issue?

**Comment by escopecz** [comment] 2020-10-28 17:10
Fixed by https://github.com/mautic/mautic/pull/9343

**Closed** 2020-11-04 08:41 UTC
Labels: T1, bug, hacktoberfest, mautic-3, ready-to-test
