### ISSUE TITLE
Unable to translate version 5.1 [mautic.core.update.archive_no_such_file]

### ISSUE THREAD

**Issue by soucosmo** [mautic/mautic#14282] opened 2024-11-22 20:27 UTC
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

I can't change the language of mautic, my installation is via composer, I'm using version 5.1.
![image](https://github.com/user-attachments/assets/e13bb4d3-cdc4-44a9-8908-c1bcc48e8716)

### How can we reproduce this issue?

Step 1: Settings
Sep 2: System settings
Step 3: System Defaults
Step 4: I change the language to Brazilian Portuguese (the same happens with Portuguese from Portugal, I haven't tested other languages)
Step 5: I click save or save and close

### Relevant log output

```shell
mautic.core.update.archive_no_such_file
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by shinde-rahul** [comment] 2024-11-25 13:10
@soucosmo, I followed the following steps but was unable to reproduce them.
1. `composer create-project mautic/recommended-project:5.x-dev  composer-mautic` 
2. Complete the installation
3. Post installation, browse, and log in as `admin` in the app
5. Navigated to Configuration. I switched the languages multiple times
6. No Error.

Did I miss something here?

**Comment by soucosmo** [comment] 2024-11-25 14:12
> @soucosmo, I followed the following steps but was unable to reproduce them.
> 
> 1. `composer create-project mautic/recommended-project:5.x-dev  composer-mautic`
> 2. Complete the installation
> 3. Post installation, browse, and log in as `admin` in the app
> 4. Navigated to Configuration. I switched the languages multiple times
> 5. No Error.
> 
> Did I miss something here?

I believe the difference is in the installation command, in my case I used:
composer create-project mautic/recommended-project:^5 /var/www/html/mautic5.1 --no-interaction

**Comment by shinde-rahul** [comment] 2024-11-25 14:16
I also used `composer create-project mautic/recommended-project:^5 /var/www/html/mautic5.1 --no-interaction`. And no luck reproducing, though the composer installation does not have a difference.

**Comment by soucosmo** [comment] 2024-11-29 01:17
It's quite strange, I solved the problem by downloading and installing the translation manually, I didn't check the code, but it could be that when downloading the update automatically there is a problem with the permissions, I'm using it with nginx and php fpm, do you have anything to suggest in this case?

**Comment by RCheesley** [comment] 2024-12-02 12:04
Did you clear the cache after you updated the language setting? I'm going to close this one as it can't be reproduced. Thanks @shinde-rahul for the troubleshooting!

**Closed as not planned by RCheesley** 2024-12-02 12:04 UTC
Labels: bug, needs-triage
