### ISSUE TITLE
Edit of a Lead not working

### ISSUE THREAD

**Issue by niklausmoser** [mautic/mautic#1398] opened 2016-02-02 09:07 UTC
Edit of a lead is not working - we assume it is due to the translation of a lead-flield.

[2016-01-26 13:07:20] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /data/mautic-prd/app/bundles/LeadBundle/Views/Lead/form.html.php
 on line 136 and defined - in file /data/mautic-prd/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php - at line 162 [] []

[2016-01-26 13:07:20] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::searchAndRenderBlock() must be an instance of Symfony\Component\Form\FormView, null given, called in /data/mautic-prd/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php
 on line 164 and defined - in file /data/mautic-prd/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 165 [] []

[2016-01-26 13:07:20] mautic.ERROR: Fatal: Call to a member function isRendered() on null - in file /data/mautic-prd/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 169 [] []

**Comment by escopecz** [comment] 2016-02-05 13:11
Would it be possible to provide steps to recreate?

**Comment by niklausmoser** [comment] 2016-02-05 13:25
Renamed the fields to German down to the database – e.g. “Veranstaltung” instead of “Event” and so on. Hope this helps.

Best
Niklaus

**Comment by escopecz** [comment] 2016-02-05 15:10
There is no lead field called "Event" by default. I don't know German so it makes it hard to find the problem. If you could provide something little more specific which I could replicate and get the error, I can fix it.

**Comment by camenisch** [comment] 2016-02-08 19:42
we have translated all the lead fields to german. the "event" field was a custom field. Maybe the translation has nothing to do with the error.

the problem happens when we click on "Edit Lead". The application stays on the normal lead overview page and writes the error above.

**Comment by escopecz** [comment] 2016-02-08 19:55
Well, it's hard to fix something that a developer cannot recreate. If you by chance discover what is the source of the problem, please, share it with us.

**Comment by NetBLOKS** [comment] 2016-04-27 14:34
Hi,

same problem here, maybe the error messages help.
When I try to edit an existing lead, I get the following error messages:

[2016-04-27 14:10:12] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 14:10:12] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 14:10:12] mautic.NOTICE: PHP Notice: Trying to get property of non-object - in file /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php - at line 136 [] []
[2016-04-27 14:10:12] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php on line 136 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php - at line 162 [] []
[2016-04-27 14:10:12] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::searchAndRenderBlock() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php on line 164 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 165 [] []
[2016-04-27 14:10:12] mautic.ERROR: Fatal: Call to a member function isRendered() on null - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 169 [] []

System 	Linux mautic.sm.local 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
Build Date 	Apr 2 2016 07:56:12
Server API 	FPM/FastCGI 

Let me know, if you need anything else.

Thanks and best regards,
Marcel

**Comment by NetBLOKS** [comment] 2016-04-27 14:37
Now even when I try to add a new lead:

[2016-04-27 14:35:39] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 14:35:39] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 14:35:39] mautic.NOTICE: PHP Notice: Trying to get property of non-object - in file /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php - at line 136 [] []
[2016-04-27 14:35:39] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php on line 136 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php - at line 162 [] []
[2016-04-27 14:35:39] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::searchAndRenderBlock() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php on line 164 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 165 [] []
[2016-04-27 14:35:39] mautic.ERROR: Fatal: Call to a member function isRendered() on null - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 169 [] []

**Comment by NetBLOKS** [comment] 2016-04-27 15:01
This happens when I add a new lead by Quick-Add:

[2016-04-27 14:59:59] mautic.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): Failed to parse time string (28/12/15) at position 0 (2): Unexpected character" at /usr/share/nginx/myMautic/public_html/app/bundles/CoreBundle/Helper/DateTimeHelper.php line 87 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (28/12/15) at position 0 (2): Unexpected character at /usr/share/nginx/myMautic/public_html/app/bundles/CoreBundle/Helper/DateTimeHelper.php:87)"} []
[2016-04-27 14:59:59] mautic.ERROR: Fatal: DateTime::__construct(): Failed to parse time string (28/12/15) at position 0 (2): Unexpected character - in file /usr/share/nginx/myMautic/public_html/app/bundles/CoreBundle/Helper/DateTimeHelper.php - at line 87 [] []

**Comment by escopecz** [comment] 2016-04-27 15:06
Try to test https://github.com/mautic/mautic/pull/1626 if it helps or wait for Mautic 1.4 which will be released soon and will contain that fix.

**Comment by NetBLOKS** [comment] 2016-04-27 15:16
Thanks a lot for the fast reply.
Does that mean, I shoud change the 4 files like #1626 says?
What´s meant by PR?

**Comment by escopecz** [comment] 2016-04-27 15:34
PR stands for Pull Request in the GitHub world :)

Yes, if you'd change the particular rows as the PR says, then it should at least solve the DateTime error.

**Comment by NetBLOKS** [comment] 2016-04-27 15:44
:-D I´m no programmer, so when I want to sync these files to my Mautic, I´d do something like:
git clone https://github.com/mautic/mautic.git /usr/share/nginx/myMautic/public_html
?
Thanks for your patience.

**Comment by escopecz** [comment] 2016-04-27 15:48
I'm afraid you'll have to copy-paste the code. You'd have to run the GitHub version of Mautic which is not recommended for productions sites, but for development. If you'd want to read more about testing a PR, here's how: https://github.com/mautic/mautic#how-to-test-a-pull-request

**Comment by NetBLOKS** [comment] 2016-04-27 16:00
Thanks a lot, I´ll try copy/pasting and will report back!

**Comment by NetBLOKS** [comment] 2016-04-27 16:46
I replaced the files with the new ones, still same error when trying to add a lead:

[2016-04-27 16:44:07] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 16:44:07] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 16:44:07] mautic.NOTICE: PHP Notice: Trying to get property of non-object - in file /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php - at line 136 [] []
[2016-04-27 16:44:07] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php on line 136 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php - at line 162 [] []
[2016-04-27 16:44:07] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::searchAndRenderBlock() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php on line 164 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 165 [] []
[2016-04-27 16:44:07] mautic.ERROR: Fatal: Call to a member function isRendered() on null - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 169 [] []

and when trying to edit a lead:
[2016-04-27 16:45:46] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 16:45:46] mautic.NOTICE: PHP Notice: Undefined index: state - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormView.php - at line 108 [] []
[2016-04-27 16:45:46] mautic.NOTICE: PHP Notice: Trying to get property of non-object - in file /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php - at line 136 [] []
[2016-04-27 16:45:46] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/app/bundles/LeadBundle/Views/Lead/form.html.php on line 136 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php - at line 162 [] []
[2016-04-27 16:45:46] mautic.ERROR: PHP Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::searchAndRenderBlock() must be an instance of Symfony\Component\Form\FormView, null given, called in /usr/share/nginx/myMautic/public_html/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/Helper/FormHelper.php on line 164 and defined - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 165 [] []
[2016-04-27 16:45:46] mautic.ERROR: Fatal: Call to a member function isRendered() on null - in file /usr/share/nginx/myMautic/public_html/vendor/symfony/form/Symfony/Component/Form/FormRenderer.php - at line 169 [] []

**Comment by escopecz** [comment] 2016-04-27 17:10
The DateTime error is gone, but it appears you have some problem with the **state** field. I cannot reproduce this issue. Do you have some idea how did you accomplished it?

**Comment by NetBLOKS** [comment] 2016-04-27 18:07
Hi John,
I think it started with the Installation and activation of the mautic API.
I followed you guide:
http://johnlinhart.com/blog/implementing-mautic-api
but since composer require mautic/api-library got an stability error I installed it via
composer require mautic/api-library @dev
Maybe there the problem is related.

**Comment by escopecz** [comment] 2016-04-27 18:14
I don't think it will be linked with the API. The lead detail tries to load a state field which does not exist somewhere. Did you change some lead field configuration? Or maybe you saved some odd value to the state field via API which is causing the issue. I'd guess something like it.

**Comment by NetBLOKS** [comment] 2016-04-28 13:04
Here is what we did:
For our leads we created new fields with different types. Most of them text, two boolean and two dates.
After that we exported leads from Excel to CSV and imported those leads in Mautic.

The leads were successfully imported and displayed correct. What we could see is that the Creation Date of a lead which should be filled out by an imported date field was set to the import date rather than the date from CSV.

After that we cannot edit a lead any more.

**Comment by vasco** [comment] 2016-10-07 09:52
I had this problem when we upgraded to 2.2.0

(same error log messages as the ones reported by @NetBLOKS )

We noticed that for each reported field ("undefined index: <field>") that field was "Unpublished" in the "Custom Fields" section.

In order to overcome this issue/bug we published all the fields and everything has started to work again.

**Comment by alanhartless** [comment] 2016-10-11 04:36
@vasco What fields were unpublished?

**Comment by vasco** [comment] 2016-10-11 08:43
We have 2 Mautic instances (that were upgraded to 2.2.0), both of them required that all the fields that Matic provides "out-of-the-box" were published.

In our Mautic instance #1, we had unpublished (we published them now to overcome this issue):

- title
- locale
- mobile
- fax
- segment
- pintrest
- snapchat

In our Mautic instance #2, we had unpublished (we published them now to overcome this issue):

- title
- mobile
- address line 1
- address line 2

**Comment by ayrad** [comment] 2016-10-21 21:48
Hi friends :)

Unpublishing custom fields, causes the following error(s), when trying to edit a contact:
`[2016-10-21 23:43:16] mautic.NOTICE: PHP Notice: Undefined index: language - in file /vendor/symfony/form/FormView.php - at line 102 [] []
[2016-10-21 23:43:16] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function isRendered() on null" at /app/bundles/LeadBundle/Views/Lead/form.html.php line 215 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function isRendered() on null at /app/bundles/LeadBundle/Views/Lead/form.html.php:215)"} []`

In this case `language` is a custom field which we used to use in older versions of Mautic

I've sent a PR that fixes this, I hope it helps (#2802)

**Closed** 2016-12-20 15:16 UTC
Labels: Bug
