### ISSUE TITLE
Allow contact imports from the CLI

### ISSUE THREAD

**Issue by techclovedev** [mautic/mautic#2386] opened 2016-08-25 07:07 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Feature request
| Enhancement? | 

## Description:
The more details the better...
Importing large amount of contacts causes frequent failures from the front end. (10K+). Allow imports via a scheduled cron. Also allow monitoring of queue statuses to allow for restarts and logs to view failures.
Create a forgiving process that logs failed contacts and proceeds with others.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 1.4
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ipso** [comment] 2016-08-25 15:03
Scheduling seems like a little overkill considering cron already exists. A simple CLI script that triggers the import (combined with a mapping file to map the columns/fields) definitely would be nice though.

**Comment by alanhartless** [comment] 2016-08-25 18:15
Duplicate of #1642

**Closed by alanhartless** 2016-08-25 18:15 UTC
Labels: Feature Request

**Comment by ldrrp** [comment] 2016-08-25 19:59
I have imported 40000 contacts at once before, Never had issues. You might wana consider leaving the LIMIT at a low number. This will do the list in segments without crashing it. Give it a try.

![image](https://cloud.githubusercontent.com/assets/985837/17983887/d4b52544-6adc-11e6-9183-1b51e09da93e.png)
