### ISSUE TITLE
Merging Contacts give 500 Error

### ISSUE THREAD

**Issue by sambarnes90** [mautic/mautic#3001] opened 2016-11-25 13:58 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I was trying to merge an anonymous contact with an existing contact.

When accessing the Merge option within the anonymous contact's profile, I initially was shown the standard filter menu as usual.

However, as I attempted to filter to try and find the contact I needed to merge it with, the window showed a 500 error and I haven't managed to get it working again since.

Tried removing the cache and starting again, but still no luck, showing the 500 error every time.

![image](https://cloud.githubusercontent.com/assets/12860024/20627271/db197b1a-b316-11e6-8265-3dff20a00de9.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.10-1
| MySQL version | mysqlnd 5.0.12-dev

### Steps to reproduce:
1. Access an anonymous contact.
2. Click the arrow at the top right and select "Merge".
3. The pop up window shown gives me a 500 error.
 
### Log errors: 

The log in Mautic shows:

`[2016-11-25 13:43:58] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT COUNT(DISTINCT(l.id)) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id INNER JOIN lead_ips_xref ip_lead ON l.id = ip_lead.lead_id INNER JOIN ip_addresses ip ON ip_lead.ip_id = ip.id WHERE (ip.ip_address LIKE ?) AND ((l.date_identified IS NOT NULL) AND (l.id <> ?) AND (()))' with params ["87.114.104.106%", 143794]:  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))' at line 1" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT COUNT(DISTINCT(l.id)) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id INNER JOIN lead_ips_xref ip_lead ON l.id = ip_lead.lead_id INNER JOIN ip_addresses ip ON ip_lead.ip_id = ip.id WHERE (ip.ip_address LIKE ?) AND ((l.date_identified IS NOT NULL) AND (l.id <> ?) AND (()))' with params [\"87.114.104.106%\", 143794]:\n\nYou have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException(code: 0): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:94)"} []`

There is **definitely** nothing in the MySQL error log.

**Comment by igormedeiros** [comment] 2017-01-02 17:45
+1

**Comment by mqueme** [comment] 2017-03-28 10:18
This works in new version 2.7.1

**Comment by github-grabaz** [comment] 2017-04-18 02:08
I just ran into this error and I am running version 2.7.1.  Why is it closed?  What was done to fix it?

It looks like the milestone was changed from 2.7.1 to 2.8.0 on Mar 13.

**Comment by escopecz** [comment] 2017-04-18 06:41
The problem is that the devs are not able to replicate it. Could you provide steps to replicate it? Does it happen with some special contacts only? If so, how are they special? Or did it start happening when you added some custom field?

**Comment by github-grabaz** [comment] 2017-04-28 19:08
I just ran into the problem again when merging two contacts.  I have a custom field marked as unique in Mautic and the two contacts each had values in this field. I was able to merge them after deleting the custom field in one of the contacts.

**Comment by escopecz** [comment] 2017-05-02 07:42
@github-grabaz could you write steps to replicate the issue, please? What field type was it? What were the values the contacts had?

**Comment by github-grabaz** [comment] 2017-05-03 08:28
Sorry didn't see your response until now.  The unique field added was an integer field created to hold vtiger ids.  I had a duplicate in vtiger that was imported into mautic.  The contacts failed to merge when both contacts had a value stored in the unique field.  When I deleted the value from one of the contacts the merge succeeded.  I will verify again tomorrow.  P.S. The Twitter duplicates issue is more important for my job.

**Comment by github-grabaz** [comment] 2017-05-03 17:15
I just created a new test install of Mautic from the github repository.  The first test to create 2 contacts with identical information except for the unique field did not duplicate the error encountered by the production box.  Please leave open as I will continue to try to replicate the  error.

Some conditions that production has that the test environment hasn't tested yet are:
1) Create duplicates and send emails to contacts so that email related tracking is captured.
2) Create landing pages that captures updated contact information.
3) Add the contacts to active campaigns so that the contacts have scheduled follow up emails.

Give me a few days to do this.

**Comment by github-grabaz** [comment] 2017-05-19 16:23
I have run across the problem in Production again and I have kept the two records intact so that I can help diagnose this.

@escopecz  What do you want me to do to help diagnose this in a production setting?

**Comment by escopecz** [comment] 2017-05-26 12:33
We will just need the steps to replicate the issue so we could find the problem and fix it.

**Closed** 2017-11-27 15:52 UTC
Labels: Backlog, Bug
