### ISSUE TITLE
Field Values returned a [object Object]

### ISSUE THREAD

**Issue by auroralabs** [mautic/mautic#4323] opened 2017-06-29 09:58 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
In the campiagn builder when I select Conditions > Form Field Value
Limit to Forms: Choose form
Field: Select the Drop List Field
Operator: equals
Values: When I try to select a value I am greeted with [object Object] for both of the choices so do bot know which is which.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.8.0
| PHP version | 5.6.30

### Steps to reproduce:
1. Campiagns New
2. launch campiagn Builder
3. Conditions > Form Field Value
4. Limit to Forms: Choose form
5. Field: Select the Drop List Field
6. Operator: equals
7. Values: When I try to select a value I am greeted with [object Object] for both of the choices so do bot know which is which.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 
<img width="512" alt="untitled_1024" src="https://user-images.githubusercontent.com/1214196/27682234-25315a38-5cc2-11e7-978f-1505ec035a84.png">

**Comment by escopecz** [comment] 2017-07-03 09:03
Could you please retest on 2.8.2 or 2.9.0 (to be released soon)? There were fixes in this area. I'll close this for now until you confirm the issue is happening on the latest release too.

**Comment by auroralabs** [comment] 2017-07-03 14:05
Hi,
I have just upgraded to 2.8.2 and the same issue. I am still getting [object Object]

**Closed** 2017-07-28 09:07 UTC
Labels: Bug, Ready To Test
