### ISSUE TITLE
Bug - Forms combined into one after clone

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1738] opened 2016-05-12 17:44 UTC
I had a clone combine into a preexisting form.

## Steps to reproduce
I had a preexisting campaign form ID 2
Created a second campaign form id 7
Put campaign form 7 into a campaign. 
Cloned campaign form to a standalone form id 8
deleted campaign form id 7
cloned standalone form into campaign form (This combined into my form ID 2) that has nothing to do with anything else.

Now i have a form with two submits buttons. I went into the database and deleted the extra submit.

![image](https://cloud.githubusercontent.com/assets/985837/15224473/8635c96a-1847-11e6-8f99-18f851e3263a.png)

**Comment by ldrrp** [comment] 2016-05-12 17:45
Also not noted in the image, but i already deleted the extra form fields from the other form that was cloned. If you were wondering what i was doing. I was trying to figure out how to send a email to our support staff but also be able to add a user to a list if they checked the subscribe button in that same form.

**Comment by escopecz** [comment] 2016-05-13 06:15
What Mautic version is it?

**Comment by npracht** [comment] 2016-05-18 13:54
I have the same issue with previous version.

**Comment by alanhartless** [comment] 2016-05-18 14:30
Does this happen every time you try or is it sporadic? This issue has been around but has been a real pita to track down due to none of us devs being able to consistently reproduce. I had hoped https://github.com/mautic/mautic/pull/1697 fixed it but apparently not.

**Comment by npracht** [comment] 2016-05-18 14:34
Something like once every 5 or 6 clone. But i couldn't reproduce it with 100% success to fail...
I hoped the same...

**Comment by ldrrp** [comment] 2016-05-18 20:44
i can reproduct it about 2/5 times. Not 100% either.

**Comment by npracht** [comment] 2016-06-15 06:19
Hi @alanhartless,

We still meet this critical issue. My devs looked into it but with no result.
I met that problem again that night, it kinda erased another form, mixing buttons and fields. Very weird.

Thanks for help.

**Comment by PatchRanger** [comment] 2016-06-24 18:30
Confirming the bug in Mautic 1.4.1.

**Comment by PatchRanger** [comment] 2016-06-25 06:12
For a reference: very similar issue #1267 .

**Comment by npracht** [comment] 2016-06-25 06:44
Yes, this is definitely related. I had also issues with buttons.
@alanhartless I have @MaxWebmecanik working on that next week to try to find the solution, he'll let you know.

**Comment by MaxWebmecanik** [comment] 2016-06-30 16:10
I've found another bug with form cloning which I suspect might have something to do with this one.
See issue #1931

**Comment by npracht** [comment] 2016-08-16 08:51
Hi @alanhartless did you have the opportunity to work on it?
We spent time and time on it and we turn crazy not finding anything there.

**Comment by MaxWebmecanik** [comment] 2016-08-17 08:14
I'm almost convinced this happens because of a non-atomic DBAL query being multiple times in parallel.
This probably happens because we have some instances which suffer from significant slowdowns.
Therefore, I would imagine the user gets bored and starts doing multiple things at the same time in different tabs. At which point, the non-atomic query rears its ugly face and mayhem soon ensues.

That's my best guess

**Comment by alanhartless** [comment] 2016-08-17 23:54
@npracht @MaxWebmecanik I've come up empty. I've never been able to reproduce this to allow me the opportunity to debug what could be causing it. I did fix #1931 so I guess we'll see if that's related. 

On the non-atomic DBAL query - anything is possible with Doctrine black magic but I'm having a hard time seeing this as the reason. It's not with selecting data but persisting data; Doctrine could be somehow keeping the original associations in memory and applying them to the new fields. 

In 2.0, a change was merged via https://github.com/mautic/mautic/pull/1852 and https://github.com/mautic/mautic/commit/df173321a973833521e2f63d5cadcf55604b3bbc that forced a prefix so that the random chance that a randomly generated string isn't mistaken as an entity ID. The fact that some of these symptoms seem to be merges into completely unrelated items (like in this report) gives some solid weight to that theory.

Has this continued to occur since 2.0?

**Comment by ldrrp** [comment] 2016-08-24 15:13
I will be testing this today.

**Comment by ldrrp** [comment] 2016-08-24 15:51
Wow, so i tried installing it so that i can always have a test setup available. /installer 500 internal server error on 2.1.0

Anyone have any ideas, there is nothing in the system logs, its completely blank.

**Comment by ldrrp** [comment] 2016-08-24 16:05
I was not able to replicate it 3 times on 2.1.0, Has anyone else had any troubles. I know this one is intermittent.

Using PHP 7

**Comment by alanhartless** [comment] 2016-08-25 15:05
I haven't seen this since 2.0 - cross my fingers - it's fixed with the changes noted in https://github.com/mautic/mautic/issues/1738#issuecomment-240584769. I'm going to close this for now. But if anyone has this happen under 2.1.1, definitely let us know!

**Closed by alanhartless** 2016-08-25 15:05 UTC
Labels: Bug, Pending Feedback

**Comment by ldrrp** [comment] 2016-08-25 15:07
Sounds good, Thanks for all the help.
