### ISSUE TITLE
Exchange 365 Email Provider with Bounce/Complaint Support

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1741] opened 2016-05-13 14:31 UTC
## Description
Using Microsoft Exchange through SMTP for Sending Mails ist not possible in combination with bounce / complaint handling support. As of today Exchange does NOT allow/support disposable "+" email addresses like account+disposable_part@mydomain.com

## Steps to solve
- look for an alternative way to track bounces without dispoable "+" part.
- allow sending email without +disposable part while still monitoring inbox e.g. by using email headers.
- allow monitoring a shared email account for bounces/complaints

## Implementation Feedback and Ideas
I'd probably be able to implement this, however I'd be interested in your feedback, if you think bounce handling is possible without the disposable + part which exchange does not support. Also I'd be very happy about feedback on how you would implement this and there to start on the mautic code (I'm new to mautic)

Thx, I'd really appreciate your help!

**Comment by escopecz** [comment] 2016-08-17 12:53
Duplicate of https://github.com/mautic/mautic/issues/1540

**Closed by escopecz** 2016-08-17 12:53 UTC
