### ISSUE TITLE
Add select option to custom contact field return 500 error

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#12154] opened 2023-04-02 04:31 UTC
### Mautic Version

5.0.x series

### PHP version

8.0

### What happened?

Add select option to custom contact field return 500 error

### How can we reproduce this issue?

Step 1:  Create select field and add option

### Relevant log output

```shell
`Uncaught PHP Exception ErrorException: "PHP Warning - Undefined array key "list"" at /var/www/html/app/bundles/LeadBundle/Form/Type/FieldType.php line 257`
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment] 2023-06-18 10:34
Hi @kuzmany - I just tried with M5 and PHP8 and had no issues with either custom contact field type "select" and "select multiple". Could you please try again or be more specific about your steps?

**Comment by dsp76** [comment] 2023-06-18 11:34
Looks like a duplicate of https://github.com/mautic/mautic/issues/12208 ?? I know yours was earlier @kuzmany - but the other got more traction. Will close this one in favor of #12208 ... please let me know if thats wrong.

**Closed as completed by dsp76** 2023-06-18 11:34 UTC
Labels: bug, duplicate
