### ISSUE TITLE
Cannot make changes in any form - v. 4.0.1

### ISSUE THREAD

**Issue by aukera-labs** [mautic/mautic#10544] opened 2021-10-20 08:09 UTC
### Mautic Version

4.0.0

### PHP version

7.4.24

### What browsers are you seeing the problem on?

Chrome

### What happened?

Mautic version 4.0.1
Cannot make changes in any form (campaign or standalone), when it was created with the "Render style from Template" option in "No".
Every time I try to make a change in any of these forms, I see a 500 Internal Server Error. 

![image](https://user-images.githubusercontent.com/37652119/138052787-1acc4cbe-7d7c-4502-b195-a736cb8c5484.png)

### How can we reproduce this issue?

Step 1: Create a form, choosing "No" in the "Render style from Template" option.
Step 2: Save it
Step 3: Try to make any change in that form. 

### Relevant log output

```shell
[2021-10-20 09:38:45] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "null or string", "boolean" given" at /home/REDACTED/public_html/mautic/vendor/symfony/form/Extension/Core/DataMapper/RadioListMapper.php line 49 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"null or string\", \"boolean\" given at /home/REDACTED/public_html/mautic/vendor/symfony/form/Extension/Core/DataMapper/RadioListMapper.php:49)"} []
[2021-10-20 09:44:29] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "null or string", "boolean" given" at /home/REDACTED/public_html/mautic/vendor/symfony/form/Extension/Core/DataMapper/RadioListMapper.php line 49 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"null or string\", \"boolean\" given at /home/REDACTED/public_html/mautic/vendor/symfony/form/Extension/Core/DataMapper/RadioListMapper.php:49)"} []
[2021-10-20 10:02:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "null or string", "boolean" given" at /home/REDACTED/public_html/mautic/vendor/symfony/form/Extension/Core/DataMapper/RadioListMapper.php line 49 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"null or string\", \"boolean\" given at /home/REDACTED/public_html/mautic/vendor/symfony/form/Extension/Core/DataMapper/RadioListMapper.php:49)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by aukera-labs** [comment] 2021-10-20 08:27
Also, if you create a form choosing "No" in "Render style from template", but change it to "Yes" at any moment, if you try to make changes afterwards, will find the same problem.

**Comment by RCheesley** [comment] 2021-10-20 09:03
Hi @aukera-labs thanks for letting us know about this bug. We are already tracking it in https://github.com/mautic/mautic/issues/10453 so I will close this PR as a duplicate of that issue.

**Closed as completed by RCheesley** 2021-10-20 09:03 UTC
Labels: bug, duplicate, needs-triage
