### ISSUE TITLE
Freegeoip timeout causing loading problems

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1583] opened 2016-04-08 07:13 UTC
## Description
Mautic v1.3.1

connections to Freegeoip service are timing out and it's causing the following issues.
For browsers not authenticated as mautic user(all leads):

- Assets don't load properly
- View in browser causes delayed loading then eventual 500 Internal Server Error

These log events are generated
> [2016-04-08 07:01:19] mautic.WARNING: IP LOOKUP: Failed to connect to freegeoip.net port 80: Connection timed out [] []

> [2016-04-08 07:01:19] mautic.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" at /home/cpsuper/public_html/sites/subdomain/sub-subdomain/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1044 {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at /home/cpsuper/public_html/sites/subdomain/sub-subdomain/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1044)"} []

## Steps to reproduce
When mautic server is unable to connect to freegeoip.net (it was offline at the time of diagnosing this fault), have it selected as the lookup source for IP addresses.

## Steps to work around
Changed IP lookup to MaxMind GeoLite2 City Download

**Comment by escopecz** [comment] 2016-04-24 14:18
I think this is duplicate of https://github.com/mautic/mautic/issues/1559

**Closed by escopecz** 2016-04-24 14:18 UTC
