### ISSUE TITLE
upload field

### ISSUE THREAD

**Issue by maeva123** [mautic/mautic#3846] opened 2017-04-12 12:04 UTC
Hi,

Please I should add a file upload to a form in mautic but I could'n find any plugin and I don't know if the right way is to add a fieldType like symfony does. pleaaase help !!

**Comment by escopecz** [comment] 2017-04-12 12:26
Duplicate of https://github.com/mautic/mautic/issues/221

**Closed by escopecz** 2017-04-12 12:26 UTC
