### ISSUE TITLE
When adding "unsubscribed" to an emails report the report errors out

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4992] opened 2017-09-21 19:18 UTC
What type of report is this:Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
(SAA) When adding "unsubscribed" to an emails report the report errors out

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment] 2017-09-22 06:52
Duplicate of https://github.com/mautic/mautic/issues/4704

**Closed** 2017-09-27 07:22 UTC
Labels: Bug, P2

**Comment by escopecz** [comment] 2017-09-27 08:36
Please answer all the questions in the issue template next time. I cannot replicate on Mautic 2.10.1. What is your version?

**Comment by npracht** [comment] 2017-09-27 08:58
@escopecz it is very the same ad #4704 as i mentionned and https://github.com/mautic/mautic/pull/4995 solves it (just tested) :-)

**Comment by escopecz** [comment] 2017-09-27 09:07
It's not quite the same. This is about unsubscribed column, #4704 is about unsubscribed ratio column. I was able to replicate it only when the report is grouped by some column which is missing in the steps to replicate.
