### ISSUE TITLE
Allow filtering by tag in reports

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#3312] opened 2017-01-28 19:48 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
Contacts can have tags associated with them, but it is not available in the reporting views etc so can't really be used for reporting.

Please can we consider adding this feature?

**Comment by escopecz** [comment] 2017-02-03 21:37
Possibly duplicate of https://github.com/mautic/mautic/issues/995, but this PR should be a solution for this: https://github.com/mautic/mautic/pull/3134

**Closed by escopecz** 2017-02-03 21:37 UTC
