### ISSUE TITLE
Trigger Action On Email Reply

### ISSUE THREAD

**Issue by renegademarketer** [mautic/mautic#5150] opened 2017-10-14 09:05 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | A
| Enhancement? | 

## Description:
It would be useful to be able to trigger an action in the campaign builder when a lead replies by email. The action should be triggered when sent to a specific email address or has a specific subject line.

One use of this is to have leads reply by email and then Mautic sends them a lead magnet. 

The email reply is extremely useful because most email service providers will automatically white label the address an email sent to. This means a higher delivery rate and better inboxing on Gmail hopefully bypassing the Promotional box.

This is such a successful technique that several of the big ESPs offer this option now, Additionally, there are reply by email opt-in forms specifically for this.

**Comment by kuzmany** [comment] 2017-10-15 22:17
In progress https://github.com/mautic/mautic/pull/4750

**Comment by alanhartless** [comment] 2017-10-26 15:49
Duplicate of #4773 and in progress in #5194

**Closed by alanhartless** 2017-10-26 15:49 UTC
Labels: Feature Request, WIP
