### ISSUE TITLE
Error 500 when clicking in settings &gt; themes 

### ISSUE THREAD

**Issue by lenonleite** [mautic/mautic#12351] opened 2023-05-16 10:09 UTC
### Mautic Version

5.0.x series

### PHP version

8.0.27

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

When I click on settings > themes it doesn't work.

[image](https://github.com/mautic/mautic/assets/218436/5df7c372-0ab2-44d6-acc3-dce51d43cdad)

Error 500 is reported:

_Short_

 mautic.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "MauticCoreBundle:Theme:index.html.twig"

==========================================================================

_Full_

[2023-05-16 09:51:09] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "MauticCoreBundle:Theme:index.html.twig" (looked into: /shared/httpd/puremautic/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /shared/httpd/puremautic/templates, /shared/httpd/puremautic/vendor/symfony/twig-bridge/Resources/views/Form) in "@MauticCore/Theme/list.html.twig" at line 1." at /shared/httpd/puremautic/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"MauticCoreBundle:Theme:index.html.twig\" (looked into: /shared/httpd/puremautic/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /shared/httpd/puremautic/templates, /shared/httpd/puremautic/vendor/symfony/twig-bridge/Resources/views/Form) in \"@MauticCore/Theme/list.html.twig\" at line 1. at /shared/httpd/puremautic/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} {"hostname":"php","pid":11963}

### How can we reproduce this issue?

Step 1: Click in settings > themes

[image](https://github.com/mautic/mautic/assets/218436/c7870156-e2b5-4d16-ac94-f8785137d838)

### Relevant log output

[2023-05-16 09:51:09] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "MauticCoreBundle:Theme:index.html.twig" (looked into: /shared/httpd/puremautic/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /shared/httpd/puremautic/templates, /shared/httpd/puremautic/vendor/symfony/twig-bridge/Resources/views/Form) in "@MauticCore/Theme/list.html.twig" at line 1." at /shared/httpd/puremautic/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\Error\LoaderError(code: 0): Unable to find template "MauticCoreBundle:Theme:index.html.twig" (looked into: /shared/httpd/puremautic/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /shared/httpd/puremautic/templates, /shared/httpd/puremautic/vendor/symfony/twig-bridge/Resources/views/Form) in "@MauticCore/Theme/list.html.twig" at line 1. at /shared/httpd/puremautic/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} {"hostname":"php","pid":11963}

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment] 2023-05-16 11:26
@lenonleite fix [this line](https://github.com/mautic/mautic/blob/e9746f6c312ec8839d2e5ede654fa22f9510b235/app/bundles/CoreBundle/Resources/views/Theme/list.html.twig#LL1C1-L1C55) 

It should be like this ```{% extends "@MauticCore/Theme/index.html.twig" %}```

**Comment by lenonleite** [comment] 2023-05-16 11:30
thanks, I will create a PR 
=)

**Comment by escopecz** [comment] 2023-09-07 10:33
I cannot reproduce so I guess it got fixed already. Closing. Please, reopen if there are more detailed steps to recreate this.
![Screenshot 2023-09-07 at 12 33 15](https://github.com/mautic/mautic/assets/1235442/87467c09-d19f-4cf3-b0d3-a8a684f3356b)

**Closed as completed by escopecz** 2023-09-07 10:33 UTC
Labels: T1, bug, regression, themes
