### ISSUE TITLE
Test Connection and Send Test mail infinite spinning on fresh 2.6.0

### ISSUE THREAD

**Issue by ikolubr** [mautic/mautic#3383] opened 2017-02-10 05:07 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Fresh install of 2.6.0 I can't go to the settings and test connection or test send email. It just spins indefinitely.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 7.0

### Steps to reproduce:
1. Go to Configuration page
2. Go to email setings
3. Fill the settings and try to click on Test Connection or Send Test Email
 
### Log errors: 

/app/log/
[2017-02-10 02:58:18] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []

webserver error
2017/02/09 20:49:40 [error] 23854#23854: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method setApiKey in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php on line 291" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: myserer, request: "POST /s/ajax?action=email:testEmailServerConnection&mauticUserLastActive=1&mauticLastNotificationId= HTTP/2.0", upstream: "fastcgi://127.0.0.1:9070", host: "mautic.incriveltalento.com.br", referrer: "https://url/s/config/edit"

**Comment by asrulmunir** [comment] 2017-02-11 03:28
Having the exact problem on freshly installed 2.6.

But no problem on updated 2.5.1 -> 2.6.

**Comment by asrulmunir** [comment] 2017-02-12 00:40
@ikolubr are you using NGNIX?

**Comment by ikolubr** [comment] 2017-02-12 01:32
Yes sir!

**Comment by asrulmunir** [comment] 2017-02-12 11:25
Seems like also happening on Apache :(

**Comment by Clobbe** [comment] 2017-02-12 13:05
Happens to me as well! :(

**Comment by asrulmunir** [comment] 2017-02-12 13:15
Upgraded Mautic 2.5.1 to 2.6 in Bitnami image... Same issue... 

Almost certain now it is really a bug, not server side problem.

**Comment by brycehamrick** [comment] 2017-02-13 00:44
Happening for me as well on a fresh 2.6 install on Apache, PHP 5.6. Campaign emails aren't sending either. I'm using Mailgun (via custom smtp server).

**Comment by asrulmunir** [comment] 2017-02-13 02:41
I don't have any problem sending emails, both campaign and broadcast emails are working.

**Comment by RCheesley** [comment] 2017-02-14 09:49
I've just spun up a new instance, Mautic 2.6.0 PHP version 7.0.15 installed locally.

Trying to configure with my local Mailhog SMTP and I am seeing the same.

[2017-02-14 09:41:50] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file /opt/lampp/htdocs/local.mautictest/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []
[2017-02-14 09:43:20] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file /opt/lampp/htdocs/local.mautictest/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []
[2017-02-14 09:43:55] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file /opt/lampp/htdocs/local.mautictest/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []

**Comment by escopecz** [comment] 2017-02-14 11:34
Please test https://github.com/mautic/mautic/pull/3440 and comment bellow it if it fixed the error you're getting.

**Comment by pagelab** [comment] 2017-02-14 19:22
#3440 fixed the issue for me. Thanks @escopecz.

**Comment by mbrinson** [comment] 2017-02-14 22:24
#3440 fixed the issue for me as well.

**Comment by asrulmunir** [comment] 2017-02-15 02:22
#3440 fixed the issue for me too 👍

**Comment by martinstr** [comment] 2017-02-15 09:35
the fix works here too 👍

**Comment by HasaanFazal** [comment] 2017-02-15 10:32
Yes fix worked for me as well. Lets see where the next road block is 💃

**Comment by escopecz** [comment] 2017-02-15 11:48
Thanks, guys! Your tests helped to get the fix merged faster.

**Closed by escopecz** 2017-02-15 11:48 UTC
Labels: Ready To Test

**Comment by asrulmunir** [comment] 2017-02-15 12:13
New PHP warning from log:

[2017-02-15 10:21:12] mautic.WARNING: PHP Warning - method_exists() expects exactly 2 parameters, 1 given - in file /var/www/html/mautic/app/bundles/EmailBundle/Controller/AjaxController.php - at line 232 [] []

**Comment by escopecz** [comment] 2017-02-15 12:14
@asrulmunir please copy-paste the line 232 so we can see where the problem is.

**Comment by asrulmunir** [comment] 2017-02-15 12:43
@escopecz , sorry... my bad, I wrongly commented old line using '#' instead of '//' :)

**Comment by asrulmunir** [comment] 2017-02-15 12:47
@escopecz : 

line 232 - if (method_exists([$mailer, 'setApiKey'])) {

**Comment by escopecz** [comment] 2017-02-15 12:52
Ok, remove the `[` and `]` like this: `if (method_exists($mailer, 'setApiKey')) {`

**Comment by asrulmunir** [comment] 2017-02-15 12:53
@escopecz OK, got it... Thanks :)
