### ISSUE TITLE
Mautic certain pages not clickable - javascript: void (0)

### ISSUE THREAD

**Issue by bertbossier** [mautic/mautic#8648] opened 2020-04-06 14:17 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.33
| Browser | Chrome

We tried updating to the latest version of Mautic (2.16.1), unfortunately that crashed our system (error 500) which forced us to go to a previous php version. Luckily, no files were lost and all of our data is remained.

However, since our restore, we can't click on certain elements anymore. Following elements aren't clickable anymore:

- Components
- Account
- Channels
- Points
- Account
- Settings

We are getting a javascript void:(0), so something must be wrong with Javascript I suppose? I've tried clearing all cookies, cache, changing browsers, devices, resetting Chrome... All without any luck.

Our forms however are still working and receive emails from our Mautic system. 

What should we do?

Thanks in advance.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by oytuntez** [comment] 2020-04-07 15:33
We just updated our fork to 2.16.1-beta and deployed on production this morning. We don't see this issue. "Channels" link is supposed to be `javascript void:(0)`, that's correct. But when you click, it should expand a submenu:

![image](https://user-images.githubusercontent.com/656635/78688564-6532b800-78c3-11ea-866c-e8abba91838e.png)

Try resetting/clearing your cache and JS/CSS assets. Let Mautic regenerate your JS assets.

**Comment by bertbossier** [comment] 2020-04-08 09:54
Hi @oytuntez 

How do I need to reset/clear our cache and JS/CSS assets so Mautic will regenerate it? Clearing our cache and JS asset through Chrome and Firefox makes no different. Neither does clearing the content below /app/cache. 

Elements like Channels don't expend to a submenu. 

Thanks in advance for you help.

Kind regards

Bert

**Comment by RCheesley** [comment] 2020-07-06 09:09
@bertbossier take a look at the docs here: https://docs.mautic.org/en/troubleshooting#1-clear-the-cache which explains how to clear the cache in Mautic 2.x (note that the location is var/cache in Mautic 3.x). You may also need to hard-clear your browser cache I expect - see if it is an issue in another/an incognito browser.

This kind of issue is almost always due to the cache so I am going to close it down, as it is not a bug with Mautic.

If you need support going forward the best place is at https://forum.mautic.org/c/support, rather that Github which is for reporting bugs with Mautic :)

**Closed as completed by RCheesley** 2020-07-06 09:09 UTC

**Comment by zautlan** [comment] 2024-08-02 12:34
I am a genius btw, I fixed it myself. To save you trouble, the NPM and node update will not work! Delete your website with Cyberpanel, then reinstall and install WORDPRESS and LS CACHE from Cyberpanel. Reinstall Mautic. It works NOW!
