### ISSUE TITLE
Problem with adding "+xxxx" to the email address

### ISSUE THREAD

**Issue by vihuarar** [mautic/mautic#1540] opened 2016-03-17 16:31 UTC
## Description
I have problems when sending an email with a queue....

I think that the problem is because I'm sendind emails from mensaje.automatico@domain.com (changed the domain for security)

In our microsoft exchange we have a rule, that the "mensaje.automatico" only can send message from that email... in the error that shows the log tells "Client does not have permissions to send as this sender"

I see that in some headers you use: mensaje.automatico+bounce_56ead34ec36ff@inder.gov.co

That could be the problem?

The strange thing is that when I send the message inmediately... the email is send..

I got this message in the log file:
[2016-03-17 15:55:01] mautic.WARNING: Command `mautic:send:emails` exited with status code 255 [] []
[2016-03-17 15:55:01] mautic.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Client does not have permissions to send as this sender " (uncaught exception) at /var/www/html/email-marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383 while running console command `mautic:send:emails` [] []
[2016-03-17 15:56:07] mautic.WARNING: Command `mautic:send:emails` exited with status code 255 [] []
[2016-03-17 15:56:07] mautic.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Client does not have permissions to send as this sender " (uncaught exception) at /var/www/html/email-marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383 while running console command `mautic:send:emails` [] []
[2016-03-17 15:57:07] mautic.WARNING: Command `mautic:send:emails` exited with status code 255 [] []
[2016-03-17 15:57:07] mautic.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Client does not have permissions to send as this sender " (uncaught exception) at /var/www/html/email-marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383 while running console command `mautic:send:emails` [] []
[2016-03-17 15:58:02] mautic.WARNING: Command `mautic:send:emails` exited with status code 255 [] []
[2016-03-17 15:58:03] mautic.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Client does not have permissions to send as this sender " (uncaught exception) at /var/www/html/email-marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383 while running console command `mautic:send:emails` [] []
[2016-03-17 15:59:01] mautic.WARNING: Command `mautic:send:emails` exited with status code 255 [] []
[2016-03-17 15:59:01] mautic.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Client does not have permissions to send as this sender " (uncaught exception) at /var/www/html/email-marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383 while running console command `mautic:send:emails` [] []

[body.txt](https://github.com/mautic/mautic/files/178204/body.txt)

## Steps to reproduce

**Comment by vihuarar** [comment] 2016-03-17 19:08
I check out again.. And I realized how the problem happen...

When the "Monitored Inbox Settings" is configured... I have these kind of problems.. I cant send:
-Test
-Emails queue
-Emails that are send inmediatly

but when I disable the "Monitored Inbox Settings" and I leave all the fields empty... I can send emails without problem...

I think this is related with "In our microsoft exchange we have a rule, that the "mensaje.automatico" only can send message from that email... in the error that shows the log tells "Client does not have permissions to send as this sender""

And my partner that manage infrastructure tells me that he cant change that configuration to anyone can send emails without checking if is the same account that is logged in..

**Comment by escopecz** [comment] 2016-04-07 15:20
So is the issue resolved? Can we close it? Or do you have some recommendation for Mautic?

**Comment by vihuarar** [comment] 2016-04-21 14:15
No.. is not solved... 

My default sender is mensaje.automatico@inder.gov.co

When we configure "Monitored inbox"... Mautic add some text in sender email, for example:  mensaje.automatico+bounce_56ead34ec36ff@inder.gov.co

"In our microsoft exchange we have a rule, that the "mensaje.automatico" only can send message from that email... in the error that shows the log tells "Client does not have permissions to send as this sender""

So mautic when try to send emails like "mensaje.automatico+bounce_56ead34ec36ff@inder.gov.co" it get a message from the Mail tranfer Agent.. that says that is only allow to send mesage the user mensaje.automatico

Like you would know, this is a secure good practice... for users dont supplant other users... so "mensaje.automatico" cant send messages like "victor.arango@..."

**Comment by funnyprinter** [comment] 2016-05-09 10:55
I can confirm the issue. Problem is NOT resolved as of now.

### Cause of the Problem:
Microsoft Exchange 365 does not support "disposable addresses" or "plus adresses" as Gmail calls them. As of know I it seems do not be possible to configure exchange to allow senders with a plus suffix nor it forwards these emails to the corresponding recipients. I guess other Email providers like gmail also prohibit sending with plus email adresses.

- https://community.office365.com/en-us/f/158/t/79034
- http://serverfault.com/questions/195276/does-exchange-support-plussed-users-e-g-mynamespamexample-com-or-a-similar


### Quick Fix Possiblities
- If bounce tracking is not needed, disable settings for monitored inbox
- Use another Email Sending Service eg. Amazon SES, ...

### Solution Email Tracking (TODO)
Add/allow multiple ways of email bounce tracking:
- Diposable / Plus email adresses (as implemented)
- Bounce Tracking without +suffix (not as reliable)
- Email Headers (only works if response contains copy of email headers)
- (Hidden) Text in Content (only works if response contains copy of message)

### Solution Email Configuration (TODO)
Problem, sending an Email through the "send test email" does not add the inbox monitoring changes. Thus sending test email works perfectly file while really sending emails fails. I'd rather use exactly the same email sending as for campaigns.

Really bad about the problem is that emails are not delivered with this issue even though it marks them as send successfully. I open a second Issue for that though.

@escopecz I'd recommend this changes, since I guess this problem ist not only an issue of exchange.

**Comment by PatchRanger** [comment] 2016-06-26 14:55
I confirm the issue in Mautic 1.4.1. I am getting such messages into logs:

> mautic.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550: MAIL FROM must match AUTHENTICATED USER (MAIL FROM: 550-'info+bounce_576fceed80ce6@example.com' != AUTH LOGIN: 550 'info@example.com') " (uncaught exception) at /public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383 while running console command `mautic:send:emails` [] []

That is abnormal as `From` header is definitely set correctly, I've checked it by debugging.

Looks like very much related to this Swiftmailer issue: https://github.com/swiftmailer/swiftmailer/issues/384 - I guess, setting `Return-path` header somehow takes precedence and influences the recognition of sender with `From` header correctly set.

**Comment by escopecz** [comment] 2016-09-29 12:35
Fixed in https://github.com/mautic/mautic/pull/2312

**Closed by escopecz** 2016-09-29 12:35 UTC
Labels: Feature Request
