### ISSUE TITLE
master composer install problem missing

### ISSUE THREAD

**Issue by olissongs** [mautic/mautic#8121] opened 2019-11-12 20:51 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

## Bug Description
testet today 

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2
| Browser | php cli 7.2.24

### Steps to reproduce
1. downloaded zip from github master
2. composer install
 
### Log errors
Composer Errors

[RuntimeException]                                                                                                  
  /var/www/vhosts/.../vendor/doctrine/lexer does not exist and could not be created. 

[RuntimeException]                                                                                                          
  /var/www/vhosts/.../vendor/mtdowling/jmespath.php does not exist and could not be created. 

My Solution, copied missing files from an mautic backup
run composer install again
worked

so i am not firm which package is meant, but i think it could be fixed adding it in the composer.json file

[//]: # ( Invisible comment:

**Comment by RCheesley** [comment] 2020-07-07 19:53
I am not able to reproduce this in Mautic 3.0.1 so closing the issue.

**Closed by RCheesley** 2020-07-07 19:53 UTC
