### ISSUE TITLE
Tracking gif only registers a few Page Hits, then ignores the rest... useless 404 not found errors?

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#267] opened 2015-04-06 00:28 UTC
Not sure if these two are related, but we suspect that the 404 errors in the log file are the reason for some Page Hits not being registered properly.

Here's a sample line (there are 5-20+ of these per hour) from our log file:

>[2015-04-02 14:03:34] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Sorry! The requested URL was not found." at /www_dev/httpdocs/PROD/mautic/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 151 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Sorry! The requested URL was not found. at /www_dev/httpdocs/PROD/mautic/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:151)"} []

This error message doesn't tell us *ANYTHING* useful, just pollutes the log file and uses up HD space so it would be nice if it also reported the actual *URL* being requested and which has failed (no route found for it?)

What we've also observed is that a new anonymous Lead is being tracked with the tracking gif but only the first few page hits are saved into mysql and reported for the Lead ... no matter what that user does afterwards (may browser to many more pages or close the browser altogether) the lead details page shows the last recorded page as being still opened (accumulating its viewing time). No further Page Hits are being reported for the same user/browser ... however, if another browser window is opened (say, was using Chrome then switched to IE) then few more Page Hits from the new browser are recorded and they do stop just the same after a few Page Hits.

Is it possible that this is related to the above 404 exception in line 151 of the Framework Controller.php ? I can provide you with additional information, mysql data, run whatever additional tests you think might help you identify and fix this issue as it currently renders Mautic rather useless for our marketing campaign :(

-Piotr

**Comment by alanhartless** [comment] 2015-04-06 16:16
Hi Piotr,

Can you look at your web server's access logs to see what URL is being accessed for those 404s? For example, cPanel servers usually store these logs in the /home/youruser/access-logs folder.  Other hosts may store them elsewhere.  We'll also look to see if we can get that message to include the URL so you don't have to look in multiple places.

As for the tracking issue, does it seem to be a specific number of page hits, a time period, or no pattern before it stops recording? Do you have any point actions or campaign events defined based on the number of page hits or amount of time spent?  Do you have any PHP fatal errors recorded in your server's error log? Again these vary based on host, but a cPanel host will usually put them in an error_log in your web root.

Thanks!
Alan

**Comment by alanhartless** [comment] 2015-04-09 22:29
Hi Piotr,

I just wanted to follow up on this one to see if you were able to determine the 404 URLs from the server's access log so we can start exploring what the potential issue is?

Thanks!
Alan

**Comment by pitus** [comment] 2015-04-10 04:16
Not yet ... our logs seem to be cluttered with thousands of /check.txt tests and lots of requests from other apps on the same server making it tedious to go through ... but some 404 errors seem to be out of place such as this:

`<IP> - - [29/Mar/2015:09:31:17 +0200] "GET //email/5517165658fa5.gif HTTP/1.1" 404 41427 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.5.0 Lightning/3.3.2"`

The email tracker failed with 404 but the `tracking_hash = 5517165658fa5` is there in the `email_stats` table so it should have succeeded, shouldn't it?

Perhaps that's what's happening, could it be related to the https://github.com/mautic/mautic/issues/264 where a delayed Action caused the following Decision not to detect the tracker?

There are quite a few 404s requesting `/mautic/p/mtracking.gif` or `//p/mtracking.gif` once it was moved to its own subdomain. But the //p is our own type due to a recent change and the problem was there before, just not with all requests as is the case now ;)

I'll try to re-run some of our tests this weekend as we've update the code a couple of days ago to the latest sources with a suspicion that the previous installation may have had some issues / corruption... Will let you know if I find anything more specific.

**Comment by alanhartless** [comment] 2015-04-10 04:47
The double forward slashes in the email tracking gif and mtracking gif will definitely cause tracking to not work as Symfony will throw a 404 for them. 

Do you recall if that email sent was triggered via a web trigger (submitting a form, etc) or from a cron job (executing a campaign)? If you from a cron job, look at the site URL in your configuration. Does it end with a forward slash? If so, try to remove it and see if the same issue presents itself.

I don't think #264 should affect the active tracking unless somewhere along the way it's the cause for some error.  But the logs should pick that up if it was the case.

**Comment by pitus** [comment] 2015-04-10 17:29
I know that //p/ will cause 404, that was a problem on our end with a recent change to the tracker ... but the problem was there before this change so I only pointed this out as a *doh* moment on our part ;)

The domain/site configuration has no trailing / (if you thought that was the source of the double // then don't worry, the person updating the tracker on the site made that mistake and put the // in the tracker itself).

The campaign sends initial email when it starts, then has a test if it's been opened followed by another email in a predefined delay (doesn't matter how long but it needs to be **for interval** as the **till date/time** seems to work correctly). Once that email is sent, everything else stops - the following Email Opened decision is never seen. If we remove the delay then all is well until next delay being hit.

So it appears that the problem is when the email is sent from the cron job trigger, but I'm not sure why the **till date/time** would not be affected just the same?

**Comment by alanhartless** [comment] 2015-04-10 20:07
Do you have one of the emails handy that was sent from the cron job trigger but didn't execute the email open decision? If so, can you check the source of the email and find the email/somerandomstring.gif and see if it looks okay? It's that image that will trigger the email opened decision so if it is not correct, the rest of the campaign will never be triggered.

Also curious if https://github.com/mautic/mautic/pull/273 fixes it.  If you have the time and are willing to help test before we release 1.0.3, it may help get any bugs with the changes worked out before the actual release.

Thanks!
Alan

**Comment by alanhartless** [comment] 2015-04-10 20:08
Sorry for accidentally closing the issue; my stupid trackpad has been a bit jumpy and I clicked the wrong button.

**Comment by pitus** [comment] 2015-04-13 13:40
I think the tracker in the email (secondary, sent from cron, doesn't get detected) is the same as in the first email (which works, gets detected).
`<img height=3D"1" wi=
dth=3D"1" src=3D"http://domain.net/email/551706addb7a8.gif" />`

Note that I've copied it directly from the original email source (at Google).
It shows `=3D` for each `=` which I'm not sure is necessary, but the same is present in the tracker that worked so this is more of a side-note (why is it **email encoded**, does it have to be?)

What could cause problems is the split `width` attribute name - didn't notice that before.

Then again, the first one looks exactly the same (different hash, of course)
`<img height=3D"1" wi=
dth=3D"1" src=3D"http://domain.net/email/55170452de925.gif" />`

I'm no longer sure which is which - might have to re-run the tests... but, just in case you can figure it out from these ... here's some more examples that look different for some reason:

`<img height=3D"1" width=3D"1" src=3D"http://domain.net/email=
/55147e2c533e1.gif" />`
no split of width, looks OK except for the `email= /` split this time - this was the first one in the campaign
`<=
img height=3D"1" width=3D"1" src=3D"http://domain.net//email/551489596=
6573.gif" />`
this one has an encoded opening brace `<=` or img? Why is is `<= img` ? - that's the second one, possibly from cron...

Something strange is happening with all these splits in various places. Let me know if you need us to re-run a complete test for you?

**Comment by pitus** [comment] 2015-04-13 16:06
Here's a suggestion for the siteUrl config parameter, as it seems very sensitive to whether it includes a trailing forward slash / or not - perhaps you should check for that (when saving it on Admin page) and remove it if present (to avoid things like a double slash in the tracker domain//email/... ?
You could also show a warning on the Dashboard when it's not been configured (as a reminder) ?

**Comment by alanhartless** [comment] 2015-04-13 22:23
@pitus That last PR should fix the double slash issue.

Thanks!
Alan

**Closed** 2015-04-14 12:48 UTC
Labels: Bug
