### ISSUE TITLE
Form Actions do not trigger

### ISSUE THREAD

**Issue by PeterTL** [mautic/mautic#2729] opened 2016-10-12 13:06 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have a vanilla and blank installation of the latest Mautic software. I configured email settings properly (tested it) and created a lead form which I embedded on a Wordpress page. The lead form actions should tag the lead and send the form results to an email address.

When I display the form on the Wordpress page, fill it out and submit, the following happens:
- The submit button remains at "Please wait..."
- The lead is created according to the field values
- The lead is not tagged
- The lead form results are not sent to the email address

It seems that the lead creation works fine, but the form actions are not triggered. Somehow the form "hangs", this is what the "Please wait..." indicates. I tested again in the form preview - same (negative) result.

Ich checked the log and the only maybe relevant error I can find is:
`[2016-10-09 09:27:54] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #11. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /.../mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.0
| PHP version | 5.6.23-1

### Steps to reproduce:
1. Create lead form
2. Fill out lead form and submit
 
### Log errors: 

`[2016-10-09 09:27:54] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #11. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /.../mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92`

**Comment by escopecz** [comment] 2016-10-12 13:22
Duplicate of https://github.com/mautic/mautic/issues/2664

**Closed by escopecz** 2016-10-12 13:22 UTC
