### ISSUE TITLE
SugarCRM Integration failed due to Authorization failed 

### ISSUE THREAD

**Issue by subhankar** [mautic/mautic#5368] opened 2017-11-23 11:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
After giving SugarCRM Community 6.5.25 oAuth credentials in Mautic and trying to Authorize App, it gives me the following error:

**Authorization failed with the error message, 'There was an unknown error encountered when trying to obtain the access token.'**

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11
| PHP version | 7.X

I have LDAP authentication enabled in SugarCRM. 

Please let me know any work around this problem

**Comment by isleshocky77** [comment] 2017-12-12 21:16
@subhankar What are you using as the command?

**Comment by it7steve** [comment] 2018-01-04 22:49
@subhankar did you find a solution to this problem ? We have the same error, with Mautic v2.12.0, SuiteCRM Community :(

**Comment by subhankar** [comment] 2018-01-05 11:37
@it7steve No luck

**Comment by isleshocky77** [comment] 2018-01-05 13:29
You never posted your exact command.

**Comment by adstagetech** [comment] 2018-01-23 11:18
same problem :(

**Comment by therealkevinard** [comment] 2018-05-28 18:47
A little late, but I had this error also. After debugging, I found that my sugar (SuiteCRM) .htaccess was broken in a way that would error-out on api calls, but not the main app. To identify:
- create a requestbin and temporarily change your integration url to point there. 
- api v4.1 uses url params (vs req. body) for its api. Copy the complete request url your requestbin recorded. Keep this in a txt file. 
- using postman or simply a new browser tab, send that request to your sugar endpoint (ofc, change the base, but keep the params the same)
500 error? If so, continue... 
- use the demo install from SuiteCRM site, and submit the same request to that api. 
Unauthorized error (but not 500)? If so...

The demo returning unauthorized says the API call is well-formatted. 
The call to your own endpoint erroring-out says the problem is there. 

Disable htaccess and try your own SuiteCRM again. Success? Debug your suite htaccess file.

**Comment by npracht** [comment] 2019-03-28 09:39
according to @therealkevinard comment, it seems to be a configuration issue. I'll close this issue.

**Closed by npracht** 2019-03-28 09:39 UTC
Labels: Bug

**Comment by hugovictor10** [comment] 2019-08-12 16:24
Very well friends.
What I mean is that SuiteCRM died for everyone. It will only exist for the bastards who charge $ 120 a year to link to Mautic for linking free software! For all of us who love Mautic's free code, we have SuiteCRM, a junk that only serves the interest of these outcasts.
Run away from SuiteCRM, this shit has no integration with Mautic, it's just wasting precious time.

And please my friends, a simple solution.

**Comment by hugovictor10** [comment] 2019-08-12 16:24
Very well friends.
What I mean is that SuiteCRM died for everyone. It will only exist for the bastards who charge $ 120 a year to link to Mautic for linking free software! For all of us who love Mautic's free code, we have SuiteCRM, a junk that only serves the interest of these outcasts.
Run away from SuiteCRM, this shit has no integration with Mautic, it's just wasting precious time.

And please my friends, a simple solution.
