### ISSUE TITLE
Add change stage in triggers and forms actions

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#4285] opened 2017-06-23 07:59 UTC
| Feature request? | 
| Enhancement? | 

## Description:
when user reach specific number of points, we do specific triggers such as change campaigns, add tags, etc... One trigger that seems to be missing is to change the lead stage. 

Many of our campaigns work on dynamic segments that rely on stages. At the moment, we created three campaigns that all they do is change lead stage as a work around

Idea: It would be quite useful and logical for the trigger to change the lead stage. 
Also in forms, if a lead filled a form. It would be quite useful and logical to put in the actions an option to move the lead to a stage. i.e. move from record to cold lead.

**Comment by escopecz** [comment] 2017-06-23 08:45
It seems like a duplicate of https://github.com/mautic/mautic/issues/3912

**Comment by mellsaid** [comment] 2017-06-23 10:31
@escopecz Its different from #3912. #3912 is suggesting to add a condition inside the campaign to check lead stage. 

This request is suggesting adding the ability to change stage as an event inside triggers. and actions inside forms. Some illustration below:

![image](https://user-images.githubusercontent.com/22168697/27475828-7a1d8508-57fe-11e7-91fe-d3b229bc95c0.png)

And in forms:

![image](https://user-images.githubusercontent.com/22168697/27478384-51e8cdd2-5807-11e7-8b33-7ad93a571968.png)

**Closed** 2018-02-25 17:52 UTC
Labels: Feature Request

**Comment by Shaz3e** [comment] 2018-06-24 14:52
I totally agree with @mellsaid this option seems very important for clear visibility, this will do some other magic.

**Comment by namankumar** [comment] 2018-09-13 14:45
+1

**Comment by allanwolski** [comment] 2019-02-12 13:38
+1
