### ISSUE TITLE
cron job error message

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#972] opened 2015-10-03 04:40 UTC
Hi,

when I send mails to about 83 recipients, I get thw following error message from the cron job (exec("/usr/bin/php mautic/app/console mautic:campaigns:trigger --env=prod -f 2>&1", $out, $result);):

Triggering events for campaign 2,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering scheduled events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering 'non-action' events,0 event(s) executed,,Triggering events for campaign 3,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering scheduled events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering 'non-action' events,0 event(s) executed,,Triggering events for campaign 4,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering scheduled events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering 'non-action' events,0 event(s) executed,,Triggering events for campaign 5,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) execu
 ted,,Triggering scheduled events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering 'non-action' events,0 event(s) executed,,Triggering events for campaign 6,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering scheduled events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering 'non-action' events,0 event(s) executed,,Triggering events for campaign 9,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering scheduled events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering 'non-action' events,0 event(s) executed,,Triggering events for campaign 10,Triggering first level events,0 total events(s) to be processed in batches of 100,0 event(s) executed,,Triggering scheduled events,1 total events(s) to be processed in batches of 100,,1 event(s) executed,,Triggering 'non-action
 ' events,0 event(s) executed,,Triggering events for campaign 11,Triggering first level events,2 total events(s) to be processed in batches of 100,,,,  [Doctrine\ORM\ORMInvalidArgumentException],  A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#campaign' that was not configured to cascade persist operations for entity: Mautic\CampaignBundle\Entity\Campaign with ID #10. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).,,,,mautic:campaigns:trigger [-i|--campaign-id[="..."]] [--scheduled-only] [--negative-only] [-l|--batch-limit[="..."]] [-m|--max-events[="..."]] [-f|--force],,

Is there anything I can do?

Robert

**Comment by escopecz** [comment] 2015-10-03 08:29
This is duplicate of https://github.com/mautic/mautic/issues/938

If you could discover the circumstance causing the error, it would help us simulate it and fix it.

**Comment by different-thinking** [comment] 2015-10-03 10:58
What can I do?

I think the error accours consistently when a specific campaign sends out mail. I think it should accoure on monday 9am CEST.

What information do you need? Access to the system? How can I help?

Robert

**Comment by escopecz** [comment] 2016-01-06 15:48
Is this still an issue with Mautic 1.2.3?

**Closed** 2016-07-27 13:00 UTC
Labels: Bug, Duplicate, Pending Feedback
