### ISSUE TITLE
"500 Internal Server Error"

### ISSUE THREAD

**Issue by najavica** [mautic/mautic#2151] opened 2016-07-31 03:31 UTC
Hi, I have a problem when trying to install Mautic on my VPS, tells me
"500 Internal Server Error". When I go to the log file to verify I read the following
  "[31/07/2016 2:38:12] mautic.CRITICAL: PHP Uncaught Exception Exception:" There is no suitable CSPRNG installed on your system "at .............. / vendor /paragonie/random_compat/lib/random.php line 185 { "exception": "[object] (Exception (code: 0): There is no suitable CSPRNG installed on your system at ........... ./vendor/paragonie/random_compat/lib/random.php:185) "} []"

Could help resolve this error please

Thank you

**Comment by escopecz** [comment] 2016-08-01 06:55
Duplicate of https://github.com/mautic/mautic/issues/2034

**Closed by escopecz** 2016-08-01 06:55 UTC

**Comment by leokovaski** [comment] 2018-06-19 16:50
Hello friends. Was able to resolve by setting some folder permissions:

/mautic

find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
chmod -R g+w app/cache/
chmod -R g+w app/logs/
chmod -R g+w app/config/
chmod -R g+w media/files/
chmod -R g+w media/images/
chmod -R g+w translations/
chown -R $USER:www-data
