### ISSUE TITLE
Segmentation based on behavior

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2186] opened 2016-08-05 01:30 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
Hi Guys,

By using Mautic, I've been faced with something that I've never thought about: segmentation based on behavior.

I can imagined (and, I fact I needed) a few useful use cases:

Contacts that visited landing pages X in the last Y days
Contacts that had filled form Z
Contacts that visited URL X

It would be a huge advancement if we could filter contacts based on behavior. A good starting point would be the possibility of adding filters based on contact's action on Mautic's components.

Just to share with you, one good reference to look at is SAP hybris Marketing, which segmentation engine is certainly one of the best when compared to the comparable high-end solutions.

ps: I know I can do this by combining a broad segment with a condition in the decision tree... my suggestion is to add this intelligence to the segmentation engine.

**Comment by alanhartless** [comment] 2016-08-25 18:16
Duplicate of #1198

**Closed by alanhartless** 2016-08-25 18:16 UTC
Labels: Feature Request
