### ISSUE TITLE
Items Per Page defaulting back to 10 for form results

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4054] opened 2017-05-11 17:13 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  **Yes**

## Description:
When trying to switch the number of displayed rows per page in form submissions, it just keeps going back to 10. Video here: https://www.screencast.com/t/pQLEmShJdKGt

Form results seems to be the only area in the app that is behaving this way. Contacts for example responds to greater than 10.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | **2.8 Cloud**
| PHP version | 

### Steps to reproduce:
1. Go to forms
2. Choose a form and click "View XX Results" (one with greater than 10 results)
3. try changing the number of results at the bottom to anything other than 10.
 
### Log errors: 

No errors that I could see. The ajax query seems to be accurate: https://demandramp.mautic.net/s/forms/results/1?tmpl=list&name=formresult.1&**limit=50**&mauticUserLastActive=2&mauticLastNotificationId=

**Comment by escopecz** [comment] 2017-05-11 17:43
I think it's related to https://github.com/mautic/mautic/issues/3933

**Comment by ronnieduke** [comment] 2017-05-12 17:33
@escopecz yeah looks like a symptom of the same core issue.

**Comment by aviboy2006** [comment] 2017-06-22 12:20
am able to reproduce it. in Mautic\FormBundle\Controller\ResultController -> indexAction
if ($this->request->getMethod() == 'POST') {

        $this->setListFilters();
    }
this call suppose to pass $name variable means form name paramter from url -
http://localhost/mautic-lead/s/forms/results/4?tmpl=list&name=formresult.4&filterby=r.disposition&value=FCB&mauticUserLastActive=1&mauticLastNotificationId=
not passing. i checked in Mautic\CoreBundle\Controller\CommonController.php for

protected function setListFilters($name = null)
{
if (null === $name) {
$name = InputHelper::clean($this->request->query->get('name'));
}
$name = 'mautic.'.$name;
}

function is not passing $name still not going to if case to get from request parameters. because without passing $name its giving me value before if case. Because of result mapping is not working. if we pass "formresult.4" from request parameter it will work properly

**Comment by RCheesley** [comment] 2019-11-14 19:14
Closing as mentioned issue has been resolved and merged with #4281

**Closed by RCheesley** 2019-11-14 19:14 UTC
Labels: Bug
