### ISSUE TITLE
GoToWebinar dont work !!

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#3590] opened 2017-03-07 10:49 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
?mauticError=Erreurs%20%3A<br%20%2F><ol><li>Bad%20request<%2Fli><%2Fol>#formulaire

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.7.0
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-03-07 11:36
Please provide more information about the problem you are having and steps to replicate.

**Comment by nesrine22** [comment] 2017-03-07 13:24
hello,
when i submit my form the inscription to the session webinaire dont work
![image](https://cloud.githubusercontent.com/assets/26248308/23658161/ba63acda-0341-11e7-8420-ea80a8472907.png)
also i have an error msg after the name of domaine :+1: ?mauticError=Erreurs%20%3A<br%20%2F>

Bad%20request<%2Fli><%2Fol>#formulaire

**Comment by nesrine22** [comment] 2017-03-07 13:43
this is the error msg that i have when i clic submit 
https://www.aaaaaaaaaaaaaaaaaa.com/test-form-mautic/?mauticError=Erreurs%20%3A%3Cbr%20%2F%3E%3Col%3E%3Cli%3EBad%20request%3C%2Fli%3E%3C%2Fol%3E#formulaire

**Comment by nesrine22** [comment] 2017-03-07 14:37
![image](https://cloud.githubusercontent.com/assets/26248308/23661106/ea38af46-034b-11e7-945b-044030956397.png)

**Comment by escopecz** [comment] 2017-03-07 15:14
Try to goole for the `ERR_BLOCKED_BY_CLIENT` error. It seems it is caused by some CDN

**Comment by escopecz** [comment] 2017-07-03 09:20
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.

**Closed by escopecz** 2017-07-03 09:20 UTC
Labels: Pending Feedback
