### ISSUE TITLE
Social Monitoring

### ISSUE THREAD

**Issue by Harry5-5** [mautic/mautic#2049] opened 2016-07-18 12:02 UTC
Help

I have set up the app on twitter and all looks to be fine. I can pull in twitter data of a contact when i know what the twitter handle is. The question i have is:

I have now set up social Monitoring through Channels menu option but i am getting no results at all showing - even though there has been activity on that twitter account.

Any ideas what i might be doing wrong?

Is there any documentation around how to properly set it up?

Roger

**Comment by nickian** [comment] 2016-07-19 22:38
Are you running this cron job?

`*/5 * * * * /usr/bin/php /www/app/console mautic:social:monitoring --env=prod`

**Comment by dbhurley** [comment] 2016-07-20 13:07
I'd recommend checking out either the forums or the Slack community for help. Closing this as not a bug...

**Closed by dbhurley** 2016-07-20 13:07 UTC
