### ISSUE TITLE
Error 500 while editing company

### ISSUE THREAD

**Issue by Arkango** [mautic/mautic#7517] opened 2019-05-11 07:51 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I read my logs and i found which multiple selection cause this erorr

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at /home/marikama/public_html/mautic/vendor/symfony/validator/Constraints/LengthValidator.php line 38

What i can do , try deleting the field ?

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 7.2.1
| Browser | chrome

### Steps to reproduce
1. add company
2. edit editing
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2019-05-17 13:01
Duplicate of https://github.com/mautic/mautic/issues/7469

**Closed by escopecz** 2019-05-17 13:01 UTC
