### ISSUE TITLE
[Feature Request] New segment filters

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3366] opened 2017-02-08 10:42 UTC
| Q  | A
| --- | ---
| Bug report? | 
| Feature request? | :heavy_check_mark: 
| Enhancement? | 

## Description:

I have seen some Mautic users launch campaigns and realise afterwards that they should have tracked downloaded assets or submitted forms. But now that the campaign is over, they don't have this information and they wish they could get these contacts back by using segments.

Therefore, I think it would be nice to see the following segments added:
- Downloaded Asset
- Submitted Form

**Comment by npracht** [comment] 2017-02-08 10:48
Duplicate of #3293 & #3294

**Closed** 2017-02-08 10:50 UTC
