### ISSUE TITLE
PHP Warning:  Illegal offset type in isset or empty in

### ISSUE THREAD

**Issue by taOsemc** [mautic/mautic#7230] opened 2019-02-08 22:41 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have created a campaign that, if a specific field of a contact is filled in, then it gives a specific value to the field " stage ". 

The problem is that it doesn't work.

I don't know if it's related, but I'm getting this message below.
Also, in the cron logs it looks like a line is duplicated and instead of a number it displays %ID%. 

I don't know anything about it, I'll let you examine it all.
![2019-02-08 23 40 16](https://user-images.githubusercontent.com/32459602/52510100-f98b8700-2bfa-11e9-907e-a55f9976cf35.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. I have no idea.
 
### Log errors

I have no idea if it's related to my issue but **I receive this from my server from time to time:** 

> PHP Warning:  Illegal offset type in isset or empty in /var/www/vhosts/************/********/mautic-master/app/bundles/CampaignBundle/EventListener/LeadSubscriber.php on line 102

**Duplicate Lines in Cron log :**

> Task "/mautic-master/app/console" successfully completed in 1 seconds, output:
> 
> Redéfinir les contacts pour la campagne 2
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 
> Redéfinir les contacts pour la campagne 3
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 
> Redéfinir les contacts pour la campagne 4
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 
> Redéfinir les contacts pour la campagne 7
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300

> Task "/mautic-master/app/console" successfully completed in 1 seconds, output:
> 
> Redéfinition des contacts pour le segment 3
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 0 contact(s) concerné(s)
> 
> Redéfinition des contacts pour le segment 4
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 0 contact(s) concerné(s)
> 
> Redéfinition des contacts pour le segment 2
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 0 contact(s) concerné(s)
> 
> Redéfinition des contacts pour le segment 6
> Redéfinir les contacts pour la campagne %id%
> 0 contact(s) à retirer aux lots 300
> 0 contact(s) concerné(s)
> 
> Redéfinition des contacts pour le segment 5
> Redéfinir les contacts pour la campagne %id%

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by taOsemc** [comment] 2019-02-08 23:04
Ok for the %ID% issue it's only when mautic is set to french.

Still trying to understand the other bug.

**Comment by taOsemc** [comment] 2019-02-09 00:33
The PHP warning comes from this cron : 

> crm.digitools.co/mautic-master/app/console mautic:segments:update

The thing is that i don't have any bad log when i use the command manualy.

**Comment by npracht** [comment] 2019-02-12 07:48
Hi @taOsemc, you need to explain what means "it does not work". For instance, how is your contact set ? In which branch should he go ? What happens instead ?

Thanks

**Comment by npracht** [comment] 2019-02-25 09:24
@taOsemc any update ?

**Comment by briidea** [comment] 2019-03-05 10:41
I am getting this error too, I have not looked into why its happening and have not worked out the consequences of the error yet. My campaign is a simple one, segment-> check not in segment exception list -> send email -> if they open add 10 points

**Comment by RCheesley** [comment] 2020-02-04 18:14
I'm going to close this issue due to lack of recent activity and insufficient information to reproduce the errors. Please feel free to re-open if it is still an issue with 2.15.3 and more detail can be provided to help with troubleshooting!

**Closed by RCheesley** 2020-02-04 18:14 UTC
Labels: Bug
