### ISSUE TITLE
Can't access System Info tab on Mautic.

### ISSUE THREAD

**Issue by thiamaster** [mautic/mautic#8321] opened 2020-01-10 17:51 UTC
What type of report is this:
Bug report

## Description:
System Info tab on mautic doesn't work. When I try to access it, I receive an error 500 page, with the saying:  "Uh oh! I think I broke it. If I do it again, please report me to the system administrator!". Sending e-mail is fine, everything else looks fine, but I need to check my mautic version, and I can't do that from this page. Logs show:
`[2020-01-10 14:24:17] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /path/to/web/mautic/vendor/symfony/http-foundation/JsonResponse.php line 164 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /path/to/web/mautic/vendor/symfony/http-foundation/JsonResponse.php:164)"} []`

If it helps, I'm with UTF-8 encoding, portuguese language.

Mautic Version: Can't|Don't know how to check
PHP Version: 5.6.40

**Comment by npracht** [comment] 2020-01-12 17:48
Duplicate of https://github.com/mautic/mautic/issues/5973. Closing in favor of it.

**Closed by npracht** 2020-01-12 17:48 UTC
