### ISSUE TITLE
Builder's Raw block content is not editable

### ISSUE THREAD

**Issue by LordRembo** [mautic/mautic#12741] opened 2023-09-26 07:58 UTC
### Mautic Version

- 4.4.x series
- 5.x

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using the GrapesJS Builder to construct an email, adding a Raw Block, renders a block with 6 images (randomized, from Unsplash). I would expect this to be placeholders and being able to edit the (html) code inside of it but clicking it reveals no options to edit. That makes this Block rather useless.

### How can we reproduce this issue?

Step 1: Create a new email
Step 2: Choose a theme that supports the Raw block (all except Blank, I think) [has to be using GrapesJS]
Step 3: Drag the Raw block into the mail
Step 4: Click the block containing the 6 placeholder images: all you can do is move, duplicate, remove. Or  you can use the Style Manager to add a title/id to it. But no way to edit the content

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2023-09-26 12:32
I think this has been an issue ever since we had the builder, I vaguely remember reporting this  during QA but at the time I think it was thought to be something upstream rather than to do with our preset or implementation.

Not sure if the issue is to be here or in the preset, as you mentioned in Slack maybe it is resolved by updating the GrapesJS version?

**Comment by LordRembo** [comment] 2024-02-01 14:07
So as it turns out, this issue isn't fixed by updating GrapesJs and its dependencies. In fact, the latest demo of the mjml newsletter builder has a Raw block that still is 'broken'.
As mentioned in Slack, I'd argue for adding the ‘Custom code’ block to the email editor (like the editor for landing Page uses).
Reason being: nobody seems to know how the ‘Raw’ block works (I’d argue it doesn’t) and [this post from 2021 is just avoiding it](https://forum.mautic.org/t/grapesjs-mj-raw-how-to-use/20839)) and assume it’s like the ‘Custom code’ popup editor that is used in the Landing Pages editor. So we might as well add ‘Custom code’.
I’d remove the ‘Raw’ block entirely but who knows, maybe some people do find a use for it (eg. to build up a gallery). So better leave it in I guess.

**Comment by LordRembo** [comment] 2024-02-01 14:20
Made a forum post to get input from the community so we can make a proposal based on that:
https://forum.mautic.org/t/product-input-how-do-you-use-the-raw-block-in-the-email-editor/30748

**Comment by LordRembo** [comment] 2024-02-13 16:37
Added a PR to remove the block: https://github.com/mautic/mautic/pull/13363

**Comment by RCheesley** [comment] 2024-11-18 12:15
Closing as the PR ismerged.

**Closed as completed by RCheesley** 2024-11-18 12:15 UTC
Labels: T1, bug, hacktoberfest, builder-grapesjs
