### ISSUE TITLE
Design request - Icon on campaign actions

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1132] opened 2015-11-05 12:18 UTC
Hi,

Those campaign actions are written text, i'm always taking time to find the action i want. **It would be nice to have an icon.**
__________
Here is what we have:
![capture d ecran 2015-11-05 a 13 16 08](https://cloud.githubusercontent.com/assets/14075239/10968127/75d2cc20-83bf-11e5-84a4-d6e275f89ff0.png)
__________
An example of competitor:
![capture d ecran 2015-11-05 a 13 15 47](https://cloud.githubusercontent.com/assets/14075239/10968128/75d3727e-83bf-11e5-8bb4-7df03ac31f3e.png)
__________
![capture d ecran 2015-11-05 a 13 15 53](https://cloud.githubusercontent.com/assets/14075239/10968126/75d1535e-83bf-11e5-8259-5a33be24c98e.png)
__________

It's not big, but makes a big difference to find quick what we look for :)

N.

**Comment by alanhartless** [comment] 2015-12-17 19:30
Going to mark this as a duplicate of #454

**Closed by alanhartless** 2015-12-17 19:30 UTC
