### ISSUE TITLE
Link Click Decision in Campaign Builder

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2576] opened 2016-09-21 14:15 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Yes
| Enhancement? | 

## Description:
Want to be able to send an Email to a segment with multiple buttons and activate different campaigns based on the button that had been clicked. Currently only possible by "Page Visited", which is possible to be done through other means navigating website or social media links for example.

Link Clicked from inside an Email would be the most convenient. I read that this is a planned feature. 

https://www.mautic.org/community/index.php/3089-clicks-link-as-decision/0

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-09-22 06:56
This seems to be duplicate of https://github.com/mautic/mautic/issues/1126

**Closed by escopecz** 2016-09-22 06:56 UTC
