### ISSUE TITLE
Unable to search for a company in the Contact edit screen

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12650] opened 2023-08-11 13:50 UTC
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I import contacts (so that there are a lot to choose from, eg usinghttps://www.datablist.com/learn/csv/download-sample-csv-files) and then try to add one to a Contact profile by searching for the name, nothing is found.

### How can we reproduce this issue?

Step 1: Import a lot of contacts - eg I used 1000 contacts from https://www.datablist.com/learn/csv/download-sample-csv-files
Step 2: Try to associate a company with a contact by editing the contact and searching for the name of the company
Step 3: Notice that nothing happens - you can even search for the companies you see appear to be selected and they don't show either.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment] 2023-08-14 07:55
It looks like the code handling the company lookup and other lookup fields was removed in https://github.com/mautic/mautic/commit/54e30a1f9d5eb994a82497dd7cae935be31c0826#diff-848adfcfe41ee4ce0df31b3241f8ee96e1d6a418191f41db4f4669d8f5b2fdf3 without any replacement. 

@biozshock what was the reason for it? The problem is with missing `AjaxLookupControllerTrait` and all its usages.

**Comment by biozshock** [comment] 2023-08-14 13:13
@escopecz haven't found any usages of the method inside of it, so it was removed. Also confirmed by tests: the method was never called (not covered?).

**Comment by escopecz** [comment] 2023-08-14 13:25
It's called from several JS files: https://github.com/search?q=repo%3Amautic%2Fmautic+getLookupChoiceList&type=code

Do you think you'll have time to get that part into the original state?

**Comment by biozshock** [comment] 2023-08-15 07:40
@escopecz unfortunately not before the mid September.

**Comment by escopecz** [comment] 2023-08-15 10:17
Fixed in https://github.com/mautic/mautic/pull/12652

**Closed as completed** 2023-08-18 13:51 UTC
Labels: T1, bug, regression, companies, contacts, javascript, good first issue
