### ISSUE TITLE
Type date/time in a field for a form

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#2539] opened 2016-09-14 19:20 UTC
What type of report is this:

You make a form with a date/time attribute. You integrate the code source in a landing page. In Firefox you don't see the type of the field. You capture a date with a text "22.09.2016 à 16 heures" When you commit you have an error on the form.

| Q  | A
| ---| ---
| Bug report? | 
Yes
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-09-15 06:32
Duplicate of https://github.com/mautic/mautic/issues/1217

**Closed by escopecz** 2016-09-15 06:32 UTC
