### ISSUE TITLE
Send email to a segment progress bar dont work

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#2391] opened 2016-08-25 15:35 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

I just update to 2.1.1 and i run a test to send a standalone email to a segment and the progress bar don't show the progress until all the emails are send.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. Send a standalone email to a segment
2. And the progress bar doesn't show the progress of the email being sent until all the emails are send.

If you have a list of 1898 email like the one i test because of the progress bar don't show the progress the user will think that the Mautic system is freeze.
Also, i make a test with a 3 email segment with the same results.
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-08-25 15:36
Could you please refresh the page to reload the JS and CSS and try again? I cannot reproduce it.

**Comment by ninjoan** [comment] 2016-08-25 15:47
I have to try to refresh the site also I log off and login with the same results.

**Comment by ninjoan** [comment] 2016-08-25 15:57
Here is a preview at 11:51AM
https://postimg.org/image/iqu16h1pr/

Here another preview at 11:54AM
https://postimg.org/image/npte3nfj5/

**Comment by gokhanerdogdu** [comment] 2016-08-27 07:05
I also face with similar problem during contact import. The progress bar is not progressing during import. Then suddenly it becomes 100% when completed and sometimes it never completes to 100% and I need to restart the process and see that some of contacts were already imported.

**Comment by alanhartless** [comment] 2016-08-27 12:07
Are you guys leaving the batch limit to default or setting it to something high?

**Comment by gokhanerdogdu** [comment] 2016-08-27 15:07
Yes, I am increasing that limit.

**Comment by alanhartless** [comment] 2016-08-27 15:17
That limit determines how many records are processed per Ajax call every 2
seconds. If you have a vps with decent specs, you may be able to handle
more records than the default per two seconds. Otherwise, try leaving it as
default.

**Comment by PatchRanger** [comment] 2016-08-30 09:36
The same issue: progress bar shows no progress (always 0), while looking at browser console I see that all AJAX-requests are successful and continue to be sent each second or so. Also if I open the email stats in a separate tab, I see that sent count is increasing each time I refresh the page.
I guess it is an issue of display/view - not of logic/error. I think, the root of the issue should be in javascript of progress bar.

**Comment by coh998** [comment] 2016-09-01 15:23
I, too, have no progress bar on send to segment. Was working before consecutive updates to 2.1 then 2.1.1. I can't say which update introduced issue since I did not send anything between updates. Am considering clean reinstall of entire package on local server for out-of-box testing of latest version.

**Comment by alanhartless** [comment] 2016-10-11 04:33
I can't reproduce this - if it's happening 2.2, can you post the response of the ajax request?

**Comment by coh998** [comment] 2016-10-11 12:48
On Oct 10, 2016, at 11:33 PM, Alan Hartless <notifications@github.com> wrote:

> I can't reproduce this - if it's happening 2.2, can you post the response of the ajax request?

No, I’m sorry, I can’t. I shut down the site and shelved Mautic because my host (SiteGround) issued a warning about MySQL database exceeding maximum 750 MB limit. And there I was wondering why the backend had become so slow and even unresponsive. We’d sent fewer than a 100,000 msgs all told. The db was over 900 MB... That, coupled with forum posts detailing some db’s over 4.5 GB, convinced me that this was a problem that was only going to get worse, and I do not have time or resources to deal with it.

Thank you for your time,

—Charles

**Comment by yllumi** [comment] 2016-12-06 05:05
I also still get this problem in Mautic v2.3.0.
The error shown at console is something like this:
```
POST http://mautic.codepolitan.com/s/ajax?action=updateUserStatus&mauticUserLastActive=61&mauticLastNotificationId= 503 (Service Unavailable)      libraries.js?v1d1f2a63:670
```
Before this I can send email as usual without problem. What is the cause of this?

**Comment by escopecz** [comment] 2016-12-06 08:39
@yllumi it might not be Mautic's fault. If you'll look at the definition of 503:

> The server is currently unable to handle the request due to a temporary overload or scheduled maintenance, which will likely be alleviated after some delay.

https://httpstatuses.com/503

It seems more that your server is overloaded when the emails are being sent and it won't accept the requests which asks for the progress report.

**Comment by escopecz** [comment] 2017-02-03 20:00
Closing for lack of answer. Feel free to comment with a new update and the issue will be opened again.

**Closed by escopecz** 2017-02-03 20:00 UTC
Labels: Bug, Pending Feedback
