### ISSUE TITLE
404 Of Mautic Javascript (mtc.js) In Landing Pages When Installed In Sub-Directory

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [mautic/mautic#2203] opened 2016-08-07 16:39 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When Mautic is installed in a sub-directory, it adds the sub-directory name twice which causes a 404 for accessing mtc.js
 
| Software  | Version(s)
| ---| ---
| Mautic  | 2.0.1/2.0.2-dev
| PHP |  5.6.24/7.0.8

### Steps to reproduce:
1.  Install Mautic in a sub-directory i.e. http://www.example.com/mautic/
2. Create Landing Page.
3. View Source.
 
<img src="https://s7.postimg.org/iqq7l92qz/image.png">

### Log errors: 

[2016-08-06 15:44:36] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL not found: /Mautic/Mautic/mtc.js" at /mnt/web014/d1/03/56975003/htdocs/joomla_10/Mautic/app/bundles/CoreBundle/Controller/CommonController.php line 411 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Requested URL not found: /Mautic/Mautic/mtc.js at /mnt/web014/d1/03/56975003/htdocs/joomla_10/Mautic/app/bundles/CoreBundle/Controller/CommonController.php:411)"} []

Community Post:

https://www.mautic.org/community/index.php/5168-rollercoaster-effects (Credit to klausv1304)

**Comment by escopecz** [comment] 2016-08-10 15:56
I actually got this error only when I was testing the Gated Video PR and cannot reproduce it on the latest staging. Did you also got this when testing https://github.com/mautic/mautic/pull/2081 or does it happen everywhere for you?

**Comment by dongilbert** [comment] 2016-08-10 21:13
This is fixed in #2081

**Closed by dongilbert** 2016-08-10 21:13 UTC
Labels: Bug

**Comment by elisei** [comment] 2017-12-29 19:25
here I am in version v2.12.1-dev and the problem is back!
