### ISSUE TITLE
Problem with "for interval" Delay with the following Decision failing

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#264] opened 2015-04-06 00:10 UTC
Delayed Email Action causes the following (joined) Email Opened Decision to fail (never triggers).

It took us a long time to figure out what's going on, we've created many scenarios, testing each campaign individually until we've realized that our scenario (one that we need to proceed with) can't be implemented with the current version due to a bug (most likely) in the way Mautic handles "for interval" delay.

Here's the setup:

cron job calls the mautic:campaigns:trigger every 2 minutes (for testing purposes it's set so low)
campaign has:
Email 1 to be sent immediately (it's sent just fine)
followed by (linked to) Opened Decision testing for that same Email 1 - if it's opened (this also works fine, the opening of email is detected)
followed by (from yes/green) another Email 2 to be sent, this time with a "for interval" delay of 1 minute (doesn't matter how long, any delay is a problem)
followed by another Opened Decision testing for Email 2 (this time, it is never triggered, nothing that follows it is being executed)
followed by Email 3 ... which is NEVER sent as long as Email 2 has a "for interval" delay init ... if we remove that delay or change it to date/time then it's fine ...
3) same issue with any other Action, not just Emails - if it has a "for interval" delay then a following decision that's linked to it fails (never triggers the yes/green)

BTW, could someone shed some light on the no/red decision output as we can't figure this one out (doesn't seem to be of any use as it is ALWAYS triggered as soon as the cron job is run) - the only way we could figure out making it useful (email not opened) is by setting up a special cron job just for that single campaign and triggering a specific mautic:campaign:trigger with this campaign's id ... but that's quite useless as it requires constant additions to cron jobs that are to be triggered at a given date/time when we consider the email from campaign has not been opened ... Another problem with this approach is also the inability to time the not-opening based on the actual email sending time (initially the campaign is sent at a known time but later, if some new lead is created, they do receive the same email at a later time/date ... and some of our campaigns are based on the fact that the email sent to the lead has not been opened say for 2 days since it has been SENT not since the Campaign started.
Anyway, just a suggestion how to improve this - the No/Red action should allow to specify a "for interval" delay since the email was sent and then we can have a single cron running every few minutes and triggering all such campaigns.

Regards,
-Piotr

**Comment by argentin** [comment] 2015-04-06 21:23
I have the same problem and I can't make drip campaigns.

**Comment by alanhartless** [comment] 2015-04-06 21:30
Hi,

Just as a FYI, I'm trying to reproduce this.  I'll give some feedback once I'm able to determine the issue(s).

@argentin can you give some background on the campaign you are trying to build?

Thanks!
Alan

**Comment by argentin** [comment] 2015-04-06 21:38
Of course Alan, look at this https://www.mautic.org/community/index.php/255-campaign-email-interval-not-working-properly/p1#p989.

**Comment by MaxOnTheHill** [comment] 2015-04-06 23:07
and this one https://github.com/mautic/mautic/issues/266#issuecomment-90269897  .... intervals and chained actions causing a bit of confusion ... possibly all able to merged into one, as solution may be through the one enhancement?

**Comment by alanhartless** [comment] 2015-04-07 02:37
Okay guys, can you help me figure out what I'm doing differently here?

Here's my test campaign:

![](http://dvkrd.co/drop/2015-04-06_21-21-39.png)

When I add my lead to the campaign, email 1 is immediately sent.  After I open the email, email 2 is scheduled:

![](http://dvkrd.co/drop/2015-04-06_21-19-00-1.png)

After a minute, I ran the command from CLI and email 2 was sent to me. 

I then open email 2 and email 3 is scheduled:

![](http://dvkrd.co/drop/2015-04-06_21-19-56.png)

Ran the command again a minute later and email 3 was sent to me.

![](http://dvkrd.co/drop/2015-04-06_21-21-18.png)

It seems to be functioning so I must be doing something different than you guys?

Thanks!
Alan

**Comment by alanhartless** [comment] 2015-04-07 02:43
Just repeated the process with a "no" connection and something is definitely off with that process.  I'm digging into that now.

**Comment by alanhartless** [comment] 2015-04-07 05:00
Just a quick update.  I found the reason for the 'no' decision path process acting erratic.  I'm just trying to figure out the best way to fix it. Hopefully will figure it out and get a PR against it tomorrow.

**Comment by MaxOnTheHill** [comment] 2015-04-07 05:31
wow ... at least got something replicated with that, seemed to be going in circles - glad you've a found possible reason ... and maybe solve the other "interval" issues; here's hoping :fireworks:

**Comment by pitus** [comment] 2015-04-07 21:30
I just remembered about one more detail about the Email Opened decision.
It allows to specify what Email to check for and it can be left blank.
We did specify the same Email that has been just sent in the preceding Action as we assumed the decision needs to know which Email tracker to test, but perhaps, it should be left blank?
Other than that, our process looks exactly the same as yours and only emails 1 and 2 are sent as the `Opens email 2` decision is **Never** registered as it follows an Email sending with a "for interval" delay.

**Comment by alanhartless** [comment] 2015-04-07 23:35
If anyone can help test #273 that'd be great.  

@pitus If the opened email limiter is left blank, it will default to the email specified in the "send email" action it's attached to. I'll test the other way to see if it makes a difference.

Thanks,
Alan

**Comment by pitus** [comment] 2015-04-09 19:16
See if you could make it (in some future version) more clear to the user in the UI, for example showing a comment below that Decision box referencing the Action (Email) linked to above - it would help the user quite a bit.

**Comment by alanhartless** [comment] 2015-04-09 21:51
Hi Pitus,

I'm not sure I'm following. Is it a bit redundant to show the name of the action it's already connected into? Or am I misunderstanding what you are asking for?

In the opens email decision, it has a reference to what would happen if the limiter is left blank:
![](http://cl.ly/image/3U1H0U261e1H/Image%202015-04-09%20at%2016%3A46%3A22.png)

**Comment by pitus** [comment] 2015-04-09 23:42
Now that I understand the process, and have re-read these hints, I do know what they refer to and mean ... however, when we originally tried to build the Campaign, we couldn't figure out what the "connected Send Email action" means when it's under "Limit to these selected emails" ... it was just very confusing at the time... perhaps add a word *above* at the end, such as: `Leave empty to default to connected Send Email action above` but even that might still be incomplete for novice users ... maybe change the label to `Limit the testing to these selected emails?` - not sure anymore.

**Comment by pitus** [comment] 2015-04-13 14:08
I think the tracker in the email (secondary, sent from cron, doesn't get detected) is the same as in the first email (which works, gets detected).
`<img height=3D"1" wi=|dth=3D"1" src=3D"http://domain.net/email/551706addb7a8.gif" />`

Note that I've copied it directly from the original email source (at Google).
It shows `=3D` for each `=` which I'm not sure is necessary, but the same is present in the tracker that worked so this is more of a side-note (why is it **email encoded**, does it have to be?)

What could cause problems is the split `width` attribute name - didn't notice that before.

Then again, the first one looks exactly the same (different hash, of course)
`<img height=3D"1" wi=|dth=3D"1" src=3D"http://domain.net/email/55170452de925.gif" />`

I'm no longer sure which is which - might have to re-run the tests... but, just in case you can figure it out from these ... here's some more examples that look different for some reason:

`<img height=3D"1" width=3D"1" src=3D"http://domain.net/email=|/55147e2c533e1.gif" />`
no split of width, looks OK except for the `email= /` split this time - this was the first one in the campaign
`<=|img height=3D"1" width=3D"1" src=3D"http://domain.net//email/551489596=|6573.gif" />`
this one has an encoded opening brace `<=` or img? Why is is `<= img` ? - that's the second one, possibly from cron...

Something strange is happening with all these splits in various places. Let me know if you need us to re-run a complete test for you?

**NOTE** that github converts New Line into a space in my code examples ... they are actually split into multiple lines after some of the `=` which I'll indicate as `|` so that you can see them. So any `=|` is actually `=\n` in the original html (email).
**NOTE 2** I just noticed that one of the tracker URLs has `//email/` in it - double slash ... yet our configuration only has a domain name with no trailing slash ... so I'm not sure where it came from ... I'll review all other tracking emails and see which ones have it as //email ... and let you know.
**NOTE 3** All emails sent on the Non-Action output (red) also have the double-slash `//email/` in them.

**Comment by pitus** [comment] 2015-04-13 16:06
Here's a suggestion for the siteUrl config parameter, as it seems very sensitive to whether it includes a trailing forward slash / or not - perhaps you should check for that (when saving it on Admin page) and remove it if present (to avoid things like a double slash in the tracker domain//email/... ?
You could also show a warning on the Dashboard when it's not been configured (as a reminder) ?

**Comment by pitus** [comment] 2015-04-13 17:09
OK, we've ran another test campaign, first ensuring that the siteUrl configuration has no trailing forward slash - it doesn't, it's just http://domain.name (of course, a different domain name than this ;)

The first email is sent immediately and other than the split `wi=\ndth=3D...` it looks OK and works:
`<img height=3D"1" wi=|dth=3D"1" src=3D"http://domain.name/email/552bd6c75e721.gif" />`

Once that's opened, another email is sent after a delay (so it's triggered by a cron job):
`<img height=3D"1" wi=|dth=3D"1" src=3D"http://domain.name//email/552bf68a75b33.gif" />`

As you can see, the one from cron job has a **double forward slash** in it `//email/` so it must be your code adding the extra slash in there - hope you can find and fix it for the **1.0.3** release this week?

**Comment by alanhartless** [comment] 2015-05-09 18:39
Closing as fixed with the latest releases.  If there are still issues, please open a new issue.

Thanks,
Alan

**Closed by alanhartless** 2015-05-09 18:39 UTC
