### ISSUE TITLE
BUG: Default's Fields

### ISSUE THREAD

**Issue by dannyec** [mautic/mautic#1806] opened 2016-05-30 04:04 UTC
## Description
"CREATE" and "EDIT" CONTACT BUTTON doesn't work when disable (a default's custom fields) occurs an error 500 

## Reason
In China we don't need First Name and Last Name fields, We only have one field for that, so disabling "First Name", make an error when creating/editing a contact.

This error doesn't happen in 1.3.1 it's totally ok.

## Second BUG:
At the same issue, when change custom field's name, this cannot change: "Company" and "City" names. Others is ok, except those two.

## Steps to reproduce
1. Configuration -> Custom Fields
2. Disable a Default's Field (e.g. Last Name)
3. CREATE a New Contact / EDIT a Contact
4. Show error 500 (cannot complete function).

**Comment by escopecz** [comment] 2016-05-30 07:47
The first bug seems to be duplicate of https://github.com/mautic/mautic/issues/1780

**Closed** 2016-08-01 05:19 UTC
