### ISSUE TITLE
A/B test not working in campaign

### ISSUE THREAD

**Issue by pth113** [mautic/mautic#1648] opened 2016-04-28 04:14 UTC
## Description
5000 leads, 1 Parent mail and 1 A/B mails with 50% weight and A/B test winner criteria based on Clickthrough rate  But only the parent mail has been send. No A/B mails....
version: 1.3.1

**Comment by escopecz** [comment] 2016-05-02 11:04
Seems like duplicate of https://github.com/mautic/mautic/issues/1520

**Closed by escopecz** 2016-05-02 11:04 UTC
