### ISSUE TITLE
Amazon SES Bounce Handling is not working using Mautic V2.1.1

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2561] opened 2016-09-19 22:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I'm using the latest version of mautic and have read some of the pull requests made to the Amazon SES bounce handling and confirmed I have latest code included in 2.1.1. Though, despite configuring everything properly. Bounces are not working.

I'm receiving the bounce Emails but they are not being read by mautic neither marked as read in the case of some users at: https://www.mautic.org/community/index.php/2948-amazon-ses-bounce-processing/0

Am I missing something?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version |  5.6

### Steps to reproduce:
1.  Configured Amazon SES as it described and previously worked with "Sendy" 
2. Bounce Emails are being sent to the address
3. Bounce Emails are not being processed by mautic
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-09-20 07:24
Should be fixed by https://github.com/mautic/mautic/pull/2312

**Comment by amagdy3** [comment] 2016-09-20 09:13
Thanks, I updated the files as per the pull, changed the bounce Email from the setting but unfortunately, started getting 500 Internal Server Error.

Some History:

Not sure if it'd be relevant or not but I had doubts it might be a reason. 

I sent the first campaign from username@domain.com, created an internal folder for bounced and configured mautic bounces to match with this folder. The option to select the created folder for bounces was being selected but giving an error while being saved as all non basic folders were being removed as I save.

When bounces were not read. I created a dedicated Email bounces@domain.com to configure for the bounces to allow it to be sent to its inbox and read from it.

Thought the above might be an indicator to you.

**Comment by escopecz** [comment] 2016-09-20 09:19
Double check you cleared the Mautic cache. The PR changes a config file, so the cache have to be refreshed. If it won't help, [check the logs](https://mautic.org/docs/en/tips/troubleshooting.html) to see what's wrong.

Also check the linked documentation on how to set it up: https://github.com/mautic/documentation/pull/92/files

**Comment by amagdy3** [comment] 2016-09-20 09:59
I sat it up as per instructions. My error log is as below - seems it happened due to recent update.

[2016-09-20 09:52:11] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 09:52:53] mautic.ERROR: PHP Error: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) - in file /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php - at line 1716 [] []
[2016-09-20 09:53:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Mautic\EmailBundle\MonitoredEmail\Mailbox::__construct() must be an instance of Mautic\CoreBundle\Helper\CoreParametersHelper, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined" at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 168 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Mautic\\EmailBundle\\MonitoredEmail\\Mailbox::__construct() must be an instance of Mautic\\CoreBundle\\Helper\\CoreParametersHelper, instance of Mautic\\CoreBundle\\Factory\\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php:168)"} []
[2016-09-20 09:53:02] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 09:53:08] mautic.ERROR: PHP Error: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) - in file /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php - at line 1716 [] []
[2016-09-20 09:53:16] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Mautic\EmailBundle\MonitoredEmail\Mailbox::__construct() must be an instance of Mautic\CoreBundle\Helper\CoreParametersHelper, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined" at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 168 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Mautic\\EmailBundle\\MonitoredEmail\\Mailbox::__construct() must be an instance of Mautic\\CoreBundle\\Helper\\CoreParametersHelper, instance of Mautic\\CoreBundle\\Factory\\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php:168)"} []
[2016-09-20 09:53:16] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 09:55:08] mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Mautic\EmailBundle\MonitoredEmail\Mailbox::__construct() must be an instance of Mautic\CoreBundle\Helper\CoreParametersHelper, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined (uncaught exception) at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 168 while running console command `mautic:email:fetch` [] []
[2016-09-20 11:55:10] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 11:55:14] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []

**Comment by escopecz** [comment] 2016-09-20 10:10
The `pdo_mysql.so: cannot open shared object file: No such file or directory` error means that the pdo_mysql extension used to be installed in your server, it's in the config file, but is not installed anymore. So either install it or remove it form the configs.

I don't know about the rest. It might be caused by a bug in the suggested PR or your copy/paste. Maybe move this communication to that PR so the author could react on it.

**Comment by amagdy3** [comment] 2016-09-20 10:39
My bad, I realized I changed the location of the mautic cache folder before and was able to clear the cash in the current folder folder.

Now getting below error which should make it clearer. Will post it at the corresponding PR as well.

Strict Standards: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) in /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 1716

**Comment by escopecz** [comment] 2016-09-23 11:43
@amagdy3 the logger issue was fixed in Mautic 2.1.1:

https://github.com/mautic/mautic/pull/2228

[LeadModel](https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Model/LeadModel.php) doesn't even have a setLogger method anymore.

**Closed by escopecz** 2016-09-23 11:43 UTC
Labels: Ready To Test

**Comment by amagdy3** [comment] 2016-09-24 13:41
Could be the reason that I copy the whole files while applying a pull request other than removing and adding lines of code. I preview the file and exchange full content.
