### ISSUE TITLE
Collect Data Focus Items don't show the form unless in bar mode

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#5054] opened 2017-09-28 15:33 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

### Screencast 🌟 

![egg9pguqen](https://user-images.githubusercontent.com/18265735/30975537-d11e7ca2-a472-11e7-8a62-c3d7ede8f1d8.gif)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 5.6

### Steps to reproduce:
1. Create Focus Item
2. Select Collect Data
3. Select Basic mode and fill in a headline, tagline and form.
4. Select any other style that bar mode
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mqueme** [comment] 2017-09-28 15:41
I think this PR might help you. https://github.com/mautic/mautic/pull/5000

**Comment by robwent** [comment] 2017-09-28 16:48
Possibly a duplicate of https://github.com/mautic/mautic/issues/4947

**Comment by dbhurley** [comment] 2017-12-01 04:03
Can't duplicate.

**Closed by dbhurley** 2017-12-01 04:03 UTC
