### ISSUE TITLE
filemanager show "no way"

### ISSUE THREAD

**Issue by Pixman** [mautic/mautic#1620] opened 2016-04-20 15:32 UTC
## Description
The filemanager just show "no way"

## My workaround
In file : _/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/connectors/php/filemanager.class.php_
the  [i]private function is_valid_path($path)[/i] ( line 1280 )
compare the $path, with the realPath on server.
My webserver is a debian 8 manage with ISPconfig, and the path send to this function is like :
/war/www/mywebsite.com/web/media/images

and the realpath founded by the function is /war/www/clients/client4/site2/web/media/images

the function return `substr(realpath($path).DIRECTORY_SEPARATOR, 0, strlen($this->path_to_files)-1) == (realpath($this->path_to_files).DIRECTORY_SEPARATOR);`

don't match, and the filemanager show " No Way"

it's a configuration problem or i have found a bug ?

tempoary i have replace 
`substr(realpath($path).DIRECTORY_SEPARATOR, 0, strlen($this->path_to_files)-1) == (realpath($this->path_to_files).DIRECTORY_SEPARATOR);`

by 
` return file_exists($path);`

thanks for help

**Comment by kuzmany** [comment] 2016-04-20 15:57
I got the same error.

**Comment by escopecz** [comment] 2016-04-20 16:10
Any chance https://github.com/mautic/mautic/pull/1506 would fix it for you?

**Comment by wittwerch** [comment] 2016-04-22 13:47
@escopecz: No, #1506 does not fix that issue, just tested it on the lastest staging branch.

**Comment by zachrdlapetr** [comment] 2016-04-29 01:37
@Pixman I had the same problem as you. I have used your trick for Debian and there still was problem with upload. I reslove it by adding FcgidMaxRequestLen 20000000 to setting apache sever.

Steps:
- add 3 lines and remove 1 line from (https://github.com/alanhartless/mautic/commit/e916f8deaff48ffada8582ad78f53192902ae757)
- relpace by return file_exists($path);  (your post)
-  adding FcgidMaxRequestLen 20000000 to setting apache sever

Done. File manager works.

**Comment by wittwerch** [comment] 2016-04-29 06:48
I just searched the code base for that "No way." string and that error handling is really scary!

![screen shot 2016-04-29 at 08 45 16](https://cloud.githubusercontent.com/assets/1575445/14909689/c1d7fac6-0de6-11e6-899e-4a25d89916a1.png)

I mean handling error in that fashion is no way! How should I know as a user what went wrong?
The error message is super generic and there is no detailed error in the log, even on debug level.

**Comment by escopecz** [comment] 2016-04-29 07:02
It would have bigger impact if you'd report this idea to the developers of the Filemanager library: https://github.com/simogeo/Filemanager

But from the perspective of the software security, it's recommended not to give possible crackers more details about why they cannot access some area. Maybe it's the reason here.

**Comment by zachrdlapetr** [comment] 2016-04-29 07:15
@wittwerch  The searching "no way" is wrong way :)  Open mautic and go to file manager (e.g. new email). If you see "no way" then go to Apache2 Error Log file and there is last error. Here you have to read the problem you have.

**Comment by wittwerch** [comment] 2016-04-29 14:19
@escopecz Did not notice that this code is part of the FileManager, but nevertheless that error handling has room for improvement. You can probably show a generic error to the user (to not give an attacker too much information), but you have to log the reason why you are throwing that error. Otherwise the administrator of the system is just digging in the dark (like me now).

@zachrdlapetr The apache error log is just empty, sadly no hint to further debug the problem.

**Comment by zachrdlapetr** [comment] 2016-04-29 14:29
@wittwerch it's impossible. did you look at the right place? please, check the apache error log path because there must be an error record. if you use e.g. ispconfig, the system records the errors on two places (virtual host and general error log).

**Comment by TomRoethlisberger** [comment] 2016-05-16 18:33
The problem is really within the is_valid_path($path) method. I've created a fix that worked for my vagrant mautic but I have to test the fix on our server before making a pull request. Here the code is somebody is interested before I make the pull request

private function startsWith($haystack, $needle) {
     // search backwards starting from haystack length characters from the end
     return $needle === "" || strrpos($haystack, $needle, -strlen($haystack)) !== FALSE;
}

private function is_valid_path($path) {

	$patt = array('/\\\\+/','/\/+/');
	$repl = array('\\\\','/');
	$substrpath = substr(realpath($path) . DIRECTORY_SEPARATOR, 0, strlen($this->path_to_files)) . DIRECTORY_SEPARATOR;
	$substrpath = preg_replace($patt,$repl,$substrpath); // removing double slash
	$rpath = realpath($this->path_to_files)  . DIRECTORY_SEPARATOR;
	$rpath = preg_replace($patt,$repl,$rpath); // removing double slash
	$this->__log('substr path : ' . $substrpath);
	$this->__log('real path : ' . $rpath);
    return $this->startsWith($substrpath, $rpath);
}

**Comment by godza** [comment] 2016-06-07 13:50
I'm having the same issue on debian server.

**Comment by alanhartless** [comment] 2016-08-19 05:03
Looks like FileManager has been deprecated in favor of https://github.com/servocoder/RichFilemanager. But I applied @Pixman 's fix in #2341. 

We're waiting on Froala to implement directory support for their image/filemanager then we'll be switching to them. Supposedly (we know how that goes) it's high priority.

**Comment by dongilbert** [comment] 2016-08-22 23:30
Fixed in #2341

**Closed by dongilbert** 2016-08-22 23:30 UTC
Labels: Bug, Ready To Test
