### ISSUE TITLE
Amazon SES Bounce/Complaint Confirmation Not Working

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#4632] opened 2017-08-09 22:43 UTC
Any idea what's going wrong here?

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Setting up the bounce/complaint webhook in SES/SNS isn't working. Getting the error below in the log when Amazon sends confirmation to the webhook.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.10.0-dev
| PHP version | 5.6

### Log errors: 

    [2017-08-09 22:20:47] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport::processJsonPayload() must be of the type array, null given, called in /www/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php on line 64 - in file /www/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php - at line 78 [] []

    [2017-08-09 22:22:26] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport::processJsonPayload() must be of the type array, null given, called in /www/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php on line 64 - in file /www/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php - at line 78 [] []

**Comment by namankumar** [comment] 2017-08-18 05:41
Getting the same thing in 2.9.2. 

`[2017-08-17 23:31:47] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\T\
ransport\AmazonTransport::processJsonPayload() must be of the type array, null given, called in /var/app/current/app/bundles/EmailBundle/Swiftmailer/Transpo\
rt/AmazonTransport.php on line 64 - in file /var/app/current/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php - at line 78 [] []


[2017-08-18 03:32:13] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\T\
ransport\AmazonTransport::processJsonPayload() must be of the type array, null given, called in /var/app/current/app/bundles/EmailBundle/Swiftmailer/Transpo\
rt/AmazonTransport.php on line 64 - in file /var/app/current/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php - at line 78 [] []
`

**Comment by mellsaid** [comment] 2017-08-18 08:54
I think this could be same problem in #4678 with sparkpost.

**Comment by namankumar** [comment] 2017-08-18 12:47
@mellsaid, I used to get 500 with SES before I changed "Send to mail through" setting to "Amazon SES" from "Other". Now I get 200. See apache log- 

`11/Aug/2017:16:02:37 +0000] "POST /mailer/amazon/callback HTTP/1.1" 200 7 "-" "Amazon Simple Notification Service Agent"
`
Another thing, I am now able to confirm my mautic installation in the SNS Dashboard, which wasn't the case when I used to get 500. That's why I posted my comments as part of this issue instead of the Sparkpost one.

I don't know what is going on now - here, it looks like mautic need to check for null value that is ok. But my problem is that Amazon shows 60 of my emails bounced yesterday morning but I can't see any of them in mautic.

**Comment by namankumar** [comment] 2017-09-22 11:18
hello, any update on this?

**Comment by FranSanchezOria** [comment] 2017-10-27 12:22
Hi I am having the same error. Can anyone throw some light here?

**Comment by Youlean** [comment] 2018-01-04 18:13
Hey guys, I was testing this also and for me it seems that https redirection is the problem. If I use http version of my site SNS connects nicely, but if I force redirection with this https://docs.bitnami.com/aws/apps/mautic/#how-to-force-https-redirection
I can not connect neither through http or https. I will investigate more. BTW, I am using bitnami Mautic installation...

**Comment by leowebguy** [comment] 2018-01-09 01:54
same problem here...

[2018-01-09 01:34:24] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport::processJsonPayload() must be of the type array, null given, called in /home/legolas/public_html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php on line 104 - in file /home/legolas/public_html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php - at line 114 [] []

any updates ?

**Comment by Youlean** [comment] 2018-01-09 02:07
For now workaround is to disable force https redirection and to use http for SNS. This works for me.

**Comment by carlosfvp** [comment] 2018-03-20 22:50
I currently don't have any http to https redirection but I have the same error.

**Comment by namankumar** [comment] 2018-03-21 21:45
This is very problematic. Without a way to track bounces and compliants,
you will all get banned from Amazon SES. I was.

On Tue, Mar 20, 2018 at 6:50 PM, Carlos Villacorta <notifications@github.com

**Comment by dsp76** [comment] 2018-03-27 11:16
Same here. 

So currently the only option is **to manually upload a bounce list** via import, as the automatical folder monitoring with Amazon SES doesn't work for bounce and complaint mail notifications either.


[2018-03-27 13:09:07] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport::processJsonPayload() must be of the type array, null given, called in ...

**Comment by dsp76** [comment] 2018-03-27 12:15
However, despite the initial log errors, it is working. I added the users: 

- "bounce@simulator.amazonses.com" and
- "complaint@simulator.amazonses.com"

and send both an individual mail directly from the Mautic contact (more here: https://docs.aws.amazon.com/de_de/ses/latest/DeveloperGuide/mailbox-simulator.html). 

**Right away, the contacts were flagged as 
- "email bounced" and
- "do not contact"
correctly.**

Test to ooto@simulator.amazonses.com caused no result.

To make clear: The error shown in the log was triggered by calling the webhook manually as http request, which is probably not the right way to do it anyway 🤣 

I also force my mautic to https, so this seem not to be a problem.

Seems not to be a bug anymore, could someone else try as well?

**Comment by namankumar** [comment] 2018-03-27 12:19
Dirk, that is a good find! What version of mautic is this? I can test with 2.10

**Comment by dsp76** [comment] 2018-03-27 15:54
I tested with 2.12.2

**Comment by FranSanchezOria** [comment] 2018-03-28 04:01
Hi Dirk,

Would you mind explaining a bit on detail how you achieved this? I have 2.12.2 and I'm still unable to make this work.

Currently, SNS won't confirm the subscription, the error is:

1 validation error detected: Value null at 'token' failed to satisfy constraint: Member must not be null (Service: AmazonSNS; Status Code: 400; Error Code: ValidationError; Request ID: e55259b9-b5b6-54d4-be69-0a8ca4130cda)

There is no error in the log file of Mautic. Any help appreciated.

**Comment by afonseca08** [comment] 2018-05-26 03:10
Just in case this helps anyone, I was running into a similar issue with the confirmation not going through. It turned out to be that I had configured the "Service to send mail through" as "Other SMPT Service" rather than "Amazon SES". 

The reason I did this initially is I had trouble connecting to Amazon (connection refused error) due to not having the right ports open on my server (25, 587, 2587). Once I sorted this out and changed it "Amazon SES" the confirmation went through as expected (using https endpoint).

**Comment by tcanani** [comment] 2018-09-05 16:53
Hello everybody!

I'm facing the same issue with hard bounces and complaints using Amazon SES, recently my account was suspended, but i managed to reinstate it. 

Now i have  the SNS configured with two subscriptions, one of them is a mailbox created specifically to monitor this situation, and the other is the mautic installation. 

But... as i'm not a full time developer (more an advanced administrator of some sort) i'm having trouble configuring the mautic side of this story. Can someone please help me with this? 

What do you guys put in the Webhook POST url field? Which checkboxes did you guys checked? I didn't find any clear info about this 'till now... but it's clear that something is wrong, cause in the webhook page i have the following error:

400 - Bad Request var mauticBasePath = ''; var mauticBaseUrl = '/'; var mauticAjaxUrl = '/s/ajax'; var mauticAjaxCsrf = 'VI2tM-2--nHN22S4N7FU2MsDL1bKZaurkv9by931ggE'; var

... and in the logs

mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Key 'Type' not found in payload " at /var/www/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Key 'Type' not found in payload  at /var/www/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php:116)"} []

I'm using the most updated version of Mautic, btw.

If someone could help me i'd appreciate.

**Comment by dsp76** [comment] 2018-09-05 18:38
You should not need to configure anything in Mautic as long as you use the "Amazon SES" Option, don't restrict CORS or at least whitelable Amazon SES Servers, don't block port 2587. Did the suscription in SNS get confirmed or is still "pending"? (by the way - you should discuss it in the forum or slack, not in the bug reports in github)

**Comment by tcanani** [comment] 2018-09-05 19:32
@dsp76 Hi man, thanks for your fast response.

I'm using Amazon SES option, and it's well configured and working properly. So you're saying that i don't need to create a webhook in mautic's side for this?

The CORS option WAS enabled... i just disabled it now for tests, but the results was the same
The subscription in SNS is confirmed alright.

I'm sorry if i posted it here. I just did it because i made everything by the book and am getting errors in return. This errors lead me here, and i made every step everyone here did and i still have the same errors. 

The only thing that is not clear for me is this Mautic part of the configuration on webhooks. I already looked for it on forums and Mautics book but it's not satisfatory (if you know a forum topic or anything related to this subject please send me)

I didn't searched in slack

**Comment by andremacola** [comment] 2019-06-11 08:28
I have 2.15.1 and the webhook jus stopped ( I was on the 2.13....) before update.

Amazon Webhook is working on stable version?

**Comment by aspiers** [comment] 2019-06-11 22:11
One issue was fixed by #7015 although [at least one more seems to still exist](https://github.com/mautic/mautic/pull/7015#issuecomment-498768039).  It is working fine for me on 2.15.1 however.

**Comment by andremacola** [comment] 2019-06-11 22:30
just fixed the problem, see #7593 for more information

**Comment by andremacola** [comment] 2019-06-12 15:15
Ok, not 100% fixed. I validate the URL on Amazon SNS but Mautic do not process

**Comment by nextgens** [comment] 2019-09-16 17:32
There's at least another problem with this... the bounces don't always include a DSN (as documented on https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html)

The following patch fixes it and works for me:
`
--- /tmp/AmazonTransport.php	2019-09-16 17:01:23.749017818 +0000
+++ /var/www/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php	2019-09-16 17:24:07.389972645 +0000
@@ -143,9 +143,10 @@
             if ($message['notificationType'] == 'Bounce' && $message['bounce']['bounceType'] == 'Permanent') {
                 // Get bounced recipients in an array
                 $bouncedRecipients = $message['bounce']['bouncedRecipients'];
+		$bounceCode = array_key_exists('diagnosticCode', $bouncedRecipients) ? bouncedRecipients['diagnosticCode'] : "unknown";
                 foreach ($bouncedRecipients as $bouncedRecipient) {
-                    $this->transportCallback->addFailureByAddress($bouncedRecipient['emailAddress'], $bouncedRecipient['diagnosticCode']);
-                    $this->logger->debug("Mark email '".$bouncedRecipient['emailAddress']."' as bounced, reason: ".$bouncedRecipient['diagnosticCode']);
+                    $this->transportCallback->addFailureByAddress($bouncedRecipient['emailAddress'], $bounceCode);
+                    $this->logger->debug("Mark email '".$bouncedRecipient['emailAddress']."' as bounced, reason: ".$bounceCode);
                 }
 
                 return;
`

**Comment by npracht** [comment] 2019-10-04 13:35
@nickian @namankumar @mellsaid @FranSanchezOria @Youlean can you test https://github.com/mautic/mautic/issues/7877 ?

**Comment by npracht** [comment] 2019-10-04 13:35
I'm closing this issue in favor of https://github.com/mautic/mautic/issues/3655, this is the sam topic.

**Closed by npracht** 2019-10-04 13:35 UTC
Labels: Bug, Ready To Test
