### ISSUE TITLE
Campaign is not  triggering dynamic content

### ISSUE THREAD

**Issue by Kedaranatha** [mautic/mautic#4607] opened 2017-08-07 23:01 UTC
What type of report is this: Bug with dynamic content in Campaign

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
simple action. according to user entry on Mautic entry landing page , display corresponding content on result page "Dynamic content". Currently Campaign doesn't  triggering dynamic content

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.21

### Steps to reproduce:
1. create "Campaign form" with email and location (Los Angeles) (dropdown with fixes selection)
2. create "Entry Landing" page and attache form
3. create "Result Landing" page with [Dynamic content] placeholder for dynamic content: <div class="mautic-slot" data-slot-name="slot111">default content</div>  
4. on "Campaign form"  add redirection url "Result Landing" 
5. create  "Dynamic content" with simple text. " la la la"
6. Create Campaign.
     - Contact Source: "Campaign form" 
     - Trigger action:  Limit to forms: "Campaign form", field: location [equals]  [Los Angeles]
- Request dynamic content: slot: slot111, select default content: "Dynamic content"
7. you can add "push dynamic content" optional
8. go to isolated web browser and complete form
9. result "default content".  Dynamic content not triggered 
10. go to Campaign page see statistics: condition "location = Los Angeles" triggered but  Dynamic content not triggered 

### Log errors: 
no errors at all
server log doest have errors as well
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dirtroof** [comment] 2017-08-11 02:19
Can confirm. Been a weeks since I was last testing this. Will test again shortly and double check error logs. As I recall, there were none, but will double check that.

**Comment by escopecz** [comment] 2017-08-17 07:33
This seems like a duplicate of https://github.com/mautic/mautic/issues/4061, but thanks for the detailed steps to replicate!

**Closed by escopecz** 2017-08-17 07:33 UTC
Labels: Bug, P0
