### ISSUE TITLE
Actions points on email not working with segment emails

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8603] opened 2020-03-27 14:28 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello, 
When you want to sent up an action point on email sent or email opened. you can't select segment email to filter on them.  Action are working on segment email but you can't filter on specific ones because of this.
| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1.  Create a segment email, with a test segment and contact
2. Create an action point on email opening as in the screenshot below :
![image](https://user-images.githubusercontent.com/49391402/77765911-37d24880-703f-11ea-907f-3f9107854012.png)
3. See in the limit to these selected mails that you can't find the mail you create before or any manual email
![image](https://user-images.githubusercontent.com/49391402/77766007-5cc6bb80-703f-11ea-903a-c15bb1e971c9.png)

Thanks !

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-03-27 16:40
I was able to reproduce this on 2.16.1 - I guess it's because changing points based on email opens is assumed to happen as part of a campaign, and hence you wouldn't include segment emails.

So this ideally needs to be able to include both types of emails when you're creating it from /points/new, if it should be possible to add points based on a segment email.

**Comment by florentpetitjean** [comment] 2020-03-31 07:17
Thanks for testing. 
Note that action point works on segment email if you do not specify any email in the action point. So to me it's just the filter that doesn't take segment email in account not the whole change points process !

**Comment by kuzmany** [comment] 2020-04-02 10:42
Let's test: https://github.com/mautic/mautic/pull/8619

**Comment by npracht** [comment] 2020-08-15 09:24
Fixed in 3.0.2 with https://github.com/mautic/mautic/pull/8619

**Closed by npracht** 2020-08-15 09:24 UTC
Labels: bug, enhancement, ready-to-test
