### ISSUE TITLE
Focus item screenshot ends in HTTP 500

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#3616] opened 2017-03-09 10:41 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
When you try to add a new focus item Mautic will take a screenshot of your system. The screenshot itself is created by PhantomJS on "https://mautic.net/api/snapshot".
We now have the situation that this call is timing out (>30s). When this happens, Mautic just returns a HTTP 500.

I think this timeout should be handled properly and we should prompt that message to the user. 

The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.15

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

[2017-03-09 11:10:46] mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Operation timed out after 30000 milliseconds with 0 bytes received" at /var/www/xy/app/vendor/joomla/http/src/Transport/Curl.php line 185
Unknown macro: {"exception"}
[]

**Comment by brunomenoli** [comment] 2017-05-03 11:24
Same error here

Mautic version 2.7.1 - app/prod
PHP Version 5.6

[2017-05-03 07:59:24] mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Operation timed out after 30001 milliseconds with 0 bytes received" at /home/mautic/public_html/mautic/vendor/joomla/http/src/Transport/Curl.php line 185 {"exception":"[object] (RuntimeException(code: 0): Operation timed out after 30001 milliseconds with 0 bytes received at /home/mautic/public_html/mautic/vendor/joomla/http/src/Transport/Curl.php:185)"} []

**Comment by brunomenoli** [comment] 2017-05-03 11:31
@wittwerch do you fixed the error?

**Comment by escopecz** [comment] 2017-05-03 11:48
I cannot replicate the issue. It loads the page for me. The error is caused by timeout. The requested page was not fetched in 30 seconds. Could you share what URL did you put in? Is any other website loading there?

**Comment by escopecz** [comment] 2017-07-03 09:22
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.

**Closed by escopecz** 2017-07-03 09:22 UTC
Labels: Pending Feedback
