### ISSUE TITLE
Can't edit a Focus Item in a Campaign event after create and save

### ISSUE THREAD

**Issue by toledomarcela** [mautic/mautic#6503] opened 2018-08-29 15:14 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
You can not edit a Focus item in a Campaign event after creating a new one, save, and close. Even if you try to edit and save again, when opening the builder of the same campaign you will see that it was not saved.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.1.20

### Steps to reproduce:
1. Create a new campaign and associate a Focus item
2. Access the builder of the same Campaign to edit it and change the Focus item
3. Save and close
4. Opening the Campaign builder again, the changed Focus item was not saved
 
### Log errors: 

_No line appears in the log._

**Comment by toledomarcela** [comment] 2018-08-29 15:15
@npracht Hi. Have you noticed anything like this?

**Comment by RCheesley** [comment] 2020-03-05 20:44
Closing as unable to reproduce this.

**Closed by RCheesley** 2020-03-05 20:44 UTC
Labels: Bug
