### ISSUE TITLE
 [221] Can't change standalone forms fields' order

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#2825] opened 2016-10-25 08:08 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I have just created my first standalone form.
I setup 4 fields
I saved the form
I saw I missed an extra field "phone" asked by my boss
I edit the form and add a new field of type "phone"
I change the field's order to match the design wished
I save again ==> phone field still at the end of the form
Edit again
change order
save ==> still at the end
other data (attributes, message validation, behavior) are well saved

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.12

**Comment by escopecz** [comment] 2016-10-25 08:13
This seems to be duplicate of https://github.com/mautic/mautic/issues/2745

**Closed by escopecz** 2016-10-25 08:13 UTC
