### ISSUE TITLE
New Contact > Number of points mismatch the points log entries

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#5369] opened 2017-11-23 13:26 UTC
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
A new lead just came into our mautic instance
we never never updated it manually.
he only went on the website, navigate to a landing page, submitted a form and downloaded an asset.

This contact has a score of 127 points

when we tried to have the details, we filter on the history on the "point gained" action but we have only 5 entries for a total of 47 points.

![points](https://user-images.githubusercontent.com/930391/33174946-4b4c94f6-d05a-11e7-9a8e-829851e21632.JPG)

Where are the remaining 80 points comes from ?

This is a real world example and customer want to be sure that Mautic points System is 100% sure (despite this field has been set as writable in the edit view of contact since few versions)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.2

**Comment by npracht** [comment] 2017-11-23 13:27
Hello Yannick, which version of mautic are you using ?

**Comment by alanhartless** [comment] 2017-11-23 13:36
Likely a duplicate of https://github.com/mautic/mautic/issues/5188 and will be fixed in 2.12

**Closed by alanhartless** 2017-11-23 13:36 UTC

**Comment by YannickBiet** [comment] 2017-11-23 13:38
@npracht  2.10.1
@alanhartless thanks for pointing out the duplicate (i tried to search before submitting but didn't found this one !)
