### ISSUE TITLE
Impossible to update to the version 2.16.2 - ssl error

### ISSUE THREAD

**Issue by cefimadmin** [mautic/mautic#8852] opened 2020-05-30 13:18 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | PHP Version 5.6.40-0+deb8u11
| Browser | Chrome Version 83.0.4103.61

### Steps to reproduce
1. Clear cache 'php app/console cache:clear'
2. Try to check if an update is available with the command line 'php app/console mautic:update:find'
3. Return a message error : An error occurred while checking for updates. Please try again later.
4. Test my ssl certificate with https://www.ssllabs.com/ssltest/ and its ok
 
### Log errors
mautic.ERROR: An error occurred while attempting to fetch updates: SSL certificate problem: certificate has expired

**Comment by OmerGafny** [comment] 2020-05-31 06:42
Seems pretty straight forward: You need to renew your SSL certificate. Do you use OpenSSL? its pretty simple to renew it with Certbot

**Comment by cefimadmin** [comment] 2020-05-31 08:13
My SSL certificate is valid until 10/12/2020.

**Comment by cefimadmin** [comment] 2020-05-31 09:14
After contact with my host, the problem comes from the root authority certificate that is being renewed.

**Comment by cefimadmin** [comment] 2020-06-01 08:50
Hello,

My host has updated the ssl certificate chain and everything works. But I still have the same error for the update with version 2.16.2

The command 'php app/console mautic:update:find' returns the following error in mautic log : mautic.ERROR: An error occurred while attempting to fetch updates: SSL certificate problem: certificate has expired [] []

Thank you for your help.

**Comment by cefimadmin** [comment] 2020-06-01 13:07
I managed to download the update package with the following command : curl -L https://github.com/mautic/mautic/releases/download/2.16.2/2.16.2-update.zip > 2.16.2-update.zip.

And I don't have any ssl errors like with the command line : 'php app/console mautic:update:find'

**Comment by dsp76** [comment] 2020-06-02 10:12
Same here...

**Comment by Gauss23** [comment] 2020-06-02 11:28
Same here. It seems as if there is something wrong with the SSL cert of `updates.mautic.org`.

Here is what wget is telling me:
```
wget https://updates.mautic.org/index.php?option=com_mauticdownload
--2020-06-02 13:07:19--  https://updates.mautic.org/index.php?option=com_mauticdownload
Resolving updates.mautic.org (updates.mautic.org)... 104.236.73.40
Connecting to updates.mautic.org (updates.mautic.org)|104.236.73.40|:443... connected.
ERROR: The certificate of ‘updates.mautic.org’ is not trusted.
ERROR: The certificate of ‘updates.mautic.org’ has expired.
```

**Comment by cefimadmin** [comment] 2020-06-02 12:00
You are right, the AC certificate COMODO is expired since 30 may.

https://www.ssllabs.com/ssltest/analyze.html?d=updates.mautic.org

COMODO RSA Certification AuthorityFingerprint SHA256: 4f32d5dc00f715250abcc486511e37f501a899deb3bf7ea8adbbd3aef1c412daPin SHA256: grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME=
--
Valid until | Sat, 30 May 2020 10:48:38 UTC (expired 3 days, 1 hour ago)   EXPIRED

**Comment by dsp76** [comment] 2020-06-02 12:31
OMG, spent couple of hours to identify the cause. Thanks @fgauttron !

**Comment by dennisameling** [comment] 2020-06-02 14:20
The SSL certificate of https://updates.mautic.org is valid until the 1st of August 2020:

![image](https://user-images.githubusercontent.com/17739158/83530731-6dd2f380-a4ec-11ea-83be-147f5bb159d9.png)

However, Sectigo's old CA root has expired on May 30. This shouldn't be a problem for modern operating systems:

> Yes. All modern clients and operating systems have the newer, modern COMODO and USERTrust roots which don’t expire until 2038.

More info on the Sectigo website: https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

However, the updates.mautic.org server also seems to be serving the old root certificate:

![image](https://user-images.githubusercontent.com/17739158/83531118-d9b55c00-a4ec-11ea-86b2-460dc0fa3624.png)

We're currently checking what we can do on our side to fix this issue. Will follow up ASAP

**Comment by dennisameling** [comment] 2020-06-02 15:13
@fgauttron @dsp76 @Gauss23 We updated Comodo's intermediate certificate on our server, should be fixed now! SSL Labs [doesn't report errors anymore](https://www.ssllabs.com/ssltest/analyze.html?d=updates.mautic.org):

![image](https://user-images.githubusercontent.com/17739158/83536948-37997200-a4f4-11ea-87b7-78eccea0a711.png)

Please let us know if it works again for you. Apologies for the inconvenience caused!

**Comment by RCheesley** [comment] 2020-06-02 18:11
Thanks for flagging this folks, I'm going to close the issue now as this should be resolved!

**Closed as completed by RCheesley** 2020-06-02 18:11 UTC
Labels: regression
