### ISSUE TITLE
[Feature] Internal reference title in addition to subject

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#451] opened 2015-05-22 15:53 UTC
When I'm working with emails, it's much easier for me to make reference to Email 1, Email 2, etc.

At the moment I have to put 1 -, 2 -, 3 - , etc in front of the emails to make it easier to work with.

I suggest having an internal title for the email, which is separate to the actual email subject, might be a useful option.  Once the campaign launches I find it really difficult to track through and find the right emails!

**Comment by alanhartless** [comment] 2015-05-22 15:55
Hi Ruth,

This is actually a duplicate of https://github.com/mautic/mautic/issues/49 and planned for 1.0.6.

Thanks!
Aaln

**Closed** 2015-05-22 15:55 UTC
Labels: Duplicate
