### ISSUE TITLE
Form buttons are duplicating in clone action

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1267] opened 2015-12-22 07:50 UTC
But cloning and deleting forms (to change it from campaign form to standalone) another form (standalone) was made anything very strange.

There is the result: 
![image](https://cloud.githubusercontent.com/assets/10166840/11950396/3286d2de-a888-11e5-9018-c86ef4084588.png)

Is the fusion of 2 forms I never made it (at least with these camps). 

At begining i had: 
1 contact form
2 campaign forms

I was cloned hte 2 capaign form to change to standalone. 

After clone and some changes in actions I deleted the original campaign forms. Now one of these forms cloned has a mix fileds from contact and the form contact is missing :(

I cannot explain more i'm going to resolve this inmediatly

**Comment by miguelpascual** [comment] 2015-12-22 15:40
Another time...

I cloned a form campaign to standalone and after save it I get a clone plus some unwanted fields

![image](https://cloud.githubusercontent.com/assets/10166840/11958788/3ccf975c-a8ca-11e5-86b0-9e4ffda48658.png)

I think the problem is that: The new cloned form get the id=2 (/s/forms/edit/2) and probably there is still some data from the erased old form

**Comment by miguelpascual** [comment] 2015-12-22 15:42
When I clone a campaign form It is overwriting my contact form (that is the id=2)

**Comment by miguelpascual** [comment] 2015-12-22 15:49
I have a Submit button for each failed clone :S (I can't erase it)
![image](https://cloud.githubusercontent.com/assets/10166840/11959113/f6f8116c-a8cb-11e5-8326-5beb45da582b.png)

**Comment by miguelpascual** [comment] 2015-12-22 15:58
I'll remove the 2 last "enviar" (submit button)
![image](https://cloud.githubusercontent.com/assets/10166840/11959372/3a37315a-a8cd-11e5-8949-39822390da3b.png)

**Comment by miguelpascual** [comment] 2015-12-22 16:02
The data about the form (see the creator was Albert And I'm modifying) 

![image](https://cloud.githubusercontent.com/assets/10166840/11959480/c87c13b8-a8cd-11e5-80de-a753e2486d67.png)

**Comment by duduric** [comment] 2016-02-05 13:14
Have you been able to reproduce it? This happened randomly a few times with us and caused some damage on live landing pages.
I am trying to fix it but just can't reproduce the error.

**Comment by justinroffmarsh** [comment] 2016-04-26 20:26
Exactly this happened to me, just now, cloning a form. Made a hell of mess.

**Comment by dbhurley** [comment] 2016-07-29 17:15
Cannot seem to replicate. I'm closing for now, please reopen or create a new issue if it remains a problem.

**Closed by dbhurley** 2016-07-29 17:15 UTC
Labels: Bug
