### ISSUE TITLE
Fresh new email added to an existing campaign does not reach previously existing contacts

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6445] opened 2018-08-09 15:36 UTC
What type of report is this:
Bug report (Unless it's a feature :-)

## Description:
If you add a new email to an old campaign, contacts that have already gone through the previously existing steps in the campaign will not receive the new emails.
However new people entering the segment and the campaign will receive the new emails.
I also tested adding a delivery time "deep enough into the future" just in case it was some timing issue, made no difference..

The weird thing about it is that mautic seems to process those contacts too, however it decides not to send them and stores them in the "action limbo".

![issue-xxxx](https://user-images.githubusercontent.com/29537089/43909156-f48a7c48-9bf9-11e8-80c7-189b673bd47e.png)

## If a bug:
| Mautic version |  Tested with both 2.13.x and 2.14.0, same results.
| PHP version | 7.0.30

### Steps to reproduce:
1. Add new email to be sent to all contacts in a previously existing campaign. 
2. Add some random delay for delivery ( like 3 minutes).
3. Make some coffee and check your email. (no emails would be sent, at least in my install). 
4 Optionally, add new contacts to the campaign (segment). those WILL receive the new emails.

### Log errors: 
No errors in Mautic log.

**Comment by heathdutton** [comment] 2018-08-09 15:45
Thanks for explaining this in detail.

I believe this is mostly expected behavior, though the chart in actions could probably do a better job of explaining this.

A typical workaround for this scenario, is to have multiple campaigns... chain them so that you can continue to expand on your actions, or you can re-push contacts back into the campaign after it's been updated. 

Ultimately, I think this could be made easier to explain if the campaign UI showed contacts visually as they are going through the tree of events. Once they are done with the campaign, they're done... adding events to the campaign after that fact does not add events for the leads, unless you are allowing the contacts to loop through the campaign.

**Comment by YosuCadilla** [comment] 2018-08-09 16:00
+1
However, why do these get stuck in the pending actions?

**Comment by MRG95** [comment] 2018-08-09 16:02
Duplicated by https://github.com/mautic/mautic/issues/6323

**Comment by npracht** [comment] 2018-08-21 09:51
According to [Alan's comment](https://github.com/mautic/mautic/issues/6323#issuecomment-409591182) this is the expected behavior.
Where you are right, is that in consequence it should not be in the pending emails.

**Comment by MRG95** [comment] 2018-08-21 10:00
He was wrong in his comment. He says that they can't let new events added to the end of a campaign apply to existing contacts that have reached that end... except for some reason, adding a decision action does JUST THAT.

So on one hand, our suggestion is an impossible doomsday event, yet you can do it right now if you just use a decision action... Why do decision actions have this property? That mentioned "problem" already exists now.

That's why Alan is wrong.

Now... Should existing contacts get new events added to events that have already passed? No. No one is requesting that.... But should existing contacts get new events added to events they have NOT passed? (Cant pass the final event). Absolutely, and they already do for decision events.

**Comment by dichvuhuuich** [comment] 2018-12-20 07:21
Is there any news on version 2.15?

**Comment by heathdutton** [comment] 2018-12-20 08:11
These show up under "Pending" because "Pending" actually means "Pending or Non Action Path Taken". The text is misleading.

@MRG95  decisions are different because it's an intentional "wait" on the contact to re-enter the campaign. Again, this is expected behavior, but obviously confusing... We need to be thinking about how to make it less so in the future. 

The best way to handle this (in my opinion) is by creating a segment based on those who have gone through another campaign, (campaign membership + delay) and feed those into a follow-up campaign. At least in that scenario you end up with a clean understanding of where the leads are from the old version of the campaign to the second. @dichvuhuuich this is available functionality in 2.15.0

**Comment by alexhammerschmied** [comment] 2019-12-03 14:25
Are there any news to that? It is still behaving like that and the contacts "are" still in pending. 
But if I understood it correctly, the contacts are actually no more inside the campaign. Is that true?

**Comment by RCheesley** [comment] 2020-02-10 18:21
I'm going to close this issue down as the issue reported is expected behaviour and a workaround is suggested (chaining campaigns). 

If you feel that the 'pending' status should be updated to be more reflective of the fact that it includes 'non action path taken' then please flag that up as a separate issue if it isn't already added.

**Closed by RCheesley** 2020-02-10 18:21 UTC
Labels: Bug, User Interface

**Comment by masonkeefe93** [comment] 2021-11-23 19:31
Hi Ruth,

Apologies for bumping a dead thread however I am struggling to find any other info on this on both the Mautic forums and Github.

This was reported as expected functionality however has the ability to allow these pending emails from old campaign contacts been enabled at all in Mautic 4? We are still on Mautic 2 so are wondering if it is worth upgrading to fix this...

Regarding the workaround, is there an easier way to achieve a campaign which can add new emails and also have them send to existing contacts within the campaign?

Many thanks for your time

**Comment by ahmad-mushtaq** [comment] 2024-03-18 22:04
> Hi Ruth,
> 
> Apologies for bumping a dead thread however I am struggling to find any other info on this on both the Mautic forums and Github.
> 
> This was reported as expected functionality however has the ability to allow these pending emails from old campaign contacts been enabled at all in Mautic 4? We are still on Mautic 2 so are wondering if it is worth upgrading to fix this...
> 
> Regarding the workaround, is there an easier way to achieve a campaign which can add new emails and also have them send to existing contacts within the campaign?
> 
> Many thanks for your time

I would like inquire about this too. How to add emails to existing campaign making sure the contacts that previously ran through it also get that newly added email. thanks in advance
