### ISSUE TITLE
Feature Request - Add campaign decision "email click"

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1009] opened 2015-10-14 14:03 UTC
Hi,

It would be awesome to filter in a campagne (add a decision) by **"click in the email"** and depending on that decide different action. That's the step after **"email open"**.
The best would be also to be able to select *which* link is clicked.

**On of the option would be instead of adding a new label "email click" to drag and drop, to change the label by "email action"** and there select if the lead:
* Open
* Click
* Visit webpage (after email)
* Unsubscribe
* Bounce

N.

**Comment by that0n3guy** [comment] 2015-10-19 13:52
Some of this is a duplicate of https://github.com/mautic/mautic/issues/124 ... FYI

**Closed** 2015-10-19 14:34 UTC
