### ISSUE TITLE
Add contacts manually not refreshing

### ISSUE THREAD

**Issue by daniellord32** [mautic/mautic#11827] opened 2022-12-20 11:01 UTC
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

Testing for the weekly friday tests.

I was testing companies and noticed that when I added a contact using the quick add button, the modal window did not close and the page did not refresh. The modal window remained with greyed out buttons. manually refreshing the page then showed the notification that the contact was added and the table displayed the newly created contact.

Editing a contact clicking save and close again did not refresh the page. buttons remained greyed out. Manually refreshing the page did show that the change persisted to the DB

### How can we reproduce this issue?

Step 1:  Create a company and go back to the table displaying that there is 0 contacts.
step 2. click on the blue contacts 0 box
step 3. use the quick add option to add a contact.
step 4. click the save button
step 5. manually refresh the page
step 6. the addition should be saved and a notification should display

### Relevant log output

```shell
No error logs were thrown.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-12-20 11:13
I think this is probably a duplicate of https://github.com/mautic/mautic/issues/11823

**Closed as not planned** 2022-12-20 11:13 UTC
Labels: bug, duplicate, needs-triage
