### ISSUE TITLE
Images in page builder don't appear on live page without additional text

### ISSUE THREAD

**Issue by drmmr763** [mautic/mautic#223] opened 2015-03-26 14:21 UTC
This issue can be confusing so pay attention:

Reproduce:
1) make new page
2) add logo to a div area (with no other text / content in that area)
3) save & preview
4) image shouldn't be there.
5) add some text to the same area as the image, save & preview - image shows
6) removing the text will sometimes allow the image to stick around, and sometimes not. Something with the markup in the div area is allowing it to parse. 

Related forum topic: https://www.mautic.org/community/index.php/179-issue-with-page-builder/p1#p896

**Comment by alanhartless** [comment] 2015-04-01 03:56
Duplicate of issue #189.

**Closed** 2015-04-01 06:14 UTC
Labels: Bug
