### ISSUE TITLE
Social Monitoring view broken in 2.6.0

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#3418] opened 2017-02-13 13:45 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Since upgrading to 2.6.0 from 2.5.1, when I click into any of the Social Monitoring channels I have set up, I get this error message:

![image](https://cloud.githubusercontent.com/assets/14789786/22885707/812fa10e-f1f2-11e6-9546-669977757428.png)

Relevant log file output shown below.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 5.6.23

### Log errors: 
`[2017-02-13 12:15:32] mautic.NOTICE: PHP Notice - unserialize(): Error at offset 194 of 330 bytes - in file /var/www/campaign/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []
[2017-02-13 12:15:32] mautic.NOTICE: PHP Notice - unserialize(): Error at offset 164 of 327 bytes - in file /var/www/campaign/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []
[2017-02-13 12:15:32] mautic.NOTICE: PHP Notice - unserialize(): Error at offset 183 of 298 bytes - in file /var/www/campaign/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []
[2017-02-13 12:15:32] mautic.ERROR: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "mautic__contacts" as such route does not exist. - in file /var/www/campaign/app/cache/prod/appProdProjectContainerUrlGenerator.php - at line 200 [] []`

**Comment by escopecz** [comment] 2017-02-13 16:56
Duplicate of https://github.com/mautic/mautic/issues/3391

**Closed by escopecz** 2017-02-13 16:56 UTC
