### ISSUE TITLE
Custom multi choice fields break save action with 500

### ISSUE THREAD

**Issue by enableit** [mautic/mautic#7344] opened 2019-03-22 13:07 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Running 2.15.1-beta, saving custom fields of type multi choice cause the save of contacts and accounts to break with a 500 error

| Q   | A
| --- | ---
| Mautic version | 2.15.1-beta
| PHP version | 7.0
| Browser | Firefox Dev

### Steps to reproduce
1. Create a custom field of type multichoice on a contact or company
2. Attempt to create a new record or edit an existing record on the entity where the custom field has been added

Expected Result: Record saves
Actual Result: 500 error
 
### Log errors
[2019-03-22 12:39:49] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at /WEBROOT/vendor/symfony/validator/Constraints/LengthValidator.php line 38 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"string\", \"array\" given at /WEBROOT/vendor/symfony/validator/Constraints/LengthValidator.php:38)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by enableit** [comment] 2019-03-25 08:26
The bug was introduced in this commit https://github.com/mautic/mautic/commit/9d1bfbbdb00cd6e53dbb09da8101808b0a3ae5ad

**Comment by npracht** [comment] 2019-03-28 09:42
@alanhartless can you advise ?

**Comment by Jhos-duall** [comment] 2019-03-28 15:14
Same problem.

**Comment by kuzmany** [comment] 2019-03-28 16:23
Quick fix https://github.com/kuzmany/mautic/tree/fix-multiple-custom-fild

**Comment by lipnotic** [comment] 2019-03-30 06:55
Same problem here

**Comment by lipnotic** [comment] 2019-03-30 08:12
@kuzmany 's FIX mentioned above fixed my form freezing while sending.
NICE!

**Comment by npracht** [comment] 2019-04-01 12:47
@enableit @lipnotic please test #7375

**Comment by hluchas** [comment] 2019-04-02 08:01
I'm sorry about this. Forgot to create/use specific validator.

**Comment by autoize** [comment] 2019-04-02 18:12
@npracht @kuzmany 

Applying #7376 fixes the form submit issue, but there is a problem with the lead that is created.
It cannot be deleted from the contact list 

Before the patch, we get this error with the form submit hanging like other commenters above.

`[2019-04-02 13:43:40] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at /var/www/html/vendor/symfony/validator/Constraints/LengthValidator.php line 38 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"string\", \"array\" given at /var/www/html/vendor/symfony/validator/Constraints/LengthValidator.php:38)"} []`

After the patch, trying to delete the contact from the contact list results in these errors. 
Trying to apply #7375 also does not help.

```
[2019-04-02 13:57:40] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.text AS text_12, t0.type AS type_13, t0.date_time AS date_time_14, t0.attachment AS attachment_15, t0.lead_id AS lead_id_16 FROM lead_notes t0 WHERE t0.lead_id = ? ORDER BY t0.date_added DESC' with params [96202]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.text AS text_12, t0.type AS type_13, t0.date_time AS date_time_14, t0.attachment AS attachment_15, t0.lead_id AS lead_id_16 FROM lead_notes t0 WHERE t0.lead_id = ? ORDER BY t0.date_added DESC' with params [96202]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-04-02 13:57:48] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.text AS text_12, t0.type AS type_13, t0.date_time AS date_time_14, t0.attachment AS attachment_15, t0.lead_id AS lead_id_16 FROM lead_notes t0 WHERE t0.lead_id = ? ORDER BY t0.date_added DESC' with params [96202]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.text AS text_12, t0.type AS type_13, t0.date_time AS date_time_14, t0.attachment AS attachment_15, t0.lead_id AS lead_id_16 FROM lead_notes t0 WHERE t0.lead_id = ? ORDER BY t0.date_added DESC' with params [96202]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-04-02 13:57:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT l0_.is_published AS is_published_0, l0_.date_added AS date_added_1, l0_.created_by AS created_by_2, l0_.created_by_user AS created_by_user_3, l0_.date_modified AS date_modified_4, l0_.modified_by AS modified_by_5, l0_.modified_by_user AS modified_by_user_6, l0_.checked_out AS checked_out_7, l0_.checked_out_by AS checked_out_by_8, l0_.checked_out_by_user AS checked_out_by_user_9, l0_.id AS id_10, l0_.text AS text_11, l0_.type AS type_12, l0_.date_time AS date_time_13, l0_.attachment AS attachment_14 FROM lead_notes l0_ WHERE l0_.lead_id = ? ORDER BY l0_.date_time DESC) dctrn_result) dctrn_table' with params [96202]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l0_.attachment' in 'field list'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT l0_.is_published AS is_published_0, l0_.date_added AS date_added_1, l0_.created_by AS created_by_2, l0_.created_by_user AS created_by_user_3, l0_.date_modified AS date_modified_4, l0_.modified_by AS modified_by_5, l0_.modified_by_user AS modified_by_user_6, l0_.checked_out AS checked_out_7, l0_.checked_out_by AS checked_out_by_8, l0_.checked_out_by_user AS checked_out_by_user_9, l0_.id AS id_10, l0_.text AS text_11, l0_.type AS type_12, l0_.date_time AS date_time_13, l0_.attachment AS attachment_14 FROM lead_notes l0_ WHERE l0_.lead_id = ? ORDER BY l0_.date_time DESC) dctrn_result) dctrn_table' with params [96202]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l0_.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l0_.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l0_.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-04-02 13:57:56] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.text AS text_12, t0.type AS type_13, t0.date_time AS date_time_14, t0.attachment AS attachment_15, t0.lead_id AS lead_id_16 FROM lead_notes t0 WHERE t0.lead_id = ? ORDER BY t0.date_added DESC' with params [96202]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.text AS text_12, t0.type AS type_13, t0.date_time AS date_time_14, t0.attachment AS attachment_15, t0.lead_id AS lead_id_16 FROM lead_notes t0 WHERE t0.lead_id = ? ORDER BY t0.date_added DESC' with params [96202]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.attachment' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
```

**Comment by pety-dc** [comment] 2019-04-04 09:10
@kuzmany I applied your quickfix to this error. The patch fixed the 500 error, but it seems that multiselect values are not saved or reloaded properly
I edit a contact, pick a value for a multiselect field, save, the values are present when I inspect the contact's details, but disappear when I start editing the contact again.

Will #7375 solve this?

**Comment by hluchas** [comment] 2019-04-04 09:20
@pety-dc Cannot reproduce here.

**Comment by kuzmany** [comment] 2019-04-04 09:26
@pety-dc definitely https://github.com/mautic/mautic/pull/7375 is solution

**Comment by autoize** [comment] 2019-04-04 14:52
Applying both #7376 and #7375 worked for our instances. No problems so far.

**Comment by pety-dc** [comment] 2019-04-08 16:02
@kuzmany 

I applied both #7376 and then #7375 

#7376 puts `$typeProperties['data']        = $type === 'multiselect' ? FormFieldHelper::parseList($value) : $value;` to the top of the switch case in ` app/bundles/LeadBundle/Form/Type/EntityFieldsBuildFormTrait.php`

In row 177. it then gets overwritten by redeclration of `$typeProperties`
select, multiselect and boolean types are affected. 

@autoize How could it work for you?

**Comment by hluchas** [comment] 2019-04-08 16:34
#7375 is solution for problem described in this issue. There is noting about modifying variables or database queries. So other problems are not related I think.

**Comment by npracht** [comment] 2019-04-18 07:30
Merged in 2.15.2

**Closed by npracht** 2019-04-18 07:30 UTC
Labels: Bug, Ready To Commit

**Comment by sambarnes90** [comment] 2019-05-20 20:56
This was affecting all of my forms but #7375 did fix it.

Great work @hluchas!

Followed this very useful guide to apply it on my live instance without any issues: https://autoize.com/applying-testing-mautic-patches-pull-requests/

**Comment by mcgumbel** [comment] 2019-07-08 14:53
Applying both [#7376](https://github.com/mautic/mautic/pull/7375) and [#7375](https://github.com/mautic/mautic/pull/7375) worked for us too. We are using 2.15.1
@autoize for putting together the "how apply patches" and @sambarnes90 for posting it here.
