### ISSUE TITLE
Social Monitoring doesn't work

### ISSUE THREAD

**Issue by giampyart** [mautic/mautic#4112] opened 2017-05-22 13:30 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Social monitoring doesn't work, I tried but no contacts come into Mautic.
I've Twitter plugin activated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1 and 2.5.1
| PHP version |  5.6.30

### Steps to reproduce:
1. Create a social monitoring campaign with your # and publish
2. No contacts come into Mautic

### Log errors: 
mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in .../app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 967 and defined (uncaught exception) at .../app/bundles/PluginBundle/Helper/oAuthHelper.php line 38 while running console command `mautic:social:monitoring` [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-05-22 13:41
Duplicate of https://github.com/mautic/mautic/issues/4100

**Closed by escopecz** 2017-05-22 13:41 UTC
