### ISSUE TITLE
Bug in Campaign Builder when using Push Dynamic Content

### ISSUE THREAD

**Issue by senoltapirdamaz** [mautic/mautic#3160] opened 2016-12-29 22:46 UTC
What type of report is this:

| Q  |
| ---| ---
| Bug report? | 

## Description:
Please see this video https://youtu.be/MzYcAtG0lMw

When in Campaign, in the Builder
after I select action Push Dynamic Content. It disappears. 
See the video. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0 
| PHP version |  5.6.29-1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

[2016-12-29 22:16:58] mautic.NOTICE: PHP Notice: Undefined variable: leadPreference - in file /var/www/------------/app/bundles/CoreBundle/Model/TranslationModelTrait.php - at line 126 [] []
[2016-12-29 22:16:58] mautic.ERROR: Deprecation: The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. - in file /var/www/----------/app/cache/prod/classes.php - at line 1277 [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mikeamcbrien** [comment] 2017-03-10 15:55
From my understanding, it is operating as intended. I have done quite a bit of testing with Dynamic content and it appears the use case for the video example given by Mautic is fairly limited, and only really helpful if you plan on creating a boatload of inefficient campaign tree's.

What I have found is that I can use code in the dynamic content and use tokens and display customized data. The WYSIWYG editor does not support the tokens, but if you go to code view, you can manually paste them. Check out my suggestion/request here.... #3644 

While this may not be you use case scenario, and your name video example was purely for an example finding out I could do this certain expanded how I will be approaching dynamic content. I hope this helps and I hope to see more examples of people using Dynamic Content because it is super powerful in marketing!

**Comment by escopecz** [comment] 2017-03-10 18:59
I think the issue from the video was fixed already in some version between 2.0.0 and 2.7.0. Try to upgrade and if it won't fix it, let us know and we'll reopen this issue.

**Comment by senoltapirdamaz** [comment] 2017-03-10 21:49
@escopecz  / John, 

Push Dynamic content is all gone in V2.7
![image](https://cloud.githubusercontent.com/assets/24833293/23814451/e0aff28c-05e3-11e7-818d-3b802a859a8d.png)

**Comment by jordan8037310** [comment] 2017-06-18 16:57
I think it is because you need to check for a condition that the lead has some field before you can push dynamic contact. Action must follow condition.

**Closed** 2017-06-19 07:11 UTC
