### ISSUE TITLE
Feature request: dynamic content in emails based on variables

### ISSUE THREAD

**Issue by cspenn** [mautic/mautic#1745] opened 2016-05-15 23:42 UTC
# Idea

Control email output with conditional variables.

## Description

PHP or variable based dynamic content based on user data. For example, suppose you had an email with this basic content:

- Intro
- Story
- Offer
- Conclusion

But suppose you know who your best customers are. Maybe you have their name, or their title. What if we could have the email above and then a block of code in the email?

- Intro

(if score > 50 AND firstname IS NOT NULL and lastname IS NOT NULL and title like '%CEO%'){
- SPECIAL OFFER!
}

- Story
- Offer
- Conclusion

At runtime, one email would be sent, but rendered differently based on database fields.

**Comment by escopecz** [comment] 2016-05-16 06:57
Thanks for the feature request, but it seems like duplicate of https://github.com/mautic/mautic/issues/849

**Closed by escopecz** 2016-05-16 06:57 UTC
