### ISSUE TITLE
Short URL feature

### ISSUE THREAD

**Issue by trevorhutt** [mautic/mautic#66] opened 2015-02-24 03:17 UTC
If there is not one already, can a URL shortening feature be added into Mautic to generate a track URLs that may be shared online?

**Comment by alanhartless** [comment] 2015-02-25 05:21
We don't yet but definitely plan to add this!

Thanks,
Alan

**Comment by alanhartless** [comment] 2015-07-16 15:55
Just noticed this is a duplicate of #39 so closing in favor of it.

**Closed by alanhartless** 2015-07-16 15:55 UTC
Labels: Feature Request
