### ISSUE TITLE
Form submission not working when user is logged on Mautic

### ISSUE THREAD

**Issue by rc125** [mautic/mautic#4462] opened 2017-07-18 18:53 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Form submission not workinking when the user is logged on Mautic

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.0

### Steps to reproduce:
1. Apply PR [#4415](https://github.com/mautic/mautic/pull/4415)
2. Create a Form
3. On Submit Action add "Modify contact's segments" and add the contact to a segment
4. Submit Form
 
### Log errors: 

`[2017-07-17 20:42:39] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\LeadBundle\Entity\ListLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 `

**Comment by escopecz** [comment] 2017-07-26 09:33
I'll close this issue in favour of https://github.com/mautic/mautic/issues/4520 since its title describes the problem better.

**Closed by escopecz** 2017-07-26 09:33 UTC
Labels: Bug

**Comment by gingerling** [comment] 2017-07-29 06:55
I don't think it's the same issue, I have been meaning to report this myself. I have found when I am logged in to mautic and test a form, the form throws a 404. It works okay in a private browsing session so it seems being logged in is the cause. I read some of the 404 thread and wasn't sure if it was related or not.

**Comment by gingerling** [comment] 2017-07-29 06:56
To clarify, by "test a form" I mean fill one out. Applies to both mautic pages and forms embedded on other pages.
