### ISSUE TITLE
Segment-Filter: All "Visited URL" values removed after update to 4.2.0

### ISSUE THREAD

**Issue by LeonOltmanns** [mautic/mautic#10990] opened 2022-03-22 09:50 UTC
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

After updating to 4.2.0 I have realized that all my "Visited URL" Segment-Filters seemed to have no value anymore. 
The values are missing and the operators are not there anymore. 

Also, when updating Segments I encountered an MySQL error. 

`Rebuilding contacts for segment 160
In ForeignValueFilterQueryBuilder.php line 103:
Method name must be a string`

![image](https://user-images.githubusercontent.com/55587275/159451672-1066dafc-1072-4eaf-acf7-8898ade6f417.png)

### How can we reproduce this issue?

Step 1: Go to a Mautic 4.1 Instance or lower
Step 2: Create a segment
Step 3: Use "Visited URL" filter
Step 4: Use "Equals" als operator and a random URL as Value
Step 5: Update to Mautic 4.2
Step 6: Open the Segment to see that the Values and Operators are gone

### Relevant log output

```shell
[2022-03-22 09:45:27] mautic.NOTICE: Error: Method name must be a string (uncaught exception) at /var/www/m.mauticinstance/htdocs/app/bundles/LeadBundle/Segment/Query/Filter/ForeignValueFilterQueryBuilder.php line 103 while running console command `mautic:segments:update` [] []

[2022-03-22 09:45:27] mautic.WARNING: Command `mautic:segments:update` exited with status code 1 [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-03-22 10:49
Thanks for raising the bug @oltmanns-leuchtfeuer but this is I believe a duplicate of existing issues which are already resolved.

Please review:

https://github.com/mautic/mautic/issues/10962
https://github.com/mautic/mautic/issues/10947

And the PR to fix:

https://github.com/mautic/mautic/pull/10985

If this is not the case and it's not resolved with the PR above please let me know and I'll re-open the issue.

**Comment by LeonOltmanns** [comment] 2022-03-22 12:19
@RCheesley  I applied the PR #10985, but it did in fact not solve my problem. My issue, that my Field-Values are gone and I cannot reproduce them is still persisting.

See here:
![image](https://user-images.githubusercontent.com/55587275/159480316-6a4c04b9-fbfd-4e30-a815-ea5b7102ac8f.png)

Im unable to investigate which Value, in this case which URL was here before.

**Comment by RCheesley** [comment] 2022-03-22 12:20
And, you have regenerated assets?

**Comment by LeonOltmanns** [comment] 2022-03-22 12:21
Yep I did. Did not change the problem.

**Comment by RCheesley** [comment] 2022-03-22 12:24
@escopecz another possible issue with the segments refactoring?

**Comment by RCheesley** [comment] 2022-03-22 12:25
OK thanks for checking it out - will have to dig in and see what's going on! We did some very heavy segment refactoring in 4.2 and it looks like a couple of thing have slipped through the net with testing.

**Comment by escopecz** [comment] 2022-03-25 09:07
I cannot reproduce. @oltmanns-leuchtfeuer did you run `bin/console mautic:assets:generate` after applying https://github.com/mautic/mautic/pull/10985?

**Comment by LeonOltmanns** [comment] 2022-03-25 09:48
@escopecz Yea I did run `bin/console mautic:assets:generate` after applying the PR. Matter of fact is, that the values of my "Visited URL" Filter are still gone. Checked of multiple instances that have been update to 4.2.0 to rule out a single edge case here.

For example:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/55587275/160096356-fec881d3-e6b6-4607-b7aa-4f372661544b.png">

The upper, red marked filter is the old one, which was there pre 4.2.0 update. Both the operator and value seem to be missing and the filter is broken as I cannot even see the value-field anymore. Beneath a newly created working URL-Filter.

Also, the upper filter used to be named "Visited URL" pre-update and post update it is named "Visited X URL" and is broken.

**Comment by escopecz** [comment] 2022-03-25 10:41
Gotcha. I can replicate if I create the segment on the 4.1 branch and then open it in the 4.x branch. This is how it is saved on 4.1:
```php
array (
    'glue' => 'and',
    'field' => 'hit_url',
    'object' => 'lead',
    'type' => 'text',
    'filter' => 'unicorn',
    'display' => NULL,
    'operator' => '=',
  ),
```
And this is on 4.x:
```php
array (
    'glue' => 'and',
    'field' => 'hit_url',
    'object' => 'behaviors',
    'type' => 'text',
    'operator' => '=',
    'properties' => 
    array (
      'filter' => 'unicorn',
    ),
  ),
```
The problem is not with moving the filter to the properties array. That is working nicely. The problem is that the object has changes from `lead` to `behaviors` and the code cannot find the operators for such field anymore.

It was introduced in https://github.com/mautic/mautic/pull/7194 that was merged to the big segment refactoring PR.

I have the fix ready and working on automated tests. Stay tuned.

**Comment by escopecz** [comment] 2022-03-25 11:02
Ready to test: https://github.com/mautic/mautic/pull/11003

**Closed as completed** 2022-03-25 13:45 UTC
Labels: bug, regression, segments
