### ISSUE TITLE
Three attempts to select category

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#25] opened 2015-01-28 20:44 UTC
To reproduce this setup some categories for emails on a clean install
Visit another page
Select manage emails
Try to click on the first category it will unselect itself
Try again  it will unselect itself
Try again it will be selected

Tested with chrome osx on mautic.com

**Comment by alanhartless** [comment] 2015-01-28 21:00
Hey Brian,

I tried to reproduce this one and am not having much luck.  Tried using chrome OS X along with firefox and safari on mautic.com, local beta3 and the latest git source.

Could there be a step missing in order to reproduce it?  

Thanks!
Alan

**Comment by brianteeman** [comment] 2015-01-28 21:04
And now it works

I could replicate it at will before

On 28 January 2015 at 21:00, Alan Hartless <notifications@github.com> wrote:

> Hey Brian,
>
> I tried to reproduce this one and am not having much luck. Tried using
> chrome OS X along with firefox and safari on mautic.com, local beta3 and
> the latest git source.
>
> Could there be a step missing in order to reproduce it?
>
> Thanks!
> Alan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/25#issuecomment-71914958>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by freak3dot** [comment] 2015-01-28 21:08
Were you replicating it at will when you had two categories with the same name?

**Comment by brianteeman** [comment] 2015-01-28 21:13
yes

On 28 January 2015 at 21:08, Ryan Johnston <notifications@github.com> wrote:

> Were you replicating it at will when you had two categories with the same
> name?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/25#issuecomment-71916292>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alanhartless** [comment] 2015-01-28 21:16
I've seen this behavior when we had bad ajax that updated the same elements that triggered the ajax request to begin with.  But that doesn't seem to be the case here as only the list area is returned.

**Comment by brianteeman** [comment] 2015-01-28 23:00
Managed to repeat it and record it

https://www.dropbox.com/s/1kw07ue7u0bll0m/mauticselect.mp4?dl=0

**Comment by alanhartless** [comment] 2015-01-28 23:16
Do you by chance see any JS errors in the browser's developer console?  There is some JS associated with those checkboxes that toggle active classes for their parents.  But other than that, I'm not sure what else would be unchecking those.

**Comment by brianteeman** [comment] 2015-01-28 23:21
Sorry no

On 28 January 2015 at 23:16, Alan Hartless <notifications@github.com> wrote:

> Do you by chance see any JS errors in the browser's developer console?
> There is some JS associated with those checkboxes that toggle active
> classes for their parents. But other than that, I'm not sure what else
> would be unchecking those.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/25#issuecomment-71937441>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alanhartless** [comment] 2015-01-28 23:38
Thanks for checking. One more question :-) Do you have the chat addon enabled? I'm trying to rack my brain on what could be causing these anomalies.  If I remember correctly, there was a now fixed issue where the frequent Ajax requests from the chat addon caused all of the main content's JS events to be rebound. I did a quick search through commit history to see if I could find it as I can't remember if that was before or after beta 3. But didn't  immediately so will have to check when I get back to my Mac.  (Once we get the community edition stable, Mautic.com will be changing those to sockets).

**Comment by brianteeman** [comment] 2015-01-29 00:02
All the tests I have done have been on mautic.com

On 28 January 2015 at 23:38, Alan Hartless <notifications@github.com> wrote:

> Thanks for checking. One more question :-) Do you have the chat addon
> enabled? I'm trying to rack my brain on what could be causing these
> anomalies. If I remember correctly, there was a now fixed issue where the
> frequent Ajax requests from the chat addon caused all of the main content's
> JS events to be rebound. I did a quick search through commit history to see
> if I could find it as I can't remember if that was before or after beta 3.
> But didn't immediately so will have to check when I get back to my Mac.
> (Once we get the community edition stable, Mautic.com will be changing
> those to sockets).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/25#issuecomment-71940421>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alanhartless** [comment] 2015-01-29 00:08
The chat addon can be enabled/disabled per mautic.com instance. It's not enabled by default.

I've tried to replicate these issues on mautic.com as well but not having luck.  Obviously they exist so something is going on. 

I apologize for keep coming back for more information; but until I can reproduce it myself, it's hard for me to track down the cause.  But I'll keep trying!

Thanks,
Alan

**Comment by brianteeman** [comment] 2015-01-29 00:11
I 100% understand the frustration with not being able to replicate issues.

The mautic.com site was vanilla. I have only tried to do the stuff that you
have seen me report issues on.

Are you using chrome on osx ? Maybe its related to that?

On 29 January 2015 at 00:08, Alan Hartless <notifications@github.com> wrote:

> The chat addon can be enabled/disabled per mautic.com instance. It's not
> enabled by default.
>
> I've tried to replicate these issues on mautic.com as well but not having
> luck. Obviously they exist so something is going on.
>
> I apologize for keep coming back for more information; but until I can
> reproduce it myself, it's hard for me to track down the cause. But I'll
> keep trying!
>
> Thanks,
> Alan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/25#issuecomment-71944009>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alanhartless** [comment] 2015-01-29 00:14
Yea, Version 40.0.2214.93 (64-bit) on Yosemite.

**Comment by brianteeman** [comment] 2015-01-29 00:16
ok well its not that then

On 29 January 2015 at 00:14, Alan Hartless <notifications@github.com> wrote:

> Yea, Version 40.0.2214.93 (64-bit) on Yosemite.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/25#issuecomment-71944664>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MaxOnTheHill** [comment] 2015-01-29 01:15
wondering if it could be a chrome extension ... have had that previously causing js not to function correctly, especially with jQueryUI ... but not sure if that would be an issue here if nothing is reported in the dev concole?

**Comment by alanhartless** [comment] 2015-01-29 01:21
I was just studying Brian's videos and in both the category delete and the checkboxes getting unchecked, it's like the events are firing twice.  With the batch delete, it deletes the category on first fire, then tries again on second fire leading to the not found message.  On the checkboxes, it checks them on the first fire, then unchecks them on the second.  So the question is, what is causing the double binding of the events. That's what I'm trying to go backwards in the code and looking at the ajax requests to see if I can figure out if it's something on our side.

**Comment by brianteeman** [comment] 2015-02-04 18:29
If you cant replicate it I think this may be an issue with my mac as today I have seen similar behaviour on other completely unrelated sites when trying to check the box

**Comment by alanhartless** [comment] 2015-02-05 02:35
Thanks Brian,

Going to close this for now then as I never could reproduce. But if you find out otherwise, definitely let us know!

Thanks,
Alan

**Closed by alanhartless** 2015-02-05 02:35 UTC
