### ISSUE TITLE
OAuth1 API is BROKEN in v2.7.1! Where is the API OAuth2 documentation?

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#3679] opened 2017-03-15 10:17 UTC
API with OAuth1 (which is the ONLY thing I'll ever wanna use because I have better things to do than "re-authorize" the OAuth2 crap), anyway, 
API with OAuth1 used to work perfectly in v2.5.1.
Now, when trying to setup API connection in Wordpress with Mautic v2.7.1 I get this (after having done the exact same setup I had with Mautic v2.5.1): 
![mautic 2017-03-15_10-51-22](https://cloud.githubusercontent.com/assets/20304781/23942722/891faa3e-096d-11e7-99a2-40b9208c922a.jpg)
Do I need this? Do I want this?
NO! I don't! 
Why is it broken? When can I start using Mautic in production environment?

Here's a suggestion: 
Why don't you guys stop adding any new features for the next 6 months and focus on turning Mautic into something that can actually be used in the production environment? 
Is it a bad idea? I know, constantly adding new features is fun, but don't you think creating something that would be usable in the production environment would be a good idea?

I really wish I could spare this rant but I can't because: 
After realizing that OAuth1 API is broken now in v2.7.1 I go ahead to create OAuth2 API (even though I'd normally prefer to avoid OAuth2 like a pest).
I'm then asked to enter the "redirect URI".
BUT: 
**There's NO fucking explanation as to what this "redirect URI" might be, where to find it or how it might look like!** 
So, I go to: https://mautic.org/docs/en/index.html
I do a search for "API".
No fucking matches! 
There's not a single word in the table of contents in the documentation that contains the word "API"! 
So, I go ahead and enter the URL of my site into the "redirect URI" field in the hope that I might just get lucky without having a clue as to what I'm actually supposed to enter there.
And of course it doesn't work! 
I get this error: 
`{"errors":[{"message":"The redirect URI provided does not match registered URI(s).","code":400,"type":"redirect_uri_mismatch"}],"error":"redirect_uri_mismatch","error_description":"The redirect URI provided does not match registered URI(s). (`error` and `error_description` are deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"}`

So, here's another suggestion: 
Why don't you guys stop adding any new features for the next 6 months and focus on creating a documentation that is actually readable by a human AND can be understood by an average user?

**Comment by abooster** [comment] 2017-03-15 11:15
Here's a serious suggestion for you guys: 

**If Mautic is not a game (intended to kill time with), 
If Mautic is supposed to be a business application intended for use in production,** 
then I suggest you adopt the following strategy: 

After every major release, spend **at least 6 months purely on fixing the bugs** and updating the documentation. 
Do NOT add any new features until you reach a version number that ends with ".9". 

That way, people who actually want to use Mautic in production environment in business would just stick to versions that end with ".9" and regard all other versions as purely experimental. 

I'm sure there will be plenty users who are eager to try the experimental versions. 
But for those folks who want to use it in business, they need to have a version that's actually usable in production and my guess is that after spending 6+ months on fixing the bugs a major release will become ready for production. 

Then and only then you can introduce a new major release.
Trust me, you'll gain a lot more fans and users if you do it this way. 

I will also be eager to test experimental versions and will do my best to report the bugs I'll find. 
But so far I have wasted countless hours on versions that I believed to be production-ready only to find out that all those versions are purely experimental and are not designed to be used in a production environment. Such an experience DOESN'T make a fan.

**Comment by abooster** [comment] 2017-03-15 12:25
Here's a quote from another user from a post in this thread: 
https://www.mautic.org/community/index.php/5389-urgent-if-you-update-and-are-using-thrive-api-integration/0
> **I can't figure out what exactly belongs in the redirect uri box when I try to set up the oAuth2 at Mautic to get the keys**

Of course, he can't figure that out. No one can. Because there's NO DOCUMENTATION!

I just tried ALL of the suggestions for the "redirect URI" from that forum thread and all I get when trying to setup an OAuth2 connection in Wordpress is this: 
![mautic - 2017-03-15_13-10-26](https://cloud.githubusercontent.com/assets/20304781/23948107/deda0820-0981-11e7-974e-abd291296239.jpg)

How can there be an "Incorrect access token" if I'm copying and pasting the credentials from Mautic?
Here's how: 
OAuth2 API is also broken in Mautic v2.7.1!

So, in Mautic v2.7.1 API is broken here and there. 
It's broken EVERYWHERE! 

Anyway, as suggested above: 
If you want Mautic to acquire a reputation of something that can be used in a production environment in business, then you should adopt the policy of NOT adding a single new feature until a version reaches a number that ends with ".9". 
Only versions that end with ".9" should be marked as "stable". 
Everything else should be marked as experimental. Because it IS!

**Comment by abooster** [comment] 2017-03-15 12:45
Well, because I have now wasted countless hours on Mautic versions that were supposed to be "stable" but turned out to be experimental versions i.e. NOT fit for use in a production environment in business, 
from now on I will regard every Mautic version that doesn't end with ".9" as an experimental version. 

And anyone who asks me for advice regarding Mautic will hear from me the same recommendation: 
If you see a Mautic version that ends with ".9", go ahead, you can use it in business. 
And if it's a version that doesn't end with ".9", don't bother because it's not intended for use in a production environment.

**Comment by dongilbert** [comment] 2017-03-15 13:22
@abooster - Let me attempt to address your concerns one by one. 

```
Do I need this? Do I want this?
NO! I don't!
Why is it broken?
```

Finding out the answers to these questions would be much easier if your reports were submitted using the Issue Template. Please consider doing so on future reports.


```
When can I start using Mautic in production environment?
```

Thousands of users have implemented Mautic in a production environment. From the apparent urgency and obvious frustration caused by the bugs you've encountered, I'd assume you were using it in a production environment already.

```
Here's a suggestion:
Why don't you guys stop adding any new features for the next 6 months and focus on turning Mautic into something that can actually be used in the production environment?
```

If you look at the change log for 2.7.1, you'll see that absolutely no new features were added. There were 30 bugfixes - nothing more. Of course there are more bugs that need to be addressed, as with any software.  Would you be willing to put some of your expertise in encountering bugs into submitting those bugs as issue reports in GitHub that follow our Issue Template? We put the issue template in place so that we can quickly analyze and appropriately prioritize the issue submissions that are received. That would be a great first step.

```
There's NO fucking explanation as to what this "redirect URI" might be, where to find it or how it might look like!
```

Here's some resources on understanding OAuth2. 

- https://aaronparecki.com/oauth-2-simplified/
- https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

The Redirect URI should be provided by the application that you are connecting to Mautic. For an example of how an app should provide that when connecting via OAuth2, you can check out the Mautic Twitter Integration. Navigate to the plugins page, and then click the Twitter icon to get the integration settings popup. You'll see it provides the callback/return/redirect URI there, which you would use when creating your OAuth2 API credentials within Twitter. I've included a screenshot below for convenience. Hopefully it helps, but the Redirect URI that you paste into Mautic when creating your OAuth2 credentials _should_ be provided by the app that you are connecting to Mautic (the app that you will paste the created Client Key/Secret pair into).

![screen shot 2017-03-15 at 9 17 41 am](https://cloud.githubusercontent.com/assets/718028/23950230/a4582dec-0960-11e7-9a26-0f671f1ce2f2.png)

Finally, if you do have some more information about the errors received when attempting an OAuth1 connection, it would be helpful. As it stands, this report offers no substantial information for us to be able to address it properly, so I'm closing it.

**Closed by dongilbert** 2017-03-15 13:22 UTC
