### ISSUE TITLE
Mautic Upgrade, SSL and Loop

### ISSUE THREAD

**Issue by skynet** [mautic/mautic#5965] opened 2018-04-18 03:26 UTC
If you are behind CloudFlare php and run Mautic over SSL (https://) PHP won't know it, and you'll end up with a loop.

I fixed the problem by adding this piece of code to index.php

```
// Was this requested over SSL?
if (isset ( $_SERVER ['HTTP_CF_VISITOR'] ) && preg_match('/https/', $_SERVER ['HTTP_CF_VISITOR']) ) {
	$_SERVER ['HTTPS'] = 'on';
	$_SERVER ['REQUEST_SCHEME'] = 'https';
}
```
Obviously, with any upgrade this file is overwritten. There should be an option for a permanent solution. Is Mautic aware of situation described above, and what do you recommend.

**Comment by npracht** [comment] 2018-04-19 07:00
Label: Bug

**Comment by SulphurDioxide** [comment] 2019-08-07 15:52
I am running an instance of Mautic behind a reverse proxy. I've experienced exactly this issue too and as soon as I update Mautic, I get stuck inside a redirect loop again. Due to the nature of the loop, there is also no errors to explain what the issue is.

Couldn't this be an option in the config file?

**Comment by skynet** [comment] 2019-08-07 20:47
Redirect for me was caused by Mautic not seeing the request as coming over SSL. Look at the headers. My proxy is Cloudflare and I had to use this in index.php:

`// Was this requested over SSL?
if (isset ( $_SERVER ['HTTP_CF_VISITOR'] ) && preg_match('/https/', $_SERVER ['HTTP_CF_VISITOR']) ) {
    $_SERVER ['HTTPS'] = 'on';
    $_SERVER ['REQUEST_SCHEME'] = 'https';
}`

Perhaps there's a better solution but this would do for now.

**Comment by skynet** [comment] 2019-08-07 21:04
Even with WordPress you can end up with such loop, unless you add the code I mentioned above to wp-config.php. Mautic doesn't have a configuration file, but it should.

**Comment by RCheesley** [comment] 2020-02-13 23:28
Closing this down as it's more of a config issue than a Mautic bug. Perhaps we could make a PR to the documentation to add this snippet if folk come across the problem? See github.com/mautic/documentation :)

**Closed by RCheesley** 2020-02-13 23:28 UTC
Labels: Bug
