### ISSUE TITLE
Role config not updating

### ISSUE THREAD

**Issue by Augentia** [mautic/mautic#3152] opened 2016-12-29 09:42 UTC
What type of report is this: While setting up custom roles, mautic is not allowing update in the 'Social monitoring and Dynamic content' area.

| Q  | A
| ---| ---
| Bug report? |  Bug
| Feature request? | 
| Enhancement? | 

## Description:
Setting up a custom role --> new role --> choose areas and set credentials --> choose 'Dynamic content area' and set credentials --> choose 'Social area and set credentials --> all the other areas excepting 'dynamic content credentials and social media credentials' are saved 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.4
| PHP version | v5.6.28

### Steps to reproduce:
1. new role
2. Choose different areas and set credentials (including dynamic content and social area)
3. All the credentials are saved, EXCEPT the dynamic content and social credentials
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-12-29 10:02
Duplicate of https://github.com/mautic/mautic/issues/3088

**Closed by escopecz** 2016-12-29 10:02 UTC
