### ISSUE TITLE
A Token was not found in the TokenStorage.

### ISSUE THREAD

**Issue by jlemangarin** [mautic/mautic#7779] opened 2019-08-09 13:59 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After trying to login, we are redirected to the login page. Seems to be a firewall.php issue

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.2.21
| Browser | Any

### Steps to reproduce
1. Try to login
2. 
 
### Log errors
```
[2019-08-09 14:51:44] request.INFO: Matched route "mautic_user_logincheck". {"route_parameters":{"_controller":"Mautic\\UserBundle\\Controller\\SecurityController::loginCheckAction","_route":"mautic_user_logincheck"},"request_uri":"https://srv04.ceo-vision.com/mautic/index_dev.php/s/login_check"}
[2019-08-09 14:51:44] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/html/mautic/vendor/symfony/security/Http/Firewall/AccessListener.php:51)
[stacktrace]
#0 /var/www/html/mautic/vendor/symfony/security/Http/Firewall.php(84): Symfony\\Component\\Security\\Http\\Firewall\\AccessListener->handle(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#1 /var/www/html/mautic/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(61): Symfony\\Component\\Security\\Http\\Firewall->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#2 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(184): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#3 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#4 /var/www/html/mautic/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(133): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#5 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(116): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#6 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#7 /var/www/html/mautic/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/mautic/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/mautic/app/AppKernel.php(141): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/mautic/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
un(Object(Stack\\StackedHttpKernel))hp(24): Stack\
#17 {main}
"}
[2019-08-09 14:51:44] security.DEBUG: Calling Authentication entry point.
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.exception" to listener "Mautic\CoreBundle\EventListener\ExceptionListener::onKernelException".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException".
[2019-08-09 14:51:44] event.DEBUG: Listener "Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception".
[2019-08-09 14:51:44] event.DEBUG: Listener "Bazinga\OAuthServerBundle\EventListener\OAuthExceptionListener::onKernelException" was not called for event "kernel.exception".
[2019-08-09 14:51:44] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException" was not called for event "kernel.exception".
[2019-08-09 14:51:44] event.DEBUG: Listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onException" was not called for event "kernel.exception".
[2019-08-09 14:51:44] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" was not called for event "kernel.exception".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bridge\Monolog\Handler\ChromePhpHandler::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Noxlogic\RateLimitBundle\EventListener\HeaderModificationListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Mautic\ApiBundle\EventListener\ApiSubscriber::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SaveSessionListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelFinishRequest".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".
[2019-08-09 14:51:44] event.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\Security\Http\Firewall::onKernelFinishRequest".
[2019-08-09 14:51:44] app.DEBUG: PHP Deprecation - The "security.context" service is deprecated since Symfony 2.6 and will be removed in 3.0. - in file /var/www/html/mautic/app/cache/dev/appDevDebugProjectContainer.php - at line 18519
[2019-08-09 14:51:44] app.DEBUG: PHP Deprecation - The Symfony\Component\Security\Core\SecurityContext class is deprecated since Symfony 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead. - in file /var/www/html/mautic/vendor/symfony/security/Core/SecurityContext.php - at line 14 {"class":"Symfony\\Component\\Security\\Core\\SecurityContext","file":"/var/www/html/mautic/vendor/composer/../symfony/security/Core/SecurityContext.php"}

```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by cpot** [comment] 2019-08-12 10:01
As we can't login in 2.15.2, we cannot use Mautic anymore. I am sure we are not alone with this critical issue.

**Comment by jlemangarin** [comment] 2019-08-14 08:12
Seems related to https://github.com/mautic/mautic/issues/7768

**Comment by escopecz** [comment] 2019-08-31 18:29
Yup, I'll close this as duplicate of #7768. Let's focus our attention there.

**Comment by escopecz** [comment] 2019-08-31 18:46
BTW I can see this info (`A Token was not found in the TokenStorage`) in my logs too. But it's not an error related to this. Just an INFO, not ERROR. I can log in just fine. My guess is that the token was expired or cache cleared or something similar and so the user must log in again to get a new token.

**Comment by jlemangarin** [comment] 2019-09-02 10:16
Seems obvious but we opened this tickets after hours of debugging and login trys

**Closed** 2020-07-07 19:22 UTC
Labels: Duplicate
