### ISSUE TITLE
Emojis are added as part of plain text emails - Auto generated

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#8222] opened 2019-12-11 20:59 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Mautic does not save emojis inside the plain text version of an email body. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.15.3
| PHP version | 7.1.32

### Steps to reproduce:
1. Create a new email 
2. Inside the body of the email add emoji
3. Close builder, go to Advanced tab
4. Click on ```Auto Generate```
5. The emoji will be part of the plain text generated
6. Save to save the email, you will get Error 500

 
### Log errors: 
``` SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x92\\xA5 W...' for column 'plain_text' at row 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x92\\xA5 W...' for column 'plain_text' at row 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []```

**Comment by RCheesley** [comment] 2020-07-01 06:28
Closing as a duplicate of #5893

**Closed by RCheesley** 2020-07-01 06:28 UTC
Labels: Bug
