### ISSUE TITLE
Opening system config results in Error 500

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4522] opened 2017-07-26 10:15 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I open the front end system info view, it shows the Error 500 page **inside the view area**.
When I retry, it works as expected. This happend today for the first time without me changing any settings, so I guess this isn't a major thing, but it is still anoying.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Open system info
2. Look at the awesome error 500 page
3. Open system info again
4. It works
 
```
[2017-07-26 07:19:19] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The string ,f��&�U�"���0U{,f��{�f���,��W{�f�}} is not a serialized array." at /var/www/html/mautic/app/bundles/CoreBundle/Model/AbstractCommonModel.php line 260  []
[2017-07-26 08:34:21] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO lead_ips_xref (lead_id, ip_id) VALUES (?, ?)' with params [19625, 1369]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '19625-1369' for key 'PRIMARY'" at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO lead_ips_xref (lead_id, ip_id) VALUES (?, ?)' with params [19625, 1369]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '19625-1369' for key 'PRIMARY' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '19625-1369' for key 'PRIMARY' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '19625-1369' for key 'PRIMARY' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-07-26 11:18:04] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/www/html/mautic/vendor/symfony/http-foundation/JsonResponse.php line 164 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/mautic/vendor/symfony/http-foundation/JsonResponse.php:164)"} []
[2017-07-26 12:07:38] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/www/html/mautic/vendor/symfony/http-foundation/JsonResponse.php line 164 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/mautic/vendor/symfony/http-foundation/JsonResponse.php:164)"} []
```

**Comment by escopecz** [comment] 2017-07-26 10:23
Thanks for the report. But I'll close it since it's not possible to replicate it. It would stay here opened forever otherwise and no one would be able to fix it.

If you or anyone else get some more details about how to replicate it, give us the steps and I'll reopen this issue.

**Closed by escopecz** 2017-07-26 10:23 UTC

**Comment by cofundhub** [comment] 2018-04-12 09:27
I had the similar problem today. I fixed it by clearing the cache.

**Comment by chalsek8** [comment] 2018-10-17 12:46
To replicate the 

> Thanks for the report. But I'll close it since it's not possible to replicate it. It would stay here opened forever otherwise and no one would be able to fix it.
> 
> If you or anyone else get some more details about how to replicate it, give us the steps and I'll reopen this issue.

To replicate the issue, Go to Settings, click System Info and it generates 500 error. Refreshing the page solves the issue but every time you click the System Info link, error appears.
![image](https://user-images.githubusercontent.com/40162015/47087030-8e820300-d24d-11e8-9a0d-a27829ada3ce.png)
![image](https://user-images.githubusercontent.com/40162015/47087053-a194d300-d24d-11e8-9ac8-593c036473eb.png)

**Comment by escopecz** [comment] 2018-10-17 12:52
I cannot reproduce. Please also add the errors recorded to your logs when you report an issue https://www.mautic.org/docs/en/tips/troubleshooting.html

**Comment by chalsek8** [comment] 2018-10-17 13:07
Thank you. Here is the error logs.

[2018-10-17 21:03:23] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 165 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:165)"} []

Mautic version | 2.14.1
PHP version | 7.0.32-0ubuntu0.16.04.1

**Comment by escopecz** [comment] 2018-10-17 13:11
So similar to the original issue....

I'm wondering what do you have on your server that's not in UTF-8 encoding. It loads `phpinfo()` results, tail of logs and list a few folders and checks if they are writable. I nave no clue now. You'd have to inspect on your machine what it is.
