### ISSUE TITLE
Preview public URL switcher needs page refresh to see change

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11185] opened 2022-05-24 09:03 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

Nothing happened after click. Switch is still turn off. To see changing I must refresh page.

![image](https://user-images.githubusercontent.com/104569506/169991865-03447009-4999-479c-a407-ca1e1e2f0ebc.png)

M4.3.1

### How can we reproduce this issue?

Step 1: Make new email.
Step 2: Try turn on public URL.

### Relevant log output

```shell
no logs.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-05-31 12:56
Hey there,

Pretty sure this is a duplicate of https://github.com/mautic/mautic/issues/10932 - can you check the console to see if you have the same error showing? Thanks in advance!

**Comment by RCheesley** [comment] 2022-07-27 08:52
Closing issue as a duplicate of #10932 due to lack of feedback.

**Closed as completed by RCheesley** 2022-07-27 08:52 UTC
Labels: bug, user-interface, pending-feedback
