### ISSUE TITLE
Using date triggers

### ISSUE THREAD

**Issue by ShareBtech** [mautic/mautic#9068] opened 2020-07-28 13:29 UTC
What is written in documentation does not seem to work (at least for me) in Mautic 3.0.2

I have created a segment with operator equal to "TODAY", or "Today" or "today" and nothing is being pulled in.

Same goes for campaign

**Comment by npracht** [comment] 2020-08-11 14:08
Hello @ShareBtech !
Can you please tell me:
* What is the language fo your instance ?
* What is the language fo your user ?
* What is the format of your field (date or date/time) ?

Thanks

**Comment by ShareBtech** [comment] 2020-08-11 14:10
Hi

Language of instance was English.
User Language English
Format of field was date.

**Comment by npracht** [comment] 2020-08-11 14:35
Hm. I just tested and it works.
<img width="899" alt="Capture d’écran 2020-08-11 à 16 33 27" src="https://user-images.githubusercontent.com/14075239/89910362-69b00a00-dbf0-11ea-97fe-7a8e9874dd1e.png">

* Do you have an error message in logs or in CLI when your run command to update segments ?
* Are you sure you have contacts that fulfil the criteria ?

Concerning campaigns, the feature does not exist. But the feature is developed and you can help making it merged into mautic by testing it --> https://github.com/mautic/mautic/pull/6126

**Comment by RCheesley** [comment] 2020-10-08 18:21
Closing this issue due to a lack of response and being unable to reproduce as above.

**Closed as completed by RCheesley** 2020-10-08 18:21 UTC
Labels: pending-feedback, segments

**Comment by Gp2mv3** [comment] 2020-10-12 08:26
Isn't it a duplicate of #9040 ?
