### ISSUE TITLE
Tag search does not work in Mautic.net (cloud version)

### ISSUE THREAD

**Issue by redcage** [mautic/mautic#2569] opened 2016-09-20 12:40 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
My campaign adds tags to my contacts whenever they do an action (eg download the MILLWORK freemium). When I want to filter the contact list by a tag (eg. millwork), I see the command in the search bar: "tag:" But whatever tag I write, Mautic returns no result.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic.net
| PHP version | N/A

### Steps to reproduce:
1. Add a tag to some of your contacts
2. Go to your contact list
3. Start typing "tag" in the search bar: you'll see the command "tag:"
4. Write the name of the tag you are searching for and press enter
5. Mautic returns no results, even though you do have contacts with this tag
 
### Log errors: 
No related log errors

**Comment by escopecz** [comment] 2016-09-20 12:46
Closing as duplicate of https://github.com/mautic/mautic/issues/2512

**Closed by escopecz** 2016-09-20 12:46 UTC

**Comment by redcage** [comment] 2016-09-20 12:47
Hi, I commented on that post and received this reply:
@redcage Fixed on a different issue/PR doesn't mean its been deployed to mautic.com.

Hence starting a new ticket, since this isn't fixed on the cloud based Mautic as yet. 

Please reopen.

**Comment by escopecz** [comment] 2016-09-20 12:49
It is fixed, but not released yet. It needs to get through code review, testing phase and then it will be released as a new version of Mautic.

**Comment by redcage** [comment] 2016-09-20 12:50
Oh I see, ok thanks. Desperate for that feature.
