### ISSUE TITLE
Feature Request - Point Groups

### ISSUE THREAD

**Issue by mm-blxsoft** [mautic/mautic#1085] opened 2015-10-28 20:16 UTC
It would be very useful to have the ability to assign points in groups. For example we have several different services we offer.

Main Service 1
Main Service 2
Main Service 3

Secondary Service 1
Secondary Service 2

It would be very useful to be able to assign groups for each of the services so if a lead visits the page for "Main Service 1" they are assigned a point under "Service1" group. Then in triggers we can trigger on the number of points the have to a specific group, rather than in general.

Then we can target in more detail that they are getting high in points for "Service1" it's time to reach out, or send to CRM, or whatever.

**Comment by alanhartless** [comment] 2015-10-28 20:18
Hi!  Thanks for reporting this!  I believe it's a duplicate of #581 so will close this in favor of it.

**Closed by alanhartless** 2015-10-28 20:18 UTC
