### ISSUE TITLE
Error 500 when editing a contact with non-valid birthday

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2053] opened 2016-07-18 18:13 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have imported a buch of contacts with a CSV file, and for some of them, the birthdate was not known (customer did not give it), so the tool I exported from uses a default value of '0000-00-00'. 

Therefore, in Mautic, for these contacts, the "Birthday" field is set to the same value of '0000-00-00'. When trying to edit one of these, I get an Internal Server Error. The logs are below.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a CSV file containing contact data, with one or several lines containing the value: '0000-00-00'
2. Match the column containing the '0000-00-00' values to the Birthday field in Mautic
3. Try to edit a contact for which the birthday has been set to '0000-00-00'
4. You should get an Internal Server Error
 
### Log errors: 

`[2016-07-18 18:02:50] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "birthday": Unexpected data found." at /var/www/html/vendor/symfony/form/Form.php line 1086 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"birthday\": Unexpected data found. at /var/www/html/vendor/symfony/form/Form.php:1086, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unexpected data found. at /var/www/html/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php:147)"} []`

**Comment by alanhartless** [comment] 2016-08-18 16:54
I think #2273 will resolve this since it will now validated imported values.

**Comment by alanhartless** [comment] 2016-08-18 16:55
Closing as a duplicate of #2261

**Closed by alanhartless** 2016-08-18 16:55 UTC
Labels: Bug

**Comment by pierreavizou** [comment] 2016-09-04 10:49
It seems that the PR is indeed validating imported dates; however this does not eliminate the bug, as the validation is not retroactive. 
Trying to edit a contact that was previously imported with an "invalid" date still throws an error 500.
