### ISSUE TITLE
Email sending hangs when an attachment has been disabled and there are still mails in the queue to be sent

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#9457] opened 2020-11-30 20:34 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.12 & after upgrade 3.2.0
| PHP version | 7.3.23
| Browser | n./a.

### Steps to reproduce
1. I can't yet reproduce
2. 

But before this issue I disabled an PDF attachment related to a Campaign and uploaded a new PDF and updated campaign emails and campaign settings as well. The PDF attachment was not deleted, only disabled (it was a last year [2020] company calendar, and from this week it was changed to the 2021 calendar PDF.)
 
### Log errors

```
[2020-11-30 14:04:03] mautic.NOTICE: Swift_IoException: Unable to open file for reading [/path-to-mautic/app/../media/files/37375d68c5d6bd0a88fd86783c083cd5613edf33.pdf] (uncaught exception) at /path-to-mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 131 while running console command `mautic:emails:send` [] []
[2020-11-30 14:04:03] mautic.WARNING: Command `mautic:emails:send` exited with status code 1 [] []
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

The issue totally breaks the production Mautic instance email sending possibilities, with queued emails during the sending. The first ~1000 email was sent, and about ~4500 emails hanged up due to this issue on the queue.

The most interesting things that there was not deleted any files from the /media/files folder by me an by other admins.

Updating from v.3.1.2 to v.3.2.0 did not solve the problem.

Cleaning cache did not solve the issue.

Recreating file and folder permissions did not solve the issue.

Finally I put an empty file to the /media/files folder with the missing name **37375d68c5d6bd0a88fd86783c083cd5613edf33.pdf** and the segment email sending can be finished.

The issue is similar to https://github.com/mautic/mautic/issues/5493 but not exactly the same. 
And similar to the https://github.com/mautic/mautic/issues/4500 but the main different is at me wasn't permission issue, I double checked it. Simple there was a missing file, and I can't imagine why Mautic looked for this PDF file.

The issue is required attention because this issue breaks the normal operation and the exception handling practically failed. 

My suggestion is: if there is such case the Command `mautic:emails:send` should skip that problematic email with missing attachments (writing proper log) and all other emails should be sent normally.

**Comment by trianity** [comment] 2020-11-30 20:35
@escopecz  Dear John, what is your viewpoint about it?

**Comment by RCheesley** [comment] 2020-12-14 12:39
@trianity are you about to reproduce this or was it a one-time thing that happened?

Is it possible that you had some older emails still queued to go out with the old attachment which had become unpublished?

Agree that there should be a graceful handling of such errors to stop only the failing mails and allow the rest to go out, any thoughts @escopecz ?

**Comment by trianity** [comment] 2020-12-14 17:58
@RCheesley Hi Ruth, It was a one-time thing that happened with me. And it is possible there were some older emails still queued to go out with the old attachment which had become unpublished.  I did not check the queue state before that changes. But the unpublished attachement is not a deleted - missing attachement, so I agree with you would be willing a graceful handling of such errors to stop only the failing mails and allow the rest to go out.

**Comment by RCheesley** [comment] 2020-12-16 11:59
@trianity just to clarify, how exactly did you disable the attachment? Was it an asset in Mautic which you unpublished?

**Comment by trianity** [comment] 2020-12-16 13:03
@RCheesley Yes.
The asset ID=30 was used in a campaing sent email as an attachement (red arrow) - 2020 calendar. It was unpublished, and the esset ID=39 now the email attachment (2021 calendar). It should be a normal operation change an attached asset in a campaign send email. I was surpirsed when the whole queue hanged up. 

![disable_2020-12-16_13-56-33](https://user-images.githubusercontent.com/6353141/102351381-a462ee00-3fa6-11eb-8f41-d0d172408223.png)

**Comment by trianity** [comment] 2020-12-16 13:07
@RCheesley I will cretae some time to test it and will test in the my test-suite of the Mauitc. The issue was in a production instance and there is now the Xmass campaign.

**Comment by RCheesley** [comment] 2021-03-11 11:45
Closing this issue due to lack of recent activity.

**Closed as completed by RCheesley** 2021-03-11 11:45 UTC
Labels: T2, bug, pending-feedback, email, assets
