### ISSUE TITLE
GET /api/contacts return total as string

### ISSUE THREAD

**Issue by iurisilvio** [mautic/mautic#7319] opened 2019-03-11 15:15 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Endpoint `/api/contacts` return total value as `string` instead of as `int`.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.23

### Steps to reproduce

Set your `AUTH=user:password` and `MAUTIC_URL`, just to avoid exposing private config here. I added a `search` parameter just to return an empty response (it is not relevant for the bug).

```
curl -u $AUTH $MAUTIC_URL/api/contacts?search=do-not-exist
{
    "total": "0",
    "contacts": []
}
```

Other endpoints return as expected:

```
curl -u $AUTH $MAUTIC_URL/api/contacts?search=do-not-exist
{
    "total": 0,
    "lists": []
}
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2019-03-12 11:37
I can confirm. List contacts - total is string. List forms - total is int.

**Comment by StoppingBuck** [comment] 2019-03-18 12:18
I can create a fix for this, but I need to know whether I should change the existing variable, "total", to be int or create a new variable for backwards compatibility reasons (and what to call it in that case)?

**Comment by escopecz** [comment] 2019-03-18 12:22
It causes no problem in PHP so I'm not sure what problem it causes in other languages. Could you describe that? I guess it causes a problem for you. But I would lean in favor of retyping the "total" string value to int as the rest of the Mautic API endpoints has it this way too.

**Comment by iurisilvio** [comment] 2019-03-18 12:27
It can be a problem for statically typed languages if they define a model
with a `String total`. I'm using Python, just did a manual cast `total =
int(total)` before comparison, it works fine with an already int value.

Em seg, 18 de mar de 2019 09:22, John Linhart <notifications@github.com>
escreveu:

**Comment by iurisilvio** [comment] 2019-03-18 12:38
I don't think it is worth to create a new weird value to maintain backward
compatibility. I'd just change the total to int. I don't think people want
a broken API just for the sake of compatibility. It'll create hidden bugs
(I discovered the bug by accident).

Em seg, 18 de mar de 2019 09:27, Iuri <iurisilvio@gmail.com> escreveu:

**Comment by MajesteitBart** [comment] 2020-02-23 21:07
In my case the problem is that contacts return as a object, not a in the form of an array. Is this known behaviour? It seems to be like it is, reading the documentation of GET /api/contacts.

GET: 
`https://mt.domain.nl/api/contacts?orderBy=date_modified&orderByDir=desc&search=last_active:(2020-02-23)+!is:anonymous`

Response:
`{
    "total": "2",
    "contacts": {
        "7493": {
        },
        "7126": {
        }
    }
}`

**Comment by RCheesley** [comment] 2020-12-16 09:53
I'm guessing that this is related to #7385 #8153 which we're slating to address with 4.0 as they will result in BC breaks, so will tag this one for that milestone as well.

**Closed** 2021-06-09 10:11 UTC
Labels: API, T1, bug
