### ISSUE TITLE
Contacts with duplicate unique identifiers not merged

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3337] opened 2017-02-03 18:59 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  x
| Feature request? | 
| Enhancement? | 

## Description:
I had an issue regarding API contacts not being tracked which got fixed in https://github.com/mautic/mautic/pull/3317

I noticed there's another issue where I Mautic created over hundreds of Contacts with the same email address. I want these to be merged.

The email field is a unique identifier, yet they don't seem to be merged automatically. Is there a way to automatically/instantly merge all contacts with duplicate emails? 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.5.2-dev
| PHP version |  7

**Comment by hansakoch** [comment] 2017-02-05 03:00
+1

**Comment by escopecz** [comment] 2017-02-14 14:58
This seems to be a duplicate of https://github.com/mautic/mautic/issues/3108

**Closed by escopecz** 2017-02-14 14:58 UTC
