### ISSUE TITLE
Segment search does not work. Panel and API

### ISSUE THREAD

**Issue by rebelia** [mautic/mautic#11578] opened 2022-10-12 11:19 UTC
### Mautic Version

4.4.x series

### PHP version

8.0.20

### What browsers are you seeing the problem on?

Firefox

### What happened?

![mautic_bug](https://user-images.githubusercontent.com/8507636/195328964-081c04c3-a3bc-43b0-a1ad-733c024d2a99.png)

And API
https://[your_mauitc_domain]/api/contacts?search=segement:segment-alias

{
    "total": "0",
    "contacts": {}
}

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-10-21 10:24
Hi there,

There is no need to enter segment: - just search for the alias.

I have tested and it is working as expected: https://watch.screencastify.com/v/uNNHxezfad0ENS8z3coQ so closing this issue as I am not able to reproduce the reported bug.

**Closed as not planned by RCheesley** 2022-10-21 10:24 UTC
Labels: bug, needs-triage
