### ISSUE TITLE
Notifications query performance

### ISSUE THREAD

**Issue by iurisilvio** [mautic/mautic#7583] opened 2019-06-03 17:09 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Every mautic admin page load make a query to last notifications:

```sql
SELECT
  n0_.id AS id_0,
  n0_.type AS type_1,
  n0_.header AS header_2,
  n0_.message AS message_3,
  n0_.date_added AS date_added_4,
  n0_.icon_class AS icon_class_5,
  n0_.is_read AS is_read_6
FROM notifications n0_
WHERE n0_.user_id = 1 AND n0_.is_read = 0 ORDER BY n0_.date_added DESC LIMIT 200;
```

This query slows down (~5s) with many results (I have 330k notifications with `user_id=1 and is_read=0`. You have a `(user_id, is_read)` index, but it does not include `date_added`.

I created the index `(user_id, is_read, date_added DESC)` in my database and it reduced the query time to ~0.02s. I think it is the right index for this table.

https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/CoreBundle/Entity/Notification.php#L68-L72

Also, using `id DESC` instead of `date_added DESC` (reducing index size) probably have the same result, but I'm not sure if it has some edge case.

| Q   | A
| --- | ---
| Mautic version | 2.15.1

### Steps to reproduce
1. Add lots of notifications
2. Load mautic dashboard
 
### Log errors

mysql slog log

```
# Time: 190603 17:07:40
# User@Host: root[root] @  [10.128.13.247]
# Thread_id: 1104235  Schema: mautic  QC_hit: No
# Query_time: 4.272715  Lock_time: 0.000140  Rows_sent: 200  Rows_examined: 328638
# Rows_affected: 0  Bytes_sent: 40701
# Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: Yes  Filesort_on_disk: No  Merge_passes: 0  Priority_queue: Yes
SET timestamp=1559581660;
SELECT n0_.id AS id_0, n0_.type AS type_1, n0_.header AS header_2, n0_.message AS message_3, n0_.date_added AS date_added_4, n0_.icon_class AS icon_class_5, n0_.is_read AS is_read_6 FROM notifications n0_ WHERE n0_.user_id = 1 AND n0_.is_read = 0 ORDER BY n0_.date_added DESC LIMIT 200;
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by StoppingBuck** [comment] 2020-06-15 08:13
This looks like a duplicate of #7504

**Comment by RCheesley** [comment] 2020-07-16 18:37
@iurisilvio I am going to close this in favour of the earlier issue #7504 - if you would be up for checking if this still exists in Mautic 3.x and making a PR if you are able that would be amazing!

**Closed by RCheesley** 2020-07-16 18:37 UTC
Labels: Bug
