### ISSUE TITLE
The avatar remains broken in Mautic v5.1

### ISSUE THREAD

**Issue by bijitchakraborty** [mautic/mautic#13840] opened 2024-06-15 11:28 UTC
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.18

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### What happened?

The avatar is broken in my freshly installed v5.1, which I installed using Composer. It happened last time, and I fixed it by changing the “site_url”. However, this time it’s not working. This is no longer an issue, which is rare. I've read about many people facing this issue for ages. Also, the avatar.png doesn't even exist in the media/images folder on a fresh install.

![7d3e1408b75a0e59ab5cacc349459ea50cac0e83](https://github.com/mautic/mautic/assets/53024273/45eec0db-bf75-4da5-87a9-0b931e3b72dc)

**Here are the steps I tried:**

- Removed the index.php from the site_url (local.php file).
- Added the avatar.png file in the media/images folder, and the permissions are fine.
- The site URL in the system settings in the Mautic dashboard is the same as the site_url in local.php.

I do have SSL installed properly, and I’m using nginx with proper configs. I’ve double-checked everything. Now the question is, what else should I try to fix it?

### How can we reproduce this issue?

Just perform a fresh install using Composer. That's it!

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by jorbarrientos** [comment] 2024-06-19 05:12
I'm not sure how to fix it; however, I hope I can give some insight and help find the root cause... 

In my efforts to fix this on my Mautic instance, I've come to the conclusion that it has something to do with the .svg file format of the updated image. I am getting a 400 Bad Request error with the https://i0.wp.com/mydomain.com/app/assets/images/avatar.svg?ssl=1, but it's not a web server issue, since I tried accessing every other image in the images folder by using the same URI, just changing the file name, and all PNG files work, except for the SVG.

**Comment by bijitchakraborty** [comment] 2024-06-19 05:56
> I'm not sure how to fix it; however, I hope I can give some insight and help find the root cause...
> 
> In my efforts to fix this on my Mautic instance, I've come to the conclusion that it has something to do with the .svg file format of the updated image. I am getting a 400 Bad Request error with the https://i0.wp.com/mydomain.com/app/assets/images/avatar.svg?ssl=1, but it's not a web server issue, since I tried accessing every other image in the images folder by using the same URI, just changing the file name, and all PNG files work, except for the SVG.

Actually, I am talking about the **avatar**, not the [Gravatar](https://gravatar.com/) here. What I know is that if anyone has a Gravatar image in their profile, and you use that email to create a Mautic account, then it will fetch that Gravatar. If not, it will use the media/images/avatar.png file, which is hosted locally. I am able to access that avatar file; the file permissions are fine. I am not sure what's wrong with Mautic. Why has a basic feature like this been broken for ages?

**Comment by ya-ku** [comment] 2024-06-19 10:02
@jorbarrientos is right here, somehow the .svg files cause the problem. A simple switch back to the avatar.png solved the issue for the moment.

Just navigate to: **app > bundles > LeadBundle > Twig > Helper > DefaultAvatarHelper.php** and change the URL to **images/avatar.png**. However, you need to add avatar.png to the images folder (e.g., from an older version). The avatar should appear again after deleting the cache. 

This should be a workaround until the problem with the .svg files is fixed in the future.

**Comment by bijitchakraborty** [comment] 2024-06-19 11:10
> @jorbarrientos is right here, somehow the .svg files cause the problem. A simple switch back to the avatar.png solved the issue for the moment.
> 
> Just navigate to: **app > bundles > LeadBundle > Twig > Helper > DefaultAvatarHelper.php** and change the URL to **images/avatar.png**. However, you need to add avatar.png to the images folder (e.g., from an older version). The avatar should appear again after deleting the cache.
> 
> This should be a workaround until the problem with the .svg files is fixed in the future.

Thanks, man, **it actually worked!** But when did Mautic change the Avatar path from media/images to app/assets/images?

Also thanks to @jorbarrientos

**Comment by jorbarrientos** [comment] 2024-06-19 15:06
Thanks for helping out with a workaround!

I've seen multiple threads where community members affirm Mautic doesn't use any type of caching, but I just don't get where do those i0.wp.com links come from.. I have a fresh dockerized installation and never enabled anything that would cause this... And it's not just gravatars because it also happens with some mautic logos.

If there's any way to configure it we might be able to add svg files as a supported format

**Comment by andersonjeccel** [comment] 2024-06-21 18:06
Fixed

**Closed as completed by andersonjeccel** 2024-06-21 18:06 UTC
Labels: bug, needs-triage
