### ISSUE TITLE
Error Sending email in some domains

### ISSUE THREAD

**Issue by cuenka** [mautic/mautic#1686] opened 2016-05-04 14:19 UTC
## Description
Hello, I put some information about my hosting.
Using Mautic 1.3.1 installed via Softaculous
PHP 5.6.19
Service to send mail through: Other SMTP Server. My domain (whitelynx.co.uk) and after click test connection the result is Success!
Monitored Inbox Settings: the test result is Success!
Hosting: Siteground
After check with Siteground, they don't have any idea whats going on I think the ask me to contact Google Support team, but I think is other issue.

I can only send emails with successfully of my own domain, in this case, @whitelynx.co.uk if I try to send emails to other domain, for example @gmail.com It doesn't work

## Steps to reproduce
After check on the configuration that the
I am going to the leads page:  /s/leads
I send an email to one user with the domain @whitelynx.co.uk and everything works as expected , no problem, however If I send and email to gmail (cuenka@gmail.com, it is a valid email ) shows the following error.

Failed to send to cuenka@gmail.com: Expected response code 250 but got code "", with message "" Log data: ++ Starting Swift_Transport_EsmtpTransport << 220-serv01.uk10.siteground.eu ESMTP #7 Wed, 04 May 2016 15:14:17 +0100 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail. >> EHLO whitelynx.co.uk << 250-serv01.uk10.siteground.eu Hello whitelynx.co.uk [185.123.97.174] 250-SIZE 52428800 250-8BITMIME 250-AUTH LOGIN PLAIN 250-STARTTLS 250 HELP >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> Y29udGFjdEB3aGl0ZWx5bnguY28udWs= << 334 UGFzc3dvcmQ6 >> UG9sbG9sb2NvMjAxNQ== << 235 Authentication succeeded ++ Swift_Transport_EsmtpTransport started >> MAIL FROM: << 250 OK >> RCPT TO: << 550-Verification failed for 550-No Such User Here 550-contact+bounce_572a03b9e4c6d@whitelynx.co.uk is not a valid address: 550 Sender verify failed !! Expected response code 250/251/252 but got code "550", with message "550-Verification failed for 550-No Such User Here 550-contact+bounce_572a03b9e4c6d@whitelynx.co.uk is not a valid address: 550 Sender verify failed " (code: 550) >> RSET << !! Expected response code 250 but got code "", with message "" (code: 0) 

Do you know what could be the problem?

Thanks

**Comment by Gustavo-Ruiz** [comment] 2016-05-12 13:59
Hi Cuenka,
Did you get this resolved? I am experiencing the same issue, please advise, thanks.

**Comment by escopecz** [comment] 2016-08-17 12:54
Duplicate of https://github.com/mautic/mautic/issues/1540

**Closed by escopecz** 2016-08-17 12:54 UTC
