### ISSUE TITLE
Creating reports not working properly

### ISSUE THREAD

**Issue by rucksman** [mautic/mautic#3190] opened 2017-01-05 11:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When creating a report, the "Filters" section is not working properly. Example:
- Creating a report with data source "Emails sent".
- Within "Data" select "Contact first name" and "Contact last Name" and "Contact email"
- Within "Filters" select "Is read" und put it to "Yes" and define it as NOT dynamic
- Save & Close
-> In the report the filter "Is read" is visible and is set to "Clear" and  can be changed at will
- Go back to "Edit" the report
-> "Is read" is defined as a dynamic filter, no matter how ofter I "Apply" or "Save & Close". In addition there is no button group "Yes" and "No" anymore but a regualr text field.

Even more weird:
- Creating a report with data source "Emails sent".
- Within "Data" select "Contact first name" and "Contact last Name" and "Contact email"
- Within "Filters" select "Is read" und put it to "Yes"
- Add 2 more filters at will
- Set the third filter as NOT dynamic
-> The button YES for the third filter stays green, but the button NO for the second filter gets red.
-> After "Save & Close" again ALL filters are still dynamic, no matter what was selected during editing
-> When editing this report again, only 2 filters are there, the third one disappeared somehow

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 5.6.23-1

### Steps to reproduce:
1. see description above

**Comment by PatchRanger** [comment] 2017-01-11 12:07
Looks like your issue is partially similar to #3082 .

**Comment by escopecz** [comment] 2017-03-06 17:55
I'll close this issue as a duplicate of https://github.com/mautic/mautic/issues/3082

**Closed by escopecz** 2017-03-06 17:55 UTC
