### ISSUE TITLE
Form Submit error 500  cascade persist

### ISSUE THREAD

**Issue by Fade59** [mautic/mautic#5391] opened 2017-11-29 14:50 UTC
What type of report is this:

| Bug report? | X

## Description:
If an External Form is submitted after the contact has received an email with the link to the form(the form ist prefilled with the users data). If the user hits submit he gets an error 500 and the log reports a "mautic.CRITICAL: Uncaught PHP Exception"

But only on the first Submit, It also does not matter If the Form is in Kiosk mode, the User uses a completely different pc from a different IP or any other solution I found in this Issue Tracker.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.22

 
### Log errors: 

`mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #13. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/clients/client2/web2/web/events/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #13. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/clients/client2/web2/web/events/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
`

**Comment by rctlopes** [comment] 2017-12-08 03:54
I am also experiencing the same issue in version 2.11.0 (User not logged in Mautic). Here is my flow:
- From a web page with a form, contact provide name and email and click submit button
- (form actions) 
   . Contact is added to a Pending segment
   . Pending tag is assigned to the contact
   . Page is successfully redirected to an external web page (from a Remote Asset link)
- A campaign from the Pending Segment verify if contact's is already confirmed (check a Confirmed tag).
- In this scenario, it goes through the Not confirmed scenario
- An email with a link to an external page (from a Remote Asset link) is sent to the contact
- The contact receives the email and clicks the link
- 500 Error Page is displayed, and the URL has the Mautic URL still in the Address bar (meaning that the redirect didn't happen yet)
- If I refresh the page, the proper destination page is displayed


Error happens 100% of the time. Not intermittent. 
Looking in the Mautic logs, I find the below error:
`[2017-12-08 01:50:17] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #9518. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /home/mauric24/public_html/emailmkt/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #9518. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /home/mauric24/public_html/emailmkt/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []`

**Comment by rctlopes** [comment] 2017-12-08 03:57
Just one more thing. Not sure if relevant or not, but The form and emails were created using the clone feature. Asset and Campaign were created from scratch.

**Comment by rctlopes** [comment] 2017-12-08 17:52
Another test. I sent a test email (Send Example from the Email) and the confirmation button opened successfully the destination page, so I think that the issue is really in the campaign.

**Comment by rctlopes** [comment] 2017-12-10 02:53
One last update. I fixed the problem re-creating the Campaign. Something was wrong with the campaign, but I'm not sure what. I wonder I had some PHP/Symfony knowledge, but I still have the "bad" campaign unpublished, just in case someone wants some info to investigate, or give me some hints on how to do so.

**Comment by Fade59** [comment] 2017-12-11 12:45
For me recreating the campaign did not help, I even installed Mautic on a completely different Server even one I do not host myself and the problem still persists.

**Comment by rctlopes** [comment] 2017-12-11 13:54
Actually the problem came back for me. I started changing the campaign to identify where the problem actually is. In my case, the problem is happening right after the confirmation email, sent from the campaign, having an Asset link. After the Send Mail activity, there was an Email is Clicked activity, where I do a bunch of tasks, like sending another email, changing segments, tags, etc. I noticed that removing everything after the "Send Mail" activity, the click was redirecting to the proper asset link. That proves that the issue IS in the campaign.
I used to have an activity after the confirmation email is sent. If the confirmation link is not clicked within one day, I was sending a follow up email reminding the contact to do so. I removed that validation, and the issue is now gone.
My suspicious is in potential two places:
1. The waiting for the click has a bug somewhere
2. I remember that I put by mistake a connection between the negative condition to the follow up validation, when it should be the affirmative instead. I changed the connection from the negative to the positive, and a dialog came over to reconfigure. When confirming, the connection was gone, so I had to drag/drop the connection again from the affirmative point to the follow up activity. Sorry, hard to explain in words. Would be easier showing :)
As I said, removing that part, fixed the issue, but my follow up is now gone.

**Comment by stephenvoisey** [comment] 2018-01-24 19:20
I've run into a similar issue with 2.12.1, getting the same log error and 500 error on submit. Emails are being sent, Mautic fails when the campaign has a logic in it, in my case I'm sending two different types of emails.

As soon as a decision is added to the campaign, the error occurs. The decision is taken and email sent, but then 500 error. I've recreated the campaign and it happens as soon as the logic is added.

**Comment by npracht** [comment] 2019-09-04 08:39
Hi @Fade59 is that still an active issue in current version ?

**Comment by biggala2310** [comment] 2020-01-20 13:11
Yes, I still have got this problem.

` mautic.ERROR: CAMPAIGN: A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). [] []`

**Comment by npracht** [comment] 2020-08-04 20:43
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment] 2020-09-04 09:33
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 09:33 UTC
Labels: bug, forms, triage-mautic-3
