### ISSUE TITLE
Error updating to 3.0.2

### ISSUE THREAD

**Issue by cefimadmin** [mautic/mautic#9073] opened 2020-08-12 16:31 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Error during update to 3.0.2

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.19-1~deb10u1
| Browser | chrome Version 84.0.4147.105 

### Steps to reproduce
1. update from version 3.0.1 to version 3.0.2 with the line command : php bin/console mautic:update:apply
2. error during the update
3. Try to run database migrations with command line : php bin/console doctrine:migration:status
4. Try to migrate (php bin/console doctrine:migration:migrate), but there are still 11 tables yet to migrate.
 
### Log errors
Status migration
 >> Name:                                               Mautic Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Host:                                      localhost
    >> Database Name:                                      mautic
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 migrations
    >> Version Column Name:                                version
    >> Migrations Namespace:                               Mautic\Migrations
    >> Migrations Directory:                               /var/www/mautic/app/migrations
    >> Previous Version:                                   2020-03-02 16:48:01 (20200302164801)
    >> Current Version:                                    2020-04-22 14:43:00 (20200422144300)
    >> Next Version:                                       Already at latest version
    >> Latest Version:                                     2020-04-22 14:43:00 (20200422144300)
    >> Executed Migrations:                                145
    >> Executed Unavailable Migrations:                    134
    >> Available Migrations:                               11
    >> New Migrations:                                     0

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by cefimadmin** [comment] 2020-08-12 16:34
Here is my logs:

[2020-08-12 17:57:13] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/mautic/var/cache/prod" directory." at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/mautic/var/cache/prod\" directory. at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:681)"} []
[2020-08-12 17:57:23] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/mautic/var/cache/prod" directory." at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/mautic/var/cache/prod\" directory. at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:681)"} []
[2020-08-12 17:57:27] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/mautic/var/cache/prod" directory." at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/mautic/var/cache/prod\" directory. at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:681)"} []
[2020-08-12 17:57:27] mautic.ERROR: Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www/mautic/var/cache/prod" directory. - in file /var/www/mautic/vendor/symfony/filesystem/Filesystem.php - at line 681 [] []
[2020-08-12 16:03:15] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oauth2_accesstokens CHANGE client_id client_id INT UNSIGNED NOT NULL, CHANGE user_id user_id INT UNSIGNED NOT NULL, CHANGE token token VARCHAR(191) NOT NULL, CHANGE scope scope VARCHAR(191) DEFAULT NULL':  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A19EB6921' (uncaught exception) at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 106 while running console command `doctrine:schema:update` [] []
[2020-08-12 16:03:15] mautic.WARNING: Command `doctrine:schema:update` exited with status code 1 [] []
[2020-08-12 18:05:26] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/mautic/var/cache/prod" directory." at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/mautic/var/cache/prod\" directory. at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:681)"} []
[2020-08-12 18:05:26] mautic.ERROR: Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www/mautic/var/cache/prod" directory. - in file /var/www/mautic/vendor/symfony/filesystem/Filesystem.php - at line 681 [] []
[2020-08-12 16:07:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/mautic/var/cache/prod" directory." at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/mautic/var/cache/prod\" directory. at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:681)"} []
[2020-08-12 16:07:11] mautic.ERROR: Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www/mautic/var/cache/prod" directory. - in file /var/www/mautic/vendor/symfony/filesystem/Filesystem.php - at line 681 [] []
[2020-08-12 16:07:12] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/mautic/var/cache/prod" directory." at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/mautic/var/cache/prod\" directory. at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:681)"} []
[2020-08-12 16:07:12] mautic.ERROR: Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www/mautic/var/cache/prod" directory. - in file /var/www/mautic/vendor/symfony/filesystem/Filesystem.php - at line 681 [] []
[2020-08-12 16:09:30] mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] []

**Comment by brafreider** [comment] 2020-08-12 17:03
The update works for me, without open migrations. Have you checked that the cache directory is writable for the user, you're running the updater with? Best would be to take the user, php is running under. 
Cheers,
Björn

**Comment by cefimadmin** [comment] 2020-08-13 09:15
I try with to run the updater with the user (www-data), but there are yet 11 available migrations. 
I have no errors in log file.
When i execute php bin/console doctrine:schema:update --force, il have the error : SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A19EB6921'

**Comment by StoppingBuck** [comment] 2020-08-15 19:58
@fgauttron Just to make sure: How much free space is on the server? I've seen the same kinds of error when my disk got full (often because spool folder ballooned in size when doing big sendouts).

**Comment by cefimadmin** [comment] 2020-08-15 20:30
38go available (79% free space)

**Comment by RCheesley** [comment] 2020-08-15 20:33
Can you provide the output of this command at command line

`ls -l` 

for your Mautic directory and the var/cache folder in particular?

This will help us to see if there are some issues with file/folder ownership/permissions.

For info, this should really be posted at https://forum.mautic.org/c/support as it is not a bug with Mautic. But let's see what we can get sorted.

**Comment by cefimadmin** [comment] 2020-08-15 20:36
another person seems to have the same problem on the mautic forum : https://forum.mautic.org/t/error-updating-from-mautic-3-0-3-01/15038/9

Here is the result of ls -l  for var/cache
drwxr-xr-x 2 www-data www-data 4096 Aug 13 11:00 ip_data
-rw-r--r-- 1 www-data www-data 3177 Aug 13 11:09 languageList.txt
drwxr-xr-x 8 www-data www-data 4096 Aug 13 11:22 prod

and the result for mautic
-rw-r--r--  1 www-data www-data 38419 Aug 13 11:08 LICENSE.txt
-rw-r--r--  1 www-data www-data  1317 Aug 13 11:08 SECURITY.md
drwxr-xr-x  8 www-data www-data  4096 Aug 13 10:17 app
drwxr-xr-x  2 www-data www-data  4096 Aug 13 10:15 bin
-rw-r--r--  1 www-data www-data     2 Aug 13 11:08 critical_migrations.txt
-rw-r--r--  1 www-data www-data 12862 Aug 13 11:08 favicon.ico
-rw-r--r--  1 www-data www-data   634 Aug 13 11:08 index.php
drwxr-xr-x  7 www-data www-data  4096 Aug 13 10:15 media
-rw-r--r--  1 www-data www-data  4043 Aug 13 11:08 offline.php
drwxr-xr-x 13 www-data www-data  4096 Aug 13 10:15 plugins
-rw-r--r--  1 www-data www-data   224 Aug 13 11:08 robots.txt
drwxr-xr-x 21 www-data www-data  4096 Aug 13 10:17 themes
drwxr-xr-x  3 www-data www-data  4096 Aug 13 10:27 translations
drwxr-xr-x  6 www-data www-data  4096 Aug 13 10:19 var
drwxr-xr-x 69 www-data www-data  4096 Aug 13 10:15 vendor

**Comment by colourfulowl** [comment] 2020-08-27 00:41
I posted a similar thing about the foreign key issue here #9129

**Comment by LevryKurniawan** [comment] 2020-09-09 23:43
I also had a similar issue.

Previously I use **Mautic 2.16.3** with **MariaDB 5.5** without any problems.

After upgrading to **MariaDB 10.4** (_still with Mautic 2.16.3_), when running `doctrine:schema:update --dump-sql` I found the output 75 changes (previously when using MariaDB 5.5 it didn't exist).

Then I run `doctrine:schema:update --force` successfully.

But when I run `doctrine:schema:update --dump-sql` there are still 75 changes, and I run back `doctrine:schema:update --force` successfully. Keep looping like that.

After that I upgraded to **Mautic 3** and found issue like #9073 and #9129.

**Comment by StoppingBuck** [comment] 2020-09-11 16:42
@LevryKurniawan I have the same issue with `doctrine:schema:update --dump-sql` still showing the old queries even after they have been run. I assume it is a cache problem somewhere, but haven't been able to debug further

**Comment by LevryKurniawan** [comment] 2020-09-11 17:25
@StoppingBuck Please see #9109. I think what @kuzmany has to say is related to that.

**Comment by mabumusa1** [comment] 2020-09-21 09:46
This issue is discussed in more details here https://github.com/mautic/mautic/issues/9129#issuecomment-696010876.

This issue is closed in favor of #9129

**Closed as completed by mabumusa1** 2020-09-21 09:46 UTC
Labels: T2, bug, installation
