### ISSUE TITLE
Allow to show/hide segments based on role membership (i.e. granular segments permissions)

### ISSUE THREAD

**Issue by void-gh** [mautic/mautic#4578] opened 2017-08-03 18:03 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Within Mautic (as of 2.9.0) when defining "Roles" under the "Permissions -> Contact Permissions -> Segments - User has access to" there is currently the following options:

- View Others
- Edit Others
- Delete Others
- Full

It would be worthwhile to be able to hide and/or allow specific segments per role.

One possible use case could be the scenario where there thousands of employee contacts that have segment membership defined based on filters (e.g. "All Employees", "Dept. A Employees", "Dept. B Employees", etc.). We would like to assign a role access to only specific segments (e.g. their department only), and not all segments.

This would allow for central management/provisioning of contacts via batch uploads and assigning them to pre-defined segments. This would allow common segments to be shared amongst multiple roles without an all or nothing approach.

**Comment by gingerling** [comment] 2017-08-10 13:42
Duplicate of this: https://github.com/mautic/mautic/issues/3716

**Closed** 2017-08-10 13:47 UTC
Labels: Feature Request
