### ISSUE TITLE
Text editor breaks when Emoji pasted (and saved) with other text.

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#4747] opened 2017-08-30 05:14 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
I don't know about other editors, but when entering a new note, there is an error if the pasted text includes an emoji. If I remove the emoji, no problemo. Encoding issues??

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
1. add new note
2. copy paste text that contains an emoji 😀
3. Save note. Get error.
 
### Log errors: 

[2017-08-30 15:05:00] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO lead_notes (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, text, type, date_time, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-08-30 05:05:00", 1, "Yalcin", null, null, null, null, null, null, "TEST\ud83d\ude00", "email", "2017-08-28 05:04:00", 10275]:  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x80<b...' for column 'text' at row 1" at /home/dev/web/crm.domain.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO lead_notes (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, text, type, date_time, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2017-08-30 05:05:00\", 1, \"Yalcin\", null, null, null, null, null, null, \"TEST\\ud83d\\ude00\", \"email\", \"2017-08-28 05:04:00\", 10275]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x80<b...' for column 'text' at row 1 at /home/dev/web/crm.domain.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x80<b...' for column 'text' at row 1 at /home/dev/web/crm.domain.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x80<b...' for column 'text' at row 1 at /home/dev/web/crm.domain.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by escopecz** [comment] 2017-08-30 06:52
Duplicate of https://github.com/mautic/mautic/issues/2629

**Closed by escopecz** 2017-08-30 06:52 UTC
