### ISSUE TITLE
mautic.CRITICAL: Uncaught PHP Exception

### ISSUE THREAD

**Issue by neurohost** [mautic/mautic#7277] opened 2019-02-23 04:05 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.26
| Browser | chrome

### Steps to reproduce
1. 
2. 
 
### Log errors
[2019-02-22 23:58:15] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\ElasticemailTransport::processCallbackRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /home/***/***.***.***/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172" at /home/***/*******/app/bundles/EmailBundle/Swiftmailer/Transport/ElasticemailTransport.php line 92 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Mautic\\EmailBundle\\Swiftmailer\\Transport\\ElasticemailTransport::processCallbackRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, null given, called in /home/****/*******/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172 at /home/****/*******/app/bundles/EmailBundle/Swiftmailer/Transport/ElasticemailTransport.php:92)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2019-02-25 08:29
Hi @neurohost could you please share the process to reproduce the issue ?

**Comment by neurohost** [comment] 2019-02-28 20:27
forgive the delay, I am currently only sending email campaigns

I can not detail the steps because it does not give me any error, the email campaigns are sent, I do not see that it affects me at all "for the moment"

I do not know why that error originates

**Comment by RCheesley** [comment] 2020-02-04 18:03
Closing this down due to a lack of information to reproduce the problem.

**Closed by RCheesley** 2020-02-04 18:03 UTC
Labels: Bug
