### ISSUE TITLE
the page title of page_hit of the contact is displayed in Roman alphabet instead of Japanese.

### ISSUE THREAD

**Issue by rmrmnrm** [mautic/mautic#7568] opened 2019-05-29 09:09 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Dear Developer.
This is a Japanese user.
Thank you for creating a great open source software called Mautic.

Few days ago, the page title of page_hit of the contact is displayed in Roman alphabet instead of Japanese.
(Reference site is this...)
https://www.facebook.com/photo.php?fbid=2251539528287303&set=gm.3311791138847040&type=3&theater&ifg=1

Hope to fix a problem from you soon.
We appreciate all that you continue to do for us.

Thank you.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1
| Browser | Every

 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2019-06-05 08:23
Closing as duplicate of https://github.com/mautic/mautic/issues/7525. Let's discuss this issue there.

**Closed by escopecz** 2019-06-05 08:23 UTC
