### ISSUE TITLE
Can't update a plugin in 2.16.2

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#8736] opened 2020-04-28 17:19 UTC
## Bug Description
We are working on a plugin, we had v.1 installed onto 2.16.2 and all was good.  Now we have made changes and updated plugin to v.2.  We can't get new version to install.

We know we have new version, we have deleted the v.1 from plugins, restarted webserver, cleared cache, warmed cache, go back into mautic and plugin shows with generic icon (but no way to enable  or publish).

We upload v.2 to plugins directory, set permissions, clear cache, warm cache, recheck all the permissions, restart apache, goto plugins, click install/update and get 0 plugins installed/updated, we can see live icon, which we can now set to published, go to the plugin, and the old v.1 interface is still in place and will not update.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2
| Browser | Chrome
|Webserver Apache|

### Steps to reproduce
1.   Install a plugin
2.   Modify something within the plugin
3.   Try to reinstall plugin with changes.
 
### Log errors
none

**Comment by alexeimm** [comment] 2020-05-06 12:18
when you say plugin v1; and plugin v2, it is the version of your evolution with the plugin? or another version inside into, 2.16.2?

**Comment by healthstatus** [comment] 2020-05-06 13:09
evolution of the plugin

**Comment by alexeimm** [comment] 2020-05-06 18:37
get back to the old version and compare what did you add with the mautic documentation, btw what documentation about mautic version (2.16.2) are you using?

**Comment by healthstatus** [comment] 2020-05-06 19:25
Your suggestion makes no sense to me, we create a plugin and install on 2.16.2, we make a new version of the plugin.  We remove the old version of the plugin, install the new version, clear the cache, multiple times, and UI elements don't change.   What does the documentation have to do with this?

**Comment by alexeimm** [comment] 2020-05-06 22:55
Oh, I was just interested to know more about the respective plugin documentation;
but, I know two things that not really sure if could be usefull, but if u clear cache and did s/update/schema
and it doesn't work, you also can check this function when you update the plugin, not really sure if you are using it https://developer.mautic.org/#install/upgrade
"updatePluginSchema() is available for use with onPluginUpdate()"

**Comment by RCheesley** [comment] 2020-05-16 14:02
Hi @healthstatus, have you looked into whether the issue is that you are missing the use of onPluginUpdate()? Let us know if this resolves the problem so that we can close the issue down!

**Closed as completed** 2020-07-01 12:17 UTC
Labels: pending-feedback
