### ISSUE TITLE
Email Builder code editor will not reopen after the builder has been closed

### ISSUE THREAD

**Issue by levihb** [mautic/mautic#11029] opened 2022-03-31 11:38 UTC
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

If you go into the email builder, click "Edit Code", edit it, then save. Now go back out of the builder. Now re-open the builder, and the "Edit Code" button no longer does anything.

The only way to fix it is to go all the way back out of the email editor, then back in. Or refresh the page.

### How can we reproduce this issue?

Step 1: Go into the email editor and open the "Builder"

Step 2:  Click the "Edit Code" button on the right, and click "Edit"

Step 3: Click X to close the builder

Step 4: Open the Builder again

Step 5: Clicking the "Edit Code" button no longer does anything.

### Relevant log output

```shell
There's no output in the browser console. No errors in the Mautic logs.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-04-07 15:50
Hi there, this is a duplicate of a known issue which is [already fixed](https://github.com/mautic/mautic/pull/10842).  See also this PR which has some additional fixes: https://github.com/mautic/mautic/pull/10847 which needs testing.

Please ensure you're running the latest version of Mautic (4.2.1) and that you've regenerated assets, cleared cache and cleared any locally / CDN cached files.

**Closed as completed by RCheesley** 2022-04-07 15:50 UTC
Labels: bug, needs-triage
