### ISSUE TITLE
[Feature Request] Progressive profiling forms

### ISSUE THREAD

**Issue by troelsfeodor** [mautic/mautic#870] opened 2015-09-07 10:54 UTC
It would be great to allow embedded forms to present new fields to a known visitor who returns. 
You'd set the order of the fields to be shown and then when a user returns after first submitting his email, he'll be asked for one or more new fields next time.

I used this feature with Marketo, but their implementation is not necessarily great: https://docs.marketo.com/display/public/DOCS/Configure+Form+Progressive+Profiling

**Comment by npracht** [comment] 2015-09-09 17:24
Hi,

Net Results does the same and it's a very powerfull feature.
https://www.net-results.com/drag-drop-form-builder/

**Comment by alanhartless** [comment] 2015-09-19 04:36
I think this is a duplicate of #414

**Closed by alanhartless** 2015-09-19 04:36 UTC
Labels: Duplicate
