### ISSUE TITLE
Elfinder (Media Manager) Requires Full Authentication

### ISSUE THREAD

**Issue by dsukhin** [mautic/mautic#9075] opened 2020-08-12 23:12 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When a user with non full (admin) access tries to use the media manager (custom code email>edit>builder>media manager) to upload images etc. they get the following error. This is new with mautic 3 as we had non admin users designing mails etc just fine before.

![Image 8-2-20 at 5 39 PM](https://user-images.githubusercontent.com/3967926/90076972-f9c48100-dcce-11ea-9bcb-acef0dfc8ebe.jpeg)

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.2.32
| Browser | Chrome (latest)

### Steps to reproduce
0. Be non admin user
1. custom code email
2. edit
3. builder
4. media manager
 
### Log errors
(none, other than much more out of mem issues on M3 vs M2)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dsukhin** [comment] 2020-08-13 00:16
possibly related: 
`[12-Aug-2020 20:03:21 America/New_York] PHP Warning:  Invalid callback elFinderSession::session_start_error, cannot access protected method elFinderSession::session_start_error() in /home/<user>/public_html/mautic/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 101`

**Comment by RCheesley** [comment] 2020-08-21 16:28
@dsukhin thanks for the bug report and for the error message - hopefully an easy one to fix 🤞

**Comment by kuzmany** [comment] 2020-10-06 08:55
I was not able to reproduce it on 

https://mautibox.com/staging/
user: test
pass: tester

Do I something wrong?

**Comment by RCheesley** [comment] 2020-12-15 14:47
Closing due to lack of recent activity.

**Closed as completed by RCheesley** 2020-12-15 14:47 UTC
Labels: T1, bug, pending-feedback, roles, file-uploader

**Comment by armancse-dev** [comment] 2022-03-04 11:24
i am getting this error Invalid callback elFinderSession::session_start_error, cannot access protected method elFinderSession::session_start_error()  > /home/wnews/public_html/campaign/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php
