### ISSUE TITLE
Filters disappears in Reports

### ISSUE THREAD

**Issue by didacrios** [mautic/mautic#2959] opened 2016-11-16 10:33 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When creating a report for exporting customers and adding Filters, when saving and entering again, the first filter disappeared.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2.1
| PHP version | 7.0.13

### Steps to reproduce:
1. Edit a report,
2.  Go to Data Tab
3. Add your filters
![image](https://cloud.githubusercontent.com/assets/211009/20343793/3261950c-abf0-11e6-9dd2-6531ec9afd40.png)
4. Click Save & Close or Apply
5. Edit the report again
6. Go to Data Tab
7. See that the First filter is not there
![image](https://cloud.githubusercontent.com/assets/211009/20343847/637cd778-abf0-11e6-8dba-20e44e592f89.png)

**Comment by Mirz** [comment] 2017-02-24 18:49
+1

I can confirm that this bug is happening to me as well. Any existing filter is removed when adding a new filter to a report. You can't 'update' the filter set. You need to delete all the filters and redo them all in order to save.

**Comment by Arjoni** [comment] 2017-02-27 11:27
Still happening on v2.6.1

**Comment by alanhartless** [comment] 2017-03-10 09:11
Duplicate of #3547.

**Closed by alanhartless** 2017-03-10 09:11 UTC
Labels: Bug
