### ISSUE TITLE
404 gif image - tracking pixel image

### ISSUE THREAD

**Issue by sontt710** [mautic/mautic#7675] opened 2019-07-09 06:23 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 5.6
| Browser | Chrome

### Steps to reproduce
1. Create contact
2. Send Email
3. Open email via Chrome

### Log errors
[09/Jul/2019:13:17:46 +0700] "GET /email/5d241cfb13fd5912040028.gif HTTP/1.1" 404 117 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2019-07-09 06:40
Hi @sontt710, the description is not complete enough. On my side i don't have any issue. How can i be sur to reproduce.
Do you have something in mautic logs ?

**Comment by sontt710** [comment] 2019-07-09 06:44
Hi @npracht,

I created contact, and send a email via mautic dashboard.

I opened the email but mautic not marked this email read. Logs of webserver show like this. Gif image is not generated.

[09/Jul/2019:13:17:46 +0700] "GET /email/5d241cfb13fd5912040028.gif HTTP/1.1" 404 117 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"

**Comment by npracht** [comment] 2019-07-09 06:45
Can you also check mautic logs ?
Settings > Sys info > Logs

**Comment by sontt710** [comment] 2019-07-09 06:50
Hi,

[2019-07-09 12:20:30] mautic.NOTICE: PHP Notice - Undefined index: spend_for_ggads - in file /usr/share/nginx/html/mautic.abc.com/app/bundles/FormBundle/Views/Builder/fieldwrapper.html.php - at line 54 [] []
[2019-07-09 13:00:10] mautic.NOTICE: PHP Notice - Undefined index: spend_for_ggads - in file /usr/share/nginx/html/mautic.abc.com/app/bundles/FormBundle/Views/Builder/fieldwrapper.html.php - at line 54 [] []
[2019-07-09 13:03:27] mautic.NOTICE: PHP Notice - Undefined index: spend_for_ggads - in file /usr/share/nginx/html/mautic.abc.com/app/bundles/FormBundle/Views/Builder/fieldwrapper.html.php - at line 54 [] []
[2019-07-09 06:15:21] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
[2019-07-09 06:20:08] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
[2019-07-09 06:25:06] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
[2019-07-09 06:30:09] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
[2019-07-09 06:35:21] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
[2019-07-09 06:40:06] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
[2019-07-09 06:45:07] mautic.NOTICE: Swift_IoException: Unable to open file for reading [http://mautic.abc.com/index.php/themes/aurora/assets/logo_white.png] (uncaught exception) at /usr/share/nginx/html/mautic.abc.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []

**Comment by npracht** [comment] 2019-08-26 07:05
Obviously there is something wrong with images in the email.

**Comment by RCheesley** [comment] 2020-07-29 12:03
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-29 12:03 UTC
Labels: bug
