### ISSUE TITLE
Campaign condition with date operator does not trigger properly on date/time fields

### ISSUE THREAD

**Issue by jgranstrom** [mautic/mautic#6979] opened 2018-12-07 09:08 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description 
The date operator with a custom number of days in campaign conditions only behaves as expected when using a date field without time or when the time is set to all zeroes (midnight). If any other time is set in the field value the condition never succeeds.

| Q   | A
| --- | ---
| Mautic version | 2.14.2 and 2.15.0-beta
| PHP version | As defined by the respective docker images
| Browser | Chrome

### Steps to reproduce
1. Add 2 custom fields, one with type `date` and one with `date/time`
2. Create a contact with the custom `date` field set to 3 days ago (e.g. `2018-12-04`) and the custom `date/time` field set to 3 days ago at some time during that day (e.g. `2018-12-04 08:00:00`)
3. Create a segment that includes that contact
4. Create one campaign with the segment as a source and add 4 separate conditions from the source
  4.1 One condition on the `date` field with the date operator and a custom value as `-3` `day(s)`
  4.2 One condition on the `date/time` field with the date operator and a custom value as `-2` `day(s)`  
  4.3 One condition on the `date/time` field with the date operator and a custom value as `-3` `day(s)`
  4.4 One condition on the `date/time` field with the date operator and a custom value as `-4` `day(s)`
<img width="988" alt="skarmavbild 2018-12-07 kl 09 50 11" src="https://user-images.githubusercontent.com/3751473/49637726-82712100-fa06-11e8-8928-8ba075be854b.png">

5. `php app/console mautic:campaigns:update`
6. `php app/console mautic:campaigns:trigger`

The contact is now in the campaign, and condition 1 is successful, but conditions 2, 3 and 4 are all failed.
<img width="1077" alt="skarmavbild 2018-12-07 kl 09 47 53" src="https://user-images.githubusercontent.com/3751473/49637511-d8919480-fa05-11e8-931c-ad07f41c1193.png">

7. Clone the first campaign
8. Change the value of the `date/time` field in the contact to be at midnight (e.g. `2018-12-04 00:00:00`)
9. `php app/console mautic:campaigns:update`
10. `php app/console mautic:campaigns:trigger`

The contact is now also in the cloned campaign, and conditions 1 and 3 are successful, while conditions 2 and 4 are failed.

<img width="1077" alt="skarmavbild 2018-12-07 kl 09 49 01" src="https://user-images.githubusercontent.com/3751473/49637609-24dcd480-fa06-11e8-94c3-2b5045203085.png">

In the first case I would expect one of the conditions 2-4 to succeed depending on how the number of days are rounded.

### Log errors
There's no errors being logged.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2018-12-12 15:59
I think it should support date/time field and probably simply ignore the time value.
What do you think ?

Would you feel confortable making a PR in that sense ? :)

**Comment by jgranstrom** [comment] 2018-12-17 11:08
@npracht I think for days/months/years it would make sense to ignore the time value in the field and just compare the dates, however there is also the hour and minute options which would require formatting both dates differently to include the hour or hour and minute of both the trigger date and the date/time field. Currently I can't see how those options would work properly at all. Also this would mean that the logic for this would be, for example, "previous hour" and not "an hour ago" if you put -1 hour(s) unless the formatting prior to checking includes more precision such as minutes, but that might make for some false negatives unless it is checked at the "right" minute.

I'll try to find some time to look at making a PR but I was unable to find the test cases related to the evaluation of these conditions so if you can point me in the right direction there it would be a bit easier to get going with a fix.

**Comment by pierrederuel** [comment] 2019-01-28 13:48
hi @jgranstrom, did you find something to handle the date/time fields? Thanks

**Comment by jgranstrom** [comment] 2019-01-29 18:52
I was going through the code and realized this might be a significant change. Right now the target timestamp string is simply compared by equality. I’m not sure what the frequency is of this check, but to me it looks like it would require some logic on the interval between the dates. What if you put the target time to be +10 second and the check is performed after 5 minutes? It would never match by some equality comparison, but you would have to check if this duration has been passed. There is a lot of edge cases and I wasn’t able to spend enough time to dig deeper as I am also not familiar with the inner workings. Even if the time would somehow be rounded to the relevant precision the condition would depend on when it is evaluated for the more granular options. One option would be to truncate each timestamp to only contain the date but in that case the hour/minute/second should probably be disabled as it would have unexpected behavior. It would also be important to note that -1 day doesn’t mean 24 hours ago but previous day regardless of time.

**Comment by pety-dc** [comment] 2019-03-18 16:04
upvote

**Comment by RCheesley** [comment] 2020-02-04 21:41
@jgranstrom @pierrederuel @pety-dc the PR to fix this requires one more tester. Head over to #8044 and give it a test if you can, let's get this into the next release!

**Comment by MauriceW2** [comment] 2020-06-21 02:59
What's the status on this bug report? I'm glad I finally found this, because I was banging my head against the wall why datetime conditions are not working in Mautic.

Is this fixed in Mautic 3.0?

**Comment by npracht** [comment] 2020-08-05 07:09
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment] 2020-09-04 09:36
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 09:36 UTC
Labels: bug, campaigns, triage-mautic-3

**Comment by alexhammerschmied** [comment] 2021-06-08 11:31
I think we need this to open again. 
After testing and digging I found that the current PR #9784 fixes most of the segment problems regarding date/time fields.
Anyway from this PR #6979 to the other one many things have fallen under the table which should be addressed. 

Most important: 
The campaign condition "date" based on hours and minutes. It is a feature which the community is craving for actually. - at least I do... ;)

IMHO Mautic needs the function to check for date/time with minutes to trigger campaign actions from there.
