### ISSUE TITLE
Performance Problem VPS

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#3826] opened 2017-04-06 20:07 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
Takes 30 plus seconds simply to get to the Channels>Emails screen.
I have tested my Mautic on different VPS server with lots of RAM up to 82GB so this can't be it. 
I have to try to use this #3580 to see if solve the problem and not luck

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-04-07 07:04
Closing as a duplicate of https://github.com/mautic/mautic/issues/2449

**Closed by escopecz** 2017-04-07 07:04 UTC

**Comment by ninjoan** [comment] 2017-04-07 13:30
In my case i only have 600 contacts.
