### ISSUE TITLE
No "Email" shows up in "Reports"

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#10813] opened 2022-01-31 15:28 UTC
### Mautic Version

4.1.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

A bug happened!

When I create a "Report" to display the metrics about the emails (sent, open, clicks...) ALMOST no email shows up.

I have tens of emails and hundreds of thousands of contacts. Most of the emails do not show up at all inside the "Reports", no matter which filters I pick.

They are "invisible".
But if I go under Channels - Emails I see them all and I can see the amount of emails sent and opened. They just do not show up under "Reports".

I have reported this bug many times but it seems that no one gives a damn about it.

### How can we reproduce this issue?

Step 1: 
Create several emails
Step 2:
Send them through Campaigns or as "Segment emails" to hundreds of K of contacts
Step 3: 
Create a report to display the metrics, very likely no mail will be included, or just some of them (some Email ID are properly displayed, others are not "detected" at all)

### Relevant log output

```shell
Nothing.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-02-05 11:24
Hi @Dylan-86 can you please check if you have the appropriate date filter set in your report when those emails were sent?

If so please share screenshots of the emails and the dates they were sent, and the report configuration / settings.

It's probably not that nobody gives a damn, just there isn't enough information to help with triaging your bug report.

**Comment by Dylan-86** [comment] 2022-02-06 11:39
Hi @RCheesley 

Actually, in the first thread I shared all the details and screenshots. You can check here:
https://github.com/mautic/mautic/issues/10420

YES, I am sure that I select the right timeframes.

Screenshots:
Email #176 (I can actually show you any of the 20+ email we have configured)
![image](https://user-images.githubusercontent.com/58813956/152678285-43440e52-916a-4a39-b974-88a6d6cb06b0.png)


Report: Totally empty
![image](https://user-images.githubusercontent.com/58813956/152678297-5dfd3b6b-9f4a-4097-8b7d-16092e2c2d03.png)

The report is configured to show ALL emails. None shows up.

**Comment by RCheesley** [comment] 2022-02-06 11:50
Right - so this is a duplicate of that issue therefore I will close it. Please do not create duplicated issues.

**Closed as completed by RCheesley** 2022-02-06 11:50 UTC
Labels: bug, duplicate, pending-feedback, reports

**Comment by Dylan-86** [comment] 2022-02-06 12:37
@RCheesley 

OK but I see this "Comments on closed issues are hard for our team to see.
If this issue is continuing with the [lastest stable version of Mautic](https://www.mautic.org/mautic-releases), please open a new issue that references this one."

Well, the issue is still there even with the new version of Mautic.

**Comment by RCheesley** [comment] 2022-02-06 13:30
@Dylan-86 your original issue https://github.com/mautic/mautic/issues/10420 is still open. It will be reviewed when the community is able to get to it. You do not need to make any more issues about it, regardless of whether you feel that it is not being resolved quickly enough.
