### ISSUE TITLE
Chrome shows Mautic dashboard as not fully secure

### ISSUE THREAD

**Issue by aspiers** [mautic/mautic#7577] opened 2019-06-02 16:23 UTC
## Bug Description

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Version 71.0.3578.98 (Official Build) (64-bit)

Mautic dashboard insecurely loads the i2.wp.com avatar over http even when the Site URL is configured for https.

### Steps to reproduce
1. Deploy Mautic with nginx handling SSL termination with letsencrypt/certbot certificates
2. Visit the dashboard in Chrome
3. Look at the icon to the left of the address bar and/or visit the Security tab in the Chrome developer tools, which clearly show a request like http://i2.wp.com/my.mautic.site/media/images/avatar.png being made, despite everything else going over https:

![image](https://user-images.githubusercontent.com/100738/58764064-bc0c8a00-855a-11e9-951a-831ebedf8855.png)

**Comment by aspiers** [comment] 2019-06-02 16:29
If I could figure out where on earth this i2 URL came from, I could probably fix it.  The question was asked in #4210 but noone answered it yet.

**Comment by nethunter** [comment] 2019-06-03 13:13
Happens when you do SSL termination before Mautic itself. I solved it by using a self-signed and connecting to 443.

**Comment by aspiers** [comment] 2019-06-03 14:39
You mean self-signed SSL on the backend, and then proxying through to that?  Double layers of SSL sounds like a grotesquely inefficient way to change a single http://i2.wp.com/... URL to https.  There must be a better way, but again I'm still waiting for an answer as to [where the code which generates this URL comes from](https://mautic.slack.com/archives/C02HV76BW/p1559495821006700?thread_ts=1559493029.006500&cid=C02HV76BW).

**Comment by nethunter** [comment] 2019-06-04 10:32
@aspiers actually, for me settings HTTPS for php-fpm like documented here: https://ma.ttias.be/setting-https-server-variables-in-php-fpm-with-nginx/ solved the issue

**Comment by aspiers** [comment] 2019-06-04 15:00
@nethunter Thanks for sharing, although I'm not using fpm so I don't think this will solve it for me.  However I've made a tiny bit more progress into understanding the issue.  The http request is triggered by this HTML in the dashboard (I've sanitised it):

```html
<img src="https://www.gravatar.com/avatar/ee21ae1627ae80b5505a20fa4c83be7a?s=250&amp;d=http%3A%2F%2Fmy.mautic.domain%2Fmedia%2Fimages%2Favatar.png">
```

gravatar.com then redirects to i2.wp.com, but it chooses to redirect via http not https, because of the `d=http%3A%2F%2F...` in the URL.  If the URL is changed to include `d=https%3A%2F%2F...` then it instead redirects to https://i2.wp.com.  So the bug is in whatever code generates this gravatar URL.

**Comment by aspiers** [comment] 2019-06-04 15:02
With that new knowledge, it was easy to trace it to here:

https://github.com/mautic/mautic/blob/07b95ec5024747bf8cb59e22c6305fcbb9e77c5a/app/bundles/CoreBundle/Templating/Helper/GravatarHelper.php#L85

I guess it won't be hard to debug and fix now.

**Comment by nethunter** [comment] 2019-06-04 15:41
@aspiers I actually answered you on Slack, and shared where the code is. https://mautic.slack.com/archives/C02HV76BW/p1559580099011200?thread_ts=1559493029.006500&cid=C02HV76BW

**Comment by aspiers** [comment] 2019-06-04 16:32
Thanks, I had missed that thread update on Slack.  Looks like we more or less came to the same conclusion.  Still some more details to be figured out though.

**Comment by aspiers** [comment] 2019-06-25 12:06
@npracht This is still an issue and should not have been closed.  As you can see from the above comments, we have traced the problem to a certain area of code, but have not fixed it yet.

**Comment by npracht** [comment] 2019-06-25 12:08
Ok my bad. I cannot see that on my side... I believe this is more a question of configuration on server side ?

**Comment by aspiers** [comment] 2019-06-25 12:10
No I think it's an actual bug in the code which generates the gravatar URL.

**Comment by aspiers** [comment] 2019-06-25 12:11
See https://github.com/mautic/mautic/issues/7577#issuecomment-498710738 for the details.

**Comment by nethunter** [comment] 2019-06-26 14:02
@aspiers it's not a bug in this code. It happens because Mautic thinks that the connection isn't through HTTPS, and that manifests itself in a number of places. As discussed on Slack, by fixing the headers passed to PHP to understand it's under HTTPS, this works as expected.

**Comment by aspiers** [comment] 2019-06-27 11:18
@nethunter Thanks. Can you point to any documentation covering this?  If not, this should be left open as a documentation bug at least.

**Comment by heathdutton** [comment] 2019-06-28 13:53
This isn't really a Mautic issue, but a general hosting issue that would impact any number of PHP applications that are not set up w/ HTTPS=on when under SSL. Set up that env variable and your issues might just go away.

**Comment by aspiers** [comment] 2019-06-28 14:08
@heathdutton Yeah that's what @nethunter just said above.  Like I said, this is still probably a documentation bug.

**Comment by ComputerCarl** [comment] 2019-08-17 00:23
@aspiers Is the solution thus far to change the source code? There seems to many issues open ([2778](https://github.com/mautic/mautic/issues/2778), [7577](https://github.com/mautic/mautic/issues/7577), , [7588](https://github.com/mautic/mautic/issues/7588) relating to proxying Mautic behind HTTPS.

**Comment by ComputerCarl** [comment] 2019-08-17 00:56
@heathdutton How would one go about this using the Docker image.. which I imagine would normally be deployed behind an HTTPS proxy?

**Comment by nethunter** [comment] 2019-08-17 05:24
The solution is to change your PHP configuration to properly indicate it's
behind a proxy... Been working perfectly for me for months now, with no
code change.

**Comment by ComputerCarl** [comment] 2019-08-17 13:36
It's good news there's such an easy fix, @nethunter! I can't wait to get my forms working! If you would be so kind as post here how one would do that on the Docker container, I will share will the dozens of other people whom are experiencing similar issues. I attempted to view the solution in the Slack channel, but am not authorized.

**Comment by autoize** [comment] 2019-10-23 02:01
Adding the following line in the Apache VirtualHost (between `<VirtualHost>` and </VirtualHost>` corrects the issue with the avatar image being served over HTTP when SSL is terminated at a reverse proxy.

`SetEnvIf X-Forwarded-Proto https HTTPS=on`

The equivalent solution for Nginx is:

`fastcgi_param  HTTPS 'on';`

**Comment by RCheesley** [comment] 2020-02-02 22:12
Hi folks, I'm going to close this issue down as it seems to be a server config issue, which has been explained and resolved as above :)

**Closed by RCheesley** 2020-02-02 22:12 UTC
Labels: Bug
