### ISSUE TITLE
pass data on form submission

### ISSUE THREAD

**Issue by avitalar** [mautic/mautic#992] opened 2015-10-08 08:16 UTC
Hello,

I'm having an issue with Mautic form parameters. I'm trying to pass the submitted form values to external api while using the redirect url action.

the url appears as below after submission:
https://www.website.com?email={formfield=email}
The required result is to get the actual email off course:
https://www.website.com?email=exmple@gmail.com

is there any known solution for this?

Thanks,

Avital

**Comment by escopecz** [comment] 2015-10-08 08:47
This issue is duplicate of https://github.com/mautic/mautic/issues/900

**Comment by alanhartless** [comment] 2015-10-22 01:50
Closing in favor of #900.

**Closed by alanhartless** 2015-10-22 01:50 UTC
Labels: Duplicate
