### ISSUE TITLE
Custom fields do not scale well

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3443] opened 2017-02-14 15:33 UTC
| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | ✔️ 

## Description:

Today, custom fields are created as columns in the leads table. This leads to a lot of technical limitations. After my tests which consisted of adding _text_ custom fields on my dev machine until it posed problem, I deduced that at the 36th custom field, Mautic could not create any more indices:

<img width="870" alt="screen shot 2017-02-14 at 16 08 57" src="https://cloud.githubusercontent.com/assets/18265735/22935161/feb731fc-f2d1-11e6-8cbd-da0c21b31b1f.png">

And at the 60th, I could not create anymore custom fields, nor could I submit forms anymore and I suspect a lot of things break due to that.

<img width="867" alt="screen shot 2017-02-14 at 16 09 26" src="https://cloud.githubusercontent.com/assets/18265735/22935388/c0d10e20-f2d2-11e6-9c02-a16e6cb96972.png">

<img width="1246" alt="screen shot 2017-02-14 at 16 08 35" src="https://cloud.githubusercontent.com/assets/18265735/22935391/c2caad6c-f2d2-11e6-9b02-caed6ff4e7a8.png">

<img width="841" alt="screen shot 2017-02-14 at 16 08 16" src="https://cloud.githubusercontent.com/assets/18265735/22935409/cffdf034-f2d2-11e6-9b01-1ece3782aaa5.png">

I think we could completely fix this problem by not adding any more columns in the leads table, but rather by truly utilizing the lead_fields table.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Create a whole lot of _text_ custom fields
2. Try to do a `doctrine:schema:update`
 
### Log errors: 

> See screenshots

**Comment by escopecz** [comment] 2017-02-14 15:39
This seems to be a duplicate of https://github.com/mautic/mautic/issues/3202

**Closed by escopecz** 2017-02-14 15:39 UTC

**Comment by MaxWebmecanik** [comment] 2017-02-14 16:07
Yup you're right
