### ISSUE TITLE
Form submission doesn't work in a Focus popup

### ISSUE THREAD

**Issue by Aneta09** [mautic/mautic#4005] opened 2017-05-05 17:19 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I have a problem with forms submissions. I have used the form in focus item. When I submit it I have "Please wait" communicate and nothing happened on the website.

On Mauitc base: I have added a new contact and filled the form. Focus item still shows up - according to my settings shouldn't. 
What is wrong?

I am using Mautic 2.8. (self-hosted). PHP 7.0. Website: WordPress. I am using WP Mautic plugin (from Git HUB - not repository Wordpress). 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
![2017-05-05_19-06-06](https://cloud.githubusercontent.com/assets/25117928/25756638/c892ba94-31c7-11e7-81e3-8fe207be9826.jpg)

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Aneta09** [comment] 2017-05-05 17:30
I have another problem. When I am using login by any social media plugin. After I succeed of authorized, pop-up doesn't want to close. When I click: Close Window - nothing works. I have answer javascrip: void(0) but the window is still open. What can be wrong
![2017-05-05_19-08-38-2](https://cloud.githubusercontent.com/assets/25117928/25757059/54e65bc6-31c9-11e7-8ddb-efd5232e09ff.jpg)
? Any idea?

**Comment by trnelson** [comment] 2017-05-05 20:47
This is due to headers on the form not permitting cross-origin within an iframe. I'm not an expert in this, but basically I had to install the Headers More package for nginx, and also add the following in the last line of my nginx conf file for Mautic (note `mysite.com` in the config.)

The problem is that by default, Mautic returns `X-Frame-Options: DENY` which prevents posting back to it within an iframe.

Hope this helps! It worked for me, though the functionality is still a bit wonky. But it solves it 90% I think.

```
  more_set_headers "X-Frame-Options: SAMEORIGIN";
  more_set_headers "Content-Security-Policy: frame-ancestors 'self' mysite.com";
```

**Comment by Aneta09** [comment] 2017-05-05 21:29
Hi Travis,

Thanks for your answer. I am not the developer - only business user... So I must admit I don't know what/where  I should add. Maybe you can write in few steps - how I should start...

**Comment by Aneta09** [comment] 2017-05-08 07:45
Hi @trnelson,

I know more. My server is Apache. Maybe you can give me instruction to .htaccess ?

**Comment by ronnieduke** [comment] 2017-05-10 17:38
@trnelson is the fix you suggested to be applied on the instance that Mautic is running on, or on the server of the website you're tracking?

**Comment by escopecz** [comment] 2017-05-30 12:54
Can you check if it's not the issue described at https://github.com/mautic/mautic/issues/2778?

**Comment by Aneta09** [comment] 2017-06-02 09:09
@escopecz No, it is not the same problem. I have https on both. I updated Mautic to 2.8.2 and problem still is. Here is the communicate  from my browser:
![2017-06-02_11-00-08](https://cloud.githubusercontent.com/assets/25117928/26719167/c110b6b4-4783-11e7-9c9b-a995d05ba31f.jpg)

**Comment by shulard** [comment] 2017-08-28 07:30
Hello,

@inhies declared the same kind on errors on the WordPress plugin issue board. If you use the iframe embed method you can face problems if your mautic webserver doesn't allow the iframe to be embedded within the website.
This depends on the current webserver configuration for your Mautic instance.

@escopecz, maybe we can use the defined CORS settings to return a `X-Frame-Options` header which allows iframes to be embedded in the whitelisted websites ? Or we can introduce a new configuration ?

@Aneta09, at the moment you must use the JavaScript embed method to avoid that kind of error.

**Comment by ikabraham** [comment] 2017-09-24 10:09
I'm using mautic plugin 2.2.1 with Wordpress and I reeceived the errors listed below:
XMLHttpRequest cannot load https://site.com/services/mtc/event. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.site.com' is therefore not allowed access.
mtracking.gif Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
(index):1 Refused to display 'https://site.com/services/form/submit?formId=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
site.com/services/form/submit?formId=1 Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE

**Comment by shulard** [comment] 2017-09-25 08:02
@ikabraham you are having two problems here (the page view event is not triggered and the form is not displayed). It seems that your ad-blocker is blocking mtracking.gif image to be loaded can you try to load the page without the adblocker to confirm that issue ? 
Also you must allow your Mautic domain to display iframes inside your website using the X-Frame-Options header :

```
X-Frame-Options: ALLOW-FROM https://mautic.monsite.com/
```

**Comment by nguyencongvu** [comment] 2018-04-07 21:06
I have same error, too (submit focus form raises an error 
Uncaught DOMException: Blocked a frame with origin)

Chrome Inspect to see the error 
My site [here](http://dme.salesacademy.com.vn)

**Comment by shulard** [comment] 2018-04-09 08:40
Hello @nguyencongvu, 

I checked on your website. I'm not familiar with vietnamese, is-it the auto appearing form on scroll which have problems ?

Actually I've submitted a test and the form submission failed with a 500 error : 
```
Uh oh! I think I broke it. If I do it again, please report me to the system administrator!
```

It seems to be on the Mautic side, can you check your Mautic application logs (app/logs) if there isn't any errors ? Maybe you'll need to run migrations or something else to fix the problem.

**Comment by RCheesley** [comment] 2019-11-06 16:46
Closing issue due to lack of recent activity

**Closed by RCheesley** 2019-11-06 16:46 UTC
Labels: Bug

**Comment by marcosjoao37** [comment] 2024-02-21 02:31
Hi! I had that same problem here. I found a lot of texts on forums talking about X-Frame-Options. Today it's deprecated. Instead we have to use Content-Security-Policy.

What I have to do to get it to work: Simple add `header("Content-Security-Policy: frame-ancestors 'self' {$_SERVER['HTTP_ORIGIN']}; frame-src 'self' {$_SERVER['HTTP_ORIGIN']};");` in my `index.php`, after `<?php` of course.

You can add this in another file, like in `app/middlewares/CORSMiddleware.php`. But you have to test yourself.

What I think that is happening: The iframe tag has a form inside. That form do a POST to Mautic services. "Mautic" (in fact, the serve where's Mautic is installed) do not allow that POST to be made from that iframe. I'm not sure why, but I think that can be something related to the fact that this iframe is inside another URL/Host that is not equal to my/your Mautic server.

For my purposes, I had to make a future lead insert its email on a form in a landing page. So, I first created a form without a campaign. I configured it to show a message after a successful POST. After that I created a Focus item, a "modal" style one, with that previous created form inside. I copied the focus item script and pasted on my client website. The modal was showing up, the data/email lead was getting registered in the Mautic service/interface, but I had an error on my client website (that I could saw on web browser developer console) that was saying that the POST action couldn't be successful because that X-Frame-Options thing. And, as you can see on Mozilla's documentation, the X-Frame-Options do not support "Allow-From" option anymore. It's was causing the modal to stay opened, and no "successful" message could be opened. neither the Modal close itself. The "Send" button turn into "Processing" and stuck.

Just to add more information about it: Deploying Mautic using Docker, image tag `mautic/mautic:v4`. The client website is Wordpress. My web browser is Firefox 122.0.1. OS is Fedora 39. Wordpress and Mautic servers are Linux, not sure about the flavor.

I hope that can help someone in the future :)
