### ISSUE TITLE
Can not save or update focus item with HTML content

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#4679] opened 2017-08-17 12:44 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Focus items with content HTML or Editor will not save or update properly

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.22

### Steps to reproduce:
1. Create a focus item with content HTML or Editor
2. Press "Save & Close" or "Apply"
3. Screen will partially "white out"
4. Nothing saved
 
### Log errors: 

```
[2017-08-17 14:44:48] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null - in file XYZ/app/bundles/CoreBundle/Event/TokenReplacementEvent.php - at line 94 [] []
```

**Comment by escopecz** [comment] 2017-08-17 12:47
Where are you getting the HTML content from? You can see in the error messages you attached that it's in some odd encoding (you cannot read it) and it actually says `Malformed UTF-8 characters, possibly incorrectly encoded`.

**Comment by wucherpfennig** [comment] 2017-08-17 12:57
I tested it again (dunno from where the mailformated thing came ;-) ) but here you see my html:

```
<style>
.mautic-focuss{
background:linear-gradient(rgba(210,180,120,0.0),rgba(210,180,120,0.0)), url("XYZ/assets/img/hero-image_v3.jpg") center center no-repeat; background-size: cover;
min-height: 130px;
position: relative;
}
.mautic-focus{
padding:0;
}
.teaser-image img{
max-width:100%;
height: auto;
}
.desc{
padding: 0 1rem;
}
</style>
<p class="teaser-image"><img src="https://z41com.bitelec.ch/assets/img/hero-image_v3.jpg" />
<p class="desc">Some TEXT</p>
<p class="desc">
<a class="button cta" href="XYZ" target="_blank" class="button">Jetzt mehr erfahren</a>
</p>
``` 

I just updated the log. only this error will be thrown on every "save"

**Comment by escopecz** [comment] 2017-08-17 13:02
I tested it with your content and got this error:
```
mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null - in file app/bundles/CoreBundle/Event/TokenReplacementEvent.php - at line 94 
```

I'll re-open the issue since it needs fixing. It may be caused by the CSS since Mautic can think those `{...}` are tokens. But could you confirm you get the same error or are you still getting the one you reported? Even if you copy the content from GitHub and paste it in a new Focus item?

**Comment by wucherpfennig** [comment] 2017-08-17 13:05
But could you confirm you get the same error or are you still getting the one you reported?
yes - see my updated first post.

Even if you copy the content from GitHub and paste it in a new Focus item?
Does not matter what I copy. even "naked" html without any style like <p></p> throws an error

**Comment by Inarus** [comment] 2017-08-17 22:06
Have the same error message:

`[2017-08-17 23:53:09] mautic.ERROR: PHP Error: Call to a member function getId() on null - in file /ssdysk/iwos/public_html/mautic/app/bundles/CoreBundle/Event/TokenReplacementEvent.php - at line 94 [] []
[2017-08-17 23:53:09] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function getId() on null - in file /mautic/app/bundles/CoreBundle/Event/TokenReplacementEvent.php - at line 94 [] [] `

wile saving focus item mozilla console reports:

`POST /mautic/s/focus/edit/5?mauticUserLastActive=1&mauticLastNotificationId=756 500 (Internal Server Error) VM457 libraries.js?v3f7114a5:673 
send @ VM457 libraries.js?v3f7114a5:673
ajax @ VM457 libraries.js?v3f7114a5:649
$.fn.ajaxSubmit @ VM457 libraries.js?v3f7114a5:2310
Mautic.postForm @ app.js?v3f7114a5:230
Mautic.postMauticForm @ app.js?v3f7114a5:228
(anonymous) @ app.js?v3f7114a5:227
dispatch @ VM457 libraries.js?v3f7114a5:404
elemData.handle @ VM457 libraries.js?v3f7114a5:379
trigger @ VM457 libraries.js?v3f7114a5:402
(anonymous) @ VM457 libraries.js?v3f7114a5:437
each @ VM457 libraries.js?v3f7114a5:149
each @ VM457 libraries.js?v3f7114a5:139
trigger @ VM457 libraries.js?v3f7114a5:437
jQuery.fn.(anonymous function) @ VM457 libraries.js?v3f7114a5:602
buttonClick @ app.js?v3f7114a5:66
dispatch @ VM457 libraries.js?v3f7114a5:404
elemData.handle @ VM457 libraries.js?v3f7114a5:379`

**Comment by escopecz** [comment] 2017-08-18 07:07
@kuzmany will you have a minute to look at this?

**Comment by kuzmany** [comment] 2017-08-18 07:38
@escopecz sure

**Comment by wucherpfennig** [comment] 2017-08-21 19:18
@kuzmany do you need any additional information?

**Comment by rc125** [comment] 2017-08-26 01:33
Same error here:

`[2017-08-25 22:27:43] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null - in file /var/www/mautic/app/bundles/CoreBundle/Event/TokenReplacementEvent.php - at line 94 [] []`

**Comment by kuzmany** [comment] 2017-08-26 21:44
Try https://github.com/mautic/mautic/pull/4734 and comment that PR (could speed up merge in next Mautic version)

**Comment by wucherpfennig** [comment] 2017-09-11 13:38
any updates on this issue?

**Comment by escopecz** [comment] 2017-09-12 09:23
Probably fixed by https://github.com/mautic/mautic/pull/4900

**Closed** 2018-01-30 09:24 UTC
Labels: Bug, Ready To Test
