### ISSUE TITLE
Point Triggers don't seem to work

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3351] opened 2017-02-06 15:26 UTC
| Q  | A
| ---| ---
| Bug report? | :heavy_check_mark: 
| Feature request? | 
| Enhancement? | 

## Description:
I can't get point triggers to work... I explain the steps I take underneath.

![image](https://cloud.githubusercontent.com/assets/18265735/22653187/fd4c8a64-ec88-11e6-899e-89a4bc3cb243.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.15

### Steps to reproduce:

1. Create an email to send to contacts that reach ten points
2. Create a point action that triggers at ten points.
3. Create a form that gives 100 points
4. Open the public form URL in a private browsing tab
5. Submit the form.
6. You get 100 points but no email...

**Comment by v-akos** [comment] 2017-02-14 13:53
I have the same issue. Not with forms, but points are gained, and the email is not sent.

My campaign is working, emails are being sent without any problem.
The triggered email is published, so is the point trigger itself.
Contacts with the needed amount of points are not set to "do not contact".

**Comment by escopecz** [comment] 2017-03-02 08:41
Duplicate of https://github.com/mautic/mautic/issues/3235

**Closed by escopecz** 2017-03-02 08:41 UTC
Labels: Bug
