### ISSUE TITLE
New Contact: Primary company (Out of place field)

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12808] opened 2023-10-18 15:39 UTC
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What happened?

Mautic 5 Beta 1, primary company field out of place.

![image](https://github.com/mautic/mautic/assets/131262825/0cb3e441-9905-4aa2-9ca5-16b2e45a3f4e)

### How can we reproduce this issue?

Step 1: Contacts > Create a new contact

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2023-10-18 16:29
Thanks so much for taking the time to report this but it's already a bug that is in the system: https://github.com/mautic/mautic/issues/12628 so I'm going to close this and mark it as a duplicate.  Please do continue to report anything else that you come across, and maybe have a quick search to see if you can find anything tagged with regression beforehand :)

**Comment by RCheesley** [comment] 2023-10-18 16:29
Closing issue as a duplicate of https://github.com/mautic/mautic/issues/12628

**Closed as not planned by RCheesley** 2023-10-18 16:29 UTC
Labels: bug, duplicate, needs-triage

**Comment by code5rick** [comment] 2023-10-18 16:31
@RCheesley my bad sorry! 😅

**Comment by RCheesley** [comment] 2023-10-20 11:53
No problem it happens to the best of us! :)
