### ISSUE TITLE
Impossible to write the email content if the email title has been filled

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic#4729] opened 2017-08-25 13:38 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When using the feature to send an email to an individual contact from the contact page, on Chrome (latest version) if you fill the subject field first, then the textarea field become unusable. It seems that the trick is to type your email content first, then the subject at the end. As soon as you enter the email subject, no matter when in the process, the textarea is disabled.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 5.6.30

### Steps to reproduce:
1. Enter a contact 
2. Click on SEND EMAIL
3. Start typing the email subject
4. Try typing the email content in the big textarea
5. The textarea isn't working, impossible to type
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-08-25 13:41
Duplicate of https://github.com/mautic/mautic/issues/4639

**Closed by escopecz** 2017-08-25 13:41 UTC
