### ISSUE TITLE
Сannot specify a host for the desired region Amazon SES (+Patch)

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#8788] opened 2020-05-14 00:09 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.16.2 
| Mautic version | 3

This problem is in the 2nd and 3rd versions of Mautic.

### Steps to reproduce
1. Go to the mail settings and select service to send Amazon SES
2. You cannot specify a host for the desired region.  For example, Europe, Canada, etc.

In my opinion, this is a bug, not an improvement. The number of regions in Amazon may continue to increase. The problem has already been mentioned here #8118 and here #8735
 
Changed the field format. Instead of the preset selection list I made a text field

Attach patches for the file /app/bundles/EmailBundle/Form/Type/ConfigType.php 

[ConfigType_patch.zip](https://github.com/mautic/mautic/files/4625306/ConfigType_patch.zip) in this archive:
ConfigType_v2. patch for Mautic v2.16. 2
ConfigType_v3. patch for Mautic v3

P.S. You also need to delete the rest of the translation files

**Comment by RCheesley** [comment] 2020-05-16 13:49
Hi @directpromo thanks for raising this issue, however it looks like this has already been raised as an issue, and a PR has already been submitted. Therefore I'm going to close this issue down as a duplicate of #8118 and PR #8735

**Closed as completed by RCheesley** 2020-05-16 13:49 UTC
Labels: duplicate
