### ISSUE TITLE
Showing duplicate fields

### ISSUE THREAD

**Issue by peterlobster** [mautic/mautic#7423] opened 2019-04-16 06:34 UTC
I'm using the Mautic image (`Linux mautic-vm 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64`) provided by @Bitnami .

In my "Custom Fields" area, I have a total of 88 'custom fields.' 
Fields 1-44 appear to be okay. However, fields 45-88 appear to be **duplicates**.

![Screen Shot 2019-04-15 at 11 32 20 PM](https://user-images.githubusercontent.com/38382145/56187221-cd173100-5fd6-11e9-9771-6ac9b13059e5.png)

It would appear [this issue was reported by another user to Bitnami a few days ago](https://community.bitnami.com/t/duplicate-custom-fields-and-reports/66409), and they suggested reporting the problem to @mautic. I don't think the other user did so; so I'm doing it because it seems to be a consistent problem with @bitnami users.

**Has this been happening to anyone else? Is there a way to fix it?**

**Comment by escopecz** [comment] 2019-04-18 13:19
We will need steps to reproduce to do something about this. If this happens only of Mautic instances created by Bitnami than I'd say it's a Bitnami issue.

**Comment by peterlobster** [comment] 2019-04-19 06:04
@escopecz Thanks for trying to help out! I'd tend to agree with you. 

However according to @bitnami, the instances are built off a 'clean' pull from this repository, which I think was their reasoning behind reporting here. However they didn't offer much help other than that.

Regardless, could you be more specfic about the information you'd want back from @bitnami? Maybe I can chime in on the exsisting ticket.

**Comment by escopecz** [comment] 2019-04-19 07:17
In order to fix this we have to know how it happened.

**Comment by peterlobster** [comment] 2019-04-19 07:37
@escopecz Does this provide any insight?

> We use [the Github repository](https://github.com/mautic/mautic) they have with the code of the application and use `composer` to install all its dependencies.

**Comment by escopecz** [comment] 2019-04-19 07:40
Sadly not. I use the same process to install and update several Mautic instances.

**Comment by peterlobster** [comment] 2019-04-19 07:43
@escopecz Then this is something that @bitnami would definitely need to provide insight on.

**Comment by javsalgar** [comment] 2019-04-19 09:22
Hi,

Bitnami developer here. Could you let us know in which table of the database this custom fields section is located. We would like to check if there are actually duplicate entries there. This way we could go gather more information about what's happening.

**Comment by escopecz** [comment] 2019-04-19 09:27
Hi, sure I can. From the screenshots there are duplicates but with unique ID. So there is twice as many rows in that table than it should be. The UI nor API will let you create a field with alias which already exist. But this constraint doesn't seem to be applied in this case. So I think it's cased by direct SQL manipulation.

So the field metadata is in the `lead_fields` table and if it will help then for the values are created new columns in the `leads` table. The field alias is equal to the column name.

**Comment by peterlobster** [comment] 2019-04-21 23:37
@javsalgar Any findings?

**Comment by pauloshimabukuro** [comment] 2019-04-23 16:20
Hello everyone, I had the same problem and I simply accessed the database and deleted the duplicate values from the "ma_lead_fields" and "ma_reports" tables.

I hope I have helped, I hug

**Comment by peterlobster** [comment] 2019-04-24 01:09
@pauloshimabukuro Good thinking! That's exactly what I did, but the problem exists in that the IDs get disorganized as the system tries to continue the numbering scheme and won't recreate the IDs that were already used by the duplicates. Maybe @escopecz has some idea on rectifying that.

Regardless I don't think it's very elegant, so I'd hardly consider this to be an actual solution to the problem.

**Comment by aminebenj** [comment] 2019-05-24 08:58
Hi, I also installed Mautic using Bitnami and have the same problem.

Did you find any other solution ?
Or did the solution that you mentioned worked well ?

Thank you

**Comment by pauloshimabukuro** [comment] 2019-05-24 12:13
@aminebenj I still have not found another solution, it seems that the problem happens in the installation and the accuracy of a change made by Bitnami.

**Comment by ran-dall** [comment] 2019-05-24 12:57
@pauloshimabukuro and @aminebenj Actually, I don't think it's a problem caused by Mautic directly. I investigated this quite a bit and ended up setting up Mautic manually with Composer quite a few times too, and there are zero problems with those installations. You can use use the scripts I used here: https://github.com/ran-dall/mautic-vagrant

Initially, I was using Mautic to set up development environments, but I've superseded Vagrant for my original use. You’ll find the scripts in the provisioners folder.

**Comment by zarocknz** [comment] 2019-06-10 03:01
Just a quick note I also encountered this issue with duplicate custom fields in Mautic installed via Bitnami on AWS. I installed Mautic locally by cloning the the bitbucket repo and do not get this problem.

**Comment by jorgehen** [comment] 2019-06-25 20:09
I also encountered this problem with duplicate custom fields on Mautic installed via Bitnami on AWS.

**Comment by npracht** [comment] 2019-07-02 08:34
Due to third party i'll close this issue. Please refer to https://github.com/mautic/mautic/issues/7423#issuecomment-495615319 if you need help of that issue.

**Closed by npracht** 2019-07-02 08:34 UTC
Labels: Pending Feedback
