### ISSUE TITLE
ER: Social Integration - Schedule Posts

### ISSUE THREAD

**Issue by piuskid** [mautic/mautic#228] opened 2015-03-31 00:18 UTC
Hi, would love to see the following business case:

Marketing Manager - 
1) Creates a new Facebook posting in Mautic
2) Schedules posting for 1PM for the next day
3) When constructing the FB message, ability to add a link to a Mautic landing page.
3A) Include tracking URL's in FB message (tracking url's not yet in Mautic :)  ) so as people click on various URL's in the FB message, I can track what clicks were most popular and by who.
4) View some reports on the FB message inside of Mautic (stretch)

**Comment by alanhartless** [comment] 2015-04-02 04:49
Excellent suggestions! Tagging this as a feature request.

**Comment by joomlacorner** [comment] 2015-04-08 16:10
if this feature can do for post to twitter and track who retweet or mention  or track by TAG.  it will be great!

**Comment by alanhartless** [comment] 2015-09-18 21:39
Doing some cleanup and found this to be a duplicate of #55.  So closing it in favor of it.

**Closed by alanhartless** 2015-09-18 21:39 UTC
Labels: Duplicate, Feature Request
