### ISSUE TITLE
Delete all contacts from a segment with one click

### ISSUE THREAD

**Issue by chrisdutra** [mautic/mautic#3363] opened 2017-02-08 04:14 UTC
What type of report is this:

| Enhancement? | 

## Description:
I have a segment with 16k contacts that never opened any e-mail I sent. I'd like to delete all these contacts but I only know how to delete 100 by 100.

Does Mautic have some option for me to delete all contacts at once? If not, i'd like to sugest this functionality because sometimes is necessary to clean the list.

**Comment by escopecz** [comment] 2017-02-08 09:32
This seems to be a duplicate of https://github.com/mautic/mautic/issues/2562

**Closed by escopecz** 2017-02-08 09:32 UTC
