### ISSUE TITLE
Cron job for campaign rebuild producing error

### ISSUE THREAD

**Issue by waqdev786** [mautic/mautic#7164] opened 2019-01-23 16:01 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  v2.15.0
| PHP version |  7.x
| Browser | chrome

### Steps to reproduce
1.  Setup campaign rebuild cron job
2.  Check log file
 
### Log errors
[2019-01-23 11:45:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mkt_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mkt_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mkt_campaign_lead_event_log WH' at line 2 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2019-01-24 14:19
Could you please detail the campaign you've done and the segment you use for the campaign?
Thanks

**Comment by waqdev786** [comment] 2019-01-24 15:17
the error occurs in campaigns that uses the Modify contact's segments action to add/remove the contact to/from a segment.

Meanwhile we are disabling those campaigns.

**Comment by escopecz** [comment] 2019-05-01 12:55
An important information in this case is what database do you use (MySql/MariaDB) and which version. Could you get that for us?

**Comment by escopecz** [comment] 2019-05-03 07:29
I'll close this issue until you get back to us.

**Comment by waqdev786** [comment] 2019-05-03 09:37
We are using Mysql database and version is 5.6.40-84.0

**Comment by waqdev786** [comment] 2019-05-03 09:38
> An important information in this case is what database do you use (MySql/MariaDB) and which version. Could you get that for us?

We are using Mysql database and version is 5.6.40-84.0

**Comment by escopecz** [comment] 2019-05-03 09:41
Should be fine. I'm not sure where the problem is then. Let's leave this issue open in case anyone else will be able to get some ideas.

**Comment by RCheesley** [comment] 2019-10-25 13:28
Seems like this might be related to #7947

**Comment by npracht** [comment] 2020-01-06 17:20
@waqdev786 did you try the fix mentioned in the issue @RCheesley has linked ?

**Comment by RCheesley** [comment] 2020-02-04 18:25
Closing this issue down due to lack of response - re-open as needed if it's still an issue!

**Closed by RCheesley** 2020-02-04 18:25 UTC
Labels: Pending Feedback
