### ISSUE TITLE
[Feature Request] Send Windows

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#2608] opened 2016-09-29 13:47 UTC
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 👍 
| Enhancement? | 

## Description:
I'd like a setting (per campaign, or per action) to configure send windows so that it will only send messages on certain days. For example only on monday, wednesday, and friday

Should be combined with the relative time period.

1. Send a message after 2 days.
2. Then check if it is a allowed day for this campaign. 
3. If yes -> Send
4. If no -> wait another day, go back to 2

![Alt text](https://ceblog.s3.amazonaws.com/wp-content/uploads/2013/02/sendpepper-3-day.png)

**Comment by escopecz** [comment] 2016-09-29 13:51
Actually, this seems like duplicate of https://github.com/mautic/mautic/issues/2518

**Closed by escopecz** 2016-09-29 13:51 UTC
Labels: Feature Request
