### ISSUE TITLE
[bug] Still possible to direct email opted out users

### ISSUE THREAD

**Issue by deanbarrow** [mautic/mautic#2320] opened 2016-08-18 11:10 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
After a user has unsubscribed or marked you as spam, you're still able to directly email them through their contact page.
I would have expected this option to be unavailable like it is after a contact has bounced.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.1.0
| PHP version | 

### Steps to reproduce:
1. Send email through channel to a contact, in my case I used complaint@simulator.amazonses.com
2. (optional) Mark email as spam. In my case, this was automatically done by AWS SES
3. Allow for cron to fetch email, or force a fetch from the console
4. Check in email report that the complaint was registered
5. Go to contact page and attempt to send email
6. You will find that Mautic will allow you to send mail to a 'bad' contact. This seems to be a UI problem as the complaint is registered in the database under lead_donotcontact

**Comment by alanhartless** [comment] 2016-08-18 12:17
This is on purpose. The unsubscription process is for automated mail - not direct email from a person. We blocked this before and was forced to change it back to how it is now based on strong feedback from community.

**Comment by deanbarrow** [comment] 2016-08-18 12:19
Okay, thanks for the reasoning behind it.

**Comment by alanhartless** [comment] 2016-08-18 12:19
Well let me ask this though - did the user get marked as unsubscribed or a bounce? What's the reason code in the database?

**Comment by deanbarrow** [comment] 2016-08-18 13:57
They were unsubscribed:

25 355 2016-08-18 10:51:34 1 email 20 Contact unsubscribed via email

Dean

**Comment by alanhartless** [comment] 2016-08-18 14:01
ok - thanks for verifying! That's by design then so we'll close this.

**Closed by alanhartless** 2016-08-18 14:01 UTC
Labels: Pending Feedback
