### ISSUE TITLE
Campaigns Don't Save

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic#61] opened 2015-02-20 20:54 UTC
After building a flow in Campaign and mapping all the link - saved the campaign. After closing the campaign and opening it up again. All the actions are bunched up in the left top corner with no mapping. 
1.  Update doesn't save. 
2.  The inline Delete and top right delete doesn't work

**Comment by alanhartless** [comment] 2015-02-25 05:15
I believe this was all related to https://github.com/mautic/mautic/commit/a54226dc9578e2e5e4bff359ec379bb2fbcb7432. Is this still happening?

Thanks,
Alan

**Comment by alanhartless** [comment] 2015-02-26 00:37
Closing since we confirmed this fixed today :-)

**Closed by alanhartless** 2015-02-26 00:37 UTC
Labels: Bug
