### ISSUE TITLE
Mautic's error log shows Mautic home page

### ISSUE THREAD

**Issue by OmerGafny** [mautic/mautic#8258] opened 2019-12-22 07:35 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic log shows mautic hompage.  Might be related to php version update, but i cant tell for sure

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.1.32
| Browser | Chrome

### Steps to reproduce
1. Go to System info > Log
2.  You will then see the entire site text and markup
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2019-12-30 14:14
Hi @OmerGafny !
I am not able to reproduce. Maybe your path to mautic logs is not correctly set up ? Please check configuration > path to logs directory.

Thanks

**Comment by OmerGafny** [comment] 2019-12-30 15:20
Hi Norman, the log directory is ok, i can see errors , the issue is that i can also see this long feed that contains the markup of Mautic site, im attaching a screenshot 
![cap](https://user-images.githubusercontent.com/42744161/71588016-9cf1cd00-2b28-11ea-8130-40491fa4f8a8.PNG)

**Comment by OmerGafny** [comment] 2019-12-30 15:24
it look like some rss issue. Just before the markup, i have the following error :mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 741: parser error : Opening and ending tag mismatch: article line 368 and div - in file /opt/bitnami/apps/mautic/htdocs/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php

**Comment by felipebirmann** [comment] 2019-12-30 19:00
I'm with exact same problem here!

**Comment by derekzernach** [comment] 2019-12-31 02:24
We have the same "problem", doesn't seem to be causing any issues besides muddying up the logs.

rss_notification_url is set to https://mautic.com/?feed=rss2&tag=notification which now redirects to https://www.acquia.com/products-services/mautic?feed=rss2&tag=notification

The html for that acquia domain is what we're seeing in the logs.

**Comment by ZenDevMaster** [comment] 2020-01-01 04:33
Also experiencing same issue in our logs; happy to help diagnose

**Comment by afonseca08** [comment] 2020-01-02 04:32
I'm seeing the same thing and the log clutter is there as well.

**Comment by mwetmore** [comment] 2020-01-02 17:00
Hi folks, we've removed the homepage redirect that was causing this issue to appear.  As soon as we come up with a plan for the feed that Mautic.com was providing we will let you know.

**Comment by RCheesley** [comment] 2020-02-02 21:07
As this was an issue with the mautic.com domain which is now resolved and will be addressed going forward to ensure that the RSS feed doesn't break, I'm going to close this issue down.

**Closed by RCheesley** 2020-02-02 21:07 UTC
Labels: Bug
