### ISSUE TITLE
Can't preview emails from certain views.

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3352] opened 2017-02-06 16:00 UTC
| Q  | A
| ---| ---
| Bug report? | :heavy_check_mark: 
| Feature request? | 
| Enhancement? | 

## Description:
Can't preview emails from certain views.

![image](https://cloud.githubusercontent.com/assets/18265735/22654475/22ff7cea-ec8d-11e6-8ba9-24b83b058aa9.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Create a template email
2. Create a standalone form
3. Add a send email action
4. Select an email
5. Hit preview
6. `404`

**Comment by alanhartless** [comment] 2017-03-10 08:37
I think this is a duplicate of #3063

**Closed by alanhartless** 2017-03-10 08:37 UTC
