### ISSUE TITLE
[Bug] Campaign forms are not triggering workflows

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1624] opened 2016-04-20 18:57 UTC
## Description
Using a campaign form to initiate a workflow does not seem to be functioning

### Mautic version
1.3.1
### Email settings
Send immediately, PHPMailer. 
Works when sending one-off mails.

## Steps to reproduce
Create a campaign form.  Create a campaign workflow with the form submission being the first step, and an email being sent as the second step.

Fill out the form.  Expected outcome: User added to campaign and receives email. Actual outcome: User added to campaign, no email sent.

### Other troubleshooting steps taken

* Tried changing to a standalone form with a form action of adding to a lead list.  Changed the same campaign, same email workflow to be initiated by joining a list - this worked fine and the email was sent and is tracked in Mautic.

**Comment by escopecz** [comment] 2016-05-02 12:32
I tested this workflow and the email was sent right after I triggered command `app/console mautic:campaigns:trigger`

My suggestions to try next time:
- make sure you test this in an incognito browser window as recommended in https://mautic.org/docs/en/pages/troubleshooting.html
- make sure your cron works and triggers the command correctly.

I will close this issue for now since I think the problem is in one of the suggestions above, but feel free to update this issue with more information and I'll open it again.

**Closed by escopecz** 2016-05-02 12:32 UTC
