### ISSUE TITLE
MauticJS.sendPageview only records page_url, does not store other page_title or anything else

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#6921] opened 2018-11-23 18:15 UTC
## Bug Description
Using MauticJS.sendPageview only stores page_url but it does not store page_title, language, or referrer. 

I have checked the contact history at http://mauticinstallation.com/s/contacts/view/ only, the referrer is updated with the values I set. 

I have checked database. In page_hits table, only url is updated. title is set to NULL, referrer is set to the mautic landing page that I called sendPageview from (expected behavior is that it should be set to the value I passed in), language is set to NULL. "query" column shows that only page_url was updated.

This may be same as #6909, I don't know.

| Q   | A
| --- | ---
| Mautic version | 2.4.12 |
| PHP version | 7.1 |
| Browser | Chrome, Firefox latest version |

### Steps to reproduce
1. go to a mautic landing while not logged in (open incognito if you're logged in)
2. wait for page to finish loading
3. open developer tools and copy/paste this one or both of these:
```
MauticJS.sendPageview(['send', 'pageview', {
            page_title: 'title - test' 
            page_url: 'url - test,		
            page_referrer: ' referrer - test ', 
            page_language: 'lang - test', 
        }]);
```
or
```
MauticJS.sendPageview(['send', 'pageview', {
            page_title: 'title 2 - test' 
            page_url: 'url  2 - test,		
            referrer: ' referrer  2  - test ', 
            language: 'lang  2 - test', 
        }]);
```
4. open the contact timeline in mautic and check 
 
### Log errors
None in apached access_log or error_log. None in mautic log.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment] 2018-11-24 12:34
Please test https://github.com/mautic/mautic/pull/6802

**Comment by Woeler** [comment] 2018-11-24 12:36
Duplicate of https://github.com/mautic/mautic/issues/6909

**Closed by Woeler** 2018-11-24 12:36 UTC
