### ISSUE TITLE
Landing Page Form Freezes at Please Wait... state.

### ISSUE THREAD

**Issue by auroralabs** [mautic/mautic#4473] opened 2017-07-20 09:26 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
Just updated to the latest version and have noticed that when I fill in a landing page form that utilises a mautic generated form the submit button stays on the Please Wait... state. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version |  PHP 7.0.20 

### Steps to reproduce:
1. Embed form on landing page (Automatic or Manually)
2. Send Test Email
3: Visit Landing Page via Link
4: Fill in Form & Hit Submit
5: Form Stalls at Please Wait... state.

Example: https://mautic.eafs-info.com/newsgatc007
 
### Log errors: 

[2017-07-20 11:36:41] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/html/mautic.eafs-info.com/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/html/mautic.eafs-info.com/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by escopecz** [comment] 2017-07-20 09:47
Duplicate of https://github.com/mautic/mautic/issues/4349

**Closed by escopecz** 2017-07-20 09:47 UTC
