### ISSUE TITLE
Can't use 'Company Name' on Reports

### ISSUE THREAD

**Issue by andrecgro** [mautic/mautic#2860] opened 2016-10-28 16:13 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
After upgrading Mautic from 2.1.1 to 2.2.1 it always shows an error when I try to access a created report that uses "Company Name". Mautic tells me that the l.companyname column doesn't exist but when I try to clear the cache or run the migrations, the error keep occurring and when I try to update the schema I receive a few errors from Doctrine and PDOException.

![](https://puu.sh/rYCbK/5630c9743d.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a report with these settings:
![](https://puu.sh/rYBrz/522d30466d.png)
2. Try to access the created report
 
### Log errors: 

[2016-10-28 11:52:17] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT l.firstname AS firstname, l.lastname AS lastname, l.companyname AS companyname, l.companyemail AS companyemail FROM leads l INNER JOIN lead_lists_leads s ON s.lead_id = l.id AND s.manually_removed = 0 WHERE (l.date_added BETWEEN ? AND ?) AND (s.leadlist_id = ?) ORDER BY l.companyname ASC LIMIT 30 OFFSET 0' with params ["2016-09-28 04:00:00", "2016-10-28 15:52:17", "6"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companyname' in 'field list'" at /home/marketing/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT l.firstname AS firstname, l.lastname AS lastname, l.companyname AS companyname, l.companyemail AS companyemail FROM leads l INNER JOIN lead_lists_leads s ON s.lead_id = l.id AND s.manually_removed = 0 WHERE (l.date_added BETWEEN ? AND ?) AND (s.leadlist_id = ?) ORDER BY l.companyname ASC LIMIT 30 OFFSET 0' with params [\"2016-09-28 04:00:00\", \"2016-10-28 15:52:17\", \"6\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companyname' in 'field list' at /home/marketing/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companyname' in 'field list' at /home/marketing/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companyname' in 'field list' at /home/marketing/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by escopecz** [comment] 2016-10-28 17:36
Seems like duplicate of https://github.com/mautic/mautic/issues/2784

**Closed by escopecz** 2016-10-28 17:36 UTC
