### ISSUE TITLE
Migration 20210502162314 was executed but did not result in any SQL statements

### ISSUE THREAD

**Issue by EnziinSystem** [mautic/mautic#10485] opened 2021-09-28 09:57 UTC
### Mautic Version

4.0.0

### PHP version

PHP/7.4.24

### What browsers are you seeing the problem on?

Not relevant

### What happened?

A bug happened!

### How can we reproduce this issue?

Step 1: Update from Mautic 3.3.4

php bin/console cache:clear

php bin/console mautic:update:find

php bin/console mautic:update:apply

php bin/console doctrine:migration:status

php bin/console doctrine:migration:migrate

### Relevant log output

```shell
Migrating up to 20210614151138 from 20210223174702

  ++ migrating 20200810153131

     -> ALTER TABLE oauth2_accesstokens CHANGE user_id user_id INT UNSIGNED DEFAULT NULL
     -> ALTER TABLE oauth2_clients ADD role_id INT UNSIGNED DEFAULT NULL
     -> ALTER TABLE oauth2_clients ADD CONSTRAINT FK_CLIENT_ROLE FOREIGN KEY (role_id) REFERENCES roles (id)
     -> CREATE INDEX IDX_CLIENT_ROLE ON oauth2_clients (role_id)

  ++ migrated (took 825.1ms, used 46.5M memory)

  ++ migrating 20201207114926

     -> UPDATE lead_fields SET is_unique_identifer = 0 WHERE object = 'company';
     -> UPDATE lead_fields SET is_unique_identifer = 1 WHERE object = 'company' and alias in ('companyname');

  ++ migrated (took 7.0999999999999ms, used 46.5M memory)

  ++ migrating 20201228041109

     -> ALTER TABLE assets MODIFY remote_path LONGTEXT
     -> ALTER TABLE assets MODIFY original_file_name LONGTEXT

  ++ migrated (took 92.6ms, used 46.5M memory)

  ++ migrating 20210502162314

Migration 20210502162314 was executed but did not result in any SQL statements.

  ++ migrated (took 1.3000000000001ms, used 46.5M memory)

  ++ migrating 20210609191822

     -> ALTER TABLE oauth1_access_tokens DROP FOREIGN KEY FK_C33AC86237FDBD6D
     -> ALTER TABLE oauth1_request_tokens DROP FOREIGN KEY FK_80F3C6EA37FDBD6D
     -> DROP TABLE oauth1_access_tokens
     -> DROP TABLE oauth1_consumers
     -> DROP TABLE oauth1_nonces
     -> DROP TABLE oauth1_request_tokens

  ++ migrated (took 1111.5ms, used 48.5M memory)

  ++ migrating 20210614151138

     -> ALTER TABLE webhooks MODIFY webhook_url LONGTEXT NOT NULL

  ++ migrated (took 40.2ms, used 48.5M memory)

  ------------------------

  ++ finished in 2085.3ms
  ++ used 48.5M memory
  ++ 6 migrations executed
  ++ 15 sql queries
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment] 2021-11-09 14:17
@dennisameling is that a bug ?

**Comment by RCheesley** [comment] 2022-02-05 12:12
I don't see any bug here. It's not a bug if a migration doesn't have anything to do when it runs. Closing the issue as a result.

**Closed as completed by RCheesley** 2022-02-05 12:12 UTC
Labels: bug, needs-triage
