### ISSUE TITLE
Mautic v1.4.1 - Unable do Add (Manually) or Edit Leads

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#1881] opened 2016-06-16 19:32 UTC
## Description
Every time I try to add or edit a lead nothing happens and Mautic generates the following error (in the log file):

PHP Fatal error:  Call to a member function isRendered() on a non-object in ../vendor/symfony/form/Symfony/Component/Form/FormRenderer.php on line 169

I tried to apply the fixes contained in similar (and previously) reported bugs but no success.

**Comment by manuelfink** [comment] 2016-06-17 09:45
Possible duplicate of #1780 and #1830. Please inspect the comments there and also please test if #1827 fix it for you.

Quick fix: check if all form fields you recently added have the field order set. Select a position in field order and resave field should fix the problem for now

**Comment by edutj** [comment] 2016-06-18 11:19
I handled it by publishing some of the fields that where unpublished. I had to check one by one to see which ones I could leave unpublished.

**Closed** 2016-06-25 16:04 UTC
