### ISSUE TITLE
Update contact Tags

### ISSUE THREAD

**Issue by rahulwalunje** [mautic/mautic#3161] opened 2016-12-30 04:38 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | / 
| Enhancement? | /

## Description:
Trying to Update existing known contact with Mautic API it works. But when I update with tags attribute gets Internal server error and contact not gets updated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 5.2.0

### Steps to reproduce:
1. Add new contact with tags
2. Update contact from API with PATCH request
 
### Log errors: 

[body] => {"error":{"message":"Catchable Fatal Error: Argument 1 passed to Mautic\\LeadBundle\\Entity\\Lead::addTag() 
    must be an instance of Mautic\\LeadBundle\\Entity\\Tag, null given, called in \/var\/www\/html\/mautic.sharkz.in\/public_html\/app\/bundles\/LeadBundle\/Model\/LeadModel.php on line 1904 and defined","code":500}}

**Comment by MarkLL** [comment] 2016-12-30 08:28
So it seems this was because @rahulwalunje was attempting to use tags as a comma delimited string instead of an array. e.g. `'tags'='tag1,tag2'` instead of `'tags'=>['tag1','tag2']`

**Comment by rahulwalunje** [comment] 2016-12-30 08:30
@MarkLL I will try it using array and get back to this issue.

**Comment by rahulwalunje** [comment] 2016-12-30 09:30
@MarkLL I have tested well and figure out what exactly happening. 
either `'tags'='tag1,tag2'` or `'tags'=>['tag1','tag2']` both works fine.

But when update contact ( making PATCH request ) and passing tags which are already assigned to that contact in Mautic. I get Fetal error as pasted in issue -- Log errors.

Let's say I am passing `['tag1','tag2','tag3']` in tags as new tags. 
While updating contact, I am using same tags `['tag1','tag2','tag3']` it will return Internal server error.

Now, If I change it to `['tag4','tag2','tag3']` -- contact will be updated ( I just changed first tag value and still it worls! ).

Please note : I am using OAuth2 authentication.

**Comment by MarkLL** [comment] 2016-12-30 10:03
@rahulwalunje Hmmm, I don't bother with PATCH because using Create, it checks for a matching email address automatically and switches to edit mode and just updates it. Why don't you try using create, if you know the email, while I look to see if there is anything obvious with the PATCH method in the code. Have you tried the API just to check it's not your code? - sorry had to ask.

**Comment by rahulwalunje** [comment] 2016-12-30 10:54
slightly going out of point. When you said 'switches to edit mode and just updates contact' there were one ticket https://github.com/mautic/mautic/issues/3108 
and there were no new Mautic updates after it. So is it included in Mautic now?

**Comment by MarkLL** [comment] 2016-12-30 10:56
It's been approved for the next release, but you could always apply the changes yourself??

**Comment by MarkLL** [comment] 2016-12-30 10:57
I had a partial fix in my dev system and I only used the same tags so did not see the issue. A mix of existing and new is when the issue shows

**Comment by escopecz** [comment] 2017-01-02 08:35
This is duplicate of https://github.com/mautic/mautic/issues/3127

**Closed by escopecz** 2017-01-02 08:35 UTC
