### ISSUE TITLE
Site offline error on login after new install

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3361] opened 2017-02-07 22:08 UTC
Everything seems to install fine, but on login, I'm getting this "site offline" and error. This only happens when I try to install from git. Works fine when I download from mautic.org (and don't have to "composer install"). Any idea what I'm missing here?

Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getIntegrationSettings() on boolean
/plugins/MauticSocialBundle/EventListener/ChannelSubscriber.php:56

```
1. /plugins/MauticSocialBundle/EventListener/ChannelSubscriber.php:56 at

2. MauticPlugin\MauticSocialBundle\EventListener\ChannelSubscriber -> onAddChannel ( object(ChannelEvent (Mautic\ChannelBundle\Event\ChannelEvent)), 'mautic.add_channel',
object(ContainerAwareEventDispatcher  (Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) )

3. /app/cache/prod/classes.php:2239 at call_user_func ( array(object(ChannelSubscriber (MauticPlugin\MauticSocialBundle\EventListener\ChannelSubscriber)), 'onAddChannel'),
object(ChannelEvent (Mautic\ChannelBundle\Event\ChannelEvent)), 'mautic.add_channel', object(ContainerAwareEventDispatcher (Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
)

4. /app/cache/prod/classes.php:2154 at Symfony\Component\EventDispatcher\EventDispatcher -> doDispatch ( array(array(object(ChannelSubscriber
(Mautic\EmailBundle\EventListener\ChannelSubscriber)), 'onAddChannel'), array(object(ChannelSubscriber (Mautic\SmsBundle\EventListener\ChannelSubscriber)), 'onAdd-
Channel'), array(object(ChannelSubscriber (MauticPlugin\MauticSocialBundle\EventListener\ChannelSubscriber)), 'onAddChannel'), array(object(ChannelSubscriber (Mautic\NotificationBundle\
EventListener\ChannelSubscriber)), 'onAddChannel'), array(object(ChannelSubscriber (Mautic\DynamicContentBundle\EventListener\ChannelSubscriber)), 'onAddChannel')),
'mautic.add_channel', object(ChannelEvent (Mautic\ChannelBundle\Event\ChannelEvent)) )

5. /app/bundles/ChannelBundle/Helper/ChannelListHelper.php:49 at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( 'mautic.add_channel', object(ChannelEvent
(Mautic\ChannelBundle\Event\ChannelEvent)) )

6. /app/cache/prod/appProdProjectContainer.php:5452 at Mautic\ChannelBundle\Helper\ChannelListHelper -> __construct ( object(ContainerAwareEventDispatcher
(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)), object(Translator (Mautic\CoreBundle\Translation\Translator)) )

7. /vendor/symfony/dependency-injection/Container.php:314 at appProdProjectContainer -> getMautic_Channel_Helper_ChannelListService ( )

8. /app/cache/prod/appProdProjectContainer.php:10676 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.channel.helper.channel_list' )

9. /vendor/symfony/dependency-injection/Container.php:314 at appProdProjectContainer -> getMautic_Lead_Model_LeadService ( )

10. /app/cache/prod/appProdProjectContainer.php:4722 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.lead.model.lead' )

11. /vendor/symfony/dependency-injection/Container.php:314 at appProdProjectContainer -> getMautic_Asset_Model_AssetService ( )

12. /app/cache/prod/appProdProjectContainer.php:4597 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.asset.model.asset' )

13. /vendor/symfony/dependency-injection/Container.php:314 at appProdProjectContainer -> getMautic_Asset_Dashboard_SubscriberService ( )

14. /app/cache/prod/classes.php:2338 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.asset.dashboard.subscriber' )

15. /app/cache/prod/classes.php:2306 at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher -> lazyLoad ( 'mautic.dashboard_on_widget_detail_generate' )

16. /app/cache/prod/classes.php:2153 at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher -> getListeners ( 'mautic.dashboard_on_widget_detail_generate'
)

17. /app/bundles/DashboardBundle/Model/DashboardModel.php:202 at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( 'mautic.dashboard_on_widget_
detail_generate', object(WidgetDetailEvent (Mautic\DashboardBundle\Event\WidgetDetailEvent)) )

18. /app/bundles/DashboardBundle/Model/DashboardModel.php:138 at Mautic\DashboardBundle\Model\DashboardModel -> populateWidgetContent ( object(Widget
(Mautic\DashboardBundle\Entity\Widget)), array('dateFrom' => object(DateTime (DateTime)), 'dateTo' => object(DateTime (DateTime))) )

19. /app/bundles/DashboardBundle/Controller/DashboardController.php:70 at Mautic\DashboardBundle\Model\DashboardModel -> populateWidgetsContent ( object(Paginator
(Doctrine\ORM\Tools\Pagination\Paginator)), array('dateFrom' => object(DateTime (DateTime)), 'dateTo' => object(DateTime (DateTime))) )

20. Mautic\DashboardBundle\Controller\DashboardController -> indexAction ( )

21. /vendor/symfony/http-kernel/HttpKernel.php:144 at call_user_func_array ( array(object(DashboardController (Mautic\DashboardBundle\Controller\DashboardController)),
'indexAction'), array() )

22. /vendor/symfony/http-kernel/HttpKernel.php:64 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request (Symfony\Component\HttpFoundation\Request)),
'1' )

23. /vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php:69 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request (Symfony\
Component\HttpFoundation\Request)), '1', true )

24. /vendor/symfony/http-kernel/Kernel.php:185 at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request

(Symfony\Component\HttpFoundation\Request)), '1', true )
25. /app/AppKernel.php:130 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request (Symfony\Component\HttpFoundation\Request)), '1', true )

26. /app/middlewares/CORSMiddleware.php:92 at AppKernel -> handle ( object(Request (Symfony\Component\HttpFoundation\Request)), '1', true )

27. /app/middlewares/CatchExceptionMiddleware.php:45 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request (Symfony\Component\HttpFoundation\Request)),
'1', true )

28. /app/middlewares/VersionCheckMiddleware.php:57 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request
(Symfony\Component\HttpFoundation\Request)), '1', true )

29. /vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request (Symfony\Component\HttpFoundation\
Request)), '1', true )

30. /vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request (Symfony\Component\HttpFoundation\Request)) )

31. /index.php:34 at Stack\run ( object(StackedHttpKernel (Stack\StackedHttpKernel)) )
```

**Comment by escopecz** [comment] 2017-02-08 09:35
Please provide steps you take to install Mautic from git.

**Comment by vesper8** [comment] 2017-02-08 11:17
I'm getting the same error.

This is what I did to get to this point

git clone https://github.com/mautic/mautic.git mautic.mydomain.com
cd mautic.mydomain.com
mkdir translations (because on a previous run it complained about app/../translations missing, indeed it isn't there for some odd reason)
composer install

I then created a database using Sequel Pro. Went through the installation process, everything worked well.

Created admin user, set my mail to using PHP Mail, then logged in with my admin user and got the same error as OP

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getIntegrationSettings() on boolean
/plugins/MauticSocialBundle/EventListener/ChannelSubscriber.php:56
```

My server is running php 7.0

**Comment by vesper8** [comment] 2017-02-08 11:27
started over, this time I ran

git clone -b master http://mautic.vesper8.com/index.php/s/dashboard

And this time all is good.. I guess initially I got the staging branch and that's what caused that error

**Comment by escopecz** [comment] 2017-02-08 12:45
I can confirm that this happens with installing fresh Mautic with staging branch.,

**Comment by escopecz** [comment] 2017-02-08 12:54
Staging branch fixed with https://github.com/mautic/mautic/commit/a7c9fe2b4dc4d17a3625b847604d2f14ba1bfe57

Try `git pull` to update your files.

**Closed by escopecz** 2017-02-08 12:54 UTC
Labels: Bug
