### ISSUE TITLE
webinair request 

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#3835] opened 2017-04-10 12:36 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.7.1
| PHP version | PHP Version 5.6.30-0+deb8u1

### Steps to reproduce:
1. submit a form 
2. register to webinair
 
### Log errors: 

[2017-04-10 14:32:37] mautic.ERROR: registerToProduct: Bad request [] []
[2017-04-10 14:32:37] mautic.ERROR: onProductRegistration - webinar: Bad request [] []

**Comment by escopecz** [comment] 2017-04-10 12:39
Closing as duplicate of https://github.com/mautic/mautic/issues/3602

Please do not create duplicates of your own previous bug reports.

**Closed by escopecz** 2017-04-10 12:39 UTC
