### ISSUE TITLE
GrapeJS: when clicking enter the screen drops to the bottom and I lose content

### ISSUE THREAD

**Issue by toondeg** [mautic/mautic#11331] opened 2022-07-11 14:38 UTC
### Mautic Version

4.3.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

**If you press Enter within a text block (e.g. for a line spacing) you end up at the end of the template, instead of remaining in the text block where you are currently writing.**

When pressing enter in the GrapeJs email builder the screen drops down to the bottom, you also lose the text you worked in.

I've tested this both on standard templates and custom, having this issue on both.

I've created a recording to clarify things:

https://user-images.githubusercontent.com/104193550/178289837-83a777fb-351e-457d-8122-7117eb934654.mp4

### How can we reproduce this issue?

Step 1:  open random template

Step 2: try to enter in different text blocks

Step 3: close template

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by automatyzuj** [comment] 2022-07-11 14:45
I've got this same. When you click "save" JavaScript is reloaded and content is back visible.

**Comment by jos0405** [comment] 2022-07-12 05:47
Duplicate of
https://github.com/mautic/mautic/issues/11173, maybe close this bug?

**Comment by jos0405** [comment] 2022-07-19 10:23
Duplicate of https://github.com/mautic/mautic/issues/11173.
Plz reopen if I'm wrong.

**Closed as completed by jos0405** 2022-07-19 10:23 UTC
Labels: bug, duplicate, builder-grapesjs
