### ISSUE TITLE
Publish at (date/time) --> This value is not valid.

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#5275] opened 2017-11-03 07:28 UTC
What type of report is this:
https://www.mautic.org/community/index.php//8731-publish-at-date-time-this-value-is-not-valid/p1

| Q  | A
| ---| ---
| Bug report? | 

## Description:
The selector add to the input a incorrect value that when you save show it's not valid

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.11.0

| PHP version | PHP Version 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. edit a campaign 
2. try to select any date in the future
 
### Log errors: 
none

**Comment by npracht** [comment] 2017-11-22 15:43
Hello, this is a duplicate of https://github.com/mautic/mautic/issues/4876

We can reproduce but not in all environments.. We couldn't find yet what is he issue.
@escopecz if you look at https://github.com/mautic/mautic/blob/0e65f3cde5841580f1c3e1339a8c664f83857cb1/app/bundles/CampaignBundle/Form/Type/CampaignType.php#L91 you can see that the expected format is without seconds. But if we start changing the format here from `'yyyy-MM-dd HH:mm'` to `'yyyy-MM-dd HH:mm:ss'` (which actually solved the interface issue), we have to change it in all the Type files (there are severals).

Maybe with that info you can check easier ? :)

N.

**Comment by alanhartless** [comment] 2017-11-24 01:00
It's the seconds and looks like it was introduced with https://github.com/mautic/mautic/pull/4615 to support human readable entries. The temporary fix is to simply manually remove the seconds prior to submitting. 

I would suggest the permanent fix being to revert the change in https://github.com/mautic/mautic/commit/718d2a1f88e66bf645ed7736ee83bfa41a5ca7be#diff-c59ff8626df48aaa206d3d48f946941eL1181 and https://github.com/mautic/mautic/commit/718d2a1f88e66bf645ed7736ee83bfa41a5ca7be#diff-c59ff8626df48aaa206d3d48f946941eL1200 to remove the seconds. Then in https://github.com/mautic/mautic/blob/718d2a1f88e66bf645ed7736ee83bfa41a5ca7be/app/bundles/LeadBundle/Form/Type/EntityFieldsBuildFormTrait.php#L94, set the data-format attribute to be `Y-m-d H:i:s` for datetime and `H:i:s` for time. That should restore BC for everywhere else yet support the required format for contact fields.

**Closed** 2018-01-24 19:54 UTC
Labels: Bug, Ready To Test

**Comment by andremacola** [comment] 2018-06-13 14:55
With api-library for create and edit emails I tried all date formats and they do not work with the API, what I am doing wrong?

```
$emailCreateApi = $api->newApi('emails', $auth, $apiUrl);
$emailArgs = array(
  'emailType' => 'list',
  'subject' => 'Assunto do Email',
  'name' => 'Nome Interno do Email',
  'title' => 'Título do Email',
  'description'	=> 'Descrição do Email criado pela API',
  'isPublished'	=> 0,
  'publishUp' => "2018-06-12 05:17",
  'publishDown' => "2018-06-13 05:17",
  'lists' => array(3),
  'customHtml'	=> '<p>teste de html</p>'
);
$emailCreate = $emailCreateApi->create($emailArgs);
var_dump($emailCreate);
```

```
code' => 400,
'message' => 'The response has unexpected status code (400).
"errors": [
    publishUp: This value is not valid....
]
```
