### ISSUE TITLE
Automatically merge contacts by unique fields when creating via API

### ISSUE THREAD

**Issue by sujaypawar** [mautic/mautic#3108] opened 2016-12-15 17:21 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

I just noticed, I have two contacts in Mautic that have a same email address. I thought, contacts would be merged automatically if their email address is same. Isn't this true?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4
| PHP version | 5.6

### Steps to reproduce:

1. Contact already exists
2. Add same contact in Mautic using API

I might be wrong, but I believe contacts with same email address are merged. Please correct me if I'm misunderstood.

**Comment by Getron** [comment] 2016-12-15 18:16
Same problem here, the contacts are not merged, and all the infos are the same. I have many same contacts, 2, 3 times.

Mautic should be able to merge contacts, if there are same infos on other contact, or maybe, to ask, if i want to merge this 2 contact because of duplicate, or adding as a new contact.

Would be great to have such automation.

**Comment by MxyzptlkFishStix** [comment] 2016-12-16 02:49
![Merge](https://s23.postimg.org/y48zxkbm3/image.png)

**Comment by sujaypawar** [comment] 2016-12-16 04:33
@Getron How are you adding contacts?

I noticed, when using the Mautic forms, the contacts are merged automatically and tracking works as expected. However if you're adding contacts with API, there is an issue.

Multiple contacts means - same person getting multiple emails through campaigns. Moreover, the tracking would be split.

I think the solution would be to add contacts through API in a similar fashion as when they are added through Mautic forms.

**Comment by escopecz** [comment] 2016-12-16 08:37
How about you asked if there is any contact with the email address before you create a new contact? You can do so with search command `email:john@doe.com`. If you're using the PHP Mautic API Library, the query for the contact with the email would be:

```
$contacts = $contactApi->getList('email:john@doe.com');
```

**Comment by sujaypawar** [comment] 2016-12-17 04:05
I had thought of this method before.

But I guess, the problem with this method would be - Mautic won't track the new cookie ID under the same (old) contact ID.

I've noticed the forms in core take care of this as they automatically merge them (new anonymous and old known contact) and so tracking works great.

I will test this better and confirm.

**Comment by kuzmany** [comment] 2016-12-17 16:37
I can confirm. With API merging doesn't work like with forms and result is duplicate contacts with two different cookies and history.

**Comment by Getron** [comment] 2016-12-18 22:40
@sujaypawar I just add contact directly, no api, nothing. add name, add mail, and by mail, if i click tab, it shows me, if there is an duplicate mail, but, if i just drag'n'drop the mail with mouse, it doesn't show anything. I have found, that, maybe, but just, maybe, it shows a duplicate email by drag'n'drop if i click afterward on the grey "lines" between fields, but, just there. And this is not 100% that will work to show a duplicate text under the mail field.

@MxyzptlkFishStix Yes, i known about "manual"merging, but, i mean, mautic should able to automaticaly notice me (or admin that add the contact), that there is a duplicate name, email, or whatever. Maybe, an popup message with buttons, to choose what to do, merge it, add it as duplicate, or clean all fields, and start new contact.

**Comment by sujaypawar** [comment] 2016-12-19 07:18
Hi @escopecz!

**Comment by sujaypawar** [comment] 2016-12-19 07:24
I believe, when adding contacts through API - if Mautic could handle the merging by itself, just as it does with the native forms (instead of having to check if email already exists) - it will solve the problem.

**Comment by kuzmany** [comment] 2017-01-30 19:06
vote for this 👍

**Comment by iadj** [comment] 2017-02-01 18:32
@sujaypawar @escopecz  I tried adding a workaround by rewriting the `mtc_id` cookie. I make a HTTP request to Mautic to search for a user's unique identifier (i.e. email or username) in the server-side.

If a user is found, I retrieve the contact's unique ID from Mautic and overwrite the mtc_id cookie.

This seemed like a good idea, except mtc.js automatically overwrites the mtc_id cookie with every request, so mtc_id would have to be overwritten with every single page request instead of just once.

**Comment by iadj** [comment] 2017-02-01 18:50
Created a PR to make overwriting the mtc_id cookie possible:
https://github.com/mautic/mautic/pull/3327

**Comment by reachadam** [comment] 2017-02-08 02:02
Wow I didn't realize this was happening after I changed all my contact creation to be via the API. Now I don't have any page hit records, seems to me like this should be a high priority and most people using the api to create contacts have no clue that this is happening.

**Comment by kuzmany** [comment] 2017-02-08 13:22
Solution #3317

**Closed** 2017-04-26 13:01 UTC
Labels: Feature Request, Ready To Test

**Comment by hiniesta** [comment] 2017-10-16 10:39
Contacts are merge but not correctly. From my point of view this situation is not working correct:
1) User is on mautic created via API with email aaa@bbb.com and mautic ID 1
2) User is created again by de API with email aaa@bbb.com but mautic ID 2 (has enter via other IP, browser, etc...)

Mautic merge both contacts in contact with ID 2, but all core fields of ID 1 are not included in ID 2 and therefore disappears.

**Comment by kuzmany** [comment] 2017-10-16 10:47
@hiniesta  maybe this could help https://github.com/mautic/mautic/pull/5050

**Comment by savicprvoslav** [comment] 2017-11-03 18:38
I have the same problem, 
if I call the API twice and try to create contact or company unique field setup is not being respected.

**Comment by bilaalabdelhassan** [comment] 2023-02-21 11:41
Was there ever a solution to this?
