### ISSUE TITLE
[feature] Translatable dates

### ISSUE THREAD

**Issue by e-roman** [mautic/mautic#409] opened 2015-05-14 15:46 UTC
It'll be great to have controls to show dates in Spanish format (13 de mayo de 2015 15:38 ) instead of standard English format (May 13, 2015 3:38 pm UTC)

Thanks!

**Comment by alanhartless** [comment] 2015-05-19 20:11
Duplicate of #321

**Closed by alanhartless** 2015-05-19 20:11 UTC
Labels: Feature Request
