### ISSUE TITLE
Web Notification Broken 

### ISSUE THREAD

**Issue by Aneta09** [mautic/mautic#4012] opened 2017-05-07 17:33 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Error like this:
![2017-05-07_19-30-24](https://cloud.githubusercontent.com/assets/25117928/25783385/df888c48-335b-11e7-8d3d-32435aea348e.jpg)

![2017-05-07_19-31-07](https://cloud.githubusercontent.com/assets/25117928/25783396/0d57e72c-335c-11e7-9225-a1e7c947bf1e.jpg)
What can I do to fix it?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.
| PHP version | 7.0

### Steps to re

produce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by tiagofelipe** [comment] 2017-05-08 01:57
For more information about this problem, the problem is in trying to persist an entity with a null field. I made a test by changing the 'mobile' field directly in the database, the mautic saved successfully but after that return on the screen to list the web notifications the same one that was registered is not seen in the list. In the database the registration is persisted successfully. See the symfony log:

mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO push_notifications (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, lang, url, heading, message, button, notification_type, publish_up, publish_down, read_count, sent_count, mobile, mobileSettings, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-05-08 01:31:05", 1, "Tiago Felipe", null, null, null, null, null, null, "notificacao-principal", null, "pt_BR", null, "Gostaria de ser informado sobre novidades da Wtis?", "A Wtis gostaria de enviar avisos para voc\u00ea sempre que uma novidade sobre tecnologia ou promo\u00e7\u00e3o acontecer.", null, "template", null, null, 0, 0, null, "N;", null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mobile' cannot be null" at /home/mwtiscom/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO push_notifications (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, lang, url, heading, message, button, notification_type, publish_up, publish_down, read_count, sent_count, mobile, mobileSettings, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2017-05-08 01:31:05\", 1, \"Tiago Felipe\", null, null, null, null, null, null, \"notificacao-principal\", null, \"pt_BR\", null, \"Gostaria de ser informado sobre novidades da Wtis?\", \"A Wtis gostaria de enviar avisos para voc\\u00ea sempre que uma novidade sobre tecnologia ou promo\\u00e7\\u00e3o acontecer.\", null, \"template\", null, null, 0, 0, null, \"N;\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mobile' cannot be null at /home/mwtiscom/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mobile' cannot be null at /home/mwtiscom/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mobile' cannot be null at /home/mwtiscom/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by escopecz** [comment] 2017-05-08 11:37
Duplicate of https://github.com/mautic/mautic/issues/3961

**Closed by escopecz** 2017-05-08 11:37 UTC
