### ISSUE TITLE
mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "SSL certificate problem: unable to get local issuer certificate" CURL Php

### ISSUE THREAD

**Issue by teddy76db** [mautic/mautic#8905] opened 2020-06-14 00:06 UTC
Hello,
we just installed mautic on our server (NGINX) we used the default configuration file for NGINX, all work perfectly but only one thing, when we wan't to make a FOCUS Item we enter valid informations and we press the button for launch the builder, and when we click on the builder we got an error 500.

We checked in the logs 
 mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "SSL certificate problem: unable to get local issuer certificate" at /home/OURDOMAINNAME/domains/OURSUBDOMAINNAME/public_html/vendor/joomla/http/src/Transport/Curl.php line 185 
{"exception":"[object] (RuntimeException(code: 0): SSL certificate problem: unable to get local issuer certificate at /home/OURDOMAINNAME/domains/OURSUBDOMAINNAME/public_html/vendor/joomla/http/src/Transport/Curl.php:185)"} []

I checked on Github if anyone have this problem, i can't find a solution, if i can have help, thanks a lot !

**Comment by teddy76db** [comment] 2020-06-14 00:10
This is our NGINX Configuration file 👍 
`server {
	server_name OURDOMAINNAMEwww.OURDOMAINNAME
	listen XXX.XX.XX.XXX;
	root /home/OURDOMAINNAME/domains/OURDOMAINNAME/public_html;
	index index.html index.htm index.php;
	access_log /var/log/virtualmin/OURDOMAINNAME_access_log;
	error_log /var/log/virtualmin/OURDOMAINNAME_error_log;
	fastcgi_param GATEWAY_INTERFACE CGI/1.1;
	fastcgi_param SERVER_SOFTWARE nginx;
	fastcgi_param QUERY_STRING $query_string;
	fastcgi_param REQUEST_METHOD $request_method;
	fastcgi_param CONTENT_TYPE $content_type;
	fastcgi_param CONTENT_LENGTH $content_length;
	fastcgi_param SCRIPT_FILENAME /home/OURDOMAINNAME/domains/OURDOMAINNAME/public_html$fastcgi_script_name;
	fastcgi_param SCRIPT_NAME $fastcgi_script_name;
	fastcgi_param REQUEST_URI $request_uri;
	fastcgi_param DOCUMENT_URI $document_uri;
	fastcgi_param DOCUMENT_ROOT /home/OURDOMAINNAME/domains/OURDOMAINNAME/public_html;
	fastcgi_param SERVER_PROTOCOL $server_protocol;
	fastcgi_param REMOTE_ADDR $remote_addr;
	fastcgi_param REMOTE_PORT $remote_port;
	fastcgi_param SERVER_ADDR $server_addr;
	fastcgi_param SERVER_PORT $server_port;
	fastcgi_param SERVER_NAME $server_name;
	fastcgi_param HTTPS $https;
    

     #######################################
    ##  Start Mautic Specific config #####
    #######################################

    # redirect some entire folders
    rewrite ^/(vendor|translations|build)/.* /index.php break;

    location / {

		# First attempt to serve request as file, then
		# as directory, then fall back to index.html
        # one option: try_files $uri $uri/ /index.php$is_args$args;
        try_files $uri /index.php$is_args$args;
 		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}

    # Deny everything else in /app folder except Assets folder in bundles
    location ~ /app/bundles/.*/Assets/ {
        allow all;
        access_log off;
    }
    location ~ /app/ { deny all; }

    # Deny everything else in /addons or /plugins folder except Assets folder in bundles
    location ~ /(addons|plugins)/.*/Assets/ {
        allow all;
        access_log off;
    }
    # location ~ /(addons|plugins)/ { deny all; }

    # Deny all php files in themes folder
    location ~* ^/themes/(.*)\.php {
        deny all;
    }

    # Don't log favicon
    location = /favicon.ico {
    	log_not_found off;
    	access_log off;
    }

    # Don't log robots
    location = /robots.txt  {
    	access_log off;
    	log_not_found off;
    }

    # Deny yml, twig, markdown, init file access
    location ~* /(.*)\.(?:markdown|md|twig|yaml|yml|ht|htaccess|ini)$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Deny all attempts to access hidden files/folders such as .htaccess, .htpasswd, .DS_Store (Mac), etc...
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Deny all grunt, composer files
    location ~* (Gruntfile|package|composer)\.(js|json)$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    #######################################
    ##  End Mautic Specific config #####
    #######################################

        location ~*  \.(jpg|jpeg|png|ico|pdf)$ {
                expires 15d;
        }

	# Deny access to any files with a .php extension in the uploads directory
        location ~* /(?:uploads|files)/.*\.php$ {
                deny all;
        }

        # Solve email tracking pixel not found
        location ~ email/(.*).gif {
        try_files $uri /index.php?$args;
        }
        # Solve JS Loading 404 Error
        location ~ (.*).js {
        try_files $uri /index.php?$args;
        }
 
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_index index.php;
				fastcgi_pass unix:/run/php/php7.3-fpm.sock;
                fastcgi_param   SCRIPT_FILENAME
                                $document_root$fastcgi_script_name;
                include       fastcgi_params;
        }

listen XXX.XX.XXX.XXX:443 ssl;
	ssl_certificate /home/OURDOMAINNAME/domains/OURSUBDOMAINNAME/ssl.cert;
	ssl_certificate_key /home/OURDOMAINNAME/domains/mautic.updoze.com/ssl.key;
}
	`

In addition we use a sub-domain on our server mautic.ourdomain.com.
Thanks.

**Comment by p4trizio** [comment] 2020-06-15 16:51
Same issue for me, using Apache2.4 on Mautic server and target website on the same server.
The problem is the same as of https://github.com/mautic/mautic/issues/7920 and https://github.com/mautic/mautic/issues/3909

**Comment by RCheesley** [comment] 2020-06-15 17:01
Hi folks, there is a [PR pending](https://github.com/mautic/mautic/pull/8894) for a fix which will go into Mautic 3.0.1. For the time being remove the domain from the focus item and you will not see the error.

Closing as a duplicate of #7179

**Closed as completed by RCheesley** 2020-06-15 17:01 UTC
