### ISSUE TITLE
Mail Editor - Up Arrow with no effect

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#14138] opened 2024-09-21 12:51 UTC
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1.

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.23

### What browsers are you seeing the problem on?

Firefox

### What happened?

The up arrow has no effect. What is the function for it? I mean to put a block one step up. That doesn't work.
![Up arror](https://github.com/user-attachments/assets/cc5d53d2-1e1b-43fb-b32b-d6bda72e90b2)

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment] 2024-09-24 10:36
Hi there,

This is to move the block up one position in the nesting within a column, I think. I'll ask some of the builder experts to chime in!

**Comment by LordRembo** [comment] 2024-09-27 15:01
@stefan-franz Clicking the arrow, highlights the parent item. So if you are in a Block, the Section gets selected, for example. 
If you want to move Blocks, you need to press the icon nest to it (the cross with arrows) and then you can drag your item anywhere you want.
It is default behaviour in GrapesJS, as you can see here: https://grapesjs.com/demo-newsletter-editor
But I'd agree that arrow is not the most intuitive, especially because there's no tooltip or something like it on hover.

**Comment by LordRembo** [comment] 2024-09-27 15:02
So basically, it's not a bug but a default feature that's not very intuitive.

**Comment by andersonjeccel** [comment] 2024-10-14 11:21
GrapesJS builder would benefit from tooltips on hover

Closing this issue

**Closed as not planned by andersonjeccel** 2024-10-14 11:21 UTC
Labels: bug, builder-grapesjs
