### ISSUE TITLE
Better Tag Management

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#3653] opened 2017-03-13 00:41 UTC
What type of report is this: Feature request (inspired by bug #3652 )

## Description:
Can we have the ability to do the following tasks on tags:

- View list of where a particular tag is referenced, such as which campaign condition, lead, smart list filter and any other place they can be used. This is like a reverse reference for object, it's actually very common in object driven firewall/UTM devices(Sophos UTM for instance) and it makes managing complicated rulesets much easier, especially when something needs to be updated and systemwide.
- Run a global replacement of a tag, so that any usage of that tag can be substituted with another tag
- Allow tags to be renamed, typos happen and so do naming conventions
- Allow tags to be deleted, where any usage of that tag is removed

**Comment by escopecz** [comment] 2017-03-13 08:40
This seems like a duplicate of https://github.com/mautic/mautic/issues/2308

**Closed by escopecz** 2017-03-13 08:40 UTC
