### ISSUE TITLE
Unable to view the file of some contacts after upgrade

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#7499] opened 2019-05-06 08:08 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | PHP Version 5.6.40-0+deb8u2
| Browser | Chrome Version 74.0.3729.131

### Steps to reproduce
1. View the list of contacts
2. Select a contact
3. The form is not displayed
 
### Log errors
PHP Notice - Undefined variable: submissions - in file /var/www/mautic/app/bundles/FormBundle/Views/Builder/form.html.php - at line 59 [] [] mautic.NOTICE: PHP Notice - Undefined variable: lead - in file /var/www/mautic/app/bundles/FormBundle/Views/Builder/form.html.php - at line 59 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2019-05-17 12:35
Duplicate of https://github.com/mautic/mautic/issues/7135

**Closed by escopecz** 2019-05-17 12:35 UTC
