### ISSUE TITLE
Impossible save Campaing when Close Builder dont work

### ISSUE THREAD

**Issue by leolage** [mautic/mautic#2815] opened 2016-10-24 11:21 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

On Campaing Builder Editor, when I have Campaings with a lot or itens, the Close Builder button dont work, I a lost all modifications. A example of size of my campaing: https://postimg.org/image/a6cyh3f27/
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.27 |
### Steps to reproduce:
1. When I edit campaing with a lot of itens, clicking on Close Builder, the Builder dont close.
2.  I lost all editions because its impossivel close builder and salve or apply changes
3. This ocourring in 80% of times on my big campaings.
### Log errors:

When I see details on firebug, I see this result received by server: {"success":0}

Checking the HTTP request I see this:
action=campaign:updateConnections&campaignId=&mauticUserLastActive=1&mauticLastNotificationId=

*\* campaignId= is empty, this is normal? I checking on a sucessfull close builder, and this campaingID is set correctly.

on server I dont see any errors.

**Comment by escopecz** [comment] 2017-08-25 14:47
Seems like duplicate of https://github.com/mautic/mautic/issues/2899

**Closed by escopecz** 2017-08-25 14:47 UTC
