### ISSUE TITLE
Search bar now only searches for items starting with the searched term

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3116] opened 2016-12-19 10:30 UTC
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
It used to be that you could use the search bar to find items that contained the searched term.
It now only finds items which start with the searched term which is a bit inconvenient...

![image](https://cloud.githubusercontent.com/assets/18265735/21309347/4bcd4542-c5de-11e6-8d5a-c076df349f58.png)

![image](https://cloud.githubusercontent.com/assets/18265735/21309375/6bee5bae-c5de-11e6-87b9-2e06c26cee77.png)

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.14

### Steps to reproduce:
1. Create a segment with a name containing multiple words
2. Search for any word that is not first in that segment's name

**Comment by escopecz** [comment] 2016-12-19 10:42
Duplicate of https://github.com/mautic/mautic/issues/2808

**Closed by escopecz** 2016-12-19 10:42 UTC
