### ISSUE TITLE
Feature request - Improve the lead owner management to campaign action, point trigger, form action, API

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1613] opened 2016-04-19 10:22 UTC
## Description
On the **Update lead action** in **campaign builder**, `fields` are missing.
* as for instance: Lead Owner

---> I think we should find here all the fields related to a lead.

**Comment by escopecz** [comment] 2016-04-20 16:33
All the lead fields are there. What is missing are special lead info like lead owner. Anything else you are missing apart from the owner?

**Comment by npracht** [comment] 2016-04-20 16:41
Hi @escopecz,

Until now, that's the only filed i've seen as missing!

**Comment by npracht** [comment] 2016-05-10 19:50
Hi @escopecz,

Thanks to the recent feature concerning lead owner automation, it takes important place in terms of communication and personal sales approach. The issue is not anymore only concerning the campaign (i'll rename my Issue).

## Problematic
The availability to edit lead owner of a lead is quite limited:
* Manual edit / creation of a lead
* List import
* Maybe API ? (To be checked)

## Suggestion
Add places to edit lead owner of a lead:
* Campaign action « edit lead field » in the dropdown list of selectable fields.
* Point trigger events
* Form action tab
* API (if not already possible)

**Comment by PatchRanger** [comment] 2016-06-09 18:55
Follow-up of https://github.com/mautic/mautic/pull/1319#issuecomment-224569388 : each owner should be matched with separate email transport configuration in order not to get considered as spam in terms of DKIM check.

**Comment by PatchRanger** [comment] 2016-06-17 18:50
I guess I can propose something better than I wrote above: not just email matching but a separate role Owner which could be assigned to site users. Each user with role Owner could then fill in special form of its own transport configuration. In fact there should be several forms: SMTP, Default, Bounce & FBL email boxes configuration. In other words each user of role Owner should have his/her own Email settings. And this configuration then would be used in case of sending emails on behalf of this Owner.
Does it look like good idea? Should I create a PR?

**Comment by npracht** [comment] 2016-06-17 19:34
Hi,

To me it sounds a bit complicated but I'm maybe simply not skilled enough.
I think it can be in a separated feature request as far as my description is a better usage of the actual feature, yours sounds to me more like a version 2 of the feature.

N.

**Comment by alanhartless** [comment] 2016-08-25 18:10
Duplicate of #897

**Closed by alanhartless** 2016-08-25 18:10 UTC
Labels: Feature Request
