### ISSUE TITLE
"Replied email" condition in campaign

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2581] opened 2016-09-21 21:21 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Add a "email replied" condition to campaigns. So we could stop a campaign if the customer has replied to one of the mails of the campaign... 

Command **mautic: email:fetch** already analyze bounces, we could also include replied mails. It could be done through 3 solutions : 
- messageId (but sometimes, messageId is changed, i think that gmail change it)
- from email + subject => last email sent according to this data
- Change the Reply-To header to add a suffix to identify the email (like Return-Path adding +bound-xxxx)

**Comment by escopecz** [comment] 2016-09-22 06:38
This seems to be a duplicate of https://github.com/mautic/mautic/issues/425

**Closed by escopecz** 2016-09-22 06:38 UTC
