### ISSUE TITLE
Button bug with text containing >>

### ISSUE THREAD

**Issue by topproto** [mautic/mautic#8323] opened 2020-01-12 15:07 UTC
1. create a landing page
2. add button
3. in text add >> (eg "click here >> More Info!"
4. add in destination url
4. save

It will look okay but when you view the page the information after >> is spilled out into text on the page showing the text 

> More Info!" data-param-href="your url here">
above the button

**Comment by topproto** [comment] 2020-01-12 15:08
This also breaks the builder if you click on the button element as the link is blank and the text says "Click" - so you cant actually fix it without deleting the button and making another one.

**Comment by aviboy2006** [comment] 2020-05-11 19:13
can i pick this ?

**Comment by RCheesley** [comment] 2020-07-16 14:13
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment] 2020-10-08 18:29
Closing as I am unable to reproduce and there was no feedback.

![screenshot-local mautic3-2020 10 08-19_29_05](https://user-images.githubusercontent.com/2930593/95499026-95efc900-099c-11eb-99ba-4c70ed7d13d7.png)

**Closed by RCheesley** 2020-10-08 18:29 UTC
Labels: bug, builders, pending-feedback
