### ISSUE TITLE
Roll defining does not save or crashes

### ISSUE THREAD

**Issue by victorkoopman** [mautic/mautic#2703] opened 2016-10-10 20:42 UTC
What type of report is this:

| Q  
| ---| ---
| Bug report | 

## Description:
I am creating a roll besides administrator with limited rights. When choosing the right in all categories an internal server 500 error appears (Uhm, I think I broke it... message).
Some categories are filled in. I did some trial and error and found it goed wrong in three categories.
Dynamic content: it won't save the selected boxes
Focus Permissions: it crashes and shows server 500 error
Social Permissions: it won't save the selected boxes

I skipped these categories and managed to create a user with limited right, but without limiting the right on above categories.

## If a bug:

| Q   
| --- | ---
| Mautic version 2.2.0 | 
| PHP version 7.0 |  

### Steps to reproduce:
1. create a roll and limit the rights
2.  look at Dynamic content, Focus Permissions, Social Permissions
 
### Log errors: 
A lot of the same error:

[2016-10-10 22:31:26] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for focusBundle!" at /home/geenac1q/it2grow.leadmaestro.nl/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 129 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for focusBundle! at /home/geenac1q/it2grow.leadmaestro.nl/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:129)"} []
![image](https://cloud.githubusercontent.com/assets/22594679/19250435/93309f2c-8f3a-11e6-8d72-d8fad4ddacef.png)

![image](https://cloud.githubusercontent.com/assets/22594679/19250438/9e78d1a6-8f3a-11e6-9183-4c622ffeadb5.png)
![image](https://cloud.githubusercontent.com/assets/22594679/19250460/b3d23ca4-8f3a-11e6-99e7-c5d043a7438c.png)

![image](https://cloud.githubusercontent.com/assets/22594679/19250485/c8d12084-8f3a-11e6-9417-0e431eb35ffd.png)

![image](https://cloud.githubusercontent.com/assets/22594679/19250506/d627415a-8f3a-11e6-93e1-9493bff81cef.png)

**Comment by alanhartless** [comment] 2016-10-11 03:08
Duplicate of #2674

**Closed by alanhartless** 2016-10-11 03:08 UTC
