### ISSUE TITLE
Cloning Campaigns only works for published Campaigns

### ISSUE THREAD

**Issue by CyberZen53** [mautic/mautic#1070] opened 2015-10-28 02:09 UTC
When cloning an unpublished campaign (reason was to test workflow on an admin-only test list), the Campaign Builder was empty of all actions and decisions.  It only shows the lead list. 

If I clone a published campaign, however, all campaign actions and decisions copy over successfully.

I'm not sure if this is the expected behavior, but I thought it helpful to submit this as a potential bug. At a minimum, consider preventing the cloning of unpublished campaigns. 

Better yet would be to allow unpublished cloning.

**Comment by alanhartless** [comment] 2015-10-28 04:41
Is this consistently reproducible? I just tried cloning a several unpublished and published campaigns and they all correctly cloned the actions and decisions as well.

Could there be another factor that is causing the issue?

**Comment by CyberZen53** [comment] 2015-10-28 21:57
Definitely possible I got this wrong: I confess I only had the problem with one very complex campaign.

I will test some more to verify and attempt to isolate the problem.

It sounds likely the campaign I tested had another issue (though it didn't throw any errors in the UI).

**Comment by npracht** [comment] 2015-11-09 16:58
Hi,

I've met the same issue. But a slight
* Cloning unpublished campaign, save ---> **Broken**
* Cloning unpublished campaign, launch generator ---> **We see the campaign** ---> close generator, save ---> **Broken**

Thanks,

N.

**Comment by mlohoar** [comment] 2016-02-05 13:57
Same as npracht. Cloning of Campaigns seems not to be working.
Tried on 3 different fresh installs. 2 versions of 1.2.4 on cpanel. 1 manual install of the master locally on IIS.

**Comment by mlohoar** [comment] 2016-02-05 14:21
FYI same problem on a new account on mautic.com

**Comment by mlohoar** [comment] 2016-02-05 14:47
Works in V1.2.3

**Comment by diouro** [comment] 2016-02-29 01:23
Running v1.2.4 encountering same problem when cloning a published and unpublished campaign.

When cloning from the campaign list it doesn't even copy all the actions. When cloning for inside the campaign it seems to copy the action and all the event look in place when you launch the campaign builder, but as you save and reopen the campaign and launch the campaign builder again it show all the action unlinked.

I had a look in the table campaign_events and all the campaign_id with the parent_id seems to be ok.

Looking forward to have it fixed.

Btw,
Congratulations for the amazing tool.

**Comment by npracht** [comment] 2016-03-09 14:52
Hi guys & @alanhartless,
We have new elements to provide after my colleague @LAN-Laurene worked on it. Now we're blocked cause it's too technical for us until now. **Please help !**

## Context of the issue
We wanna clone an existing campaign.

## What's happening - definition of the issue
No trouble when we clone, we land on the cloned campaign to edit. 

### 1st case
1. You directly open the campaign generator `events` and `connections`are existing and well cloned.
2. You **Save and close**.
3. You edit the campaign, open the campaign generator and `connections` disappeared. Concerning `events`, they are all stacked on the top left of the canvas.

### 2nd case
1. You don't open the campaign generator.
2. You directly **Save and close**.
3. You edit the campaign, open the campaign generator and all `connections` and `events` disappeared except the `Lead Source event` which is the `event #1`.

## What's happening in the database
In the `campaigns` table: `canvas_settings` field contains an `array` containing `events X,Y position` and `connections sourceId / connections targetId` between all the `events`.

### On a cloned campaign
**The `id`, `sourceId` and `targetId` of the cloned `events` are missing.**

## What we've found in the code
### 1st case (explained previously)
1. In the function `setCanvasSettings()` of file `CampaignModel` we see that the parameter `$events`is incomplete ---> `id` are missing.
2. However, `events` are well saved in the database table `campaign_events` with the great `values` for each `fields`.
3. The function `setEvents()` seems not getting the new `id` of the `event`.

### 2nd case (explained previously)
The function `setEvents()` is simply not called.

**Comment by escopecz** [comment] 2016-03-09 15:08
Seems like duplicate of https://github.com/mautic/mautic/issues/1182 , but better described :) I also tried to fix this issue, but got lost in the code. All the sessions and the whole complexity.

**Comment by leonidr** [comment] 2016-03-18 16:33
Just guessing without looking at the code - the id field is "auto_increment" and is not assigned until cloned event is persisted to DB.

**Comment by escopecz** [comment] 2016-05-02 15:02
Fixed in https://github.com/mautic/mautic/pull/1566, will be released in Mautic 1.4.0

**Closed by escopecz** 2016-05-02 15:02 UTC
Labels: Bug, Pending Feedback, Ready To Test
