### ISSUE TITLE
Marketplace Error 500 after fresh install with composer!

### ISSUE THREAD

**Issue by demianrihs** [mautic/mautic#12285] opened 2023-05-01 19:22 UTC
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

500 Internal server Error trying to access /s/marketplace

I made a new mautic installation using the official guide and using the composer. After a succesful installation I enabled updates via composer on the main settings page and tried to access the marketplace. but it is throwing an error 500

### How can we reproduce this issue?

Step 1: Install Mautic following https://docs.mautic.org/en/setup/how-to-install-mautic/install-and-manage-mautic-with-composer
Step 2: Enable Mautic Marketplace
Step 3: Access Mautic Marketplace (nothing happens) Access url direclty and error 500 is shown

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment] 2023-06-05 21:10
Seems to have the same root cause as: https://github.com/mautic/mautic/issues/11720

`
Log message in Mautic: [2023-06-05 23:07:38] mautic.CRITICAL: Uncaught PHP Exception LogicException: "psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x." 
`

**Comment by dsp76** [comment] 2023-06-05 21:13
The suggested workaround downgrading simple-cache works:
"composer2 require phpoffice/phpspreadsheet:1.24.0 -w"

Lets close this as a duplicate in favor of #11720

**Closed as not planned by dsp76** 2023-06-05 21:13 UTC
Labels: duplicate, composer
