### ISSUE TITLE
Feature: Allow 2-legged Oauth or service accounts for API access

### ISSUE THREAD

**Issue by amit777** [mautic/mautic#1786] opened 2016-05-24 07:09 UTC
## Description
When doing backend integration from system to system, a web authentication flow is not desirable.  It would be cool if we could have a 3rd type of option where a random set of keys can be generated.  Most service providers including Marketo, Hubspot, Mandrill, SES and even Gmail have this type of feature.  It will make it very simple for people to create 3rd party libraries to complement the PHP API library.

**Comment by alanhartless** [comment] 2016-08-25 18:06
Closing this as a duplicate of #1430

**Closed by alanhartless** 2016-08-25 18:06 UTC
Labels: Feature Request
