### ISSUE TITLE
Error on insert page hit into db

### ISSUE THREAD

**Issue by FerRubioMorales** [mautic/mautic#4519] opened 2017-07-26 06:38 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
Mautic throw error on insert page hit (Look at mautic logs section of this page fo the error). Seems that user agent should be decode before insert. If you decode hex you get this: 

Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A403 [FBAN/FBIOS;FBAV/68.0.0.49.70;FBBV/41924288;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/10.0.1;FBSS/2;FBCR/OrangeEspaña;FBID/phone;FBLC/es_ES;FBOP/5]

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.1

### Steps to reproduce:
1. Unknow who send this page hit
 
### Log errors: 

[2017-07-25 08:23:18] mautic.ERROR: An exception occurred while executing 'INSERT INTO page_hits (date_hit, date_left, country, region, city, isp, organization, code, referer, url, url_title, user_agent, remote_host, page_language, browser_languages, tracking_id, source, source_id, query, page_id, redirect_id, email_id, lead_id, ip_id, device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2017-07-25 08:23:18", null, "Spain", "Barcelona", "Barcelona", "", "", 200, "http:\/\/m.facebook.com", "\/typeform-fertilidad?utm_source=facebook&utm_medium=social&utm_campaign=typeform-fbads", null, "\x4d\x6f\x7a\x69\x6c\x6c\x61\x2f\x35\x2e\x30\x20\x28\x69\x50\x68\x6f\x6e\x65\x3b\x20\x43\x50\x55\x20\x69\x50\x68\x6f\x6e\x65\x20\x4f\x53\x20\x31\x30\x5f\x30\x5f\x31\x20\x6c\x69\x6b\x65\x20\x4d\x61\x63\x20\x4f\x53\x20\x58\x29\x20\x41\x70\x70\x6c\x65\x57\x65\x62\x4b\x69\x74\x2f\x36\x30\x32\x2e\x31\x2e\x35\x30\x20\x28\x4b\x48\x54\x4d\x4c\x2c\x20\x6c\x69\x6b\x65\x20\x47\x65\x63\x6b\x6f\x29\x20\x4d\x6f\x62\x69\x6c\x65\x2f\x31\x34\x41\x34\x30\x33\x20\x5b\x46\x42\x41\x4e\x2f\x46\x42\x49\x4f\x53\x3b\x46\x42\x41\x56\x2f\x36\x38\x2e\x30\x2e\x30\x2e\x34\x39\x2e\x37\x30\x3b\x46\x42\x42\x56\x2f\x34\x31\x39\x32\x34\x32\x38\x38\x3b\x46\x42\x52\x56\x2f\x30\x3b\x46\x42\x44\x56\x2f\x69\x50\x68\x6f\x6e\x65\x37\x2c\x32\x3b\x46\x42\x4d\x44\x2f\x69\x50\x68\x6f\x6e\x65\x3b\x46\x42\x53\x4e\x2f\x69\x4f\x53\x3b\x46\x42\x53\x56\x2f\x31\x30\x2e\x30\x2e\x31\x3b\x46\x42\x53\x53\x2f\x32\x3b\x46\x42\x43\x52\x2f\x4f\x72\x61\x6e\x67\x65\x45\x73\x70\x61\xf1\x61\x3b\x46\x42\x49\x44\x2f\x70\x68\x6f\x6e\x65\x3b\x46\x42\x4c\x43\x2f\x65\x73\x5f\x45\x53\x3b\x46\x42\x4f\x50\x2f\x35\x5d", null, "es", "a:1:{i:0;s:5:\"es-es\";}", "f970edcfe98c60e26902071576774a3735d714f7", null, null, "a:1:{i:0;s:73:\"utm_campaign=typeform-fbads&utm_medium=social&utm_source=facebook\";}", 2, null, null, 21757, 708, 10592]:  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF1a;FBI...' for column 'user_agent' at row 1 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO page_hits (date_hit, date_left, country, region, city, isp, organization, code, referer, url, url_title, user_agent, remote_host, page_language, browser_languages, tracking_id, source, source_id, query, page_id, redirect_id, email_id, lead_id, ip_id, device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"2017-07-25 08:23:18\", null, \"Spain\", \"Barcelona\", \"Barcelona\", \"\", \"\", 200, \"http:\\/\\/m.facebook.com\", \"\\/typeform-fertilidad?utm_source=facebook&utm_medium=social&utm_campaign=typeform-fbads\", null, \"\\x4d\\x6f\\x7a\\x69\\x6c\\x6c\\x61\\x2f\\x35\\x2e\\x30\\x20\\x28\\x69\\x50\\x68\\x6f\\x6e\\x65\\x3b\\x20\\x43\\x50\\x55\\x20\\x69\\x50\\x68\\x6f\\x6e\\x65\\x20\\x4f\\x53\\x20\\x31\\x30\\x5f\\x30\\x5f\\x31\\x20\\x6c\\x69\\x6b\\x65\\x20\\x4d\\x61\\x63\\x20\\x4f\\x53\\x20\\x58\\x29\\x20\\x41\\x70\\x70\\x6c\\x65\\x57\\x65\\x62\\x4b\\x69\\x74\\x2f\\x36\\x30\\x32\\x2e\\x31\\x2e\\x35\\x30\\x20\\x28\\x4b\\x48\\x54\\x4d\\x4c\\x2c\\x20\\x6c\\x69\\x6b\\x65\\x20\\x47\\x65\\x63\\x6b\\x6f\\x29\\x20\\x4d\\x6f\\x62\\x69\\x6c\\x65\\x2f\\x31\\x34\\x41\\x34\\x30\\x33\\x20\\x5b\\x46\\x42\\x41\\x4e\\x2f\\x46\\x42\\x49\\x4f\\x53\\x3b\\x46\\x42\\x41\\x56\\x2f\\x36\\x38\\x2e\\x30\\x2e\\x30\\x2e\\x34\\x39\\x2e\\x37\\x30\\x3b\\x46\\x42\\x42\\x56\\x2f\\x34\\x31\\x39\\x32\\x34\\x32\\x38\\x38\\x3b\\x46\\x42\\x52\\x56\\x2f\\x30\\x3b\\x46\\x42\\x44\\x56\\x2f\\x69\\x50\\x68\\x6f\\x6e\\x65\\x37\\x2c\\x32\\x3b\\x46\\x42\\x4d\\x44\\x2f\\x69\\x50\\x68\\x6f\\x6e\\x65\\x3b\\x46\\x42\\x53\\x4e\\x2f\\x69\\x4f\\x53\\x3b\\x46\\x42\\x53\\x56\\x2f\\x31\\x30\\x2e\\x30\\x2e\\x31\\x3b\\x46\\x42\\x53\\x53\\x2f\\x32\\x3b\\x46\\x42\\x43\\x52\\x2f\\x4f\\x72\\x61\\x6e\\x67\\x65\\x45\\x73\\x70\\x61\\xf1\\x61\\x3b\\x46\\x42\\x49\\x44\\x2f\\x70\\x68\\x6f\\x6e\\x65\\x3b\\x46\\x42\\x4c\\x43\\x2f\\x65\\x73\\x5f\\x45\\x53\\x3b\\x46\\x42\\x4f\\x50\\x2f\\x35\\x5d\", null, \"es\", \"a:1:{i:0;s:5:\\\"es-es\\\";}\", \"f970edcfe98c60e26902071576774a3735d714f7\", null, null, \"a:1:{i:0;s:73:\\\"utm_campaign=typeform-fbads&utm_medium=social&utm_source=facebook\\\";}\", 2, null, null, 21757, 708, 10592]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF1a;FBI...' for column 'user_agent' at row 1 at /home/virtualmin/x.x.x/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF1a;FBI...' for column 'user_agent' at row 1 at /home/virtualmin/x.x.x/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF1a;FBI...' for column 'user_agent' at row 1 at /home/virtualmin/x.x.x/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by escopecz** [comment] 2017-07-26 07:06
Is this happening regularly or is this just a weird one time error you found in the logs? It'd be very helpful if we could replicate it somehow.

**Comment by FerRubioMorales** [comment] 2017-07-26 07:14
It's  just a weird one time error. But i got also this error with this weird values when forms are submitted. I fixed the error on forms changing the html file charset, i don't know if the charset can be the source of the error.

**Comment by Woeler** [comment] 2017-07-26 07:49
Just some extra information here. A hex-decode of the value gives the following result. 

`Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A403 [FBAN/FBIOS;FBAV/68.0.0.49.70;FBBV/41924288;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/10.0.1;FBSS/2;FBCR/OrangeEspa�a;FBID/phone;FBLC/es_ES;FBOP/5]`

Might help narrow down the issue.

**Comment by escopecz** [comment] 2017-08-25 15:01
This is duplicate of https://github.com/mautic/mautic/issues/2790

**Closed by escopecz** 2017-08-25 15:01 UTC
Labels: Bug
