### ISSUE TITLE
"Restart campaign" feature missing Mautic 3.0 +

### ISSUE THREAD

**Issue by vettloffah** [mautic/mautic#9296] opened 2020-10-14 01:37 UTC
## Bug Description

| Q   | A
| --- | ---
| Mautic version |  3.1.0
| PHP version |  7.2.29
| Browser | Chrome

### Steps to reproduce
1. Create campaign 
2. Enable "Allow contacts to restart this campaign" 
3. In the campaign builder, add a campaign segment with contacts
4. Add action, e.g. "send email at relative time period" with 1 minute delay.
5. Add another action - "Change campaign"
Under  `Add contact to` There is no `This campaign (Restart this campaign)` option, as is reported as being a feature since 2.15
There is a "this" option - but it does not add the contact back to the beginning of the campaign. It doesn't seem to actually do anything.

![image](https://user-images.githubusercontent.com/3166892/95933235-0f702880-0d9c-11eb-9351-11aa22656816.png)

Does anyone know why this feature seems to be missing?

**Comment by colourfulowl** [comment] 2020-10-15 09:35
Does it work if you select the campaign instead of using the "this" command? I've don't usually use "this" in my campaigns, but I can confirm it doesn't work on my installs either.

**Comment by vettloffah** [comment] 2020-10-15 13:02
The problem with adding to the same campaign instead of "this" is that the campaign has to be published or it doesn't show up in the list. Also I _think_ I tried that and it doesn't work.

Just to test things out to make sure this is a bug I:

1. installed a fresh version of 2.16 on a fresh LAMP stack
2. Confirmed `This campaign (restart this campaign)` is an option in campaign builder
3. Upgraded to Mautic 3.0
4. Confirmed that the feature is no longer included, and instead replaced by `this` which doesn't actually work

**Comment by galgamo** [comment] 2020-10-19 09:45
I also confirm selecting "this" doesn't work.

Using Mautic 3.1.1
PHP Version 7.3
Browser: Firefox

I am editing to post that, if the campaign is named Campaign1, the event of restart campaign is not scheduled and the option set in add contact is "This" and "Campaign1" it works as expected. Of course, you have to first publish the campaign and then modify it receiving the warning that modifying campaign that are published are risky

I will do further tests to try to find out if there is a problem with scheduling or with names

**Comment by imrodmartin** [comment] 2020-11-14 23:08
Any work around on this?  I tried "this" and restarting the actual campaign.  Also tried sending the contact back to a previous step... nothing worked.

**Comment by vettloffah** [comment] 2020-11-14 23:12
@imrodmartin set up two identical campaigns and ping pong the contacts between them. 

So send from campaign 1 to campaign 2 then back to campaign 1....

**Comment by imrodmartin** [comment] 2020-11-14 23:17
Thanks @vettloffah - what a clunky way to do it - but I appreciate your response!  It seems Mautic just doesn't want to do a "happy birthday" campaign the easy way LOL 😉

**Comment by galgamo** [comment] 2020-11-15 07:04
@imrodmartin It seems as "this" doesnt work. After many test the best workaround I found is the one I mentioned above.

Start your campaign with "this" and when started modify ir and add "your campaign name" next to this.

That works for me. Ping ponging beetween to identical campaign also works, but I find simpler having only one.

Hope you manage yo get It working

**Comment by imrodmartin** [comment] 2020-11-15 13:55
> @imrodmartin It seems as "this" doesnt work. After many test the best workaround I found is the one I mentioned above.
> 
> Start your campaign with "this" and when started modify ir and add "your campaign name" next to this.
> 
> That works for me. Ping ponging beetween to identical campaign also works, but I find simpler having only one.
> 
> Hope you manage yo get It working

Ah!! got it - thanks @galgamo - I didn’t quite get that from the previous comments - thank you for explaining it again!  Community rocks :)

**Comment by RCheesley** [comment] 2020-12-10 22:14
Hi folks, this has been resolved in 3.2.0 so I'm going to close this issue down. The PR for reference is here: https://github.com/mautic/mautic/pull/9418.

**Closed as completed by RCheesley** 2020-12-10 22:14 UTC
Labels: bug, campaigns
