### ISSUE TITLE
"500 Internal Server Error" with ssl let's encrypt

### ISSUE THREAD

**Issue by lucasmoraes804** [mautic/mautic#2478] opened 2016-09-06 02:20 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When I install ssl with let's encrypt in my server and then some page show "500 Internal Server Error".

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.23-

### Steps to reproduce:
When I acess pages s/points/triggers/edit/, s/config/edit, s/themes for exemple
 
### Log errors: 

[2016-09-06 02:13:02] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/admin/web/coach.meusitevendedor.com.br/public_html/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/admin/web/coach.meusitevendedor.com.br/public_html/vendor/paragonie/random_compat/lib/random.php:185)"} []

**Comment by escopecz** [comment] 2016-09-06 05:59
Duplicate of https://github.com/mautic/mautic/issues/2034 - solved there.

**Closed by escopecz** 2016-09-06 05:59 UTC
