### ISSUE TITLE
Google+ Plugin does not save Field Mapping

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5179] opened 2017-10-20 13:20 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
After authorizing Google+, it requires email to be mapped to Mautic.  When selecting email from the drop down on the Mautic side, then clicking SC and going back into the Plugin, the mapping does not persist.  Clicking "Apply", then closing the modal does not work, either.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. Navigate to Plugins
2. Authorize Google+
3. Navigate into Contact Mapping tab
4. Enter email in required space
5. Click SC
6. Re-open Google+ Plugin
7. Email did not save.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by RCheesley** [comment] 2019-11-20 10:41
I am able to replicate this in 2.15.3 and while G+ isn't available for personal use any more, some enterprises use the commercial version.

**Comment by RCheesley** [comment] 2020-05-16 15:41
Duplicate of #4284

**Closed by RCheesley** 2020-05-16 15:41 UTC
Labels: Bug, L1
