### ISSUE TITLE
Error on changing pagination limit

### ISSUE THREAD

**Issue by mgaido** [mautic/mautic#13681] opened 2024-04-22 17:48 UTC
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

When i change the pagination limit, it doesn't consider the change and lists the same amount again.

### How can we reproduce this issue?

Step 1:  Go to contacts page or to contact-fields page
Step 2: Change the pagination limit

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by obamwonyi** [comment] 2024-04-24 12:15
Hi @mgaido  I am unable to reproduce the issue, my output is shown below.
![mgaido_issue_review (2)](https://github.com/mautic/mautic/assets/96271272/e65388f8-da36-4629-ac1a-6ce410a11c94)
![contacts fields](https://github.com/mautic/mautic/assets/96271272/17106344-ab44-48db-ae5e-4d1df33f9edc)


any help on reproducing it will be very much appriciated.

**Comment by escopecz** [comment] 2024-04-25 08:56
@mgaido I'll close this issue as others cannot reproduce. Please come up with more concrete steps to reproduce and I'll reopen it.

Double-check that it's not caused by a Mautic plugin or a browser extension.

**Closed as completed by escopecz** 2024-04-25 08:56 UTC
Labels: bug, needs-triage
