### ISSUE TITLE
Problems with the email editor

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2510] opened 2016-09-11 20:29 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When editing one email (or just pasting HTML code from another editor) and clicking apply/save and close, i get one error about froyla script acting weird and firefox asks me to close or continue. 
script: js/libraries.js?v65c69422:458

Pictures are resized, some don't even show and i get random heights on emails. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6

### Steps to reproduce:
1. Create one email
2. Paste HTML code
3. Click save

Wouldn't it be better to go back to the previous editor? Imported HTML code worked fine there and we didn't have problems. At least until the new editor is mature enough.

**Comment by Arjoni** [comment] 2016-09-11 20:30
Wouldn't it be better to go back to the previous editor? Imported HTML code worked fine there and we didn't have problems. At least until the new editor is mature enough.

**Comment by escopecz** [comment] 2016-09-12 06:08
Please provide the HTML where we will be able to see the problems.

Also, see https://github.com/mautic/mautic/pull/2459 and let us know whether you'd prefer to ditch Outlook support or the image size attributes there.

**Comment by Arjoni** [comment] 2016-09-12 08:57
@escopecz I can send the html in slack (or login details to test yourself) if you want but it happens with all emails that have long html code. 

I don't want my email to change after submit my html code. You mean ditch outlook support for the outlook client or hotmail.com? Before adding this feature, emails didn't look good on outlook?

Is there a temp fix to make emails look good right now? If not, an urgent update fixing this would be very well accepted.
Thank you.

**Comment by escopecz** [comment] 2016-09-12 09:05
The option to add the image sizes was requested by other user as stated in the linked PR description. For the quick fix, you can remove [this line](https://github.com/mautic/mautic/pull/2459/files#diff-c39ac84ffcabd2815b713f76d024a3c1L287) and rebuild the assets as described in the steps to test section of that PR description.

**Comment by Arjoni** [comment] 2016-09-12 09:51
Okay thank you. Is there any ETA on the update?

**Comment by Arjoni** [comment] 2016-09-12 11:56
@escopecz if you meant removing  "imageOutputSize: true,"  I did and it didn't fix anything.

**Comment by escopecz** [comment] 2016-09-12 14:18
Did you rebuild the assets?

**Comment by Arjoni** [comment] 2016-09-12 14:23
Yes, i even created a new email and inserted the HTML code and it was the same. I believe there should be an urgent release that fixes the editor bugs. Literally i have days that i am not running any campaign because the editor is making it unusable for me. Is there any way i can go back to v1.4.1 from 2.1.1?

**Comment by patmifsud** [comment] 2016-09-12 23:12
I lost a weekend to this issue also. 

Happy to test future versions if possible, not familiar with Github, any way for me to sign up to Beta test/ Qa?

**Comment by nbfibres** [comment] 2016-09-14 17:20
I've also lost 2 days to this issue. None of my images will work at all within the email. It has stopped me in my tracks. I agree with Arjoni that we should be able to go back to v1.4.1 so work can continue until the issue is fixed. How can we do this?

**Comment by Arjoni** [comment] 2016-09-14 17:22
You should remove   
useClasses: false,
imageOutputSize: true,
from this file https://github.com/mautic/mautic/pull/2459/files#diff-c39ac84ffcabd2815b713f76d024a3c1L287 lines 286 and 287. Then better use the native templates and you will be fine. I stopped importing external HTML because i never got it working as it was in other editors. Native templates are beautiful.

**Comment by Arjoni** [comment] 2016-09-14 17:23
Also don't forget to clean browser cache (and cloudflare) after editing those files.

**Comment by escopecz** [comment] 2016-09-30 10:55
This should be fixed in Mautic 2.2.0, plus this will be in 2.2.1: https://github.com/mautic/mautic/pull/2601

**Closed by escopecz** 2016-09-30 10:55 UTC
