### ISSUE TITLE
Tag description disabled after save

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12794] opened 2023-10-13 14:19 UTC
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

After creating a new tag, if we want to edit the tag description, the textarea field is disabled, and we are unable to edit it. Mautic 4 version allow the field description to be edited.

![image](https://github.com/mautic/mautic/assets/131262825/d2744e2f-eb06-4525-8e12-9756c715c7f4)

### How can we reproduce this issue?

Step 1: Go to Tags, and create a new one
Step 2: Fill a name and description and save it.
Step 3: Edit the new created tag. The textarea description of the tag is disabled and unable to be edited.

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment] 2023-11-18 08:57
@code5rick 

can you retest this on 5.0.0-rc1? I can't reproduce this

**Comment by code5rick** [comment] 2023-11-20 10:16
Certainly, @mollux  I can't reproduce it either. Since we are now using a different text editor, that bug could be related to the old one.

**Comment by dsp76** [comment] 2024-04-12 23:44
Also tested with 5.0.4 and couldn't reproduce the bug, @code5rick and @mollux - thats why I close this here.

**Closed as not planned by dsp76** 2024-04-12 23:44 UTC
Labels: tags, mautic-5, wont-fix
