### ISSUE TITLE
"1" showing in landingspage (in header) when having analytics code

### ISSUE THREAD

**Issue by dev-marcel** [mautic/mautic#9465] opened 2020-12-02 09:25 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In the landingspage a 1 was showing above the page (See: screenshot)
![image](https://user-images.githubusercontent.com/11071510/100852926-71d5d300-3487-11eb-8d4d-84d754b0b8b8.png)

The 1 was not in the builder, and also was nog visible in the database. After debugging we found that there is code in the PublicController of the Page bundle (PageBundle/Controller/PublicController.php:269) which places the analytics code into the page. Further research shows that the AnalyticsHelper->getCode return true, (which is 1 and is replaced by the PublicController).

In the config file there is valid HTML, the code $parametersHelper->getParameter('google_analytics', '') returns true where it should return the HTML. 

I did not have time to futher debug this issue yet. 

| Q   | A
| --- | ---
| Mautic version | v3.1.2
| PHP version | 7.3
| Browser | All

### Steps to reproduce
1. Go to configuration > Landingspage settings and add code to Analytics script
2. Create/Open landingspage 
 
### Log errors
No errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-12-10 14:58
Hi @dev-marcel thanks for reporting but this is a duplicate of an existing issue which has already been resolved with a PR. Please check out #9352 and test the PR #9389 which has been merged for the next patch release.

**Closed as completed by RCheesley** 2020-12-10 14:58 UTC
Labels: duplicate
