### ISSUE TITLE
Twig Error

### ISSUE THREAD

**Issue by drobotiks** [mautic/mautic#2012] opened 2016-07-11 17:42 UTC
## Description

[2016-07-11 16:12:56] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /home/osdiaz/agora.abs-group.com/public_html/app/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /home/osdiaz/agora.abs-group.com/public_html/app/cache/prod/classes.php:6705)"} []

[2016-07-11 16:12:56] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /home/osdiaz/agora.abs-group.com/public_html/app/cache/prod/classes.php - at line 6705 [] []

I keep getting these messages on my log. .not sure how to fix it. Any Ideas?

## Steps to reproduce

Creating a new email.

**Comment by edutj** [comment] 2016-07-11 18:10
Similar error here:
[11-Jul-2016 16:09:51 UTC] PHP Warning:  include(): Failed opening '/path/to/mautic/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /path/to/mautic/vendor/composer/ClassLoader.php on line 412
[11-Jul-2016 16:09:51 UTC] PHP Fatal error:  Class 'Twig_Node_Expression_Test_Defined' not found in /path/to/mautic/app/cache/prod/classes.php on line 6705

**Comment by escopecz** [comment] 2016-07-12 07:28
This is a duplicate of https://github.com/mautic/mautic/issues/1983

**Closed by escopecz** 2016-07-12 07:28 UTC
