### ISSUE TITLE
Issue creating admin user

### ISSUE THREAD

**Issue by aequasi** [mautic/mautic#21] opened 2015-01-27 02:34 UTC
Trying to create my admin user, but it looks like its trying to connect to a local mysql install, even though i specified a non-localhost ip

```
An error occurred while attempting to create the admin user: 
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by alanhartless** [comment] 2015-01-27 22:11
Hi,

What mysql driver are you using? MySQL (PDO) or MySQLi? (You can look in app/config/local.php if you're not sure).

Do you only get that error when creating an admin user or does it happen elsewhere as well?

Thanks!
Alan

**Comment by aequasi** [comment] 2015-01-27 22:20
I've tried with both. I can't really get past creating the admin user

**Comment by alanhartless** [comment] 2015-01-27 22:39
Ah, so this is this during the installer. Are you on a shared host or VPS?

We use doctrine to handle the database connections and doing a search brought up a possible fix.  Let's see what it does for you.

Open app/config/config.php.  Find a section that looks like this:

```
//Doctrine Configuration
$container->loadFromExtension('doctrine', array(
    'dbal' => array(
        'driver'   => '%mautic.db_driver%',
        'host'     => '%mautic.db_host%',
        'port'     => '%mautic.db_port%',
        'dbname'   => '%mautic.db_name%',
        'user'     => '%mautic.db_user%',
        'password' => '%mautic.db_password%',
        'charset'  => 'UTF8',
        //if using pdo_sqlite as your database driver, add the path in config file
        //e.g. 'database_path' => '%kernel.root_dir%/data/data.db3'
        //'path'    => '%db_path%'
        'types'    => array(
            'datetime' => 'Mautic\CoreBundle\Doctrine\Type\UTCDateTimeType'
        )
    ),

    'orm'  => array(
        'auto_generate_proxy_classes' => '%kernel.debug%',
        'auto_mapping'                => true
    )
));
```

Add this after it:

```

$container->setDefinition('pdo', new \Symfony\Component\DependencyInjection\Definition(
    'PDO',
    array(
        'mysql:host=%mautic.db_host%;port=%mautic.db_port%;dbname=%mautic.db_name%',
        '%mautic.db_user%',
        '%mautic.db_password%'
    )
));
```

Now delete the folder app/cache/prod then try to go through the install.  What happens?

If that fails, remove that section of code, delete app/cache/prod again then try using MySQLi as the driver.  (The key here deleting the app/cache/prod folder). Does that make a difference?

If that still doesn't work, are you using an IP or a domain name for the remote host? I'll need to try to reproduce so I can figure out what could be causing it to not use the remote address.  

Thanks!
Alan

**Comment by aequasi** [comment] 2015-01-27 23:07
That gives me a hole new error:

```
An error occurred while attempting to create the admin user: Access denied for user 'www-data'@'localhost' (using password: NO)
```

I've already tried mysqli while clearing cache, same error as the original post

**Comment by alanhartless** [comment] 2015-01-27 23:11
Just to rule it out, are you sure that your external host is configured to accept connections from whatever your current IP is? 

Thanks,
Alan

**Comment by aequasi** [comment] 2015-01-27 23:22
Yeah, that works fine. It seems like its ignoring the settings i've input on the previous step.

**Comment by alanhartless** [comment] 2015-01-27 23:25
If you are making it to the admin user step, is it populating the database tables?

**Comment by aequasi** [comment] 2015-01-27 23:28
Yeah, the tables are there

**Comment by alanhartless** [comment] 2015-01-27 23:43
Okay, let's try this. Open app/bundles/InstallBundle/Controller/InstallController.php and around line 667 you'll see 

```
            //Add the event listener that adds the table prefix to entity metadata
            $eventManager = new EventManager();
            $eventManager->addEventSubscriber(new DoctrineEventsSubscriber());
```

add this after it

```
$dbParams['pdo'] = new \PDO("mysql:host={$dbParams['host']}:{$dbParams['port']};dbname={$dbParams['dbname']}", $dbParams['username'], $dbParams['password']);
```

What happens? (That's completely untested).

**Comment by aequasi** [comment] 2015-01-28 00:00
From the logs: 

```
SQLSTATE[HY000] [2005] Unknown MySQL server host 'localhost:3306' (2)" at ../app/bundles/InstallBundle/Controller/InstallController.php line 671 {"exception":"[object] (PDOException(code: 2005): SQLSTATE[HY000] [2005] Unknown MySQL server host 'localhost:3306' (2) at .../app/bundles/InstallBundle/Controller/InstallController.php:671)"} []
```

**Comment by alanhartless** [comment] 2015-01-28 00:04
And that's with setting the remote host in step one of the installer?  If you look in app/config/local.php, does it have your remote credentials in there?

**Comment by aequasi** [comment] 2015-01-28 00:07
Ah, yeah, that didnt save it properly. Now with it saved, im getting an "Unkown MySQL server host 'my-server.ip.com:3306'....."

**Comment by alanhartless** [comment] 2015-01-28 00:10
Okay, try changing that line to

```
$dbParams['pdo'] = new \PDO("mysql:host={$dbParams['host']};port={$dbParams['port']};dbname={$dbParams['dbname']}", $dbParams['username'], $dbParams['password']);
```

**Comment by aequasi** [comment] 2015-01-28 00:17
Interesting: 

```
Uncaught PHP Exception PDOException: "SQLSTATE[28000] [1045] Access denied for user 'www-data'@'my-aws-ip' (using password: YES)" at .../app/bundles/InstallBundle/Controller/InstallController.php line 670 {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'www-data'@'my-aws-ip' (using password: YES) at .../app/bundles/InstallBundle/Controller/InstallController.php:670)"} []
```

Thats not the user i told it to use. Should the above be `db_user` and `db_password`?

**Comment by alanhartless** [comment] 2015-01-28 00:22
Sorry; I should pay more attention.  Have too many things going on at once :-)

Change username to user.

Fingers crossed! :-)

**Comment by aequasi** [comment] 2015-01-28 00:30
That worked

**Comment by alanhartless** [comment] 2015-01-28 00:32
Okay great.  So I'll get that added to the code for the pdo driver.  

Did you leave the the code change in config.php? If so, do you have the time (and patience after all that) to try removing the code change in config.php, leaving only the change in InstallController, delete app/cache/prod and try again?  Just wondering if the config file code change is needed or not.

Thanks!
Alan

**Comment by alanhartless** [comment] 2015-02-15 08:11
I've done several successful tests with several remote servers so I think this was an isolated case.  I'm closing for now unless we can find a definite cause/fix within Mautic for it. Unfortunately we can't apply the work around from earlier comments as since we have to support multiple drivers and not just MySql.

Thanks!
Alan

**Closed by alanhartless** 2015-02-15 08:11 UTC

**Comment by davetbo** [comment] 2016-03-13 16:45
I'm getting this error, too.  I have an EC2 linux instance with wordpress running against an RDS MariaDB.   Wordpress is working fine.  I try installing Mautic on the same EC2 instance connecting to the same RDS db, and it's giving me this same error (An error occurred while attempting to create the admin user: Access denied for user 'app_db_user'@'172.xx.yy.zz' (using password: YES) (names and IPs obfuscated).  It creates the tables, so I know it can connect to the database, but then when it gets to the part where it adds the Mautic admin user it gives this error.  I'm not sure how it could connect and create the tables but not be able to connect and insert the admin user.  Please advise.  I'm running Mautic version 1.2.4.

I appreciate your help.

Best,
Dave

**Comment by davetbo** [comment] 2016-03-13 17:12
I just realized 1.3.0 was available, so I just tried with that, too.  It didn't work, either.  Same error. What happens differently during table creation than during the admin user insert?  Is it choking on email address verification or something?  This is a .online TLD email address I'm using.

**Comment by davetbo** [comment] 2016-03-13 22:20
OK, I just went through the effort of spinning up an RDS instance of Mysql 5.6.27  and with Mysql 5.5.46 instead of MariaDB 10.  Same error on both:

An error occurred while attempting to create the admin user: SQLSTATE[28000] [1045] Access denied for user 'app_db_user'@'172.xx.yy.zz' (using password: YES)

There goes my theory that there's some sort of database compatibility issue.

Any thoughts?

**Comment by davetbo** [comment] 2016-03-13 22:41
I figured it out by finding the right places in your code and sticking some logging lines. It was choking on the password that my password vault had generated for app_db_user.  Apparently there was a double quote in it that was being escaped by your input validation, so by the time your code was using the password it had changed.  Your code added some backslashes before the quote.

To reproduce the problem, try assigning a mautic db owner with a password of something like this:
Sxz1ZiE0"JnUw
by the time it's shows up in the dbParams in line 889 of the InstallController.php file, it will look like this:
Sxz1ZiE0\\\\"JnUw

Best,
Dave

**Comment by uhlhosting** [comment] 2019-03-26 01:11
I GOT SAME ISSUE!
