### ISSUE TITLE
Custome fields are not visible during campaign creation

### ISSUE THREAD

**Issue by apmcodes** [mautic/mautic#8623] opened 2020-04-03 23:47 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Custome fields are not visible (listed) during campaign creation under Condition (contacts field value)

| Q   | A
|mautic|Mautic 3.0.0. beta
| --- | ---
|PHP|PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS ) Copyright (c) 1997-2018 The PHP Group Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
|Browser|Chrome

### Steps to reproduce
1. Create custom fields
2. New campaign > Campaing Builder > Contact Source = Contact segments > Condtion= Contact Fields value > Custom fields are not shown
 
### Log errors
**mautic_prod-2020-04-03.php**
```
[2020-04-03 23:37:31] mautic.WARNING: PHP Warning - array_flip(): Can only flip STRING and INTEGER values! - in file /var/www/mautic-3.0.0-beta/app/bundles/LeadBundle/Form/Type/LeadFieldsType.php - at line 36 {"options":"[object] (Symfony\\Component\\OptionsResolver\\OptionsResolver: {})"} []

```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by apmcodes** [comment] 2020-04-06 21:32
No fields are loading now. Have tried to clear the cache in /var/cache folder. No duplicates field. 

![Screenshot from 2020-04-07 02-56-53](https://user-images.githubusercontent.com/13360356/78607096-0a29a280-787c-11ea-8a15-d5c2473e48c7.png)

**Comment by apmcodes** [comment] 2020-04-06 22:30
This is one sick php project. Getting repeatedly `currently offline` error during install step 2. 

Why would one build a large system like marketing automation in PHP.

**Comment by CyberMarsl** [comment] 2020-05-23 16:03
I got the same issue.

I know from a couple of people who need the option to fire an action in relation to custom field value datetime (i.e. 15 minutes before an event). It does not work in my mautic 3 beta installation.

It seems that date and datetime contact fields are not usable in "contact field value" when creating the condition. 

For us this is a very important function and we think it is very basic for a marketing automation tool like mautic.

(no error message in log)

**Comment by RCheesley** [comment] 2020-07-06 09:30
Hi folks,

Just tested this locally on Mautic 3.0 and was able to:
* Create a custom field (text based)
* Add the field to a contact (content: Mautic)
* Build a segment based on the content (where custom field = Mautic)
* Trigger the rebuild, contact was added as expected
* Build a campaign based on this segment to add points
* Trigger the campaign, contact had points added

![screenshot-local mautic3-2020 07 06-10_25_20](https://user-images.githubusercontent.com/2930593/86578328-8b73fc80-bf73-11ea-9bea-c7af2c8fa4ff.png)

 Guessing it was fixed in the stable release, can you confirm this is the case?

**Comment by RCheesley** [comment] 2020-07-06 09:54
I also tried using a conditional field which worked as well:

![screenshot-local mautic3-2020 07 06-10_32_45](https://user-images.githubusercontent.com/2930593/86580666-ece99a80-bf76-11ea-9033-6f9febd5e06c.png)

Going to close this issue as am unable to reproduce - please do re-open if there are still problems in Mautic 3.x or if I have misunderstood!

**Closed by RCheesley** 2020-07-06 09:54 UTC
Labels: pending-feedback
