### ISSUE TITLE
Merge contacts with Mautic API

### ISSUE THREAD

**Issue by rahulwalunje** [mautic/mautic#3138] opened 2016-12-26 12:45 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | /
| Feature request? | Y
| Enhancement? | / 

## Description:
It will be great, if one can merge anonymous and known contacts with Mautic API. just like happen after submitting Mautic form, so that tracking will be more efficient.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

Steps to test this PR:

1. Unknown contact.
2. We find email address
3. But contact already exists
4. Merge unknown contact to known.

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-12-27 14:44
This seems to be duplicate of https://github.com/mautic/mautic/issues/3108

**Closed by escopecz** 2016-12-27 14:44 UTC
