### ISSUE TITLE
Segment Search Only Uses First Word

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#3646] opened 2017-03-10 18:06 UTC
What type of report is this:

| Bug report | Y

## Description:

Segment search currently only searches the first word. 

If I have a segment that is titled: 
"Staff | BillyBob | Trade Show"
A search for "Staff" will return the segment.
A search for "BillyBob" or "Trade" will not return the segment. 

This also occurs for segments titled:
"team1 trade show booth 42" 
A search for "team1" will return the segment. 
A search for "trade", "show", or "booth"  will not return the segment. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7
| PHP version | 5.6.30

### Steps to reproduce:
1.  Create a new segment
2.  Title it with multiple words separated by spaces
3.  Search for the segment using any word other than the first.
 
### Log errors: 

None.

**Comment by escopecz** [comment] 2017-03-10 18:41
This seems like a duplicate of https://github.com/mautic/mautic/issues/2808

**Closed by escopecz** 2017-03-10 18:41 UTC

**Comment by Kyle-Foley** [comment] 2017-03-10 18:54
Clarified here:

https://github.com/mautic/mautic/pull/2874#issuecomment-285753039
