### ISSUE TITLE
Mautic giving error while form submission after upgrading

### ISSUE THREAD

**Issue by ZeeshiEli92** [mautic/mautic#6739] opened 2018-10-14 11:06 UTC
What type of report is this:

Mautic giving error while form submission
cached clear but still not working
www.mysite.com/?mauticError=Errors%3A<br%20%2F><ol><li>Array<%2Fli><%2Fol>#Form_Name

on all forms.

This error comes after upgrading

**Comment by escopecz** [comment] 2018-10-15 08:40
Duplicate of https://github.com/mautic/mautic/issues/6632

**Closed by escopecz** 2018-10-15 08:40 UTC
