### ISSUE TITLE
Creating email ommitting the language causes an error 500

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4617] opened 2017-08-08 14:01 UTC
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Go to Channel > Emails
Create a new email (either segment or template email)
remove / empty language field
try to save

Error 500

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by YannickBiet** [comment] 2017-08-08 14:03
Log :

[2017-08-08 14:00:43] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO emails (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, subject, from_address, from_name, reply_to_address, bcc_address, template, content, utm_tags, plain_text, custom_html, email_type, publish_up, publish_down, read_count, sent_count, revision, lang, variant_settings, variant_start_date, dynamic_content, variant_sent_count, variant_read_count, category_id, translation_parent_id, variant_parent_id, unsubscribeform_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-08-08 14:00:43", 1, "admin admin", null, null, null, null, null, null, "test", null, "", null, null, null, null, "goldstar", "a:0:{}", "a:4:{s:9:\"utmSource\";N;s:9:\"utmMedium\";N;s:7:\"utmName\";N;s:10:\"utmContent\";N;}", "Web Version [{webview_url}\u200d]\n\nUnsubscribe [{unsubscribe_url}]\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n_Thank you_\n\n\u00a0\n\nFOR YOUR ORDER!\n\n\u00a0\n\n\u00a0\n\nFeel free to review your invoice below or click the button to view you\naccount.\n\nMY ACCOUNT\n\n\u00a0\n\n\u00a0\n\nSHIPPING ADDRESS:\n\n\u00a0\n\n\u00a0\n\nJane Doe\n123 Street | Victoria, BC\nCanada\n1(250)222-2232\n\n\u00a0\n\n\u00a0\n\nORDER NUMBER: A80SD99\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nDATE SHIPPED:\n\n\u00a0\n\n\u00a0\n\nJanuary 12, 2016\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nItem\n\n\u00a0\n\n\u00a0\n\nQty\n\n\u00a0\n\n\u00a0\n\nTotal\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nDouble Lapel Blazer\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n1\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n$89.90\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nDraped Neck Cardigan\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n1\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n$22.80\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nSubtotal:\n\n\u00a0\n\n\u00a0\n\n$112.70\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nShipping:\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n$10.00\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\nTOTAL:\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n$122.70\n\n\u00a0\n\n\u00a0\n\n\u00a0\n\n{signature}", "\n\n\n    \n    \n    \n    \n    \n    \n

**Comment by escopecz** [comment] 2018-06-10 10:42
Duplicate of https://github.com/mautic/mautic/issues/3688

**Closed by escopecz** 2018-06-10 10:42 UTC
Labels: Bug
