### ISSUE TITLE
Engagement graph on contacts page shows incorrect # of points

### ISSUE THREAD

**Issue by thomeudt** [mautic/mautic#3270] opened 2017-01-19 14:52 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
On the contact page, the "engagements" graph is showing the count of point-related events, rather than the sum of points a contact has gained. Example: You had three engagements where you increase the points by 10 each time. In this case, the points chart should show 3x10=30. It does show 3 though, which to me is incorrect.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.13

### Steps to reproduce:
Run a campaign during which you modify the point score for a contact
 
### Log errors: 
n/a

**Comment by merlin0** [comment] 2017-01-23 15:06
Do you mean this? https://github.com/mautic/mautic/issues/1813 I think it worsk as intended but I am not sure.

**Comment by thomeudt** [comment] 2017-01-23 15:44
>Do you mean this? #1813 I think it worsk as intended but I am not sure.

That's what I mean, and I think the way it is implemented is misleading. If the current implementation is what was intended, i.e. show the number of point triggers rather than the total points gained, it should be tagged this way in the graph (i.e. "point events" instead of "points").

**Comment by escopecz** [comment] 2017-02-03 18:21
I can replicate. A contact added 3 points, but the chart shows only 1, which can be 1 point event.

**Comment by dongilbert** [comment] 2017-03-09 15:59
@alanhartless Should the "Points" label on the engagements graph be changed to "Point Events", or should the data in the graph be changed to show the cumulative modification of points over time? 

ie, They start with 0 points, and on the next day they had 3 engagements that each triggered a points event, with the first adding 4, the second subtracting 2, and the third adding 6, for a total change of +8, so the total for that day is placed at 8. Then the next day they have a single engagement that adds 5 points, so the graph goes to 13 for that day.

Maybe a more simple way to ask is if each day on the graph should show the contacts total points on that day, regardless the of number of point change actions?

**Comment by escopecz** [comment] 2017-07-03 09:19
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.

**Comment by merlin0** [comment] 2017-07-03 09:24
In the 1.x version it showed the total points that a lead gained that day. I personally think it's more logical to show the total amount since the point events can differ quite a lot in total scoring.

**Closed** 2017-11-28 11:38 UTC
Labels: Bug, P2, Pending Feedback
