### ISSUE TITLE
Upgrade to 1.0 - Hung on Process DB Updates

### ISSUE THREAD

**Issue by piuskid** [mautic/mautic#188] opened 2015-03-10 18:02 UTC
Update seems to have gone ok, however, during the update process, the last step of updating the database just showed the spinning icon.  I waited a few minutes then hit refresh in the browser which said I was successfully updated.  Is there a way to check  the db just to make sure?

**Comment by alanhartless** [comment] 2015-03-10 18:07
Hi!

Can you check your database and look at the migrations table, do you have an entry for 20150310000000?

Thanks!
Alan

**Comment by piuskid** [comment] 2015-03-10 18:29
yep.  that is the last row in the table.

**Comment by alanhartless** [comment] 2015-03-10 18:47
So that's the very last thing done so it must be some kind of miscommunication between the server and the JS script executing the ajax call.  

Do you have the time and are willing to setup a RC4 install then try upgrading to 1.0 stable again, this time watching the ajax requests through the browser's developer console to see if what is communicated during that last step?  If so, I can get you the RC4 package.

Thanks!
Alan

**Comment by piuskid** [comment] 2015-03-10 20:34
I have to admit that I don't know how to capture the Ajax requests using browser tools. I usually use firebug or chrome to grab styles and that sort of thing but I am not a developer.  If you tell me how, I would be happy to grab what you need.

**Comment by pbwebdev** [comment] 2015-03-10 22:53
Annoyingly I went to do an update so I could give you the ajax data but this time in worked perfectly on localhost. Didn't work on the production and staging server.

Will have to install an RC and do it again.

**Comment by dbhurley** [comment] 2015-03-10 23:55
Annoyingly it worked :wink: - love it.

**Comment by alanhartless** [comment] 2015-03-11 02:12
@piuskid Firebug actually makes it really easy to watch the ajax requests. During the upgrade, watch the console.  You'll see a bunch of POST or GET entries. If you click on the plus sign then on the response tab, you'll see what is being sent back from the server.  See what is sent back during the database step.  Or at the time the it fails.  Does it just stop posting to the server at some point, does it hit a 500 error, does it hit a JS error, or does it keep posting over and over and not going anywhere. 

@pbwebdev That's been part of the frustration as there have been a few reports of this but it's been tricky to track down the cause as its been very inconsistent. 

Thanks guys!

**Comment by kigorwe** [comment] 2015-03-11 10:07
Hello,

I have installed Mautic on a server. Tried updating to the latest version and the process keeps spinning without ever completing. I checked console and found some sort of an error
-----------
SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data
------------
Has anyone come across this problem? How can i resolve it?

Thanks guys!

**Comment by piuskid** [comment] 2015-03-11 15:57
I performed the update from 1.0 to 1.0.1 and had the same issue on the last step.  i haven't had a chance to install the old release and try again but wanted to report that it happened again.

**Comment by alanhartless** [comment] 2015-03-11 16:30
What hosting company do you guys use?

Thanks,
Alan

**Comment by piuskid** [comment] 2015-03-11 16:38
I am using bluehost

**Comment by alanhartless** [comment] 2015-04-09 21:57
Did you guys have the same issue with upgrading from 1.0.1 to 1.0.2?

We think this might be related to some shared hosts and the number of cache files that can be generated.  We're hoping to remedy that once we merge https://github.com/mautic/mautic/pull/229 into the release cycle.

Thanks!
Alan

**Comment by pbwebdev** [comment] 2015-04-09 21:58
Yes same issues

On Friday, April 10, 2015, Alan Hartless <notifications@github.com> wrote:

> Did you guys have the same issue with upgrading from 1.0.1 to 1.0.2?
>
> We think this might be related to some shared hosts and the number of
> cache files that can be generated. We're hoping to remedy that once we
> merge #229 <https://github.com/mautic/mautic/pull/229> into the release
> cycle.
>
> Thanks!
> Alan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/188#issuecomment-91366830>.
>


-- 

Regards,

*Peter Bui*
*Director and Web Analyst*




*Sydney*
P: (02) 9282 8767
M: 0413 49 49 47

Level 24, 66 Goulburn St
Sydney, NSW 2011

**Comment by piuskid** [comment] 2015-04-09 22:05
Me too

**Comment by alanhartless** [comment] 2015-04-09 22:28
Ok; thanks guys. I had a feeling it would. 

Will keep this open of course and touch back once we get that PR merged and released to see if the issue remains.  Well, probably the release after the one that includes the change since the cache will still be large with that first upgrade.

**Comment by natselection** [comment] 2015-04-10 02:46
I have the same problem. Not on a shared host though. DigitalOcean with Centos6.6 / PHP 5.4.38. Most limit settings are pretty high but it could very well be a configuration issue. 

http://xxxxx.xxx/s/ajax?action=core:updateDatabaseMigration&_=1428633374899&mauticUserLastActive=13&mauticLastNotificationId=290 500 Internal Server Error
		4.01s

Here are screenshots of the console different tabs
Params: http://note.io/1Juq9MQ
Headers: http://note.io/1Juqe38
Response: http://note.io/1Fpoc5G
JSON: http://note.io/1Fpofi7
Cookies: http://note.io/1FpomtM

**Comment by alanhartless** [comment] 2015-04-10 03:13
Thanks Matthew! That helps give some info into the issue. The response is what's odd.  It's like it's not making it to the correct controller function on that call as the response doesn't match what the call to the updateDatabaseMigration should be returning. But, the fact that it's returning a json encoded success var means that it is executing all the way through one of our ajax functions and not hitting an uncaught exception.  But the fact that its returning a 500 response to the browse with the json encode response is definitely odd behavior.

Is that consistently reproducible on your server? If so, would you be willing to let me have access to a "playarea" that I can take a crack at getting this solved or at least figure out what's causing it? It's obviously a problem but none of us developers have servers that are replicating this issue.  If so, hit me up on slack (https://mautic.org/slack) or email me at alan.hartless@mautic.org.

Thanks!
Alan

**Comment by natselection** [comment] 2015-04-15 16:15
Sorry for the delay Alan. It's consistent between 2 VPS's that we have the same environment configured. I'll try and get a spot set up today for you and will email the details.

**Comment by alanhartless** [comment] 2015-04-15 19:01
That would be awesome! Thanks!

**Closed** 2015-05-03 19:32 UTC
Labels: Bug
