### ISSUE TITLE
From Name shows garbled code when using Amazon SES - API

### ISSUE THREAD

**Issue by anki630** [mautic/mautic#9614] opened 2021-01-23 17:07 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v3.2.4
| PHP version | 7.3.25
| Browser | Chrome 88.0.4324.96

### Steps to reproduce
1. In Email Setting --> Service to send mail through --> Amazon SES - API
2. Set 'Name to send mail as' to the non-ASCII character like Japanese
3. Send a test email or launch a campaign
4. Recipient will receive an email with 'From Name' show garbled code like "���w�~̵"
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2021-01-25 20:19
I believe that this is a duplicate of #9433 which has a fix proposed (#9434) so closing this issue.

**Closed as completed by RCheesley** 2021-01-25 20:19 UTC
Labels: needs-triage
