### ISSUE TITLE
Time show on Upcoming Events and Submit form always UTC

### ISSUE THREAD

**Issue by dichvuhuuich** [mautic/mautic#8666] opened 2020-04-09 23:45 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  2.16.2 beta
| PHP version |  PHP Version 7.2.28-3+ubuntu18.04.1+deb.sury.org+1
| Browser |  Version 80.0.3987.163 (Official Build) (64-bit)

### Steps to reproduce
I. Upcoming Events
1. Go to configuration, set default timezone not UTC, example Ho Chi Minh (UTC+7)
2. Create a test contact
3. Create a test segment
4. Add test contact to test segment
5. Create a test campaign with source test segment
6. Add a action example +1 point immediately and an action with at a relative time 15' or at specific date/time
7. Go to contact and see campaign trigger and see History, trigger +1 point immediately time UTC+7 but on Upcoming Events, time always UTC.

II. Date on form
1. Create a test form Name and email
2. Embed form on a landing page
3. Submit form
4. Go to form results and see that Date Submitted always UTC 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dennisameling** [comment] 2020-04-10 08:15
Thanks for reporting this issue! We are currently investigating to see if we can reproduce this problem on 2.16.2-beta.

**Comment by dennisameling** [comment] 2020-04-10 12:45
@dichvuhuuich 
I've tried to reproduce the steps you mentioned under "Upcoming events" with timezone Ho Chi Minh (UTC+7), but all times seem to be in the correct timezone:

![Screenshot from 2020-04-10 14-28-58](https://user-images.githubusercontent.com/17739158/78990799-ac28e380-7b37-11ea-934d-b465ed628c0e.png)

Also after the scheduled email is sent, the timezone is still correct:

![Screenshot from 2020-04-10 14-31-37](https://user-images.githubusercontent.com/17739158/78990947-05911280-7b38-11ea-84d9-2d84de62a4e7.png)

**2. Date on form**
Trying to submit the form, I'm indeed seeing that the time is shown in UTC (it's explicitly mentioned that the time is shown in UTC though).

![Screenshot from 2020-04-10 14-35-59](https://user-images.githubusercontent.com/17739158/78991182-a5e73700-7b38-11ea-93cb-81eb0386ca30.png)

I tested both on 2.16.1 and 2.16.2-beta, so I'm not marking this as a regression (since it wasn't introduced specifically in 2.16.2-beta) but as a bug instead.

**Comment by mohit-rocks** [comment] 2020-04-10 16:37
I am working on the issue.

**Comment by dichvuhuuich** [comment] 2020-04-10 23:35
> @dichvuhuuich
> I've tried to reproduce the steps you mentioned under "Upcoming events" with timezone Ho Chi Minh (UTC+7), but all times seem to be in the correct timezone:
> 
> ![Screenshot from 2020-04-10 14-28-58](https://user-images.githubusercontent.com/17739158/78990799-ac28e380-7b37-11ea-934d-b465ed628c0e.png)
> 
> Also after the scheduled email is sent, the timezone is still correct:
> 
> ![Screenshot from 2020-04-10 14-31-37](https://user-images.githubusercontent.com/17739158/78990947-05911280-7b38-11ea-84d9-2d84de62a4e7.png)
> 
> **2. Date on form**
> Trying to submit the form, I'm indeed seeing that the time is shown in UTC (it's explicitly mentioned that the time is shown in UTC though).
> 
> ![Screenshot from 2020-04-10 14-35-59](https://user-images.githubusercontent.com/17739158/78991182-a5e73700-7b38-11ea-93cb-81eb0386ca30.png)
> 
> I tested both on 2.16.1 and 2.16.2-beta, so I'm not marking this as a regression (since it wasn't introduced specifically in 2.16.2-beta) but as a bug instead.

You can see on picture 1 that Upcoming Events on Right, time is UTC, in history, time is ok.

![image](https://user-images.githubusercontent.com/4901985/79029417-898ddd80-7bbe-11ea-9eec-dc0531679707.png)

**Comment by cyanstar** [comment] 2020-04-14 10:33
If the updating to 2.16.2 doesn't resolve it, [7752](https://github.com/mautic/mautic/pull/7752) might. I know there was a tweak in 2.16.2 around a similar issue. @rcheesley @anton-vlasenko, thoughts?

**Comment by npracht** [comment] 2020-04-15 13:33
Hi @dichvuhuuich please test #8675 !

**Comment by dennisameling** [comment] 2020-06-27 10:53
I'm currently testing #7752 and it resolves the issues mentioned here (as well as some other date/time related bugs):

Upcoming events fixed:

![image](https://user-images.githubusercontent.com/17739158/85920476-62b57e00-b874-11ea-8f18-59eb2301af38.png)

Date on form fixed:

![image](https://user-images.githubusercontent.com/17739158/85920544-d6578b00-b874-11ea-8042-e77f58f9fa14.png)

I'll go ahead and mark #7752 as the PR that will close this issue. Sorry @mohit-rocks and thanks for your work on #8675, but #7752 fixes even more date/time related issues and has tests included 😊

**Closed as completed** 2020-06-27 13:39 UTC
Labels: bug, ready-to-test
