### ISSUE TITLE
How can I see who clicked on the link?

### ISSUE THREAD

**Issue by w4admin** [mautic/mautic#1579] opened 2016-04-07 12:32 UTC
Hi

We sent the first newsletter with the mautic tool.
I now wanted to see which lead clicked on which link in the email. however, i only can see whether they opened the email or not. is it not possible to see for every lead the link clicking statistics?

what do I have to do to get this information?
thank you!

**Comment by FarhadF** [comment] 2016-04-11 07:22
Hi,
Go to Emails, Click on desired email, On bottom of the diagram you can see each tracked link with its unique clicks and stuff.

regards
Farhad

**Comment by Hailong** [comment] 2016-04-12 02:05
I'm wondering if you can achieve this by defining an Asset. In the new asset page, you can input a Remote URL. Just my thought, never tried it out.

**Comment by escopecz** [comment] 2016-04-24 15:17
This is duplicate of https://github.com/mautic/mautic/issues/573

**Closed by escopecz** 2016-04-24 15:17 UTC
Labels: Feature Request
