### ISSUE TITLE
Can't create new Stand Alone Forms since 4.1.0 upgrade

### ISSUE THREAD

**Issue by charles-talk2us** [mautic/mautic#10666] opened 2021-12-06 15:02 UTC
### Mautic Version

4.0.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

I tried to create a new stand alone form, since the upgrade to version 4.1.0 was completed. I get an the same error on all 4 instances we have. 

The error message is "There was an error creating the submission results table. Try a different name."

No amount of trying seems to help.

### How can we reproduce this issue?

Steps:  

1. Open Mautic
2. Components>Forms> +New
3. Name the Form
4. Save
5. Note Error - "There was an error creating the submission results table. Try a different name." 

### Relevant log output

```shell
None seen
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by raramuridesign** [comment] 2021-12-06 18:42
@RCheesley  I consider this an important bug to look at, reported since the last upgrade
version 4.0.0 

There are NO Error LOGS to report.

I can confirm this is a problem on multiple instances, different servers, with the same PHP and Apache setup as above.

Brower: Chrome

After Saving a NEW FORM the following screenshot information shows.

![image](https://user-images.githubusercontent.com/902376/144903377-92c6abd8-83ce-4577-842f-837e82b0c1ac.png)

**Comment by ciflycom** [comment] 2021-12-08 16:58
I just tested this on PHP 7.4 and Mautic 4.1.0 and do not see this problem.
Are you running anything special in your installation, maybe some plugin?

**Comment by jolaun** [comment] 2021-12-08 17:24
I have the same issue. I have no special configuration or installation. My mautic is running on a plesk environment.

**Comment by nikolaknezeviccom** [comment] 2021-12-08 17:37
I am running 4.1.0 Mautic with Maria DB 10.6  PHP 7.4 and Plesk with Litespeed
I do not get that error (empty installation with 500k contacts in it imported).
Created few types of forms once I saw this but not a problem for me.

**Comment by MaraKasubke** [comment] 2021-12-09 09:55
No problem on Mautic 4.1 PHP 7.4.26, Firefox

**Comment by charles-talk2us** [comment] 2021-12-09 10:17
> No problem on Mautic 4.1 PHP 7.4.26, Firefox

I tried Firefox, the issue remains... :(

**Comment by charles-talk2us** [comment] 2021-12-09 10:22
I thought of trying to clone a Form and renaming it.

**Please Note:** I can't clone an existing form either can you @raramuridesign or @nikolaknezeviccom ?

**Comment by nikolaknezeviccom** [comment] 2021-12-09 10:26
On my Mautic ( 4.1.0 Mautic with Maria DB 10.6 PHP 7.4 )
Creating standalone as well as campaign forms works for me.
Cloning from campaign to standalone works.
Cloning from standalone to standalone works.
Cloning from standalone to campaign works.

**Comment by nikolaknezeviccom** [comment] 2021-12-09 11:06
@charles-talk2us  Can you try on the same server plain install of Mautic 4.1 maybe there is an issue while upgrade only?

**Comment by charles-talk2us** [comment] 2021-12-09 11:14
@raramuridesign would you be able to do a plain fresh install on one of our instances so we can check this please? Thanks for the suggestion @nikolaknezeviccom 

Maybe a standalone rather @raramuridesign, not sure how we'll preserve the data?

**Comment by charles-talk2us** [comment] 2021-12-14 06:52
Hello @raramuridesign do you have any feedback on this issue and the possible fresh installation using version 4.1? 

@RCheesley do you think this bug will be fixed by the 20 December release? We have five separate production instances for various customers that are being affected by this bug, so a quick resolution is essential for us. All Form creation and cloning is impossible on these instances at present.

**Comment by renatocron** [comment] 2021-12-14 17:56
@charles-talk2us did you selected "Render style from Template? " to "No" on those forms?
I think this is related to this: https://github.com/mautic/mautic/issues/10453

You can "fix" this by running `update forms set render_style=true where id=XXX`, then do your changes, and update it back to false when saving the form.

There's one patch - remove line 155 from app/bundles/FormBundle/Form/Type/FormType.php

 https://github.com/rpayanm/mautic/commit/6eba3d1c4f8a19301d32a12ffa9ba86d65437ded

Still not merged, waiting for side-effects analyses on the mautic team.

**Comment by raramuridesign** [comment] 2021-12-14 18:01
@charles-talk2us @RCheesley 

Some Feedback.

1. New installation does not have this issue. 
2. After some digging I found that the old systems which had been upgraded needed the following command updated at command line level

`php bin/console doctrine:migrations:migrate`

3. Error occured in this process where the leads table would not add a new column. 

-----------------------------------------------------
public_html]# php bin/console doctrine:migrations:migrate

++ adding generated column generated_email_domain
-> ALTER TABLE mgo21_leads ADD generated_email_domain VARCHAR(255) AS (SUBSTRING(email, LOCATE("@", email) + 1)) COMMENT '(DC2Type:generated)';
            ALTER TABLE mgo21_leads ADD INDEX `mgo21_generated_email_domain`(generated_email_domain)

In AbstractMySQLDriver.php line 98:
                                                                                                          
  An exception occurred while executing 'ALTER TABLE mgo21_leads ADD generated_email_domain VARCHAR(255)  
   AS (SUBSTRING(email, LOCATE("@", email) + 1)) COMMENT '(DC2Type:generated)';                           
              ALTER TABLE mgo21_leads ADD INDEX `mgo21_generated_email_domain`(generated_email_domain)':  
                                                                                                          
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version  
   for the right syntax to use near 'ALTER TABLE mgo21_leads ADD INDEX `mgo21_generated_email_domain`(ge  
  nerated_em...' at line 2                                                                                
                                                                                                          

In ConnectionError.php line 19:
                                                                                                          
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version  
   for the right syntax to use near 'ALTER TABLE mgo21_leads ADD INDEX `mgo21_generated_email_domain`(ge  
  nerated_em...' at line 2          

-----------------------------------------------------

4. Next Step add this manually
5. re-ran STEP 2, and the migration finished.
6. Then ran this script https://domain.com/s/update/schema which completed without errors.
7. After this process I was able to create / clone forms

I suspect Step 3 error where the field could not be added to the table is the issue.

Perhaps someone could comment on the above
Thanks.

**Comment by renatocron** [comment] 2021-12-14 18:16
Oh, aside from the error reported on my last commend on this thread,
I did found this issue when upgraded from 4.0.0 to 4.1.0 via the web, web did not finished successfully the migration.

I'm using the docker image with percona/percona-server:5.7 and did not have issues with upgrade from command line.

**Comment by raramuridesign** [comment] 2021-12-14 18:17
@renatocron
We have a script where we run the upgrades, We might need to include the schema update for future upgrades.

**Comment by curtisgray** [comment] 2021-12-18 08:53
This issue has been resolved and should be closed.

**Comment by npracht** [comment] 2021-12-23 09:02
I close it, this is an installation/configuration issue.

**Closed as completed** 2021-12-23 09:01 UTC
Labels: bug, needs-triage

**Comment by ramphy** [comment] 2022-03-16 15:39
@raramuridesign


Thank you so much!

**Comment by shanbhardwaj** [comment] 2022-04-07 08:35
I'm getting a similar error in upgrading from 4.1.1 to 4.2.1
``` 
An exception occurred while executing 'ALTER TABLE leads ADD generated_email_domain TEXT AS (SUBSTRING(email, LOCATE("@", email) + 1)) COMMENT '(DC2Type:generated)';
              ALTER TABLE leads ADD INDEX `generated_email_domain`(generated_email_domain)':
  SQLSTATE[42S22]: Column not found: 1054 Unknown column '@' in 'generated column function'
