### ISSUE TITLE
Error 500 when pressing save button of the Contact Preference Center

### ISSUE THREAD

**Issue by Malbrouck** [mautic/mautic#9158] opened 2020-09-01 05:49 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

If I edit a contact's preferences by clicking the Email channel, it's not possible to edit the Frequency parameters as they are greyed out
![Capture d’écran 2020-08-31 à 19 46 03](https://user-images.githubusercontent.com/1681762/91799486-717b3100-ec27-11ea-87dd-ef22d320b5ff.png)

Then when I press save:
![Capture d’écran 2020-08-31 à 19 46 54](https://user-images.githubusercontent.com/1681762/91799506-7c35c600-ec27-11ea-8f59-517536b86fd4.png)

Corresponding to this log line:

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "removeDncForLead" of class "Mautic\LeadBundle\Model\LeadModel"." at /var/www/mmm.mysite.com/app/bundles/LeadBundle/Controller/FrequencyRuleTrait.php line 180 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"removeDncForLead\" of class \"Mautic\\LeadBundle\\Model\\LeadModel\". at /var/www/mmm.mysite.com/app/bundles/LeadBundle/Controller/FrequencyRuleTrait.php:180)"} []

Why would I have an undefined method named "removeDncForLead" ?

I looked at that line 180 in FrequencyRuleTrait.php:
$leadModel->removeDncForLead($lead, $contactChannel);

Then I looked into app/bundles/LeadBundle/Model/LeadModel.php but didn’t find any definition of removeDncForLead. I stopped there…

My Mautic version is: 3.1.0
My PHP version is: 7.3.20
My MariaDB version is : 10.5

### Steps to reproduce
1. Edit a contact's preferences
2. Tick the Email channel box
3. Save
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "removeDncForLead" of class "Mautic\LeadBundle\Model\LeadModel"." at /var/www/mmm.mysite.com/app/bundles/LeadBundle/Controller/FrequencyRuleTrait.php line 180 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"removeDncForLead\" of class \"Mautic\\LeadBundle\\Model\\LeadModel\". at /var/www/mmm.mysite.com/app/bundles/LeadBundle/Controller/FrequencyRuleTrait.php:180)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Malbrouck** [comment] 2020-09-01 06:33
This bug could be the same as #9017

**Comment by flynet70** [comment] 2020-09-04 05:18
same problem

**Comment by StoppingBuck** [comment] 2020-09-05 12:36
As mentioned, this is a duplicate of #9017 - PR #9081 should hopefully fix it, but currently seems to have some issues with code coverage so needs more tests.

**Comment by Malbrouck** [comment] 2020-09-05 13:26
I manually patched my AjaxController.php as proposed in #9081 but it didn't solve the problem

Still producing error 500 on web gui + same CRITICAL message in log

**Comment by StoppingBuck** [comment] 2020-09-05 16:51
@Malbrouck Ah! That seems more like what @RCheesley mentioned here: https://github.com/mautic/mautic/issues/9017#issuecomment-666306933

**Comment by npracht** [comment] 2020-09-07 12:20
Closed in favor of https://github.com/mautic/mautic/issues/9017

**Closed as completed by npracht** 2020-09-07 12:20 UTC
Labels: duplicate
