### ISSUE TITLE
Enhancement - Mautic should only have 1 form type

### ISSUE THREAD

**Issue by nadvolod** [mautic/mautic#4233] opened 2017-06-12 23:27 UTC
What type of report is this:
 Enhancement

## Description:
I am requesting that the 2 different types of forms(Campaign and Standalone) be condensed into 1 form. It is extremely confusing to me about why they are separate. A form is a form at the end of the day and is just a method of gathering data from the Contact. The form features are still exactly the same regardless of where that data is pushed after it is gathered.  The variation is the action that occurs after you fill out the form. Do you link it to a campaign? Do you segment a contact? Maybe something else? 

I believe that this will reduce confusion as it will follow the standards of other tools for marketing automation. Furthermore, it will probably reduce code complexity as you just need to maintain a single form that has multiple actions available for it.

**Comment by npracht** [comment] 2017-06-13 06:15
Duplicate of https://github.com/mautic/mautic/issues/2979

**Closed** 2017-06-13 07:16 UTC
Labels: Duplicate
