### ISSUE TITLE
Mysql leads table, too many keys specified max 64 keys allowed 

### ISSUE THREAD

**Issue by FerRubioMorales** [mautic/mautic#4465] opened 2017-07-19 07:54 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | 
| Enhancement? | 

## Description:
This bug does not let you perform write actions over leads table. When custom field property it's created the system also creates and index in this table. For solve you have to recompile MySQL:

./configure --prefix=/usr/local/mysql --with-charset=cp1251 --enable-thread-safe-client --with-max-indexes=256

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.1

### Steps to reproduce:
1. Create new custom field properties (each custom field property ads an index to the lead table, when max keys are 64 and this is not being controlled)
2. Try tu run doctrine:schema:update
3. You will have an error that says: "too many keys specified max 64 keys allowed". This produce a partial migration and lead tables does not contains all the columns.
 
### Log errors: 

 [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE INDEX instagram_search ON leads (instagram)':
  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed

**Comment by escopecz** [comment] 2017-07-19 08:39
Thanks for the report! I'll close it in favour of https://github.com/mautic/mautic/issues/4372

**Closed by escopecz** 2017-07-19 08:39 UTC

**Comment by pjeby** [comment] 2017-07-19 19:01
How is this related to #4372?  That issue doesn't say anything about indexes, only column size.  Is it to add an option for whether the field should be indexed or not?

**Comment by escopecz** [comment] 2017-07-20 07:57
Yes, that is the idea. Give user option to configure the column size and whether the column should have index. Please comment there with the index limit. I still think these 2 options could be done in one PR.

**Comment by moskoweb** [comment] 2018-04-06 23:49
How to solve this problem?

It's stopping my campaigns from rolling.

**Comment by FerRubioMorales** [comment] 2018-04-07 12:57
I did not found solution for this. May be you could solve it recompiling
mysql using some options bypassing the 64keys limit, but i cant test it
because i cant recompile.

**Comment by escopecz** [comment] 2018-04-09 06:51
A quick fix could be to remove indexes from some custom fields that you think Mautic does not use to search or join by. For example those that aren't used in segment filters. You'd have to do that in your database directly. Use PhpMyAdmin or Adminer for easier database manipulation. Let us know if this worked for you please.

**Comment by FerRubioMorales** [comment] 2018-04-09 07:50
Thanks John! I will try it. I think it’s a temporal fix because on next
mautic Update this will throw errors due to migrations (i think migrations
will add the indexes again.)

**Comment by moskoweb** [comment] 2018-04-10 00:32
So you have no solution for that yet? Why the problem is giving in a custom field I created in 2.12.11.

**Comment by FerRubioMorales** [comment] 2018-04-10 11:10
I confirm that the answer by @John Linhart it's right, but it's more a
patch than a solution, but at least you can update your instance without
problems.

**Comment by moskoweb** [comment] 2018-04-10 19:43
The ideal would be to have a solution, the alternative may work temporarily, but with the growth of the tool, how does it work?

**Comment by YosuCadilla** [comment] 2018-05-11 11:43
Might this be helpful?
https://www.safaribooksonline.com/blog/2012/11/06/avoiding-too-many-keys-in-mysql/

**Comment by starshunter88** [comment] 2020-06-26 17:28
+1 I am also encountering this issue
