### ISSUE TITLE
Amazon SES: Handling of an unverified email address does not work

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#2426] opened 2016-08-31 08:30 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | yes |
## Description:

Amazon SES requires, that you verify all emails address you want to send emails from. If you try to use an unverified from email address, Amazon rejects your email. It can happen that a user tries to send emails from an unverified address, because it is possible to overwrite that value from the email editor.

> 554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: nope@nope.com

This error must be considered as a failed email. Currently if you use queue mode, Mautic treats it like a bounced message and flags the user as bounced. This is wrong, it should just be a failed email.

Output from sending the mail from the filesystem spool.

```
root@box:/vagrant# php app/console mautic:emails:send


  [Swift_TransportException]
  Expected response code 250 but got code "554", with message "554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1:
   Nope <nope@nope.com>, nope@nope.com
  "


mautic:emails:send [--message-limit [MESSAGE-LIMIT]] [--time-limit [TIME-LIMIT]] [--do-not-clear] [--recover-timeout [RECOVER-TIMEOUT]] [--clear-timeout [CLEAR-TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

root@box:/vagrant# ll app/spool/default/
total 28
drwxr-xr-x 3 501 dialout   102 Aug 31 08:16 ./
drwxr-xr-x 3 501 dialout   102 Jul 22 13:47 ../
-rw-rw-r-- 1 501 dialout 18532 Aug 31 08:16 3wQB8Tq3kV.message.sending
root@box:/vagrant# ll app/spool/default/
total 28
drwxr-xr-x 3 501 dialout   102 Aug 31 08:16 ./
drwxr-xr-x 3 501 dialout   102 Jul 22 13:47 ../
-rw-rw-r-- 1 501 dialout 18532 Aug 31 08:16 3wQB8Tq3kV.message.sending
root@box:/vagrant# php app/console mautic:emails:send
root@box:/vagrant# ll app/spool/default/
total 8
drwxr-xr-x 2 501 dialout  68 Aug 31 08:17 ./
drwxr-xr-x 3 501 dialout 102 Jul 22 13:47 ../
```

Emails shows up as bounced instead of failed.

![screen shot 2016-08-31 at 10 27 48](https://cloud.githubusercontent.com/assets/1575445/18121585/9c372284-6f65-11e6-8aec-4f28eba35021.png)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 7.0.5-2+deb.sury.org~trusty+1 |
### Steps to reproduce:
1. Select Amazon as email transport and set it to queue
2. Create a email and set an unverified email as from
3. Send the mail
4. Run cronjob manually twice
5. Check sending statistics of your email. It shown as bounced and the user is flagged as bounced.

**Comment by amagdy3** [comment] 2016-09-25 17:11
I confirm this happened with me resulting on marking contacted as bounced when using an unverified mailbox. I verified the domain I use with Amazon SES so I can use any mailbox for sending and avoid this error.

**Comment by martinstr** [comment] 2016-11-02 12:18
Same here had one in my team that entered a wrong email address and 600 contacts got marked as bounce in mautic, not good at all.

**Comment by gopi-ar** [comment] 2017-09-02 14:05
+1 thankfully we caught this in the test campaign to internal contacts.

**Comment by npracht** [comment] 2019-04-25 09:39
Hi @wittwerch @martinstr @devabdo @gopi-ar is that still an issue ?

**Comment by virgilwashere** [comment] 2019-06-12 21:20
@npracht AWS SES definitely fails the outbound message for unverified addresses.

`==> mautic_prod-2019-06-12.php <==`
```php
[2019-06-13 06:24:14] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "554", with message "554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: torpedo@rockets.com, Tainted Torpedo <torpedo@rockets.com>
"
```

But if I set an invalid From address on a Segment email, it Bounces the contact as per above.

`mautic.lead.event.donotcontact_bounced`

**Comment by npracht** [comment] 2019-10-04 13:38
duplicate of https://github.com/mautic/mautic/issues/3655

**Closed by npracht** 2019-10-04 13:38 UTC
Labels: Backlog, Bug
