### ISSUE TITLE
Mautic 3.0 Interface doesn't change language

### ISSUE THREAD

**Issue by Videonas** [mautic/mautic#9009] opened 2020-07-13 16:02 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Ever since I updates to Mautic 3.0, the software won't change language. I've changed the language in the System settings and it seems to download the language files (they appear in the translation folder on the server), but the interface doesn't change. I've already tried logging out and clearing cache as I've read in a forum thread about an older version. In the previous version I've had installed (2.16 I think. The version before 3.0 because I try to keep my software as up to date as possible), the interface did change language.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.18
| Browser | Brave, Firefox, Vivaldi, Chrome

### Steps to reproduce
1. Go to Configuration > System Settings
2. In System Defaults, change Default Language to Dutch (or something else, Ive also tried French and German)

The English interface isn't a problem for me personaly but I guess that the items that my contacts get to see (preference settings etc.) don't get translated either. This makes the user experience less pleasant and professional. 

Can someone help me with this? Many thanks in advance

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by lhpz** [comment] 2020-07-14 16:20
Hello,

I can confirm that changing the language from English to French, works on my Mautic 3.0.1 installation, with the following downsides:
- for the language change to be visible in the back-office, I have to disconnect first then re-login.
- not all UI strings are translated to French at this stage.

There is no need to clear the cache for me. 

I understand that your 3.0.1 installation was obtained by upgrading from a previous version, and is not a fresh 3.0.1 installation, so you might be in a different situation because of this. Sorry for not being more helpful.

**Comment by hoylen** [comment] 2020-07-15 02:08
Switching to Dutch on my _fresh installation_ of 3.0.1 works immediately after logging out (but I get a "mautic.core.update.archive_no_such_file" error with 3.0.0). So this supports the theory that the issue has something to do with an upgraded Mautic.

**Comment by RCheesley** [comment] 2020-07-16 13:34
Closing the issue as this does not seem to be a bug with Mautic - please post up at https://forum.mautic.org if you need further support! Thanks @lhpz and @hoylen for the info!

**Closed as completed by RCheesley** 2020-07-16 13:34 UTC
Labels: needs-triage

**Comment by benfavre** [comment] 2020-09-07 23:02
It is a bug with upgraded mautic and no helpful comment has been posted to help resolution, why is this closed ?

**Comment by joaopintof** [comment] 2020-09-24 19:13
the same issue for me.
i've change the language to Portuguese, and i got the message mautic.core.update.archive_no_such_file!

any workaround? tks!

**Comment by joaopintof** [comment] 2020-09-24 19:56
I found a solution here
i downloaded the translation zip file from url https://language-packs.mautic.com/pt_BR.zip and i sent unziped files to **'/htdocs/translations'**  

Everything works like a charm!! :-)

Hope this helps!!!!
