### ISSUE TITLE
Saving an email without a language crashes the app

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#5047] opened 2017-09-28 09:52 UTC
| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

### Screencast 🌟 

![adal1h3vg1](https://user-images.githubusercontent.com/18265735/30960241-bd5dcfb8-a442-11e7-822d-148c35259c54.gif)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a new email
2. Remove its language
3. Save & Close
 
### Log errors: 

```
[2017-09-28 09:46:24] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO emails (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, subject, from_address, from_name, reply_to_address, bcc_address, template, content, utm_tags, plain_text, custom_html, email_type, publish_up, publish_down, read_count, sent_count, revision, lang, variant_settings, variant_start_date, dynamic_content, variant_sent_count, variant_read_count, category_id, translation_parent_id, variant_parent_id, unsubscribeform_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-09-28 09:46:24", 1, "Maximilien Mellen", null, null, null, null, null, null, "No Language", null, "", null, null, null, null, "blank", "a:0:{}", "a:4:{s:9:\"utmSource\";N;s:9:\"utmMedium\";N;s:11:\"utmCampaign\";N;s:10:\"utmContent\";N;}", null, "<!DOCTYPE html>\n<html>\n    <head>\n        <title>{subject}<\/title>\n        <style type=\"text\/css\" media=\"only screen and (max-width: 480px)\">\n            \/* Mobile styles *\/\n            @media only screen and (max-width: 480px) {\n\n                [class=\"w320\"] {\n                    width: 320px !important;\n                }\n\n                [class=\"mobile-block\"] {\n                    width: 100% !important;\n                    display: block !important;\n                }\n            }\n        <\/style>\n    <\/head>\n    <body style=\"margin:0\">\n        <div data-section-wrapper=\"1\">\n            <center>\n                <table data-section=\"1\" style=\"width: 600;\" width=\"600\" cellpadding=\"0\" cellspacing=\"0\">\n                    <tbody>\n                        <tr>\n                            <td>\n                                <div data-slot-container=\"1\" style=\"min-height: 30px\">\n                                    <div data-slot=\"text\">\n                                        <br \/>\n                                        <h2>Hello there!<\/h2>\n                                        <br \/>\n                                        We haven't heard from you for a while...\n                                        <br \/>\n                                        <br \/>\n                                        {unsubscribe_text} | {webview_text}\n                                        <br \/>\n                                    <\/div>\n                                <\/div>\n                            <\/td>\n                        <\/tr>\n                    <\/tbody>\n                <\/table>\n            <\/center>\n        <\/div>\n    <\/body>\n<\/html>", "template", null, null, 0, 0, 1, null, "a:0:{}", null, "a:1:{i:0;a:3:{s:9:\"tokenName\";s:17:\"Dynamic Content 1\";s:7:\"content\";s:23:\"Default Dynamic Content\";s:7:\"filters\";a:1:{i:0;a:2:{s:7:\"content\";N;s:7:\"filters\";a:0:{}}}}}", 0, 0, null, null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'lang' cannot be null" at path/to/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO emails (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, subject, from_address, from_name, reply_to_address, bcc_address, template, content, utm_tags, plain_text, custom_html, email_type, publish_up, publish_down, read_count, sent_count, revision, lang, variant_settings, variant_start_date, dynamic_content, variant_sent_count, variant_read_count, category_id, translation_parent_id, variant_parent_id, unsubscribeform_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2017-09-28 09:46:24\", 1, \"Maximilien Mellen\", null, null, null, null, null, null, \"No Language\", null, \"\", null, null, null, null, \"blank\", \"a:0:{}\", \"a:4:{s:9:\\\"utmSource\\\";N;s:9:\\\"utmMedium\\\";N;s:11:\\\"utmCampaign\\\";N;s:10:\\\"utmContent\\\";N;}\", null, \"<!DOCTYPE html>\\n<html>\\n    <head>\\n        <title>{subject}<\\/title>\\n        <style type=\\\"text\\/css\\\" media=\\\"only screen and (max-width: 480px)\\\">\\n            \\/* Mobile styles *\\/\\n            @media only screen and (max-width: 480px) {\\n\\n                [class=\\\"w320\\\"] {\\n                    width: 320px !important;\\n                }\\n\\n                [class=\\\"mobile-block\\\"] {\\n                    width: 100% !important;\\n                    display: block !important;\\n                }\\n            }\\n        <\\/style>\\n    <\\/head>\\n    <body style=\\\"margin:0\\\">\\n        <div data-section-wrapper=\\\"1\\\">\\n            <center>\\n                <table data-section=\\\"1\\\" style=\\\"width: 600;\\\" width=\\\"600\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\">\\n                    <tbody>\\n                        <tr>\\n                            <td>\\n                                <div data-slot-container=\\\"1\\\" style=\\\"min-height: 30px\\\">\\n                                    <div data-slot=\\\"text\\\">\\n                                        <br \\/>\\n                                        <h2>Hello there!<\\/h2>\\n                                        <br \\/>\\n                                        We haven't heard from you for a while...\\n                                        <br \\/>\\n                                        <br \\/>\\n                                        {unsubscribe_text} | {webview_text}\\n                                        <br \\/>\\n                                    <\\/div>\\n                                <\\/div>\\n                            <\\/td>\\n                        <\\/tr>\\n                    <\\/tbody>\\n                <\\/table>\\n            <\\/center>\\n        <\\/div>\\n    <\\/body>\\n<\\/html>\", \"template\", null, null, 0, 0, 1, null, \"a:0:{}\", null, \"a:1:{i:0;a:3:{s:9:\\\"tokenName\\\";s:17:\\\"Dynamic Content 1\\\";s:7:\\\"content\\\";s:23:\\\"Default Dynamic Content\\\";s:7:\\\"filters\\\";a:1:{i:0;a:2:{s:7:\\\"content\\\";N;s:7:\\\"filters\\\";a:0:{}}}}}\", 0, 0, null, null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'lang' cannot be null at path/to/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'lang' cannot be null at path/to/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'lang' cannot be null at path/to/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
```

**Comment by npracht** [comment] 2017-10-05 09:44
Duplicate of https://github.com/mautic/mautic/issues/4617

**Closed** 2017-12-01 03:53 UTC
Labels: Bug, Duplicate, P1
