### ISSUE TITLE
Error on form submit

### ISSUE THREAD

**Issue by Pixman** [mautic/mautic#2693] opened 2016-10-10 10:41 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
After update to mautic 2.2.0, the form validation generate a 500 error code. The log file report a doctrine relationship error. 

i have make theses step for search correction : 

- update doctrine schema ( 33 requests waiting for update after mautic upgrade !)
- clear cache
- check folder permissions.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.0
| PHP version | 5.6.24

### Steps to reproduce:
1. go to a form, and submit it
2. the ajax request return 500 error
 
### Log errors: 

`
[2016-10-10 12:33:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #28568. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/clients/client0/web1/web/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #28568. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/clients/client0/web1/web/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []`

**Comment by escopecz** [comment] 2016-10-10 10:43
Duplicate of https://github.com/mautic/mautic/issues/2664

**Closed by escopecz** 2016-10-10 10:43 UTC

**Comment by Pixman** [comment] 2016-10-10 11:11
ok, sorry for duplicate
