### ISSUE TITLE
Form - Radio Group - Label and Value can't be "0" - will be deleted from the option list.

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#4751] opened 2017-08-31 00:09 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
Set up a Radio Group with an Option Label = 0 and Value = 0 (e.g. needed for an Net Promoter Score form). After saving the option "0" gets lost from the option list.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9.2
| PHP version | 7.0.22

### Steps to reproduce:
1. Add form
2. Add radio group
3. Add option label=0 and value=0
4. Save and close
5. Look at preview of form - option 0 doesn't show
6. Look into forms radio group field - option 0  doesn't exist anymore
 
### Log errors: 
none

**Comment by escopecz** [comment] 2017-08-31 09:13
I'll close this as duplicate of https://github.com/mautic/mautic/issues/3251. The developer fixing the option list with 0 value will fix both issues.

**Closed by escopecz** 2017-08-31 09:13 UTC
Labels: Bug

**Comment by dsp76** [comment] 2018-01-31 09:34
Also related to this bug: https://github.com/mautic/mautic/issues/4990
