### ISSUE TITLE
Sugar CRM Activity sync not working

### ISSUE THREAD

**Issue by markp22** [mautic/mautic#7503] opened 2019-05-07 14:01 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Calling mautic:integration:pushleadactivity for a Sugarcrm activity does not seem to do anything. No error message is displayed.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.17
| Browser | Chrome

### Steps to reproduce
1. Setup SugarCRM integration with several "Events to include in Activity Sync" selected.
2. Run mautic:integration:pushleadactivity.
 
### Log errors
No errors logged

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by markp22** [comment] 2019-05-08 10:23
Further to my original post, it appears that the getEngagements function in app/bundles/LeadBundle/Model/LeadModel.php is not returning any events despite the fact that I can clearly see events on the timelines of my contacts.

**Comment by escopecz** [comment] 2019-05-17 12:36
Duplicate of https://github.com/mautic/mautic/issues/6139

**Closed by escopecz** 2019-05-17 12:36 UTC
