### ISSUE TITLE
Problems with tracking IPv6 IP addresses

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#4209] opened 2017-06-08 11:43 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
If a visitor is on an IPv6 connection, Mautic does not seem to be tracking their activity. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.14

### Steps to reproduce:
1. Visit mautic instance from IPv6 connection and browse around
2. Fill out a Mautic form so that you become a known lead
3. Expect to have previous browsing history associated with known lead, but this doesn't seem to be happening. Known contact does not have any web activity logged.
 
### Log errors: 

None as far as I can tell

**Comment by ankitpr89** [comment] 2017-07-21 02:09
Since there are almost 16% of Internet users using  IPv6, and mautic loosing track of 16% visitors!!

**Comment by escopecz** [comment] 2017-07-21 07:15
That's not entirely true. Mautic use cookies as a main identifier.

**Comment by djeraseit** [comment] 2019-02-08 08:17
usually people on a mobile phone have IPv6 and if the website is listening over IPv6 it will be served to the IPv6 user. This issue is major since users can clear cookies but not change IP often.

**Comment by fmbertholdo** [comment] 2019-11-18 12:20
I use Mautic version 2.15.2 and when a lead uses ipv6 the selection fields are changed to the default option. Does anyone else have this mistake?

**Comment by npracht** [comment] 2020-08-04 20:41
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment] 2020-09-04 09:30
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 09:30 UTC
Labels: bug, tracking, triage-mautic-3
