### ISSUE TITLE
"empty" segment filter on tags is still not working

### ISSUE THREAD

**Issue by Woolgoose** [mautic/mautic#7982] opened 2019-10-25 23:47 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This bug was already reported here but got not fixed despite the bug report being closed:
Segment filters not working #2720

| Q   | A
| --- | ---
| Mautic version | 2.15.1-2.15.3
| PHP version | 7.2.23
| Browser | Google Chrome, FF

### Steps to reproduce
1. Create 10 contacts, 5 where tags are empty, 5 with any kind of tags
2. Create segment with filter tags > empty
3. Instead of getting 5 contacts with empty tags in this segment there are 0.
 
### Log errors
No errors in log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2019-11-05 20:50
I am able to reproduce this, segment with tags = not empty is correct but segment with tags = empty remains with zero contacts.

**Comment by RCheesley** [comment] 2020-06-11 10:53
Closing as duplicate of #7715

**Closed by RCheesley** 2020-06-11 10:53 UTC
Labels: Bug
