### ISSUE TITLE
Upcoming events display issues

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1516] opened 2016-03-10 03:27 UTC
## Description
Looking at a lead shows this in their upcoming events.
![screenshot from 2016-03-10 14 26 02](https://cloud.githubusercontent.com/assets/10385295/13658540/12aec93a-e6cc-11e5-8390-f1d3a45f2fc8.png)

Has a date formatting mistake on my part caused this?

**Comment by escopecz** [comment] 2016-03-16 07:24
Can you provide steps to reproduce?

**Comment by zstephen** [comment] 2016-03-16 08:09
I'm not quite sure how to reproduce this. It's just something that I've noticed in my instance, are there any key config or other files I should look for particular details in?

**Comment by escopecz** [comment] 2016-03-16 08:27
I also don't have a clue how to reproduce this issue. But developers cannot fix something they cannot reproduce locally so I guess we can as well close this issue if we don't have steps to reproduce.

**Comment by zstephen** [comment] 2016-04-15 20:35
Is there a way someone can indicate what values those are defined in before being displayed? If so then I'll have a look around and try to get more clues?

**Comment by PatchRanger** [comment] 2016-07-14 08:37
@zstephen Looks like it's a bug that relates to your installation. I propose such way of debugging:
- Notice the route where the issue is seen
- Find a corresponding controller for the route
- Find a corresponding controller action for the route
- Find which view is called to display broken item
- Debug the view & passed parameters

**Comment by zstephen** [comment] 2016-07-14 20:47
Hi @PatchRanger thanks for your advice, I'm not quite sure how to tap into those means of debugging.

I have my instance hosted on a godaddy shared linux hosting, so I'm not sure if I am able to monitor the system as much as if it was my own instance. Can you give me some tips on how I might do some of that debugging you've suggested?

Thanks

**Closed** 2016-07-29 17:39 UTC
Labels: Pending Feedback
