### ISSUE TITLE
Update Contact's Stage Based on Points

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4925] opened 2017-09-14 18:47 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I want the ability to change the stage of a contact based on the number of points they've earned or lost

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment] 2017-09-15 07:24
Duplicate of https://github.com/mautic/mautic/issues/4285 ?

**Closed** 2017-12-30 23:06 UTC
Labels: Feature Request
