### ISSUE TITLE
Filemanager 500 Error in 2.6.0

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3427] opened 2017-02-13 21:25 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:

After updating to 2.6.0, the Filemanager has become inaccessible. It just sits at the initial loading screen and generates a 500 error in the console.

<img width="854" alt="screen shot 2017-02-13 at 2 19 40 pm" src="https://cloud.githubusercontent.com/assets/590678/22903937/bac7fa10-f1f7-11e6-9752-8be9034c32cc.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0 
| PHP version | 7.0.14

### Steps to reproduce:
1. Be logged in.
2. Open the filemanager (https://mautic.mysite.com/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/index.html?type=Images)
 
### Log errors: 

Chrome console:
`jquery-1.11.3.min.js:5 GET https://mautic.mysite.com/app/bundles/CoreBundle/Assets/js/libr…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=899&type=Images   500 (Internal Server Error)`

Apache error.log:
```
[Mon Feb 13 14:07:07.156641 2017] [:error] [pid 3167] [client 0.0.0.0:64572] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to a member function setLogger() on null in /home/mautic/www/app/bundles/CoreBundle/EventListener/ErrorHandlingListener.php:42

\nStack trace:

\n#0 /home/mautic/www/app/cache/prod/appProdProjectContainer.php(5984): Mautic\\CoreBundle\\EventListener\\ErrorHandlingListener->__construct(Object(Symfony\\Bridge\\Monolog\\Logger), Object(Symfony\\Bridge\\Monolog\\Logger), NULL)

\n#1 /home/mautic/www/vendor/symfony/dependency-injection/Container.php(314): appProdProjectContainer->getMautic_Core_Errorhandler_SubscriberService()

\n#2 /home/mautic/www/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(183): Symfony\\Component\\DependencyInjection\\Container->get('mautic.core.err...')

\n#3 /home/mautic/www/vendor/symfony/event-dispatcher/ContainerAwareEventDispatc in /home/mautic/www/app/bundles/CoreBundle/EventListener/ErrorHandlingListener.php on line 42, referer: https://mautic.mysite.com/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/index.html?type=Images
```

**Comment by escopecz** [comment] 2017-02-13 22:06
Duplicate of https://github.com/mautic/mautic/issues/3381

**Closed by escopecz** 2017-02-13 22:06 UTC
