### ISSUE TITLE
Dynamic content variable doesn't work inside html attributes

### ISSUE THREAD

**Issue by wise-gorilla** [mautic/mautic#8843] opened 2020-05-28 16:27 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Dynamic content variable doesn't work inside html attributes because of the double quotes conflict, and the froala editor prevent the use of the single quotes in html.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
To test that try the followig codes in the email builder.
1. `<a href="{dynamiccontent="Dynamic Content 2"}">Link</a>`
2. `<a href='{dynamiccontent="Dynamic Content 2"}'>Link</a>`
 

My suggestion is to prevent froala editor from editing the html which allow us to add single quotes or to change the dynamic content variable and remove the space and double quotes from it making it like this {dynamiccontent=dynamic_content_2}
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-07-01 11:49
Closing as a duplicate of #7272

**Closed as completed by RCheesley** 2020-07-01 11:49 UTC
