### ISSUE TITLE
Apply button in GrapesJS builder causes an error and doesn't save - was #13271

### ISSUE THREAD

**Issue by ErikI1** [mautic/mautic#13794] opened 2024-05-29 14:29 UTC
### Mautic Version

5.0.4 series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Same issue as closed https://github.com/mautic/mautic/issues/13271

I got Javascript error after editing with the GrapesJS editor the default Blank template. The error code appears in the browser's console, after I press the Apply button in the right-upper corner. The check icon turns to never ending spinner.

### How can we reproduce this issue?

Step 1: Open the Blank email template.
Step 2: Press the "Apply changes" button in the right-upper corner.

### Relevant log output

```shell
Uncaught TypeError: History.pushState is not a function
    at preset-mautic:apply-form.postFormResponse (buttonApply.command.js:68:17)
    at Object.success (app.js?v3f21d8ec:288:33)
    at options.success (libraries.js?v3f21d8ec:1626:134)
    at fire (libraries.js?v3f21d8ec:271:351)
    at Object.fireWith [as resolveWith] (libraries.js?v3f21d8ec:276:179)
    at done (libraries.js?v3f21d8ec:667:95)
    at XMLHttpRequest.<anonymous> (libraries.js?v3f21d8ec:680:311)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment] 2024-05-30 08:20
Hi @ErikI1 thanks for reporting this. The reason the issue is closed, is because this bug has been fixed with the PR https://github.com/mautic/mautic/pull/13665. Therefore I'll close this issue as a duplicate.

The fix will be released in 5.1 but you can apply that fix in the meantime if you urgently need this to be addressed.

To help with getting the 5.1 release out, please join us on Fridays in the Open Source Friday sprints, where we help to test bug fixes and new features. All this can be done in the browser, and all you need is a GitHub account to help with that. Please do consider putting aside an hour or two to help - here's the docs: https://mau.tc/tester.

**Closed as not planned by RCheesley** 2024-05-30 08:20 UTC
Labels: bug, duplicate, needs-triage
