### ISSUE TITLE
Identifying companies behind anonymous visits

### ISSUE THREAD

**Issue by bramjeurissen** [mautic/mautic#2209] opened 2016-08-08 14:28 UTC
What type of report is this:

| Q  | A
| ---| ---

| Feature request? | 

## Description:
I would like to know witch company is visiting our website. Hubspot, Leadfeeder and other company's have this feature. It would be great to integrate with Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-08-08 14:43
Duplicate of https://github.com/mautic/mautic/issues/1164

**Closed by escopecz** 2016-08-08 14:43 UTC

**Comment by bramjeurissen** [comment] 2016-08-08 14:45
Why?

Groet,

*Bram Jeurissen*


Bel: +316 19 59 67 89
Surf: www.FNKE.nl <http://www.fnke.nl/>
Tweet: @Bram <https://twitter.com/bramjeurissen>
Link: Bram Jeurissen <https://nl.linkedin.com/in/bjeurissen>

**Comment by escopecz** [comment] 2016-08-08 14:56
Do you mean why it was closed? I thought it is obvious that it doesn't make a sense to have 2 identical feature requests opened. Or is yours different from the one I linked in my comment?

**Comment by bramjeurissen** [comment] 2016-08-08 15:14
Excuse me, did not notice.

Groet,

*Bram Jeurissen*


Bel: +316 19 59 67 89
Surf: www.FNKE.nl <http://www.fnke.nl/>
Tweet: @Bram <https://twitter.com/bramjeurissen>
Link: Bram Jeurissen <https://nl.linkedin.com/in/bjeurissen>

**Comment by bramjeurissen** [comment] 2016-08-08 15:15
Excuse me, did not notice.

Groet,

*Bram Jeurissen*


Bel: +316 19 59 67 89
Surf: www.FNKE.nl <http://www.fnke.nl/>
Tweet: @Bram <https://twitter.com/bramjeurissen>
Link: Bram Jeurissen <https://nl.linkedin.com/in/bjeurissen>
