### ISSUE TITLE
Cron Job doesn't finish after update to 4.2.1

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#11061] opened 2022-04-08 12:32 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After migrate from 4.1.2 to 4.2.1 the jobs campaigns:rebuild and campaigns:update does never ends. 

When executed from console the process gets 100% but keeps summing and never ends. 

Sorry, it's in Spanish:

Recuperando contactos para la campaña 47
3 total de contacto(s) a ser agregados en lotes de 300
 1102/1102 [============================] 100%^C

It means:
Retreaving contacts for campaign 47
3 contacts to be adder in groups of 300
 1102/1102 [============================] 100%^C

The log reports this:

[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47. 
[...] this sequence repeats for many lines. 

I have checked than those contacts are already in the campaign. 

I have tried  bin/console m:a:g and didn't work
mautilc/s/update/schema reports schema is up to date
doctrine:migration:migrate reports nothing to migrate 
doctrine:schema:update --dump-sql reports errors:

> In AbstractMySQLDriver.php line 128:
> 
>   An exception occurred while executing 'ALTER TABLE maujs_oauth2_accesstokens CHANGE client_id c
>   lient_id INT UNSIGNED NOT NULL, CHANGE user_id user_id INT UNSIGNED DEFAULT NULL, CHANGE token
>   token VARCHAR(191) NOT NULL, CHANGE scope scope VARCHAR(191) DEFAULT NULL':
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key co
>   nstraint 'FK_5DD8E68219EB6921'
> 
> 
> In Exception.php line 18:
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key co
>   nstraint 'FK_5DD8E68219EB6921'
> 
> 
> In PDOConnection.php line 132:
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key co
>   nstraint 'FK_5DD8E68219EB6921'

### How can we reproduce this issue?

I'm not sure how to reproduce this in a clean installation. 

### Relevant log output

```shell
The log reports this:

[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47. 
[...] this sequence repeats for many lines.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by carduz** [comment] 2022-04-17 14:18
I had an analogous issue and after 3 hours of debugging I found out that the issue was caused by a contact that was previously removed manually by the campaign. Check the conditions inside "Mautic\CampaignBundle\Membership\Action\Adder::updateExistingMembership"

**Comment by Carlos-mb** [comment] 2022-04-17 15:58
Thank you Carduz.

I already deleted the first three contacts that caused the problem, but it fails with other contacts.

I can't debug because I'm using 4.1.2. The processes are working fine in that version.

Regards.

**Comment by RCheesley** [comment] 2022-05-17 12:12
Hi folks,

Thanks for the bug report, pinging @mautic/campaigns-webhooks-tiger-team to take a look and see if we can reproduce this.

**Comment by adiux** [comment] 2022-07-13 15:53
We can confirm that we reproduced the issue on the 4.4 branch. We try to solve it now. Any hint would be appreciated.

**Comment by escopecz** [comment] 2022-07-14 09:29
This means you have an infinite loop in your campaigns. We also found several customers have this problem when we released it. We had to revert [this commit](https://github.com/mautic/mautic/commit/c7d9750ab72a5f70f65761dae0e2a460e8a00c12) (as @volha-pivavarchyk  pointed out) before we'll figure out a way how to find the infinite loops in campaigns.

**Comment by RCheesley** [comment] 2022-07-14 10:18
Not sure if it is the same issue but I noticed this PR from @kuzmany to fix a looping campaign issue: https://github.com/mautic/mautic/pull/11332

**Comment by volha-pivavarchyk** [comment] 2022-07-14 10:24
@escopecz Could you please write when this commit was reverted or in what version?

**Comment by volha-pivavarchyk** [comment] 2022-07-14 10:28
@RCheesley I have just found the PR [#11318](https://github.com/mautic/mautic/pull/11318) from @kuzmany to fix it. It it the same issue

**Comment by escopecz** [comment] 2022-09-15 10:12
I'm about to merge the PR https://github.com/mautic/mautic/pull/11318 but @kuzmany created it against 5.x branch so it will be fixed in Mautic 5. Is there a need to fix it for Mautic 4 as well or is Mautic 5 good enough? If we need it in M4 then is there some volunteer to cherry-pick the commits on top of the 4.4 branch?

**Closed as completed** 2022-09-15 10:22 UTC
Labels: bug, ready-to-test, campaigns

**Comment by martinstadelmann** [comment] 2024-03-06 09:58
@escopecz I cherry-picked the commit on top of the 4.4 branch and opened a new PR in #13524.
