### ISSUE TITLE
Cant edit contacts nor add a new contact

### ISSUE THREAD

**Issue by zora-li** [mautic/mautic#3686] opened 2017-03-15 17:56 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
The more details the better...

## If a bug:

Cant edit nor add new contact.

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | PHP Version 5.6.28

### Steps to reproduce:
1. Go to Contact
2. Create ou Edit a Contat
3. Save and Close not working
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-03-15 18:21
Any errors in the logs?

**Comment by zora-li** [comment] 2017-03-15 18:30
Not in Developer Tools in Chrome.

Where do I find other log that could help ?

Thanks




*Marcelo Galli*

*Diretor Executivo*

* www.cotexo.com.br <http://www.cotexo.com.br>*

*11 94005 4120*

*11 3090 2904*

2017-03-15 15:22 GMT-03:00 John Linhart <notifications@github.com>:

**Comment by zora-li** [comment] 2017-03-15 18:50
Found in Mautic 👍 
[2017-03-15 16:35:33] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO ma_point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params ["2017-03-15 16:35:33", 3, 1081, 273]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1081' for key 'PRIMARY'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO ma_point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params [\"2017-03-15 16:35:33\", 3, 1081, 273]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1081' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1081' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1081' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-03-15 16:42:40] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO ma_point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params ["2017-03-15 16:42:40", 3, 2325, 283]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2325' for key 'PRIMARY'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO ma_point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params [\"2017-03-15 16:42:40\", 3, 2325, 283]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2325' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2325' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2325' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-03-15 16:57:22] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO ma_point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params ["2017-03-15 16:57:22", 3, 2048, 302]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2048' for key 'PRIMARY'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO ma_point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params [\"2017-03-15 16:57:22\", 3, 2048, 302]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2048' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2048' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2048' for key 'PRIMARY' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-03-15 14:33:12] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.tipo_da_empresa FROM ma_leads l WHERE (l.tipo_da_empresa <> '') AND (l.tipo_da_empresa IS NOT NULL) ORDER BY l.tipo_da_empresa ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.tipo_da_empresa FROM ma_leads l WHERE (l.tipo_da_empresa <> '') AND (l.tipo_da_empresa IS NOT NULL) ORDER BY l.tipo_da_empresa ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-03-15 14:33:12] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.segmento_da_empresa FROM ma_leads l WHERE (l.segmento_da_empresa <> '') AND (l.segmento_da_empresa IS NOT NULL) ORDER BY l.segmento_da_empresa ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.segmento_da_empresa FROM ma_leads l WHERE (l.segmento_da_empresa <> '') AND (l.segmento_da_empresa IS NOT NULL) ORDER BY l.segmento_da_empresa ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-03-15 14:33:39] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.tipo_da_empresa FROM ma_leads l WHERE (l.tipo_da_empresa <> '') AND (l.tipo_da_empresa IS NOT NULL) ORDER BY l.tipo_da_empresa ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.tipo_da_empresa FROM ma_leads l WHERE (l.tipo_da_empresa <> '') AND (l.tipo_da_empresa IS NOT NULL) ORDER BY l.tipo_da_empresa ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.tipo_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-03-15 14:33:39] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.segmento_da_empresa FROM ma_leads l WHERE (l.segmento_da_empresa <> '') AND (l.segmento_da_empresa IS NOT NULL) ORDER BY l.segmento_da_empresa ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.segmento_da_empresa FROM ma_leads l WHERE (l.segmento_da_empresa <> '') AND (l.segmento_da_empresa IS NOT NULL) ORDER BY l.segmento_da_empresa ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

**Comment by escopecz** [comment] 2017-03-15 19:02
This is the problem: `Column not found: 1054 Unknown column 'l.segmento_da_empresa' in 'field list'`. What is the setting of the field segmento_da_empresa? It seems that it exists as a custom field, but the column was not created in the `leads` table. Do you have any idea why? Did you do some manual schema changes?

**Comment by zora-li** [comment] 2017-03-15 19:17
The colum in example (1 lead tested) is : Oficina de Funilaria

We did a select and insert command in database to update some fields but did not changed the database schema. Seems the problem appeared after upgrad to 2.7.1.

IS there any clue to solve it ?

Thanks you.

**Comment by escopecz** [comment] 2017-03-15 19:27
It can be caused by some wrong value in the lead_fields table. And if I understand well, you were changing those values manually with a INSERT query. I don't know what you've changed, so I'm helpless here. If you have a backup of that table before your manual changes, try to apply it. I'll close this PR since it doesn't seem to be a Mautic bug. But feel free to comment with new info.

**Closed by escopecz** 2017-03-15 19:27 UTC
