### ISSUE TITLE
Using the API to add DNC without a reason defaults to 0 ("Contactable")

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic#9076] opened 2020-08-13 11:17 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When adding DNC to a contact through the API, and either not including abody or including the body `{ "reason": 0 }` results in the Contact getting added to the `lead_donotcontact` table with a reason of 0 - "Contactable". Thus actually rendering the Contact contactable while appearing to set DNC. Calling the came endpoint multiple times like this adds new duplicate rows to `lead_donotcontact` - removing DNC via the API only removes the fake DNC's one at a time.

So if you for example call the endpoint `POST /contacts/14/dnc/email/add` 3 times in a row, you end up with this in Mautic:

![image](https://user-images.githubusercontent.com/8426548/90128172-c1708180-dd66-11ea-9e94-cc1a839fd875.png)

...and in order to remove all three you have to call `POST /contacts/14/dnc/email/add` 3 times.

The [documentation states](https://developer.mautic.org/#add-do-not-contact) that calling the endpoint without a reason should result in defaulting to reason 3 ("Manual"), but that is not currently the case.

Thus, the default reason for API-based DNC additions needs to be changed from 0 to 3, and the range of valid reasons needs to be restricted to only 1 ("Unsubscribed"), 2 ("Bounce") and 3 ("Manual").

| Q   | A
| --- | ---
| Mautic version | 3.1
| PHP version | 7.3.21
| Browser | Irrelevant, using Postman for API calls

### Steps to reproduce
1. Have the API enabled and a Contact in Mautic
2. Call the API endpoint `POST /contacts/<ContactId>/dnc/email/add` multiple times
3. The Contact in Mautic now has a bunch of duplicate fake DNC statuses on the Email channel
4. Call the endpoint `POST /contacts/<ContactId>/dnc/email/remove` once
5. Only one of the DNS statuses on the Email channel was removed

**Comment by StoppingBuck** [comment] 2020-08-14 06:30
Adding a little more:
- I initially thought this was a regression, but it seems to be present in the 2.x branch as well
- The response from Mautic to both adding and removing DNC contains a lot of unnecessary information about the contact, such as irrelevant field descriptions etc., but that issue is probably covered by #7385 
- When removing DNC with `POST /contacts/<ContactId>/dnc/email/remove`, in addition to the `contact` object, a boolean field called `recordFound` is included and will indicate whether there was any DNC status to remove in the first place (i.e. trying to remove DNC from someone who isn't marked as DNC in the first place will give `recordFound: false`. However, no such logic appears to be used for the adding DNC endpoint. 

I think the smartest way to solve this would be to apply a boolean to the add DNC endpoint, like is currently with the remove DNC endpoint, to show whether DNC was added. So if you try to add DNC to someone who already has DNC it could say `recordChanged: false`. (Incidentally, I think we should change the `recordFound` variable in remove DNC endpoint to `recordChanged` as calling it "recordFound" is misleading, since it makes it sound like a contact was not found.

**Comment by RCheesley** [comment] 2020-08-21 16:22
@StoppingBuck thanks for the bug report and apologies for the delay in getting back to you!

Would you be up for making a PR to fix this?  We have some resources [here](https://contribute.mautic.org/contributing-to-mautic/developer) that might be helpful to get set up locally.  Shout if you need any help!

**Comment by StoppingBuck** [comment] 2020-09-04 08:11
After looking at #8434 I think this error might be related to the fact that calling the add DNC API endpoint without `{ "reason": 1 }` (or 2 or 3) in the body accidentally sets the reason to 0, thus rendering the contact contactable - and accidentally removing any DNC status already there. Hopefully, the linked PR will fix this.

**Comment by StoppingBuck** [comment] 2020-09-07 12:05
After upgrading to Mautic 3.1 and re-testing it seems that this is still present, but it actually seems that this only happens if the DNC is created with a reason of `0`. As soon as a DNC is properly set with a reason of `1`, `2` or `3`, it is no longer possible to spam the `0` reason calls.

I've created a separate bug report - #9175 - to handle the fact that it is actually possible to set DNC with reason: `0` at all. I can't really make out whether this bug - being able to spam dummy DNC rows of `0` reason - is actually part of the other bug report or not.

@RCheesley if the two reports are actually about the same thing then I recommend closing this one in favor of #9175 as fixing that one would fix this one as well.

**Comment by StoppingBuck** [comment] 2020-09-19 13:51
I've updated the title and description of this bug to better tell it apart from the other DNC shenanigans.

**Comment by dennisameling** [comment] 2020-09-21 11:14
@StoppingBuck Good catch - I did some research as part of my work on https://github.com/mautic/mautic/pull/9226. The issue you're describing is basically caused by the following:
- The function [`addDncForContact`](https://github.com/mautic/mautic/blob/3.0/app/bundles/LeadBundle/Model/DoNotContact.php#L91) has a default of `DNC::BOUNCED`, which equals 2. This function is used by several parts of Mautic, e.g. while creating contacts through the API, bounce processing, etc. - the default value of 2 is good IMO as it at least creates the DNC properly.
- The API endpoint `/dnc/email/add` that you're mentioning has the following [piece of code](https://github.com/mautic/mautic/blob/3.0/app/bundles/LeadBundle/Controller/Api/LeadApiController.php#L412) in it:
  
  ```PHP
  $reason   = (int) $this->request->request->get('reason');
  ```
  This code basically means that, if no `reason` is set in the POST body or if it's set but empty, it is type casted to 0 because of the `(int)` in front of it (empty string = 0 after casting). This is then passed on to `addDncForContact` and there you have it: the reasonCode will be 0.

The fix for this is rather simple; setting a default value of 3 (manual) in case no or an empty reason was given in the POST request. This restores the functionality that's mentioned in the developer docs. Since https://github.com/mautic/mautic/pull/9186 doesn't cover this scenario, I'll go ahead and create a separate PR to fix this functionality.

**Comment by dennisameling** [comment] 2020-09-21 11:46
@StoppingBuck PR done, please test whether this fixes the issue: https://github.com/mautic/mautic/pull/9229

**Comment by dennisameling** [comment] 2020-09-21 11:53
Hi! To keep things central regarding issues around Do Not Contact (DNC), I created a JIRA issue to track all issues related to DNC in a single place. That way, we can more efficiently fix the several bugs that were reported. Please check it out: https://mautic.atlassian.net/browse/TPROD-72

**Comment by dennisameling** [comment] 2020-09-21 17:31
Closing now that https://github.com/mautic/mautic/pull/9229 has been merged 👍

**Closed as completed by dennisameling** 2020-09-21 17:31 UTC
Labels: T2, bug, API, contacts
