### ISSUE TITLE
Updating database schema error

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#10973] opened 2022-03-16 15:52 UTC
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I have updated Mautic on version 4.2.0

> **This is the upgrade process that I use:**
> 
> **Step 1** Check for unfinished migrations 
> `./bin/console doctrine:migration:migrate`
> 
> Now we’re gonna make sure there aren’t any differences between your database schema and how it is supposed to be:
> 
> `./bin/console doctrine:schema:update --force`
> 
> Clear the Mautic cache:
> 
> `./bin/console cache:clear`
> 
> Now go browse your Mautic UI to check if everything is running properly, also check the Mautic logs apache logs and PHP logs to see if there’s any new error.
> 
> **Step 2** Find the latest update.
> 
> `./bin/console mautic:update:find`
> 
> Apply the update.
> 
> `./bin/console mautic:update:apply`
> 
> Commit the update.
> 
> `./bin/console mautic:update:apply --finish`
> 
> **Step 3** Repeat Step 1 commands, check logs for errors.
> 
> Finished.

On Mautic 4.2.0 if I use this command : `php bin/console doctrine:migration:migrate`
I have this error message : 
`WARNING! You have 138 previously executed migrations in the database that are not registered migrations.`

Prompt ask : `Are you sure you wish to continue? (y/n)` => y
Prompt ask :`WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)` => y

The result is : `No migrations to execute.`

I think, all it's OK (but in reality no...).

After that, I use this command : `php bin/console doctrine:schema:update --force`

I have this answer : 

```
Updating database schema...
In AbstractMySQLDriver.php line 128:

  An exception occurred while executing 'ALTER TABLE oauth2_accesstokens CHANGE client_id client_id INT UNSIGNED NOT NULL, CHANGE user_id user_id INT UNSIGNED DEFAULT NULL, CHANGE token token VARCHAR(191) NOT NULL, CHANGE scope scope VA  
  RCHAR(191) DEFAULT NULL':                                                                                              

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A1  
  9EB6921'                                                                                                               

In Exception.php line 18:
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A1  
  9EB6921'                                                                                                               

In PDOConnection.php line 132:
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A1  
  9EB6921'

doctrine:schema:update [--em EM] [--complete] [--dump-sql] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**What can I do for this?**

### How can we reproduce this issue?

Step 1: update Mautic to v4.2.0
Step 2: execute `php bin/console doctrine:migration:migrate`
Step 3: execute `php bin/console doctrine:schema:update --force`

### Relevant log output

```shell
Not log
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-03-16 18:37
Pretty sure this is a duplicate of https://github.com/mautic/mautic/issues/9129 but feel free to request a re-open if that's not the case.

**Closed as completed by RCheesley** 2022-03-16 18:37 UTC
Labels: bug, needs-triage

**Comment by PierreAmmeloot** [comment] 2022-03-30 09:59
Hello @RCheesley,

Indeed it is apparently the same bug.

Pierre
