### ISSUE TITLE
Forms Action Email Disable

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#3409] opened 2017-02-11 22:06 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 7.0

### Steps to reproduce:
1. Create a standalone form
2. Go to Action
3. Select Send Email to Contact
![screenshot from 2017-02-11 18-04-08](https://cloud.githubusercontent.com/assets/14807878/22857863/9f0446a4-f084-11e6-9e76-9b07a0676fbe.png)
The problem is in
Forms > Standalone Form > Forms Action

The email is published and enable.
I have tried 4 browsers to see if is related to JS.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-02-13 13:10
What is the issue here?

**Comment by ninjoan** [comment] 2017-02-13 13:13
Can add emails in the Forms Action, dont let you preview the email.

And if you select an email template without preview and saved the form and reopen the form to edit if you preview the email you choose it give a error 404.

**Comment by ninjoan** [comment] 2017-02-16 21:03
[Update] i upgrade to 2.6.1 still have the bug.

**Comment by escopecz** [comment] 2017-02-17 08:17
Sadly, this was not fixed yet.

**Comment by alanhartless** [comment] 2017-03-10 08:39
Duplicate of #3063 maybe

**Closed** 2017-03-13 07:50 UTC
Labels: Bug, Ready To Test
