### ISSUE TITLE
Page hit dosen't load

### ISSUE THREAD

**Issue by Aneta09** [mautic/mautic#4011] opened 2017-05-07 13:52 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I have noticed something like this:

![2017-05-07_15-41-18](https://cloud.githubusercontent.com/assets/25117928/25781691/1a1a74ee-333d-11e7-9dfa-60f2cc200bcc.jpg)

What happened? 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-05-08 13:09
I cannot reproduce it with Mautic Landing Pages nor with pages tracked with Mautic JS Tracking. Do you have any idea how to reproduce it? Do you know if the page hits with no URL were made from a Landing Page or from a website tracked by Mautic? How did you configure the tracking?

**Comment by Aneta09** [comment] 2017-05-08 13:46
Here is link to website: l[ink](url https://www.mymautic.pl/)
I used WP Mautic (plugin from GitHub - not form repository Wordpress).

**Comment by escopecz** [comment] 2017-05-08 14:16
The mtc.js is implemented there 2 times. That could be the reason of your troubles.

**Comment by Aneta09** [comment] 2017-05-08 15:16
I deleted one of them. I will observe the change, I hope it will help.  Thanks for the advice.

**Comment by Aneta09** [comment] 2017-05-10 10:54
@escopecz  Still doesn't work. Now I don't have any hit. Contact view - Mautic doesn't show which pages the contact hit. 
![2017-05-10_12-54-07](https://cloud.githubusercontent.com/assets/25117928/25895362/d38a28f4-357f-11e7-9e1a-e1cde132de2c.jpg)

**Comment by escopecz** [comment] 2017-05-10 21:52
What's your page again?

**Comment by Aneta09** [comment] 2017-05-10 22:00
https://www.mymautic.pl/

**Comment by escopecz** [comment] 2017-05-11 12:24
I can see a OneSignal JS error there. It should be fixed in 2.8.1. It will be released soon.

The event request (page hit) is successfully made. Isn't it the same problem as in https://github.com/mautic/mautic/issues/3671#issuecomment-300767098 ?

**Comment by Aneta09** [comment] 2017-05-12 06:43
OK. Thanks.

**Closed** 2017-05-12 11:10 UTC
Labels: Pending Feedback
