### ISSUE TITLE
"Override block" option not available for all users.

### ISSUE THREAD

**Issue by duduric** [mautic/mautic#1523] opened 2016-03-11 15:49 UTC
The "override block" when a landing page is checked by someone else is not available to some users.
I couldn't find anything related in the roles editor. Is it somehow locked to the Admin role?

**Comment by escopecz** [comment] 2016-03-16 07:50
Could you please write down exact steps to replicate the issue?

**Comment by duduric** [comment] 2016-03-16 14:37
Just open in administration any landing page currently checked out by another user. It will show the dialog "This page is currently checked out by so-so....", with an "Override block" link. Though this link only shows to the administrator role... I think it should be available to all roles with permission to edit other users landing pages?

**Comment by npracht** [comment] 2016-05-26 10:31
Hi @escopecz , let me complete the brief of @duduric.

# Step to reproduce
1. create a user (A) with admin rights
2. create a user (B) with limited rights (only full rights on emails for instance)
3. edit an email with A, apply to save and quit badly (close your window, not on save and close)
4. go with user B editing the same email, **you'll be block because editing by user A**.
5. edit another email with B, apply to save and quit badly (close your window, not on save and close)
6. go with user A editing the same email, **you'll be block because editing by user A + have the opportunity to override block to finally edit the email**.

# Suggestion
It would be great to have in the role administration to be able to give this right. **Override block when a user edit an item**.

_Somewhere here_
![capture d ecran 2016-05-26 a 11 32 10](https://cloud.githubusercontent.com/assets/14075239/15571856/a0c9f50c-233d-11e6-86f3-0ba4427bdec6.png)

**Comment by dongilbert** [comment] 2016-08-23 02:12
Fixed in #2291

**Closed** 2016-08-23 02:12 UTC
Labels: Bug, Ready To Test
