### ISSUE TITLE
Upgrade 2.1 to 2.1.1 - Mautic freeze with french user

### ISSUE THREAD

**Issue by edwood79** [mautic/mautic#2528] opened 2016-09-13 09:19 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No 
| Enhancement? | No

## Description:
After the upgrade, there no data on the interface and we can use mautic. Everything is freeze. The bug affect only user who has setted the language in french. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 7.0.7-1

### Steps to reproduce:
1. Log with a user with french interface
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-09-13 09:37
Please provide the errors from the logs (https://mautic.org/docs/en/tips/troubleshooting.html)

**Comment by edwood79** [comment] 2016-09-16 14:33
It seems to be a JS error
![mauticfr-jserror](https://cloud.githubusercontent.com/assets/20922403/18589496/501ccd9a-7c2b-11e6-8fa4-3243b1eb70b5.PNG)

**Comment by escopecz** [comment] 2016-09-16 15:21
Check if it's not the [Cloudflare](https://github.com/froala/wysiwyg-editor/issues/1482) problem.

**Comment by edwood79** [comment] 2016-09-16 16:15
I don't use Cloudflare

**Comment by edwood79** [comment] 2016-09-16 16:24
I don't this error when I switch in English. Please find the 

> TypeError: document.body is null
> vmlAvailable()
> libraries.js:4057
> window.jsPlumbAdapter.isRenderModeAvailable()
> libraries.js:4084
> window.jsPlumbAdapter.setRenderMode()
> libraries.js:4084
> window.jsPlumbInstance/this.setRenderMode()
> libraries.js:4280
> window.jsPlumbInstance/this.init<()
> libraries.js:4226
> bound ()
> self-hosted
> jQuery.Callbacks/fire()
> libraries.js:328
> jQuery.Callbacks/self.fireWith()
> libraries.js:333
> .ready()
> libraries.js:340
> completed()
> libraries.js:340
> libraries.js:4057:414

> SyntaxError: missing } after property listdashboard:27:96
> ReferenceError: mauticBaseUrl is not defined
> Mautic.activateGlobalFroalaOptions()
> app.js:13
> Mautic.onPageLoad()
> app.js:13
> <anonyme>
> dashboard:980
> app.js:13:955

> ReferenceError: mauticAjaxUrl is not defined
> <anonyme>
> app.js:6
> jQuery.Callbacks/fire()
> libraries.js:328
> jQuery.Callbacks/self.fireWith()
> libraries.js:333
> .ready()
> libraries.js:340
> completed()
> libraries.js:340
> app.js:6:88

**Comment by Pixman** [comment] 2016-09-28 07:26
Hello, the bug is caused by the translation a non escaped quote is present in string.
see my capture
![mautic_french_bug](https://cloud.githubusercontent.com/assets/314482/18904280/7ff72246-855d-11e6-9edd-5bdf5a4bffcc.png)

**Comment by escopecz** [comment] 2016-09-28 08:02
It should be fixed by https://github.com/mautic/mautic/pull/2540

**Closed** 2016-09-30 07:19 UTC
Labels: Ready To Test
