### ISSUE TITLE
Segment rights for roles look incomplete 

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#13650] opened 2024-04-12 23:22 UTC
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

not relevant

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The rights for roles related to segments are incomplete. Its missing the "own" rights and the "create" right. Currently I can't take away the right to create a segment from any user, as it looks like?

<img width="234" alt="image" src="https://github.com/mautic/mautic/assets/1241376/50dd2c2d-7889-4017-a871-6cdd6b953b83">

### How can we reproduce this issue?

Step 1: Go to settings > roles.
Step 2: Create a new role or open an existing one
Step 3: Look into Contacts section, where you find the rights related to segments.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment] 2024-04-19 09:01
@dsp76 I cannot reproduce. See what I see when I go to the contact permissions on latest 5.x branch:
![Screenshot 2024-04-19 at 11 01 14](https://github.com/mautic/mautic/assets/1235442/a95640a6-87d3-4503-b46f-2c3e7ab7c02d)

**Comment by escopecz** [comment] 2024-04-19 09:03
Perhaps this got fixed by https://github.com/mautic/mautic/pull/13321. Closing

**Closed as completed by escopecz** 2024-04-19 09:03 UTC
Labels: bug, pending-feedback, segments, roles
