### ISSUE TITLE
Edit a contacts points

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#2125] opened 2016-07-27 18:48 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:

Ability to edit the contacts points under the edit page like below

![image](https://cloud.githubusercontent.com/assets/985837/17187887/fb6c0c42-5408-11e6-95fc-578ca25cf2aa.png)

This is useful if you have a marketer spamming fields and you want to set his points to something like -1000 so it does not affect reports, triggers or actions

**Comment by escopecz** [comment] 2016-07-28 07:09
Duplicate of https://github.com/mautic/mautic/issues/967

**Closed by escopecz** 2016-07-28 07:09 UTC
