### ISSUE TITLE
Page/email builder empty after I select new theme

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5132] opened 2017-10-11 15:05 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | X

## Description:
When creating a new email and choosing a theme, going on the builder directly in a short time will not load the theme.
<img width="939" alt="capture d ecran 2017-10-11 a 16 57 25" src="https://user-images.githubusercontent.com/31535432/31448904-d5f47050-aea5-11e7-9ca2-4f31300627dc.png">

Then closing the builder will not work
<img width="689" alt="capture d ecran 2017-10-11 a 16 57 34" src="https://user-images.githubusercontent.com/31535432/31448922-dec828f2-aea5-11e7-97e4-02714d593d82.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Create a new email
2. Change the theme
3. In a really short time after changing the theme, go in the builder
4. It will be empty
5. Click on close the builder
6. It will grey out and load indefinitely

**Comment by escopecz** [comment] 2018-10-23 11:36
This is caused by you being faster than the request :)

When you select a theme then a request is made to the server requesting HTML of that theme to prefill the builder content. If you open the builder before the HTML was loaded it will crash.

So the quick fix is to wait a second after you select the theme and then open the builder.

The proper fix would be to disable the builder button until the content is fetched.

**Comment by npracht** [comment] 2018-10-31 09:57
Let's close it.

**Closed by npracht** 2018-10-31 09:57 UTC
Labels: Bug
