### ISSUE TITLE
Cloned Campaign Bug in Campaign builder

### ISSUE THREAD

**Issue by rodurma** [mautic/mautic#1455] opened 2016-02-20 21:30 UTC
- Clone an exists campaign
- Click to edit this cloned capaign
- Open the campaign builder
- The fluxogram have a bug (parts of them isn't attached)

**Comment by rodurma** [comment] 2016-02-23 02:12
https://www.youtube.com/watch?v=zE3Ze6eCokE

**Comment by kuzmany** [comment] 2016-02-23 19:23
confirm

**Comment by fashionlearn** [comment] 2016-02-24 13:28
Confirm

**Comment by escopecz** [comment] 2016-02-24 13:54
This is duplicate of https://github.com/mautic/mautic/issues/1182

**Closed by escopecz** 2016-02-24 13:54 UTC
