### ISSUE TITLE
Form redirects add data

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#4358] opened 2017-07-06 11:14 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
I dont know if someone else had the same problem. Actually i need the feature when i use the mautic forms within the redirect, it would be great if the submitted data will be send also (as get parameters?) to the redirect url.

the following situation i have, i want to use the mautic form, and want to redirect the user to an personalized site. to personalize the site (user get an unique url) i need the form data.

regards

**Comment by escopecz** [comment] 2017-07-06 11:20
It seems like a duplicate of https://github.com/mautic/mautic/issues/900 and that this feature is already implemented.

**Closed by escopecz** 2017-07-06 11:20 UTC
