### ISSUE TITLE
Missing Admin Avatar at fresh composer based install v.4.3.1

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#11287] opened 2022-06-27 06:21 UTC
### Mautic Version

4.3.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Chrome

### What happened?

A symptom occurred during a recent Mautic 4.3.1 composer-based installation, with nothing loaded on the admin avatar image.

The missing image wanted to be uploaded from this location: https://i2.wp.com/mautic_setup.tld/media/images/avatar.png?ssl=1

You receive the following error message when opening the image's URL: "We cannot complete this request, remote data could not be fetched"

Checked all avatar related previously resolved issue. Even this: https://forum.mautic.org/t/avatar-png/16423/8 
The Firewall issue was double checked: "firewall thing, port 80/443 needs to be open".

Finally, I found that the avatar is not loaded because avatar.png is not where Helper would look, i.e. it is a **scaffolding issue**.

### Working solution:

Copying avatar.png to <mautic_root>/docroot/media/images from /docroot/app/assets/images/avatar.png will resolve the issue.

I also ran into the problem with two consecutive installations; one running an nginx web server and the other running only in Apache/2.4.53. Thus, an error in assigning a special permission to nginx can also be ruled out.

### How can we reproduce this issue?

Step 1: Fresh composer based Mautic install with `composer create-project mautic/recommended-project:^4 some-dir --no-interaction`

### Relevant log output

```shell
Nothing
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-06-27 08:01
Thanks for the report but this is a duplicate of #11286 so let's keep things centralised over there :)

**Closed as completed by RCheesley** 2022-06-27 08:01 UTC
Labels: bug, duplicate
