### ISSUE TITLE
Permission error while accessing landing pages

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#5416] opened 2017-12-05 22:53 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Create a role "limited rights"
Set permission to have

Landing pages : full
<img width="1102" alt="1" src="https://user-images.githubusercontent.com/930391/33635163-34b6ddde-da17-11e7-8044-b91d23f7810f.png">

dynamic content : none
<img width="1163" alt="2" src="https://user-images.githubusercontent.com/930391/33635162-3499d9fa-da17-11e7-9f29-405b9ac5f0a7.png">

(the idea here is to let users have access to landing page and builder but no access to web dynamic content section)

Apply it to a user
Log with this specific user

Go to landing pages modules

Click New : nothin happens
(see error log below)

In mautic 2.10.1 it was working fine, but as soon as we updated in 2.11, it stopped working

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.12

 
### Log errors: 

mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for dynamicContent in permissions classes" at /home/www/mautic/www_rec/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for dynamicContent in permissions classes at /home/www/mautic/www_rec/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:128)"} []

**Comment by dbhurley** [comment] 2017-12-06 03:29
Duplicate of #5321 

Good catch @YannickBiet

**Closed by dbhurley** 2017-12-06 03:29 UTC
