### ISSUE TITLE
Gated Video Pause and Play after form fill working for youtube but not for html-mp4 video

### ISSUE THREAD

**Issue by kmanojkumar** [mautic/mautic#7397] opened 2019-04-09 05:08 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After form submits, gated video re-plays from the beginning, not from where it has paused. Browser console has the following error

| Q   | A
| --- | ---
| Mautic version | Latest version
| PHP version | 7.2-fpm
| Browser | Google Chrome

### Steps to reproduce
1. Insert the form with a video/mp4, fill the form and click submit
2. Video replays from the start
 
### Log errors
![Screenshot 2019-04-09 at 10 31 05 AM](https://user-images.githubusercontent.com/14366356/55774631-93649880-5ab3-11e9-8149-89a37881eada.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kmanojkumar** [comment] 2019-04-10 05:02
Does anyone face this issue? @npracht can you please help?

**Comment by npracht** [comment] 2019-04-10 06:50
Hi @kmanojkumar, your how to reproduce is incomplete. I don't have the issue on my side. Can you show the HTML you use ? is the mtc.js on your web page ? Can we have the URL where the code is ?
What is latest version for you ?

Thanks

**Comment by kmanojkumar** [comment] 2019-04-10 11:19
Hi @npracht ,

**I am using the following code:** 
```
<video width="100%" height="100%" data-form-id="9" data-gate-time="5">
    <source type="video/mp4" src="https://*****.s3.ap-south-1.amazonaws.com/public-docs/*****.mp4" />
</video>
```

**mtc.js is hosted on https://pmail.peerxp.com (Mautic) and https://pws.peerxp.com/demo/ is a wordpress site serving the html video.** You may please play the video on this page and check if I am missing something. 

Mautic Latest version, I am using is: v2.15.1

**Comment by npracht** [comment] 2019-04-10 11:51
I cannot reproduce your issue:
![Capture d’écran 2019-04-10 à 13 50 40](https://user-images.githubusercontent.com/14075239/55876322-a8b2f300-5b97-11e9-8dda-954a20c2a1f2.png)


Are you logged into mautic in the same browser session ? Did you try while doing incognito ?

**Comment by kmanojkumar** [comment] 2019-04-10 12:07
No, I have resolved the browser console errors that were being displayed after updating mautic to the latest version, clearing cache and regenerating mautic assets. 

But, the auto-play error is still there. After we fill the form in the 5th second of the video, it isn't resuming from the 6th second, it is starting from 1 second which isn't as expected. 

Yes, I did try in incognito, its the same.

**Comment by kmanojkumar** [comment] 2019-04-11 11:12
Can you please check it @npracht?

**Comment by kmanojkumar** [comment] 2019-04-16 06:30
Hey @npracht, can you please check and close this issue?

> But, the auto-play error is still there. After we fill the form in the 5th second of the video, it isn't resuming from the 6th second, it is starting from 1 second which isn't as expected.

**Comment by npracht** [comment] 2019-04-16 07:14
Hi,

I don't have the issue on my side. I'm not a developer i cannot investigate deeper.

**Comment by kmanojkumar** [comment] 2019-04-19 08:13
Hi,

Thanks @npracht. 

**Explaining the issue further again:**
After filling the form displayed on the video, the video has to resume playing from where it has paused. This feature isn't working when using an mp4 video as a source, but working when using a youtube video as a source. 

I have created a **demo-test** page on Wordpress where the auto-play after filling the form is working for video links with source as youtube, but not for direct mp4 source links. 

Please check: [https://pws.peerxp.com/demo-test/](https://pws.peerxp.com/demo-test/)

Also, I noticed that form CSS doesn't properly load when the source link is youtube, but with mp4 as src, it loads perfectly!

**Comment by npracht** [comment] 2020-08-04 20:02
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment] 2020-09-04 09:29
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-09-04 09:29 UTC
Labels: bug, triage-mautic-3
