### ISSUE TITLE
Segment filters not working

### ISSUE THREAD

**Issue by igisho** [mautic/mautic#2720] opened 2016-10-11 14:53 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

Hi,
 the segment filters should be fixed in v2.2.0 ?  I have two filters set in specific segment. Both of them are looking into custom contact field specifically they are looking if they are empty, but they are not filtering correctly (they did not filter anything, based on those all contacts should have those custom fields empty which is not true). I have cron jobs set correctly,
Coustom fields are data type: (1 x text and 1x number)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.0 |
| PHP version | 7.0.1 |
### Steps to reproduce:
1.  create custom fields (text and number)
2. create segment
3. add filters custom field1 (condition: empty) (operator: and) custom field2 (condition: empty)
4. run cronjob
### Log errors:

no erros in logs at all. Manually run cron job runs with no complication also.

**Comment by escopecz** [comment] 2016-10-12 13:29
I cannot reproduce. It's working for me. Are you sure there are no errors in the logs? (https://mautic.org/docs/en/tips/troubleshooting.html) There was an error when working with contacts in 2.2.0. Lets wait if you'll have this issue with 2.2.1 too and if so, we'll dig deeper. Let us know after you upgrade please.

**Comment by igisho** [comment] 2016-10-13 07:06
I double check logs for any error, but with no luck. Ok, i will definitely let you know.

**Comment by igisho** [comment] 2016-10-13 09:52
Even filtering by email is not working correctly for me. There is aprox. 3300000 contact in that mautic installation. Could it be related? Could it be mysql querry execution time setting related?

**Comment by igisho** [comment] 2016-10-18 12:02
after update to lastest version i can confirm that segment filter condition "empty" is still not working correctly for me. I created 2 new test segments with only one filter set 1. had a condition set to "not empty" and 2. had a condition set to "empty". after segments update 1. contained 82738 contacts and 2. contained 3371113 contacts which is basically all contacts.

**Comment by mqueme** [comment] 2017-03-08 12:35
I am also testing this and I am not able to reproduce using latest version 2.7.0.  I have created two custom fields of types text and number. I have added two filters using these two fields both set to empty, operator AND.

I have 47 contacts, one of them has one of these fields populated. my segment is built with 46 contacts. Then I updated 6 contacts with either one or both fields populated and after rebuilding segment I am now left with 40 contacts.

Can you please confirm that this still persists in V2.7.0?

**Comment by mqueme** [comment] 2017-03-28 10:13
I am closing this, as it is working in version 2.7.0

**Closed by mqueme** 2017-03-28 10:13 UTC
Labels: Bug, P0, Pending Feedback

**Comment by buckhornmktg** [comment] 2017-05-04 21:36
This seems to be a problem in 2.8. Please re-open.

**Comment by copyhold** [comment] 2017-05-13 19:28
I have the same issue. Custom TEXT field. Segment can't find contacts. Segment with core fields works OK

**Comment by rorymadden** [comment] 2017-09-14 09:14
I can confirm that naming a filed source means that it does not work in segment filters. Once I created a new field with a different alias it worked correctly.

**Comment by Woolgoose** [comment] 2019-07-18 12:59
I saw that the empty filter is not working on the tag field. I wanted to find contacts that have no tags and the segment tags > empty turned out 0 though some contacts clearly had no tags. I repeated the test with some other fields and they worked. So in my case the tag field seems to have that issue other fields may have it or not (I did not test all of them).

**Comment by suriite8** [comment] 2019-07-26 07:03
@Woolgoose  Yes, it seems to bug in mautic. I too tried with all possibilities. segment filter is not working on tag field. Please report it as bug.
