### ISSUE TITLE
Create Contact Page 

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#12222] opened 2023-04-14 11:58 UTC
### Mautic Version

5.0.x series

### PHP version

8.0

### What happened?

This is how the create contact page looks like

![image](https://user-images.githubusercontent.com/12627658/232037430-af2129dc-eba0-4c72-8596-21b874a61fb9.png)

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LordRembo** [comment] 2023-04-14 13:33
For that free floating `Primary company` row, I can see it's being printed in `app/bundles/LeadBundle/Resources/views/Lead/form.html.twig` as part of `{{ form_end(form) }}`
Haven't been able to find where it is originally created and put into that function variable/function so far.

**Comment by LordRembo** [comment] 2023-04-21 12:48
I took another look at this but can't figure out where that row & field are actually being processed. It looks like it either was injected in the `form` variable by accident, or some html got messed up when merging this field into whatever list `form` is holding. Eg. a div not closed, that usually causes the whole row to render outside the original container.
But that's about the limit of what I can see.

**Comment by mollux** [comment] 2023-10-31 05:14
@mabumusa1 @LordRembo 

this looks like the same issue as #12628, which may be fixed with #12848

**Comment by LordRembo** [comment] 2023-10-31 16:30
Yeah, that's the same issue. We should mark this as closed

**Comment by LordRembo** [comment] 2023-10-31 16:32
@mabumusa1 Can you mark this as solved?

**Comment by mollux** [comment] 2023-10-31 21:04
duplicate of #12628, which was fixed and merged

**Closed as not planned by mollux** 2023-10-31 21:04 UTC
Labels: bug, regression
