### ISSUE TITLE
Code-editing in Email-breaks the rendering

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10388] opened 2021-08-31 08:55 UTC
### Mautic Version

4.0.x series

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

Extremely frustrating. Just try to use any of the e-mail templates with graphics/ buttons and try to change the URL it points to. By the way there's no UI element to modify the URL the button points to. Once you try you'll se items disappear and all the s** goes wild.

### How can we reproduce this issue?

Step 1: Extremely frustrating. Just try to use any of the e-mail templates with graphics/ buttons and try to change the URL it points to.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by rafalsk** [comment] 2021-08-31 09:50
Interestingly once the template is saved and opened-up again everything looks good.

**Comment by RCheesley** [comment] 2021-08-31 18:47
Hey there,

Firstly, we do not appreciate expletives in issue reporting, or indeed anywhere in our community. Assuming you will have read my other message regarding refreshing your memory with the Code of Conduct, and that one warning is sufficient, I hope that you will also edit this post to be more polite and helpful.

It seems that you have addressed the issue (by saving the email and opening it again) so that's great. Here it is not clear enough to enable us to triage the issue effectively so we will require some further information:

> Just try to use any of the e-mail templates with graphics/ buttons

Please be specific, which templates are you referring to here? Please use the actual name of the template, and whether it was an existing email you were editing from prior to updating to Mautic 4, or something new you were creating from scratch.

> try to change the URL it points to.

In the GrapesJS builder there are configuration settings in the right hand pane for blocks like buttons.  This is where you enter the URL, configure the settings (e.g. size of the button, radius and so forth). Simply click the paintbrush at the top of the right hand pane, as demonstrated here:

https://youtu.be/OUVdqmf2I5M

This allows you to edit the configuration, in this case the link.  In the section underneath the href settings in the accordion menu, you will be able to change the dimensions, the typography and the decorations.

I believe based on this, that your issue may be relating to a lack of familiarity with the user interface, rather than a bug with Mautic. If that is the case, please close the issue. If you would like to provide more detail about the strange behaviour you experienced, perhaps you could give more information and a screencast to demonstrate to us clearly what the issue was. Thanks!

**Comment by rafalsk** [comment] 2021-09-01 06:58
> Hey there,
> 
> Firstly, we do not appreciate expletives in issue reporting, or indeed anywhere in our community. Assuming you will have read my other message regarding refreshing your memory with the Code of Conduct, and that one warning is sufficient, I hope that you will also edit this post to be more polite and helpful.

Relax Chesley, would you..
> 
> It seems that you have addressed the issue (by saving the email and opening it again) so that's great. Here it is not clear enough to enable us to triage the issue effectively so we will require some further information:
> 
After saving and re-opening the rendering is fine, yeah.
> > Just try to use any of the e-mail templates with graphics/ buttons
> 
> Please be specific, which templates are you referring to here? Please use the actual name of the template, and whether it was an existing email you were editing from prior to updating to Mautic 4, or something new you were creating from scratch.
> 
Any from the available ones, nothing custom was created, you may give 'Paprika' a try, that's the one I've tried myself.
> > try to change the URL it points to.
> 
> In the GrapesJS builder there are configuration settings in the right hand pane for blocks like buttons. This is where you enter the URL, configure the settings (e.g. size of the button, radius and so forth). Simply click the paintbrush at the top of the right hand pane, as demonstrated here:
> 
> https://youtu.be/OUVdqmf2I5M
> 
> This allows you to edit the configuration, in this case the link. In the section underneath the href settings in the accordion menu, you will be able to change the dimensions, the typography and the decorations.
> 
Now that's great! Thanks for pointing out the magic brush button; it works and most importantly editing items through it doesn't break the rendering.
> I believe based on this, that your issue may be relating to a lack of familiarity with the user interface, rather than a bug with Mautic. If that is the case, please close the issue. If you would like to provide more detail about the strange behaviour you experienced, perhaps you could give more information and a screencast to demonstrate to us clearly what the issue was. Thanks!

Nope Cheesley; the fact that I got to know about the magic brush button doesn't change the fact that by-hand code editing breaks the rendering. (trust me I would close it was it the case, closed a couple of issues here by myself already).

**Comment by RCheesley** [comment] 2021-09-01 17:48
Hi there,

There is no need to tell me to relax, as the Project Lead it is my responsibility to set the tone for the community.  That includes ​ensuring that the Mautic Community is welcoming to all, and the Code of Conduct is followed by all. 

Several of your posts have been rude and  in some cases insulting, behaviour which is not welcome here. That needs to change, if you wish to continue interacting in the community.

Regarding your issue, ​please can you share a screencast showing us the problem you are experiencing with 'by-hand code editing' so that we can better understand this issue. I am not able to reproduce this when going to code mode, so we need to understand what precisely the issue is so that we can troubleshoot.

Thanks

**Closed as completed** 2021-09-09 14:49 UTC
Labels: bug, pending-feedback, mautic-4, builder-grapesjs
