### ISSUE TITLE
RSS Newsletter

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#1888] opened 2016-06-17 12:40 UTC
I think have an RSS Newsletter option in Mautic will help. The idea is to connect Mautic to an RSS to send an email to the Mautic lead list.

Do you get the idea?

**Comment by escopecz** [comment] 2016-06-17 12:41
@ninjoan isn't this duplicate of https://github.com/mautic/mautic/issues/1116 ?

**Comment by ninjoan** [comment] 2016-06-17 12:43
Tru my bad first time using GitHub im not very familiar with the search stuff here.

**Closed** 2016-06-17 12:44 UTC
