### ISSUE TITLE
ELFinder tries to create weird paths and exits with error 500

### ISSUE THREAD

**Issue by nickveenhof** [mautic/mautic#9132] opened 2020-08-26 14:12 UTC
## Bug Description

When trying to open elfinder I get an error 500. The detail of the error is

[2020-08-26 16:05:52] mautic.CRITICAL: Uncaught PHP Exception League\Flysystem\Exception: "Impossible to create the root directory "/var/www/mautic/dev/docroot/app/..//var/www/mautic/dev/docroot/app/../sites/default/files/images". mkdir(): File exists" at /var/www/mautic/dev/vendor/league/flysystem/src/Adapter/Local.php line 112 {"exception":"[object] (League\\Flysystem\\Exception(code: 0): Impossible to create the root directory \"/var/www/mautic/dev/docroot/app/..//var/www/mautic/dev/docroot/app/../sites/default/files/images\". mkdir(): File exists at /var/www/mautic/dev/vendor/league/flysystem/src/Adapter/Local.php:112)"} []

Custom configs:
    'mailer_spool_path' => '%kernel.root_dir%/../sites/default/files/spool',
    'log_path' => '%kernel.root_dir%/../sites/default/files/logs',
    'image_path' => '%kernel.root_dir%/../sites/default/files/images',
    'upload_dir' => '%kernel.root_dir%/../sites/default/files/mautic-files',
    'form_upload_dir' => '%kernel.root_dir%/../sites/default/files/mautic-files/form',
    'report_temp_dir' => '%kernel.root_dir%/../sites/default/files/mautic-files/temp',
    'cache_path' => '%kernel.root_dir%/../sites/default/files/cache',
    'tmp_path' => '%kernel.root_dir%/../sites/default/files/tmp',

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | 

### Steps to reproduce
1. See configs above
2. Browse to https://mymauticurl.localhost/elfinder
 
### Log errors
See description

**Comment by RCheesley** [comment] 2020-10-08 17:39
Thanks for raising this @nickveenhof - just out of interest, why browse to the URL? Does this happen if you're using the file upload tool within the UI?

I'm not able to reproduce this on my local 3.1 instance, maybe it's something relating to your file paths?

**Comment by RCheesley** [comment] 2020-12-10 22:29
@nickveenhof is this still an issue with 3.2.1 please? If so we'll need to do a bit more debugging, if not we'll close the issue.

**Comment by nickveenhof** [comment] 2020-12-11 10:03
Actually it isn't really an ELFinder problem. The problem was here: 

'image_path' => '%kernel.root_dir%/../sites/default/files/images',
'image_path' => 'sites/default/files/images',

All other path configurations expect full path, image_path is relative to the domain it seems. That wasn't very clear and caused all this sideeffects

**Comment by nickveenhof** [comment] 2020-12-11 10:03
Feel free to close this if you think this should not be solved or followed-up

**Comment by RCheesley** [comment] 2020-12-14 19:01
> Feel free to close this if you think this should not be solved or followed-up

It should probably form part of the configuration documentation, I think? Thanks for flagging it up, pinging @mautic/education-team for info. Will close this issue down.

**Closed as completed by RCheesley** 2020-12-14 19:01 UTC
Labels: T1, bug, pending-feedback, file-uploader
