### ISSUE TITLE
UI/Bug - Dropdown list on Landing page editor + Contact page edition

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1945] opened 2016-07-04 10:15 UTC
## Description
The drop down list is cut by the screen.
##### Landing page builder
![capture d ecran 2016-04-15 a 16 38 14](https://cloud.githubusercontent.com/assets/14075239/16557546/d75c3942-41e0-11e6-855e-a787e164bc42.png)
##### Contact edition page
![capture d ecran 2016-07-04 a 12 13 46](https://cloud.githubusercontent.com/assets/14075239/16557547/d75d0b1a-41e0-11e6-8466-10d4e9dd11c3.png)

## Steps to reproduce
1. Create and edit a landing page
2. Edit a contact

**Comment by escopecz** [comment] 2016-07-05 08:01
Duplicate of https://github.com/mautic/mautic/issues/1706

**Closed by escopecz** 2016-07-05 08:01 UTC
