### ISSUE TITLE
Use Amazon AWS SDK to send emails through SES instead of SMTP (for Amazon SES)

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#2754] opened 2016-10-14 10:11 UTC
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
Currently Mautic only transmits Amazon SES emails through `Other SMTP Service` rather than the actual AWS/SES API. This is very problematic as email sending with Amazon SES through SMTP transmits only a handful of emails per minute (i.e. 5 emails per minute), effectively rendering it useless for any medium to large sized campaigns.

Using the Amazon AWS/SES SDK would allow for transferring the allowed maximum per second (i.e. 100 emails per second) This is an essential feature/enhancement since Amazon SES by far provides the cheapest email solution as compared to other email services (as low as 5% relative to other services).

Official Amazon AWS PHP SDK: https://github.com/aws/aws-sdk-php

**Comment by magician7** [comment] 2016-10-14 10:20
+1

**Comment by escopecz** [comment] 2016-10-14 10:40
Seems like a duplicate of https://github.com/mautic/mautic/issues/1740

**Closed** 2016-10-14 11:07 UTC

**Comment by iadj** [comment] 2016-10-14 11:20
@escopecz That thread handles various features in depth. Considering the priority this enhancement has over i.e. bounce/complaint webhooks I felt like it should deserve its own thread.

**Comment by ineptikus** [comment] 2017-04-06 04:28
+1

**Comment by alexander-friedrich** [comment] 2018-11-05 17:24
+1
