### ISSUE TITLE
Your bug title goes here!

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#10447] opened 2021-09-16 17:03 UTC
### Mautic Version

3.3.x series

### PHP version

7.3.30

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello,

When I an email with a <table> tag that contains a <div> tag that itself contains a <a> tag that I save my email and I come back into editing the <div> suitcase disappears.
This means that I can no longer edit the link in the email except to go through the HTML code which is not very convenient.

How to avoid this problem?

Best regards,
Pierre

### How can we reproduce this issue?

Step 1: create an email with a layout containing <table> tables.
Step 2: embed a text field (this creates a <div> in the code) 
Step 3: add text to the field
Step 4: put all the text as a link
Step 5: save the email and exit
Step 6: go back to editing the email
Step 7: try to edit the text content (the one that is a link) and notice that it is not possible to remove any characters

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment] 2021-11-09 13:12
Duplicate of https://github.com/mautic/mautic/issues/10446

**Closed as completed by npracht** 2021-11-09 13:12 UTC
Labels: bug, duplicate, builder-grapesjs
