### ISSUE TITLE
Allow zero as response to mandatory field

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3792] opened 2017-03-31 11:56 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y

## Description:
If you make a number field in a form mandatory, the answer zero will cause the "mandatory fields". For example, how many dogs, cats or small animals do you have? 

If I say 2 cats, 1 dog and 0 small animals, the 0 small animals triggers the warning and the form will not submit.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net hosting

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment] 2019-04-25 10:05
Couldn't reproduce. Must be fixed now.

**Closed by npracht** 2019-04-25 10:05 UTC
Labels: Backlog, Bug
