### ISSUE TITLE
Categorization of Smart Lists and email notification preferences

### ISSUE THREAD

**Issue by RegisScaggiante** [mautic/mautic#1268] opened 2015-12-22 13:10 UTC
For me it is important to better organize the lists. Just as there are categories of mail, types of landing pages and categories of forms, I think we could have categories lists. This would facilitate the organization. 

Allow the lead change your email notification preferences is very important in my opinion. Enabling or disabling certain types of information. Categories of Smart Lists could be created and the lead could choose to which category he would like to receive information.

**Comment by escopecz** [comment] 2016-01-06 13:36
I think this issue is duplicate of https://github.com/mautic/mautic/issues/822.

**Closed by escopecz** 2016-01-06 13:36 UTC
