### ISSUE TITLE
Edit email builder: Browsing for an image results in spinner of death

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#1507] opened 2016-03-07 20:33 UTC
After updating to 1.3.. Trying to browse for an image results in the spinner of death. Chrome dev tools says:

```
https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=307&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)

https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=323&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)

https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=290&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)

https://mautic.example.com/app/bundles/CoreBundle/Assets/js/libraries/ckedi…lemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=760&type=Images 
Failed to load resource: the server responded with a status of 500 (OK)
```

**Comment by escopecz** [comment] 2016-03-08 09:05
Seems like duplicate of https://github.com/mautic/mautic/issues/1499

**Closed by escopecz** 2016-03-08 09:05 UTC
