### ISSUE TITLE
Segment contacts added with filter are not removed when filter is removed

### ISSUE THREAD

**Issue by Psymbionic** [mautic/mautic#7679] opened 2019-07-10 17:57 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hey there,

I have a segment with contacts manually added as well as some added from filters. I’m having an issue where removing those filters does not remove the contacts from the segment. This is reproducible for me with new segments. It seems that this is a [known issue](https://github.com/mautic/mautic/issues/4095), and although it is shown as fixed, myself (and [others](https://github.com/mautic/mautic/issues/5123)) still seem to be having this problem.

Output when manually mautic:segments:update after creating new filter in test segment:

```
Rebuilding contacts for segment 23
3079 total contact(s) to be added in batches of 300
3079/3079 [============================] 100%
0 total contact(s) to be removed in batches of 300
3079 contact(s) affected
```

_After removing the filter:_

```
Rebuilding contacts for segment 23
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected
```

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version |  7.2.19
| Browser | 

### Steps to reproduce
1. Create new test segment
2. Create filter in test segment which adds contacts to segment
3. Manually run app/console mautic:segments:update
4. See that output adds new contacts to segment
5. Remove filter from test segment
6. Again, manually run app/console mautic:segments:update
7. See that no contacts are removed
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2019-07-26 07:55
@escopecz what do you think of that ? What was the initial purpose of the feature ? It is maybe just a lack of documentation ?

**Comment by escopecz** [comment] 2019-07-26 08:05
I may not understand the issue properly. In the description are mentioned manually added contacts. In the steps to reproduce I don't see adding them. Are they important? They should stick with the segment no matter what filter it has until a user manually removes them.

**Comment by npracht** [comment] 2019-07-26 08:08
@Psymbionic please share feedbacks clearer.

**Comment by Psymbionic** [comment] 2019-07-26 08:18
The problem does not have to do with manually added contacts. The problem is that contacts added by a filter are not removed when the filter is deleted from a segment. Regardless of whether or not contacts were manually added to a segment, the issue is still the same. Removing a filter does not remove contacts from the segment in my install.

My real world issue is that I have a segment which has a lot of manually added contacts. I tried to add a filter which I later wanted to remove, but the contacts added from the filter stay even after removing the filter. This makes the segment useless to me now. If I did not need the segment/manually added contacts, I could just recreate the segment with the _only_ the filters I wanted for said segment, but the addition of manually added contacts nullifies that workaround.

**Comment by MusTon79** [comment] 2019-10-31 16:40
I have the same problem. I also downgraded to php version 5.6
and Mautic 2.14.2 but the problem is always present.

**Comment by Psymbionic** [comment] 2019-10-31 23:28
@MusTon79 any chance you're on a Bitnami installation?

**Comment by MusTon79** [comment] 2019-10-31 23:36
No im running it on my own server and manually installation

**Comment by MusTon79** [comment] 2019-10-31 23:37
@Psymbionic No im running it on my own server and manually installation

**Comment by RCheesley** [comment] 2020-07-07 12:27
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment] 2020-07-29 10:14
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-29 10:14 UTC
Labels: bug, pending-feedback, triage-mautic-3
