### ISSUE TITLE
Stray Character in Landing Page

### ISSUE THREAD

**Issue by steve3g** [mautic/mautic#9192] opened 2020-09-12 15:42 UTC
## Bug Description
here is a stray digit ("1") showing up on landing pages built from a variety of templates. This digit appears to be inserted on request processing and does not appear to be related to the template. I used the raw LP1-Subscribe template on two cases - first unchanged from the distribution and second having commented out the twig call to outputScripts('bodyOpen'). The digit moves in the HTML, but remains (see HTML page sources attached). These and other templates worked fine in version 2, but stopped working after the upgrade. I am getting no log errors.

| Q   | A
| --- | ---
Mautic 3.1
PHP 7.3.22
Chrome 85.0.4183.102

### Steps to reproduce
1. Produce a new landing page using LP-1 or Fresh template (same whether template is edited or not)
2. Render the resulting landing page
 
### Log errors
NONE

HTML SOURCE NO CHANGE TO TEMPLATE
[view-source_https___stevekretsch.com_mautic_page_preview_26.html.txt](https://github.com/mautic/mautic/files/5212904/view-source_https___stevekretsch.com_mautic_page_preview_26.html.txt)

HTML SOURCE COMMENT OUT outputScripts('bodyOpen')
[view-source_https___stevekretsch.com_mautic_page_preview_27.html.txt](https://github.com/mautic/mautic/files/5212906/view-source_https___stevekretsch.com_mautic_page_preview_27.html.txt)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-09-19 19:41
Hi @steve3g you might have to help me out a bit here with trying to reproduce your bug report.

1. What theme are you referring to when you say _I used the raw LP1-Subscribe template_?
2. Which Fresh theme are you referring to?

Can you share a screenshot of where the stray digit is showing up?

**Comment by steve3g** [comment] 2020-09-25 12:30
@RCheesley, thanks for the reply. The LP1-Subscribe template is one I found on the Internet and modified for my own use, but I suffered the same problem with the original download. However, I also have the same issue with all the Fresh templates, The attached screen shots are from "Fresh - Center". To further test, I also have the problem using a blank template (see screenshot).
![Whole Page](https://user-images.githubusercontent.com/54789352/94267263-4a074380-ff09-11ea-841e-de9e407e49b5.PNG)
![Highlighted](https://user-images.githubusercontent.com/54789352/94267280-4f648e00-ff09-11ea-8bfb-4074dda72333.PNG)
![Screenshot 2020-09-25 082851](https://user-images.githubusercontent.com/54789352/94267309-5c817d00-ff09-11ea-9267-5bfbaa57f68c.png)

**Comment by RCheesley** [comment] 2020-09-28 09:20
Are you using any browser tools that block ads at all? Does this happen in an incognito browser?

**Comment by steve3g** [comment] 2020-09-28 18:38
I have not installed any blocking tools and I do not think my settings would interfere. I have now tested on Chrome with / without incognito, Edge with / without private browsing and Safari on an iPhone with / without private setting.

**Comment by colourfulowl** [comment] 2020-09-29 09:08
Any chance you can upload the HTML files without all of the line item details. It makes it incredibly difficult to see what's what.

**Comment by steve3g** [comment] 2020-09-29 10:49
I have attached the HTML from the mautic database. I assume this is what you want

I used the "Blank" template to keep the file as simple as possible. For your reference, I also included a screenshot of the rendering of this form in Chrome.

<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths responsejs " style=""><head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>{pagetitle}</title>
            <meta name="description" content="{pagemetadescription}" />

                                      </head>
    <body class="ui-sortable">
        <div data-section-wrapper="1">
    <center>
        <table data-section="1" style="width: 600;" width="600" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        <div data-slot-container="1" style="min-height: 30px" class="ui-sortable">
                            <div data-slot="text">
                                <br />
                                <h2>Hello there!</h2>
                                <br />
                                We haven't heard from you for a while...
                                <br />
                                <br />
                                <br />
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </center>
</div>
</body></html>

![Screenshot 2020-09-29 064031](https://user-images.githubusercontent.com/54789352/94549135-bfcc2180-021f-11eb-86f0-d4a0ce5b0de6.png)

**Comment by colourfulowl** [comment] 2020-09-29 10:58
Hi @steve3g is this only happening in the preview, or is it happening when you publish the page as well?

I have the exact same set up as you and I can't reproduce this issue. There does seem to be some content missing from your code mode template.

`<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>{pagetitle}</title>
            <meta name="description" content="{pagemetadescription}">
                                
<script data-source="mautic">var mauticForms={"0" ***** REMOVED FOR SERCURITY - This will be filled with all of your form IDs ****** };</script>


    </head>
    <body>
        
        <div data-section-wrapper="1">
    <center>
        <table data-section="1" style="width: 600;" width="600" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        <div data-slot-container="1" style="min-height: 30px">
                            <div data-slot="text">
                                <br>
                                <h2>Hello there!</h2>
                                <br>
                                We haven't heard from you for a while...
                                <br>
                                <br>
                                <br>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </center>
</div>
        
    </body>
</html>`

**Comment by colourfulowl** [comment] 2020-09-29 10:59
Hi @steve3g is this only happening in the preview, or is it happening when you publish the page as well?

I have the exact same set up as you and I can't reproduce this issue. There does seem to be some content missing from your code mode template. That might just be Github though. Can you try it with the below? Github really doesn't like me putting code here. 

[mautic-code-mode-error.log](https://github.com/mautic/mautic/files/5298437/mautic-code-mode-error.log)

**Comment by steve3g** [comment] 2020-09-29 11:15
Both preview and publish render identically.

**Comment by steve3g** [comment] 2020-10-15 21:05
I had no luck with your code. Same result. I installed a fresh version of mautic to see if a file might have been corrupted, but there are no differences. Only logical missing files (e.g. image files). I can only think it is somehow in the database, but I have no idea where to look. I am happy to reinstall, but I would like to keep my contacts and segments. I would love to also keep my emails and landing pages, but I am willing to sacrifice these if I can get the landing pages to work properly.

**Comment by steve3g** [comment] 2020-10-28 21:56
@colourfulowl please see my comments above

**Comment by npracht** [comment] 2020-11-10 12:18
closing in favor of https://github.com/mautic/mautic/issues/9352

**Closed as completed by npracht** 2020-11-10 12:18 UTC
Labels: pending-feedback
