### ISSUE TITLE
Extra message on delete

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#27] opened 2015-01-28 20:48 UTC
Create multiple categories
Select one to delete
You get two messages
First message is useful 
eg 1 category is deleted

Second message is not needed and is confusing
No page category with an id of 5 was found!

Of course it is not found you just deleted it

**Comment by alanhartless** [comment] 2015-01-28 22:46
Hey Brian,

I'm afraid I can't reproduce this one either.  Curious, are you by chance on a slow ISP? I'm wondering if ajax requests are getting crossed.  I've added some js code in recent commits to help prevent this.

Thanks,
Alan

**Comment by brianteeman** [comment] 2015-01-28 22:52
Grrh I cant replicate this one any more either - it was definitely
happening repeatedly as I was selecting the error text in the message box
in order to post it

On 28 January 2015 at 22:46, Alan Hartless <notifications@github.com> wrote:

> Hey Brian,
>
> I'm afraid I can't reproduce this one either. Curious, are you by chance
> on a slow ISP? I'm wondering if ajax requests are getting crossed. I've
> added some js code in recent commits to help prevent this.
>
> Thanks,
> Alan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/27#issuecomment-71933016>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment] 2015-01-28 23:02
Replicated it and recorded it in action

https://www.dropbox.com/s/uumag8mccgssdmc/mauticdelete.mp4?dl=0

**Comment by alanhartless** [comment] 2015-01-29 01:28
I was able to reproduce this by double clicking the confirmation modal's delete button.  Is it possible that your mouse or trackpad is initiating a double click?

**Comment by brianteeman** [comment] 2015-01-29 03:10
3am here

Unlikely but that's unlikely. Also it makes no sense technicaly as an
explanation.

**Comment by alanhartless** [comment] 2015-01-29 04:03
Just had to ask as that seems to be the behavior exhibited. :) I'm adding some catches to help prevent duplicate executions but of course that doesn't fix whatever is causing it nor would it fix the checkbox issues. I'll keep at it though. 

I pulled an all nighter last night and tonight doesn't look much better :-) Sleep well!

**Comment by alanhartless** [comment] 2015-02-05 02:37
Closing this as the referenced commit should prevent this behavior from occurring.

**Closed by alanhartless** 2015-02-05 02:37 UTC
