### ISSUE TITLE
"There is no column with name 'email' on table 'companies'" when creating a custom company field

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#9980] opened 2021-05-08 12:34 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When adding a custom field for companies, a flash message shows up:

![image](https://user-images.githubusercontent.com/17739158/117539099-54de9680-b009-11eb-8eef-019f03e75963.png)

This doesn't prevent the user from creating a custom company field though. At this point I'm not sure if it has any other side-effects.

| Q   | A
| --- | ---
| Mautic version | 4.0-beta (`features` branch)
| PHP version | 7.4
| Browser | Microsoft Edge Chromium

### Steps to reproduce
1. Open the Mautic dashboard
2. Click the gear icon in the top right corner
3. Open Custom Fields
4. Create a new custom field. Make sure you set "Object" to "Company"
5. The flash message shows up
 
### Log errors

N/A

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by shinde-rahul** [comment] 2021-05-16 03:46
Unable to reproduce the same with the following.
P | |Version
-|-|-
PHP version|: |7.4
Mautic|:| `features` (branch)  [367d2bdebc]

**Comment by RCheesley** [comment] 2021-08-23 17:08
Closing due to report of not being able to reproduce as above.

**Closed as completed by RCheesley** 2021-08-23 17:08 UTC
Labels: bug, mautic-4
