### ISSUE TITLE
FR: Campaign Decision Contact Field Equals Empty / Not Equals Empty

### ISSUE THREAD

**Issue by medianicus** [mautic/mautic#2765] opened 2016-10-15 01:37 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |
| Enhancement? | Yes

## Description:
I'm trying to implement a campaign that moves a contacts stage based on whether the contact field 'Email' contains data or not. I can't see a way to do this.

It would be very useful if "empty" and "not empty" could be added to the condition based on a contact field value and condition based on a form field value. This is already available in the filters for Segments.

**Comment by escopecz** [comment] 2016-10-17 07:32
This seems like a duplicate of https://github.com/mautic/mautic/issues/1424

**Closed by escopecz** 2016-10-17 07:32 UTC
