### ISSUE TITLE
Unable to load Dashboard and Campaigns are not working

### ISSUE THREAD

**Issue by genasia** [mautic/mautic#6808] opened 2018-11-03 09:28 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
From last month I started getting the issues with Mautic 2.14.* 

1. While User Logs in instead of Dashboard the 500 Internal Server Error comes. 
2. Campaigns are not working at all which use to be working fine earlier. 

All these issues have started appearing after I upgraded the Mautic version. 

| Q   | A
| --- | ---
| Mautic version | Latest Version 2.14.*
| PHP version | PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
| Browser | Safari, Chrome

### Steps to reproduce
1. When User logs in Dashaboard doesnt load it shows 500 Internal Server Error 
 
### Log errors
[2018-11-03 14:23:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN trq_mautcompanies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source_id = ce.id AND s.source = "campaign.event" LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, "2018-10-04 00:00:00", "2018-11-03 14:23:53"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN trq_mautcompanies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source_id = ce.id AND s.source = \"campaign.event\" LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, \"2018-10-04 00:00:00\", \"2018-11-03 14:23:53\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

[2018-11-03 14:24:09] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN trq_mautcompanies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source_id = ce.id AND s.source = "campaign.event" LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, "2018-10-04 00:00:00", "2018-11-03 14:24:09"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN trq_mautcompanies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source_id = ce.id AND s.source = \"campaign.event\" LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, \"2018-10-04 00:00:00\", \"2018-11-03 14:24:09\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

[2018-11-03 14:26:32] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN trq_mautcompanies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source_id = ce.id AND s.source = "campaign.event" LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, "2018-10-04 00:00:00", "2018-11-03 14:26:32"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN trq_mautcompanies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source_id = ce.id AND s.source = \"campaign.event\" LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, \"2018-10-04 00:00:00\", \"2018-11-03 14:26:32\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

[2018-11-03 14:31:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, s.date_sent, s.date_read, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON ph.source = "email" and ph.source_id = s.email_id and ph.lead_id = s.lead_id LEFT JOIN trq_mautcompanies_leads cl ON (s.lead_id = cl.lead_id) AND (cl.is_primary = 1) LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source = "campaign.event" and s.source_id = ce.id LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, "2018-10-04 00:00:00", "2018-11-03 14:31:53"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, s.date_sent, s.date_read, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM trq_mautemail_stats s LEFT JOIN trq_mautemails e ON s.email_id = e.id LEFT JOIN trq_mautpage_hits ph ON ph.source = \"email\" and ph.source_id = s.email_id and ph.lead_id = s.lead_id LEFT JOIN trq_mautcompanies_leads cl ON (s.lead_id = cl.lead_id) AND (cl.is_primary = 1) LEFT JOIN trq_mautcompanies c ON cl.company_id = c.id LEFT JOIN trq_mautcampaign_events ce ON s.source = \"campaign.event\" and s.source_id = ce.id LEFT JOIN trq_mautlead_lists ll ON s.list_id = ll.id LEFT JOIN trq_mautcampaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, \"2018-10-04 00:00:00\", \"2018-11-03 14:31:53\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dmpm.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/dmpm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2018-11-05 08:01
Duplicate of https://github.com/mautic/mautic/issues/4021

BTW this can be prevented with database configuration as the error message suggests.

**Closed by escopecz** 2018-11-05 08:01 UTC
