### ISSUE TITLE
Unable to create Dynamic Content in Mautic 3.0.0

### ISSUE THREAD

**Issue by FrancisSamo** [mautic/mautic#8416] opened 2020-02-09 19:41 UTC
## Bug Description
I just installed Mautic 3.0.0 Alpha to see if a problem where I assume has to do with Chrome 80 new SameSite Cookie got solved. But it seems evan worse in Mautic 3.0.0! However in order to keep it simple and not to mix the problems, I only go to the problem I had in Mautic 3.0.0. The actual problem can be explained very quickly and easily: **I'm not able to create dynamic content - at all!**
When clicking "New" it loads but nothing happens. 

![Mautic Issue - Unable to create Dynamic Content](https://user-images.githubusercontent.com/5165185/74108576-00d1d180-4b7c-11ea-8aca-58aec4bdb419.gif)

| Q   | A
| --- | ---
| Mautic version | 3.0.0 Alpha
| PHP version | 7.2
| Browser |  Chrome/Firefox

### Steps to reproduce
1. Go to Components/Dynamic Content
2. Click on "+New" 
 
### Log errors
There are no errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-02-09 22:39
Did you see any errors in your Chrome developer console?

**Comment by FrancisSamo** [comment] 2020-02-09 22:52
@RCheesley Just checked and indeed I get the following errors:
libraries.js?v56eb8c05:766  500 (Internal Server Error)
send	@	libraries.js?v56eb8c05:766
ajax	@	libraries.js?v56eb8c05:744
Mautic.loadContent	@	app.js?v56eb8c05:41
Mautic.ajaxifyLink	@	app.js?v56eb8c05:99
(anonymous)	@	app.js?v56eb8c05:84
dispatch	@	libraries.js?v56eb8c05:465
elemData.handle	@	libraries.js?v56eb8c05:451

Unchecked runtime.lastError: The message port closed before a response was received.

![Mautic 3 0 0 Dynamic Content Issue](https://user-images.githubusercontent.com/5165185/74111738-36d07f00-4b97-11ea-9a67-8f87111cae61.gif)

**Comment by lukassykora** [comment] 2020-02-26 13:31
Hi @FrancisSamo, I can not reproduce it. Please, could you share your log file? It should be inside var/logs/.

**Comment by FrancisSamo** [comment] 2020-02-27 12:17
@lukassykora Here's the log file from that day: 
[mautic_prod-2020-02-09.php.txt](https://github.com/mautic/mautic/files/4261526/mautic_prod-2020-02-09.php.txt)
☝️ I changed the file type from php to txt in order to upload it here.

**Comment by lukassykora** [comment] 2020-02-28 08:59
I am sorry but I cannot reproduce it. It seems that it could be related to https://github.com/mautic/mautic/commit/7f5dc063a346f584bc2484a72a74b68bd7b376d7, because it tries to call key 'type' which does not exist anymore (it was renamed to entry_type).  @FrancisSamo please, are you sure that you cleared your cache?

**Comment by alanhartless** [comment] 2020-03-03 20:33
I'm closing this as resolved in the latest M3 beta.

**Closed by alanhartless** 2020-03-03 20:33 UTC
Labels: Bug, Mautic 3, Regression
