### ISSUE TITLE
SNS Bounce messages not parsed properly

### ISSUE THREAD

**Issue by magnific0** [mautic/mautic#4306] opened 2017-06-27 09:36 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | NO
| Enhancement? |  NO

## Description:
Bounce message from SNS are not being processed. "MessageHelper" fail to parse the JSON in the body correctly. Leading to lead not identified and message just end up being read, but lead data not altered. 

The cause of this is unexpected newline characters inside the JSON. These are placed after exactly 1000 characters of string. Whether this is Amazon or the receiving smtp server or imap, I don't know.

I have fixed this behaviour for my Mautic (see below). It detects the signature delimiter (--) instead of  newline. Not sure if up to coding standards. I'd be happy to issue a PR.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.20-1~dotdeb+8.1
| Postfix | 2.11.3-1+deb8u2
| Dovecot | 2.2.13-12~deb8u3

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

     PHP Notice:  Trying to get property of non-object in /var/www/mautic/app/bundles/EmailBundle/Helper/MessageHelper.php on line 167

Because the message array is basically empty.

### Fix:

```
MessageHelper.php
...
        $this->logger->debug("Analyzing message to {$message->toString}");
        // If message from Amazon SNS collect bounces and complaints
        if ($message->fromAddress == 'no-reply@sns.amazonaws.com') {
            list($message_json, $message_sign ) = preg_split("/\r?\n\r?\n--\r?\n/", $message->textPlain, 2 );
            $message = json_decode(preg_replace("/\r?\n/", "", $message_json), true);
...
```

**Comment by skynet** [comment] 2017-06-29 03:32
Are you talking about the SNS from SES?

**Comment by magnific0** [comment] 2017-06-29 09:39
Yes

**Comment by skynet** [comment] 2017-06-30 00:58
How does that work? Can you actually see the bounces on the Mautic dashboard?

**Comment by magnific0** [comment] 2017-06-30 06:43
No bounces show up. They just fail to process at all. The inbox with bounces gets read, but nothing happens. 

I did some more reading up why the line breaks are inserted at 1000 characters and sure enough this is no coincidence. Apparently this is in accordance to RFC 2822:
https://tools.ietf.org/html/rfc2822#section-2.1.1

**Comment by skynet** [comment] 2017-07-01 02:50
We definitely need to be able to process bounces with Mautic. is there a suppression list somewhere? Or, how does Mautic know not to send email to the same address that bounced.

**Comment by magnific0** [comment] 2017-07-01 08:47
It already does that, see the docs. This isssue is about a bug in that system.

**Comment by npracht** [comment] 2019-10-04 13:37
Duplicate of https://github.com/mautic/mautic/issues/3655

**Closed by npracht** 2019-10-04 13:37 UTC
Labels: Bug
