### ISSUE TITLE
Amazon SES bounce reporting error?

### ISSUE THREAD

**Issue by httpoz** [mautic/mautic#3173] opened 2017-01-04 09:42 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
We are testing out Mautic and we have integrated it with Amazon SES. Once we send out the email Amazon hits the callback url, and the responses are processed appropriately with one omission - the `email_id` is not saved to the `lead_donotcontact` table in the `channel_id` column. This means there is no bounce reporting etc which is a challenge for us.

looking at `app\bundles\EmailBundle\Swiftmailer\Transport\AmazonTransport.php`:
```php
// Data structure that Mautic expects to be returned from this callback
        $rows = [
            DoNotContact::BOUNCED => [
                'hashIds' => [],
                'emails'  => [],
            ],
            DoNotContact::UNSUBSCRIBED => [
                'hashIds' => [],
                'emails'  => [],
            ],
        ];
```

but the row sent back on a bounced email:
```php
$rows[DoNotContact::BOUNCED]['emails'][$bouncedRecipient['emailAddress']] = $bouncedRecipient['diagnosticCode'];
```

there is no hashId there, would that be the culprit or did I miss a step in my setup?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5
| PHP version | 7.0

### Steps to reproduce:
1. Send email via SES
2. check `lead_donotcontact` table and all details will be saved except the `channel_id`
 
### Log errors: 
No errors.
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by wittwerch** [comment] 2017-02-09 10:57
Yes that is true. The reason this information is missing in Mautic is because it is not available on Amazon SES. The email received from Mautic does not contain that information, so we can't read that out the the bounced email.
Afaik swiftmailer has no option to add additional headers to the email. I think that something that will be possible once we send emails using the Amazon SES API.

**Comment by httpoz** [comment] 2017-02-09 11:44
I may also not have been clear, so we send out emails via SES but we receive them via SNS. SNS hits `http://mautic.url/mailer/amazon/callback` and the AmazonTransport Class reads the data. So I recycled some functions Mautic uses to get a hashId from the mail->source value in the returned object. I will paste the code below but I would to note that, it only worked for the first email (whichever one SNS sent back first) out of the 3 bounces we test with.


```php

<?php

/*
 * @copyright   2014 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace Mautic\EmailBundle\Swiftmailer\Transport;

use Joomla\Http\Exception\UnexpectedResponseException;
use Joomla\Http\Http;
use Mautic\CoreBundle\Factory\MauticFactory;
use Mautic\LeadBundle\Entity\DoNotContact;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\HttpException;

/**
 * Class AmazonTransport.
 */
class AmazonTransport extends \Swift_SmtpTransport implements InterfaceCallbackTransport
{
    private $httpClient;

    /**
     * {@inheritdoc}
     */
    public function __construct($host, Http $httpClient)
    {
        parent::__construct($host, 587, 'tls');
        $this->setAuthMode('login');
        $this->httpClient = $httpClient;
    }

    /**
     * Returns a "transport" string to match the URL path /mailer/{transport}/callback.
     *
     * @return mixed
     */
    public function getCallbackPath()
    {
        return 'amazon';
    }

    /**
     * Handle bounces & complaints from Amazon.
     *
     * @param Request $request
     * @param MauticFactory $factory
     *
     * @return mixed
     */
    public function handleCallbackResponse(Request $request, MauticFactory $factory)
    {
        $translator = $factory->getTranslator();
        $logger = $factory->getLogger();
        $logger->debug('Receiving webhook from Amazon');

        $payload = json_decode($request->getContent(), true);

        return $this->processJsonPayload($payload, $logger, $translator);
    }

    /**
     * Process json request from Amazon SES.
     *
     * http://docs.aws.amazon.com/ses/latest/DeveloperGuide/best-practices-bounces-complaints.html
     *
     * @param array $payload from Amazon SES
     * @param $logger
     * @param $translator
     *
     * @return array with bounced and unsubscribed email addresses
     */
    public function processJsonPayload(array $payload, $logger, $translator)
    {

        // Data structure that Mautic expects to be returned from this callback
        $rows = [
            DoNotContact::BOUNCED => [
                'hashIds' => [],
                'emails' => [],
            ],
            DoNotContact::UNSUBSCRIBED => [
                'hashIds' => [],
                'emails' => [],
            ],
        ];

        if (!isset($payload['Type'])) {
            throw new HttpException(400, "Key 'Type' not found in payload ");
        }

        if ($payload['Type'] == 'SubscriptionConfirmation') {
            // Confirm Amazon SNS subscription by calling back the SubscribeURL from the playload
            $requestFailed = false;
            try {
                $response = $this->httpClient->get($payload['SubscribeURL']);
                if ($response->code == 200) {
                    $logger->info('Callback to SubscribeURL from Amazon SNS successfully');
                } else {
                    $requestFailed = true;
                    $reason = 'HTTP Code ' . $response->code . ', ' . $response->body;
                }
            } catch (UnexpectedResponseException $e) {
                $requestFailed = true;
                $reason = $e->getMessage();
            }

            if ($requestFailed) {
                $logger->error('Callback to SubscribeURL from Amazon SNS failed, reason: ' . $reason);
            }
        } elseif ($payload['Type'] == 'Notification') {
            $message = json_decode($payload['Message'], true);

            // only deal with hard bounces
            if ($message['notificationType'] == 'Bounce' && $message['bounce']['bounceType'] == 'Permanent') {
                // Get bounced recipients in an array
                $bouncedRecipients = $message['bounce']['bouncedRecipients'];
                foreach ($bouncedRecipients as $bouncedRecipient) {
                    $rows[DoNotContact::BOUNCED]['emails'][$bouncedRecipient['emailAddress']] = $bouncedRecipient['diagnosticCode'];
                    $logger->debug("Mark email '" . $bouncedRecipient['emailAddress'] . "' as bounced, reason: " . $bouncedRecipient['diagnosticCode']);
                }
                $hashId = $this->retrieveHashId($message['mail']['source']);
                $rows[DoNotContact::BOUNCED]['hashIds'][$hashId] = $message['bounce']['bouncedRecipients'][0]['diagnosticCode'];
            } // unsubscribe customer that complain about spam at their mail provider
            elseif ($message['notificationType'] == 'Complaint') {
                foreach ($message['complaint']['complainedRecipients'] as $complainedRecipient) {
                    $reason = null;
                    if (isset($message['complaint']['complaintFeedbackType'])) {
                        // http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#complaint-object
                        switch ($message['complaint']['complaintFeedbackType']) {
                            case 'abuse':
                                $reason = $translator->trans('mautic.email.complaint.reason.abuse');
                                break;
                            case 'fraud':
                                $reason = $translator->trans('mautic.email.complaint.reason.fraud');
                                break;
                            case 'virus':
                                $reason = $translator->trans('mautic.email.complaint.reason.virus');
                                break;
                        }
                    }

                    if ($reason == null) {
                        $reason = $translator->trans('mautic.email.complaint.reason.unkown');
                    }

                    $hashId = $this->retrieveHashId($message['mail']['source']);
                    $rows[DoNotContact::UNSUBSCRIBED]['hashIds'][$hashId] = $reason;
                    $rows[DoNotContact::UNSUBSCRIBED]['emails'][$complainedRecipient['emailAddress']] = $reason;
                    $logger->debug("Unsubscribe email '" . $complainedRecipient['emailAddress'] . "'");
                }
            }
        }

        return $rows;
    }

    public function retrieveHashId($toEmail){
        if (preg_match('#^(.*?)\+(.*?)@(.*?)$#', $toEmail, $parts)) {
            if (strstr($parts[2], '_')) {
                // Has an ID hash so use it to find the lead
                $words = explode('_', $parts[2]);
                $hashId = array_pop($words);
                return $hashId;
            }
        }

        return null;
    }
}


```

**Comment by dbhurley** [comment] 2017-11-28 11:19
Is this still an issue in 2.11?

**Comment by mojsilo** [comment] 2017-12-22 12:09
This is still the issue in 2.12. We use SNS to send bounces to mautic webhook and it works well. All bounced contacts have been updated nicely.

But in the report section there's no bounces.

**Comment by Cappobianco** [comment] 2018-02-20 11:11
Hi, @mojsilo
I write here from Brazil.
I caught enough to create this callback URL for my mautic.
I am running version 2.12.1 updated by direct command lines on the server.
PHP 7.0. I use Ubuntu 16.04 + EasyEngine + NGINX

I'm with my instance on amazon. EC2

Anyway ... I do not know what happens.

In my log's error folder there is nothing!

Can you give me some basic information on how you set up that call back URL on amazon SNS with webhook?

**Comment by jaulaobligatoria** [comment] 2018-03-19 15:46
Hi everyone,

I still have this issue. ¿Any news about it?

**Comment by jonasstinkens** [comment] 2018-04-03 08:33
Hi,

Same issue over here. Also when I create a report with bounces, it's always 0.

**Comment by amagdy3** [comment] 2018-08-20 11:12
I'm still getting this issue!

**Comment by DalbertHab** [comment] 2019-04-17 11:50
Hi everyone,

we have the problems to. It seems that the SNS Notification doesn't contain any information to identity the origin mail.

We added a custom header for every mail named **X-Message-ID** and enabled the SNS Notification with headers in SES. Now the payload contains the original headers of the mail in the mail object of the payload. 

In the file EmailBundle/Swiftmailer/Transport/Amazon.php add the following code above the line (145) `if ($message['notificationType'] == 'Bounce' && $message['bounce']['bounceType'] == 'Permanent') {`

```php
$channelId = null;
if (isset($message['mail'])) {
	$mail = $message['mail'];
	if (count($mail['headers'])) {
		 $headers = array_filter($mail['headers'], function ($header) {
			 return strtolower($header['name']) === 'x-message-id';
		});
	}
	if (count($headers)) {
		$header = current($headers);
		$channelId = (int)$header['value'];
	}
}
```

and change the line (149) `$this->transportCallback->addFailureByAddress($bouncedRecipient['emailAddress'], $bouncedRecipient['diagnosticCode']);` to 
```php
if (strlen($channelId)) {
	$this->transportCallback->addFailureByAddress($bouncedRecipient['emailAddress'], $bouncedRecipient['diagnosticCode'], DoNotContact::BOUNCED, $channelId);
} else {
	$this->transportCallback->addFailureByAddress($bouncedRecipient['emailAddress'], $bouncedRecipient['diagnosticCode']);
}
```

Hope this helps someone.

**Comment by ianmartorell** [comment] 2019-06-12 07:12
I was having the same issue, and @DalbertHab's solution fixed it for me. Bounces from Amazon SNS are now correctly updating the bounced contact.

However, looking through the `AmazonTransport` code I see there is no handling of soft bounces. Is that right? Only hard bounces are processed, and soft bounces are **ignored**?

**Comment by npracht** [comment] 2019-10-04 13:38
duplicate of https://github.com/mautic/mautic/issues/3655

**Closed by npracht** 2019-10-04 13:38 UTC
Labels: Backlog, Bug
