### ISSUE TITLE
Mautic Email Builder and Landing Page Builder not working

### ISSUE THREAD

**Issue by cardened** [mautic/mautic#9181] opened 2020-09-09 17:10 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | Mautic 3.1.0-0 
| PHP version | 7.2.33
| Browser | 

### Steps to reproduce
1. Build / Edit an Email 
2. go to BUILDER

- Once in the builder you see the right hand panel, but the left side is empty and I cannot edit anything (for both Email and Landing Page Builder the same happens.  
-  The builder does not close. 
- The Preview of email does not close 

Here is a video screen recording of the problem and how I get it.  
--> https://www.loom.com/share/4871191fccc74bb1bf84b4aafb5f1d49

### Log errors
[2020-09-09 10:41:56] mautic.NOTICE: PHP Notice - Undefined index: path - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/ExceptionController.php - at line 120 {"request":"[object] (Symfony\\Component\\HttpFoundation\\Request: CONNECT ip.ws.126.net:443 HTTP/1.1\r\nHost:           ip.ws.126.net:443\r\nUser-Agent:     Go-http-client/1.1\r\nX-Php-Ob-Level: 1\r\n\r\n)","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FlattenException: {})","logger":null,"class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","currentContent":"","layout":"Error","code":404,"anonymous":true,"baseTemplate":"MauticCoreBundle:Default:slim.html.php","templatePage":false,"template":"MauticCoreBundle:Error:404.html.php","templating":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\DelegatingEngine: {})","statusText":"Not Found","url":"ip.ws.126.net:443","urlParts":{"host":"ip.ws.126.net","port":443}} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment] 2020-09-10 08:02
Hello, did you try to regenerate assets and/or apply [this PR](https://github.com/mautic/mautic/pull/9143) ?
I think your issue is a duplicate of https://github.com/mautic/mautic/issues/9127

**Closed as completed by npracht** 2020-09-10 08:02 UTC
Labels: duplicate, builder-legacy
