### ISSUE TITLE
Feature Request: Set 'Do no Contact' status via api

### ISSUE THREAD

**Issue by SikhNerd** [mautic/mautic#1826] opened 2016-06-03 18:29 UTC
## Description

Basically what it says on the tin, would like an API call that sets a contact to 'Do Not Contact'.

Currently because this does not exist, I'm forced to manage this state externally from mautic, and just delete users entirely - losing valuable data in the process.

**Comment by ipso** [comment] 2016-07-24 21:24
Looks to be a duplicate of #770

**Closed** 2016-08-01 05:18 UTC
