### ISSUE TITLE
Email test connection does not work in mautic 2.6 

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#3410] opened 2017-02-12 08:51 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When trying to test connection under Configuration -> Email Settings you get an endless loop circle animation and nothing happens. This is tested with Amazon SES settings and Other SMTP Server with same result.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 7.0.15

### Steps to reproduce:
1. go to Configuration -> Email Settings
2. test connection
 
### Log errors: 

[2017-02-12 08:30:32] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file ./public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []
[2017-02-12 08:31:41] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file ./public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []
[2017-02-12 08:33:02] mautic.NOTICE: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_mode AS trigger_mode_10, c0_.decision_path AS decision_path_11, c0_.temp_id AS temp_id_12, c0_.channel AS channel_13, c0_.channel_id AS channel_id_14 FROM campaign_events c0_ WHERE c0_.campaign_id = 2 AND c0_.parent_id IS NULL AND c0_.event_type <> 'decision'':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.channel' in 'field list' (uncaught exception) at ./public/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 while running console command `mautic:campaigns:trigger` [] []
[2017-02-12 08:34:48] mautic.ERROR: PHP Error - Call to undefined method setApiKey - in file ./public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []
[2017-02-12 08:36:03] mautic.NOTICE: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_mode AS trigger_mode_10, c0_.decision_path AS decision_path_11, c0_.temp_id AS temp_id_12, c0_.channel AS channel_13, c0_.channel_id AS channel_id_14 FROM campaign_events c0_ WHERE c0_.campaign_id = 2 AND c0_.parent_id IS NULL AND c0_.event_type <> 'decision'':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.channel' in 'field list' (uncaught exception) at ./public/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 while running console command `mautic:campaigns:trigger` [] []

**Comment by gino1234** [comment] 2017-02-12 09:30
I have same problem with Sendgrid...

**Comment by seuaCoder** [comment] 2017-02-12 09:50
Same problem here on a fresh install, the POST request lead to an error 500, i have the same error in the log 

 mautic.ERROR: PHP Error - Call to undefined method setApiKey

**Comment by Clobbe** [comment] 2017-02-12 13:04
I get the same error with Mailjet.

Also tried with SMTP, but without success =(

**Comment by escopecz** [comment] 2017-02-12 14:36
This seems to be duplicate of https://github.com/mautic/mautic/issues/3383

**Closed by escopecz** 2017-02-12 14:36 UTC
