### ISSUE TITLE
Contact Name - IP Address

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#6911] opened 2018-11-21 15:48 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Okay, this is a really weird one guys. After updating to mautic v2.14.2 I've started to see a whole collection of contacts being added to the contacts (identified) list even if the only information known is there IP. This isn't the same as anonymous users. when i toggle into the anonymous list, it's completely different list to the ones in the main (identified) list.

| Q   | A
| --- | ---
| Mautic version | v2.14.2
| PHP version | 7.0.30
| Browser | Chome

### Steps to reproduce
1. visit /s/contacts and look at the default list.
2. Compare to anonymous list by press the anonymous toggle button in the top right.
 
### Log errors
- None. The only error is the this one, produced for me being signed in and viewing the site.

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /opt/bitnami/apps/mautic/htdocs/app/bundles/LeadBundle/Helper/ContactRequestHelper.php line 173 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /opt/bitnami/apps/mautic/htdocs/app/bundles/LeadBundle/Helper/ContactRequestHelper.php:173)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2018-11-26 08:54
I cannot replicate. Can you provide a screenshot of the list view and also the detail page of a problematic contact, the table of all field values?

**Comment by escopecz** [comment] 2018-11-26 09:07
Actually, this seems like duplicate of https://github.com/mautic/mautic/issues/6837. Let's continue the discussion there.

**Closed by escopecz** 2018-11-26 09:07 UTC
Labels: Pending Feedback
