### ISSUE TITLE
Guys, please help! Not able to create segment, campaign and etc.

### ISSUE THREAD

**Issue by vsaifee** [mautic/mautic#7208] opened 2019-02-04 07:17 UTC
Hi Guys,

I am facing issue like not able to create segment, campaign and etc. I created a campaign and segment both. First I created segment and add contact through filters and likewise, but once saved, no contacts are appearing. Shows as 0 contacts in segment. Similarly not able to start campaign or send email individually. Please help.

Below is error while trying to send out email directly from contact:

Failed to send to XXXX@XX.com: Expected response code 250 but got code "554", with message "554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 16.55847:8C120000, 17.43559:0000000094000000000000000000000000000000, 20.52176:140F2C860C0010100300170E, 20.50032:140F2C867C1710100A005780, 0.35180:E7020000, 255.23226:0A008440, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A000000, 16.55847:80000000, 17.43559:00000000A0010000000000001B00000000000000, 20.52176:140F2C860C00101000030000, 20.50032:140F2C867C17101005030000, 0.35180:0A000712, 255.23226:0A030000, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:14030000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:0A000580, 0.38698:00000000, 0.37692:00000000, 0.44092:31334600, 0.41232:00000000, 0.60208:31343933, 0.37136:42000100, 0.34608:00000000, 0.55056:31413744, 0.42768:30003A4D, 0.56112:00000000, 0.52807:32343343, 4.33016:DC040000, 7.40748:010000000000010B32324239, 7.57132:000000000000000000000000, 1.63016:32000000, 4.39640:DC040000, 8.45434:989D616839AE9A4D818E3404267F260832000000, 5.10786:0000000031352E32302E313538302E3031323A4D4531505230314D42313630343A62316263633764342D656233632D343266632D386465322D35376339633462303066376200000000000000, 255.1750:0A006680, 255.31418:80030000, 0.22753:0A000180, 255.21817:DC040000, 4.60547:DC040000, 0.21966:8A030000, 4.30158:DC040000 [Hostname=ME1PR01MB1604.ausprd01.prod.outlook.com] "

**Comment by npracht** [comment] 2019-02-04 09:54
You obviously have a configuration issue on your email configuration side. Please check on that side and discuss with community in Slack.

As far as it this is not a bug, i'll close this issue.

**Closed by npracht** 2019-02-04 09:54 UTC
