### ISSUE TITLE
RSS-Newsletter

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#1307] opened 2016-01-02 06:46 UTC
Hello, all
This is a feature request for an RSS-to-Mail-Option. Sadly enough I am no programmer, so let me ask this here. 
I search for an option to send mails to a List, once something happened on a defined RSS-Feed. The Mail then should contain text and/or the entire RSS-Article. I see this Feature on CleverReach, ActiveCampaign and MailChimp, in the WordPress Plugin MailPoet it is in the “automatic Newsletter”-Section.
Maybe this can be a new Start-Point in the Workflow-Builder with a new type of “active” E-Mail, that contains just some blocks of the RSS-Feed. Or so….
Thanks a lot
OLAF

**Comment by alanhartless** [comment] 2016-01-02 08:21
Thanks for posting this! I believe it's a duplicate of #1116 so I'm going to mark this as a duplicate and close it in favor of the existing feature request.

Thanks!
Alan

**Closed by alanhartless** 2016-01-02 08:21 UTC
Labels: Duplicate

**Comment by OlafDammann** [comment] 2016-01-02 09:44
Ops! Sorry for not checking :( And THX for referencing
