### ISSUE TITLE
Mautic-form.js is not defined after update to 2.7.1

### ISSUE THREAD

**Issue by heanfig** [mautic/mautic#3848] opened 2017-04-12 14:16 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | N
| Enhancement? | N

## Description:
After updating mautic to 2.7.1 display error "Mautic form.js can not find"

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6.30

### Steps to reproduce:
1. install mautic in a folder like http://#IP#/~mautic/
2. create form
3. embed form in a landing page or website

create and embed the form on a website

Duplicate appears

![captura de pantalla 2017-04-12 a las 8 29 37 a m](https://cloud.githubusercontent.com/assets/4906962/24962069/615f5b6c-1f60-11e7-8c2f-22da390a7f7c.png)
 
Error

![captura de pantalla 2017-04-12 a las 9 14 39 a m](https://cloud.githubusercontent.com/assets/4906962/24962116/817d309a-1f60-11e7-9621-66bef30b9d53.png)

**Comment by escopecz** [comment] 2017-04-12 14:21
It must be some problem in your server, because if you check the file in 2.7.1, it is there:

https://github.com/mautic/mautic/blob/2.7.1/media/js/mautic-form.js

So either the file is removed on your server for some reason or your server is throwing 404 for some other reason. Let us know what was it when you figure it out, please.

**Comment by heanfig** [comment] 2017-04-12 14:27
That's true, but the folder appears duplicated when the getUrl method is called

The following folder of the virgulilla appears duplicated

before 
http://98.142.105.122/~inboundfeliciden/media/js/mautic-form.js 

after
http://98.142.105.122/~inboundfeliciden/~inboundfeliciden/media/js/mautic-form.js 

What problem could have had the server knowing that the only thing that was done in this was the update of the mautic,

![captura de pantalla 2017-04-12 a las 8 29 37 a m](https://cloud.githubusercontent.com/assets/4906962/24962664/2eb39b18-1f62-11e7-8fd6-787bb8a5147e.png)

**Comment by escopecz** [comment] 2017-04-12 14:30
Ah, it seems to be related to https://github.com/mautic/mautic/issues/3709

**Comment by RCheesley** [comment] 2017-05-03 14:21
Confirmed, same problem!

**Comment by escopecz** [comment] 2017-05-24 20:06
Fixed in https://github.com/mautic/mautic/pull/4148

**Comment by FabianTe** [comment] 2017-07-06 09:32
I can confirm this issue. Is it already fixed?

The first request for ```mautic-form.js``` results in a 301 redirect:

![image](https://user-images.githubusercontent.com/7669818/27904767-12d6318e-623e-11e7-84a8-61ddbaa72266.png)

The second request fails because it contains a dublicate:

![image](https://user-images.githubusercontent.com/7669818/27904794-3038d556-623e-11e7-9bb9-2046e95c821d.png)

When I remove the duplicate (```https://......./mautic/media/js/mautic-form.js```) I am able to get the file.

Every other request for media files such as images in the web page work.

Mautic version: 2.8.2
Site URL configuration: ```https://subdomain.domain.com/mautic/index.php```
Mautic installation path: ```var/www/html/mautic/``` contains ```app``` and so on

**Closed** 2017-07-28 09:07 UTC
Labels: Bug, P1, Ready To Test
