### ISSUE TITLE
Separate form values from labels

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#954] opened 2015-09-29 06:56 UTC
It would be awesome if we could separate the form values from the labels for select list, radio buttons, et cetera.
This way we can display friendly options to the user without showing them our internal mautic field values.
Currently this can only be achieved by editing the form output.

**Comment by alanhartless** [comment] 2015-10-21 05:22
This is a duplicate of #761.

**Closed by alanhartless** 2015-10-21 05:22 UTC
Labels: Duplicate
