### ISSUE TITLE
Errors when deleting contacts through a campaign action

### ISSUE THREAD

**Issue by mdorchain** [mautic/mautic#3696] opened 2017-03-16 17:16 UTC
**Bug report**

## Description:
Errors when deleting contacts through a campaign action

Mautic version: 2.7.0
PHP version: 5.6

### Steps to reproduce:
1. Set a campaign with a "Delete Contact" action
2. Trigger the campaign from the console
 
### Console errors: 
unserialize(): Error at offset 148 of 205 bytes in /home/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58  
                 
PHP Notice:  unserialize(): Error at offset 157 of 197 bytes in /home/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58                   
  1400/22133 [=>--------------------------]   6%

PHP Notice:  unserialize(): Error at offset 100 of 124 bytes in /home/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/T
ypes/ArrayType.php on line 58                   
                                                                                                                                                                   
PHP Notice:  unserialize(): Error at offset 96 of 100 bytes in /home/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58  

In /app/log/ 

mautic.NOTICE: PHP Notice - unserialize(): Error at offset 95 of 109 bytes - in file /home/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []

**Comment by escopecz** [comment] 2017-03-17 07:49
This error is not caused by the delete action. It's caused by corrupted contact data. Usually because of social monitoring data with emoticons in them. I'll close this issue in favour of https://github.com/mautic/mautic/issues/2597

**Closed by escopecz** 2017-03-17 07:49 UTC
