### ISSUE TITLE
Merge MTC IDs if email already exist when adding a contact with API

### ISSUE THREAD

**Issue by sujaypawar** [mautic/mautic#3442] opened 2017-02-14 14:43 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

We've integrated forms on our website with Mautic using API method.

Tracking is seamless for the submission from one device. However, when the form is submitted from other device, Mautic API unfortunately doesn't merge MTC IDs even though email address of the contacts is same. The new device is still tracked independently with it's own MTC ID as unknown contact.

This problem is not present if we use Mautic forms (instead of API that we're using now) to create a contact. It automatically merges MTC ID if the email is same.

Is there a workaround for this? Or this is a bug in API that could be fixed / imrpoved?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-02-14 14:53
This seems to be a duplicate of https://github.com/mautic/mautic/issues/3108

**Closed by escopecz** 2017-02-14 14:53 UTC

**Comment by sujaypawar** [comment] 2017-02-14 15:00
Opps, I forgot - there was an open issue for this already. Sorry!
