### ISSUE TITLE
(Enhancement) Email A/B testing : After the variant wins, show action "Merge difference into parent/control"

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7350] opened 2019-03-26 12:08 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:

This enhancement allows to not have to manually copy/paste the variant subject line, or content or whatever was tested into the parent, to simplify adoption of the test learnings and iterate safely.

It would simply copy the the variant details as the parent. So we keep improving the original email who ID may be in use in campaigns, form submit actions, API emails etc...

**Comment by RCheesley** [comment] 2020-07-16 18:55
#1752 should address this issue, I think @albanleandri ?

**Comment by RCheesley** [comment] 2020-10-08 19:02
Closing as a duplicate of #1752

**Closed by RCheesley** 2020-10-08 19:02 UTC
Labels: builders, enhancement, pending-feedback
