### ISSUE TITLE
Mautic is recording contacts in future date/time

### ISSUE THREAD

**Issue by LucasFarley** [mautic/mautic#4709] opened 2017-08-23 01:00 UTC
What type of report is this:
Error during the record of visits ( Anonymous contacts ).
| Q  | A
| ---| ---
| Bug report? | 
Mautic is showing the visit record the future.  But the correct is showing the lead in my time zone.

| Feature request? | 
| Enhancement? | 

## Description:

My time zone is America, São Paulo. But if i have a visit during the night mautic is showing the visit record the future.  But the correct is showing the lead in my time zone. 

Se more details in the screens attached.

<img width="1080" alt="screen" src="https://user-images.githubusercontent.com/22159940/29593993-42cc4124-8784-11e7-9bcf-889fa7d3fa79.png">

<img width="1033" alt="screen02" src="https://user-images.githubusercontent.com/22159940/29594080-ec373e30-8784-11e7-974f-bd259614b59d.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| PHP version | PHP Version 5.6.31-1~ubuntu16.04.1+deb.sury.org+1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-08-23 06:35
> My time zone is America, São Paulo

Is that configured in Mautic configuration or your profile configuration or both? If you change it, does it have any effect on the issue?

**Comment by LucasFarley** [comment] 2017-08-23 11:45
Mautic configuration and profile configuration has the same timezone.

 

Both are configured with time zone America, São Paulo.

**Comment by LucasFarley** [comment] 2017-08-23 13:01
Is it necessary to check some configuration in server(host) date/time configuration?

**Comment by escopecz** [comment] 2017-08-23 13:02
Server should be set to UTC. Is it?

**Comment by LucasFarley** [comment] 2017-08-23 13:16
See the configuration in attached screen.

**Comment by escopecz** [comment] 2017-08-23 13:17
GitHub doesn't display email attachments.

**Comment by LucasFarley** [comment] 2017-08-23 13:19
See the server configuration.

> root@m:~# timedatectl
>       Local time: Wed 2017-08-23 13:14:18 UTC
>   Universal time: Wed 2017-08-23 13:14:18 UTC
>         RTC time: Wed 2017-08-23 13:14:18
>        Time zone: Etc/UTC (UTC, +0000)
>  Network time on: yes
> NTP synchronized: yes

 RTC in local TZ: no

**Comment by luizeof** [comment] 2017-08-23 19:16
@LucasFarley This article can help you in pt-BR: https://powertic.com/mautic/configurando-data-e-hora-do-servidor-linux/

**Comment by LucasFarley** [comment] 2017-08-23 22:56
@luizeof, thanks so much, but the item was tagged as a bug.
Beside that, I can't apply the procedure in the post because the system must work according to timezone configured in Mautic Configuration and Profile Configuration.
Other point,  the problem is happening only in some features of Mautic Tool. 
The tool must have the same way to work all user view.

**Comment by justinfortes** [comment] 2018-01-19 18:15
@LucasFarley is this still an issue after 4733 was closed?

**Comment by LucasFarley** [comment] 2018-01-19 18:26
@escopecz, I did not see any solution on #4733.  In fact in the [close] description of #4733, you redirect to this ticket.

Right?

**Comment by escopecz** [comment] 2018-01-20 07:42
@LucasFarley I don't see any mention of me saying that #4733 is a solution. I closed it as a duplicate of this issue.

**Comment by dbhurley** [comment] 2018-01-20 07:45
That was @justinfortes fault. He assumed the issue was resolved because it was closed. He didn't realize the reason for closure (duplicate)

**Comment by afonseca08** [comment] 2018-02-10 07:53
Hi, I'm new to Mautic and just ran into this issue on my fresh install. I described the issue thinking visitors tracking was broken, in #5550. However, upon some more searching around I found the visits were indeed being recorded to the page_hits database table. The aha moment was looking at the date_hit field and seeing all the dates in the future!

> SELECT `date_hit` FROM `page_hits` WHERE 1 ORDER BY `date_hit` ASC
> 
> date_hit
> 2018-02-10 04:46:24
> 2018-02-10 04:53:12
> 2018-02-10 04:53:30
> 2018-02-10 04:53:33
> 2018-02-10 05:23:48
> 2018-02-10 05:26:34
> 2018-02-10 05:27:01
> 2018-02-10 05:31:06
> 2018-02-10 05:37:21
> 2018-02-10 05:37:23
> 2018-02-10 05:44:17
> 2018-02-10 05:47:14
> 2018-02-10 05:47:30
> 2018-02-10 05:47:37
> 2018-02-10 05:47:39
> 2018-02-10 05:48:07
> 2018-02-10 05:48:17
> 2018-02-10 05:48:23
> 2018-02-10 05:50:56
> 2018-02-10 05:51:19
> 2018-02-10 05:52:28
> 2018-02-10 06:39:05
> 2018-02-10 06:42:43
> 2018-02-10 06:42:54
> 2018-02-10 06:55:49


My server and Mautic profile are both set to my local time zone, America/Los_Angeles. 

> [~]# timedatectl
>       Local time: Fri 2018-02-09 23:52:37 PST
>  Universal time: Sat 2018-02-10 07:52:37 UTC
>         RTC time: n/a
>        Time zone: America/Los_Angeles (PST, -0800)

However, the date_hit field in the table is recording entries in UTC time zone. Therefore, when I look at the Visits widget in the Dashboard, it was empty because that UTC time of the visits falls on the next day which is not selectable in the date picker.

I was able to confirm the tracking is indeed working in the UI by changing my Mautic profile to UTC temporarily which allowed me to select the next day and there are all the visits.

I hope this issue can be addressed soon otherwise the data shown is off by variable amounts of time for users based on their time offset to UTC.

**Comment by dsukhin** [comment] 2018-02-11 07:22
Having the same issue on my fresh install as well. My server is on local timezone and configuration is set to local as well. However, until I set my profile timezone (this is another setting from from the config timezone) to local, contact pages were showing hits in UTC. But even with all the settings, the dashboard is still showing in UTC.

**Comment by afonseca08** [comment] 2018-06-12 00:42
Just an update with 2.13.1, this is still happening despite server, Mautic config, and Mautic user profile all matching the same local time zone (America/Los Angeles). In order to see data accurately in any of the Mautic charts (dashboard, e-mails sent, etc) I have to set the end date in the range to +1 day in the future.

**Comment by npracht** [comment] 2020-07-17 08:18
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment] 2020-08-04 20:07
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-08-04 20:07 UTC
Labels: bug, triage-mautic-3
