### ISSUE TITLE
Search / filter not functioning (on form results page)

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3933] opened 2017-04-27 12:28 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When viewing form results there is a filter box at the top of each column which you can type free text into, presumably this functions then like a search box. This seems not be be working at all.

When searching for any item (twitter handle, contact ID etc) I briefly see the "working" indication (animation at top of page indicates so) then the page appears the same as before and the item in filter box is gone (possibly the page just refreshes)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net
| PHP version | 

### Steps to reproduce:
1. go to forms and click to see the form results
2. use any of the filter boxes to search for an item you know is in the list (for example the one at the top of the list)
3. the search does not work
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-05-02 07:58
I can replicate

**Comment by aviboy2006** [comment] 2017-06-22 12:19
I am able to reproduce it. in Mautic\FormBundle\Controller\ResultController -> indexAction 
  if ($this->request->getMethod() == 'POST') {

            $this->setListFilters();
        }
this call suppose to pass $name variable means form name paramter from url - 
http://localhost/mautic-lead/s/forms/results/4?tmpl=list&name=formresult.4&filterby=r.disposition&value=FCB&mauticUserLastActive=1&mauticLastNotificationId=
not passing. i checked in Mautic\CoreBundle\Controller\CommonController.php  for 

protected function setListFilters($name = null)
    {
 if (null === $name) { 
            $name = InputHelper::clean($this->request->query->get('name'));
        }
        $name = 'mautic.'.$name;
}  

function is not passing $name still not going to if case to get from request parameters. because without passing $name its giving me value before if case. Because of result mapping is not working. if we pass "formresult.4" from request parameter it will work properly

**Comment by escopecz** [comment] 2017-06-22 12:21
@aviboy2006 would you be able to send a pull request with the modifications you suggest?

**Comment by aviboy2006** [comment] 2017-06-22 12:29
Can i give to master or staging ? can i fork it ?

**Comment by escopecz** [comment] 2017-06-22 12:31
Yep, fork it and use staging branch as the base for your new branch.

**Comment by aviboy2006** [comment] 2017-06-22 12:44
https://github.com/mautic/mautic/pull/4281  kindly review it.

**Closed** 2017-07-03 07:32 UTC
Labels: Bug, Ready To Test

**Comment by gingerling** [comment] 2017-07-14 13:35
Bonza! thanks for the fix folks, that's awesome :) :)
