### ISSUE TITLE
UI problem when configuring DWC actions in passive cases

### ISSUE THREAD

**Issue by insetic** [mautic/mautic#2680] opened 2016-10-08 10:45 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
There is a but that persists in version 2.2.0 although it was apparently solved with #2423 
The bug is described in #2396 

![image](https://cloud.githubusercontent.com/assets/20638806/19212593/d28d5530-8d54-11e6-91f9-bdc06f9c489a.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.0
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2016-10-10 10:52
I re-opened https://github.com/mautic/mautic/issues/2396 before I noticed you created a new issue. I'll close this issue as duplicate of re-opened issue since that one holds more history.

**Closed by escopecz** 2016-10-10 10:52 UTC
