### ISSUE TITLE
Feature request - Report Filters based on tags and lists

### ISSUE THREAD

**Issue by gpassarelli** [mautic/mautic#1063] opened 2015-10-26 23:02 UTC
It would be nice if we could create a report for the Lead data source with a filter for the following options:
* Tags (include & exclude)
* Lists (Belongs & Doesn't belong)

**Comment by alanhartless** [comment] 2015-10-28 04:33
I think this is a duplicate of #597 and #995.

**Closed by alanhartless** 2015-10-28 04:33 UTC
Labels: Duplicate
