### ISSUE TITLE
Mautic Installation On Litespeed Server | Through Softaculous

### ISSUE THREAD

**Issue by bgit-c** [mautic/mautic#12283] opened 2023-05-01 13:17 UTC
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Not relevant

### What happened?

Fresh install of Mautic on Litespeed server through softaculous brings out 403 error. You can't login on a fresh install. The installation isn't in a sub-folder. It's a sub-domain install.

Current solution is to comment out: 

    <FilesMatch "\.php$">
        Require all denied
    </FilesMatch>

Or eliminate the entire section:

<IfModule authz_core_module>
    # Deny access via HTTP requests to all PHP files.
    <FilesMatch "\.php$">
        Require all denied
    </FilesMatch>

    # Deny access via HTTP requests to composer files.
    <FilesMatch "^(composer\.json|composer\.lock)$">
        Require all denied
    </FilesMatch>

    # Except those allowed below.
    <If "%{REQUEST_URI} =~ m#^/(index|index_dev|upgrade/upgrade)\.php#">
        Require all granted
    </If>
</IfModule>

The above code is meant for Apache 2.4+

As per my understanding, the code above is specific to Apache web servers and uses the "authz_core_module" module, which is part of the Apache server software.

LiteSpeed, on the other hand, is a separate web server software, and although it is compatible with Apache's configuration files, it has its own set of modules and directives that it uses to configure access restrictions. This might explain why Mautic as a 403 error as a fresh install on litespeed servers through softaculous.

And the solution thereby is to comment out the code stated earlier. (Which doesn't feel right)

Here is what I have done/would suggest to mitigate the problem.
Add a litespeed section/Eliminate the apache module on litespeed installs and replace it with litespeed compatible code.

Below are two code sections I have come up with that are litespeed compatible. Both should work fine and are pretty much the same.

''
# Litespeed server
<IfModule LiteSpeed>

    # Deny access via HTTP requests to all PHP files.
    RewriteRule \.php$ - [F]
    
    # Deny access via HTTP requests to composer files.
    RewriteRule ^(composer\.json|composer\.lock)$ - [F]

    # Except those allowed below.
    RewriteCond %{REQUEST_URI} ^/(index|index_dev|upgrade/upgrade)\.php$ [NC]
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
</IfModule>
''

The second is an alteration of the first.

# Litespeed server
RewriteEngine On

# Deny access via HTTP requests to all PHP files.
RewriteRule \.php$ - [F]

# Deny access via HTTP requests to composer files.
RewriteRule ^(composer\.json|composer\.lock)$ - [F]

# Except those allowed below.
RewriteCond %{REQUEST_URI} !/(index|index_dev|upgrade/upgrade)\.php$
RewriteRule ^ - [F]

Both of them should work fine in whichever approach.

They address the commenting out of code issue. Importantly, they maintain the intended purpose or function of the original code. 

**The Result:** Mautic installation on litespeed will be more secure | No more 403 error on litespeed softaculous fresh installs | Litespeed section addition and removal of code causing the error on litespeed servers.

P.S. If I missed something please let me know

### How can we reproduce this issue?

Install Mautic on a litespeed Server
Install Mautic through softaculous on a litespeed server

I have tried installing Mautic on two different litespeed servers hosted by two different hosting providers and the result was the same. A 403 error on a fresh install.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment] 2023-06-05 21:19
Hi @bgit-c if I understand correctly, you suggest an improvement, that increases compatibility with litespeed and is still compatible with the current Apache setup? The only official supported webserver is Apache now, although the community runs it also on NGINX. 

So currently this is not a bug, its more like a feature request [https://forum.mautic.org](https://forum.mautic.org). But you are welcome to provide your suggested changes as a PR to be considered and merged into the core code.

Thanks a lot!

**Closed as not planned by dsp76** 2023-06-05 21:19 UTC
Labels: enhancement
