### ISSUE TITLE
Unpublished custom fields still show up when editing lead

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#1596] opened 2016-04-14 00:41 UTC
## Description
Unpublished custom fields still show up when editing lead

## Steps to reproduce
Create custom field (I used "personal" group)
Unpublish those fields...
Now they should not show up when editing the lead, but they do. 
Also note that they break the layout.

See screenshot:
http://s30.postimg.org/dfc2xlyao/Screen_Shot_2016_04_14_at_10_36_39_AM.jpg

**Comment by escopecz** [comment] 2016-04-14 06:46
Duplicate of https://github.com/mautic/mautic/issues/1562 (fix is there as well. A test would be great)

**Closed by escopecz** 2016-04-14 06:46 UTC
