### ISSUE TITLE
Emails don't have styling in major platforms like Gmail and Hotmail

### ISSUE THREAD

**Issue by joshua62493** [mautic/mautic#10891] opened 2022-02-23 18:01 UTC
### Mautic Version

4.1.x series

### PHP version

7.4

### What happened?

When writing an email in code format I ensure that the style tags are inside the head tags for formatting rules, however the system automatically moves it outside of the head tag and to the bottom of the email. Breaking emails for gmail and hotmail

### How can we reproduce this issue?

Step 1: Create email
Step 2: Put style tags within head tags

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2022-03-07 10:59
Hi @joshua62493 - this sounds like something to do with the GrapesJS builder functionalities rather than a bug with Mautic. I know that @jos0405 was talking around this topic recently in the Helpdesk Meetup. I am not sure if it is a bug or expected behaviour though, @jos0405 can you clarify?

**Comment by joshua62493** [comment] 2022-03-15 13:47
I would sincerely hope this is not intended behaviour as it makes the purposes of it useless as a majority of people use Microsoft and Google based email accounts, plus it breaks internet standards for formatting. Why would you use something that would actively fail at its purpose with more security systems coming into place?

**Comment by RCheesley** [comment] 2022-05-17 12:09
Pretty sure this is a duplicate of #10953 so closing it as such.

**Closed as completed by RCheesley** 2022-05-17 12:09 UTC
Labels: bug, duplicate, pending-feedback, needs-triage, builder-grapesjs

**Comment by AnujaFromUDA** [comment] 2022-10-21 05:33
I am facing the same issue as described above.
My emails break on Gmail - can someone suggest any solution that proved to be working

**Comment by AnujaFromUDA** [comment] 2022-10-24 23:42
> ### Mautic Version
> 4.1.x series
> 
> ### PHP version
> 7.4
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### What happened?
> When writing an email in code format I ensure that the style tags are inside the head tags for formatting rules, however the system automatically moves it outside of the head tag and to the bottom of the email. Breaking emails for gmail and hotmail
> 
> ### How can we reproduce this issue?
> Step 1: Create email Step 2: Put style tags within head tags
> 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I confirm that I have read and agree to follow this project's Code of Conduct

Hi Was this issue resolved for you? I am facing the same issue.
