### ISSUE TITLE
Asset insertion in email

### ISSUE THREAD

**Issue by shockalotti** [mautic/mautic#7180] opened 2019-01-30 03:43 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm having an issue with inserting assets into emails. I've uploaded a PDF, which has id 1. When in the email builder, I click the curly brace - { - to see different options. But {assetlink=1} is not there.

Here's a video showing what I mean:
https://cl.ly/9b5b493f6d54

| Q   | A
| --- | ---
| Mautic version 2.15.0 | 
| PHP version 7.0.33 | 
| Chrome browser on PC | 
 
### Log errors
None that I can see.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2020-02-04 18:15
Closing this down as unable to reproduce in 2.15.3.

**Closed by RCheesley** 2020-02-04 18:15 UTC
Labels: Bug
