### ISSUE TITLE
SAML Authentication not working

### ISSUE THREAD

**Issue by jakub-klik-it** [mautic/mautic#13361] opened 2024-02-13 12:20 UTC
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

SAML authentication not working, on release version 5.0.3.

Tested on multiple machines.

### How can we reproduce this issue?

Step 1: Download from https://github.com/mautic/mautic/releases/download/5.0.3/5.0.3.zip
Step 2: Run `composer require symfony/amazon-mailer `
Step 3: Install via web interface 
Step 4: Set SAML authentication on web interface
Step 5: Error 500, can not login.

### Relevant log output

```shell
php.CRITICAL: Uncaught Error: LightSaml\SpBundle\Controller\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed {"exception":"[object] (ArgumentCountError(code: 0): LightSaml\\SpBundle\\Controller\\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed at /var/www/html/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php:29)"} {"hostname":"xxx","pid":46}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by Ajtak** [comment] 2024-02-14 09:23
Not working too, but without `composer require symfony/amazon-mailer`.
I'm getting same error message

**Comment by tfmm** [comment] 2024-03-03 14:41
Any updates to this isssue?

**Comment by sertys3** [comment] 2024-03-04 17:35
I can confirm this does not work with me as well. 
Running mautic-docker on 5.0.3.
Downgrading to 4.4.9 works as expected.
It is unfortunate that the community is being driven to 5.x without core features covered.

**Comment by aki263** [comment] 2024-03-21 22:34
+1 SAML is not working.

Error:

`[2024-03-21T22:17:01.775952+00:00] mautic.CRITICAL: Uncaught PHP Exception ArgumentCountError: "LightSaml\SpBundle\Controller\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed" at /var/www/mautic/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php line 29 {"exception":"[object] (ArgumentCountError(code: 0): LightSaml\\SpBundle\\Controller\\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed at /var/www/mautic/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php:29)"} {"hostname":"ip-10-0-2-135","pid":16264}`

**Comment by stefanomarty** [comment] 2024-03-26 09:33
### +1 SAML is not working
```
[2024-03-26T08:37:26.830272+00:00] mautic.CRITICAL: Uncaught PHP Exception ArgumentCountError: 
"LightSaml\SpBundle\Controller\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed" at 
.../vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php line 29 
{"exception":"[object] (ArgumentCountError(code: 0): LightSaml\\SpBundle\\Controller\\DefaultController::__construct(): 
Argument #1 ($metadataProfileBuilder) not passed at 
.../vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php:29)"} {"hostname":"...","pid":3724925}
```

As a side effect, users are redirected to:
https:// mautic.your.domain **/s/saml/login**
where they receive a 500 Internal Server Error

Link to the standard (non SAML) login is:
https:// mautic.your.domain **/s/login**

**Comment by dusatvoj** [comment] 2024-03-27 09:29
@RCheesley you told @ https://github.com/mautic/mautic/issues/12304#issuecomment-1764301555 that you are focused to mautic 5.x but it's as buggy as 4.4.x series :thinking:

**Comment by stefanomarty** [comment] 2024-03-27 09:42
> @RCheesley you told @ [#12304 (comment)](https://github.com/mautic/mautic/issues/12304#issuecomment-1764301555) that you are focused to mautic 5.x but it's as buggy as 4.4.x series 🤔

While I have great respect for the efforts made to bring us mautic 5.x, I can't hide that I'm very scared of all those red bug icons on the first page of issues here...

**Comment by kingfisher77** [comment] 2024-03-30 12:40
+1 SAML does not work
I use SAML-based login with Entra (Azure AD). "Test this application" in Entra works! But not when browsing directly to site_url. Redirect to s/saml/login gets the 500 code, error messages appear in the logs as posted above.

**Comment by uadf** [comment] 2024-05-02 09:57
I'm impatiently waiting for SAML to work...

**Comment by RCheesley** [comment] 2024-05-02 09:58
We do know that it's frustrating, and we're holding up the 5.1 release to ensure that this is fixed. We just haven't got anyone who is able to work on this yet.

**Comment by stefanomarty** [comment] 2024-05-02 11:51
While at it pls consider adding OIDC.

**Comment by RCheesley** [comment] 2024-05-10 13:06
> While at it pls consider adding OIDC.

It's not on the plans right now, but if it's something you're interested in please do feel free to add some funds to the bounty pot which would mean we could fund a developer to work on it (see the info in the original post).

**Comment by RCheesley** [comment] 2024-05-12 16:34
Hi folks! Thanks to @mollux we have a fix for this issue. Please can you review, test and report back on this PR: https://github.com/mautic/mautic/pull/13742

General instructions for testing: https://mau.tc/tester but **please check the instructions in the PR** for specific instructions (please especially do the bit about leaving your review!)

Thanks all!

**Comment by escopecz** [comment] 2024-05-20 07:46
Hey everyone, please test https://github.com/mautic/mautic/pull/13742 if you want to get this fixed in Mautic 5.1.0. Otherwise I'll release it without it.

**Comment by stefanomarty** [comment] 2024-05-20 07:58
Hi @escopecz, thanks for handling this issue, when is the deadline for version 5.1.0? I'm too busy today and tomorrow, I think I can try it on Wednesday. If it's too late, it doesn't matter, we will publish it in the next version :-)

**Comment by escopecz** [comment] 2024-05-20 08:01
Wednesday is OK. Thank you!

**Comment by javiervalerocelada** [comment] 2024-05-20 11:01
Hi, i applaied two changes in my files:

- https://github.com/mautic/SpBundle/pull/2
- https://github.com/mautic/mautic/pull/13742

But i follow getting error in DefaultController line 29:
mautic.CRITICAL: Uncaught PHP Exception ArgumentCountError: "LightSaml\SpBundle\Controller\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed" at /var/www/html/mautic/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php line 29 {"exception":"[object] (ArgumentCountError(code: 0): LightSaml\\SpBundle\\Controller\\DefaultController::__construct(): Argument #1 ($metadataProfileBuilder) not passed at /var/www/html/mautic/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php:29)"} {"hostname":"ironman","pid":1162}

**Comment by escopecz** [comment] 2024-05-20 11:24
@javiervalerocelada it's not only about updating files. The problem isn't in Mautic itself but in another library that Mautic depends on. Dependencies are handled with Composer. In order to update the dependencies you must let Composer do it's thing. https://github.com/mautic/mautic/pull/13742 is there only to showcase how to test it. It won't be merged. But look at step 1 in the steps to test.

**Comment by stefanomarty** [comment] 2024-05-23 14:27
> Wednesday is OK. Thank you!

I tried to test the #13742 PR as per your instructions, but unfortunately I couldn't get past the first login screen. I'm not very familiar with Gitpod so I'm probably missing something here, but after configuring it and arriving at the Mautic login screen, when I try to login with admin/mautic I get this message:
`Your password is too weak. Please reset it.`

After following the reset procedure I see this new message:
`A new password has been generated and will be emailed to you, if this user exists. If you do not receive it within a few minutes, check your spam box and/or contact the system administrator.`

I thought I'd get the email on the GitHub user, but nothing gets there. No spam either. Sorry I have no idea how the admin email is configured in that Gipod istance and where the new password is sent. I'll try again in the weekend on a local server but it'll take a little bit more to setup the test enviroment.

**Comment by escopecz** [comment] 2024-05-24 08:35
@stefanomarty please check https://contribute.mautic.org/contributing-to-mautic/tester on how to get this work. The password is not `admin` and is written in the installation notes:
![Screenshot 2024-05-24 at 10 15 38](https://github.com/mautic/mautic/assets/1235442/040f3cd2-2297-401b-b424-431c54d661d1)
Bellow that is also a link to Mailhog where the testing Mautic instance is sending emails. It's not actually sending emails otherwise spammers would abuse that. However, when I tried it the Mailhog link did not work, so there was some change somewhere that broke it. Someone will have to take a look into that. However, with the right password you don't need the emails, to work to test this, right?

**Comment by stefanomarty** [comment] 2024-05-24 08:59
It's my fault, I didn't read all the instructions on https://contribute.mautic.org/contributing-to-mautic/tester, I just watched the video on Youtube. So I was using the password `mautic` instead of `Maut1cR0cks!`. But please note that the nice lady in the video is actually saying "The password is mautic" https://youtu.be/fqnT3kaDaW4?t=143 :-)))
Also I do not understand why the message was:
`Your password is too weak. Please reset it.`
That message made me think the password was right, just too short, so I tried the reset.

Anyway no problem, I'll try again over the weekend and let you know!

**Comment by escopecz** [comment] 2024-05-24 11:07
Yep, since then the requirement for the password strength was increased due to security report concerns. The video should be either edited or redone. And the error message is also confusing. If you could help with any of that, please do. The community needs any help you can give.

**Comment by RCheesley** [comment] 2024-05-31 13:59
Hi @stefanomarty @jakub-klik-it @Ajtak @tfmm @sertys3 @aki263 @dusatvoj @kingfisher77 @uadf the wait is nearly over .... we just need **one** of you to test the PR for us to be able to ship the 5.1 release with this fix.

Please review the very detailed step by step instructions which are [on the PR](https://github.com/mautic/mautic/pull/13742), if you need to set up a local Mautic installation we have docs on how to do that here: https://contribute.mautic.org/contributing-to-mautic/tester#setting-up-a-local-testing-environment using DDEV.

**Closed as completed** 2024-06-06 08:22 UTC
Labels: T2, bug, ready-to-test, regression, essential, configuration, good first issue
