### ISSUE TITLE
Error campaign 

### ISSUE THREAD

**Issue by neurohost** [mautic/mautic#6762] opened 2018-10-19 23:24 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
when trying to send an email campaign to a certain segment, it throws the following error

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.32
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors
[2018-10-19 22:20:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:20:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:35:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:35:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:40:22] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:40:22] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:46:54] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:46:54] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:50:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 22:50:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 23:05:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []
[2018-10-19 23:20:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mauyw_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mauyw_campaign_lead_event_log ' at line 2 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment] 2018-10-23 08:05
Closing as duplicate of https://github.com/mautic/mautic/issues/6589 as that issue contains the same error message and steps to reproduce.

**Closed by escopecz** 2018-10-23 08:05 UTC
