### ISSUE TITLE
Negative path action did not occour

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3948] opened 2017-04-30 15:06 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
In the same campaign as https://github.com/mautic/mautic/issues/3947 (where contacts were sent down both positive and negative paths when it should have just been positive) a contact did not complete an action and the negative path was not followed for that client (reminder email not sent)

![contact_a_path](https://cloud.githubusercontent.com/assets/2853040/25565452/9f138494-2dbe-11e7-827a-412aceb4a7a8.png)

Here is the specific setup used.

![screenshot from 2017-04-30 16-12-43](https://cloud.githubusercontent.com/assets/2853040/25565509/fd5e9fe2-2dbf-11e7-8af4-23e4453c2462.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment] 2017-04-30 15:06
Child of https://github.com/mautic/mautic/issues/3945

**Comment by gingerling** [comment] 2017-05-02 11:30
thanks, let me know if there is any extra info I can provide, I am still unsure if I can export some kind of code for these campaigns which are clearer than  diagrams

**Comment by Dcoutelle** [comment] 2017-05-03 09:50
Hello,

I don't know it's the same root problem, but we had the same kind of comportement on a campaign.
Into our campaign, the negative way were never taken.
It's was because the decision path was not correctly set into database

### campaign graph
![image](https://cloud.githubusercontent.com/assets/14074272/25655737/49259f2e-2ff6-11e7-9cd4-1c671d498aef.png)

### database
![image](https://cloud.githubusercontent.com/assets/14074272/25655762/65b4d100-2ff6-11e7-8ff0-fc32670e5440.png)

I was not able to reproduce the way to not set correctly decision path ( played with clone, builder, segment, etc...)

**Comment by gingerling** [comment] 2017-05-03 14:11
Hi, a few days ago https://github.com/merlin0 said 

"Got the same problem in 2.7.1. This only happens when the campaign is updated. Untouched campaigns from before 2.7.1. work fine." 

on this bug https://github.com/mautic/mautic/issues/3947  

If this is the case it could cause your issue and mine, and many many others. **It's a major bug**

I have just started a second campaign that is almost identical the the one I had with so many issues https://github.com/mautic/mautic/issues/3945 (of which this bug is just one). I made sure to not edit the campaign at all, and it is working perfectly now. 

I am not sure how to proceed but someone needs to take a look at this right away.

**Comment by gingerling** [comment] 2017-05-03 14:11
@escopecz you seem to sort bugs out here, I think there may be a big problem lurking here, can you assist?

**Comment by alanhartless** [comment] 2017-05-04 13:37
@gingerling Mautic.net should be fixed for this now. 

@Dcoutelle Can you check your database to see if the decision_path got wiped out? We had a bug that if you opened the campaign without opening the builder (i.e. just edited the published state or the name) and saved, the decision path got wiped out. That is fixed and will be PR'ed today.

**Comment by Dcoutelle** [comment] 2017-05-04 14:10
@alanhartless 

Check this : 
https://cloud.githubusercontent.com/assets/14074272/25655762/65b4d100-2ff6-11e7-8ff0-fc32670e5440.png

I think we are in this case.

Thanks for the PR!

**Comment by alanhartless** [comment] 2017-05-04 16:04
@Dcoutelle https://github.com/mautic/mautic/pull/3993

**Comment by gingerling** [comment] 2017-05-04 16:12
Hi, ok, when did the fix to mautic.net occour, so I can see if my current campaign was ok? Also does this cover all the issues linked to this, or just this one?

**Comment by npracht** [comment] 2017-05-16 09:40
@escopecz i think it can be closed due to https://github.com/mautic/mautic/pull/3993 we have tested and it works !

**Comment by escopecz** [comment] 2017-05-16 10:26
Thanks Norman!

**Closed by escopecz** 2017-05-16 10:26 UTC
Labels: Bug, Ready To Test
