### ISSUE TITLE
[feature] display different form/content after user has filled out a form

### ISSUE THREAD

**Issue by yankees9920** [mautic/mautic#414] opened 2015-05-16 12:37 UTC
If a lead goes to a page that contains a form they have previously filled out, it would be nice to have the ability to display different content or form to that user.

**Comment by dbhurley** [comment] 2015-05-28 20:53
Couldn't this be done simply by navigating the user to a different page with a different form after a submission?

**Comment by yankees9920** [comment] 2015-05-29 13:19
Its my understanding that you could navigate them to a different page/form after submission, however this wouldn't handle the following scenario which I was envisioning - you may have a form on your homepage to capture email address for a mailing list, however once they submit that form, you have their email, so any subsequent time they visit that page, there is the opportunity to show them a different piece of content in that location, rather than still asking for their email address, which we already know.
Similar to Hubspot's smart forms and progressive profiling.

**Comment by troelsfeodor** [comment] 2015-09-19 17:55
My feature request for "progressive profiling forms" was marked as a duplicate of this. I'm not 100% sure it is. Depends on how this is implemented. They key is in a intelligent way to be able to ask a returning known lead for new information in new forms that he might submit.

**Comment by escopecz** [comment] 2016-04-18 10:03
Please check and possibly test this PR if it solves this issue: https://github.com/mautic/mautic/pull/1363

**Comment by npracht** [comment] 2016-06-08 08:16
Hi @dbhurley & @escopecz, let me complete the brief. Cause it's clearly not linked to Issue 1363.

# Objective
Qualify better leads by asking us information **we do not have yet** on the forms.
## What is Progressive Profiling?
Progressive Profiling allows your forms to only ask for information that’s not already known by the marketing automation software. This allows your forms to progressively uncover additional qualifying information as leads become more engaged with your content and your company.

On the forms, you'd have a feature to enable. For instance, Net Results does the same and it's a very powerfull feature. https://www.net-results.com/progressive-profiling/


# How to proceed
1. On the form you enable the feature
2. Then you choose how many fields shoud be displayed
3. You sort fields the way you want (the way they'll appear on the website)
4. On each field you have the opportunity to **always display** the field
5. All known contact values make invisible the form input and replaced by the next in the form input list.

![capture d ecran 2016-06-08 a 10 12 16](https://cloud.githubusercontent.com/assets/14075239/15887245/84fd5728-2d61-11e6-9949-531253a61b31.png)

**Comment by npracht** [comment] 2017-05-31 07:32
@escopecz can be closed in favor of https://github.com/mautic/mautic/issues/2545 ?

**Comment by escopecz** [comment] 2017-05-31 08:21
I think those 2 are different features. One is showing additional fields based on the values in other field, this one is showing something after form submission based on the form values.

**Closed** 2017-11-27 15:59 UTC
Labels: Backlog, Feature Request
