### ISSUE TITLE
Twilio SMS - Alpha Sender ID

### ISSUE THREAD

**Issue by lsoldado** [mautic/mautic#2636] opened 2016-10-04 13:51 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
In Twilio it is possible to send SMS by a alphanumeric number. 

## If a bug:
If i try to change it in Text Messege Settings -> Sending Phone Number it gives me one error.
After i can´t edit or clone any campaign. 

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 7.0.1

### Steps to reproduce:
1. Set Alpha numeric sender in Twilio
2. Change SMS sender to Alpha numeric sender
 
### Log errors: 
[2016-10-04 13:38:43] mautic.CRITICAL: Uncaught PHP Exception libphonenumber\NumberParseException: "The string supplied did not seem to be a phone number." at xxxx/vendor/giggsey/libphonenumber-for-php/src/libphonenumber/PhoneNumberUtil.php line 1340 {"exception":"[object] (libphonenumber\\NumberParseException(code: 1): The string supplied did not seem to be a phone number. at xxx/vendor/giggsey/libphonenumber-for-php/src/libphonenumber/PhoneNumberUtil.php:1340)"} []

**Comment by escopecz** [comment] 2016-10-04 13:55
This seems like a duplicate of https://github.com/mautic/mautic/issues/2240

**Closed by escopecz** 2016-10-04 13:55 UTC
