### ISSUE TITLE
List Population Issues

### ISSUE THREAD

**Issue by SolacetechInformationServices** [mautic/mautic#54] opened 2015-02-17 19:58 UTC
Interesting... I made a form that added any anyone who signed up to my podcast to a list named podcast. After I used that list to email my podcast the list emptied. My other list that has filters used has not emptied after email. Before I create a work around is there a way to make permanent lists,for a lack of better words?

**Comment by alanhartless** [comment] 2015-02-25 05:23
I've tried to reproduce this through multiple scenarios but so far have been unsuccessful. Can you still reproduce it? 

Thanks,
Alan

**Comment by SolacetechInformationServices** [comment] 2015-02-25 05:31
I think it might be my database because I'm constantly receiving new users via my campaigns. I think I also might have imported my second CSV file wrong. I'm just manually adding users to lists for the time being.

**Comment by alanhartless** [comment] 2015-02-26 00:41
So leads you add manually are staying put after sending an email to the list? Asking because programmatically, manually adding a lead and having a form add a lead uses the same code and means of storing the relationship in the table.  If sending the email is the catalyst for depleting the list, it should happen for leads added via a form submit action or manually added through the lead details view.

Thanks,
Alan

**Comment by SolacetechInformationServices** [comment] 2015-02-26 04:09
After I send the emails the list empties again.

**Comment by SolacetechInformationServices** [comment] 2015-02-26 04:41
Here is a demo of me trying to use smart lists. Testing Mautic: http://youtu.be/da75lp1eC4g

**Comment by alanhartless** [comment] 2015-03-07 19:53
Hey Anthony,

So we did find the issue causing lists to be wiped out and fixed in RC3 (then RC4 which included a hot fix related to viewing lists). 

Upgrading should solve this issue.  

Thanks,
Alan

**Closed** 2015-03-10 15:10 UTC
Labels: Bug
