### ISSUE TITLE
Tracking pixel gets inserted into empty text/html MIME part

### ISSUE THREAD

**Issue by aspiers** [mautic/mautic#7703] opened 2019-07-21 16:52 UTC
## Bug Description

Even when the HTML part of an email is left empty, Mautic will add a tracking pixel which prevents sending of pure plain text emails as per #4593.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Chrome 75.0.3770.89 for Android 9

### Steps to reproduce

- Create a new email template 
- Select the Code Mode theme
- Delete *all* of the HTML code (e.g. press `Control+A` then `Backspace`)
- Put some content in the text part
- Observe that when you click the `Send Example` button from this template email, it sends a email with no `text/html` MIME part, i.e. it is a pure `text/plain` email.
- Observe that when it gets sent as part of a campaign, Mautic inserts a tracking pixel, so the `text/html` part gets instantiated, e.g.

```
--_=_swift_v4_1561145556_93e0cbb9adc6ed8c3f66ba65e2ea837c_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<img height=3D"1" width=3D"1" src=3D"https://mautic.mydomain.com/email/5d=
0d30d6b87d8677213888.gif" alt=3D"" />

--_=_swift_v4_1561145556_93e0cbb9adc6ed8c3f66ba65e2ea837c_=_--
```

and of course this shows as a blank email to most people, even if the `text/plain` part contains content, because most mail clients will default to showing the HTML MIME part if there is one in preference to the `text/plain` part.

**Comment by JackReaperz** [comment] 2019-07-26 03:13
Try checking the Tracking settings in your Configurations. It might still be turned on.

**Comment by npracht** [comment] 2019-07-26 07:25
It can be closely related to https://github.com/mautic/mautic/issues/7711. Today we don't manage the plain text version, even in code mode this is HTML. So i'll consider this issue as duplicate of https://github.com/mautic/mautic/issues/7711 because if https://github.com/mautic/mautic/issues/7711 is solved, you'll be able to send only plain text version.

**Comment by aspiers** [comment] 2019-07-26 09:09
@npracht Sorry but they are fundamentally different, not duplicates.  #7711 is about sending emails which have both an HTML part *and* a plain text part which is automatically generated from the HTML part whenever the HTML changes.  In contrast, this issue is about sending emails which have *no* HTML part at all, *only* a plain text part.

So please can you reopen this?

**Comment by npracht** [comment] 2019-07-26 09:16
I can re-open but if the text version is created automatically = managed, then we will be able to have the version without the pixel. So it is highly related.

**Comment by aspiers** [comment] 2019-07-26 09:24
I don't see how it can be related at all.  This issue is about *manually* handwriting the text part from scratch, and never having *anything* in the HTML part.  In this case, there cannot be any auto-generation at all. 

This is a significantly different approach to having both parts looking more or less identical, because some mail clients (and indeed their human users) use the presence of an HTML part as a factor in judging whether the mail was sent in bulk.  When a mail is purely `text/plain` with no `text/html`, it instantly looks more personal and therefore more likely to be read.

**Comment by npracht** [comment] 2019-07-26 09:33
If you can autogenerate it, that means it manages a plain text version. Which is not the case of today.
If you can manage a plain tex version, you can manage a version without image.

That's what i meant.
No matter, i re-opened it and marked it to be addressed when we re-do the mautic email builder.

**Closed** 2020-03-06 11:09 UTC
Labels: Email builder, Enhancement, Ready To Test
