### ISSUE TITLE
Problem with mautic builder in mautic 3.1.0

### ISSUE THREAD

**Issue by mishudm** [mautic/mautic#9127] opened 2020-08-26 12:47 UTC
Hello, I updated mautic from 3.0.2 to 3.1.0.  after that mautic builder not working when we create new email. its become a blank screen . then i fressly install mautic and its also has same problem.
![2020-08-20_004544](https://user-images.githubusercontent.com/64133213/91305172-76298a80-e7cc-11ea-9790-19420953d521.png)

you can see the photo.
 i cant edit or create new email

**Comment by nickveenhof** [comment] 2020-08-26 19:05
Do you see something in your network console? I had the same issue but in my case we upgraded from 2.16to 3.1 and were missing the grapesjsbuilderbundle plugin, after installing that the problem got solved!

**Comment by mishudm** [comment] 2020-08-26 19:20
> Do you see something in your network console? I had the same issue but in my case we upgraded from 2.16to 3.1 and were missing the grapesjsbuilderbundle plugin, after installing that the problem got solved!

how wil i know what is missing? now its a fress install mautic not a update. i also install another mautic in another vps thats have also the same issue.
but i installed many mautic when it was 3.0.2 but did not face any problem ever

**Comment by Bandito83** [comment] 2020-08-27 07:32
Hi, i have this same problem... Problem is with JS code script.

![mautic](https://user-images.githubusercontent.com/8414876/91411118-31433980-e848-11ea-87b5-ef80c5660350.png)

**Comment by mishudm** [comment] 2020-08-27 07:50
> Hi, i have this same problem... Problem is with JS code script.
> 
> ![mautic](https://user-images.githubusercontent.com/8414876/91411118-31433980-e848-11ea-87b5-ef80c5660350.png)

How can i fix it?

**Comment by quadcom** [comment] 2020-08-27 19:14
I would suggest posting a copy of the PHP Info page in Configuration > System Info. Rule out any missing server directives. It appears there is a JSON parsing error popping up. 

I run all my sites on Linode with Runcloud managing them. They have a step by step doc getting Mautic up on their servers. https://blog.runcloud.io/install-mautic-runcloud/

**Comment by petycomp** [comment] 2020-08-30 05:07
Exactly the same issue here. Clean installation of 3.1 and the email builder doesn't work, nothing appears in the left block of the email builder. Some kind of JS problem.

**Comment by chattouti** [comment] 2020-09-01 14:37
the same issue here.

**Comment by quadcom** [comment] 2020-09-01 14:44
It may not be something missing in the mautic install but a server directive which is why I suggested posting the PHP info page. Let's make sure you have the SERVER setup correctly first. 

Yes, it may have worked correctly in previous versions of mautic because the older versions didn't use the server directives the new version does. It doesn't mean there's a problem with your mautic install but rather something missing in the server that mautic is trying to use.

**Comment by chattouti** [comment] 2020-09-01 14:54
[info.txt](https://github.com/mautic/mautic/files/5156986/info.txt)

> It may not be something missing in the mautic install but a server directive which is why I suggested posting the PHP info page. Let's make sure you have the SERVER setup correctly first.
> 
> Yes, it may have worked correctly in previous versions of mautic because the older versions didn't use the server directives the new version does. It doesn't mean there's a problem with your mautic install but rather something missing in the server that mautic is trying to use.

**Comment by chattouti** [comment] 2020-09-01 14:54
![image](https://user-images.githubusercontent.com/4406090/91867341-77930100-ec6b-11ea-82cd-995412e86093.png)

**Comment by quadcom** [comment] 2020-09-01 15:38
Can you try upping your php version to 7.3?

**Comment by petycomp** [comment] 2020-09-01 17:54
> Can you try upping your php version to 7.3?

I've just tried it, but haven't fixed the problem. Same issue. 

PHP Info: https://pastebin.ubuntu.com/p/Hdc55DZY78/

**Comment by quadcom** [comment] 2020-09-01 18:23
I can't say for sure what's going on but I would check your servers PHP functions. My server managed by Runcloud gave these instructions.
  
https://blog.runcloud.io/install-mautic-runcloud/#create-php-web-application-in-runcloud

There's a section talking about PHP functions and provided a list. Perhaps you could check your server to see that these are all enabled.

**Comment by chattouti** [comment] 2020-09-01 19:00
> Can you try upping your php version to 7.3?

i've tried  but same problem

**Comment by petycomp** [comment] 2020-09-02 02:43
> I can't say for sure what's going on but I would check your servers PHP functions. My server managed by Runcloud gave these instructions.
> 
> https://blog.runcloud.io/install-mautic-runcloud/#create-php-web-application-in-runcloud
> 
> There's a section talking about PHP functions and provided a list. Perhaps you could check your server to see that these are all enabled.

"_For disable_functions, it is optional, you can remove all php_posix functions from the list."_ - this is the only PHP specific part in the description, but I think it doesn't make sense.

**Comment by quadcom** [comment] 2020-09-02 13:35
That's right. But the list that they do give may have functions that your server does not have. I set my server up following this and my install works fine.

**Comment by aranet** [comment] 2020-09-02 17:43
i had the same problem with clean install. Console message was "Uncaught SyntaxError: Unexpected token u in JSON at position 0" in app.js. I'm not sure exactly what resolved it, so take this with caution...but I did the following:
- php bin/console mautic:assets:generate
- rm -rf app/cache/*
- sudo chmod 777 app/cache

**Comment by petycomp** [comment] 2020-09-03 03:08
> i had the same problem with clean install. Console message was "Uncaught SyntaxError: Unexpected token u in JSON at position 0" in app.js. I'm not sure exactly what resolved it, so take this with caution...but I did the following:
> 
> * php bin/console mautic:assets:generate
> * rm -rf app/cache/*
> * sudo chmod 777 app/cache

The error message is the same on our side... I've just tried out the above suggested things, but did not help :(

**Comment by npracht** [comment] 2020-09-07 12:48
duplicate of https://github.com/mautic/mautic/issues/9138

**Closed as completed by npracht** 2020-09-07 12:48 UTC
Labels: duplicate

**Comment by drptiago** [comment] 2020-09-08 12:53
Same issue here and not related to #9138.

**Comment by petycomp** [comment] 2020-09-09 03:58
I agree, I patched my instance based on 9138, but it didn't fix this issue. Now I get the following erros message every time, when I try to modify any templates with the code builder.. libraries.js?v0201c404:766 GET http://mautic.xxxxx.com/s/emails/builder/1?template=vibrant&_=1599623410444&mauticUserLastActive=115&mauticLastNotificationId= 500 (Internal Server Error)

**Comment by ziruhel786** [comment] 2020-09-28 07:58
I am having a similar issue, I have installed Mautic through AWS marketplace (https://aws.amazon.com/marketplace/pp/Bitnami-Mautic-Certified-by-Bitnami/B015YU4RJA#pdp-support). Everything working fine but Email builder not working. Please see this screenshot 
![2020-09-28_13-30-33](https://user-images.githubusercontent.com/4748229/94405491-7255a300-0192-11eb-97f3-bdcc3e3ac50e.png) How can I solve this, any idea?

**Comment by RodrigoRosadeOliveira** [comment] 2020-09-28 20:37
> I am having a similar issue, I have installed Mautic through AWS marketplace (https://aws.amazon.com/marketplace/pp/Bitnami-Mautic-Certified-by-Bitnami/B015YU4RJA#pdp-support). Everything working fine but Email builder not working. Please see this screenshot
> ![2020-09-28_13-30-33](https://user-images.githubusercontent.com/4748229/94405491-7255a300-0192-11eb-97f3-bdcc3e3ac50e.png) How can I solve this, any idea?

Same here, i have installed  through AWS too.


`VM105:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Mautic.initGrapesJS (app.js?v3b19c01f:706)
    at Object.Mautic.launchBuilder (app.js?v3b19c01f:706)
    at HTMLButtonElement.onclick (new:1749)
    at Object.trigger (libraries.js?v3b19c01f:683)
    at HTMLButtonElement.<anonymous> (libraries.js?v3b19c01f:688)
    at Function.each (libraries.js?v3b19c01f:153)
    at jQuery.fn.init.each (libraries.js?v3b19c01f:144)
    at jQuery.fn.init.trigger (libraries.js?v3b19c01f:688)
    at jQuery.fn.init.jQuery.fn.<computed> [as click] (libraries.js?v3b19c01f:796)`

**Comment by ziruhel786** [comment] 2020-09-28 20:50
@RodrigoRosadeOliveira
I have solved my problem by changing the OS Debian to Ubuntu. 
I have re-installed using Ubuntu, If you have used Debian, you can try with Ubuntu.

**Comment by RodrigoRosadeOliveira** [comment] 2020-09-28 20:55
> @RodrigoRosadeOliveira
> I have solved my problem by changing the OS Debian to Ubuntu.
> I have re-installed using Ubuntu, If you have used Debian, you can try with Ubuntu.

I'm also with Debian:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"

I will try that, thank you.

**Comment by RCheesley** [comment] 2020-09-28 21:01
Folks, this issue in the last few posts was due to some files getting pushed to staging which had incorrect assets (see #9188 and the PR that fixed the issue #9194). It was fixed just over two weeks ago. 

Suggest you pull down from Staging, or grab the latest installer (if you wait a few minutes we should have 3.1.1 available) and re-generate the assets using `bin/console m:a:g` at command line (plus the usual clearing cache etc).

**Comment by petycomp** [comment] 2020-09-29 04:14
> > @RodrigoRosadeOliveira
> > I have solved my problem by changing the OS Debian to Ubuntu.
> > I have re-installed using Ubuntu, If you have used Debian, you can try with Ubuntu.
> 
> I'm also with Debian:
> 
> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> 
> I will try that, thank you.

I had the same issue with Ubuntu, so changing from Debian to Ubuntu probably won't solve the problem. 

@RCheesley I already tried to fix this issue based on 9188 and 9194, and it didn't help.
