### ISSUE TITLE
mts.js leaks MediaElements player CSS to page DOM

### ISSUE THREAD

**Issue by jevgen** [mautic/mautic#4443] opened 2017-07-17 11:20 UTC
This is bug. 
## Description:
On a page where I have background video running, mts.js after a short while calls MediaElements Player CSS which breaks site layout. 

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7

### Steps to reproduce:
1. Make page with Mautic tracker that runs background video with mp4 and webwm in `<video>` on canvas.
2. After few seconds Mautic spits `<span class="mejs-offscreen">Video Player</span>` into your DOM and erratic GET request mtc.js:9 GET pathtoyourmautic/pathtoyourmautic/media/css/mediaelementplayer.css

**Comment by escopecz** [comment] 2017-07-17 11:29
Seems like a duplicate of https://github.com/mautic/mautic/issues/4431

**Closed by escopecz** 2017-07-17 11:29 UTC
