### ISSUE TITLE
feature request A/B test in forms

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#878] opened 2015-09-09 10:31 UTC
Landing A/B is usefull but I use the forms as a javascript embeed in the pages. Make testing A/B in forms will be very interesting for me.

**Comment by that0n3guy** [comment] 2015-09-09 20:26
Does something like this belong in mautic at all?  There are some great A/B apps out there already (convert.com, optimizely.com, etc...)

**Comment by alanhartless** [comment] 2015-09-19 04:39
Duplicate of #53

**Closed by alanhartless** 2015-09-19 04:39 UTC
Labels: Duplicate
