### ISSUE TITLE
Ability to custom the contact fields displayed on Contacts page

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1927] opened 2016-06-30 10:34 UTC
## Description
Today when you go on your Contacts page, you have displayed:
* Name (containing : `firstname`, `lastname`, `company`)
* Email address
* Location
* Points
* Last Active
* ID

### 1. Add a little settings button
On top right to configure/customize the fields (columns) displayed for the logged mautic user.
![capture d ecran 2016-06-30 a 12 29 38](https://cloud.githubusercontent.com/assets/14075239/16485319/9f983800-3ebe-11e6-8df1-470649d82764.png)
### 2. Open a popin
Where you can set your chosen fields.
![capture d ecran 2016-06-30 a 12 33 32](https://cloud.githubusercontent.com/assets/14075239/16485409/e2f7fec8-3ebe-11e6-98a4-c2a897673261.png)

**Comment by alanhartless** [comment] 2016-08-25 18:14
duplicate of #1927

**Closed by alanhartless** 2016-08-25 18:14 UTC
Labels: Feature Request

**Comment by xtremewebsites** [comment] 2017-01-18 18:30
This is a great feature request. The supposed duplicate does not give as much detail and does not give any answer either.

**Comment by engerim42** [comment] 2019-11-03 04:24
Only works if the field group is set to "Core". If I set a custom field to "Social" the column is shown but not the data.
