### ISSUE TITLE
JS error after migrating to Mautic 2.5.1

### ISSUE THREAD

**Issue by guillaumegarcia13** [mautic/mautic#3269] opened 2017-01-19 10:02 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After migrating to Mautic 2.5.1, some pages are not reachable (or very occasionnaly) such as Dashboard.
Many requests result in JavaScript errors and interface is unresponsive (action buttons are disabled)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Create a new e-mail and save it
2. Edit the new e-mail
 
### Log errors: 

Error is a Javascript one (Uncaught TypeError: Cannot read property 'indexOf' of undefined) in **media/js/app.js?v5422e254** at the line :
`var errorStart = request.responseText.indexOf('{"newContent');`

Although it seems not to be related (timestamp does not seem to match), the System Info > Log shows
`[2017-01-19 09:51:57] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT es.id as id, es.device as device, es.device_fingerprint FROM maulead_devices es WHERE es.lead_id = 235070':  Unknown column 'es.device_fingerprint' in 'field list'" at /var/www/html/mautic.freelance.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT es.id as id, es.device as device, es.device_fingerprint FROM maulead_devices es WHERE es.lead_id = 235070':\n\nUnknown column 'es.device_fingerprint' in 'field list' at /var/www/html/mautic.freelance.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException(code: 0): Unknown column 'es.device_fingerprint' in 'field list' at /var/www/html/mautic.freelance.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:94)"} []`

**Comment by escopecz** [comment] 2017-01-19 11:51
It seems that your database migrations didn't run successfully. Follow https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful to fix it. Let us know if it helped.

**Comment by guillaumegarcia13** [comment] 2017-01-24 10:00
Hi John,

1. Removing the cache helped a bit (pages that do not load, now load) but issue keeps coming back after a while (1 day).
2. No update available -> _"Great! You are running the current version of Mautic."_

3. WARNING! You have 4 previously executed migrations in the database that are not registered migrations.
    > 2015-02-01 00:00:00 (20150201000000)
    > 2015-02-25 00:00:00 (20150225000000)
    > 2015-03-07 00:00:00 (20150307000000)
    > 2015-03-10 00:00:00 (20150310000000)

4. php app/console doctrine:schema:update --dump-sql outputs a bunch of SQL statements
`ALTER TABLE maudynamic_content_lead_data DROP FOREIGN KEY FK_35FB044155458D;`
`ALTER TABLE maudynamic_content_lead_data DROP FOREIGN KEY FK_35FB0441D9D0CD7;`
`ALTER TABLE maudynamic_content_lead_data CHANGE lead_id lead_id INT DEFAULT NULL`
`ALTER TABLE maudynamic_content_lead_data ADD CONSTRAINT FK_35FB044155458D FOREIGN KEY (lead_id) REFERENCES mauleads (id);`
`ALTER TABLE maudynamic_content_lead_data ADD CONSTRAINT FK_35FB0441D9D0CD7 FOREIGN KEY (dynamic_content_id) REFERENCES maudynamic_content (id);`
`ALTER TABLE mauemail_stats DROP copy;`
`ALTER TABLE mauform_fields CHANGE show_when_value_exists show_when_value_exists TINYINT(1) DEFAULT NULL;`
`ALTER TABLE mauleads CHANGE title title VARCHAR(255) DEFAULT NULL`
`CREATE INDEX maulastname_search ON mauleads (lastname);`
`CREATE INDEX maufirstname_search ON mauleads (firstname);`
`CREATE INDEX mauupdated_by_owner_date_search ON mauleads (updated_by_owner_date);`
`CREATE INDEX mauonetime_connect_expiratio_search ON mauleads (onetime_connect_expiratio);`
`CREATE INDEX maucontact_last_login_date_search ON mauleads (contact_last_login_date);`
`CREATE INDEX maucontact_last_login_year_search ON mauleads (contact_last_login_year);`
`CREATE INDEX mauaudit_lastlogin_date_search ON mauleads (audit_lastlogin_date);`
`CREATE INDEX maufax_search ON mauleads (fax);`
`CREATE INDEX mauaddress1_search ON mauleads (address1);`
`CREATE INDEX mauaddress2_search ON mauleads (address2);`
`CREATE INDEX mautitle_search ON mauleads (title);`
`CREATE INDEX maucity_search ON mauleads (city);`
`CREATE INDEX maustate_search ON mauleads (state);`
`CREATE INDEX mauzipcode_search ON mauleads (zipcode);`
`CREATE INDEX maucompany_search ON mauleads (company);`
`CREATE INDEX mauwebsite_search ON mauleads (website);`
`CREATE INDEX mautwitter_search ON mauleads (twitter);`
`CREATE INDEX mauposition_search ON mauleads (position);`
`CREATE INDEX maufacebook_search ON mauleads (facebook);`
`CREATE INDEX maugoogleplus_search ON mauleads (googleplus);`
`CREATE INDEX mauphone_search ON mauleads (phone);`
`CREATE INDEX maumobile_search ON mauleads (mobile);`
`CREATE INDEX mauskype_search ON mauleads (skype);`
`CREATE INDEX maulinkedin_search ON mauleads (linkedin);`
`CREATE INDEX mauinstagram_search ON mauleads (instagram);`
`CREATE INDEX maufoursquare_search ON mauleads (foursquare);`
`ALTER TABLE maucompanies CHANGE score score INT NOT NULL;`
`ALTER TABLE maucompanies_leads CHANGE is_primary is_primary TINYINT(1) NOT NULL;`
`ALTER TABLE maulead_frequencyrules CHANGE preferred_channel preferred_channel TINYINT(1) NOT NULL;`
`ALTER TABLE maupage_redirects DROP email_id;`

Should I proceed with 3 and then 4?
Only 4?

Thanks!!

**Comment by guillaumegarcia13** [comment] 2017-01-27 11:36
OK, got to move on so I updated the schema (point 4 of the list).
Will tell you if it solves the problem

**Comment by guillaumegarcia13** [comment] 2017-01-27 14:19
Well, not so good.
Still have JS issues (cf. screenshot)

![image](https://cloud.githubusercontent.com/assets/2786038/22373864/fd63ff24-e4a3-11e6-80c3-044d2b3c0af7.png)

**Comment by escopecz** [comment] 2017-08-17 07:39
Is this fixed now? If not, run `app/console mautic:assets:generate` to regenerate assets like JS and CSS. I'll close this now, but re-open if you still have the issue.

**Closed by escopecz** 2017-08-17 07:39 UTC

**Comment by guillaumegarcia13** [comment] 2017-08-31 09:20
Hi John,

Try this command ```console mautic:assets:generate```, stopped / started Mautic but still an issue when trying to edit an email for instance.
So, I tried to upgrade to latest version (2.9.2) hoping for a fix.
Followed the steps in your troubleshooting guide (force SQL update, regenerate assets) and then stop/start once again and still have this
![image](https://user-images.githubusercontent.com/2786038/29916160-3ff4aaac-8e3e-11e7-91a1-1454c2f2dcab.png)

**Comment by escopecz** [comment] 2017-08-31 09:40
Try to google for `ERR_INCOMPLETE_CHUNKED_ENCODING` as from what I found it could be caused by your antivirus software.
