### ISSUE TITLE
Twitter campaign not tweeting

### ISSUE THREAD

**Issue by danielelodola** [mautic/mautic#5144] opened 2017-10-12 21:35 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I have configured and published the Twitter plugin on my Mautic install. I believe this has been done correctly and am able to run Social Monitoring (new leads created etc.); also, Contacts with a Twitter handle display the relevant and up to date twitter info. The call back url was correctly added to the Twitter app ( [https://service.liquidem.com/plugins/integrations/authcallback/Twitter](url) )

However, I am unable to send Tweets from Mautic in a campaign. The campaign is set up and configured, when I trigger the campaign I see the event be run however I get the error illustrated hereafter in the contact's history + the logs detailed hereafter.

![twitter-error](https://user-images.githubusercontent.com/17082399/31520245-878b2e26-afa5-11e7-8def-0f60adf79d20.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.22

### Steps to reproduce:
1. Configure and publish Twitter plugin
2. Create a new campaign
3. Add "Tweet contact" action
4. Trigger campaign
 
### Log errors: 

[2017-10-12 23:08:37] mautic.WARNING: PHP Warning - preg_match() expects parameter 2 to be string, array given - in file .../mautic/plugins/MauticSocialBundle/Integration/TwitterIntegration.php - at line 289 [] []
[2017-10-12 23:08:37] mautic.WARNING: PHP Warning - substr() expects parameter 1 to be string, array given - in file .../mautic/plugins/MauticSocialBundle/Integration/TwitterIntegration.php - at line 292 [] []
[2017-10-12 23:08:37] mautic.WARNING: PHP Warning - urlencode() expects parameter 1 to be string, array given - in file .../mautic/plugins/MauticSocialBundle/Integration/TwitterIntegration.php - at line 296 [] []

**Comment by npracht** [comment] 2020-07-07 12:46
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment] 2020-07-29 10:04
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Closed by RCheesley** 2020-07-29 10:04 UTC
Labels: bug, campaigns, pending-feedback, plugin, triage-mautic-3

**Comment by christian-krieg** [comment] 2022-05-16 01:32
Hey there, Unfortunately I am also unable to send tweets. As opposed to OP, I only see a warning symbol without any hint on the error. Any idea where to look for hints on the root cause? The log in Mautic is empty, and so are my server logs... I am running Mautic 4.2.1
