### ISSUE TITLE
smart list problem

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1287] opened 2015-12-28 11:36 UTC
Hi 
I worked to get a way to users select preferences of notifications via checkboxes. See https://github.com/mautic/mautic/issues/1255 and finally seems that it works fine the first time one user select preferences. 

The form with checkboxes save the data in the text field of database by coma separated. 

Example:
![image](https://cloud.githubusercontent.com/assets/10166840/12018024/f65eb0f8-ad5d-11e5-9e0d-be249150faea.png)

Save in the core field:
![image](https://cloud.githubusercontent.com/assets/10166840/12018031/11986d32-ad5e-11e5-82d2-3e63079a7930.png)

The idea is the smartlist use this field to add the lead to these smart list

![image](https://cloud.githubusercontent.com/assets/10166840/12018051/6db4d6be-ad5e-11e5-8ef5-1c470fc60105.png)

Until this point all works!

The problem is when one user want to change their preferences. The second time one use select another option the text field is correctly updated but the smart list dont made the query to get this lead.

(when one user send the form with new preferences in the form I have one action that remove the lead from all lists) 

But even the field has the data correct the smart list dont run another time the selection to add this user to the new lists.

I think there we have some limitation about the execution of the smartlist condition. 

Now I have this information in the lead:
![image](https://cloud.githubusercontent.com/assets/10166840/12018104/4a9fd3d0-ad5f-11e5-911f-46dbf6fe5a4a.png)

This condition in the smart list:

![image](https://cloud.githubusercontent.com/assets/10166840/12018106/54198a78-ad5f-11e5-9730-79762f78ef67.png)

And the lead is not in the list:
![image](https://cloud.githubusercontent.com/assets/10166840/12018112/5f8dd940-ad5f-11e5-8b3a-e98b2bd15252.png)

the problem could be there some limit about how many times the smartlist evaluate a lead?

**Comment by escopecz** [comment] 2016-01-18 15:27
This issue is so nicely described here, but it seems it is duplicate of https://github.com/mautic/mautic/issues/1225 . I will close this one since #1225 is was reported before this one.

**Closed** 2016-01-18 15:27 UTC
Labels: Bug, Duplicate
