### ISSUE TITLE
Symfony Error at social monitoring after upgrade to 2.8.1

### ISSUE THREAD

**Issue by wowawebdesign** [mautic/mautic#4100] opened 2017-05-19 22:27 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
After upgrading to 2.8.1, I got the following error everytime, /app/console mautic:social:monitoring is executed.

` [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                        
  Type error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /var/www/m/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 967  `

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.13

### Log errors: 

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /var/www/m/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 967 (uncaught exception) at /var/www/m/app/bundles/PluginBundle/Helper/oAuthHelper.php line 38 while running console command `mautic:social:monitoring` `

**Comment by Avocation** [comment] 2017-05-22 12:43
I have the same problem running v2.8.1 (php 5.6.30) but from the CRON job running social monitoring:

[2017-05-22 12:31:02] mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /home4/avocatio/public_html/www.amman.co.uk/erudition/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 967 and defined (uncaught exception) at /home4/avocatio/public_html/www.amman.co.uk/erudition/app/bundles/PluginBundle/Helper/oAuthHelper.php line 38 while running console command `mautic:social:monitoring` [] []

**Comment by robwent** [comment] 2017-05-23 17:28
This seems to be caused by this commit

https://github.com/mautic/mautic/commit/65f2f3702afbf719653f2ab0b5b64a4760a25cd4#diff-a0a366e0b3049551c32aa5bc22cca45e

If I revert to a version before that change then the social monitoring for twitter mentions works for me

**Comment by robwent** [comment] 2017-05-23 17:41
More specifically, it's the 2 defines here: https://github.com/mautic/mautic/blob/staging/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L167

    $this->session           = (!defined('IN_MAUTIC_CONSOLE')) ? $factory->getSession() : null;
    $this->request           = (!defined('IN_MAUTIC_CONSOLE')) ? $factory->getRequest() : null;

Changing them back to `MAUTIC_CONSOLE` makes the twitter monitoring work again. Just not sure if it will break anything else.

**Comment by robwent** [comment] 2017-05-23 17:53
Looking in the console file `IN_MAUTIC_CONSOLE` looks to be the right define to check if we are running a console command.
So the issue seems to be that line 168 is purposely nulling the request data for console commands, so when the cron runs there is no request to send on the line mentioned in the error message.

    $oauthHelper = new oAuthHelper($this, $this->request, $settings);

**Comment by Avocation** [comment] 2017-05-25 10:43
Hi @robwent 
Is there a workaround for this until a new release is issued?

**Comment by robwent** [comment] 2017-05-25 11:36
You can revert the changes I mentioned above and edit the defines lines back to `MAUTIC_CONSOLE`

Check the previous version of the file here: https://github.com/mautic/mautic/commit/665eeacf6a9a83147bf79bd6df369f88036c883b#diff-a0a366e0b3049551c32aa5bc22cca45e

Be careful to check that it doesn't stop something else from working as it should.

**Comment by escopecz** [comment] 2017-05-31 08:53
Fixed in #4176. Please test the change if you can and write the comment there.

**Comment by robwent** [comment] 2017-06-02 07:24
This seems to have broken again with the 2.8.2 release.

**Comment by escopecz** [comment] 2017-06-02 08:11
Is it the same error message? I fixed it for 2.8.2 and it worked for me. Please make sure the cache is cleared.

**Comment by robwent** [comment] 2017-06-02 08:24
Tried clearing cache. Error is:

     [Symfony\Component\Debug\Exception\FatalThrowableError]
      Type error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__
      construct() must be an instance of Symfony\Component\HttpFoundation\Request
      , null given, called in /srv/users/serverpilot/apps/marketing/public/app/bu
      ndles/PluginBundle/Integration/AbstractIntegration.php on line 1119

Looks like it might be something to do with the depreciation of `MauticFactory` as `$factory` is now NULL here: https://github.com/mautic/mautic/blob/staging/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L172

so the following is skipped and `$this->request` is not setup.

    $this->request           = $factory->getRequest();

Dumping `$this` after  `$this->init();` I get:

    object(MauticPlugin\MauticSocialBundle\Integration\TwitterIntegration)#725 (23) {
      ["persistNewLead":protected]=>
      bool(false)
      ["integrationHelper":protected]=>
      NULL
      ["coreIntegration":protected]=>
      bool(false)
      ["factory":protected]=>
      NULL
      ["dispatcher":protected]=>
      NULL
      ["settings":protected]=>
      NULL
      ["keys":protected]=>
      array(0) {
      }
      ["cache":protected]=>
      NULL
      ["em":protected]=>
      NULL
      ["session":protected]=>
      NULL
      ["request":protected]=>
      NULL
      ["router":protected]=>
      NULL
      ["logger":protected]=>
      NULL
      ["translator":protected]=>
      NULL
      ["encryptionHelper":protected]=>
      NULL
      ["leadModel":protected]=>
      NULL
      ["companyModel":protected]=>
      NULL
      ["pathsHelper":protected]=>
      NULL
      ["notificationModel":protected]=>
      NULL
      ["fieldModel":protected]=>
      NULL
      ["adminUsers":protected]=>
      NULL
      ["notifications":protected]=>
      array(0) {
      }
      ["lastIntegrationError":protected]=>
      NULL
    }

**Comment by robwent** [comment] 2017-06-02 08:53
The issue seems to come from a change in the SocialBundle.

If I replace the `/plugins/MauticSocialBundle` folder from 2.8.1 then social monitoring works again.

**Comment by billybobilly** [comment] 2017-06-04 13:45
Same problem here.  Does replacing MauticSocialBundle cause any other problems?

**Comment by robwent** [comment] 2017-06-04 13:55
@billybobilly not that I have seen on my test site, but I am only using the mentions functionality.
If it did break anything else it would probably be something within that bundle ie some other Twitter functionality.

**Comment by iwantaspeaker** [comment] 2017-06-06 15:01
Is this still broken as I am currently getting this cron response.

Executing Monitor Item 1

                                                                                                                                                                                                                                                                                                                     
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                                                                                                                          
  Catchable Fatal Error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /home/contactsiwantasp/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1119 and defined  
                                                                                                                                                                                                                                                                                                                     

mautic:social:monitoring [--mid [MID]] [--batch-size BATCH-SIZE] [--query-count [QUERY-COUNT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by VcDesigns** [comment] 2017-06-13 17:44
i have had this same problem since mautic went to version 2.8  and than 2.8.1 and than 2.8.2  before that it worked and i haven't been able to figure out why it worked before 2.8 and now after 2.8.   i even added two other crons to go with the  social:media:monitoring 

mautic:social:monitoring  

these worked before version 2.8 it actually helped this plugin work better. now nothing.

social:monitor:twitter:hashtags
social:monitor:twitter:mentions

I really hope this is fixed next update because they have said this would be fixed the past 2 updates and no changes.

**Comment by robwent** [comment] 2017-06-13 19:32
@VcDesigns 

It was fixed but clashed with another update.

To get it working you can replace the plugin files from version 2.8.1 as mentioned above.

**Comment by VcDesigns** [comment] 2017-06-13 19:45
i have done that and did nothing or i wouldn't have added a comment a work around isn't a fix that just causes problems someplace else. i rather have 1 error with something not working then end up with additional problems with more errors showing up.

**Comment by robwent** [comment] 2017-06-13 19:53
Obviously a workaround is not a fix, however, you can see that this issue has been reopened and that people are aware of the problem. Venting frustration here is neither constructive or helpful.

Social monitoring is a plugin so replacing the files will have minimal effect on other operations since it is self-contained code.
I have been using the 2.8.1 version on 3 updated sites for over a week and they are functioning fine other than a php warning.
Did you try clearing your cache after replacing the plugin files?

I spent hours last week trying to fix the problem, unfortunately, it's beyond my knowledge of Mautic.

**Comment by VcDesigns** [comment] 2017-06-13 20:27
im not venting anything you interpreted that yourself, i was giving my experience on how workarounds are that is all, i don't appreciate being accused of something i wasn't doing or implying.   I know how mautic works, i also code and develop, i was sent this link for this issue going on still that is all.  My mautic works perfectly well except this social thing with twitter.  i also know some others who have tried what you suggested and it hasn't worked.  Mautic isn't perfect and it differently doesn't run or work the same on every ones platform because everyone uses different resources making some things work and somethings not work. i'm not judging anyone and you have judged me for telling me i'm venting when that isn't the case at all.

**Comment by robwent** [comment] 2017-06-13 20:35
Fair enough, I apologise.

Maybe you can help fix it?

**Comment by robwent** [comment] 2017-06-28 20:33
Just tested on a 2.8.2 install with twitter monitoring set up.

After file changes I got the same error, then cleared cache and it worked without errors.

    Executing Monitor Item 1
    No new tweets
    Result Code: 0

**Closed** 2017-07-03 07:31 UTC
Labels: Bug, P0, Ready To Test

**Comment by spsingh** [comment] 2017-07-04 09:26
tried these changes and even after clearing cache had the same error.
