### ISSUE TITLE
Landing Page Builder Unresponsive

### ISSUE THREAD

**Issue by dr312** [mautic/mautic#9164] opened 2020-09-03 14:15 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3.21
| Browser | Chrome,Firefox & Safari

### Steps to reproduce
1. Go to Components > Landing Pages
2. Click New
3. Select Template
4. Apply or Save & Close
 Nothing. Error below

### Log errors
[2020-09-03 16:07:54] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to URLify::transliterate() must be of the type string, null given, called in /home/ugviscom/email/app/bundles/CoreBundle/Helper/InputHelper.php on line 516" at /home/ugviscom/email/vendor/jbroadway/urlify/URLify.php line 360 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to URLify::transliterate() must be of the type string, null given, called in /home/ugviscom/email/app/bundles/CoreBundle/Helper/InputHelper.php on line 516 at /home/ugviscom/email/vendor/jbroadway/urlify/URLify.php:360)"} []

![Errors](https://user-images.githubusercontent.com/13722045/92126343-bb6f3d00-ee08-11ea-8ccc-63f7c523629a.JPG)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment] 2020-09-04 19:27
There is a known issue with 3.0.1, 3.0.2 and 3.1 where the JS file that powers the editor crashes. Check here #9138

**Comment by npracht** [comment] 2020-09-07 12:21
duplicate of #9138

**Closed as completed by npracht** 2020-09-07 12:21 UTC
Labels: duplicate
