### ISSUE TITLE
500 Error when changing tag and save/close

### ISSUE THREAD

**Issue by CodeConnectPtyLtd** [mautic/mautic#12063] opened 2023-03-08 07:43 UTC
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Chrome

### What happened?

I’m receiving a 500 error saving a contact via the GUI…

I’ve created a quick screen share to demonstrate the issue I’m facing:

[https://streamable.com/b3jzax](https://streamable.com/b3jzax)

### How can we reproduce this issue?

Step 1:  Add contact
Step 2:  Add tag to contact
Step 3: Save
Step 4: Swap tag fpr a different tag
Step 5: Save & Close

This results in a 500 response from the server.  After this the contact cannot be viewed.  The view contact page then returns a 500 error.

### Relevant log output

```shell
There is nothing in the log related to the issue described.
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment] 2023-03-08 09:14
Hi there, thanks for reporting the issue. If a 500 error is being thrown there should be an entry in thy logs. Please can you check again, as that will point towards what the problem is. Thanks!

**Comment by CodeConnectPtyLtd** [comment] 2023-03-08 09:29
@RCheesley Hi Ruth... there's absolutely nothing in the logs except the following which looks to be just the attempted bounce checking every hour due to the cron job:

`[2023-03-07 23:00:02] mautic.NOTICE: Error: Call to undefined function Mautic\EmailBundle\MonitoredEmail\imap_search() (uncaught exception) at /home/mauticadmin/public_html/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 542 while running console command `mautic:email:fetch` [] {"hostname":"myserver.com","pid":641456}
[2023-03-07 23:00:02] mautic.WARNING: Command `mautic:email:fetch` exited with status code 1 [] {"hostname":"myserver.com","pid":641456}`

Happy to give you access if you like?

**Comment by CodeConnectPtyLtd** [comment] 2023-03-09 21:01
@RCheesley this one really has me puzzled and I would greatly appreciate some assistance.  There's literally nothing in the log file apart from the above errors.  Would you be able to spare a small amount of time to access the server as an admin.  Happy to give you FTP access so  that you can check the logs yourself as well. 

Graciously requesting assistance from the knowledge bank :)

**Comment by RCheesley** [comment] 2023-03-13 10:36
Thanks for the added info! That second 500 error should be putting something in the apache/nginx logs I would have thought, if not the Mautic logs.

Which actual version of Mautic are you using? Then we can check to see if we can reproduce.

You mentioned this is happening in the API as well - is it the same process that you are following?

**Comment by RCheesley** [comment] 2023-03-13 11:02
OK I have tested this on Mautic 4.4.7 using Gitpod and the error in the console is:

```
SyntaxError: Unexpected token '}', "}" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.processAjaxError (1.core.js?v86926218:600:41)
    at Object.error (6.forms.js?v86926218:253:20)
    at options.error (4b.jquery.form.js?v86926218:288:26)
    at fire (2.jquery.js?v86926218:3268:32)
    at Object.fireWith [as rejectWith] (2.jquery.js?v86926218:3398:8)
    at done (2.jquery.js?v86926218:9307:15)
    at XMLHttpRequest.<anonymous> (2.jquery.js?v86926218:9548:10)
```

Error in the logs is:

`[2023-03-13 10:57:47] mautic.ERROR: ErrorException: PHP Notice - Undefined offset: 1 - in file /var/www/html/app/bundles/LeadBundle/Views/Auditlog/details.html.php - at line 53  {"hostname":"mautic-web","pid":1997}`

I also tested this in the latest Mautic 5 branch using Gitpod, and the following error comes up in the logs so it seems like the issue (or a separate issue) persists with 5.x. cc @LordRembo @escopecz for visibility.

```
[2023-03-13 10:48:23] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Key "1" for array with keys "removed, added" does not exist." at /var/www/html/app/bundles/LeadBundle/Views/Auditlog/details.html.twig line 58 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"1\" for array with keys \"removed, added\" does not exist. at /var/www/html/app/bundles/LeadBundle/Views/Auditlog/details.html.twig:58)
[stacktrace]
#0 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(193): twig_get_attribute(Object(Twig\\Environment), Object(Twig\\Source), Array, 1, Array, 'array', false, false, false, 58)
#1 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7f1694296debb31c0e47eda062a2f18ec6fcbb32bd63b2a184cb8d7eb556de31->doDisplay(Array, Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
#4 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1323): Twig\\TemplateWrapper->render(Array)
#6 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(320): twig_include(Object(Twig\\Environment), Array, Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_1e6ae385bdf13eacb950614ad43cef188abe6e1dc3558d45e6ec5773377e54e5->doDisplay(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
#10 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1323): Twig\\TemplateWrapper->render(Array)
#12 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(714): twig_include(Object(Twig\\Environment), Array, 'MauticLeadBundl...', Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_59a48a234d9ae469475402bfbbf3740f4ee9b671283097bc6023cccac4a2870b->block_content(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(243): Twig\\Template->displayBlock('content', Array, Array, true)
#15 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(66): Twig\\Template->renderBlock('content', Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9e78e08f70d834378e63126dc4836f107ec7324bd4daa2c44a703680d4af21a6->doDisplay(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(72): Twig\\Template->display(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_59a48a234d9ae469475402bfbbf3740f4ee9b671283097bc6023cccac4a2870b->doDisplay(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
#22 /var/www/html/vendor/symfony/twig-bridge/TwigEngine.php(54): Twig\\Template->render(Array)
#23 /var/www/html/vendor/symfony/templating/DelegatingEngine.php(41): Symfony\\Bridge\\Twig\\TwigEngine->render('MauticLeadBundl...', Array)
#24 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(233): Symfony\\Component\\Templating\\DelegatingEngine->render('MauticLeadBundl...', Array)
#25 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(222): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->render('MauticLeadBundl...', Array, Object(Symfony\\Component\\HttpFoundation\\Response))
#26 /var/www/html/app/bundles/LeadBundle/Controller/LeadController.php(420): Mautic\\CoreBundle\\Controller\\CommonController->delegateView(Array)
#27 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(169): Mautic\\LeadBundle\\Controller\\LeadController->viewAction('55')
#28 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#29 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(96): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#30 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(371): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->forward('Mautic\\\\LeadBund...', Array, Array)
#31 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(301): Mautic\\CoreBundle\\Controller\\CommonController->ajaxAction(Array)
#32 /var/www/html/app/bundles/LeadBundle/Controller/LeadController.php(745): Mautic\\CoreBundle\\Controller\\CommonController->postActionRedirect(Array)
#33 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\LeadBundle\\Controller\\LeadController->editAction('55', '')
#34 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(169): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', '55', 0, '')
#35 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#36 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#37 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#38 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#39 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#40 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#41 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#42 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#43 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#44 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#45 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#46 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#47 {main}
"} {"hostname":"mautic-web","pid":2008}
```

**Comment by CodeConnectPtyLtd** [comment] 2023-03-13 22:43
> Thanks for the added info! That second 500 error should be putting something in the apache/nginx logs I would have thought, if not the Mautic logs.
> 
> Which actual version of Mautic are you using? Then we can check to see if we can reproduce.
> 
> You mentioned this is happening in the API as well - is it the same process that you are following?

Hi Ruth... yes.  When swapping tags in the API I'm getting the same error.

Below are the 2 successive calls to the API to update the contact.  Both calls succeed according the to API response code.

`(
    [wp_user_id] => 1463985
    [email] => mauticfailedsub7@emaildomain.com
    [firstname] => 
    [lastname] => 
    [dateregistered] => 2023-03-07 01:19:11
    [last_login_time] => 2023-03-07 01:03:19
    [communications_opt_in] => 1
    [user_occupation] => Podcaster
    [membership_status] => 
    [membership_level] => 13
    [membership_start_date] => 2023-03-07 01:03:19
    [expiration_date] => 
    [phone] => 
    [card_type] => 
    [last_paypalexpress_ipn_id] => 
    [tags] => Array
        (
            [0] => -Membership Payment Failed
            [1] => Basic User
            [2] => -Monthly Gold Subscriber
            [3] => -Yearly Gold Subscriber
            [4] => -Sub Account
            [5] => -Membership Expired
            [6] => -Membership Cancellation Pending
            [7] => -Membership Cancelled
        )

)`


`(
    [wp_user_id] => 1463985
    [email] => mauticfailedsub7@emaildomain.com
    [firstname] => Bon
    [lastname] => Jones
    [dateregistered] => 2023-03-07 01:19:11
    [last_login_time] => 2023-03-07 01:03:19
    [communications_opt_in] => 1
    [user_occupation] => Podcaster
    [membership_status] => 
    [membership_level] => 1
    [membership_start_date] => 2023-03-07 01:03:24
    [expiration_date] => 
    [phone] => 0431111111
    [card_type] => 
    [last_paypalexpress_ipn_id] => 
    [tags] => Array
        (
            [0] => -Membership Payment Failed
            [1] => Monthly Gold Subscriber
            [2] => -Basic User
            [3] => -Membership Expired
            [4] => -Membership Cancellation Pending
            [5] => -Membership Cancelled
        )

)`

**Comment by CodeConnectPtyLtd** [comment] 2023-03-21 22:04
@RCheesley Is there anything I can do at this point?  This has caused my project to come to a complete halt.  Is there any fix that I can implement to allow me to move forward?

**Comment by LordRembo** [comment] 2023-03-21 22:18
Going by the error, I'm guessing the `values` variable that is being checked at rule 55 and below, in the template `app/bundles/LeadBundle/Views/Auditlog/details.html.twig`, isn't formatted as expected (the array indexes are messed up perhaps?).
~~As a dirty fix or a patch, you could try to replace `{% if values|length >= 2 %}` with a check that looks at the indexes
For example: `{% if values[0] is defined and values[1] is defined %}`.
It won't fix the underlying problem (eg. why `values` doesn't have 0 and 1 indexes) but it'll at least skip by the offending bit in the template and load the page.~~

**Comment by LordRembo** [comment] 2023-03-21 22:26
I'm also not sure that the `is string` check (at rules 58 and 59) actually exists in Twig.
It might be better to replace that with `is not iterable` (checks it's not an array or traversable object):
[https://twig.symfony.com/doc/3.x/tests/iterable.html](https://twig.symfony.com/doc/3.x/tests/iterable.html)

**Comment by LordRembo** [comment] 2023-03-22 14:47
I've made a pull request with a fix for this (version 4.x): https://github.com/mautic/mautic/pull/12105
Basically, the data in the contact audit log isn't always an array with indexes for keys, sometimes it's an object (named keys). The fix is to check for that.

I'll make a separate one for mautic 5.x as well.

If you want to patch the solution yourself, it's 1 change: https://github.com/mautic/mautic/pull/12105/files

EDIT: just noticed that bit of code needs to be replaced twice. Further down the page, there's another instance where the values array is checked.

**Comment by LordRembo** [comment] 2023-03-22 15:30
Pull request for version 5.x: https://github.com/mautic/mautic/pull/12106

**Comment by CodeConnectPtyLtd** [comment] 2023-03-22 21:01
@LordRembo thx so much for this.... I'll test this change when I get a chance :)

**Comment by RCheesley** [comment] 2023-03-31 10:27
Thanks @LordRembo for making the PRs!

**Closed as completed** 2023-04-17 08:24 UTC
Labels: T1, bug, tags
