### ISSUE TITLE
Configuration error 2.5.1.

### ISSUE THREAD

**Issue by Aneta09** [mautic/mautic#3248] opened 2017-01-14 15:24 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
php 5.6
Mautic 2.5.1

When I am trying to change configuration (language, time zone, etc) systems doesn't save the change for every set. When I go out from configuration the setting resets to default. I deleted catch, I instaled cronfig so my cronfig are ok.  My hosting tells server is ok, they send me log-report (no errors) - but system still doesn't work. 

I created  user:
1. Login: Mautic
2. Password: Mautic
3. Link: www.siutcrm.warw.ayz.pl 

What is wrong? Sorry for my bad English... 

Please help I  x

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  5.6
| PHP version | 2.5.1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

[strace.txt](https://github.com/mautic/mautic/files/706019/strace.txt)

**Comment by corradofiore** [comment] 2017-01-16 09:06
Hi All,

I can confirm the problem.  Preferences are not being written to the local.php configuration file when you hit "save and close" or "apply".

_Steps to reproduce:_

1.  Go to the preferences page in Mautic, i.e. `/s/config/edit`
2.  Select one of the vertical tabs, e.g. "email configuration"
3.  Change the value of one of the preferences' fields
4.  Hit either "Save and close" or "Apply"
5.  Reload the page in your browser:  Mautic will show the old value because the `/app/config/local.php` file wasn't modified.

Both the app log and the php logs do not show anything relevant.

_System config:_

PHP 7.0.14 (cli) (built: Dec  7 2016 10:15:15) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14, Copyright (c) 1999-2016, by Zend Technologies

I'm using PHP-FPM with nginx 1.10.2

Cheers
Corrado

**Comment by MxyzptlkFishStix** [comment] 2017-01-17 09:12
Fill in the Name, First Name & Last Name under Configuration, User/Authentication Settings.  I've already done it for you.  Just be sure to change your login/pass details.

**Comment by ttmubarak** [comment] 2017-01-17 11:39
I have the same issue, Please tell us how to update that or resolve this problem

Thank you

**Comment by MxyzptlkFishStix** [comment] 2017-01-17 20:33
@ttmubarak
I just did.

**Comment by ttmubarak** [comment] 2017-01-18 04:10
Please tell , how to resolve that problem

**Comment by escopecz** [comment] 2017-02-16 14:00
This was fixed in 2.6.0

**Closed by escopecz** 2017-02-16 14:00 UTC
