### ISSUE TITLE
Cannot Save API Key for SparkPost/SendGrid

### ISSUE THREAD

**Issue by zachary-russell** [mautic/mautic#6497] opened 2018-08-27 18:54 UTC
What type of report is this:
Bug report?

## Description:
I am trying to enter an API key to be able to send mail through an external service (tried SparkPost and SendGrid because I have accounts with them). I am unable to save my API key so I can't send email. When I click "test" it says "connection successful. I tried clearing caches just in case.

OS Ubuntu 18.04
Mautic version 2.14.0
PHP version 7.1.20

### Steps to reproduce:
1. Go to Configuration > Email Settings
2. Select SparkPost or Sendgrid, enter API key, click Save & Close or Apply Changes
3. Go back to Configuration > Email Setting screen and key is gone
 
### Log errors: 

Logs are empty. I had an MCRYPT issue before, but I just needed to install the extension. After that it's empty.

**Comment by npracht** [comment] 2018-08-29 07:31
Hello @zachary-russell ,

I cannot reproduce. Do you have an error in the browser console ?

**Comment by escopecz** [comment] 2018-10-18 11:56
Closing as there was no answer for some time.

**Closed by escopecz** 2018-10-18 11:56 UTC
Labels: Pending Feedback
