### ISSUE TITLE
Webhooks and Social tabs in Config not working if FR language

### ISSUE THREAD

**Issue by acsfer** [mautic/mautic#7187] opened 2019-01-30 15:56 UTC
| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.13
| Browser | Firefox@latest

### Steps to reproduce
1. Switch to French (**not tested** with other languages)
2. Go to `Configuration `
3. Click on `Webhooks` or `Social` tab. Nothing shows. Those areas are added at the bottom of the actual right panel instead of opening a dedicated area for configuration of those.

To better understand this behavior, first click on `SMS` tab, then `Webhooks` or `Social` tab.

![image](https://user-images.githubusercontent.com/12234510/51994594-6b542a00-24b1-11e9-8925-b56a3227aa39.png)

**Comment by npracht** [comment] 2019-02-04 10:02
Could you please test other languages ? I guess it is an issue in the forms not related to languages.

**Comment by acs-ferreira** [comment] 2019-02-05 11:08
Tried with Portuguese (PT) and English (US), can't reproduce. Only with FR.

**Comment by npracht** [comment] 2020-07-17 15:09
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment] 2020-08-16 09:54
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Closed by npracht** 2020-08-16 09:54 UTC
Labels: bug, triage-mautic-3, user-interface
