### ISSUE TITLE
Campaign action based on click of a specific email link

### ISSUE THREAD

**Issue by marziovit** [mautic/mautic#3056] opened 2016-12-05 22:57 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Imagine this scenario: you send out an email with a link to a page where you sell your product/service. A contact clicks on that link and you add him to a campaign with three emails that sells him on the benefits of your product/service.

Right now to achieve this you would need to install the tracking script on your site and construct the campaign using the "visits page" condition. Wouldn't be easier to just use the link clicks informations that Mautic is already collecting about how clicks / unique clicks each link received in an email?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment] 2017-01-02 10:17
This seems to be duplicate of https://github.com/mautic/mautic/issues/1126

**Closed by escopecz** 2017-01-02 10:17 UTC
