### ISSUE TITLE
Rejoining to continue a campain after leaving Mid campaign - recuring times conditions OR condition to run once per result

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#2931] opened 2016-11-11 17:21 UTC
| Enhancement? |  Bug?

## Description:
At the moment, we have a campaign that sends series of emails. If a user haven't opened a couple, he is moved to a follow up campaign that nurture him. When he is nurtures, we move him back to the main campaign in hope that he should follow the condition where he left. However because that condition ran before where its result was Negative and action was move to campaign, when the user is readded, that condition never run. 

What should happen is that the condition should run still and follow normal pattern. OR the condition to run and only if the result is positive, that it continues.

Its very difficult to rejoin anyone to a campaign at the moment. I think it would be logical that all conditions run even if they ran before given that its a condition to allow the user to funnel where they were. OR Another suggession, perhaps to add conditions that run every 1 day for example? so they could be branched (not connected to the header) where they run once a day to check leads that have match specific criteria..

**Comment by escopecz** [comment] 2017-03-06 08:58
This seems like a duplicate of https://github.com/mautic/mautic/issues/1606

**Closed by escopecz** 2017-03-06 08:58 UTC
