### ISSUE TITLE
[FEATURE REQUEST] Account Based Marketing > Add ISP name to lead profile and list filters

### ISSUE THREAD

**Issue by inseti** [mautic/mautic#1443] opened 2016-02-17 11:23 UTC
In order to start using Mautic for Account Based Marketing it will be awesome to be able to identify a lead by its ISP.

I've noticed that the ISP info exists in the database for each lead, so probably it may be relatively easy to attach that info in a lead field and be able to filter leads by ISP.

**Comment by npracht** [comment] 2016-02-29 09:12
Duplicate ? https://github.com/mautic/mautic/issues/1164

**Comment by dongilbert** [comment] 2016-03-02 04:08
Yes, duplicate of #1164. Closing this one.

@inseti looks like if you use a paid IP provider lookup service, you'll be able to fetch this information. There's a discussion about it at the issue I linked above.

**Closed by dongilbert** 2016-03-02 04:08 UTC
