### ISSUE TITLE
Segment-Mails are forced into email queue, even if queueing is not set up

### ISSUE THREAD

**Issue by LeonOltmanns** [mautic/mautic#10275] opened 2021-07-20 07:42 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Bug occurred while testing out Segment-Emailing. 

Once I am asked to send out the Segment-Mail, I have to accept that the Mail will be queued. I can only accept that or cancel sending entirely. Issue is, I have not set up my Mautic to use email-queue, instead I am using the "send immediatley" option, resulting in the forced queued Segment-Email never being send out and stuck in queue. 

![Screenshot v4000rc 1](https://user-images.githubusercontent.com/55587275/126279486-45531e09-08af-40dc-b6a2-d795acf7feaa.png)

Even worse is, I cannot access email-queue per CLI and force them to send out this way. I am getting an error stating, that email-queue is not set up.

![Screenshot at Jul 20 09-11-50](https://user-images.githubusercontent.com/55587275/126279751-4b5a0765-081e-4145-99ca-e014f758a2b3.png)

| Q   | A
| --- | ---
| Mautic version | v4.0.0rc
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Go to Configuration - Email Settings
2. Set Email-Send method to "Send immediately"
2. Create a test-segment
2. Push a test-contact into that segment
3. Create a Segment-Mail
4. Send the Segment-Mail to the test-segment 
5. See that you have to Queue the Mail 
6. Mail gets stuck in a not-setup Queue

### Log errors
No errors are logged. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dennisameling** [comment] 2021-07-21 10:20
@oltmanns-leuchtfeuer I wasn't able to reproduce this issue by following the steps you indicated.

![image](https://user-images.githubusercontent.com/17739158/126473383-5bc17f50-cdab-4eaf-b444-2e2d80501337.png)

The email gets sent correctly without ending up in the queue:

![image](https://user-images.githubusercontent.com/17739158/126473433-560992fa-d6db-42fc-9644-f2f3fb78d3e0.png)

![image](https://user-images.githubusercontent.com/17739158/126473484-ae4cd5d0-3575-4745-b7ff-0db886500a0d.png)

Just to confirm, you mean this field in the settings, right?

![image](https://user-images.githubusercontent.com/17739158/126473575-2f3649ea-09c1-487f-a997-c9e5131b9a49.png)

**Comment by LeonOltmanns** [comment] 2021-07-21 10:53
@dennisameling How strange. As soon as I want to send out the Test-Segment Mail this Windows pops up: 

![image](https://user-images.githubusercontent.com/55587275/126477061-6f6f17d7-bda7-4474-ac2e-dd8428babe30.png)

I can only put the Mail into Queue or just cancel it. 
Double checked for my configuration, got queueing disabled:

![image](https://user-images.githubusercontent.com/55587275/126477192-49b7cbe7-8457-45d2-bad8-aafb7b9ade82.png)

But I wasnt able to reproduce it on another system that is running 4.0.0.rc, so maybe it is just my one instance having issues. 

I will close this Issue for now and once other users are encountering the same bug, we can dig further into it. :) Thanks for your testing tho!

**Comment by RCheesley** [comment] 2021-07-21 10:56
I think this is a UX thing. What that means is not 'put these emails into the queue' but 'send these emails'. If there is a queue, they go into the queue. If there is not, they are sent directly.

I have seen the emails getting stuck if you have already sent to the segment and therefore have exceeded the 'send x emails per y timeperiod' limit - usually that can be seen in the contact activity log with a warning to that effect though.

**Comment by LeonOltmanns** [comment] 2021-07-21 11:01
It is not only UX, provided in my first Part of this issue yesterday, the Email got indeed put into the email-queue and was never send out, in fact, it is still pending. :D 

![image](https://user-images.githubusercontent.com/55587275/126478396-332e6778-61e9-42ab-b89e-2300b06ff20c.png)



And I made that Segment and Test-contact for that single time use, so "send x emails per timeperiod" shouldnt be an issue. 

But like stated above, I hope this is just a single occurrance on my instance and if others wont be able to reproduce it I wont be sad at all! :)

**Comment by RCheesley** [comment] 2021-07-21 11:05
OK - worth keeping in mind in case we are able to replicate it again!  Thanks for reporting!

**Comment by RCheesley** [comment] 2021-08-22 13:56
I am going to re-open this as I have had this come up locally when testing PRs.

1. Check your global config to ensure you have nothing set for the frequency rule globally (under Email settings)
2. Check the contact preference settings in a segment (eg United States in the sample data) to ensure that contacts have not got anything set in their frequency (sample data should be empty for all)
3. Send email to segment (eg United States on the sample data)
4. Clone the email, and send to the same segment

Expected behaviour: As there is nothing set globally or locally to provide a preference for frequency of mailings, the email should be sent.

Actual behaviour: The second email will have all the contacts set in the 'queued' state. According to the docs, we should be able to clear the queue if the frequency rules have passed using the command bin/console mautic:messages:send but this does not clear the queue.

**Comment by RCheesley** [comment] 2021-08-22 15:10
Additional note: This seems to be an issue sometimes with this PR applied: https://github.com/mautic/mautic/pull/10114 - any chance you happened to be testing that PR at the time @oltmanns-leuchtfeuer ?

It does not happen for me (unless there is a frequency rule on the contact) with the features branch.

**Comment by RCheesley** [comment] 2021-08-23 15:58
![screenshot-mautic4 ddev site-2021 08 23-16_49_43](https://user-images.githubusercontent.com/2930593/130478078-47cfcf64-382d-4d92-a8d7-253c7c10a6b4.png)

In the screenshot attached:

Blue: Initial email sent
Red: Cloned email sent - all are queued
Green: I manually set one contact to have a 10 emails/day limit, the subsequent emails were sent only to that user

My global settings are the Mautic default settings on a fresh installation on the Features branch.

**Comment by mollux** [comment] 2022-01-13 15:19
Due to a bug (see PR #10753) the `0` was not taken into account.
The way we mitigated this before the patch was by clearing the `messages each` field, as that is the only field taken into account.

**Comment by mollux** [comment] 2022-01-18 11:06
@RCheesley see the comment above, I found what's causing this and added a PR to fix it.

**Comment by RCheesley** [comment] 2022-01-18 11:35
Awesome, thanks @mollux !

**Comment by RCheesley** [comment] 2022-01-25 12:37
Resolved with #10753

**Closed as completed by RCheesley** 2022-01-25 12:37 UTC
Labels: bug, email, configuration, contacts
