### ISSUE TITLE
DB migration error after updating from 4.4.10 to 5.0.3

### ISSUE THREAD

**Issue by ldrolez** [mautic/mautic#13559] opened 2024-03-20 08:47 UTC
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What happened?

The migration fails
```
mautic.WARNING: Command `doctrine:migrations:migrate` exited with status code 255 []
mautic.ERROR: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 4025 CONSTRAINT `emails.headers` failed for `mautic`.`emails` (uncaught exception) at /www/mautic/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 117 while running console command `doctrine:migrations:migrate`
```

### How can we reproduce this issue?

Step 1: get a 10 years old mautic install :)
Step 2: do all the major upgrades up to 5.0.x

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment] 2024-04-13 00:06
@ldrolez thats not really a qualified bug now. I know its a pain and experienced it myself with our old database - but managed it step by steps with researching the issue and migrating the database - only partly documented unfortunately (https://twzn.de/9p3d9).

Its more of a maintenance issue now. You may start to discuss it in the forum and fine help from other community members?

As we can't recreate the issue here and its not happening with current versions, I'm going to close the issue for now. We can reopen it, if the bug can be recreated and the issue is documented in detail.

**Closed as not planned by dsp76** 2024-04-13 00:06 UTC
Labels: pending-feedback
