### ISSUE TITLE
[Feature request] Add non-campaign options for synchronising with integrations

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#3205] opened 2017-01-08 12:30 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
The growing range and scope of integrations is really great to see, however at present it seems only possible to trigger synchronising contacts through a campaign action (from what I've seen, but please do put me right if that's not the case!).

Some of the integrations with CRM's would necessitate an update whenever a contact is updated, and sometimes may need to allow manual pushing of contacts who haven't triggered any of the campaign actions.

I propose:

**Supporting automatic pushing to integrations on contact updates**
An option for integrations which listens for contact updates and automatically synchronises those changes.

**Supporting manual push to integration for individual contacts**
Adding a dropdown to the context menu for a contact which says 'Push to integration'.  

![context-menu-contact-record](https://cloud.githubusercontent.com/assets/2930593/21749774/f06e9280-d59d-11e6-97a7-b3d921d5effe.png)

The next action would be a popup to choose which integration (in the case where there might be multiple).  Maybe from a UX perspective a multi-select would be useful, it might be a bit inconvenient to have to repeat the process multiple times (but totally understand that it might be programmatically easier to do one at a time).

**Comment by merlin0** [comment] 2017-01-10 11:20
+1

**Comment by dongilbert** [comment] 2017-01-10 13:22
I like the idea of manual push, and an event listener that pushes on contact update. Both solid choices. They would take some setup to implement, but I think it's a reasonable request.

In the mean time, there are a couple ways outside of the campaign builder to push a contact to an integration. These include Form Actions and Point Actions. You can opt to push directly to an integration as a result of point adjustments, or as a result of a form submission.

**Comment by RCheesley** [comment] 2017-01-16 10:44
Sure but what if you have someone just added directly as a contact or imported - that's the kind of scenario I was meaning :)  But yes, they are indeed workarounds :)

**Comment by mqueme** [comment] 2017-09-27 08:14
duplicate of https://github.com/mautic/mautic/issues/1086 so closing

**Closed by mqueme** 2017-09-27 08:14 UTC
Labels: Feature Request
