### ISSUE TITLE
Registration webinair

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#3666] opened 2017-03-14 10:55 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | mauticError=Errors
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.7.1
| PHP version | 5.6.30-0+deb8u1

### Steps to reproduce:
1. try to subscribe to webinar with form mautic 
2. 
 
### Log errors: 

https://www.xxxxxxxxxxxxxxxxx.com/formulaire-webiniare/?mauticError=Errors%3A%3Cbr%20%2F%3E%3Col%3E%3Cli%3EBad%20request%3C%2Fli%3E%3C%2Fol%3E#test

**Comment by escopecz** [comment] 2017-03-14 11:04
This seems like a duplicate of https://github.com/mautic/mautic/issues/3602

**Closed by escopecz** 2017-03-14 11:04 UTC
