### ISSUE TITLE
Return-path and bounce when using SMTP

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#1917] opened 2016-06-28 15:48 UTC
## Description

When using SMTP server and sending a mail from mymail@myserver.com, the Return-path generated in the email is mymail+bounce_6497489486546@myserver.com.

If my email server is not configured to accept this email, i can't receive bounce. I didn't see anything in the documentation about this

**Comment by escopecz** [comment] 2016-08-17 12:53
Duplicate of https://github.com/mautic/mautic/issues/1540

**Closed by escopecz** 2016-08-17 12:53 UTC
