### ISSUE TITLE
Enhancement: Missing number of contacts (items) information

### ISSUE THREAD

**Issue by grunf1a** [mautic/mautic#2743] opened 2016-10-13 14:36 UTC
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? | Y |
## Description:

In contacts grid view I am missing number of items (contacts). This is also important when I write search condition (in filter)  and i would like to see number of hits matching this criteria. 
Other thing is number of pages. There are visible first 4 pages i have  no clue how many pages are behind in this query till i press last page button.

Probably similar functionality is needed  in companies section.

**Comment by escopecz** [comment] 2017-02-03 21:09
Duplicate of https://github.com/mautic/mautic/issues/1501 and will be implemented in 2.6.0

**Closed by escopecz** 2017-02-03 21:09 UTC
