### ISSUE TITLE
Salesforce integration - Sync record type

### ISSUE THREAD

**Issue by beloa-fr** [mautic/mautic#7778] opened 2019-08-08 23:10 UTC
As record types set different business processes, Mautic would be able to send a specific field to set the salesforce record type. So the list of salesforce fields in the salesforce plugin should include it.

**Comment by escopecz** [comment] 2019-08-15 08:52
What's the issue again? I'll close this issue. Please create a new one with clear description of what the issue is and provide the whole info that was requested in the issue template.

**Closed by escopecz** 2019-08-15 08:52 UTC

**Comment by beloa-fr** [comment] 2019-08-15 09:49
OK done: https://github.com/mautic/mautic/issues/7797
