### ISSUE TITLE
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator. System administrators, check server logs for errors.

### ISSUE THREAD

**Issue by xmthx** [mautic/mautic#7632] opened 2019-06-20 19:19 UTC
#  Bug Description
After upgrade my server version (Plesk Onyx with debian) I have recreated the domain and database with all the same DB, Users and Password, but mautic show this: 

The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator. System administrators, check server logs for errors.

All the necessary php modules are Active and work about pdo, pdo_mysql etc etc.

![Php Setting Screenshot](https://user-images.githubusercontent.com/5032257/59876177-30d92400-93a3-11e9-85e6-5a83951a6982.png)

| Q   | A
| --- | ---
| Mautic version |  Last
| PHP version | 7.2.19
| Browser | Tested with all Browser
| Server | Plesk Onyx Version 17.8.11 - Debian 9.9

### Steps to reproduce
I have change the server. My previous server version was in CENTOS, now is DEBIAN whit the last version of Plesk Onyx.

I have made Backup of FTP and MySQL, and i have recreate the main domain and the sub domain where MAUTIC are on the root directory sub.mysite.ext.

I have reused same DB Name, DB user and Password, and the DB address is always localhost on port 3306.

I have try to cancel the Cache, but nothing.
I have try to set the right permission by console:
cd /var/www/vhost/thisismywebsite.ext/mautic.thisismywebsite.ext/
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
chmod -R g+w app/cache/
chmod -R g+w app/logs/
chmod -R g+w app/config/
chmod -R g+w media/files/
chmod -R g+w media/images/
chmod -R g+w translations/

but again don't work

On my new server i have a new version of MySQL, 10.1.38-MariaDB-0+deb9u1 Debian 9.8
On my previous version MySql version was 5.5.60-MariaDB

### Log errors
`[2019-06-21 11:02:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'UPDATE users SET online_status = ? WHERE last_active <= ?' with params ["offline", "2019-06-21 08:47:29"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist" at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'UPDATE users SET online_status = ? WHERE last_active <= ?' with params [\"offline\", \"2019-06-21 08:47:29\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-06-21 11:02:29] mautic.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'UPDATE users SET online_status = ? WHERE last_active <= ?' with params ["offline", "2019-06-21 08:47:29"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'UPDATE users SET online_status = ? WHERE last_active <= ?' with params [\"offline\", \"2019-06-21 08:47:29\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mmautic.users' doesn't exist at /var/www/vhosts/thisismysite.ext/mautic.thisismysite.ext/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2019-06-21 11:02:29] mautic.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'UPDATE users SET online_status = ? WHERE last_active  [] []`

Please can help me?
Sorry for Bad English

**Comment by mightyfree** [comment] 2019-06-25 02:22
Focus on the errors.  The issue is, the users table doesn't exist, or cannot be located. Check your database to confirm this table exists, and your database settings in the configuration file. Ensure your database connection details and database prefix are properly set.

**Comment by autoize** [comment] 2019-07-05 10:50
Were you able to solve the issue? 
It seems like the MySQL database was not completely migrated when you moved the server.
If you still need assistance, email us at info@autoize.com and our support team can help.

**Comment by RCheesley** [comment] 2019-11-05 21:02
Closing as not a bug with Mautic.

**Closed by RCheesley** 2019-11-05 21:02 UTC
