### ISSUE TITLE
SugarCrm Integration Sync Command throwing undefined index notices

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#5442] opened 2017-12-12 21:22 UTC
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X |
## Description:

```
user@server:~$ ./app/console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="16 hours"
Command to fetch contacts from integration
Fetch contacts command is starting

Number of leads/contacts fetched: 6

Updating/creating leads from Mautic to Sugarcrm
PHP Notice:  Undefined index: ids in /srv/mautic/plugins/MauticCrmBundle/Api/SugarcrmApi.php on line 235
PHP Notice:  Undefined index: ids in /srv/mautic/plugins/MauticCrmBundle/Api/SugarcrmApi.php on line 235
PHP Notice:  Undefined index: ids in /srv/mautic//plugins/MauticCrmBundle/Api/SugarcrmApi.php on line 235
PHP Notice:  Undefined index: ids in /srv/mautic//plugins/MauticCrmBundle/Api/SugarcrmApi.php on line 235
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 5.6
| SuiteCrm | 7.9.7

### Steps to reproduce:
1. Run Command `./app/console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="16 hours"`

**Comment by npracht** [comment] 2020-07-07 13:03
I'll close the issue, i'm using this integration and it works properly with all pending PR related to sugar. Also the issue is very old probably not relevant anymore.

**Closed by npracht** 2020-07-07 13:03 UTC
Labels: Bug
