### ISSUE TITLE
Database prefix not taken into account during set-up on 4.0-RC

### ISSUE THREAD

**Issue by jonathandhn** [mautic/mautic#10311] opened 2021-08-01 13:22 UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Database prefix are not taken into account on the web install helper, going through without setting custom prefix is working.

| Q   | A
| --- | ---
| Mautic version | 4.0-rc
| PHP version | 7.4
| Browser | Safari 14

### Steps to reproduce
1. Download Mautic 4.0-rc OR composer install Mautic 4.0-rc
2. Open the Mautic installer on your browser
3. Set up every things and go to database management while using the installer 
4. Add a custom prefix to install Mautic 4.0-rc and try starting install
 
### Log errors
none

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment] 2021-08-09 16:59
Closing as a duplicate of an existing issue - see https://github.com/mautic/mautic/pull/9934

**Closed as completed by RCheesley** 2021-08-09 16:59 UTC
Labels: needs-triage
